-- EXPLAIN (VERBOSE) over an INSERT into a table with an identity column
-- deparses the rewriter-added NextValueExpr (unported-panic audit A2:
-- get_rule_expr's T_NextValueExpr arm was the only missing deparse tag vs
-- C's case list, so this panicked instead of rendering C's
-- nextval('seqname') form, ruleutils.c).
CREATE TABLE identity_expl (id int GENERATED ALWAYS AS IDENTITY, x int);
EXPLAIN (VERBOSE, COSTS OFF) INSERT INTO identity_expl(x) VALUES (1);
-- BY DEFAULT identity rides the same NextValueExpr node
CREATE TABLE identity_expl_bd (id bigint GENERATED BY DEFAULT AS IDENTITY, x int);
EXPLAIN (VERBOSE, COSTS OFF) INSERT INTO identity_expl_bd(x) SELECT x FROM identity_expl;
-- the statements still execute after being EXPLAINed
INSERT INTO identity_expl(x) VALUES (1);
SELECT id, x FROM identity_expl;
DROP TABLE identity_expl_bd;
DROP TABLE identity_expl;
