// ALTER SYSTEM — AlterSystemSetConfigFile (guc.c:4607) plus its helpers
// write_auto_conf_file (guc.c:4469) and replace_auto_config_value (guc.c:4537).

use std::cmp::Ordering;
use std::io::Write;
use std::os::fd::FromRawFd;

use elog::ereport;
use guc::name::guc_name_compare;
use guc_file::{ConfigVariable, ParseConfigFp, CONF_FILE_START_DEPTH};
use types_error::{
    PgError, PgResult, ERRCODE_CANT_CHANGE_RUNTIME_PARAM, ERRCODE_CONFIG_FILE_ERROR,
    ERRCODE_FEATURE_NOT_SUPPORTED, ERRCODE_INSUFFICIENT_PRIVILEGE,
    ERRCODE_INVALID_PARAMETER_VALUE, ERROR, LOG,
};
use types_guc::{GUC_DISALLOW_IN_AUTO_FILE, GUC_DISALLOW_IN_FILE, PGC_INTERNAL, PGC_S_FILE};
use types_nodes::parsenodes::{AlterSystemStmt, VariableSetKind, ACL_ALTER_SYSTEM};

use crate::ExtractSetVariableArgs;

// PG_AUTOCONF_FILENAME (utils/conffiles.h).
const PG_AUTOCONF_FILENAME: &str = "postgresql.auto.conf";
// AutoFile (storage/lwlocklist.h index 35).
const AUTO_FILE_LOCK: usize = 35;
const ACLCHECK_OK: i32 = 0;

// escape_single_quotes_ascii (src/port/quotes.c): double single quotes and
// backslashes (config-file strings treat backslash as an escape).
fn escape_single_quotes_ascii(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    for c in src.chars() {
        if c == '\'' || c == '\\' {
            out.push(c);
        }
        out.push(c);
    }
    out
}

// replace_auto_config_value (guc.c:4537): remove any existing entry (or
// entries — external tools may add duplicates) for "name", then, unless
// value is None (a deletion), append a fresh entry at the tail.
fn replace_auto_config_value(list: &mut Vec<ConfigVariable>, name: &str, value: Option<&str>) {
    list.retain(|item| match &item.name {
        Some(item_name) => guc_name_compare(item_name, name) != Ordering::Equal,
        None => true,
    });
    let Some(value) = value else {
        return;
    };
    list.push(ConfigVariable::setting(
        name.to_string(),
        value.to_string(),
        std::path::PathBuf::new(),
        0,
    ));
}

// write_auto_conf_file's buffer (guc.c:4469): warning header plus one
// name = 'value' line per entry.
fn render_auto_conf_file(list: &[ConfigVariable]) -> String {
    let mut buf = String::new();
    buf.push_str("# Do not edit this file manually!\n");
    buf.push_str("# It will be overwritten by the ALTER SYSTEM command.\n");
    for item in list {
        let (Some(name), Some(value)) = (&item.name, &item.value) else {
            continue;
        };
        buf.push_str(name);
        buf.push_str(" = '");
        buf.push_str(&escape_single_quotes_ascii(value));
        buf.push_str("'\n");
    }
    buf
}

fn file_error(msg: String, e: &std::io::Error) -> PgError {
    let mut b = ereport(ERROR);
    if let Some(errno) = e.raw_os_error() {
        b = b.with_saved_errno(errno).errcode_for_file_access();
    }
    b.errmsg(msg).into_error()
}

// The flag/context checks and value validation from AlterSystemSetConfigFile
// (guc.c:4676-4744), run under one store borrow.
fn validate_auto_config_value(name: &str, value: Option<&str>) -> PgResult<()> {
    let found = guc::store::with_store(|reg| -> PgResult<bool> {
        let Some(record) = reg.find_option(name) else {
            return Ok(false);
        };
        let gen = record.gen();
        if gen.context == PGC_INTERNAL
            || gen.flags & GUC_DISALLOW_IN_FILE != 0
            || gen.flags & GUC_DISALLOW_IN_AUTO_FILE != 0
        {
            return Err(ereport(ERROR)
                .errcode(ERRCODE_CANT_CHANGE_RUNTIME_PARAM)
                .errmsg(format!("parameter \"{name}\" cannot be changed"))
                .into_error()
                .into());
        }
        if let Some(value) = value {
            // C wraps a false return in "invalid value for parameter"; the
            // ported parse_and_validate_value already errors in that form.
            let _ = guc::parse_and_validate_value(record, value, PGC_S_FILE)?;
        }
        Ok(true)
    })
    .expect("GUC store not initialized")?;

    if !found {
        // Unknown variable: check we'd be allowed to create it, except for a
        // RESET of an unknown custom GUC (reserved-prefix settings must stay
        // removable).
        if value.is_some() || !guc::valid_custom_variable_name(name) {
            guc::assignable_custom_variable_name(name, false)?;
        }
    }

    // The config-file grammar has no embedded newline in string literals.
    if value.is_some_and(|v| v.contains('\n')) {
        return Err(ereport(ERROR)
            .errcode(ERRCODE_INVALID_PARAMETER_VALUE)
            .errmsg("parameter value for ALTER SYSTEM must not contain a newline")
            .into_error()
            .into());
    }
    Ok(())
}

// AlterSystemSetConfigFile (guc.c:4607). On error the original
// postgresql.auto.conf is left intact; AutoFileLock serializes updates and is
// released by the abort path's LWLockReleaseAll on error, like C.
pub fn AlterSystemSetConfigFile(stmt: &AlterSystemStmt<'_>) -> PgResult<()> {
    let setstmt = stmt.setstmt;
    let name = setstmt.name.unwrap_or("");

    if !guc_tables::vars::AllowAlterSystem.read() {
        return Err(ereport(ERROR)
            .errcode(ERRCODE_FEATURE_NOT_SUPPORTED)
            .errmsg("ALTER SYSTEM is not allowed in this environment")
            .into_error()
            .into());
    }

    let mut resetall = false;
    let value: Option<String> = match setstmt.kind {
        VariableSetKind::VAR_SET_VALUE => ExtractSetVariableArgs(setstmt)?,
        VariableSetKind::VAR_SET_DEFAULT | VariableSetKind::VAR_RESET => None,
        VariableSetKind::VAR_RESET_ALL => {
            resetall = true;
            None
        }
        other => {
            return Err(ereport(ERROR)
                .errmsg_internal(format!(
                    "unrecognized alter system stmt type: {}",
                    other as i32
                ))
                .into_error()
                .into())
        }
    };

    if !superuser::superuser()? {
        if resetall {
            return Err(ereport(ERROR)
                .errcode(ERRCODE_INSUFFICIENT_PRIVILEGE)
                .errmsg("permission denied to perform ALTER SYSTEM RESET ALL")
                .into_error()
                .into());
        }
        let aclresult =
            aclchk_seams::pg_parameter_aclcheck::call(name, miscinit::GetUserId(), ACL_ALTER_SYSTEM)?;
        if aclresult != ACLCHECK_OK {
            return Err(ereport(ERROR)
                .errcode(ERRCODE_INSUFFICIENT_PRIVILEGE)
                .errmsg(format!("permission denied to set parameter \"{name}\""))
                .into_error()
                .into());
        }
    }

    if !resetall {
        validate_auto_config_value(name, value.as_deref())?;
    }

    // Both files are always in the data directory (the backend's cwd), so
    // simple relative paths work.
    let tmp_file_name = format!("{PG_AUTOCONF_FILENAME}.tmp");

    lwlock::LWLockAcquire(
        lwlock::main_lock(AUTO_FILE_LOCK),
        lwlock::LW_EXCLUSIVE,
        init_small::globals::MyProcNumber(),
    )?;

    let mut head: Vec<ConfigVariable> = Vec::new();
    if !resetall {
        match std::fs::read(PG_AUTOCONF_FILENAME) {
            Ok(contents) => {
                if !ParseConfigFp(
                    &contents,
                    std::path::Path::new(PG_AUTOCONF_FILENAME),
                    CONF_FILE_START_DEPTH,
                    LOG,
                    &mut head,
                )? {
                    return Err(ereport(ERROR)
                        .errcode(ERRCODE_CONFIG_FILE_ERROR)
                        .errmsg(format!(
                            "could not parse contents of file \"{PG_AUTOCONF_FILENAME}\""
                        ))
                        .into_error()
                        .into());
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(file_error(
                    format!("could not open file \"{PG_AUTOCONF_FILENAME}\": %m"),
                    &e,
                )
                .into())
            }
        }
        replace_auto_config_value(&mut head, name, value.as_deref());
    }

    // C: InvokeObjectPostAlterHookArgStr — the object_access_hook surface is
    // absent by design in this port.

    // Crash safety: write + fsync a temp file, then atomically rename it into
    // place. A leftover temp file from a previous crash is truncated/reused.
    let raw = fd::BasicOpenFile(&tmp_file_name, libc::O_CREAT | libc::O_RDWR | libc::O_TRUNC)?;
    if raw < 0 {
        return Err(file_error(
            format!("could not open file \"{tmp_file_name}\": %m"),
            &std::io::Error::last_os_error(),
        )
        .into());
    }
    // SAFETY: raw is a live fd we own; File takes ownership and closes it.
    let mut file = unsafe { std::fs::File::from_raw_fd(raw) };
    let write_result = (|| -> PgResult<()> {
        let content = render_auto_conf_file(&head);
        file.write_all(content.as_bytes()).map_err(|e| {
            file_error(format!("could not write to file \"{tmp_file_name}\": %m"), &e)
        })?;
        file.sync_all().map_err(|e| {
            file_error(format!("could not fsync file \"{tmp_file_name}\": %m"), &e)
        })?;
        Ok(())
    })();
    // Close before renaming (PG_CATCH parity: close then unlink on error).
    drop(file);
    if let Err(e) = write_result {
        let _ = std::fs::remove_file(&tmp_file_name);
        return Err(e);
    }
    if let Err(e) = fd::durable_rename(&tmp_file_name, PG_AUTOCONF_FILENAME, ERROR) {
        let _ = std::fs::remove_file(&tmp_file_name);
        return Err(e);
    }

    lwlock::LWLockRelease(lwlock::main_lock(AUTO_FILE_LOCK))?;
    Ok(())
}
