use crate::types::{among, symbol, SN_env};
use crate::api::{SN_create_env, SN_close_env};
#[allow(unused_imports)]
use crate::utilities::{
    in_grouping, in_grouping_b, out_grouping, out_grouping_b,
    in_grouping_U, in_grouping_b_U, out_grouping_U, out_grouping_b_U,
    find_among, find_among_b, slice_from_s, slice_del, slice_to,
    eq_s, eq_s_b, eq_v_b, insert_s, len_utf8, skip_utf8, skip_b_utf8,
};

static mut s_0_0: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_1: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_2: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_3: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8a as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_4: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8a as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_5: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8a as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_6: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_7: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_8: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_9: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_10: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8b as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_11: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_12: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_13: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_14: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_15: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_16: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_17: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_18: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_19: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_20: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_21: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_22: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
];
static mut s_0_23: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
];
static mut s_0_24: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
];
static mut s_0_25: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
];
static mut s_0_26: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
];
static mut s_0_27: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
];
static mut s_0_28: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
];
static mut s_0_29: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
];
static mut s_0_30: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_31: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_32: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_33: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_34: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x80 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_35: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_36: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_37: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x89 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_38: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_39: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x88 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_40: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x88 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_41: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x88 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_42: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8b as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_43: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8b as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_44: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8b as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_45: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8b as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_46: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8b as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_47: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_48: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_49: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_50: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x89 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_51: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_52: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_53: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_54: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_55: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_56: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_57: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x81 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_58: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_59: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x89 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_60: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_61: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_62: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_63: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_64: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_65: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_66: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_67: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_68: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_69: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_70: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
];
static mut s_0_71: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
];
static mut s_0_72: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
];
static mut s_0_73: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_74: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_75: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_76: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_77: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_78: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_79: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8b as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_80: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_81: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_82: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_83: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_84: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_85: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_86: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_87: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_88: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_89: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_90: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
];
static mut s_0_91: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x88 as ::core::ffi::c_int as symbol,
];
static mut s_0_92: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x88 as ::core::ffi::c_int as symbol,
];
static mut s_0_93: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x88 as ::core::ffi::c_int as symbol,
];
static mut s_0_94: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x89 as ::core::ffi::c_int as symbol,
];
static mut s_0_95: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8a as ::core::ffi::c_int as symbol,
];
static mut s_0_96: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8b as ::core::ffi::c_int as symbol,
];
static mut s_0_97: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x8d as ::core::ffi::c_int as symbol,
];
static mut s_0_98: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
];
static mut s_0_99: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
];
static mut s_0_100: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
];
static mut s_0_101: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
];
static mut s_0_102: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
];
static mut s_0_103: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
];
static mut s_0_104: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
];
static mut s_0_105: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
];
static mut s_0_106: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
];
static mut s_0_107: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x93 as ::core::ffi::c_int as symbol,
];
static mut s_0_108: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x95 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xb0 as ::core::ffi::c_int as symbol,
];
static mut s_0_109: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x95 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xb0 as ::core::ffi::c_int as symbol,
];
static mut s_0_110: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x95 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xb0 as ::core::ffi::c_int as symbol,
];
static mut s_0_111: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x95 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xb0 as ::core::ffi::c_int as symbol,
];
static mut s_0_112: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_113: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_114: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8a as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_115: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8a as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_116: [symbol; 15] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8a as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x82 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_117: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa5 as ::core::ffi::c_int as symbol,
    0x87 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_118: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_119: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_120: [symbol; 12] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x8f as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x97 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_121: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_122: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_123: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_124: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_125: [symbol; 6] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_126: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x85 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_127: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_128: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xa8 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_129: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0x86 as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_130: [symbol; 9] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xaf as ::core::ffi::c_int as symbol,
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbe as ::core::ffi::c_int as symbol,
];
static mut s_0_131: [symbol; 3] = [
    0xe0 as ::core::ffi::c_int as symbol,
    0xa4 as ::core::ffi::c_int as symbol,
    0xbf as ::core::ffi::c_int as symbol,
];
static mut a_0: [among; 132] = unsafe {
    [
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_0 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_1 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_2 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_3 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_4 as *const symbol,
            substring_i: 3 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_5 as *const symbol,
            substring_i: 3 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_6 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_7 as *const symbol,
            substring_i: 6 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_8 as *const symbol,
            substring_i: 6 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_9 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_10 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_11 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_12 as *const symbol,
            substring_i: 11 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_13 as *const symbol,
            substring_i: 11 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_14 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_15 as *const symbol,
            substring_i: 14 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_16 as *const symbol,
            substring_i: 14 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_17 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_18 as *const symbol,
            substring_i: 17 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_19 as *const symbol,
            substring_i: 17 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_20 as *const symbol,
            substring_i: 17 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_21 as *const symbol,
            substring_i: 0 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_22 as *const symbol,
            substring_i: 21 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_23 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_24 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_25 as *const symbol,
            substring_i: 24 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_26 as *const symbol,
            substring_i: 25 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_27 as *const symbol,
            substring_i: 25 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_28 as *const symbol,
            substring_i: 24 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_29 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_30 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_31 as *const symbol,
            substring_i: 30 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_32 as *const symbol,
            substring_i: 31 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_33 as *const symbol,
            substring_i: 31 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_34 as *const symbol,
            substring_i: 31 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_35 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_36 as *const symbol,
            substring_i: 35 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_37 as *const symbol,
            substring_i: 35 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_38 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_39 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_40 as *const symbol,
            substring_i: 39 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_41 as *const symbol,
            substring_i: 39 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_42 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_43 as *const symbol,
            substring_i: 42 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_44 as *const symbol,
            substring_i: 43 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_45 as *const symbol,
            substring_i: 43 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_46 as *const symbol,
            substring_i: 42 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_47 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_48 as *const symbol,
            substring_i: 47 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_49 as *const symbol,
            substring_i: 47 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_50 as *const symbol,
            substring_i: 47 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_51 as *const symbol,
            substring_i: 47 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_52 as *const symbol,
            substring_i: 51 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_53 as *const symbol,
            substring_i: 52 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_54 as *const symbol,
            substring_i: 51 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_55 as *const symbol,
            substring_i: 54 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_56 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_57 as *const symbol,
            substring_i: 56 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_58 as *const symbol,
            substring_i: 56 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_59 as *const symbol,
            substring_i: 56 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_60 as *const symbol,
            substring_i: 56 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_61 as *const symbol,
            substring_i: 60 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_62 as *const symbol,
            substring_i: 61 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_63 as *const symbol,
            substring_i: 60 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_64 as *const symbol,
            substring_i: 63 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_65 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_66 as *const symbol,
            substring_i: 65 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_67 as *const symbol,
            substring_i: 66 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_68 as *const symbol,
            substring_i: 66 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_69 as *const symbol,
            substring_i: 65 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_70 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_71 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_72 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_73 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_74 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_75 as *const symbol,
            substring_i: 74 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_76 as *const symbol,
            substring_i: 74 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_77 as *const symbol,
            substring_i: 76 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_78 as *const symbol,
            substring_i: 76 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_79 as *const symbol,
            substring_i: 74 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_80 as *const symbol,
            substring_i: 74 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_81 as *const symbol,
            substring_i: 80 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_82 as *const symbol,
            substring_i: 80 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_83 as *const symbol,
            substring_i: 74 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_84 as *const symbol,
            substring_i: 83 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_85 as *const symbol,
            substring_i: 83 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_86 as *const symbol,
            substring_i: 83 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_87 as *const symbol,
            substring_i: 74 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_88 as *const symbol,
            substring_i: 87 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_89 as *const symbol,
            substring_i: 87 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_90 as *const symbol,
            substring_i: 87 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_91 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_92 as *const symbol,
            substring_i: 91 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_93 as *const symbol,
            substring_i: 91 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_94 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_95 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_96 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_97 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_98 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_99 as *const symbol,
            substring_i: 98 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_100 as *const symbol,
            substring_i: 98 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_101 as *const symbol,
            substring_i: 100 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_102 as *const symbol,
            substring_i: 100 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_103 as *const symbol,
            substring_i: 98 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_104 as *const symbol,
            substring_i: 98 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_105 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_106 as *const symbol,
            substring_i: 105 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_107 as *const symbol,
            substring_i: 105 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_108 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_109 as *const symbol,
            substring_i: 108 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_110 as *const symbol,
            substring_i: 108 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_111 as *const symbol,
            substring_i: 108 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_112 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_113 as *const symbol,
            substring_i: 112 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_114 as *const symbol,
            substring_i: 112 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_115 as *const symbol,
            substring_i: 114 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 15 as ::core::ffi::c_int,
            s: &raw const s_0_116 as *const symbol,
            substring_i: 114 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_117 as *const symbol,
            substring_i: 112 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_118 as *const symbol,
            substring_i: 112 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_119 as *const symbol,
            substring_i: 118 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 12 as ::core::ffi::c_int,
            s: &raw const s_0_120 as *const symbol,
            substring_i: 118 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_121 as *const symbol,
            substring_i: 112 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_122 as *const symbol,
            substring_i: 121 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_123 as *const symbol,
            substring_i: 121 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_124 as *const symbol,
            substring_i: 121 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 6 as ::core::ffi::c_int,
            s: &raw const s_0_125 as *const symbol,
            substring_i: 112 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: Some(
                r_CONSONANT as unsafe fn(*mut SN_env) -> ::core::ffi::c_int,
            ),
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_126 as *const symbol,
            substring_i: 125 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_127 as *const symbol,
            substring_i: 125 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_128 as *const symbol,
            substring_i: 125 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_129 as *const symbol,
            substring_i: 112 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 9 as ::core::ffi::c_int,
            s: &raw const s_0_130 as *const symbol,
            substring_i: 112 as ::core::ffi::c_int,
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
        among {
            s_size: 3 as ::core::ffi::c_int,
            s: &raw const s_0_131 as *const symbol,
            substring_i: -(1 as ::core::ffi::c_int),
            result: -(1 as ::core::ffi::c_int),
            function: None,
        },
    ]
};
static mut g_consonant: [::core::ffi::c_uchar; 10] = [
    255 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    255 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    255 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    255 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    159 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    0 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    0 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    0 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    248 as ::core::ffi::c_int as ::core::ffi::c_uchar,
    7 as ::core::ffi::c_int as ::core::ffi::c_uchar,
];
unsafe fn r_CONSONANT(mut z: *mut SN_env) -> ::core::ffi::c_int {
    if in_grouping_b_U(
        z,
        &raw const g_consonant as *const ::core::ffi::c_uchar,
        2325 as ::core::ffi::c_int,
        2399 as ::core::ffi::c_int,
        0 as ::core::ffi::c_int,
    ) != 0
    {
        return 0 as ::core::ffi::c_int;
    }
    return 1 as ::core::ffi::c_int;
}
pub unsafe fn hindi_UTF_8_stem(mut z: *mut SN_env) -> ::core::ffi::c_int {
    let mut ret: ::core::ffi::c_int = skip_utf8(
        (*z).p,
        (*z).c,
        (*z).l,
        1 as ::core::ffi::c_int,
    );
    if ret < 0 as ::core::ffi::c_int {
        return 0 as ::core::ffi::c_int;
    }
    (*z).c = ret;
    (*z).lb = (*z).c;
    (*z).c = (*z).l;
    (*z).ket = (*z).c;
    if find_among_b(z, &raw const a_0 as *const among, 132 as ::core::ffi::c_int) == 0 {
        return 0 as ::core::ffi::c_int;
    }
    (*z).bra = (*z).c;
    let mut ret_0: ::core::ffi::c_int = slice_del(z);
    if ret_0 < 0 as ::core::ffi::c_int {
        return ret_0;
    }
    (*z).c = (*z).lb;
    return 1 as ::core::ffi::c_int;
}
pub unsafe fn hindi_UTF_8_create_env() -> *mut SN_env {
    return SN_create_env(0 as ::core::ffi::c_int, 0 as ::core::ffi::c_int);
}
pub unsafe fn hindi_UTF_8_close_env(mut z: *mut SN_env) {
    SN_close_env(z, 0 as ::core::ffi::c_int);
}
