[package]
name = "launch_backend"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "launch_backend"
path = "src/lib.rs"

[dependencies]
guc = { path = "../../utils/misc/guc" }
types_core = { path = "../../../_support/types/types_core" }
types_startup = { path = "../../../_support/types/types_startup" }
init_small = { path = "../../utils/init/init_small" }
miscinit = { path = "../../utils/init/miscinit" }
stack_depth = { path = "../../utils/misc/stack_depth" }
backend_startup = { path = "../../tcop/backend_startup" }
timestamp_seams = { path = "../../utils/adt/timestamp_seams" }
autovacuum = { path = "../autovacuum" }
bgwriter = { path = "../bgwriter" }
checkpointer = { path = "../checkpointer" }
postmaster_startup = { path = "../startup" }
walwriter = { path = "../walwriter" }
postmaster_seams = { path = "../postmaster_seams" }
interrupt = { path = "../interrupt" }
procsignal = { path = "../../storage/ipc/procsignal" }
ipc = { path = "../../storage/ipc/ipc" }
libc = "0.2"

[dev-dependencies]
xact_seams = { path = "../../access/transam/xact_seams" }
scalar_seams = { path = "../../utils/adt/scalar_seams" }
types_guc = { path = "../../../_support/types/types_guc" }
ip = { path = "../../../common/ip" }
libpq_pqsignal = { path = "../../libpq/libpq_pqsignal" }
guc_tables = { path = "../../utils/misc/guc_tables" }
pqcomm_seams = { path = "../../libpq/pqcomm_seams" }
waiteventset_seams = { path = "../../storage/ipc/waiteventset_seams" }
types_storage = { path = "../../../_support/types/types_storage" }
libc = "0.2"
