[package]
name = "commands_publicationcmds"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "commands_publicationcmds"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_rel = { path = "../../../_support/types/rel" }
types_scan = { path = "../../../_support/types/types_scan" }
types_tuple = { path = "../../../_support/types/types_tuple" }
datum = { path = "../../../_support/types/datum" }
mcx = { path = "../../../_support/mcx" }
rel_vocab = { path = "../../../_support/types/rel_vocab" }
elog = { path = "../../utils/error/elog" }
genam = { path = "../../access/index/genam" }
table = { path = "../../access/table/table" }
heaptuple = { path = "../../access/common/heaptuple" }
xact = { path = "../../access/transam/xact" }
transam_xlog = { path = "../../access/transam/transam_xlog" }
catalog = { path = "../../catalog/catalog" }
catalog_namespace = { path = "../../catalog/catalog_namespace" }
catalog_indexing = { path = "../../catalog/catalog_indexing" }
catalog_dependency = { path = "../../catalog/catalog_dependency" }
pg_depend = { path = "../../catalog/pg_depend" }
pg_shdepend = { path = "../../catalog/pg_shdepend" }
pg_publication = { path = "../../catalog/pg_publication" }
pg_inherits = { path = "../../catalog/pg_inherits" }
aclchk = { path = "../../catalog/aclchk" }
adt_acl = { path = "../../utils/adt/acl" }
inval = { path = "../../utils/cache/inval" }
lsyscache = { path = "../../utils/cache/lsyscache" }
cache_syscache = { path = "../../utils/cache/cache_syscache" }
relcache = { path = "../../utils/cache/relcache" }
init_small = { path = "../../utils/init/init_small" }
miscinit = { path = "../../utils/init/miscinit" }
superuser = { path = "../../utils/misc/superuser" }
varlena = { path = "../../utils/adt/varlena" }
detoast = { path = "../../access/common/detoast" }
mbutils = { path = "../../utils/mb/mbutils" }
readfuncs = { path = "../../nodes/readfuncs" }
rewrite_handler = { path = "../../rewrite/rewrite_handler" }
nodes_core = { path = "../../nodes/nodes_core" }
parser_small1 = { path = "../../parser/parser_small1" }
parse_relation = { path = "../../parser/parse_relation" }
parse_clause = { path = "../../parser/parse_clause" }
parse_collate = { path = "../../parser/parse_collate" }
commands_define = { path = "../commands_define" }
dbcommands = { path = "../dbcommands" }
publicationcmds_seams = { path = "../publicationcmds_seams" }
fmgr_seams = { path = "../../utils/fmgr/fmgr_seams" }
lmgr = { path = "../../storage/lmgr/lmgr" }
