[package]
name = "procsignal"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "procsignal"
path = "src/lib.rs"

[dependencies]
walsender_seams = { path = "../../../replication/walsender_seams" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_storage = { path = "../../../../_support/types/types_storage" }
elog = { path = "../../../utils/error/elog" }
init_small = { path = "../../../utils/init/init_small" }
latch = { path = "../latch" }
lmgr_proc = { path = "../../lmgr/lmgr_proc" }
procsignal_seams = { path = "../procsignal_seams" }
ipc_seams = { path = "../ipc_seams" }
shmem_seams = { path = "../shmem_seams" }
async_seams = { path = "../../../commands/async_seams" }
parallel_seams = { path = "../../../access/transam/parallel_seams" }
sinval_seams = { path = "../sinval_seams" }
postgres_seams = { path = "../../../tcop/postgres_seams" }
s_lock_seams = { path = "../../lmgr/s_lock_seams" }
condition_variable_seams = { path = "../../lmgr/condition_variable_seams" }
smgr_seams = { path = "../../smgr/smgr_seams" }
mcxt_seams = { path = "../../../utils/mmgr/mcxt_seams" }
pgsync = { path = "../../../../_support/pgsync" }
libc = "0.2"

[dev-dependencies]
pg_sema_seams = { path = "../../../port/pg_sema_seams" }
