[package]
name = "pg_sema"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "pg_sema"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../_support/types/types_core" }
pg_sema_seams = { path = "../pg_sema_seams" }
waiter = { path = "../../storage/ipc/waiter" }
