[package]
name = "multixactfuncs"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "multixactfuncs"
path = "src/lib.rs"

[dependencies]
types_error = { path = "../../../../_support/types/types_error" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
datum = { path = "../../../../_support/types/datum" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
fmgr_core = { path = "../../../utils/fmgr/fmgr_core" }
funcapi = { path = "../../../utils/fmgr/funcapi" }
heaptuple = { path = "../../common/heaptuple" }
varlena = { path = "../../../utils/adt/varlena" }
typcache_seams = { path = "../../../utils/cache/typcache_seams" }
multixact = { path = "../multixact" }
