[package]
name = "coerce"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "coerce"
path = "src/lib.rs"

[dependencies]
datum = { path = "../../../_support/types/datum" }
detoast = { path = "../../access/common/detoast" }
elog = { path = "../../utils/error/elog" }
format_type = { path = "../../utils/adt/format_type" }
fmgr = { package = "types_fmgr", path = "../../../_support/types/fmgr" }
fmgr_core = { path = "../../utils/fmgr/fmgr_core" }
lsyscache = { path = "../../utils/cache/lsyscache" }
mbutils = { path = "../../utils/mb/mbutils" }
mcx = { path = "../../../_support/mcx" }
parser_small1 = { path = "../parser_small1" }
syscache_seams = { path = "../../utils/cache/syscache_seams" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_tuple = { path = "../../../_support/types/types_tuple" }
