[package]
name = "gist"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
mcx = { path = "../../../../_support/mcx" }
datum = { path = "../../../../_support/types/datum" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_scan = { path = "../../../../_support/types/types_scan" }
types_gist = { path = "../../../../_support/types/gist" }
types_rel = { path = "../../../../_support/types/rel" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
types_storage = { path = "../../../../_support/types/types_storage" }
types_nbtree = { path = "../../../../_support/types/types_nbtree" }
types_snapshot = { path = "../../../../_support/types/snapshot" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
types_relscan = { path = "../../index/relscan" }
nbtree = { path = "../../nbtree/nbtree" }
tupdesc = { path = "../../common/tupdesc" }
fmgr_seams = { path = "../../../utils/fmgr/fmgr_seams" }
indexam_seams = { path = "../../index/indexam_seams" }
bufmgr_seams = { path = "../../../storage/buffer/bufmgr_seams" }
predicate_seams = { path = "../../../storage/lmgr/predicate_seams" }
transam_xlog_seams = { path = "../../transam/transam_xlog_seams" }
transam_xlog = { path = "../../transam/transam_xlog" }
xloginsert = { path = "../../transam/xloginsert" }
xloginsert_seams = { path = "../../transam/xloginsert_seams" }
xact = { path = "../../transam/xact" }
tidbitmap = { path = "../../../nodes/tidbitmap" }
init_small = { path = "../../../utils/init/init_small" }
freespace = { path = "../../../storage/freespace/freespace" }
pg_prng = { path = "../../../../common/pg_prng" }
vacuum_seams = { path = "../../../commands/vacuum_seams" }
varsup = { path = "../../transam/varsup" }
procarray_seams = { path = "../../../storage/ipc/procarray_seams" }
elog = { path = "../../../utils/error/elog" }
