[package]
name = "commands_define"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "commands_define"
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../_support/mcx" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
adt_int8 = { path = "../../utils/adt/int8" }
