[package]
name = "postgres"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
libc = "0.2"
mcx = { path = "../../../_support/mcx" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_portal = { path = "../../../_support/types/portal" }
types_nodes = { path = "../../../_support/types/nodes" }
types_dest = { path = "../../../_support/types/types_dest" }
stringinfo = { path = "../../../_support/types/stringinfo" }
elog = { path = "../../utils/error/elog" }
cmdtag = { path = "../cmdtag" }
tcop_dest = { path = "../dest" }
pquery = { path = "../pquery" }
portalmem = { path = "../../utils/mmgr/portalmem" }
snapmgr = { path = "../../utils/time/snapmgr" }
xact = { path = "../../access/transam/xact" }
pqcomm = { path = "../../libpq/pqcomm" }
pqformat = { path = "../../libpq/pqformat" }
init_small = { path = "../../utils/init/init_small" }
lmgr_proc = { path = "../../storage/lmgr/lmgr_proc" }
latch = { path = "../../storage/ipc/latch" }
pmsignal = { path = "../../storage/ipc/pmsignal" }
sinval = { path = "../../storage/ipc/sinval" }
procsignal = { path = "../../storage/ipc/procsignal" }
procsignal_seams = { path = "../../storage/ipc/procsignal_seams" }
mcxt_seams = { path = "../../utils/mmgr/mcxt_seams" }
interrupt = { path = "../../../backend/postmaster/interrupt" }
guc = { path = "../../utils/misc/guc" }
guc_file = { path = "../../utils/misc/guc_file" }
guc_tables = { path = "../../utils/misc/guc_tables" }
pgstat = { path = "../../utils/activity/pgstat" }
postgres_seams = { path = "../postgres_seams" }
utility_seams = { path = "../utility_seams" }
parser_seams = { path = "../../parser/parser_seams" }
analyze_seams = { path = "../../parser/analyze_seams" }
rewrite_handler_seams = { path = "../../rewrite/rewrite_handler_seams" }
planner_seams = { path = "../../optimizer/plan/planner_seams" }
ps_status_seams = { path = "../../utils/misc/ps_status_seams" }
timeout_seams = { path = "../../utils/misc/timeout_seams" }
backend_status_seams = { path = "../../utils/activity/backend_status_seams" }
ipc = { path = "../../storage/ipc/ipc" }
ipc_seams = { path = "../../storage/ipc/ipc_seams" }
postinit = { path = "../../utils/init/postinit" }
miscinit = { path = "../../utils/init/miscinit" }
types_guc = { path = "../../../_support/types/types_guc" }

[dev-dependencies]
lock_seams = { path = "../../storage/lmgr/lock_seams" }
s_lock_seams = { path = "../../storage/lmgr/s_lock_seams" }
shmem_seams = { path = "../../storage/ipc/shmem_seams" }
pg_sema_seams = { path = "../../port/pg_sema_seams" }
types_storage = { path = "../../../_support/types/types_storage" }
pgstat_seams = { path = "../../utils/activity/pgstat_seams" }
init_small_seams = { path = "../../utils/init/init_small_seams" }
