[package]
name = "memwatchdog"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "memwatchdog"
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../_support/mcx" }
types_core = { path = "../../../_support/types/types_core" }
types_storage = { path = "../../../_support/types/types_storage" }
elog = { path = "../../utils/error/elog" }
guc_tables = { path = "../../utils/misc/guc_tables" }
lmgr_proc = { path = "../../storage/lmgr/lmgr_proc" }
procsignal = { path = "../../storage/ipc/procsignal" }
