[package]
name = "xlogarchive"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "xlogarchive"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
elog = { path = "../../../utils/error/elog" }
fd = { path = "../../../storage/file/fd" }
guc_tables = { path = "../../../utils/misc/guc_tables" }
init_small = { path = "../../../utils/init/init_small" }
ipc = { path = "../../../storage/ipc/ipc" }
pgarch = { path = "../../../postmaster/pgarch" }
postmaster_startup = { path = "../../../postmaster/startup" }
archive = { path = "../../../../common/archive" }
percentrepl = { path = "../../../../common/percentrepl" }
wait_error = { path = "../../../../common/wait_error" }
transam_xlog = { path = "../transam_xlog" }
waitevent_seams = { path = "../../../utils/activity/waitevent_seams" }
xlogarchive_seams = { path = "../xlogarchive_seams" }
xlogrecovery_seams = { path = "../xlogrecovery_seams" }
libc = "0.2"

[dev-dependencies]
xact_seams = { path = "../xact_seams" }
