[package]
name = "nodes_params"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
adt_scalar = { path = "../../utils/adt/scalar" }
conv = { path = "../../utils/mb/conv" }
datum = { path = "../../../_support/types/datum" }
fmgr_seams = { path = "../../utils/fmgr/fmgr_seams" }
lsyscache = { path = "../../utils/cache/lsyscache" }
mcx = { path = "../../../_support/mcx" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_fmgr = { path = "../../../_support/types/fmgr" }
types_portal = { path = "../../../_support/types/portal" }
xact = { path = "../../access/transam/xact" }

[dev-dependencies]
syscache_seams = { path = "../../utils/cache/syscache_seams" }
types_tuple = { path = "../../../_support/types/types_tuple" }
