[package]
name = "injection_points"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "injection_points"
path = "src/lib.rs"

[dependencies]
datum = { path = "../../_support/types/datum" }
types_error = { path = "../../_support/types/types_error" }
types_fmgr = { path = "../../_support/types/fmgr" }
dfmgr = { path = "../../backend/utils/fmgr/dfmgr" }
injection_point = { path = "../../backend/utils/misc/injection_point" }
