[package]
name = "smgr"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "smgr"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_storage = { path = "../../../../_support/types/types_storage" }
types_rel = { path = "../../../../_support/types/rel" }
mcx = { path = "../../../../_support/mcx" }
elog = { path = "../../../utils/error/elog" }
md = { path = "../md" }
pgstat = { path = "../../../utils/activity/pgstat" }
fd = { path = "../../file/fd" }
inval = { path = "../../../utils/cache/inval" }
xlogutils = { path = "../../../access/transam/xlogutils" }
smgr_seams = { path = "../smgr_seams" }
bufmgr_seams = { path = "../../buffer/bufmgr_seams" }
relmapper_seams = { path = "../../../utils/cache/relmapper_seams" }
init_small = { path = "../../../utils/init/init_small" }

[dev-dependencies]
types_tuple = { path = "../../../../_support/types/types_tuple" }
guc_tables = { path = "../../../utils/misc/guc_tables" }
xact_seams = { path = "../../../access/transam/xact_seams" }
aio_seams = { path = "../../aio/aio_seams" }
waitevent_seams = { path = "../../../utils/activity/waitevent_seams" }
pgstat_seams = { path = "../../../utils/activity/pgstat_seams" }
relpath_seams = { path = "../../../../common/relpath_seams" }
sync_seams = { path = "../../sync/sync_seams" }
tablespace_seams = { path = "../../../commands/tablespace_seams" }
libc = "0.2"
