[package]
name = "main_main"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "main_main"
path = "src/lib.rs"

[[bin]]
name = "postgres"
path = "src/bin/postgres.rs"

[dependencies]
libc = "0.2"
mimalloc = "0.1"
mcx = { path = "../../../_support/mcx" }
types_error = { path = "../../../_support/types/types_error" }
elog = { path = "../../utils/error/elog" }
init_small = { path = "../../utils/init/init_small" }
stack_depth = { path = "../../utils/misc/stack_depth" }
ps_status = { path = "../../utils/misc/ps_status" }
pg_locale = { path = "../../utils/adt/pg_locale" }
postmaster = { path = "../../postmaster/postmaster" }
seams_init = { path = "../../../_support/seams_init" }
