//! Shared compression-method definitions
//! (`src/include/common/compression.h`).
//!
//! These are the shared vocabulary types for compression methods and
//! specifications. The C struct `pg_compress_specification` is produced by
//! `common/compression.c`'s `parse_compress_specification` (still unported) and
//! is consumed by, among others, the base-backup compression sinks
//! (`basebackup_gzip.c` / `basebackup_lz4.c` / `basebackup_zstd.c`) and by
//! `basebackup.c` itself, so it lives here as shared vocabulary rather than in
//! any one consumer.

#![no_std]
#![forbid(unsafe_code)]

extern crate alloc;

use alloc::string::String;

/// Compression algorithm (C `enum pg_compress_algorithm`).
///
/// These values are stored on disk (e.g. in files generated by `pg_dump`), so
/// the discriminant order must not change.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PgCompressAlgorithm {
    /// `PG_COMPRESSION_NONE`
    None,
    /// `PG_COMPRESSION_GZIP`
    Gzip,
    /// `PG_COMPRESSION_LZ4`
    Lz4,
    /// `PG_COMPRESSION_ZSTD`
    Zstd,
}

/// `PG_COMPRESSION_OPTION_WORKERS` — the `workers` field is set
/// (`compress->options` bit `1 << 0`).
pub const PG_COMPRESSION_OPTION_WORKERS: u32 = 1 << 0;

/// `PG_COMPRESSION_OPTION_LONG_DISTANCE` — the `long_distance` field is set
/// (`compress->options` bit `1 << 1`).
pub const PG_COMPRESSION_OPTION_LONG_DISTANCE: u32 = 1 << 1;

/// A fully-resolved compression specification (C
/// `struct pg_compress_specification`).
///
/// Produced by `common/compression.c`'s `parse_compress_specification` and
/// passed to the consumer. `options` is an OR of the
/// `PG_COMPRESSION_OPTION_*` constants; `parse_error` is `None` if parsing
/// succeeded, else the error message (the C `char *parse_error`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PgCompressSpecification {
    /// Selected algorithm.
    pub algorithm: PgCompressAlgorithm,
    /// OR of `PG_COMPRESSION_OPTION_*` constants.
    pub options: u32,
    /// Compression level.
    pub level: i32,
    /// Worker count (valid iff `PG_COMPRESSION_OPTION_WORKERS` is set).
    pub workers: i32,
    /// Long-distance matching enabled (valid iff
    /// `PG_COMPRESSION_OPTION_LONG_DISTANCE` is set).
    pub long_distance: bool,
    /// `None` if parsing was OK, else the parse-error message.
    pub parse_error: Option<String>,
}
