[package]
name = "be_secure"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "be_secure"
path = "src/lib.rs"

[dependencies]
types_error = { path = "../../../_support/types/types_error" }
types_storage = { path = "../../../_support/types/types_storage" }
init_small = { path = "../../utils/init/init_small" }
latch_seams = { path = "../../storage/ipc/latch_seams" }
postgres_seams = { path = "../../tcop/postgres_seams" }
pqcomm = { path = "../pqcomm" }
be_secure_seams = { path = "../be_secure_seams" }
be_secure_openssl = { path = "../be_secure_openssl" }
elog = { path = "../../utils/error/elog" }
types_core = { path = "../../../_support/types/types_core" }
libc = "0.2"

[dev-dependencies]
fd = { path = "../../storage/file/fd" }
ip = { path = "../../../common/ip" }
ipc_seams = { path = "../../storage/ipc/ipc_seams" }
latch = { path = "../../storage/ipc/latch" }
mcx = { path = "../../../_support/mcx" }
miscinit_seams = { path = "../../utils/init/miscinit_seams" }
pgstat_seams = { path = "../../utils/activity/pgstat_seams" }
pqcomm_seams = { path = "../pqcomm_seams" }
stringinfo = { path = "../../../_support/types/stringinfo" }
types_startup = { path = "../../../_support/types/types_startup" }
waitevent_seams = { path = "../../utils/activity/waitevent_seams" }
waiteventset = { path = "../../storage/ipc/waiteventset" }
