[package]
name = "shmem"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "shmem"
path = "src/lib.rs"

[dependencies]
types_error = { path = "../../../../_support/types/types_error" }
elog = { path = "../../../utils/error/elog" }
shmem_seams = { path = "../shmem_seams" }
