[package]
name = "shmem"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "shmem"
path = "src/lib.rs"

[dependencies]
s_lock_seams = { path = "../../lmgr/s_lock_seams" }
datum = { path = "../../../../_support/types/datum" }
types_error = { path = "../../../../_support/types/types_error" }
types_fmgr = { package = "types_fmgr", path = "../../../../_support/types/fmgr" }
elog = { path = "../../../utils/error/elog" }
shmem_seams = { path = "../shmem_seams" }
funcapi = { path = "../../../utils/fmgr/funcapi" }
varlena = { path = "../../../utils/adt/varlena" }
mcx = { path = "../../../../_support/mcx" }

[dev-dependencies]
s_lock = { path = "../../lmgr/s_lock" }
waitevent_seams = { path = "../../../utils/activity/waitevent_seams" }
