[package]
name = "fmgr_core"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "fmgr_core"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
datum = { path = "../../../../_support/types/datum" }
fmgr = { package = "types_fmgr", path = "../../../../_support/types/fmgr" }
fmgr_seams = { path = "../fmgr_seams" }
adt_bool = { path = "../../adt/bool" }
adt_scalar = { path = "../../adt/scalar" }
adt_cash = { path = "../../adt/cash" }
adt_date = { path = "../../adt/adt_date" }
adt_float = { path = "../../adt/float" }
adt_int = { path = "../../adt/int" }
adt_int8 = { path = "../../adt/int8" }
adt_mac = { path = "../../adt/mac" }
adt_mac8 = { path = "../../adt/mac8" }
adt_numeric = { path = "../../adt/numeric" }
adt_like = { path = "../../adt/like" }
adt_oracle_compat = { path = "../../adt/oracle_compat" }
adt_pseudotypes = { path = "../../adt/pseudotypes" }
name = { path = "../../adt/name" }
nbt_compare = { path = "../../../access/nbtree/compare" }
varlena = { path = "../../adt/varlena" }

[dev-dependencies]
mcx = { path = "../../../../_support/mcx" }
nodes = { package = "types_nodes", path = "../../../../_support/types/nodes" }
