[package]
name = "dfmgr"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "dfmgr"
path = "src/lib.rs"

[dependencies]
fmgr = { package = "types_fmgr", path = "../../../../_support/types/fmgr" }
types_error = { path = "../../../../_support/types/types_error" }
elog = { path = "../../error/elog" }
guc_tables = { path = "../../misc/guc_tables" }
init_small = { path = "../../init/init_small" }
pg_path = { path = "../../../../port/pg_path" }
fd = { path = "../../../storage/file/fd" }
vfs = { path = "../../../storage/file/vfs" }
