[package]
name = "parse_oper"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "parse_oper"
path = "src/lib.rs"

[dependencies]
cache_syscache = { path = "../../utils/cache/cache_syscache" }
catalog_namespace = { path = "../../catalog/catalog_namespace" }
coerce = { path = "../coerce" }
datum = { path = "../../../_support/types/datum" }
elog = { path = "../../utils/error/elog" }
format_type = { path = "../../utils/adt/format_type" }
inval = { path = "../../utils/cache/inval" }
lsyscache = { path = "../../utils/cache/lsyscache" }
mbutils = { path = "../../utils/mb/mbutils" }
mcx = { path = "../../../_support/mcx" }
parse_func = { path = "../parse_func" }
parser_small1 = { path = "../parser_small1" }
syscache_seams = { path = "../../utils/cache/syscache_seams" }
typcache = { path = "../../utils/cache/typcache" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }

parse_utilcmd = { path = "../parse_utilcmd" }

[dev-dependencies]
namespace_seams = { path = "../../catalog/namespace_seams" }
types_tuple = { path = "../../../_support/types/types_tuple" }
miscinit_seams = { path = "../../utils/init/miscinit_seams" }
indexcmds_seams = { path = "../../commands/indexcmds_seams" }
pg_inherits_seams = { path = "../../catalog/pg_inherits_seams" }
