//! Startup aggregator: calls every ported crate's `init_seams()`.
//!
//! This crate contains NO logic and NO `set()` calls of its own — one line
//! per ported crate, nothing else. Each crate wires its own seams in its own
//! `init_seams()`; this is just the place that invokes them all.

pub fn init_all() {
    // One line per ported crate, kept sorted:
    backend_access_common_detoast::init_seams();
    backend_access_common_heaptuple::init_seams();
    backend_access_common_reloptions::init_seams();
    backend_access_hashvalidate::init_seams();
    backend_access_heap_heaptoast::init_seams();
    backend_access_rmgrdesc_small::init_seams();
    backend_access_table_table::init_seams();
    backend_access_table_tableam::init_seams();
    backend_access_transam_twophase::init_seams();
    backend_access_transam_xact::init_seams();
    backend_access_transam_xlog::init_seams();
    backend_access_transam_xlogprefetcher::init_seams();
    backend_access_transam_xlogstats::init_seams();
    backend_catalog_namespace::init_seams();
    backend_catalog_pg_depend::init_seams();
    backend_executor_execAmi::init_seams();
    backend_executor_execParallel::init_seams();
    backend_executor_execPartition::init_seams();
    backend_executor_execUtils::init_seams();
    backend_executor_instrument::init_seams();
    backend_executor_nodeMaterial::init_seams();
    backend_executor_nodeMergejoin::init_seams();
    backend_executor_nodeModifyTable::init_seams();
    backend_executor_nodeForeignscan::init_seams();
    backend_executor_nodeSeqscan::init_seams();
    backend_libpq_pqcomm::init_seams();
    backend_libpq_pqformat::init_seams();
    backend_libpq_pqsignal::init_seams();
    backend_port_atomics::init_seams();
    backend_postmaster_interrupt::init_seams();
    backend_postmaster_launch_backend::init_seams();
    backend_postmaster_startup::init_seams();
    backend_regex_core::init_seams();
    backend_replication_logical_logical::init_seams();
    backend_postmaster_syslogger::init_seams();
    backend_replication_logical_conflict::init_seams();
    backend_replication_logical_proto::init_seams();
    backend_storage_file_buffile::init_seams();
    backend_storage_ipc::init_seams();
    backend_storage_ipc_dsm_core::init_seams();
    backend_storage_ipc_latch::init_seams();
    backend_storage_ipc_procsignal::init_seams();
    backend_storage_ipc_shm_mq::init_seams();
    backend_storage_ipc_shm_toc::init_seams();
    backend_storage_ipc_standby::init_seams();
    backend_storage_lmgr_condition_variable::init_seams();
    backend_storage_lmgr_deadlock::init_seams();
    backend_storage_lmgr_lwlock::init_seams();
    backend_storage_lmgr_s_lock::init_seams();
    backend_storage_page_checksum::init_seams();
    backend_timezone_localtime::init_seams();
    backend_timezone_strftime::init_seams();
    backend_utils_activity_small::init_seams();
    backend_utils_activity_xact::init_seams();
    backend_utils_adt_acl::init_seams();
    backend_utils_adt_numutils::init_seams();
    backend_utils_adt_regexp::init_seams();
    backend_utils_adt_range_selfuncs::init_seams();
    backend_utils_adt_rangetypes::init_seams();
    backend_utils_cache_attoptcache::init_seams();
    backend_utils_cache_relfilenumbermap::init_seams();
    backend_utils_cache_spccache::init_seams();
    backend_utils_cache_syscache::init_seams();
    backend_utils_cache_ts_cache::init_seams();
    backend_utils_error::init_seams();
    backend_utils_init_small::init_seams();
    backend_utils_mb_wstrcmp::init_seams();
    backend_utils_mb_wstrncmp::init_seams();
    backend_utils_misc_more::init_seams();
    backend_utils_misc_pg_rusage::init_seams();
    backend_utils_misc_queryenvironment::init_seams();
    backend_utils_misc_sampling::init_seams();
    backend_utils_mmgr_freepage::init_seams();
    backend_utils_time_combocid::init_seams();
    interfaces_libpq_legacy_pqsignal::init_seams();
}
