[package]
name = "pg_enum_seams"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[dependencies]
seam_core = { path = "../../../_support/seam_core" }
mcx = { path = "../../../_support/mcx" }
types_tuple = { path = "../../../_support/types/types_tuple" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
