[package]
name = "adt_oracle_compat"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
datum = { path = "../../../../_support/types/datum" }
init_small = { path = "../../init/init_small" }
postgres_seams = { path = "../../../tcop/postgres_seams" }
mcx = { path = "../../../../_support/mcx" }
mbutils = { path = "../../mb/mbutils" }
pg_locale = { path = "../pg_locale" }
pg_locale_seams = { path = "../pg_locale_seams" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
varlena = { path = "../varlena" }
wchar = { path = "../../../../common/wchar" }

[dev-dependencies]
syscache_seams = { path = "../../cache/syscache_seams" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
