[package]
name = "subtrans"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "subtrans"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_storage = { path = "../../../../_support/types/types_storage" }
types_guc = { path = "../../../../_support/types/types_guc" }
elog = { path = "../../../utils/error/elog" }
init_small = { path = "../../../utils/init/init_small" }
guc = { path = "../../../utils/misc/guc" }
guc_tables = { path = "../../../utils/misc/guc_tables" }
guc_seams = { path = "../../../utils/misc/guc_seams" }
lwlock = { path = "../../../storage/lmgr/lwlock" }
slru = { path = "../slru" }
subtrans_seams = { path = "../subtrans_seams" }
varsup_seams = { path = "../varsup_seams" }
procarray = { path = "../../../storage/ipc/procarray" }

[dev-dependencies]
libc = "0.2"
shmem_seams = { path = "../../../storage/ipc/shmem_seams" }
file_seams = { path = "../../../storage/file/file_seams" }
sync_seams = { path = "../../../storage/sync/sync_seams" }
pgstat_seams = { path = "../../../utils/activity/pgstat_seams" }
waitevent_seams = { path = "../../../utils/activity/waitevent_seams" }
transam_xlog_seams = { path = "../transam_xlog_seams" }
xlogutils_seams = { path = "../xlogutils_seams" }
