/*
 * pg_instrbe_io.c: vendored PostgreSQL C oracle for the instrument_diff
 * differential fuzz target (100%-coverage campaign, lane p1-wavea).
 * Crate under test: crates/backend/executor/instrument.
 *
 * GENERATED by csrc/gen/assemble_instrbe.sh — verbatim sections are
 * sed-extracted, never hand-typed. Do not edit the VERBATIM sections here;
 * edit the script's shim heredocs and re-run.
 *
 * Provenance (all VERBATIM sections byte-for-byte from
 * ~/dev/pgrust-fabled/vendor/postgres-src, Stamp-18.3, upstream sha
 * 62d6c7d3df6287f1bd83199c1a746e50d31571a0):
 *   - src/include/portability/instr_time.h lines 60-72 (comment +
 *     instr_time typedef), 75-79 (NS_PER_* constants), 125-126
 *     (INSTR_TIME_GET_NANOSEC, POSIX variant), 165-195 (ALL common macros:
 *     IS_ZERO, SET_ZERO, SET_CURRENT_LAZY, ADD, SUBTRACT, ACCUM_DIFF,
 *     GET_DOUBLE, GET_MILLISEC, GET_MICROSEC). INSTR_TIME_SET_CURRENT
 *     alone is shimmed (stub:clock environment read, see shim list);
 *     every derived tick after the read is this verbatim arithmetic.
 *   - src/include/executor/instrument.h lines 19-94 (BufferUsage,
 *     WalUsage, InstrumentOption enum, Instrumentation — the full struct
 *     layer, never transcribed by hand) and lines 116-119 (the
 *     BufferUsageAccumDiff/WalUsageAccumDiff extern prototypes the
 *     vendored bodies call ahead of definition).
 *   - src/backend/executor/instrument.c lines 20 and 22 (the pgBufferUsage
 *     / pgWalUsage global definitions), 25-26 (static prototypes), 56-196
 *     (InstrInit, InstrStartNode, InstrStopNode, InstrUpdateTupleCount,
 *     InstrEndLoop, InstrAggNode) and 224-293 (BufferUsageAdd,
 *     BufferUsageAccumDiff, WalUsageAdd, WalUsageAccumDiff).
 *     NOT vendored (census carve, family-grain):
 *       - InstrAlloc (lines 29-54): palloc0 allocation plumbing; the Rust
 *         crate has no InstrAlloc (callers InstrInit pre-allocated
 *         structs). Its option-bit fanout is InstrInit's, which IS in.
 *       - InstrStartParallelQuery / InstrEndParallelQuery /
 *         InstrAccumParallelQuery (lines 198-222) + the save_pgBufferUsage
 *         / save_pgWalUsage statics (lines 21, 23): the parallel-query
 *         WORKER_CONTRIB overlay is a DELIBERATE pgrust divergence (the
 *         Rust side accumulates worker usage in a thread-local overlay
 *         because the live counters cannot be bumped) — fenced OUT per the
 *         census, documented in the driver header.
 *
 * Shims (PLUMBING ONLY, never logic):
 *   - fixed-width typedefs matching c.h on LP64 (int64/uint64/bool);
 *     PG_INT32_MAX = INT32_MAX; INT64CONST.
 *   - INSTR_TIME_SET_CURRENT -> ticks = (int64) pg_stub_get_mono_ns()
 *     (stub:clock monotonic half, csrc/stubshims/pg_stub_state.c; the
 *     driver pins the SAME fuzz-derived value into pg_clock's
 *     fuzz_mono_pin cell on the Rust side per fuzz/STUBS.md — the OS
 *     clock read is ENVIRONMENT; INSTR_TIME_SET_CURRENT_LAZY and all
 *     elapsed arithmetic are the verbatim pastes above).
 *   - elog(ERROR, "literal") -> record the literal in pg_instrbe_errmsg_v
 *     + longjmp (error-verdict + message planes; instrument.c's three
 *     elogs are all single string literals).
 *   - GLOBALS PIN (driver contract, documented here as the census
 *     mandate requires): pgBufferUsage is pinned ZERO on both sides —
 *     pg_instrbe_reset() zeroes it, no vendored writer of it is compiled
 *     in, and this TU exports no setter for it (the Rust side's bufmgr
 *     counters are never bumped by the fuzz driver, so its
 *     pg_buffer_usage() is zero by construction; fuzz-fed buffer deltas
 *     enter through IDENTICAL struct-field injection on both sides).
 *     pgWalUsage is SET FROM FUZZ INPUT identically on both sides:
 *     pg_instrbe_set_wal_global() here, the installed
 *     transam_xlog_seams::wal_usage seam on the Rust side.
 *   - family-prefix renames (#define ahead of the pastes) for every
 *     non-static vendored symbol so this TU exports pg_instrbe_* only.
 *   - wire pack/unpack helpers: the driver exchanges structs as packed
 *     little-endian byte images (field-by-field memcpy, no logic).
 *
 * Comparison planes (driver: core/src/instrument_diff.rs): every
 * Instrumentation/BufferUsage/WalUsage field value-compared (f64 totals
 * bit-exact via the wire image, counters exact) + error-verdict + error
 * message literal. No tolerance anywhere except the driver's any-NaN ==
 * any-NaN relaxation on the f64 fields (NaN payload propagation through
 * fadd is IEEE-unspecified and compiler-dependent; see the driver header).
 */

#include <assert.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* ---------- c.h-shaped typedefs (LP64) ---------- */
typedef int64_t int64;
typedef uint64_t uint64;
typedef int32_t int32;
typedef uint32_t uint32;

#define INT64CONST(x) INT64_C(x)
#define PG_INT32_MAX INT32_MAX

/* stub:clock monotonic half (csrc/stubshims/pg_stub_state.c). */
extern uint64_t pg_stub_get_mono_ns(void);

/* ---------- INSTR_TIME_SET_CURRENT shim (stub:clock; the arithmetic below
 * is verbatim instr_time.h) ---------- */
#define INSTR_TIME_SET_CURRENT(t) \
	((t).ticks = (int64) pg_stub_get_mono_ns())

/* ---------- elog shim: verdict + message-literal capture ---------- */
static _Thread_local jmp_buf pg_instrbe_jmp;
static _Thread_local const char *pg_instrbe_errmsg_v;

#define elog(elevel, ...) \
	do { \
		pg_instrbe_errmsg_v = "" __VA_ARGS__; \
		longjmp(pg_instrbe_jmp, 1); \
	} while (0)

/* ---------- family-prefix renames for the non-static vendored symbols ---- */
#define pgBufferUsage pg_instrbe_pgBufferUsage
#define pgWalUsage pg_instrbe_pgWalUsage
#define InstrInit pg_instrbe_InstrInit
#define InstrStartNode pg_instrbe_InstrStartNode
#define InstrStopNode pg_instrbe_InstrStopNode
#define InstrUpdateTupleCount pg_instrbe_InstrUpdateTupleCount
#define InstrEndLoop pg_instrbe_InstrEndLoop
#define InstrAggNode pg_instrbe_InstrAggNode
#define BufferUsageAccumDiff pg_instrbe_BufferUsageAccumDiff
#define WalUsageAccumDiff pg_instrbe_WalUsageAccumDiff

/* == SECTION 1: src/include/portability/instr_time.h lines 60-72 (VERBATIM) == */
/*
 * We store interval times as an int64 integer on all platforms, as int64 is
 * cheap to add/subtract, the most common operation for instr_time. The
 * acquisition of time and converting to specific units of time is platform
 * specific.
 *
 * To avoid users of the API relying on the integer representation, we wrap
 * the 64bit integer in a struct.
 */
typedef struct instr_time
{
	int64		ticks;			/* in platforms specific unit */
} instr_time;

/* == SECTION 2: src/include/portability/instr_time.h lines 75-79 (VERBATIM) == */
/* helpers macros used in platform specific code below */

#define NS_PER_S	INT64CONST(1000000000)
#define NS_PER_MS	INT64CONST(1000000)
#define NS_PER_US	INT64CONST(1000)

/* == SECTION 3: src/include/portability/instr_time.h lines 125-126 (VERBATIM) == */
#define INSTR_TIME_GET_NANOSEC(t) \
	((int64) (t).ticks)

/* == SECTION 4: src/include/portability/instr_time.h lines 165-195 (VERBATIM) == */
/*
 * Common macros
 */

#define INSTR_TIME_IS_ZERO(t)	((t).ticks == 0)


#define INSTR_TIME_SET_ZERO(t)	((t).ticks = 0)

#define INSTR_TIME_SET_CURRENT_LAZY(t) \
	(INSTR_TIME_IS_ZERO(t) ? INSTR_TIME_SET_CURRENT(t), true : false)


#define INSTR_TIME_ADD(x,y) \
	((x).ticks += (y).ticks)

#define INSTR_TIME_SUBTRACT(x,y) \
	((x).ticks -= (y).ticks)

#define INSTR_TIME_ACCUM_DIFF(x,y,z) \
	((x).ticks += (y).ticks - (z).ticks)


#define INSTR_TIME_GET_DOUBLE(t) \
	((double) INSTR_TIME_GET_NANOSEC(t) / NS_PER_S)

#define INSTR_TIME_GET_MILLISEC(t) \
	((double) INSTR_TIME_GET_NANOSEC(t) / NS_PER_MS)

#define INSTR_TIME_GET_MICROSEC(t) \
	(INSTR_TIME_GET_NANOSEC(t) / NS_PER_US)

/* == SECTION 5: src/include/executor/instrument.h lines 19-94 (VERBATIM) == */
/*
 * BufferUsage and WalUsage counters keep being incremented infinitely,
 * i.e., must never be reset to zero, so that we can calculate how much
 * the counters are incremented in an arbitrary period.
 */
typedef struct BufferUsage
{
	int64		shared_blks_hit;	/* # of shared buffer hits */
	int64		shared_blks_read;	/* # of shared disk blocks read */
	int64		shared_blks_dirtied;	/* # of shared blocks dirtied */
	int64		shared_blks_written;	/* # of shared disk blocks written */
	int64		local_blks_hit; /* # of local buffer hits */
	int64		local_blks_read;	/* # of local disk blocks read */
	int64		local_blks_dirtied; /* # of local blocks dirtied */
	int64		local_blks_written; /* # of local disk blocks written */
	int64		temp_blks_read; /* # of temp blocks read */
	int64		temp_blks_written;	/* # of temp blocks written */
	instr_time	shared_blk_read_time;	/* time spent reading shared blocks */
	instr_time	shared_blk_write_time;	/* time spent writing shared blocks */
	instr_time	local_blk_read_time;	/* time spent reading local blocks */
	instr_time	local_blk_write_time;	/* time spent writing local blocks */
	instr_time	temp_blk_read_time; /* time spent reading temp blocks */
	instr_time	temp_blk_write_time;	/* time spent writing temp blocks */
} BufferUsage;

/*
 * WalUsage tracks only WAL activity like WAL records generation that
 * can be measured per query and is displayed by EXPLAIN command,
 * pg_stat_statements extension, etc. It does not track other WAL activity
 * like WAL writes that it's not worth measuring per query. That's tracked
 * by WAL global statistics counters in WalStats, instead.
 */
typedef struct WalUsage
{
	int64		wal_records;	/* # of WAL records produced */
	int64		wal_fpi;		/* # of WAL full page images produced */
	uint64		wal_bytes;		/* size of WAL records produced */
	int64		wal_buffers_full;	/* # of times the WAL buffers became full */
} WalUsage;

/* Flag bits included in InstrAlloc's instrument_options bitmask */
typedef enum InstrumentOption
{
	INSTRUMENT_TIMER = 1 << 0,	/* needs timer (and row counts) */
	INSTRUMENT_BUFFERS = 1 << 1,	/* needs buffer usage */
	INSTRUMENT_ROWS = 1 << 2,	/* needs row count */
	INSTRUMENT_WAL = 1 << 3,	/* needs WAL usage */
	INSTRUMENT_ALL = PG_INT32_MAX
} InstrumentOption;

typedef struct Instrumentation
{
	/* Parameters set at node creation: */
	bool		need_timer;		/* true if we need timer data */
	bool		need_bufusage;	/* true if we need buffer usage data */
	bool		need_walusage;	/* true if we need WAL usage data */
	bool		async_mode;		/* true if node is in async mode */
	/* Info about current plan cycle: */
	bool		running;		/* true if we've completed first tuple */
	instr_time	starttime;		/* start time of current iteration of node */
	instr_time	counter;		/* accumulated runtime for this node */
	double		firsttuple;		/* time for first tuple of this cycle */
	double		tuplecount;		/* # of tuples emitted so far this cycle */
	BufferUsage bufusage_start; /* buffer usage at start */
	WalUsage	walusage_start; /* WAL usage at start */
	/* Accumulated statistics across all completed cycles: */
	double		startup;		/* total startup time (in seconds) */
	double		total;			/* total time (in seconds) */
	double		ntuples;		/* total tuples produced */
	double		ntuples2;		/* secondary node-specific tuple counter */
	double		nloops;			/* # of run cycles for this node */
	double		nfiltered1;		/* # of tuples removed by scanqual or joinqual */
	double		nfiltered2;		/* # of tuples removed by "other" quals */
	BufferUsage bufusage;		/* total buffer usage */
	WalUsage	walusage;		/* total WAL usage */
} Instrumentation;

/* == SECTION 5b: src/include/executor/instrument.h lines 116-119 (VERBATIM:
 * the extern prototypes the vendored bodies call ahead of definition) == */
extern void BufferUsageAccumDiff(BufferUsage *dst,
								 const BufferUsage *add, const BufferUsage *sub);
extern void WalUsageAccumDiff(WalUsage *dst, const WalUsage *add,
							  const WalUsage *sub);

/* == SECTION 6: src/backend/executor/instrument.c lines 20, 22 (VERBATIM; the
 * save_* statics on lines 21/23 belong to the OUT parallel-query overlay) == */
BufferUsage pgBufferUsage;
WalUsage	pgWalUsage;

/* == SECTION 7: src/backend/executor/instrument.c lines 25-26 (VERBATIM) == */
static void BufferUsageAdd(BufferUsage *dst, const BufferUsage *add);
static void WalUsageAdd(WalUsage *dst, WalUsage *add);

/* == SECTION 8: src/backend/executor/instrument.c lines 56-196 (VERBATIM) == */
/* Initialize a pre-allocated instrumentation structure. */
void
InstrInit(Instrumentation *instr, int instrument_options)
{
	memset(instr, 0, sizeof(Instrumentation));
	instr->need_bufusage = (instrument_options & INSTRUMENT_BUFFERS) != 0;
	instr->need_walusage = (instrument_options & INSTRUMENT_WAL) != 0;
	instr->need_timer = (instrument_options & INSTRUMENT_TIMER) != 0;
}

/* Entry to a plan node */
void
InstrStartNode(Instrumentation *instr)
{
	if (instr->need_timer &&
		!INSTR_TIME_SET_CURRENT_LAZY(instr->starttime))
		elog(ERROR, "InstrStartNode called twice in a row");

	/* save buffer usage totals at node entry, if needed */
	if (instr->need_bufusage)
		instr->bufusage_start = pgBufferUsage;

	if (instr->need_walusage)
		instr->walusage_start = pgWalUsage;
}

/* Exit from a plan node */
void
InstrStopNode(Instrumentation *instr, double nTuples)
{
	double		save_tuplecount = instr->tuplecount;
	instr_time	endtime;

	/* count the returned tuples */
	instr->tuplecount += nTuples;

	/* let's update the time only if the timer was requested */
	if (instr->need_timer)
	{
		if (INSTR_TIME_IS_ZERO(instr->starttime))
			elog(ERROR, "InstrStopNode called without start");

		INSTR_TIME_SET_CURRENT(endtime);
		INSTR_TIME_ACCUM_DIFF(instr->counter, endtime, instr->starttime);

		INSTR_TIME_SET_ZERO(instr->starttime);
	}

	/* Add delta of buffer usage since entry to node's totals */
	if (instr->need_bufusage)
		BufferUsageAccumDiff(&instr->bufusage,
							 &pgBufferUsage, &instr->bufusage_start);

	if (instr->need_walusage)
		WalUsageAccumDiff(&instr->walusage,
						  &pgWalUsage, &instr->walusage_start);

	/* Is this the first tuple of this cycle? */
	if (!instr->running)
	{
		instr->running = true;
		instr->firsttuple = INSTR_TIME_GET_DOUBLE(instr->counter);
	}
	else
	{
		/*
		 * In async mode, if the plan node hadn't emitted any tuples before,
		 * this might be the first tuple
		 */
		if (instr->async_mode && save_tuplecount < 1.0)
			instr->firsttuple = INSTR_TIME_GET_DOUBLE(instr->counter);
	}
}

/* Update tuple count */
void
InstrUpdateTupleCount(Instrumentation *instr, double nTuples)
{
	/* count the returned tuples */
	instr->tuplecount += nTuples;
}

/* Finish a run cycle for a plan node */
void
InstrEndLoop(Instrumentation *instr)
{
	double		totaltime;

	/* Skip if nothing has happened, or already shut down */
	if (!instr->running)
		return;

	if (!INSTR_TIME_IS_ZERO(instr->starttime))
		elog(ERROR, "InstrEndLoop called on running node");

	/* Accumulate per-cycle statistics into totals */
	totaltime = INSTR_TIME_GET_DOUBLE(instr->counter);

	instr->startup += instr->firsttuple;
	instr->total += totaltime;
	instr->ntuples += instr->tuplecount;
	instr->nloops += 1;

	/* Reset for next cycle (if any) */
	instr->running = false;
	INSTR_TIME_SET_ZERO(instr->starttime);
	INSTR_TIME_SET_ZERO(instr->counter);
	instr->firsttuple = 0;
	instr->tuplecount = 0;
}

/* aggregate instrumentation information */
void
InstrAggNode(Instrumentation *dst, Instrumentation *add)
{
	if (!dst->running && add->running)
	{
		dst->running = true;
		dst->firsttuple = add->firsttuple;
	}
	else if (dst->running && add->running && dst->firsttuple > add->firsttuple)
		dst->firsttuple = add->firsttuple;

	INSTR_TIME_ADD(dst->counter, add->counter);

	dst->tuplecount += add->tuplecount;
	dst->startup += add->startup;
	dst->total += add->total;
	dst->ntuples += add->ntuples;
	dst->ntuples2 += add->ntuples2;
	dst->nloops += add->nloops;
	dst->nfiltered1 += add->nfiltered1;
	dst->nfiltered2 += add->nfiltered2;

	/* Add delta of buffer usage since entry to node's totals */
	if (dst->need_bufusage)
		BufferUsageAdd(&dst->bufusage, &add->bufusage);

	if (dst->need_walusage)
		WalUsageAdd(&dst->walusage, &add->walusage);
}

/* == SECTION 9: src/backend/executor/instrument.c lines 224-293 (VERBATIM) == */
/* dst += add */
static void
BufferUsageAdd(BufferUsage *dst, const BufferUsage *add)
{
	dst->shared_blks_hit += add->shared_blks_hit;
	dst->shared_blks_read += add->shared_blks_read;
	dst->shared_blks_dirtied += add->shared_blks_dirtied;
	dst->shared_blks_written += add->shared_blks_written;
	dst->local_blks_hit += add->local_blks_hit;
	dst->local_blks_read += add->local_blks_read;
	dst->local_blks_dirtied += add->local_blks_dirtied;
	dst->local_blks_written += add->local_blks_written;
	dst->temp_blks_read += add->temp_blks_read;
	dst->temp_blks_written += add->temp_blks_written;
	INSTR_TIME_ADD(dst->shared_blk_read_time, add->shared_blk_read_time);
	INSTR_TIME_ADD(dst->shared_blk_write_time, add->shared_blk_write_time);
	INSTR_TIME_ADD(dst->local_blk_read_time, add->local_blk_read_time);
	INSTR_TIME_ADD(dst->local_blk_write_time, add->local_blk_write_time);
	INSTR_TIME_ADD(dst->temp_blk_read_time, add->temp_blk_read_time);
	INSTR_TIME_ADD(dst->temp_blk_write_time, add->temp_blk_write_time);
}

/* dst += add - sub */
void
BufferUsageAccumDiff(BufferUsage *dst,
					 const BufferUsage *add,
					 const BufferUsage *sub)
{
	dst->shared_blks_hit += add->shared_blks_hit - sub->shared_blks_hit;
	dst->shared_blks_read += add->shared_blks_read - sub->shared_blks_read;
	dst->shared_blks_dirtied += add->shared_blks_dirtied - sub->shared_blks_dirtied;
	dst->shared_blks_written += add->shared_blks_written - sub->shared_blks_written;
	dst->local_blks_hit += add->local_blks_hit - sub->local_blks_hit;
	dst->local_blks_read += add->local_blks_read - sub->local_blks_read;
	dst->local_blks_dirtied += add->local_blks_dirtied - sub->local_blks_dirtied;
	dst->local_blks_written += add->local_blks_written - sub->local_blks_written;
	dst->temp_blks_read += add->temp_blks_read - sub->temp_blks_read;
	dst->temp_blks_written += add->temp_blks_written - sub->temp_blks_written;
	INSTR_TIME_ACCUM_DIFF(dst->shared_blk_read_time,
						  add->shared_blk_read_time, sub->shared_blk_read_time);
	INSTR_TIME_ACCUM_DIFF(dst->shared_blk_write_time,
						  add->shared_blk_write_time, sub->shared_blk_write_time);
	INSTR_TIME_ACCUM_DIFF(dst->local_blk_read_time,
						  add->local_blk_read_time, sub->local_blk_read_time);
	INSTR_TIME_ACCUM_DIFF(dst->local_blk_write_time,
						  add->local_blk_write_time, sub->local_blk_write_time);
	INSTR_TIME_ACCUM_DIFF(dst->temp_blk_read_time,
						  add->temp_blk_read_time, sub->temp_blk_read_time);
	INSTR_TIME_ACCUM_DIFF(dst->temp_blk_write_time,
						  add->temp_blk_write_time, sub->temp_blk_write_time);
}

/* helper functions for WAL usage accumulation */
static void
WalUsageAdd(WalUsage *dst, WalUsage *add)
{
	dst->wal_bytes += add->wal_bytes;
	dst->wal_records += add->wal_records;
	dst->wal_fpi += add->wal_fpi;
	dst->wal_buffers_full += add->wal_buffers_full;
}

void
WalUsageAccumDiff(WalUsage *dst, const WalUsage *add, const WalUsage *sub)
{
	dst->wal_bytes += add->wal_bytes - sub->wal_bytes;
	dst->wal_records += add->wal_records - sub->wal_records;
	dst->wal_fpi += add->wal_fpi - sub->wal_fpi;
	dst->wal_buffers_full += add->wal_buffers_full - sub->wal_buffers_full;
}

/* ========== SECTION 10: fuzz-facing driver entries (NOT Postgres code) ===== */

/*
 * Wire images (little-endian byte layout shared with the Rust driver —
 * core/src/instrument_diff.rs keeps the mirror; pure field-by-field memcpy):
 *   BufferUsage  = 16 x 8 bytes, declared field order (10 int64 counters,
 *                  then 6 instr_time ticks).
 *   WalUsage     = 4 x 8 bytes (wal_records, wal_fpi, wal_bytes,
 *                  wal_buffers_full).
 *   Instrumentation = 5 flag bytes (need_timer, need_bufusage,
 *                  need_walusage, async_mode, running), starttime.ticks,
 *                  counter.ticks, firsttuple, tuplecount, bufusage_start,
 *                  walusage_start, startup, total, ntuples, ntuples2,
 *                  nloops, nfiltered1, nfiltered2, bufusage, walusage
 *                  = 413 bytes.
 */

static void
pg_instrbe_put8(unsigned char *p, uint64 v)
{
	int			i;

	for (i = 0; i < 8; i++)
		p[i] = (unsigned char) (v >> (8 * i));
}

static uint64
pg_instrbe_get8(const unsigned char *p)
{
	uint64		v = 0;
	int			i;

	for (i = 0; i < 8; i++)
		v |= (uint64) p[i] << (8 * i);
	return v;
}

static void
pg_instrbe_buf_pack(unsigned char *out, const BufferUsage *b)
{
	pg_instrbe_put8(out + 0, (uint64) b->shared_blks_hit);
	pg_instrbe_put8(out + 8, (uint64) b->shared_blks_read);
	pg_instrbe_put8(out + 16, (uint64) b->shared_blks_dirtied);
	pg_instrbe_put8(out + 24, (uint64) b->shared_blks_written);
	pg_instrbe_put8(out + 32, (uint64) b->local_blks_hit);
	pg_instrbe_put8(out + 40, (uint64) b->local_blks_read);
	pg_instrbe_put8(out + 48, (uint64) b->local_blks_dirtied);
	pg_instrbe_put8(out + 56, (uint64) b->local_blks_written);
	pg_instrbe_put8(out + 64, (uint64) b->temp_blks_read);
	pg_instrbe_put8(out + 72, (uint64) b->temp_blks_written);
	pg_instrbe_put8(out + 80, (uint64) b->shared_blk_read_time.ticks);
	pg_instrbe_put8(out + 88, (uint64) b->shared_blk_write_time.ticks);
	pg_instrbe_put8(out + 96, (uint64) b->local_blk_read_time.ticks);
	pg_instrbe_put8(out + 104, (uint64) b->local_blk_write_time.ticks);
	pg_instrbe_put8(out + 112, (uint64) b->temp_blk_read_time.ticks);
	pg_instrbe_put8(out + 120, (uint64) b->temp_blk_write_time.ticks);
}

static void
pg_instrbe_buf_unpack(BufferUsage *b, const unsigned char *in)
{
	b->shared_blks_hit = (int64) pg_instrbe_get8(in + 0);
	b->shared_blks_read = (int64) pg_instrbe_get8(in + 8);
	b->shared_blks_dirtied = (int64) pg_instrbe_get8(in + 16);
	b->shared_blks_written = (int64) pg_instrbe_get8(in + 24);
	b->local_blks_hit = (int64) pg_instrbe_get8(in + 32);
	b->local_blks_read = (int64) pg_instrbe_get8(in + 40);
	b->local_blks_dirtied = (int64) pg_instrbe_get8(in + 48);
	b->local_blks_written = (int64) pg_instrbe_get8(in + 56);
	b->temp_blks_read = (int64) pg_instrbe_get8(in + 64);
	b->temp_blks_written = (int64) pg_instrbe_get8(in + 72);
	b->shared_blk_read_time.ticks = (int64) pg_instrbe_get8(in + 80);
	b->shared_blk_write_time.ticks = (int64) pg_instrbe_get8(in + 88);
	b->local_blk_read_time.ticks = (int64) pg_instrbe_get8(in + 96);
	b->local_blk_write_time.ticks = (int64) pg_instrbe_get8(in + 104);
	b->temp_blk_read_time.ticks = (int64) pg_instrbe_get8(in + 112);
	b->temp_blk_write_time.ticks = (int64) pg_instrbe_get8(in + 120);
}

static void
pg_instrbe_wal_pack(unsigned char *out, const WalUsage *w)
{
	pg_instrbe_put8(out + 0, (uint64) w->wal_records);
	pg_instrbe_put8(out + 8, (uint64) w->wal_fpi);
	pg_instrbe_put8(out + 16, w->wal_bytes);
	pg_instrbe_put8(out + 24, (uint64) w->wal_buffers_full);
}

static void
pg_instrbe_wal_unpack(WalUsage *w, const unsigned char *in)
{
	w->wal_records = (int64) pg_instrbe_get8(in + 0);
	w->wal_fpi = (int64) pg_instrbe_get8(in + 8);
	w->wal_bytes = pg_instrbe_get8(in + 16);
	w->wal_buffers_full = (int64) pg_instrbe_get8(in + 24);
}

static double
pg_instrbe_bits_to_double(uint64 bits)
{
	double		d;

	memcpy(&d, &bits, 8);
	return d;
}

static uint64
pg_instrbe_double_to_bits(double d)
{
	uint64		bits;

	memcpy(&bits, &d, 8);
	return bits;
}

static void
pg_instrbe_instr_pack(unsigned char *out, const Instrumentation *n)
{
	out[0] = n->need_timer ? 1 : 0;
	out[1] = n->need_bufusage ? 1 : 0;
	out[2] = n->need_walusage ? 1 : 0;
	out[3] = n->async_mode ? 1 : 0;
	out[4] = n->running ? 1 : 0;
	pg_instrbe_put8(out + 5, (uint64) n->starttime.ticks);
	pg_instrbe_put8(out + 13, (uint64) n->counter.ticks);
	pg_instrbe_put8(out + 21, pg_instrbe_double_to_bits(n->firsttuple));
	pg_instrbe_put8(out + 29, pg_instrbe_double_to_bits(n->tuplecount));
	pg_instrbe_buf_pack(out + 37, &n->bufusage_start);
	pg_instrbe_wal_pack(out + 165, &n->walusage_start);
	pg_instrbe_put8(out + 197, pg_instrbe_double_to_bits(n->startup));
	pg_instrbe_put8(out + 205, pg_instrbe_double_to_bits(n->total));
	pg_instrbe_put8(out + 213, pg_instrbe_double_to_bits(n->ntuples));
	pg_instrbe_put8(out + 221, pg_instrbe_double_to_bits(n->ntuples2));
	pg_instrbe_put8(out + 229, pg_instrbe_double_to_bits(n->nloops));
	pg_instrbe_put8(out + 237, pg_instrbe_double_to_bits(n->nfiltered1));
	pg_instrbe_put8(out + 245, pg_instrbe_double_to_bits(n->nfiltered2));
	pg_instrbe_buf_pack(out + 253, &n->bufusage);
	pg_instrbe_wal_pack(out + 381, &n->walusage);
}

static void
pg_instrbe_instr_unpack(Instrumentation *n, const unsigned char *in)
{
	n->need_timer = (in[0] != 0);
	n->need_bufusage = (in[1] != 0);
	n->need_walusage = (in[2] != 0);
	n->async_mode = (in[3] != 0);
	n->running = (in[4] != 0);
	n->starttime.ticks = (int64) pg_instrbe_get8(in + 5);
	n->counter.ticks = (int64) pg_instrbe_get8(in + 13);
	n->firsttuple = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 21));
	n->tuplecount = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 29));
	pg_instrbe_buf_unpack(&n->bufusage_start, in + 37);
	pg_instrbe_wal_unpack(&n->walusage_start, in + 165);
	n->startup = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 197));
	n->total = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 205));
	n->ntuples = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 213));
	n->ntuples2 = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 221));
	n->nloops = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 229));
	n->nfiltered1 = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 237));
	n->nfiltered2 = pg_instrbe_bits_to_double(pg_instrbe_get8(in + 245));
	pg_instrbe_buf_unpack(&n->bufusage, in + 253);
	pg_instrbe_wal_unpack(&n->walusage, in + 381);
}

/* Two node slots: 0 = the working node (dst), 1 = the AggNode add-side. */
static _Thread_local Instrumentation pg_instrbe_nodes[2];

/* Zero the nodes AND the globals: the pgBufferUsage zero-pin of record
 * (see file header); pgWalUsage starts zero and is advanced only by
 * pg_instrbe_set_wal_global (mirrored by the Rust seam pin). */
void
pg_instrbe_reset(void)
{
	memset(&pg_instrbe_nodes[0], 0, sizeof(Instrumentation));
	memset(&pg_instrbe_nodes[1], 0, sizeof(Instrumentation));
	memset(&pgBufferUsage, 0, sizeof(BufferUsage));
	memset(&pgWalUsage, 0, sizeof(WalUsage));
	pg_instrbe_errmsg_v = "";
}

/* stub wal-global: fuzz-fed pgWalUsage, identical on the Rust side via the
 * installed transam_xlog_seams::wal_usage seam. */
void
pg_instrbe_set_wal_global(const unsigned char *w)
{
	pg_instrbe_wal_unpack(&pgWalUsage, w);
}

/* async_mode is set by InstrAlloc in C (census OUT); the driver sets the
 * field directly on both sides. */
void
pg_instrbe_set_async(int on)
{
	pg_instrbe_nodes[0].async_mode = (on != 0);
}

void
pg_instrbe_load_node(int which, const unsigned char *wire)
{
	pg_instrbe_instr_unpack(&pg_instrbe_nodes[which & 1], wire);
}

void
pg_instrbe_store_node(int which, unsigned char *out)
{
	pg_instrbe_instr_pack(out, &pg_instrbe_nodes[which & 1]);
}

const char *
pg_instrbe_errmsg(void)
{
	return pg_instrbe_errmsg_v;
}

void
pg_instrbe_init(int options)
{
	InstrInit(&pg_instrbe_nodes[0], options);
}

/* 0 = ok, 1 = elog'ed (literal in pg_instrbe_errmsg). State mutations made
 * before the elog persist, exactly as they do across the Rust panic. */
int
pg_instrbe_start_node(void)
{
	if (setjmp(pg_instrbe_jmp))
		return 1;
	InstrStartNode(&pg_instrbe_nodes[0]);
	return 0;
}

int
pg_instrbe_stop_node(uint64 ntuples_bits)
{
	if (setjmp(pg_instrbe_jmp))
		return 1;
	InstrStopNode(&pg_instrbe_nodes[0], pg_instrbe_bits_to_double(ntuples_bits));
	return 0;
}

void
pg_instrbe_update_tuple_count(uint64 ntuples_bits)
{
	InstrUpdateTupleCount(&pg_instrbe_nodes[0],
						  pg_instrbe_bits_to_double(ntuples_bits));
}

int
pg_instrbe_end_loop(int which)
{
	if (setjmp(pg_instrbe_jmp))
		return 1;
	InstrEndLoop(&pg_instrbe_nodes[which & 1]);
	return 0;
}

void
pg_instrbe_agg_node(void)
{
	InstrAggNode(&pg_instrbe_nodes[0], &pg_instrbe_nodes[1]);
}

/* Pure struct arithmetic, wire in / wire out. */
void
pg_instrbe_bufusage_add(unsigned char *dst, const unsigned char *add)
{
	BufferUsage d,
				a;

	pg_instrbe_buf_unpack(&d, dst);
	pg_instrbe_buf_unpack(&a, add);
	BufferUsageAdd(&d, &a);
	pg_instrbe_buf_pack(dst, &d);
}

void
pg_instrbe_bufusage_accum_diff(unsigned char *dst, const unsigned char *add,
							   const unsigned char *sub)
{
	BufferUsage d,
				a,
				s;

	pg_instrbe_buf_unpack(&d, dst);
	pg_instrbe_buf_unpack(&a, add);
	pg_instrbe_buf_unpack(&s, sub);
	BufferUsageAccumDiff(&d, &a, &s);
	pg_instrbe_buf_pack(dst, &d);
}

void
pg_instrbe_walusage_add(unsigned char *dst, const unsigned char *add)
{
	WalUsage	d,
				a;

	pg_instrbe_wal_unpack(&d, dst);
	pg_instrbe_wal_unpack(&a, add);
	WalUsageAdd(&d, &a);
	pg_instrbe_wal_pack(dst, &d);
}

void
pg_instrbe_walusage_accum_diff(unsigned char *dst, const unsigned char *add,
							   const unsigned char *sub)
{
	WalUsage	d,
				a,
				s;

	pg_instrbe_wal_unpack(&d, dst);
	pg_instrbe_wal_unpack(&a, add);
	pg_instrbe_wal_unpack(&s, sub);
	WalUsageAccumDiff(&d, &a, &s);
	pg_instrbe_wal_pack(dst, &d);
}

/* Fuzz-fed struct-field injections (both sides receive the SAME wire; the
 * driver mirrors each write on its Rust Instrumentation). */
void
pg_instrbe_inject_bufusage_start(const unsigned char *w)
{
	pg_instrbe_buf_unpack(&pg_instrbe_nodes[0].bufusage_start, w);
}

void
pg_instrbe_inject_walusage_start(const unsigned char *w)
{
	pg_instrbe_wal_unpack(&pg_instrbe_nodes[0].walusage_start, w);
}

void
pg_instrbe_inject_accums(const unsigned char *buf, const unsigned char *wal)
{
	pg_instrbe_buf_unpack(&pg_instrbe_nodes[0].bufusage, buf);
	pg_instrbe_wal_unpack(&pg_instrbe_nodes[0].walusage, wal);
}
