/*
 * pg_nodesfam_io.c: vendored PostgreSQL C oracle for the nodesfam_diff
 * differential fuzz target (100%-coverage campaign, lane p1-nodes).
 * Crates under test (see fuzz/core/src/nodesfam_diff.rs):
 *   crates/backend/nodes/readfuncs  (stringToNode: read.c + readfuncs.c)
 *   crates/backend/nodes/outfuncs   (nodeToString: outfuncs.c)
 *   crates/backend/nodes/copyfuncs  (copyObject:  copyfuncs.c)
 *
 * Provenance: every PostgreSQL body in this family is a VERBATIM
 * WHOLE-FILE copy from ~/dev/pgrust-reference/vendor/postgres-src
 * (Stamp-18.3, upstream sha 62d6c7d3df6287f1bd83199c1a746e50d31571a0),
 * assembled by csrc/nodesfam/assemble.sh (re-runnable, no-op diff):
 *   - src/backend/nodes/{outfuncs,readfuncs,copyfuncs,equalfuncs,read,
 *     value,list,bitmapset}.c
 *   - src/backend/utils/adt/datum.c (datumCopy for Const)
 *   - src/backend/utils/misc/stack_depth.c (the recursion guard BOTH
 *     sides must enforce; C calls check_stack_depth() in outNode,
 *     copyObjectImpl and parseNodeString)
 *   - src/common/{stringinfo,d2s,psprintf,string}.c and
 *     src/port/{snprintf,pg_bitutils,pg_popcount_aarch64,strerror,
 *     strlcpy,strlcat}.c
 *   - GENERATED BY POSTGRESQL'S OWN GENERATORS from the same pinned tree
 *     (never hand-written): nodesfam/gen/{outfuncs,readfuncs,copyfuncs,
 *     equalfuncs}.{funcs,switch}.c (gen_node_support.pl),
 *     gen/nodes/nodetags.h, gen/utils/errcodes.h (generate-errcodes.pl),
 *     gen/storage/lwlocknames.h (generate-lwlocknames.pl),
 *     gen/catalog/*_d.h (genbki.pl).
 *   - The full src/include header closure (165 files, computed by
 *     clang -MM over every TU; list in nodesfam/hdr_closure.txt) is
 *     vendored whole under nodesfam/include/.
 *
 * Shims (plumbing only, never logic):
 *   - nodesfam/shim/pg_config.h + pg_config_os.h: fabricated config for
 *     LP64 little-endian gcc/clang, values matching a real 18.3 build on
 *     the CI cluster (aarch64-linux) and this dev host (aarch64-darwin).
 *   - palloc family -> bump ARENA below, reset per exec (node trees are
 *     never freed piecemeal by these walkers; C context reset parity).
 *   - ereport/elog -> errstart records, errcode captures the packed
 *     sqlstate, errfinish longjmps to the armed driver entry (PG's error
 *     longjmp, exactly the miscfam pattern). Message text never crosses
 *     the comparison seam.
 *   - extensible-node registry EMPTY: GetExtensibleNodeMethods /
 *     GetCustomScanMethods raise exactly what extensible.c raises on a
 *     lookup miss — real behavior of a backend with no extensions loaded
 *     (the CUSTOMSCAN/EXTENSIBLENODE arms are the documented carve; the
 *     Rust port has no registry at all).
 *   - datum.c expanded-object/external-toast arms abort(): readDatum
 *     builds only plain byval/byref datums, so copyObject over trees
 *     built by stringToNode can never see them (readfuncs.c _readConst).
 *   - hash_bytes aborts: bms_hash_value is unreachable from
 *     read/out/copy/equal (link-only dependency of bitmapset.c).
 *   - stack guard: REAL vendored stack_depth.c. pg_nf_init() records the
 *     stack base and fixes max_stack_depth at the server default 2048kB
 *     (what a real postmaster computes from an 8MB rlimit; the Rust side
 *     of the driver pins the identical value).
 *
 * Driver entries (SECTION D, pg_nf_ prefix) are fuzz plumbing, NOT
 * Postgres code.
 */

#include "postgres.h"

#include <setjmp.h>

#include "miscadmin.h"
#include "nodes/nodes.h"
#include "nodes/pg_list.h"
#include "nodes/readfuncs.h"
#include "nodes/extensible.h"
#include "utils/expandeddatum.h"
#include "utils/guc_hooks.h"
#include "utils/memutils.h"

extern char *nodeToString(const void *obj);

/* ============================ SECTION A: arena ========================= */

/*
 * Bump arena, reset per exec. 256 MiB virtual cap; the depth guard and
 * MaxAllocSize fire long before it fills for any input libFuzzer can make.
 */
#define NF_ARENA_CAP (256u * 1024 * 1024)
static char *nf_arena;
static size_t nf_arena_used;

static void *
nf_arena_alloc(size_t size)
{
	size_t		aligned = MAXALIGN(size + MAXIMUM_ALIGNOF);
	char	   *p;

	if (nf_arena == NULL)
	{
		nf_arena = malloc(NF_ARENA_CAP);
		if (nf_arena == NULL)
			abort();
	}
	if (aligned > NF_ARENA_CAP - nf_arena_used)
		abort();				/* arena exhausted: raise NF_ARENA_CAP */
	p = nf_arena + nf_arena_used;
	nf_arena_used += aligned;
	/* size header for repalloc, one MAXALIGN quantum before the chunk */
	*(size_t *) p = size;
	return p + MAXIMUM_ALIGNOF;
}

MemoryContext CurrentMemoryContext = (MemoryContext) 1;

void *
palloc(Size size)
{
	return nf_arena_alloc(size);
}

void *
palloc0(Size size)
{
	void	   *p = nf_arena_alloc(size);

	memset(p, 0, size);
	return p;
}

void *
palloc_extended(Size size, int flags)
{
	void	   *p = nf_arena_alloc(size);

	if (flags & MCXT_ALLOC_ZERO)
		memset(p, 0, size);
	return p;
}

void *
repalloc(void *pointer, Size size)
{
	size_t		old = *(size_t *) ((char *) pointer - MAXIMUM_ALIGNOF);
	void	   *p = nf_arena_alloc(size);

	memcpy(p, pointer, old < size ? old : size);
	return p;
}

void
pfree(void *pointer)
{
	(void) pointer;				/* arena-reset semantics */
}

char *
pstrdup(const char *in)
{
	size_t		len = strlen(in) + 1;
	char	   *p = nf_arena_alloc(len);

	memcpy(p, in, len);
	return p;
}

void *
MemoryContextAlloc(MemoryContext context, Size size)
{
	(void) context;
	return nf_arena_alloc(size);
}

MemoryContext
GetMemoryChunkContext(void *pointer)
{
	(void) pointer;
	return CurrentMemoryContext;
}

/* ====================== SECTION B: ereport capture ===================== */

static jmp_buf nf_jmp;
static int	nf_jmp_armed;
static int	nf_errcode_val;		/* packed sqlstate from errcode() */

bool
errstart(int elevel, const char *domain)
{
	(void) domain;
	/* elog.c: ERROR-level reports default to XX000 unless errcode() runs */
	nf_errcode_val = (elevel >= 20 /* ERROR */ ) ?
		MAKE_SQLSTATE('X', 'X', '0', '0', '0') : 0;
	return true;
}

bool
errstart_cold(int elevel, const char *domain)
{
	return errstart(elevel, domain);
}

void
errfinish(const char *filename, int lineno, const char *funcname)
{
	(void) filename;
	(void) lineno;
	(void) funcname;
	if (!nf_jmp_armed)
		abort();
	longjmp(nf_jmp, 1);
}

int
errcode(int sqlerrcode)
{
	nf_errcode_val = sqlerrcode;
	return 0;
}

int
errmsg(const char *fmt,...)
{
	(void) fmt;
	return 0;
}

int
errmsg_internal(const char *fmt,...)
{
	(void) fmt;
	return 0;
}

int
errdetail(const char *fmt,...)
{
	(void) fmt;
	return 0;
}

int
errhint(const char *fmt,...)
{
	(void) fmt;
	return 0;
}

/* elog.c string plumbing referenced by stack_depth.c's GUC check hook */
char	   *GUC_check_errdetail_string;
char	   *GUC_check_errhint_string;

void
pre_format_elog_string(int errnumber, const char *domain)
{
	(void) errnumber;
	(void) domain;
}

char *
format_elog_string(const char *fmt,...)
{
	(void) fmt;
	return NULL;
}

/* =================== SECTION C: environment stubs ====================== */

/*
 * Extensible-node registry: EMPTY, exactly a backend with no extensions
 * loaded. Message wording matches extensible.c so nothing else differs.
 */
const ExtensibleNodeMethods *
GetExtensibleNodeMethods(const char *extnodename, bool missing_ok)
{
	if (!missing_ok)
		ereport(ERROR,
				(errcode(ERRCODE_UNDEFINED_OBJECT),
				 errmsg("ExtensibleNodeMethods \"%s\" was not registered",
						extnodename)));
	return NULL;
}

const struct CustomScanMethods *
GetCustomScanMethods(const char *CustomName, bool missing_ok)
{
	if (!missing_ok)
		ereport(ERROR,
				(errcode(ERRCODE_UNDEFINED_OBJECT),
				 errmsg("CustomScanMethods \"%s\" was not registered",
						CustomName)));
	return NULL;
}

/* datum.c expanded-object / external-toast arms: unreachable (see header) */
ExpandedObjectHeader *
DatumGetEOHP(Datum d)
{
	(void) d;
	abort();
}

void
EOH_flatten_into(ExpandedObjectHeader *eohptr, void *result, Size allocated_size)
{
	(void) eohptr;
	(void) result;
	(void) allocated_size;
	abort();
}

Size
EOH_get_flat_size(ExpandedObjectHeader *eohptr)
{
	(void) eohptr;
	abort();
}

Datum
TransferExpandedObject(Datum d, MemoryContext new_parent)
{
	(void) d;
	(void) new_parent;
	abort();
}

struct varlena *
pg_detoast_datum_packed(struct varlena *datum)
{
	(void) datum;
	abort();
}

Size
toast_raw_datum_size(Datum value)
{
	(void) value;
	abort();
}

uint32
hash_bytes(const unsigned char *k, int keylen)
{
	(void) k;
	(void) keylen;
	abort();					/* bms_hash_value: link-only */
}

void
pg_qsort(void *base, size_t nel, size_t elsize,
		 int (*cmp) (const void *, const void *))
{
	qsort(base, nel, elsize, cmp);	/* list_sort support: link-only here */
}

/* ======================= SECTION D: driver entries ===================== */

/*
 * Verdicts. OK = the pipeline stage succeeded; ERROR = ereport(ERROR)
 * captured (nf_errcode holds the packed sqlstate).
 */
#define NF_OK 0
#define NF_ERROR 1

typedef struct NfOut
{
	int			verdict;
	int			errcode;		/* packed sqlstate (MAKE_SQLSTATE encoding) */
	const char *out_text;		/* nodeToString(read(input)) */
	const char *copy_text;		/* nodeToString(copyObject(read(input))) */
	int			equal_ok;		/* equal(node, copy) */
	int			reread_ok;		/* out(read(out_text)) == out_text */
} NfOut;

static NfOut nf_result;

void
pg_nf_init(void)
{
	set_stack_base();
	/* server default: postmaster raises 100kB -> 2048kB given >=2.5MB rlimit */
	assign_max_stack_depth(2048, NULL);
}

/*
 * Full oracle pipeline over one node-text input:
 *   read -> out -> copy -> out(copy) -> equal -> re-read(out) -> out.
 * Any ereport(ERROR) longjmps here and reports the stage's verdict.
 * Input must be NUL-terminated; the arena is reset on entry.
 */
const NfOut *
pg_nf_exec(const char *input)
{
	void	   *node;
	void	   *copy;
	char	   *out1;
	char	   *out2;
	char	   *out3;
	void	   *reread;

	nf_arena_used = 0;
	nf_result.verdict = NF_ERROR;
	nf_result.errcode = 0;
	nf_result.out_text = NULL;
	nf_result.copy_text = NULL;
	nf_result.equal_ok = -1;
	nf_result.reread_ok = -1;

	nf_jmp_armed = 1;
	if (setjmp(nf_jmp) != 0)
	{
		nf_jmp_armed = 0;
		nf_result.errcode = nf_errcode_val;
		return &nf_result;
	}

	node = stringToNode(input);
	/* out even for NULL ("<>" input): C nodeToString(NULL) prints "<>" */
	out1 = nodeToString(node);
	copy = copyObjectImpl(node);
	out2 = nodeToString(copy);
	nf_result.out_text = out1;
	nf_result.copy_text = out2;
	nf_result.equal_ok = (node == NULL && copy == NULL) ||
		(node != NULL && copy != NULL && equal(node, copy));

	reread = stringToNode(out1);
	out3 = nodeToString(reread);
	nf_result.reread_ok = strcmp(out1, out3) == 0;

	nf_jmp_armed = 0;
	nf_result.verdict = NF_OK;
	return &nf_result;
}
