/*
 * pg_nodesfam_io.c: vendored PostgreSQL C oracle for the nodesfam_diff
 * differential fuzz target (100%-coverage campaign, lane p1-nodes).
 * Crates under test (see fuzz/core/src/nodesfam_diff.rs):
 *   crates/backend/nodes/readfuncs  (stringToNode: read.c + readfuncs.c)
 *   crates/backend/nodes/outfuncs   (nodeToString: outfuncs.c)
 *   crates/backend/nodes/copyfuncs  (copyObject:  copyfuncs.c)
 *
 * Provenance: every PostgreSQL body in this family is a VERBATIM
 * WHOLE-FILE copy from ~/dev/pgrust-fabled/vendor/postgres-src
 * (Stamp-18.3, upstream sha 62d6c7d3df6287f1bd83199c1a746e50d31571a0),
 * assembled by csrc/nodesfam/assemble.sh (re-runnable, no-op diff):
 *   - src/backend/nodes/{outfuncs,readfuncs,copyfuncs,equalfuncs,read,
 *     value,list,bitmapset}.c
 *   - src/backend/utils/adt/datum.c (datumCopy for Const)
 *   - src/backend/utils/misc/stack_depth.c (the recursion guard BOTH
 *     sides must enforce; C calls check_stack_depth() in outNode,
 *     copyObjectImpl and parseNodeString)
 *   - src/common/{stringinfo,d2s,psprintf,string}.c and
 *     src/port/{snprintf,pg_bitutils,pg_popcount_aarch64,strerror,
 *     strlcpy,strlcat}.c
 *   - GENERATED BY POSTGRESQL'S OWN GENERATORS from the same pinned tree
 *     (never hand-written): nodesfam/gen/{outfuncs,readfuncs,copyfuncs,
 *     equalfuncs}.{funcs,switch}.c (gen_node_support.pl),
 *     gen/nodes/nodetags.h, gen/utils/errcodes.h (generate-errcodes.pl),
 *     gen/storage/lwlocknames.h (generate-lwlocknames.pl),
 *     gen/catalog/*_d.h (genbki.pl).
 *   - The full src/include header closure (165 files, computed by
 *     clang -MM over every TU; list in nodesfam/hdr_closure.txt) is
 *     vendored whole under nodesfam/include/.
 *
 * Shims (plumbing only, never logic):
 *   - nodesfam/shim/pg_config.h + pg_config_os.h: fabricated config for
 *     LP64 little-endian gcc/clang, values matching a real 18.3 build on
 *     the fleet (aarch64-linux) and this dev host (aarch64-darwin).
 *   - palloc family -> bump ARENA below, reset per exec (node trees are
 *     never freed piecemeal by these walkers; C context reset parity).
 *   - ereport/elog -> errstart records elevel + default sqlstate, errcode
 *     captures the packed sqlstate, errfinish longjmps to the armed driver
 *     entry for elevel >= ERROR (PG's error longjmp) and RETURNS for
 *     WARNING and below so C continues, exactly like the backend (task
 *     #137; sub-ERROR reports land on a side-channel counter, never a
 *     compared plane). Message text never crosses the comparison seam.
 *   - extensible-node registry EMPTY: GetExtensibleNodeMethods /
 *     GetCustomScanMethods raise exactly what extensible.c raises on a
 *     lookup miss — real behavior of a backend with no extensions loaded
 *     (the CUSTOMSCAN/EXTENSIBLENODE arms are the documented carve; the
 *     Rust port has no registry at all).
 *   - datum.c expanded-object/external-toast arms abort(): readDatum
 *     builds only plain byval/byref datums, so copyObject over trees
 *     built by stringToNode can never see them (readfuncs.c _readConst).
 *   - hash_bytes aborts: bms_hash_value is unreachable from
 *     read/out/copy/equal (link-only dependency of bitmapset.c).
 *   - stack guard: REAL vendored stack_depth.c. pg_ndf_init() records the
 *     stack base and fixes max_stack_depth at the server default 2048kB
 *     (what a real postmaster computes from an 8MB rlimit; the Rust side
 *     of the driver pins the identical value).
 *
 * Driver entries (SECTION D, pg_ndf_ prefix) are fuzz plumbing, NOT
 * Postgres code.
 */

#include "postgres.h"

#include <setjmp.h>

#include "miscadmin.h"
#include "nodes/nodes.h"
#include "nodes/pg_list.h"
#include "nodes/readfuncs.h"
#include "nodes/extensible.h"
#include "utils/expandeddatum.h"
#include "utils/guc_hooks.h"
#include "utils/memutils.h"
#include "pg_oracle_guard.h"	/* oracle-serialization holder check */

extern char *nodeToString(const void *obj);

/* ============================ SECTION A: arena ========================= */

/*
 * Bump arena, reset per exec. 256 MiB virtual cap; the depth guard and
 * MaxAllocSize fire long before it fills for any input libFuzzer can make.
 */
#define NDF_ARENA_CAP (256u * 1024 * 1024)
static char *ndf_arena;
static size_t ndf_arena_used;

static void *
ndf_arena_alloc(size_t size)
{
	size_t		aligned = MAXALIGN(size + MAXIMUM_ALIGNOF);
	char	   *p;

	if (ndf_arena == NULL)
	{
		ndf_arena = malloc(NDF_ARENA_CAP);
		if (ndf_arena == NULL)
			abort();
	}
	/*
	 * PG's palloc REFUSES a request over MaxAllocSize with
	 * ERRCODE_PROGRAM_LIMIT_EXCEEDED rather than attempting it, and the
	 * pgrust side does the same — so the oracle must raise, not abort.
	 * (Found at ~25M local execs: `(b 0 00800000000000)` is a Bitmapset with
	 * a member index near 2^47, whose word array is ~1 TB; the arena aborted
	 * where both real PG and pgrust raise.) Requests that fit MaxAllocSize
	 * but not this arena are a HARNESS limit and raise the same way, which
	 * keeps the verdict comparable rather than killing the process.
	 */
	if (!AllocSizeIsValid(size) || aligned > NDF_ARENA_CAP - ndf_arena_used)
		ereport(ERROR,
				(errcode(ERRCODE_PROGRAM_LIMIT_EXCEEDED),
				 errmsg("invalid memory alloc request size %zu", size)));
	p = ndf_arena + ndf_arena_used;
	ndf_arena_used += aligned;
	/* size header for repalloc, one MAXALIGN quantum before the chunk */
	*(size_t *) p = size;
	return p + MAXIMUM_ALIGNOF;
}

MemoryContext CurrentMemoryContext = (MemoryContext) 1;

void *
palloc(Size size)
{
	return ndf_arena_alloc(size);
}

void *
palloc0(Size size)
{
	void	   *p = ndf_arena_alloc(size);

	memset(p, 0, size);
	return p;
}

void *
palloc_extended(Size size, int flags)
{
	void	   *p = ndf_arena_alloc(size);

	if (flags & MCXT_ALLOC_ZERO)
		memset(p, 0, size);
	return p;
}

void *
repalloc(void *pointer, Size size)
{
	size_t		old = *(size_t *) ((char *) pointer - MAXIMUM_ALIGNOF);
	void	   *p = ndf_arena_alloc(size);

	memcpy(p, pointer, old < size ? old : size);
	return p;
}

void
pfree(void *pointer)
{
	(void) pointer;				/* arena-reset semantics */
}

char *
pstrdup(const char *in)
{
	size_t		len = strlen(in) + 1;
	char	   *p = ndf_arena_alloc(len);

	memcpy(p, in, len);
	return p;
}

void *
MemoryContextAlloc(MemoryContext context, Size size)
{
	(void) context;
	return ndf_arena_alloc(size);
}

MemoryContext
GetMemoryChunkContext(void *pointer)
{
	(void) pointer;
	return CurrentMemoryContext;
}

/* ====================== SECTION B: ereport capture ===================== */

static jmp_buf ndf_jmp;
static int	ndf_jmp_armed;
static int	ndf_errcode_val;		/* packed sqlstate from errcode() */
static int	ndf_cur_elevel;			/* elevel of the report being assembled */
static int	ndf_notice_count;		/* sub-ERROR reports emitted since the
									 * last driver-entry reset. SIDE CHANNEL
									 * ONLY, never a compared plane: real PG
									 * prints these and continues, and the
									 * Rust ports carry no warning surface. */

bool
errstart(int elevel, const char *domain)
{
	(void) domain;
	ndf_cur_elevel = elevel;

	/*
	 * elog.c errstart: default sqlstate unless errcode() runs — XX000
	 * (internal error) for >= ERROR, 01000 for WARNING/WARNING_CLIENT_ONLY,
	 * successful completion below that. (The old `elevel >= 20` cutoff
	 * predated WARNING_CLIENT_ONLY == 20 in this tree; ERROR is 21.)
	 */
	if (elevel >= ERROR)
		ndf_errcode_val = MAKE_SQLSTATE('X', 'X', '0', '0', '0');
	else if (elevel >= WARNING)
		ndf_errcode_val = MAKE_SQLSTATE('0', '1', '0', '0', '0');
	else
		ndf_errcode_val = 0;
	return true;
}

bool
errstart_cold(int elevel, const char *domain)
{
	return errstart(elevel, domain);
}

void
errfinish(const char *filename, int lineno, const char *funcname)
{
	(void) filename;
	(void) lineno;
	(void) funcname;

	/*
	 * PG's errfinish performs the error non-local exit ONLY for elevel >=
	 * ERROR; WARNING and below are emitted to log/client and control
	 * RETURNS so the reporting C code continues (outfuncs.c:766 is this
	 * family's live warn-and-continue site). Task #137: this shim used to
	 * longjmp at ANY elevel, converting sub-ERROR paths into false oracle
	 * errors. Sub-ERROR reports land on the side-channel counter only.
	 */
	if (ndf_cur_elevel < ERROR)
	{
		ndf_notice_count++;
		return;
	}
	if (!ndf_jmp_armed)
		abort();
	longjmp(ndf_jmp, 1);
}

int
errcode(int sqlerrcode)
{
	ndf_errcode_val = sqlerrcode;
	return 0;
}

/*
 * DIAGNOSTIC CHANNEL ONLY (never a compared plane): with
 * PGRUST_NODESFAM_DEBUG=1 the oracle prints the C error text to stderr, so a
 * lane can see WHY C rejected an input. Message text stays out of every
 * comparison (campaign rule: value + verdict + errcode only).
 */
static void
ndf_debug_msg(const char *fmt, va_list ap)
{
	static int	on = -1;

	if (on < 0)
		on = getenv("PGRUST_NODESFAM_DEBUG") != NULL;
	if (on)
	{
		fputs("C-ERROR: ", stderr);
		vfprintf(stderr, fmt, ap);
		fputc('\n', stderr);
	}
}

int
errmsg(const char *fmt,...)
{
	va_list		ap;

	va_start(ap, fmt);
	ndf_debug_msg(fmt, ap);
	va_end(ap);
	return 0;
}

int
errmsg_internal(const char *fmt,...)
{
	va_list		ap;

	va_start(ap, fmt);
	ndf_debug_msg(fmt, ap);
	va_end(ap);
	return 0;
}

int
errdetail(const char *fmt,...)
{
	(void) fmt;
	return 0;
}

int
errhint(const char *fmt,...)
{
	(void) fmt;
	return 0;
}

/* elog.c string plumbing referenced by stack_depth.c's GUC check hook */
char	   *GUC_check_errdetail_string;
char	   *GUC_check_errhint_string;

void
pre_format_elog_string(int errnumber, const char *domain)
{
	(void) errnumber;
	(void) domain;
}

char *
format_elog_string(const char *fmt,...)
{
	(void) fmt;
	return NULL;
}

/* =================== SECTION C: environment stubs ====================== */

/*
 * Extensible-node registry: EMPTY, exactly a backend with no extensions
 * loaded. Message wording matches extensible.c so nothing else differs.
 */
const ExtensibleNodeMethods *
GetExtensibleNodeMethods(const char *extnodename, bool missing_ok)
{
	if (!missing_ok)
		ereport(ERROR,
				(errcode(ERRCODE_UNDEFINED_OBJECT),
				 errmsg("ExtensibleNodeMethods \"%s\" was not registered",
						extnodename)));
	return NULL;
}

const struct CustomScanMethods *
GetCustomScanMethods(const char *CustomName, bool missing_ok)
{
	if (!missing_ok)
		ereport(ERROR,
				(errcode(ERRCODE_UNDEFINED_OBJECT),
				 errmsg("CustomScanMethods \"%s\" was not registered",
						CustomName)));
	return NULL;
}

/* datum.c expanded-object / external-toast arms: unreachable (see header) */
ExpandedObjectHeader *
DatumGetEOHP(Datum d)
{
	(void) d;
	abort();
}

void
EOH_flatten_into(ExpandedObjectHeader *eohptr, void *result, Size allocated_size)
{
	(void) eohptr;
	(void) result;
	(void) allocated_size;
	abort();
}

Size
EOH_get_flat_size(ExpandedObjectHeader *eohptr)
{
	(void) eohptr;
	abort();
}

Datum
TransferExpandedObject(Datum d, MemoryContext new_parent)
{
	(void) d;
	(void) new_parent;
	abort();
}

struct varlena *
pg_detoast_datum_packed(struct varlena *datum)
{
	(void) datum;
	abort();
}

Size
toast_raw_datum_size(Datum value)
{
	(void) value;
	abort();
}

uint32
hash_bytes(const unsigned char *k, int keylen)
{
	(void) k;
	(void) keylen;
	abort();					/* bms_hash_value: link-only */
}

/*
 * pg_qsort for list_sort: VERBATIM port/qsort.c instantiation of
 * lib/sort_template.h (vendored whole under nodesfam/include/lib/).
 *
 * oracle-integrity sweep (task #98): this used to be a libc qsort()
 * trampoline commented "link-only", but unlike the abort() link-only
 * shims above it would SILENTLY sort with libc's tie order if list_sort
 * ever became reachable — the spgkdtree wrong-oracle class. The
 * backend's qsort IS pg_qsort (port.h `#define qsort pg_qsort`), so the
 * oracle's must be too.
 */
#define ST_SORT pg_qsort
#define ST_ELEMENT_TYPE_VOID
#define ST_COMPARE_RUNTIME_POINTER
#define ST_SCOPE
#define ST_DECLARE
#define ST_DEFINE
#include "lib/sort_template.h"

/* ======================= SECTION D: driver entries ===================== */

/*
 * Verdicts. OK = the pipeline stage succeeded; ERROR = ereport(ERROR)
 * captured (nf_errcode holds the packed sqlstate).
 */
#define NDF_OK 0
#define NDF_ERROR 1

typedef struct NdfOut
{
	int			verdict;
	int			errcode;		/* packed sqlstate (MAKE_SQLSTATE encoding) */
	const char *out_text;		/* nodeToString(read(input)) */
	const char *copy_text;		/* nodeToString(copyObject(read(input))) */
	int			equal_ok;		/* equal(node, copy) */
	int			reread_ok;		/* out(read(out_text)) == out_text */
} NdfOut;

static NdfOut ndf_result;

void
pg_ndf_init(void)
{
	PG_ORACLE_GUARD_CHECK(__func__);
	set_stack_base();
	/* server default: postmaster raises 100kB -> 2048kB given >=2.5MB rlimit */
	assign_max_stack_depth(2048, NULL);
}

/*
 * Full oracle pipeline over one node-text input:
 *   read -> out -> copy -> out(copy) -> equal -> re-read(out) -> out.
 * Any ereport(ERROR) longjmps here and reports the stage's verdict.
 * Input must be NUL-terminated; the arena is reset on entry.
 */
const NdfOut *
pg_ndf_exec(const char *input)
{
	PG_ORACLE_GUARD_CHECK(__func__);
	void	   *node;
	void	   *copy;
	char	   *out1;
	char	   *out2;
	char	   *out3;
	void	   *reread;

	ndf_arena_used = 0;
	ndf_notice_count = 0;
	ndf_result.verdict = NDF_ERROR;
	ndf_result.errcode = 0;
	ndf_result.out_text = NULL;
	ndf_result.copy_text = NULL;
	ndf_result.equal_ok = -1;
	ndf_result.reread_ok = -1;

	ndf_jmp_armed = 1;
	if (setjmp(ndf_jmp) != 0)
	{
		ndf_jmp_armed = 0;
		ndf_result.errcode = ndf_errcode_val;
		return &ndf_result;
	}

	node = stringToNode(input);
	/* out even for NULL ("<>" input): C nodeToString(NULL) prints "<>" */
	out1 = nodeToString(node);
	copy = copyObjectImpl(node);
	out2 = nodeToString(copy);
	ndf_result.out_text = out1;
	ndf_result.copy_text = out2;
	ndf_result.equal_ok = (node == NULL && copy == NULL) ||
		(node != NULL && copy != NULL && equal(node, copy));

	reread = stringToNode(out1);
	out3 = nodeToString(reread);
	ndf_result.reread_ok = strcmp(out1, out3) == 0;

	ndf_jmp_armed = 0;
	ndf_result.verdict = NDF_OK;
	return &ndf_result;
}

/* Side channel for the tests: sub-ERROR reports since the last entry. */
int
pg_ndf_notice_count(void)
{
	return ndf_notice_count;
}

/*
 * Shim-contract control (task #137), fuzz plumbing, NOT Postgres code.
 *
 * Drives the ONE sub-ERROR report the vendored family contains —
 * outfuncs.c outNode's default arm, elog(WARNING, "could not dump
 * unrecognized node type: %d") — through the real ereport plumbing, by
 * handing nodeToString a fabricated node whose tag is nodetags.h-valid but
 * has no out function (T_InlineCodeBlock, an executor node). The tag census
 * (nodesfam_diff_tests.rs) proves stringToNode can never build such a node,
 * so the arm is unreachable through pg_ndf_exec and needs this direct entry.
 *
 * The backend emits that WARNING and outNode CONTINUES, producing "{}".
 * Contract under test: errfinish longjmps ONLY for elevel >= ERROR;
 * WARNING/NOTICE record-and-return (real errfinish, elog.c). Reports like
 * pg_ndf_exec: verdict OK + out_text "{}" when the contract holds, verdict
 * ERROR if the WARNING was misreported as an oracle error.
 */
const NdfOut *
pg_ndf_warning_control(void)
{
	PG_ORACLE_GUARD_CHECK(__func__);
	struct
	{
		NodeTag		type;
	}			stub;

	ndf_arena_used = 0;
	ndf_notice_count = 0;
	ndf_result.verdict = NDF_ERROR;
	ndf_result.errcode = 0;
	ndf_result.out_text = NULL;
	ndf_result.copy_text = NULL;
	ndf_result.equal_ok = -1;
	ndf_result.reread_ok = -1;

	ndf_jmp_armed = 1;
	if (setjmp(ndf_jmp) != 0)
	{
		ndf_jmp_armed = 0;
		ndf_result.errcode = ndf_errcode_val;
		return &ndf_result;
	}

	stub.type = T_InlineCodeBlock;
	ndf_result.out_text = nodeToString(&stub);

	ndf_jmp_armed = 0;
	ndf_result.verdict = NDF_OK;
	return &ndf_result;
}
