/*
 * pg_tsm_system_time_io.c: vendored PostgreSQL C oracle for the
 * tsm_system_time_diff differential fuzz target (100%-coverage campaign,
 * lane p1-wavea). Crate under test: crates/contrib/tsm_system_time.
 *
 * GENERATED by csrc/gen/assemble_tsmtime.sh — verbatim sections are
 * sed-extracted, never hand-typed. Do not edit the VERBATIM sections here;
 * edit the script's shim heredocs and re-run.
 *
 * Provenance (all VERBATIM sections byte-for-byte from
 * ~/dev/pgrust-fabled/vendor/postgres-src, Stamp-18.3, upstream sha
 * 62d6c7d3df6287f1bd83199c1a746e50d31571a0):
 *   - contrib/tsm_system_time/tsm_system_time.c lines 44-74 (comment,
 *     SystemTimeSamplerData, static prototypes) and 101-355 (all bodies:
 *     system_time_samplescangetsamplesize, system_time_initsamplescan,
 *     system_time_beginsamplescan, system_time_nextsampleblock,
 *     system_time_nextsampletuple, gcd, random_relative_prime).
 *     NOT vendored: tsm_system_time_handler (lines 77-99) — fmgr/makeNode
 *     TsmRoutine registry plumbing with no computation (the Rust handler is
 *     registry plumbing too and is exercised by the driver's Rust-only
 *     registry arm; tsm_system_rows/contribafam precedent).
 *   - src/include/portability/instr_time.h lines 69-73 (instr_time
 *     typedef), 77-79 (NS_PER_* constants), 125-126
 *     (INSTR_TIME_GET_NANOSEC, POSIX variant), 181-182
 *     (INSTR_TIME_SUBTRACT), 191-192 (INSTR_TIME_GET_MILLISEC) — the
 *     elapsed-time ARITHMETIC is all verbatim. INSTR_TIME_SET_CURRENT
 *     alone is shimmed (see shim list: stub:clock environment read).
 *   - src/include/postgres.h lines 492-513 (DatumGetFloat8 static inline,
 *     USE_FLOAT8_BYVAL arm — the never-fabricate-header-inlines rule).
 *   - src/backend/utils/misc/sampling.c lines 229-251
 *     (sampler_random_init_state, sampler_random_fract), renamed to
 *     pg_tsmtime_* via #define ahead of the paste (family symbol prefix —
 *     the bodies are untouched).
 *   - src/backend/optimizer/path/costsize.c line 128 (MAXIMUM_ROWCOUNT) and
 *     lines 212-230 (clamp_row_est), renamed pg_tsmtime_clamp_row_est via
 *     #define ahead of the paste.
 *   - pg_prng engine NOT duplicated: pg_prng_seed / pg_prng_double /
 *     pg_prng_uint64 are consumed via extern from csrc/pg_pg_prng_io.c,
 *     which vendors src/common/pg_prng.c verbatim (single copy per the
 *     duplicate-export rule). pg_prng_state struct transcribed from
 *     src/include/common/pg_prng.h (two uint64 fields).
 *
 * Shims (PLUMBING ONLY, never logic — census note of record: same
 * file-grain shape as tsm_system_rows; the C callbacks touch only
 * node->tsm_state):
 *   - fixed-width typedefs matching c.h on LP64; BlockNumber/OffsetNumber/
 *     Oid/Datum per block.h/off.h/postgres_ext.h/postgres.h;
 *     InvalidBlockNumber 0xFFFFFFFF; InvalidOffsetNumber 0;
 *     FirstOffsetNumber 1; Min; unlikely; USE_FLOAT8_BYVAL (LP64);
 *     INT64CONST; DatumGetInt64 cast.
 *   - INSTR_TIME_SET_CURRENT -> ticks = (int64) pg_stub_get_mono_ns()
 *     (stub:clock monotonic half, csrc/stubshims/pg_stub_state.c; the
 *     driver pins the SAME fuzz-derived value into pg_clock's
 *     fuzz_mono_pin cell on the Rust side per fuzz/STUBS.md — the OS
 *     clock read is ENVIRONMENT; every derived tick after it is the
 *     verbatim instr_time.h/tsm arithmetic above).
 *   - SampleScanState: FABRICATED minimal shell {tsm_state} (census carve
 *     note; the time callbacks touch no other field).
 *   - system_time_samplescangetsamplesize planner plumbing (census:
 *     compare POST-FOLDING): Node/Const shells with a type tag +
 *     constvalue/constisnull; IsA tag test; linitial(l) == the
 *     driver-passed node (single-element list identity);
 *     estimate_expression_value = identity (the driver pre-folds);
 *     RelOptInfo shell {reltablespace, tuples, pages};
 *     get_tablespace_page_costs -> reports the driver-provided
 *     spc_random_page_cost (spccache.c reads catalogs/GUCs — session
 *     environment; the value is a compared input given identically to the
 *     shipped Rust entry point's spc_random_page_cost argument).
 *     PlannerInfo/List opaque, never dereferenced.
 *   - ereport(ERROR, (errcode(..), errmsg(..))) -> record errcode class in
 *     the shared TLS pg_diff_errcode channel and longjmp to the armed
 *     driver entry; errmsg swallowed (message text out of scope).
 *     Classes: 0 ok; 1 = 2202H ERRCODE_INVALID_TABLESAMPLE_ARGUMENT.
 *   - CHECK_FOR_INTERRUPTS() -> no-op (no signal plane in-process; the
 *     loop is finite for every reachable state, Rust carries the same
 *     documented elision).
 *   - palloc0 -> TLS pointer arena (scaffold pattern; reset per exec).
 */

#include <assert.h>
#include <math.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Shared TLS errcode channel (defined in csrc/pg_float_io.c). */
extern _Thread_local int pg_diff_errcode;

/* stub:clock monotonic half (csrc/stubshims/pg_stub_state.c). */
extern uint64_t pg_stub_get_mono_ns(void);

/* Errcode classes (map on the Rust side to sqlstates). */
#define PG_TSMTIME_ERRCLASS_TABLESAMPLE 1	/* 2202H */

/* ---------- type shims (c.h / block.h / off.h / postgres.h, LP64) ---------- */
typedef uint32_t uint32;
typedef uint64_t uint64;
typedef int64_t int64;
typedef uint16_t uint16;
typedef uint32 BlockNumber;
typedef uint16 OffsetNumber;
typedef uint32 Oid;
typedef uintptr_t Datum;
typedef double float8;

#define InvalidBlockNumber ((BlockNumber) 0xFFFFFFFF)
#define InvalidOffsetNumber ((OffsetNumber) 0)
#define FirstOffsetNumber ((OffsetNumber) 1)
#define Min(x, y) ((x) < (y) ? (x) : (y))
#define unlikely(x) __builtin_expect((x) != 0, 0)
#define USE_FLOAT8_BYVAL 1
#define INT64CONST(x) INT64_C(x)
#define DatumGetInt64(X) ((int64) (X))
#define CHECK_FOR_INTERRUPTS() ((void) 0)

/* pg_prng_state (src/include/common/pg_prng.h, VERBATIM struct); engine
 * consumed from csrc/pg_pg_prng_io.c (verbatim src/common/pg_prng.c). */
typedef struct pg_prng_state
{
	uint64		s0,
				s1;
} pg_prng_state;

extern void pg_prng_seed(pg_prng_state *state, uint64 seed);
extern double pg_prng_double(pg_prng_state *state);
extern uint64 pg_prng_uint64(pg_prng_state *state);

/* ---------- ereport shim ---------- */
static _Thread_local jmp_buf pg_tsmtime_jmp;

#define ERROR 21
#define ereport(elevel, rest) \
	do { (void) (rest); longjmp(pg_tsmtime_jmp, 1); } while (0)
#define errcode(c) (pg_diff_errcode = (c))
#define errmsg(...) 0
#define ERRCODE_INVALID_TABLESAMPLE_ARGUMENT PG_TSMTIME_ERRCLASS_TABLESAMPLE

/* ---------- INSTR_TIME_SET_CURRENT shim (stub:clock; arithmetic below is
 * verbatim instr_time.h) ---------- */
#define INSTR_TIME_SET_CURRENT(t) \
	((t).ticks = (int64) pg_stub_get_mono_ns())

/* ---------- planner shims for samplescangetsamplesize (post-folding) ------ */
typedef struct PlannerInfo PlannerInfo;	/* opaque, never dereferenced */
typedef struct List List;				/* opaque; the "list" IS the node */

enum pg_tsmtime_nodetag
{
	PG_TSMTIME_T_Invalid = 0,
	PG_TSMTIME_T_Const = 1
};

typedef struct Node
{
	int			type;
} Node;

typedef struct Const
{
	int			type;
	Datum		constvalue;
	bool		constisnull;
} Const;

typedef struct RelOptInfo
{
	Oid			reltablespace;
	double		tuples;
	BlockNumber pages;
} RelOptInfo;

#define IsA(nodeptr, _type_) (((const Node *) (nodeptr))->type == PG_TSMTIME_T_##_type_)
#define linitial(l) ((void *) (l))

/* identity fold: the driver pre-folds (census carve — compared post-folding) */
static Node *
estimate_expression_value(PlannerInfo *root, Node *node)
{
	(void) root;
	return node;
}

/* get_tablespace_page_costs (utils/cache/spccache.c) reads catalogs + GUC
 * session state — environment; the driver provides the cost, which is the
 * SAME compared input the shipped Rust entry point takes as an argument. */
static _Thread_local double pg_tsmtime_spc_random_page_cost;

static void
get_tablespace_page_costs(Oid spcid, double *spc_random_page_cost,
						  double *spc_seq_page_cost)
{
	(void) spcid;
	if (spc_random_page_cost)
		*spc_random_page_cost = pg_tsmtime_spc_random_page_cost;
	if (spc_seq_page_cost)
		assert(!"tsm_system_time never asks for seq_page_cost");
}

/* ---------- SampleScanState fabricated shell (census carve note) ---------- */
typedef struct SampleScanState
{
	void	   *tsm_state;
} SampleScanState;

/* ---------- palloc arena shim (scaffold pattern) ---------- */
#define PG_DIFF_ARENA_MAX 64
static _Thread_local void *pg_tsmtime_arena[PG_DIFF_ARENA_MAX];
static _Thread_local int pg_tsmtime_arena_n;

static void
pg_tsmtime_arena_reset(void)
{
	int			i;

	for (i = 0; i < pg_tsmtime_arena_n; i++)
		free(pg_tsmtime_arena[i]);
	pg_tsmtime_arena_n = 0;
}

static void *
pg_tsmtime_palloc0_impl(size_t n)
{
	void	   *p = calloc(1, n);

	assert(pg_tsmtime_arena_n < PG_DIFF_ARENA_MAX);
	pg_tsmtime_arena[pg_tsmtime_arena_n++] = p;
	return p;
}

#define palloc0(n) pg_tsmtime_palloc0_impl(n)

/* ---------- family-prefix renames for the non-static vendored pastes ------ */
#define sampler_random_init_state pg_tsmtime_sampler_random_init_state
#define sampler_random_fract pg_tsmtime_sampler_random_fract
#define clamp_row_est pg_tsmtime_clamp_row_est

/* == SECTION 1: src/include/portability/instr_time.h lines 69-73 (VERBATIM) == */
typedef struct instr_time
{
	int64		ticks;			/* in platforms specific unit */
} instr_time;


/* == SECTION 2: src/include/portability/instr_time.h lines 77-79 (VERBATIM) == */
#define NS_PER_S	INT64CONST(1000000000)
#define NS_PER_MS	INT64CONST(1000000)
#define NS_PER_US	INT64CONST(1000)

/* == SECTION 3: src/include/portability/instr_time.h lines 125-126 (VERBATIM) == */
#define INSTR_TIME_GET_NANOSEC(t) \
	((int64) (t).ticks)

/* == SECTION 4: src/include/portability/instr_time.h lines 181-182 (VERBATIM) == */
#define INSTR_TIME_SUBTRACT(x,y) \
	((x).ticks -= (y).ticks)

/* == SECTION 5: src/include/portability/instr_time.h lines 191-192 (VERBATIM) == */
#define INSTR_TIME_GET_MILLISEC(t) \
	((double) INSTR_TIME_GET_NANOSEC(t) / NS_PER_MS)

/* == SECTION 6: src/include/postgres.h lines 492-513 (VERBATIM) == */
/*
 * DatumGetFloat8
 *		Returns 8-byte floating point value of a datum.
 *
 * Note: this function hides whether float8 is pass by value or by reference.
 */
static inline float8
DatumGetFloat8(Datum X)
{
#ifdef USE_FLOAT8_BYVAL
	union
	{
		int64		value;
		float8		retval;
	}			myunion;

	myunion.value = DatumGetInt64(X);
	return myunion.retval;
#else
	return *((float8 *) DatumGetPointer(X));
#endif
}

/* == SECTION 7: src/backend/optimizer/path/costsize.c line 128 (VERBATIM) == */
#define MAXIMUM_ROWCOUNT 1e100

/* == SECTION 8: src/backend/optimizer/path/costsize.c lines 212-230 (VERBATIM) == */
double
clamp_row_est(double nrows)
{
	/*
	 * Avoid infinite and NaN row estimates.  Costs derived from such values
	 * are going to be useless.  Also force the estimate to be at least one
	 * row, to make explain output look better and to avoid possible
	 * divide-by-zero when interpolating costs.  Make it an integer, too.
	 */
	if (nrows > MAXIMUM_ROWCOUNT || isnan(nrows))
		nrows = MAXIMUM_ROWCOUNT;
	else if (nrows <= 1.0)
		nrows = 1.0;
	else
		nrows = rint(nrows);

	return nrows;
}


/* == SECTION 9: src/backend/utils/misc/sampling.c lines 229-251 (VERBATIM) == */
/*----------
 * Random number generator used by sampling
 *----------
 */
void
sampler_random_init_state(uint32 seed, pg_prng_state *randstate)
{
	pg_prng_seed(randstate, (uint64) seed);
}

/* Select a random value R uniformly distributed in (0 - 1) */
double
sampler_random_fract(pg_prng_state *randstate)
{
	double		res;

	/* pg_prng_double returns a value in [0.0 - 1.0), so we must reject 0.0 */
	do
	{
		res = pg_prng_double(randstate);
	} while (unlikely(res == 0.0));
	return res;
}

/* == SECTION 10: contrib/tsm_system_time/tsm_system_time.c lines 44-74 (VERBATIM) == */
/* Private state */
typedef struct
{
	uint32		seed;			/* random seed */
	double		millis;			/* time limit for sampling */
	instr_time	start_time;		/* scan start time */
	OffsetNumber lt;			/* last tuple returned from current block */
	BlockNumber doneblocks;		/* number of already-scanned blocks */
	BlockNumber lb;				/* last block visited */
	/* these three values are not changed during a rescan: */
	BlockNumber nblocks;		/* number of blocks in relation */
	BlockNumber firstblock;		/* first block to sample from */
	BlockNumber step;			/* step size, or 0 if not set yet */
} SystemTimeSamplerData;

static void system_time_samplescangetsamplesize(PlannerInfo *root,
												RelOptInfo *baserel,
												List *paramexprs,
												BlockNumber *pages,
												double *tuples);
static void system_time_initsamplescan(SampleScanState *node,
									   int eflags);
static void system_time_beginsamplescan(SampleScanState *node,
										Datum *params,
										int nparams,
										uint32 seed);
static BlockNumber system_time_nextsampleblock(SampleScanState *node, BlockNumber nblocks);
static OffsetNumber system_time_nextsampletuple(SampleScanState *node,
												BlockNumber blockno,
												OffsetNumber maxoffset);
static uint32 random_relative_prime(uint32 n, pg_prng_state *randstate);

/* == SECTION 11: contrib/tsm_system_time/tsm_system_time.c lines 101-355 (VERBATIM) == */
/*
 * Sample size estimation.
 */
static void
system_time_samplescangetsamplesize(PlannerInfo *root,
									RelOptInfo *baserel,
									List *paramexprs,
									BlockNumber *pages,
									double *tuples)
{
	Node	   *limitnode;
	double		millis;
	double		spc_random_page_cost;
	double		npages;
	double		ntuples;

	/* Try to extract an estimate for the limit time spec */
	limitnode = (Node *) linitial(paramexprs);
	limitnode = estimate_expression_value(root, limitnode);

	if (IsA(limitnode, Const) &&
		!((Const *) limitnode)->constisnull)
	{
		millis = DatumGetFloat8(((Const *) limitnode)->constvalue);
		if (millis < 0 || isnan(millis))
		{
			/* Default millis if the value is bogus */
			millis = 1000;
		}
	}
	else
	{
		/* Default millis if we didn't obtain a non-null Const */
		millis = 1000;
	}

	/* Get the planner's idea of cost per page read */
	get_tablespace_page_costs(baserel->reltablespace,
							  &spc_random_page_cost,
							  NULL);

	/*
	 * Estimate the number of pages we can read by assuming that the cost
	 * figure is expressed in milliseconds.  This is completely, unmistakably
	 * bogus, but we have to do something to produce an estimate and there's
	 * no better answer.
	 */
	if (spc_random_page_cost > 0)
		npages = millis / spc_random_page_cost;
	else
		npages = millis;		/* even more bogus, but whatcha gonna do? */

	/* Clamp to sane value */
	npages = clamp_row_est(Min((double) baserel->pages, npages));

	if (baserel->tuples > 0 && baserel->pages > 0)
	{
		/* Estimate number of tuples returned based on tuple density */
		double		density = baserel->tuples / (double) baserel->pages;

		ntuples = npages * density;
	}
	else
	{
		/* For lack of data, assume one tuple per page */
		ntuples = npages;
	}

	/* Clamp to the estimated relation size */
	ntuples = clamp_row_est(Min(baserel->tuples, ntuples));

	*pages = npages;
	*tuples = ntuples;
}

/*
 * Initialize during executor setup.
 */
static void
system_time_initsamplescan(SampleScanState *node, int eflags)
{
	node->tsm_state = palloc0(sizeof(SystemTimeSamplerData));
	/* Note the above leaves tsm_state->step equal to zero */
}

/*
 * Examine parameters and prepare for a sample scan.
 */
static void
system_time_beginsamplescan(SampleScanState *node,
							Datum *params,
							int nparams,
							uint32 seed)
{
	SystemTimeSamplerData *sampler = (SystemTimeSamplerData *) node->tsm_state;
	double		millis = DatumGetFloat8(params[0]);

	if (millis < 0 || isnan(millis))
		ereport(ERROR,
				(errcode(ERRCODE_INVALID_TABLESAMPLE_ARGUMENT),
				 errmsg("sample collection time must not be negative")));

	sampler->seed = seed;
	sampler->millis = millis;
	sampler->lt = InvalidOffsetNumber;
	sampler->doneblocks = 0;
	/* start_time, lb will be initialized during first NextSampleBlock call */
	/* we intentionally do not change nblocks/firstblock/step here */
}

/*
 * Select next block to sample.
 *
 * Uses linear probing algorithm for picking next block.
 */
static BlockNumber
system_time_nextsampleblock(SampleScanState *node, BlockNumber nblocks)
{
	SystemTimeSamplerData *sampler = (SystemTimeSamplerData *) node->tsm_state;
	instr_time	cur_time;

	/* First call within scan? */
	if (sampler->doneblocks == 0)
	{
		/* First scan within query? */
		if (sampler->step == 0)
		{
			/* Initialize now that we have scan descriptor */
			pg_prng_state randstate;

			/* If relation is empty, there's nothing to scan */
			if (nblocks == 0)
				return InvalidBlockNumber;

			/* We only need an RNG during this setup step */
			sampler_random_init_state(sampler->seed, &randstate);

			/* Compute nblocks/firstblock/step only once per query */
			sampler->nblocks = nblocks;

			/* Choose random starting block within the relation */
			/* (Actually this is the predecessor of the first block visited) */
			sampler->firstblock = sampler_random_fract(&randstate) *
				sampler->nblocks;

			/* Find relative prime as step size for linear probing */
			sampler->step = random_relative_prime(sampler->nblocks, &randstate);
		}

		/* Reinitialize lb and start_time */
		sampler->lb = sampler->firstblock;
		INSTR_TIME_SET_CURRENT(sampler->start_time);
	}

	/* If we've read all blocks in relation, we're done */
	if (++sampler->doneblocks > sampler->nblocks)
		return InvalidBlockNumber;

	/* If we've used up all the allotted time, we're done */
	INSTR_TIME_SET_CURRENT(cur_time);
	INSTR_TIME_SUBTRACT(cur_time, sampler->start_time);
	if (INSTR_TIME_GET_MILLISEC(cur_time) >= sampler->millis)
		return InvalidBlockNumber;

	/*
	 * It's probably impossible for scan->rs_nblocks to decrease between scans
	 * within a query; but just in case, loop until we select a block number
	 * less than scan->rs_nblocks.  We don't care if scan->rs_nblocks has
	 * increased since the first scan.
	 */
	do
	{
		/* Advance lb, using uint64 arithmetic to forestall overflow */
		sampler->lb = ((uint64) sampler->lb + sampler->step) % sampler->nblocks;
	} while (sampler->lb >= nblocks);

	return sampler->lb;
}

/*
 * Select next sampled tuple in current block.
 *
 * In block sampling, we just want to sample all the tuples in each selected
 * block.
 *
 * When we reach end of the block, return InvalidOffsetNumber which tells
 * SampleScan to go to next block.
 */
static OffsetNumber
system_time_nextsampletuple(SampleScanState *node,
							BlockNumber blockno,
							OffsetNumber maxoffset)
{
	SystemTimeSamplerData *sampler = (SystemTimeSamplerData *) node->tsm_state;
	OffsetNumber tupoffset = sampler->lt;

	/* Advance to next possible offset on page */
	if (tupoffset == InvalidOffsetNumber)
		tupoffset = FirstOffsetNumber;
	else
		tupoffset++;

	/* Done? */
	if (tupoffset > maxoffset)
		tupoffset = InvalidOffsetNumber;

	sampler->lt = tupoffset;

	return tupoffset;
}

/*
 * Compute greatest common divisor of two uint32's.
 */
static uint32
gcd(uint32 a, uint32 b)
{
	uint32		c;

	while (a != 0)
	{
		c = a;
		a = b % a;
		b = c;
	}

	return b;
}

/*
 * Pick a random value less than and relatively prime to n, if possible
 * (else return 1).
 */
static uint32
random_relative_prime(uint32 n, pg_prng_state *randstate)
{
	uint32		r;

	/* Safety check to avoid infinite loop or zero result for small n. */
	if (n <= 1)
		return 1;

	/*
	 * This should only take 2 or 3 iterations as the probability of 2 numbers
	 * being relatively prime is ~61%; but just in case, we'll include a
	 * CHECK_FOR_INTERRUPTS in the loop.
	 */
	do
	{
		CHECK_FOR_INTERRUPTS();
		r = (uint32) (sampler_random_fract(randstate) * n);
	} while (r == 0 || gcd(r, n) > 1);

	return r;
}

/* ========== SECTION 12: fuzz-facing driver entries (NOT Postgres code) ===== */

static _Thread_local SampleScanState pg_tsmtime_node;

/* Fresh scan state: arena reset + verbatim initsamplescan (palloc0 zeroes
 * the sampler exactly as PG's executor path does — step == 0 sentinel). */
void
pg_tsmtime_scan_reset(void)
{
	pg_tsmtime_arena_reset();
	pg_diff_errcode = 0;
	system_time_initsamplescan(&pg_tsmtime_node, 0);
}

/* 0 = ok, 1 = ereport'ed (class in pg_diff_errcode). millis passed as raw
 * f64 BITS: Float8GetDatum on USE_FLOAT8_BYVAL is the bit image in the
 * Datum word; the verbatim body unwraps it with vendored DatumGetFloat8. */
int
pg_tsmtime_beginsamplescan(uint64 millis_bits, uint32 seed)
{
	Datum		params[1];

	pg_diff_errcode = 0;
	params[0] = (Datum) millis_bits;	/* Float8GetDatum, LP64 by-value */
	if (setjmp(pg_tsmtime_jmp))
		return 1;
	system_time_beginsamplescan(&pg_tsmtime_node, params, 1, seed);
	return 0;
}

uint32
pg_tsmtime_nextsampleblock(uint32 nblocks)
{
	return system_time_nextsampleblock(&pg_tsmtime_node, nblocks);
}

uint16
pg_tsmtime_nextsampletuple(uint32 blockno, uint16 maxoffset)
{
	return system_time_nextsampletuple(&pg_tsmtime_node, blockno, maxoffset);
}

/* has_const: 0 = non-Const node (the "didn't obtain a Const" arm);
 * 1 = Const with constisnull/constvalue (raw f64 bits) as given. */
void
pg_tsmtime_getsamplesize(int has_const, int isnull, uint64 limit_bits,
						 double spc_random_page_cost,
						 uint32 pages, double tuples,
						 uint32 *out_pages, double *out_tuples)
{
	Const		c;
	Node		notconst;
	void	   *limitnode;
	RelOptInfo	baserel;
	BlockNumber pages_out = 0;
	double		tuples_out = 0;

	pg_diff_errcode = 0;
	pg_tsmtime_spc_random_page_cost = spc_random_page_cost;
	if (has_const)
	{
		c.type = PG_TSMTIME_T_Const;
		c.constisnull = (isnull != 0);
		c.constvalue = (Datum) limit_bits;
		limitnode = &c;
	}
	else
	{
		notconst.type = PG_TSMTIME_T_Invalid;
		limitnode = &notconst;
	}
	baserel.reltablespace = 0;
	baserel.tuples = tuples;
	baserel.pages = pages;
	system_time_samplescangetsamplesize(NULL, &baserel, (List *) limitnode,
										&pages_out, &tuples_out);
	*out_pages = pages_out;
	*out_tuples = tuples_out;
}

/* random_relative_prime over a locally seeded sampler state; *post_draw =
 * one raw engine draw after, witnessing the number of consumed draws. */
uint32
pg_tsmtime_random_relative_prime(uint32 n, uint64 seed, uint64 *post_draw)
{
	pg_prng_state st;
	uint32		r;

	pg_diff_errcode = 0;
	pg_prng_seed(&st, seed);
	r = random_relative_prime(n, &st);
	*post_draw = pg_prng_uint64(&st);
	return r;
}
