/*
 * pg_tsm_system_rows_io.c: vendored PostgreSQL C oracle for the
 * tsm_system_rows_diff differential fuzz target (100%-coverage campaign,
 * lane p1-wavea). Crate under test: crates/contrib/tsm_system_rows.
 *
 * GENERATED by csrc/gen/assemble_tsmrows.sh — verbatim sections are
 * sed-extracted, never hand-typed. Do not edit the VERBATIM sections here;
 * edit the script's shim heredocs and re-run.
 *
 * Provenance (all VERBATIM sections byte-for-byte from
 * ~/dev/pgrust-fabled/vendor/postgres-src, Stamp-18.3, upstream sha
 * 62d6c7d3df6287f1bd83199c1a746e50d31571a0):
 *   - contrib/tsm_system_rows/tsm_system_rows.c lines 45-74 (comment,
 *     SystemRowsSamplerData, static prototypes) and 101-342 (all bodies:
 *     system_rows_samplescangetsamplesize, system_rows_initsamplescan,
 *     system_rows_beginsamplescan, system_rows_nextsampleblock,
 *     system_rows_nextsampletuple, gcd, random_relative_prime).
 *     NOT vendored: tsm_system_rows_handler (lines 77-99) — fmgr/makeNode
 *     TsmRoutine registry plumbing with no computation (the Rust handler is
 *     registry plumbing too and is exercised by the driver's Rust-only
 *     registry arm; contribafam precedent for unvendored PG_FUNCTION_INFO_V1
 *     plumbing).
 *   - src/backend/utils/misc/sampling.c lines 229-251
 *     (sampler_random_init_state, sampler_random_fract), renamed to
 *     pg_tsmrows_* via #define ahead of the paste (family symbol prefix —
 *     the bodies are untouched).
 *   - src/backend/optimizer/path/costsize.c line 128 (MAXIMUM_ROWCOUNT) and
 *     lines 212-230 (clamp_row_est), renamed pg_tsmrows_clamp_row_est via
 *     #define ahead of the paste.
 *   - pg_prng engine NOT duplicated: pg_prng_seed / pg_prng_double /
 *     pg_prng_uint64 are consumed via extern from csrc/pg_pg_prng_io.c,
 *     which vendors src/common/pg_prng.c verbatim (single copy per the
 *     duplicate-export rule). pg_prng_state struct transcribed from
 *     src/include/common/pg_prng.h (two uint64 fields).
 *
 * Shims (PLUMBING ONLY, never logic — census note of record: the C
 * callbacks touch only node->tsm_state / donetuples / use_pagemode,
 * verified against C lines 179-281):
 *   - fixed-width typedefs matching c.h on LP64; BlockNumber/OffsetNumber/
 *     Datum per block.h/off.h/postgres.h; InvalidBlockNumber 0xFFFFFFFF;
 *     InvalidOffsetNumber 0; FirstOffsetNumber 1; Min; unlikely; NULL node
 *     tags.
 *   - SampleScanState: FABRICATED minimal shell {tsm_state, donetuples,
 *     use_pagemode} (census carve note; execnodes.h's real struct is
 *     executor state the callbacks never touch beyond these three fields).
 *   - system_rows_samplescangetsamplesize planner plumbing (census: compare
 *     POST-FOLDING): Node/Const shells with a type tag + constvalue/
 *     constisnull; IsA tag test; linitial(l) == the driver-passed node
 *     (single-element list identity); estimate_expression_value = identity
 *     (the driver pre-folds: it passes either a Const or a non-Const tag,
 *     exactly the post-estimate_expression_value cases the verbatim body
 *     dispatches on); RelOptInfo shell {tuples, pages}; DatumGetInt64 LP64
 *     cast. PlannerInfo/List opaque, never dereferenced.
 *   - ereport(ERROR, (errcode(..), errmsg(..))) -> record errcode class in
 *     the shared TLS pg_diff_errcode channel and longjmp to the armed
 *     driver entry; errmsg swallowed (message text out of scope).
 *     Classes: 0 ok; 1 = 2202H ERRCODE_INVALID_TABLESAMPLE_ARGUMENT.
 *   - CHECK_FOR_INTERRUPTS() -> no-op (no signal plane in-process; the
 *     loop is finite for every reachable state, Rust carries the same
 *     documented elision).
 *   - palloc0 -> TLS pointer arena (scaffold pattern; reset per exec).
 *   - use_pagemode: C line 198 sets node->use_pagemode = true inside the
 *     verbatim callback; the shipped Rust API documents that the CALLER
 *     forces pagemode. The driver asserts the C side set it (branch
 *     witness); there is no Rust-side field to compare (census-noted).
 */

#include <assert.h>
#include <math.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Shared TLS errcode channel (defined in csrc/pg_float_io.c). */
extern _Thread_local int pg_diff_errcode;

/* Errcode classes (map on the Rust side to sqlstates). */
#define PG_TSMROWS_ERRCLASS_TABLESAMPLE 1	/* 2202H */

/* ---------- type shims (c.h / block.h / off.h / postgres.h, LP64) ---------- */
typedef uint32_t uint32;
typedef uint64_t uint64;
typedef int64_t int64;
typedef uint16_t uint16;
typedef uint32 BlockNumber;
typedef uint16 OffsetNumber;
typedef uintptr_t Datum;

#define InvalidBlockNumber ((BlockNumber) 0xFFFFFFFF)
#define InvalidOffsetNumber ((OffsetNumber) 0)
#define FirstOffsetNumber ((OffsetNumber) 1)
#define Min(x, y) ((x) < (y) ? (x) : (y))
#define unlikely(x) __builtin_expect((x) != 0, 0)
#define DatumGetInt64(X) ((int64) (X))
#define CHECK_FOR_INTERRUPTS() ((void) 0)

/* pg_prng_state (src/include/common/pg_prng.h, VERBATIM struct); engine
 * consumed from csrc/pg_pg_prng_io.c (verbatim src/common/pg_prng.c). */
typedef struct pg_prng_state
{
	uint64		s0,
				s1;
} pg_prng_state;

extern void pg_prng_seed(pg_prng_state *state, uint64 seed);
extern double pg_prng_double(pg_prng_state *state);
extern uint64 pg_prng_uint64(pg_prng_state *state);

/* ---------- ereport shim ---------- */
static _Thread_local jmp_buf pg_tsmrows_jmp;

#define ERROR 21
#define ereport(elevel, rest) \
	do { (void) (rest); longjmp(pg_tsmrows_jmp, 1); } while (0)
#define errcode(c) (pg_diff_errcode = (c))
#define errmsg(...) 0
#define ERRCODE_INVALID_TABLESAMPLE_ARGUMENT PG_TSMROWS_ERRCLASS_TABLESAMPLE

/* ---------- planner shims for samplescangetsamplesize (post-folding) ------ */
typedef struct PlannerInfo PlannerInfo;	/* opaque, never dereferenced */
typedef struct List List;				/* opaque; the "list" IS the node */

enum pg_tsmrows_nodetag
{
	PG_TSMROWS_T_Invalid = 0,
	PG_TSMROWS_T_Const = 1
};

typedef struct Node
{
	int			type;
} Node;

typedef struct Const
{
	int			type;
	Datum		constvalue;
	bool		constisnull;
} Const;

typedef struct RelOptInfo
{
	double		tuples;
	BlockNumber pages;
} RelOptInfo;

#define IsA(nodeptr, _type_) (((const Node *) (nodeptr))->type == PG_TSMROWS_T_##_type_)
#define linitial(l) ((void *) (l))

/* identity fold: the driver pre-folds (census carve — compared post-folding) */
static Node *
estimate_expression_value(PlannerInfo *root, Node *node)
{
	(void) root;
	return node;
}

/* ---------- SampleScanState fabricated shell (census carve note) ---------- */
typedef struct SampleScanState
{
	void	   *tsm_state;
	int64		donetuples;
	bool		use_pagemode;
} SampleScanState;

/* ---------- palloc arena shim (scaffold pattern) ---------- */
#define PG_DIFF_ARENA_MAX 64
static _Thread_local void *pg_tsmrows_arena[PG_DIFF_ARENA_MAX];
static _Thread_local int pg_tsmrows_arena_n;

static void
pg_tsmrows_arena_reset(void)
{
	int			i;

	for (i = 0; i < pg_tsmrows_arena_n; i++)
		free(pg_tsmrows_arena[i]);
	pg_tsmrows_arena_n = 0;
}

static void *
pg_tsmrows_palloc0_impl(size_t n)
{
	void	   *p = calloc(1, n);

	assert(pg_tsmrows_arena_n < PG_DIFF_ARENA_MAX);
	pg_tsmrows_arena[pg_tsmrows_arena_n++] = p;
	return p;
}

#define palloc0(n) pg_tsmrows_palloc0_impl(n)

/* ---------- family-prefix renames for the non-static vendored pastes ------ */
#define sampler_random_init_state pg_tsmrows_sampler_random_init_state
#define sampler_random_fract pg_tsmrows_sampler_random_fract
#define clamp_row_est pg_tsmrows_clamp_row_est

/* == SECTION 1: src/backend/optimizer/path/costsize.c line 128 (VERBATIM) == */
#define MAXIMUM_ROWCOUNT 1e100

/* == SECTION 2: src/backend/optimizer/path/costsize.c lines 212-230 (VERBATIM) == */
double
clamp_row_est(double nrows)
{
	/*
	 * Avoid infinite and NaN row estimates.  Costs derived from such values
	 * are going to be useless.  Also force the estimate to be at least one
	 * row, to make explain output look better and to avoid possible
	 * divide-by-zero when interpolating costs.  Make it an integer, too.
	 */
	if (nrows > MAXIMUM_ROWCOUNT || isnan(nrows))
		nrows = MAXIMUM_ROWCOUNT;
	else if (nrows <= 1.0)
		nrows = 1.0;
	else
		nrows = rint(nrows);

	return nrows;
}


/* == SECTION 3: src/backend/utils/misc/sampling.c lines 229-251 (VERBATIM) == */
/*----------
 * Random number generator used by sampling
 *----------
 */
void
sampler_random_init_state(uint32 seed, pg_prng_state *randstate)
{
	pg_prng_seed(randstate, (uint64) seed);
}

/* Select a random value R uniformly distributed in (0 - 1) */
double
sampler_random_fract(pg_prng_state *randstate)
{
	double		res;

	/* pg_prng_double returns a value in [0.0 - 1.0), so we must reject 0.0 */
	do
	{
		res = pg_prng_double(randstate);
	} while (unlikely(res == 0.0));
	return res;
}

/* == SECTION 4: contrib/tsm_system_rows/tsm_system_rows.c lines 45-74 (VERBATIM) == */
/* Private state */
typedef struct
{
	uint32		seed;			/* random seed */
	int64		ntuples;		/* number of tuples to return */
	OffsetNumber lt;			/* last tuple returned from current block */
	BlockNumber doneblocks;		/* number of already-scanned blocks */
	BlockNumber lb;				/* last block visited */
	/* these three values are not changed during a rescan: */
	BlockNumber nblocks;		/* number of blocks in relation */
	BlockNumber firstblock;		/* first block to sample from */
	BlockNumber step;			/* step size, or 0 if not set yet */
} SystemRowsSamplerData;

static void system_rows_samplescangetsamplesize(PlannerInfo *root,
												RelOptInfo *baserel,
												List *paramexprs,
												BlockNumber *pages,
												double *tuples);
static void system_rows_initsamplescan(SampleScanState *node,
									   int eflags);
static void system_rows_beginsamplescan(SampleScanState *node,
										Datum *params,
										int nparams,
										uint32 seed);
static BlockNumber system_rows_nextsampleblock(SampleScanState *node, BlockNumber nblocks);
static OffsetNumber system_rows_nextsampletuple(SampleScanState *node,
												BlockNumber blockno,
												OffsetNumber maxoffset);
static uint32 random_relative_prime(uint32 n, pg_prng_state *randstate);

/* == SECTION 5: contrib/tsm_system_rows/tsm_system_rows.c lines 101-342 (VERBATIM) == */
/*
 * Sample size estimation.
 */
static void
system_rows_samplescangetsamplesize(PlannerInfo *root,
									RelOptInfo *baserel,
									List *paramexprs,
									BlockNumber *pages,
									double *tuples)
{
	Node	   *limitnode;
	int64		ntuples;
	double		npages;

	/* Try to extract an estimate for the limit rowcount */
	limitnode = (Node *) linitial(paramexprs);
	limitnode = estimate_expression_value(root, limitnode);

	if (IsA(limitnode, Const) &&
		!((Const *) limitnode)->constisnull)
	{
		ntuples = DatumGetInt64(((Const *) limitnode)->constvalue);
		if (ntuples < 0)
		{
			/* Default ntuples if the value is bogus */
			ntuples = 1000;
		}
	}
	else
	{
		/* Default ntuples if we didn't obtain a non-null Const */
		ntuples = 1000;
	}

	/* Clamp to the estimated relation size */
	if (ntuples > baserel->tuples)
		ntuples = (int64) baserel->tuples;
	ntuples = clamp_row_est(ntuples);

	if (baserel->tuples > 0 && baserel->pages > 0)
	{
		/* Estimate number of pages visited based on tuple density */
		double		density = baserel->tuples / (double) baserel->pages;

		npages = ntuples / density;
	}
	else
	{
		/* For lack of data, assume one tuple per page */
		npages = ntuples;
	}

	/* Clamp to sane value */
	npages = clamp_row_est(Min((double) baserel->pages, npages));

	*pages = npages;
	*tuples = ntuples;
}

/*
 * Initialize during executor setup.
 */
static void
system_rows_initsamplescan(SampleScanState *node, int eflags)
{
	node->tsm_state = palloc0(sizeof(SystemRowsSamplerData));
	/* Note the above leaves tsm_state->step equal to zero */
}

/*
 * Examine parameters and prepare for a sample scan.
 */
static void
system_rows_beginsamplescan(SampleScanState *node,
							Datum *params,
							int nparams,
							uint32 seed)
{
	SystemRowsSamplerData *sampler = (SystemRowsSamplerData *) node->tsm_state;
	int64		ntuples = DatumGetInt64(params[0]);

	if (ntuples < 0)
		ereport(ERROR,
				(errcode(ERRCODE_INVALID_TABLESAMPLE_ARGUMENT),
				 errmsg("sample size must not be negative")));

	sampler->seed = seed;
	sampler->ntuples = ntuples;
	sampler->lt = InvalidOffsetNumber;
	sampler->doneblocks = 0;
	/* lb will be initialized during first NextSampleBlock call */
	/* we intentionally do not change nblocks/firstblock/step here */

	/*
	 * We *must* use pagemode visibility checking in this module, so force
	 * that even though it's currently default.
	 */
	node->use_pagemode = true;
}

/*
 * Select next block to sample.
 *
 * Uses linear probing algorithm for picking next block.
 */
static BlockNumber
system_rows_nextsampleblock(SampleScanState *node, BlockNumber nblocks)
{
	SystemRowsSamplerData *sampler = (SystemRowsSamplerData *) node->tsm_state;

	/* First call within scan? */
	if (sampler->doneblocks == 0)
	{
		/* First scan within query? */
		if (sampler->step == 0)
		{
			/* Initialize now that we have scan descriptor */
			pg_prng_state randstate;

			/* If relation is empty, there's nothing to scan */
			if (nblocks == 0)
				return InvalidBlockNumber;

			/* We only need an RNG during this setup step */
			sampler_random_init_state(sampler->seed, &randstate);

			/* Compute nblocks/firstblock/step only once per query */
			sampler->nblocks = nblocks;

			/* Choose random starting block within the relation */
			/* (Actually this is the predecessor of the first block visited) */
			sampler->firstblock = sampler_random_fract(&randstate) *
				sampler->nblocks;

			/* Find relative prime as step size for linear probing */
			sampler->step = random_relative_prime(sampler->nblocks, &randstate);
		}

		/* Reinitialize lb */
		sampler->lb = sampler->firstblock;
	}

	/* If we've read all blocks or returned all needed tuples, we're done */
	if (++sampler->doneblocks > sampler->nblocks ||
		node->donetuples >= sampler->ntuples)
		return InvalidBlockNumber;

	/*
	 * It's probably impossible for scan->rs_nblocks to decrease between scans
	 * within a query; but just in case, loop until we select a block number
	 * less than scan->rs_nblocks.  We don't care if scan->rs_nblocks has
	 * increased since the first scan.
	 */
	do
	{
		/* Advance lb, using uint64 arithmetic to forestall overflow */
		sampler->lb = ((uint64) sampler->lb + sampler->step) % sampler->nblocks;
	} while (sampler->lb >= nblocks);

	return sampler->lb;
}

/*
 * Select next sampled tuple in current block.
 *
 * In block sampling, we just want to sample all the tuples in each selected
 * block.
 *
 * When we reach end of the block, return InvalidOffsetNumber which tells
 * SampleScan to go to next block.
 */
static OffsetNumber
system_rows_nextsampletuple(SampleScanState *node,
							BlockNumber blockno,
							OffsetNumber maxoffset)
{
	SystemRowsSamplerData *sampler = (SystemRowsSamplerData *) node->tsm_state;
	OffsetNumber tupoffset = sampler->lt;

	/* Quit if we've returned all needed tuples */
	if (node->donetuples >= sampler->ntuples)
		return InvalidOffsetNumber;

	/* Advance to next possible offset on page */
	if (tupoffset == InvalidOffsetNumber)
		tupoffset = FirstOffsetNumber;
	else
		tupoffset++;

	/* Done? */
	if (tupoffset > maxoffset)
		tupoffset = InvalidOffsetNumber;

	sampler->lt = tupoffset;

	return tupoffset;
}

/*
 * Compute greatest common divisor of two uint32's.
 */
static uint32
gcd(uint32 a, uint32 b)
{
	uint32		c;

	while (a != 0)
	{
		c = a;
		a = b % a;
		b = c;
	}

	return b;
}

/*
 * Pick a random value less than and relatively prime to n, if possible
 * (else return 1).
 */
static uint32
random_relative_prime(uint32 n, pg_prng_state *randstate)
{
	uint32		r;

	/* Safety check to avoid infinite loop or zero result for small n. */
	if (n <= 1)
		return 1;

	/*
	 * This should only take 2 or 3 iterations as the probability of 2 numbers
	 * being relatively prime is ~61%; but just in case, we'll include a
	 * CHECK_FOR_INTERRUPTS in the loop.
	 */
	do
	{
		CHECK_FOR_INTERRUPTS();
		r = (uint32) (sampler_random_fract(randstate) * n);
	} while (r == 0 || gcd(r, n) > 1);

	return r;
}

/* ========== SECTION 6: fuzz-facing driver entries (NOT Postgres code) ===== */

static _Thread_local SampleScanState pg_tsmrows_node;

/* Fresh scan state: arena reset + verbatim initsamplescan (palloc0 zeroes
 * the sampler exactly as PG's executor path does — step == 0 sentinel). */
void
pg_tsmrows_scan_reset(void)
{
	pg_tsmrows_arena_reset();
	pg_diff_errcode = 0;
	system_rows_initsamplescan(&pg_tsmrows_node, 0);
	pg_tsmrows_node.donetuples = 0;
	pg_tsmrows_node.use_pagemode = false;
}

/* 0 = ok, 1 = ereport'ed (class in pg_diff_errcode). */
int
pg_tsmrows_beginsamplescan(int64 ntuples, uint32 seed)
{
	Datum		params[1];

	pg_diff_errcode = 0;
	params[0] = (Datum) ntuples;	/* Int64GetDatum, LP64 by-value */
	if (setjmp(pg_tsmrows_jmp))
		return 1;
	system_rows_beginsamplescan(&pg_tsmrows_node, params, 1, seed);
	return 0;
}

int
pg_tsmrows_use_pagemode(void)
{
	return pg_tsmrows_node.use_pagemode ? 1 : 0;
}

uint32
pg_tsmrows_nextsampleblock(uint32 nblocks, int64 donetuples)
{
	pg_tsmrows_node.donetuples = donetuples;
	return system_rows_nextsampleblock(&pg_tsmrows_node, nblocks);
}

uint16
pg_tsmrows_nextsampletuple(uint32 blockno, uint16 maxoffset, int64 donetuples)
{
	pg_tsmrows_node.donetuples = donetuples;
	return system_rows_nextsampletuple(&pg_tsmrows_node, blockno, maxoffset);
}

/* has_const: 0 = non-Const node (the "didn't obtain a Const" arm);
 * 1 = Const with constisnull/constvalue as given. */
void
pg_tsmrows_getsamplesize(int has_const, int isnull, int64 limitval,
						 uint32 pages, double tuples,
						 uint32 *out_pages, double *out_tuples)
{
	Const		c;
	Node		notconst;
	void	   *limitnode;
	RelOptInfo	baserel;
	BlockNumber pages_out = 0;
	double		tuples_out = 0;

	pg_diff_errcode = 0;
	if (has_const)
	{
		c.type = PG_TSMROWS_T_Const;
		c.constisnull = (isnull != 0);
		c.constvalue = (Datum) limitval;
		limitnode = &c;
	}
	else
	{
		notconst.type = PG_TSMROWS_T_Invalid;
		limitnode = &notconst;
	}
	baserel.tuples = tuples;
	baserel.pages = pages;
	system_rows_samplescangetsamplesize(NULL, &baserel, (List *) limitnode,
										&pages_out, &tuples_out);
	*out_pages = pages_out;
	*out_tuples = tuples_out;
}

/* random_relative_prime over a locally seeded sampler state; *post_draw =
 * one raw engine draw after, witnessing the number of consumed draws. */
uint32
pg_tsmrows_random_relative_prime(uint32 n, uint64 seed, uint64 *post_draw)
{
	pg_prng_state st;
	uint32		r;

	pg_diff_errcode = 0;
	pg_prng_seed(&st, seed);
	r = random_relative_prime(n, &st);
	*post_draw = pg_prng_uint64(&st);
	return r;
}
