/*
 * pg_tablesample_io.c: vendored PostgreSQL C oracle for the tablesample_diff
 * differential fuzz target (100%-coverage campaign, lane p1-wavea). Crate
 * under test: crates/backend/access/tablesample/tablesample.
 *
 * GENERATED by csrc/gen/assemble_tsmpl.sh — verbatim sections are
 * sed-extracted, never hand-typed. Do not edit the VERBATIM sections here;
 * edit the script's shim heredocs and re-run.
 *
 * Provenance (all VERBATIM sections byte-for-byte from
 * ~/dev/pgrust-fabled/vendor/postgres-src, Stamp-18.3, upstream sha
 * 62d6c7d3df6287f1bd83199c1a746e50d31571a0):
 *   - src/include/postgres.h lines 202-210 (DatumGetInt32), 222-240
 *     (DatumGetUInt32, UInt32GetDatum), 458-473 (DatumGetFloat4) — the
 *     Datum conversion static inlines the sampler bodies use (header
 *     static inlines vendored verbatim per the never-fabricate rule).
 *   - src/include/common/hashfn.h lines 30-34 (hash_any static inline
 *     wrapper); hash_bytes itself is NOT duplicated — consumed via extern
 *     from csrc/pg_hashfn_io.c, which vendors src/common/hashfn.c verbatim
 *     (single copy per the duplicate-export rule).
 *   - src/backend/access/tablesample/bernoulli.c lines 36-42
 *     (BernoulliSamplerData), 123-130 (bernoulli_initsamplescan), 132-167
 *     (bernoulli_beginsamplescan), 169-229 (bernoulli_nextsampletuple).
 *     NOT vendored: tsm_bernoulli_handler (lines 61-80, fmgr/makeNode
 *     TsmRoutine registry plumbing — the Rust-only registry arm covers the
 *     shipped dispatch against these literal vtable values; tsmrows
 *     precedent) and bernoulli_samplescangetsamplesize (lines 82-121 —
 *     census OUT: planner fold, excepted).
 *   - src/backend/access/tablesample/system.c lines 36-43
 *     (SystemSamplerData), 126-133 (system_initsamplescan), 135-172
 *     (system_beginsamplescan), 174-221 (system_nextsampleblock), 223-256
 *     (system_nextsampletuple). NOT vendored: tsm_system_handler (lines
 *     63-82) and system_samplescangetsamplesize (lines 84-124) — same two
 *     carves as bernoulli.c.
 *   - src/backend/access/tablesample/tablesample.c: NOT vendored at all —
 *     its only function, GetTsmRoutine, is the syscache/fmgr handler-call
 *     seam (census OUT: Tsm::get, excepted).
 *
 * All vendored bodies are file-static (TU-local): the only external symbols
 * this TU defines are the pg_tsmpl_-prefixed driver entries (nm-census
 * rule). hash_bytes / pg_diff_errcode are consumed, not defined.
 *
 * Shims (PLUMBING ONLY, never logic — census note of record: the C
 * callbacks read only node->tsm_state (+ set use_bulkread/use_pagemode,
 * which ARE compared values here); donetuples untouched by these two
 * methods):
 *   - fixed-width typedefs matching c.h on LP64; BlockNumber/OffsetNumber/
 *     Datum per block.h/off.h/postgres.h; InvalidBlockNumber 0xFFFFFFFF;
 *     InvalidOffsetNumber 0; FirstOffsetNumber 1; PG_UINT32_MAX (c.h line
 *     559: UINT32_MAX).
 *   - SampleScanState: FABRICATED minimal shell {tsm_state, donetuples,
 *     use_bulkread, use_pagemode} (census carve note; execnodes.h's real
 *     struct is executor state the callbacks never touch beyond these).
 *   - ereport(ERROR, (errcode(..), errmsg(..))) -> record errcode class in
 *     the shared TLS pg_diff_errcode channel and longjmp to the armed
 *     driver entry; errmsg swallowed (message text out of scope).
 *     Classes: 0 ok; 1 = 2202H ERRCODE_INVALID_TABLESAMPLE_ARGUMENT.
 *   - palloc0 -> TLS pointer arena (scaffold pattern; reset per exec).
 *   - params[0]: the driver passes the float4 bit pattern as
 *     (Datum) pctbits — identical to Float4GetDatum's low-32 union store
 *     for every bit pattern (DatumGetFloat4 reads only the low 32 bits via
 *     DatumGetInt32; Float4GetDatum's Int32GetDatum sign-extension is
 *     invisible to it).
 */

#include <assert.h>
#include <math.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Shared TLS errcode channel (defined in csrc/pg_float_io.c). */
extern _Thread_local int pg_diff_errcode;

/* Errcode classes (map on the Rust side to sqlstates). */
#define PG_TSMPL_ERRCLASS_TABLESAMPLE 1	/* 2202H */

/* ---------- type shims (c.h / block.h / off.h / postgres.h, LP64) ---------- */
typedef uint32_t uint32;
typedef uint64_t uint64;
typedef int64_t int64;
typedef int32_t int32;
typedef uint16_t uint16;
typedef float float4;
typedef uint32 BlockNumber;
typedef uint16 OffsetNumber;
typedef uintptr_t Datum;

#define InvalidBlockNumber ((BlockNumber) 0xFFFFFFFF)
#define InvalidOffsetNumber ((OffsetNumber) 0)
#define FirstOffsetNumber ((OffsetNumber) 1)
#define PG_UINT32_MAX UINT32_MAX

/* hash_bytes: verbatim src/common/hashfn.c body exported by
 * csrc/pg_hashfn_io.c (single copy per the duplicate-export rule). */
extern uint32 hash_bytes(const unsigned char *k, int keylen);

/* == SECTION 1: src/include/postgres.h lines 202-210 (VERBATIM) == */
/*
 * DatumGetInt32
 *		Returns 32-bit integer value of a datum.
 */
static inline int32
DatumGetInt32(Datum X)
{
	return (int32) X;
}

/* == SECTION 2: src/include/postgres.h lines 222-240 (VERBATIM) == */
/*
 * DatumGetUInt32
 *		Returns 32-bit unsigned integer value of a datum.
 */
static inline uint32
DatumGetUInt32(Datum X)
{
	return (uint32) X;
}

/*
 * UInt32GetDatum
 *		Returns datum representation for a 32-bit unsigned integer.
 */
static inline Datum
UInt32GetDatum(uint32 X)
{
	return (Datum) X;
}

/* == SECTION 3: src/include/postgres.h lines 458-473 (VERBATIM) == */
/*
 * DatumGetFloat4
 *		Returns 4-byte floating point value of a datum.
 */
static inline float4
DatumGetFloat4(Datum X)
{
	union
	{
		int32		value;
		float4		retval;
	}			myunion;

	myunion.value = DatumGetInt32(X);
	return myunion.retval;
}

/* == SECTION 4: src/include/common/hashfn.h lines 30-34 (VERBATIM) == */
static inline Datum
hash_any(const unsigned char *k, int keylen)
{
	return UInt32GetDatum(hash_bytes(k, keylen));
}

/* ---------- ereport shim ---------- */
static _Thread_local jmp_buf pg_tsmpl_jmp;

#define ERROR 21
#define ereport(elevel, rest) \
	do { (void) (rest); longjmp(pg_tsmpl_jmp, 1); } while (0)
#define errcode(c) (pg_diff_errcode = (c))
#define errmsg(...) 0
#define ERRCODE_INVALID_TABLESAMPLE_ARGUMENT PG_TSMPL_ERRCLASS_TABLESAMPLE

/* ---------- SampleScanState fabricated shell (census carve note) ---------- */
typedef struct SampleScanState
{
	void	   *tsm_state;
	int64		donetuples;
	bool		use_bulkread;
	bool		use_pagemode;
} SampleScanState;

/* ---------- palloc arena shim (scaffold pattern) ---------- */
#define PG_DIFF_ARENA_MAX 64
static _Thread_local void *pg_tsmpl_arena[PG_DIFF_ARENA_MAX];
static _Thread_local int pg_tsmpl_arena_n;

static void
pg_tsmpl_arena_reset(void)
{
	int			i;

	for (i = 0; i < pg_tsmpl_arena_n; i++)
		free(pg_tsmpl_arena[i]);
	pg_tsmpl_arena_n = 0;
}

static void *
pg_tsmpl_palloc0_impl(size_t n)
{
	void	   *p = calloc(1, n);

	assert(pg_tsmpl_arena_n < PG_DIFF_ARENA_MAX);
	pg_tsmpl_arena[pg_tsmpl_arena_n++] = p;
	return p;
}

#define palloc0(n) pg_tsmpl_palloc0_impl(n)

/* == SECTION 5: src/backend/access/tablesample/bernoulli.c lines 36-42 (VERBATIM) == */
/* Private state */
typedef struct
{
	uint64		cutoff;			/* select tuples with hash less than this */
	uint32		seed;			/* random seed */
	OffsetNumber lt;			/* last tuple returned from current block */
} BernoulliSamplerData;

/* == SECTION 6: src/backend/access/tablesample/bernoulli.c lines 123-130 (VERBATIM) == */
/*
 * Initialize during executor setup.
 */
static void
bernoulli_initsamplescan(SampleScanState *node, int eflags)
{
	node->tsm_state = palloc0(sizeof(BernoulliSamplerData));
}

/* == SECTION 7: src/backend/access/tablesample/bernoulli.c lines 132-167 (VERBATIM) == */
/*
 * Examine parameters and prepare for a sample scan.
 */
static void
bernoulli_beginsamplescan(SampleScanState *node,
						  Datum *params,
						  int nparams,
						  uint32 seed)
{
	BernoulliSamplerData *sampler = (BernoulliSamplerData *) node->tsm_state;
	double		percent = DatumGetFloat4(params[0]);
	double		dcutoff;

	if (percent < 0 || percent > 100 || isnan(percent))
		ereport(ERROR,
				(errcode(ERRCODE_INVALID_TABLESAMPLE_ARGUMENT),
				 errmsg("sample percentage must be between 0 and 100")));

	/*
	 * The cutoff is sample probability times (PG_UINT32_MAX + 1); we have to
	 * store that as a uint64, of course.  Note that this gives strictly
	 * correct behavior at the limits of zero or one probability.
	 */
	dcutoff = rint(((double) PG_UINT32_MAX + 1) * percent / 100);
	sampler->cutoff = (uint64) dcutoff;
	sampler->seed = seed;
	sampler->lt = InvalidOffsetNumber;

	/*
	 * Use bulkread, since we're scanning all pages.  But pagemode visibility
	 * checking is a win only at larger sampling fractions.  The 25% cutoff
	 * here is based on very limited experimentation.
	 */
	node->use_bulkread = true;
	node->use_pagemode = (percent >= 25);
}

/* == SECTION 8: src/backend/access/tablesample/bernoulli.c lines 169-229 (VERBATIM) == */
/*
 * Select next sampled tuple in current block.
 *
 * It is OK here to return an offset without knowing if the tuple is visible
 * (or even exists).  The reason is that we do the coinflip for every tuple
 * offset in the table.  Since all tuples have the same probability of being
 * returned, it doesn't matter if we do extra coinflips for invisible tuples.
 *
 * When we reach end of the block, return InvalidOffsetNumber which tells
 * SampleScan to go to next block.
 */
static OffsetNumber
bernoulli_nextsampletuple(SampleScanState *node,
						  BlockNumber blockno,
						  OffsetNumber maxoffset)
{
	BernoulliSamplerData *sampler = (BernoulliSamplerData *) node->tsm_state;
	OffsetNumber tupoffset = sampler->lt;
	uint32		hashinput[3];

	/* Advance to first/next tuple in block */
	if (tupoffset == InvalidOffsetNumber)
		tupoffset = FirstOffsetNumber;
	else
		tupoffset++;

	/*
	 * We compute the hash by applying hash_any to an array of 3 uint32's
	 * containing the block, offset, and seed.  This is efficient to set up,
	 * and with the current implementation of hash_any, it gives
	 * machine-independent results, which is a nice property for regression
	 * testing.
	 *
	 * These words in the hash input are the same throughout the block:
	 */
	hashinput[0] = blockno;
	hashinput[2] = sampler->seed;

	/*
	 * Loop over tuple offsets until finding suitable TID or reaching end of
	 * block.
	 */
	for (; tupoffset <= maxoffset; tupoffset++)
	{
		uint32		hash;

		hashinput[1] = tupoffset;

		hash = DatumGetUInt32(hash_any((const unsigned char *) hashinput,
									   (int) sizeof(hashinput)));
		if (hash < sampler->cutoff)
			break;
	}

	if (tupoffset > maxoffset)
		tupoffset = InvalidOffsetNumber;

	sampler->lt = tupoffset;

	return tupoffset;
}

/* == SECTION 9: src/backend/access/tablesample/system.c lines 36-43 (VERBATIM) == */
/* Private state */
typedef struct
{
	uint64		cutoff;			/* select blocks with hash less than this */
	uint32		seed;			/* random seed */
	BlockNumber nextblock;		/* next block to consider sampling */
	OffsetNumber lt;			/* last tuple returned from current block */
} SystemSamplerData;

/* == SECTION 10: src/backend/access/tablesample/system.c lines 126-133 (VERBATIM) == */
/*
 * Initialize during executor setup.
 */
static void
system_initsamplescan(SampleScanState *node, int eflags)
{
	node->tsm_state = palloc0(sizeof(SystemSamplerData));
}

/* == SECTION 11: src/backend/access/tablesample/system.c lines 135-172 (VERBATIM) == */
/*
 * Examine parameters and prepare for a sample scan.
 */
static void
system_beginsamplescan(SampleScanState *node,
					   Datum *params,
					   int nparams,
					   uint32 seed)
{
	SystemSamplerData *sampler = (SystemSamplerData *) node->tsm_state;
	double		percent = DatumGetFloat4(params[0]);
	double		dcutoff;

	if (percent < 0 || percent > 100 || isnan(percent))
		ereport(ERROR,
				(errcode(ERRCODE_INVALID_TABLESAMPLE_ARGUMENT),
				 errmsg("sample percentage must be between 0 and 100")));

	/*
	 * The cutoff is sample probability times (PG_UINT32_MAX + 1); we have to
	 * store that as a uint64, of course.  Note that this gives strictly
	 * correct behavior at the limits of zero or one probability.
	 */
	dcutoff = rint(((double) PG_UINT32_MAX + 1) * percent / 100);
	sampler->cutoff = (uint64) dcutoff;
	sampler->seed = seed;
	sampler->nextblock = 0;
	sampler->lt = InvalidOffsetNumber;

	/*
	 * Bulkread buffer access strategy probably makes sense unless we're
	 * scanning a very small fraction of the table.  The 1% cutoff here is a
	 * guess.  We should use pagemode visibility checking, since we scan all
	 * tuples on each selected page.
	 */
	node->use_bulkread = (percent >= 1);
	node->use_pagemode = true;
}

/* == SECTION 12: src/backend/access/tablesample/system.c lines 174-221 (VERBATIM) == */
/*
 * Select next block to sample.
 */
static BlockNumber
system_nextsampleblock(SampleScanState *node, BlockNumber nblocks)
{
	SystemSamplerData *sampler = (SystemSamplerData *) node->tsm_state;
	BlockNumber nextblock = sampler->nextblock;
	uint32		hashinput[2];

	/*
	 * We compute the hash by applying hash_any to an array of 2 uint32's
	 * containing the block number and seed.  This is efficient to set up, and
	 * with the current implementation of hash_any, it gives
	 * machine-independent results, which is a nice property for regression
	 * testing.
	 *
	 * These words in the hash input are the same throughout the block:
	 */
	hashinput[1] = sampler->seed;

	/*
	 * Loop over block numbers until finding suitable block or reaching end of
	 * relation.
	 */
	for (; nextblock < nblocks; nextblock++)
	{
		uint32		hash;

		hashinput[0] = nextblock;

		hash = DatumGetUInt32(hash_any((const unsigned char *) hashinput,
									   (int) sizeof(hashinput)));
		if (hash < sampler->cutoff)
			break;
	}

	if (nextblock < nblocks)
	{
		/* Found a suitable block; remember where we should start next time */
		sampler->nextblock = nextblock + 1;
		return nextblock;
	}

	/* Done, but let's reset nextblock to 0 for safety. */
	sampler->nextblock = 0;
	return InvalidBlockNumber;
}

/* == SECTION 13: src/backend/access/tablesample/system.c lines 223-256 (VERBATIM) == */
/*
 * Select next sampled tuple in current block.
 *
 * In block sampling, we just want to sample all the tuples in each selected
 * block.
 *
 * It is OK here to return an offset without knowing if the tuple is visible
 * (or even exists); nodeSamplescan.c will deal with that.
 *
 * When we reach end of the block, return InvalidOffsetNumber which tells
 * SampleScan to go to next block.
 */
static OffsetNumber
system_nextsampletuple(SampleScanState *node,
					   BlockNumber blockno,
					   OffsetNumber maxoffset)
{
	SystemSamplerData *sampler = (SystemSamplerData *) node->tsm_state;
	OffsetNumber tupoffset = sampler->lt;

	/* Advance to next possible offset on page */
	if (tupoffset == InvalidOffsetNumber)
		tupoffset = FirstOffsetNumber;
	else
		tupoffset++;

	/* Done? */
	if (tupoffset > maxoffset)
		tupoffset = InvalidOffsetNumber;

	sampler->lt = tupoffset;

	return tupoffset;
}

/* ========== SECTION 14: fuzz-facing driver entries (NOT Postgres code) ===== */

static _Thread_local SampleScanState pg_tsmpl_node;

/* Fresh scan state for the given method (0 = bernoulli, 1 = system):
 * arena reset + the verbatim initsamplescan (palloc0 zeroes the sampler
 * exactly as PG's executor path does). */
void
pg_tsmpl_scan_reset(int method)
{
	pg_tsmpl_arena_reset();
	pg_diff_errcode = 0;
	if (method == 0)
		bernoulli_initsamplescan(&pg_tsmpl_node, 0);
	else
		system_initsamplescan(&pg_tsmpl_node, 0);
	pg_tsmpl_node.donetuples = 0;
	pg_tsmpl_node.use_bulkread = false;
	pg_tsmpl_node.use_pagemode = false;
}

/* 0 = ok, 1 = ereport'ed (class in pg_diff_errcode). pctbits = the float4
 * parameter's bit pattern (see the params[0] plumbing note in the header).
 * On ok, *out_bulkread / *out_pagemode carry the compared flag outputs. */
int
pg_tsmpl_beginsamplescan(int method, uint32 pctbits, uint32 seed,
						 int *out_bulkread, int *out_pagemode)
{
	Datum		params[1];

	pg_diff_errcode = 0;
	params[0] = (Datum) pctbits;
	if (setjmp(pg_tsmpl_jmp))
		return 1;
	if (method == 0)
		bernoulli_beginsamplescan(&pg_tsmpl_node, params, 1, seed);
	else
		system_beginsamplescan(&pg_tsmpl_node, params, 1, seed);
	*out_bulkread = pg_tsmpl_node.use_bulkread ? 1 : 0;
	*out_pagemode = pg_tsmpl_node.use_pagemode ? 1 : 0;
	return 0;
}

/* SYSTEM only (bernoulli has NextSampleBlock == NULL in its vtable). */
uint32
pg_tsmpl_nextsampleblock(uint32 nblocks)
{
	return system_nextsampleblock(&pg_tsmpl_node, nblocks);
}

uint16
pg_tsmpl_nextsampletuple(int method, uint32 blockno, uint16 maxoffset)
{
	if (method == 0)
		return bernoulli_nextsampletuple(&pg_tsmpl_node, blockno, maxoffset);
	return system_nextsampletuple(&pg_tsmpl_node, blockno, maxoffset);
}
