[package]
name = "pg_proc"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
pgstat = { path = "../../utils/activity/pgstat" }
mcx = { path = "../../../_support/mcx" }
datum = { path = "../../../_support/types/datum" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
elog = { path = "../../utils/error/elog" }
pquery = { path = "../../tcop/pquery" }
types_portal = { path = "../../../_support/types/portal" }
types_rel = { path = "../../../_support/types/rel" }
types_tuple = { path = "../../../_support/types/types_tuple" }
types_fmgr = { path = "../../../_support/types/fmgr" }
heaptuple = { path = "../../access/common/heaptuple" }
table = { path = "../../access/table/table" }
catalog = { path = "../catalog" }
catalog_seams = { path = "../catalog_seams" }
catalog_indexing = { path = "../catalog_indexing" }
pg_depend = { path = "../pg_depend" }
aclchk_seams = { path = "../aclchk_seams" }
aclchk = { path = "../aclchk" }
types_nodes = { path = "../../../_support/types/nodes" }
outfuncs = { path = "../../nodes/outfuncs" }
dependency_seams = { path = "../dependency_seams" }
cache_syscache = { path = "../../utils/cache/cache_syscache" }
varlena = { path = "../../utils/adt/varlena" }
readfuncs = { path = "../../nodes/readfuncs" }
nodes_core = { path = "../../nodes/nodes_core" }
format_type = { path = "../../utils/adt/format_type" }
fmgr_core = { path = "../../utils/fmgr/fmgr_core" }
dfmgr = { path = "../../utils/fmgr/dfmgr" }
syscache_seams = { path = "../../utils/cache/syscache_seams" }
lsyscache = { path = "../../utils/cache/lsyscache" }
xact = { path = "../../access/transam/xact" }
funcapi = { path = "../../utils/fmgr/funcapi" }
tupdesc = { path = "../../access/common/tupdesc" }
guc_seams = { path = "../../utils/misc/guc_seams" }
guc_tables = { path = "../../utils/misc/guc_tables" }
