// Vectors generated by running the vendored src/common/hashfn.c (see data/).
mod c_vectors {
    include!("data/c_vectors.rs");
}
use c_vectors::*;

fn fill_buf() -> Vec<u8> {
    let mut prng: u64 = 0x243f6a8885a308d3;
    (0..8192)
        .map(|_| {
            prng = prng
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            (prng >> 56) as u8
        })
        .collect()
}

#[test]
fn hash_bytes_matches_c() {
    let buf = fill_buf();
    assert!(HASH_BYTES.len() >= 71 * 8);
    for &(len, off, expect) in HASH_BYTES {
        assert_eq!(
            hashfn::hash_bytes(&buf[off..off + len]),
            expect,
            "len={len} off={off}"
        );
    }
}

#[test]
fn hash_bytes_extended_matches_c() {
    let buf = fill_buf();
    for &(len, off, seed, expect) in HASH_BYTES_EXTENDED {
        assert_eq!(
            hashfn::hash_bytes_extended(&buf[off..off + len], seed),
            expect,
            "len={len} off={off} seed={seed:#x}"
        );
    }
}

#[test]
fn uint32_variants_match_c() {
    for &(k, expect) in HASH_BYTES_UINT32 {
        assert_eq!(hashfn::hash_bytes_uint32(k), expect);
        assert_eq!(hashfn::uint32_hash(k), expect);
    }
    for &(k, seed, expect) in HASH_BYTES_UINT32_EXTENDED {
        assert_eq!(hashfn::hash_bytes_uint32_extended(k, seed), expect);
    }
}

#[test]
fn header_helpers_match_c() {
    for &(a, b, expect) in HASH_COMBINE {
        assert_eq!(hashfn::hash_combine(a, b), expect);
    }
    for &(a, b, expect) in HASH_COMBINE64 {
        assert_eq!(hashfn::hash_combine64(a, b), expect);
    }
    for &(x, expect) in MURMURHASH32 {
        assert_eq!(hashfn::murmurhash32(x), expect);
    }
    for &(x, expect) in MURMURHASH64 {
        assert_eq!(hashfn::murmurhash64(x), expect);
    }
    for &(v, expect) in ROTATE_HL32 {
        assert_eq!(hashfn::rotate_high_and_low_32bits(v), expect);
    }
}

#[test]
fn dynahash_wrappers_match_c() {
    for &(keysize, expect) in STRING_HASH {
        assert_eq!(hashfn::string_hash(STRING_HASH_KEY, keysize), expect);
    }
    let buf = fill_buf();
    for &(keysize, off, expect) in TAG_HASH {
        assert_eq!(hashfn::tag_hash(&buf[off..], keysize), expect);
    }
}
