//! record_in / record_out whitespace conformance against executed PostgreSQL 18.4.
//!
//! C's rowtypes.c asks "is this whitespace?" through `isspace((unsigned char))`
//! in exactly three places -- record_in's leading skip (rowtypes.c:152), its
//! trailing skip (:290), and record_out's needquote predicate (:445).  Rust's
//! `u8::is_ascii_whitespace` omits VT (0x0b), so a hand-rolled predicate here
//! silently disagrees with C on that one byte.
//!
//! The expectation table in `c_cases` is machine-generated by
//! scripts/gen-rowtypes-ws-differential.py from a psql run against PostgreSQL
//! 18.4: the SQL and this case list come from one source so they cannot drift.
//! Control characters reached the server only through `chr()`.
extern crate std;

use std::string::String;
use std::vec::Vec;

use super::*;
use crate::c_cases::{IN_CASES, OUT_CASES};

use ::mcx::MemoryContext;
use ::types_core::catalog::RECORDOID;
use ::types_fmgr::LocalFcinfo;
use ::types_tuple::FormData_pg_attribute;

const TEXTOID: Oid = 25;
const MYTEXTIN: Oid = 990_001;
const MYTEXTOUT: Oid = 990_002;

// An identity text codec, so this file exercises rowtypes' own quoting and
// nothing else.  (The sibling `varlena` crate is deliberately not pulled in.)
std::thread_local! {
    static OUT_SCRATCH: core::cell::RefCell<Vec<u8>> = const { core::cell::RefCell::new(Vec::new()) };
}

fn fc_mytextin(_f: Option<&mut FmgrInfo>, fcinfo: &mut Fcinfo) -> PgResult<Datum> {
    let s = unsafe { fcinfo.arg_cstring(0) }.to_bytes();
    let mcx = fcinfo.result_mcx();
    let total = ::datum::VARHDRSZ + s.len();
    let mut img = vec_with_capacity_in(mcx, total)?;
    ::mcx::vec_append_bytes(&mut img, &::datum::varlena::set_varsize_4b(total))?;
    ::mcx::vec_append_bytes(&mut img, s)?;
    let d = Datum::from_usize(img.as_ptr() as usize);
    core::mem::forget(img);
    Ok(d)
}

/// VARDATA_ANY/VARSIZE_ANY_EXHDR: heap_form_tuple converts short values to the
/// 1-byte header form, so the header size has to be read off the datum.
fn payload<'a>(d: Datum) -> &'a [u8] {
    let p = d.as_usize() as *const u8;
    // SAFETY: a live varlena built by fc_mytextin or deformed out of a tuple.
    unsafe {
        let total = ::types_tuple::varatt::varsize_any(p);
        let hdr = if ::types_tuple::varatt::varatt_is_1b(p) {
            1
        } else {
            ::datum::VARHDRSZ
        };
        core::slice::from_raw_parts(p.add(hdr), total - hdr)
    }
}

fn fc_mytextout(_f: Option<&mut FmgrInfo>, fcinfo: &mut Fcinfo) -> PgResult<Datum> {
    let bytes = payload(fcinfo.arg(0)).to_vec();
    OUT_SCRATCH.with(|c| {
        let mut b = c.borrow_mut();
        b.clear();
        b.extend_from_slice(&bytes);
        b.push(0);
        Ok(Datum::from_usize(b.as_ptr() as usize))
    })
}

static SEAMS: std::sync::Once = std::sync::Once::new();

fn install() {
    SEAMS.call_once(|| {
        ::syscache_seams::pg_type_io_shape::set(|typid| {
            Ok((typid == TEXTOID).then(|| ::syscache_seams::PgTypeIoShape {
                oid: TEXTOID,
                typinput: MYTEXTIN,
                typoutput: MYTEXTOUT,
                typreceive: InvalidOid,
                typsend: InvalidOid,
                typmodin: InvalidOid,
                typmodout: InvalidOid,
                typelem: InvalidOid,
                typlen: -1,
                typbyval: false,
                typalign: b'i' as i8,
                typdelim: b',' as i8,
                typisdefined: true,
            }))
        });
        ::fmgr_seams::fmgr_info::set(|oid| match oid {
            MYTEXTIN => Ok(FmgrInfo::new(fc_mytextin, MYTEXTIN, 1, true, false)),
            MYTEXTOUT => Ok(FmgrInfo::new(fc_mytextout, MYTEXTOUT, 1, true, false)),
            _ => panic!("fmgr_info: unexpected oid {oid}"),
        });
        ::detoast_seams::detoast_attr::set(|mcx, raw| {
            // No toasting in these fixtures: the image is already plain.
            let mut v = vec_with_capacity_in(mcx, raw.len())?;
            ::mcx::vec_append_bytes(&mut v, raw)?;
            Ok(v)
        });
    });
}

fn att(name: &str, num: i16) -> FormData_pg_attribute {
    let mut a = FormData_pg_attribute::default();
    a.attname.namestrcpy(name);
    a.attnum = num;
    a.atttypid = TEXTOID;
    a.attlen = -1;
    a.attbyval = false;
    a.attalign = b'i' as i8;
    a.attstorage = b'x' as i8;
    a.atttypmod = -1;
    a
}

/// ct = (a text, b text), registered as an anonymous RECORD so no catalog is
/// needed.  Returns the typmod record_in/record_out are keyed by.
fn ct_typmod(mcx: ::mcx::Mcx<'_>) -> i32 {
    let mut td = ::tupdesc::CreateTupleDesc(mcx, &[att("a", 1), att("b", 2)]).unwrap();
    td.tdtypeid = RECORDOID;
    td.tdtypmod = -1;
    ::typcache::assign_record_type_typmod(&mut td).unwrap();
    td.tdtypmod
}

fn hex(b: &[u8]) -> String {
    let mut s = String::new();
    for &x in b {
        s.push_str(&std::format!("{x:02x}"));
    }
    s
}

/// record_in.  `Err` collapses to None, matching the table's "ERR".
fn record_in(mcx: ::mcx::Mcx<'_>, typmod: i32, literal: &[u8]) -> Option<Datum> {
    let mut cstr = literal.to_vec();
    cstr.push(0);
    let mut fci = LocalFcinfo::<3>::new(0);
    unsafe { fci.set_result_mcx(mcx) };
    fci.set_arg(0, Datum::from_usize(cstr.as_ptr() as usize));
    fci.set_arg(1, Datum::from_oid(RECORDOID));
    fci.set_arg(2, Datum::from_i32(typmod));
    let mut flinfo = FmgrInfo::new(fc_record_in, 0, 3, true, false);
    let r = fc_record_in(Some(&mut flinfo), &mut fci).ok();
    // keep `cstr` alive until record_in has finished reading it
    core::hint::black_box(&cstr);
    r
}

fn record_out(mcx: ::mcx::Mcx<'_>, d: Datum) -> Option<Vec<u8>> {
    let mut fci = LocalFcinfo::<1>::new(0);
    unsafe { fci.set_result_mcx(mcx) };
    fci.set_arg(0, d);
    let mut flinfo = FmgrInfo::new(fc_record_out, 0, 1, true, false);
    let r = fc_record_out(Some(&mut flinfo), &mut fci).ok()?;
    let p = r.as_usize() as *const u8;
    let mut v = Vec::new();
    let mut i = 0usize;
    loop {
        let c = unsafe { *p.add(i) };
        if c == 0 {
            break;
        }
        v.push(c);
        i += 1;
    }
    Some(v)
}

/// The two field values of a parsed composite, as `Option<payload>`.
fn fields(mcx: ::mcx::Mcx<'_>, d: Datum) -> [Option<Vec<u8>>; 2] {
    let p = d.as_usize() as *const u8;
    let total = unsafe { ::types_tuple::varatt::varsize_any(p) };
    let raw = unsafe { core::slice::from_raw_parts(p, total) };
    let hdr = unsafe { &*(raw.as_ptr() as *const HeapTupleHeaderData) };
    let tupdesc =
        ::typcache::lookup_rowtype_tupdesc_copy(mcx, hdr.type_id(), hdr.typmod()).unwrap();
    let tuple = unsafe {
        HeapTupleData::from_raw_parts(
            raw.as_ptr(),
            hdr.datum_length(),
            ItemPointerData::invalid(),
            InvalidOid,
        )
    };
    let n = tupdesc.natts as usize;
    let mut values: PgVec<'_, Datum> = vec_from_elem_in(mcx, Datum::null(), n);
    let mut nulls: PgVec<'_, bool> = vec_from_elem_in(mcx, true, n);
    ::types_tuple::heap_deform_tuple(&tuple, &tupdesc, &mut values, &mut nulls);
    [0usize, 1].map(|i| (!nulls[i]).then(|| payload(values[i]).to_vec()))
}

/// The exact string the SQL fixture printed, so a cell compares verbatim.
fn describe_in(mcx: ::mcx::Mcx<'_>, typmod: i32, literal: &[u8]) -> String {
    match record_in(mcx, typmod, literal) {
        None => String::from("ERR"),
        Some(d) => {
            let f = fields(mcx, d);
            let show = |o: &Option<Vec<u8>>| match o {
                None => String::from("<NULL>"),
                Some(v) => hex(v),
            };
            let out = record_out(mcx, d).expect("record_out must succeed on a parsed record");
            std::format!("OK f1={} f2={} out={}", show(&f[0]), show(&f[1]), hex(&out))
        }
    }
}

#[test]
fn record_in_whitespace_positions_match_c() {
    install();
    let ctx = MemoryContext::new("ws_in");
    let mcx = ctx.mcx();
    let typmod = ct_typmod(mcx);
    let mut bad = Vec::new();
    for c in IN_CASES {
        let got = describe_in(mcx, typmod, c.literal);
        if got != c.expect {
            bad.push(std::format!(
                "{}/{}: literal={} C={} pgrust={}",
                c.name,
                c.ch,
                hex(c.literal),
                c.expect,
                got
            ));
        }
    }
    assert!(
        bad.is_empty(),
        "{} divergent cells:\n{}",
        bad.len(),
        bad.join("\n")
    );
}

#[test]
fn record_out_quoting_and_roundtrip_match_c() {
    install();
    let ctx = MemoryContext::new("ws_out");
    let mcx = ctx.mcx();
    let typmod = ct_typmod(mcx);
    let mut bad = Vec::new();
    for c in OUT_CASES {
        // Build (value, 'z') without leaning on the predicate under test: the
        // value arrives inside double quotes, where whitespace is always literal.
        let mut lit = Vec::new();
        lit.push(b'(');
        lit.push(b'"');
        lit.extend_from_slice(c.value);
        lit.extend_from_slice(b"\",z)");
        let d = record_in(mcx, typmod, &lit).expect("quoted literal must parse");
        let out = record_out(mcx, d).expect("record_out");
        // Feed our own output back in: does it reproduce the field?
        let rt = match record_in(mcx, typmod, &out) {
            None => String::from("rt=ERR"),
            Some(d2) => match &fields(mcx, d2)[0] {
                Some(v) if v.as_slice() == c.value => String::from("rt=EQ"),
                Some(v) => std::format!("rt=NE:{}", hex(v)),
                None => String::from("rt=NE:<NULL>"),
            },
        };
        let got = std::format!("out={} {}", hex(&out), rt);
        if got != c.expect {
            bad.push(std::format!(
                "{}/{}: value={} C={} pgrust={}",
                c.name,
                c.ch,
                hex(c.value),
                c.expect,
                got
            ));
        }
    }
    assert!(
        bad.is_empty(),
        "{} divergent cells:\n{}",
        bad.len(),
        bad.join("\n")
    );
}

/// The predicate itself, spelled out: C-locale isspace is {HT,LF,VT,FF,CR,SP}
/// and nothing else.  Guards against a future edit reaching for the Rust set.
#[test]
fn c_locale_isspace_set_is_exact() {
    for b in 0u8..=255 {
        let want = matches!(b, 0x09 | 0x0a | 0x0b | 0x0c | 0x0d | 0x20);
        assert_eq!(isspace_c_locale(b), want, "byte 0x{b:02x}");
    }
    // The single byte Rust's own predicate gets wrong.
    assert!(!0x0bu8.is_ascii_whitespace());
    assert!(isspace_c_locale(0x0b));
}

/// Boundary-guard audit finding 5: nested/huge ROW output grew into an
/// unceilinged PgVec — gigabytes of RSS from one statement where C's
/// enlargeStringInfo raises "string buffer exceeds maximum allowed length
/// (1073741823 bytes)" immediately. record_out now builds in the StringInfo
/// port; pre-fix this test FAILS because the over-ceiling output succeeds.
/// (~537MB of '"' doubles under record_out quoting, crossing 1GB.)
#[test]
fn record_out_over_ceiling_output_raises_c_stringinfo_error() {
    install();
    let ctx = MemoryContext::new("t");
    let mcx = ctx.mcx();
    let typmod = ct_typmod(mcx);
    let tupdesc = ::typcache::lookup_rowtype_tupdesc_copy(mcx, RECORDOID, typmod).unwrap();

    let n = ::mcx::MAX_ALLOC_SIZE / 2 + 16;
    let total = ::datum::VARHDRSZ + n;
    let mut img: Vec<u8> = Vec::with_capacity(total);
    img.extend_from_slice(&::datum::varlena::set_varsize_4b(total));
    img.resize(total, b'"');
    let d = Datum::from_usize(img.as_ptr() as usize);

    let tuple =
        ::heaptuple::heap_form_tuple(mcx, &tupdesc, &[d, Datum::null()], &[false, true])
            .unwrap();
    let rec = Datum::from_usize(tuple.image().as_ptr() as usize);
    core::mem::forget(tuple);
    drop(img);

    let mut fci = LocalFcinfo::<1>::new(0);
    unsafe { fci.set_result_mcx(mcx) };
    fci.set_arg(0, rec);
    let mut flinfo = FmgrInfo::new(fc_record_out, 0, 1, true, false);
    let err = fc_record_out(Some(&mut flinfo), &mut fci)
        .expect_err("record_out output above MaxAllocSize must raise C's StringInfo ceiling error");
    assert_eq!(
        err.message(),
        std::format!(
            "string buffer exceeds maximum allowed length ({} bytes)",
            ::mcx::MAX_ALLOC_SIZE
        )
    );
}
