// @generated by scripts/gen-rowtypes-ws-differential.py from executed
// PostgreSQL 18.4 (Debian, glibc, aarch64) output.  DO NOT EDIT BY HAND:
// every expectation below is verbatim C behavior.
//
// Type under test: ct = (a text, b text).
// IN_CASES feed the literal to record_in; the expectation is
//   "OK f1=<hex> f2=<hex> out=<hex>"  (out = record_out of the parsed value)
//   or "ERR" (C's own message rides in the trailing comment).
// OUT_CASES put the character inside a field value and check record_out's
// quoting plus that the output reads back equal (rt=EQ).

pub(crate) struct InCase {
    pub name: &'static str,
    pub ch: &'static str,
    pub literal: &'static [u8],
    pub expect: &'static str,
}

pub(crate) struct OutCase {
    pub name: &'static str,
    pub ch: &'static str,
    /// field-a value; the test builds it by feeding record_in a QUOTED
    /// literal, a path that never depended on the predicate under test.
    pub value: &'static [u8],
    pub expect: &'static str,
}

#[rustfmt::skip]
pub(crate) const IN_CASES: &[InCase] = &[
    InCase { name: "p01_leading", ch: "SP", literal: &[0x20, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p02_after_lparen", ch: "SP", literal: &[0x28, 0x20, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=2061 f2=62 out=28222061222c6229" }, // C: OK f1=2061 f2=62 out=28222061222c6229
    InCase { name: "p03_before_comma", ch: "SP", literal: &[0x28, 0x61, 0x20, 0x2c, 0x62, 0x29],
        expect: "OK f1=6120 f2=62 out=28226120222c6229" }, // C: OK f1=6120 f2=62 out=28226120222c6229
    InCase { name: "p04_after_comma", ch: "SP", literal: &[0x28, 0x61, 0x2c, 0x20, 0x62, 0x29],
        expect: "OK f1=61 f2=2062 out=28612c2220622229" }, // C: OK f1=61 f2=2062 out=28612c2220622229
    InCase { name: "p05_before_rparen", ch: "SP", literal: &[0x28, 0x61, 0x2c, 0x62, 0x20, 0x29],
        expect: "OK f1=61 f2=6220 out=28612c2262202229" }, // C: OK f1=61 f2=6220 out=28612c2262202229
    InCase { name: "p06_trailing", ch: "SP", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x20],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p07_in_quotes", ch: "SP", literal: &[0x28, 0x22, 0x61, 0x20, 0x62, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=612062 f2=62 out=2822612062222c6229" }, // C: OK f1=612062 f2=62 out=2822612062222c6229
    InCase { name: "p08_after_backslash", ch: "SP", literal: &[0x28, 0x61, 0x5c, 0x20, 0x62, 0x2c, 0x62, 0x29],
        expect: "OK f1=612062 f2=62 out=2822612062222c6229" }, // C: OK f1=612062 f2=62 out=2822612062222c6229
    InCase { name: "p09_lone_field", ch: "SP", literal: &[0x28, 0x20, 0x2c, 0x62, 0x29],
        expect: "OK f1=20 f2=62 out=282220222c6229" }, // C: OK f1=20 f2=62 out=282220222c6229
    InCase { name: "p10_only_ws", ch: "SP", literal: &[0x20],
        expect: "ERR" }, // C: ERR malformed record literal: " "
    InCase { name: "p11_leading_twice", ch: "SP", literal: &[0x20, 0x20, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p12_lead_and_trail", ch: "SP", literal: &[0x20, 0x28, 0x61, 0x2c, 0x62, 0x29, 0x20],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p13_ws_before_lparen_after_ws", ch: "SP", literal: &[0x20, 0x20, 0x20, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p14_quoted_only_ws", ch: "SP", literal: &[0x28, 0x22, 0x20, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=20 f2=62 out=282220222c6229" }, // C: OK f1=20 f2=62 out=282220222c6229
    InCase { name: "p15_empty_field", ch: "SP", literal: &[0x28, 0x2c, 0x62, 0x29],
        expect: "OK f1=<NULL> f2=62 out=282c6229" }, // C: OK f1=<NULL> f2=62 out=282c6229
    InCase { name: "p16_trailing_then_junk", ch: "SP", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x20, 0x78],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b) x"
    InCase { name: "p01_leading", ch: "HT", literal: &[0x09, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p02_after_lparen", ch: "HT", literal: &[0x28, 0x09, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=0961 f2=62 out=28220961222c6229" }, // C: OK f1=0961 f2=62 out=28220961222c6229
    InCase { name: "p03_before_comma", ch: "HT", literal: &[0x28, 0x61, 0x09, 0x2c, 0x62, 0x29],
        expect: "OK f1=6109 f2=62 out=28226109222c6229" }, // C: OK f1=6109 f2=62 out=28226109222c6229
    InCase { name: "p04_after_comma", ch: "HT", literal: &[0x28, 0x61, 0x2c, 0x09, 0x62, 0x29],
        expect: "OK f1=61 f2=0962 out=28612c2209622229" }, // C: OK f1=61 f2=0962 out=28612c2209622229
    InCase { name: "p05_before_rparen", ch: "HT", literal: &[0x28, 0x61, 0x2c, 0x62, 0x09, 0x29],
        expect: "OK f1=61 f2=6209 out=28612c2262092229" }, // C: OK f1=61 f2=6209 out=28612c2262092229
    InCase { name: "p06_trailing", ch: "HT", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x09],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p07_in_quotes", ch: "HT", literal: &[0x28, 0x22, 0x61, 0x09, 0x62, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=610962 f2=62 out=2822610962222c6229" }, // C: OK f1=610962 f2=62 out=2822610962222c6229
    InCase { name: "p08_after_backslash", ch: "HT", literal: &[0x28, 0x61, 0x5c, 0x09, 0x62, 0x2c, 0x62, 0x29],
        expect: "OK f1=610962 f2=62 out=2822610962222c6229" }, // C: OK f1=610962 f2=62 out=2822610962222c6229
    InCase { name: "p09_lone_field", ch: "HT", literal: &[0x28, 0x09, 0x2c, 0x62, 0x29],
        expect: "OK f1=09 f2=62 out=282209222c6229" }, // C: OK f1=09 f2=62 out=282209222c6229
    InCase { name: "p10_only_ws", ch: "HT", literal: &[0x09],
        expect: "ERR" }, // C: ERR malformed record literal: "	"
    InCase { name: "p11_leading_twice", ch: "HT", literal: &[0x09, 0x09, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p12_lead_and_trail", ch: "HT", literal: &[0x09, 0x28, 0x61, 0x2c, 0x62, 0x29, 0x09],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p13_ws_before_lparen_after_ws", ch: "HT", literal: &[0x09, 0x20, 0x09, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p14_quoted_only_ws", ch: "HT", literal: &[0x28, 0x22, 0x09, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=09 f2=62 out=282209222c6229" }, // C: OK f1=09 f2=62 out=282209222c6229
    InCase { name: "p15_empty_field", ch: "HT", literal: &[0x28, 0x2c, 0x62, 0x29],
        expect: "OK f1=<NULL> f2=62 out=282c6229" }, // C: OK f1=<NULL> f2=62 out=282c6229
    InCase { name: "p16_trailing_then_junk", ch: "HT", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x09, 0x78],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)	x"
    InCase { name: "p01_leading", ch: "LF", literal: &[0x0a, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p02_after_lparen", ch: "LF", literal: &[0x28, 0x0a, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=0a61 f2=62 out=28220a61222c6229" }, // C: OK f1=0a61 f2=62 out=28220a61222c6229
    InCase { name: "p03_before_comma", ch: "LF", literal: &[0x28, 0x61, 0x0a, 0x2c, 0x62, 0x29],
        expect: "OK f1=610a f2=62 out=2822610a222c6229" }, // C: OK f1=610a f2=62 out=2822610a222c6229
    InCase { name: "p04_after_comma", ch: "LF", literal: &[0x28, 0x61, 0x2c, 0x0a, 0x62, 0x29],
        expect: "OK f1=61 f2=0a62 out=28612c220a622229" }, // C: OK f1=61 f2=0a62 out=28612c220a622229
    InCase { name: "p05_before_rparen", ch: "LF", literal: &[0x28, 0x61, 0x2c, 0x62, 0x0a, 0x29],
        expect: "OK f1=61 f2=620a out=28612c22620a2229" }, // C: OK f1=61 f2=620a out=28612c22620a2229
    InCase { name: "p06_trailing", ch: "LF", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x0a],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p07_in_quotes", ch: "LF", literal: &[0x28, 0x22, 0x61, 0x0a, 0x62, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=610a62 f2=62 out=2822610a62222c6229" }, // C: OK f1=610a62 f2=62 out=2822610a62222c6229
    InCase { name: "p08_after_backslash", ch: "LF", literal: &[0x28, 0x61, 0x5c, 0x0a, 0x62, 0x2c, 0x62, 0x29],
        expect: "OK f1=610a62 f2=62 out=2822610a62222c6229" }, // C: OK f1=610a62 f2=62 out=2822610a62222c6229
    InCase { name: "p09_lone_field", ch: "LF", literal: &[0x28, 0x0a, 0x2c, 0x62, 0x29],
        expect: "OK f1=0a f2=62 out=28220a222c6229" }, // C: OK f1=0a f2=62 out=28220a222c6229
    InCase { name: "p10_only_ws", ch: "LF", literal: &[0x0a],
        expect: "ERR" }, // C: ERR malformed record literal: "
    InCase { name: "p11_leading_twice", ch: "LF", literal: &[0x0a, 0x0a, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p12_lead_and_trail", ch: "LF", literal: &[0x0a, 0x28, 0x61, 0x2c, 0x62, 0x29, 0x0a],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p13_ws_before_lparen_after_ws", ch: "LF", literal: &[0x0a, 0x20, 0x0a, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p14_quoted_only_ws", ch: "LF", literal: &[0x28, 0x22, 0x0a, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=0a f2=62 out=28220a222c6229" }, // C: OK f1=0a f2=62 out=28220a222c6229
    InCase { name: "p15_empty_field", ch: "LF", literal: &[0x28, 0x2c, 0x62, 0x29],
        expect: "OK f1=<NULL> f2=62 out=282c6229" }, // C: OK f1=<NULL> f2=62 out=282c6229
    InCase { name: "p16_trailing_then_junk", ch: "LF", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x0a, 0x78],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)
    InCase { name: "p01_leading", ch: "VT", literal: &[0x0b, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p02_after_lparen", ch: "VT", literal: &[0x28, 0x0b, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=0b61 f2=62 out=28220b61222c6229" }, // C: OK f1=0b61 f2=62 out=28220b61222c6229
    InCase { name: "p03_before_comma", ch: "VT", literal: &[0x28, 0x61, 0x0b, 0x2c, 0x62, 0x29],
        expect: "OK f1=610b f2=62 out=2822610b222c6229" }, // C: OK f1=610b f2=62 out=2822610b222c6229
    InCase { name: "p04_after_comma", ch: "VT", literal: &[0x28, 0x61, 0x2c, 0x0b, 0x62, 0x29],
        expect: "OK f1=61 f2=0b62 out=28612c220b622229" }, // C: OK f1=61 f2=0b62 out=28612c220b622229
    InCase { name: "p05_before_rparen", ch: "VT", literal: &[0x28, 0x61, 0x2c, 0x62, 0x0b, 0x29],
        expect: "OK f1=61 f2=620b out=28612c22620b2229" }, // C: OK f1=61 f2=620b out=28612c22620b2229
    InCase { name: "p06_trailing", ch: "VT", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x0b],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p07_in_quotes", ch: "VT", literal: &[0x28, 0x22, 0x61, 0x0b, 0x62, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=610b62 f2=62 out=2822610b62222c6229" }, // C: OK f1=610b62 f2=62 out=2822610b62222c6229
    InCase { name: "p08_after_backslash", ch: "VT", literal: &[0x28, 0x61, 0x5c, 0x0b, 0x62, 0x2c, 0x62, 0x29],
        expect: "OK f1=610b62 f2=62 out=2822610b62222c6229" }, // C: OK f1=610b62 f2=62 out=2822610b62222c6229
    InCase { name: "p09_lone_field", ch: "VT", literal: &[0x28, 0x0b, 0x2c, 0x62, 0x29],
        expect: "OK f1=0b f2=62 out=28220b222c6229" }, // C: OK f1=0b f2=62 out=28220b222c6229
    InCase { name: "p10_only_ws", ch: "VT", literal: &[0x0b],
        expect: "ERR" }, // C: ERR malformed record literal: ""
    InCase { name: "p11_leading_twice", ch: "VT", literal: &[0x0b, 0x0b, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p12_lead_and_trail", ch: "VT", literal: &[0x0b, 0x28, 0x61, 0x2c, 0x62, 0x29, 0x0b],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p13_ws_before_lparen_after_ws", ch: "VT", literal: &[0x0b, 0x20, 0x0b, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p14_quoted_only_ws", ch: "VT", literal: &[0x28, 0x22, 0x0b, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=0b f2=62 out=28220b222c6229" }, // C: OK f1=0b f2=62 out=28220b222c6229
    InCase { name: "p15_empty_field", ch: "VT", literal: &[0x28, 0x2c, 0x62, 0x29],
        expect: "OK f1=<NULL> f2=62 out=282c6229" }, // C: OK f1=<NULL> f2=62 out=282c6229
    InCase { name: "p16_trailing_then_junk", ch: "VT", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x0b, 0x78],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)x"
    InCase { name: "p01_leading", ch: "FF", literal: &[0x0c, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p02_after_lparen", ch: "FF", literal: &[0x28, 0x0c, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=0c61 f2=62 out=28220c61222c6229" }, // C: OK f1=0c61 f2=62 out=28220c61222c6229
    InCase { name: "p03_before_comma", ch: "FF", literal: &[0x28, 0x61, 0x0c, 0x2c, 0x62, 0x29],
        expect: "OK f1=610c f2=62 out=2822610c222c6229" }, // C: OK f1=610c f2=62 out=2822610c222c6229
    InCase { name: "p04_after_comma", ch: "FF", literal: &[0x28, 0x61, 0x2c, 0x0c, 0x62, 0x29],
        expect: "OK f1=61 f2=0c62 out=28612c220c622229" }, // C: OK f1=61 f2=0c62 out=28612c220c622229
    InCase { name: "p05_before_rparen", ch: "FF", literal: &[0x28, 0x61, 0x2c, 0x62, 0x0c, 0x29],
        expect: "OK f1=61 f2=620c out=28612c22620c2229" }, // C: OK f1=61 f2=620c out=28612c22620c2229
    InCase { name: "p06_trailing", ch: "FF", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x0c],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p07_in_quotes", ch: "FF", literal: &[0x28, 0x22, 0x61, 0x0c, 0x62, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=610c62 f2=62 out=2822610c62222c6229" }, // C: OK f1=610c62 f2=62 out=2822610c62222c6229
    InCase { name: "p08_after_backslash", ch: "FF", literal: &[0x28, 0x61, 0x5c, 0x0c, 0x62, 0x2c, 0x62, 0x29],
        expect: "OK f1=610c62 f2=62 out=2822610c62222c6229" }, // C: OK f1=610c62 f2=62 out=2822610c62222c6229
    InCase { name: "p09_lone_field", ch: "FF", literal: &[0x28, 0x0c, 0x2c, 0x62, 0x29],
        expect: "OK f1=0c f2=62 out=28220c222c6229" }, // C: OK f1=0c f2=62 out=28220c222c6229
    InCase { name: "p10_only_ws", ch: "FF", literal: &[0x0c],
        expect: "ERR" }, // C: ERR malformed record literal: ""
    InCase { name: "p11_leading_twice", ch: "FF", literal: &[0x0c, 0x0c, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p12_lead_and_trail", ch: "FF", literal: &[0x0c, 0x28, 0x61, 0x2c, 0x62, 0x29, 0x0c],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p13_ws_before_lparen_after_ws", ch: "FF", literal: &[0x0c, 0x20, 0x0c, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p14_quoted_only_ws", ch: "FF", literal: &[0x28, 0x22, 0x0c, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=0c f2=62 out=28220c222c6229" }, // C: OK f1=0c f2=62 out=28220c222c6229
    InCase { name: "p15_empty_field", ch: "FF", literal: &[0x28, 0x2c, 0x62, 0x29],
        expect: "OK f1=<NULL> f2=62 out=282c6229" }, // C: OK f1=<NULL> f2=62 out=282c6229
    InCase { name: "p16_trailing_then_junk", ch: "FF", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x0c, 0x78],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)x"
    InCase { name: "p01_leading", ch: "CR", literal: &[0x0d, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p02_after_lparen", ch: "CR", literal: &[0x28, 0x0d, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=0d61 f2=62 out=28220d61222c6229" }, // C: OK f1=0d61 f2=62 out=28220d61222c6229
    InCase { name: "p03_before_comma", ch: "CR", literal: &[0x28, 0x61, 0x0d, 0x2c, 0x62, 0x29],
        expect: "OK f1=610d f2=62 out=2822610d222c6229" }, // C: OK f1=610d f2=62 out=2822610d222c6229
    InCase { name: "p04_after_comma", ch: "CR", literal: &[0x28, 0x61, 0x2c, 0x0d, 0x62, 0x29],
        expect: "OK f1=61 f2=0d62 out=28612c220d622229" }, // C: OK f1=61 f2=0d62 out=28612c220d622229
    InCase { name: "p05_before_rparen", ch: "CR", literal: &[0x28, 0x61, 0x2c, 0x62, 0x0d, 0x29],
        expect: "OK f1=61 f2=620d out=28612c22620d2229" }, // C: OK f1=61 f2=620d out=28612c22620d2229
    InCase { name: "p06_trailing", ch: "CR", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x0d],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p07_in_quotes", ch: "CR", literal: &[0x28, 0x22, 0x61, 0x0d, 0x62, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=610d62 f2=62 out=2822610d62222c6229" }, // C: OK f1=610d62 f2=62 out=2822610d62222c6229
    InCase { name: "p08_after_backslash", ch: "CR", literal: &[0x28, 0x61, 0x5c, 0x0d, 0x62, 0x2c, 0x62, 0x29],
        expect: "OK f1=610d62 f2=62 out=2822610d62222c6229" }, // C: OK f1=610d62 f2=62 out=2822610d62222c6229
    InCase { name: "p09_lone_field", ch: "CR", literal: &[0x28, 0x0d, 0x2c, 0x62, 0x29],
        expect: "OK f1=0d f2=62 out=28220d222c6229" }, // C: OK f1=0d f2=62 out=28220d222c6229
    InCase { name: "p10_only_ws", ch: "CR", literal: &[0x0d],
        expect: "ERR" }, // C: ERR malformed record literal: "\r"
    InCase { name: "p11_leading_twice", ch: "CR", literal: &[0x0d, 0x0d, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p12_lead_and_trail", ch: "CR", literal: &[0x0d, 0x28, 0x61, 0x2c, 0x62, 0x29, 0x0d],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p13_ws_before_lparen_after_ws", ch: "CR", literal: &[0x0d, 0x20, 0x0d, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=61 f2=62 out=28612c6229" }, // C: OK f1=61 f2=62 out=28612c6229
    InCase { name: "p14_quoted_only_ws", ch: "CR", literal: &[0x28, 0x22, 0x0d, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=0d f2=62 out=28220d222c6229" }, // C: OK f1=0d f2=62 out=28220d222c6229
    InCase { name: "p15_empty_field", ch: "CR", literal: &[0x28, 0x2c, 0x62, 0x29],
        expect: "OK f1=<NULL> f2=62 out=282c6229" }, // C: OK f1=<NULL> f2=62 out=282c6229
    InCase { name: "p16_trailing_then_junk", ch: "CR", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0x0d, 0x78],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)\rx"
    InCase { name: "p01_leading", ch: "NBSP", literal: &[0xc2, 0xa0, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "ERR" }, // C: ERR malformed record literal: "Â (a,b)"
    InCase { name: "p02_after_lparen", ch: "NBSP", literal: &[0x28, 0xc2, 0xa0, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=c2a061 f2=62 out=28c2a0612c6229" }, // C: OK f1=c2a061 f2=62 out=28c2a0612c6229
    InCase { name: "p03_before_comma", ch: "NBSP", literal: &[0x28, 0x61, 0xc2, 0xa0, 0x2c, 0x62, 0x29],
        expect: "OK f1=61c2a0 f2=62 out=2861c2a02c6229" }, // C: OK f1=61c2a0 f2=62 out=2861c2a02c6229
    InCase { name: "p04_after_comma", ch: "NBSP", literal: &[0x28, 0x61, 0x2c, 0xc2, 0xa0, 0x62, 0x29],
        expect: "OK f1=61 f2=c2a062 out=28612cc2a06229" }, // C: OK f1=61 f2=c2a062 out=28612cc2a06229
    InCase { name: "p05_before_rparen", ch: "NBSP", literal: &[0x28, 0x61, 0x2c, 0x62, 0xc2, 0xa0, 0x29],
        expect: "OK f1=61 f2=62c2a0 out=28612c62c2a029" }, // C: OK f1=61 f2=62c2a0 out=28612c62c2a029
    InCase { name: "p06_trailing", ch: "NBSP", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0xc2, 0xa0],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)Â "
    InCase { name: "p07_in_quotes", ch: "NBSP", literal: &[0x28, 0x22, 0x61, 0xc2, 0xa0, 0x62, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=61c2a062 f2=62 out=2861c2a0622c6229" }, // C: OK f1=61c2a062 f2=62 out=2861c2a0622c6229
    InCase { name: "p08_after_backslash", ch: "NBSP", literal: &[0x28, 0x61, 0x5c, 0xc2, 0xa0, 0x62, 0x2c, 0x62, 0x29],
        expect: "OK f1=61c2a062 f2=62 out=2861c2a0622c6229" }, // C: OK f1=61c2a062 f2=62 out=2861c2a0622c6229
    InCase { name: "p09_lone_field", ch: "NBSP", literal: &[0x28, 0xc2, 0xa0, 0x2c, 0x62, 0x29],
        expect: "OK f1=c2a0 f2=62 out=28c2a02c6229" }, // C: OK f1=c2a0 f2=62 out=28c2a02c6229
    InCase { name: "p10_only_ws", ch: "NBSP", literal: &[0xc2, 0xa0],
        expect: "ERR" }, // C: ERR malformed record literal: "Â "
    InCase { name: "p11_leading_twice", ch: "NBSP", literal: &[0xc2, 0xa0, 0xc2, 0xa0, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "ERR" }, // C: ERR malformed record literal: "Â Â (a,b)"
    InCase { name: "p12_lead_and_trail", ch: "NBSP", literal: &[0xc2, 0xa0, 0x28, 0x61, 0x2c, 0x62, 0x29, 0xc2, 0xa0],
        expect: "ERR" }, // C: ERR malformed record literal: "Â (a,b)Â "
    InCase { name: "p13_ws_before_lparen_after_ws", ch: "NBSP", literal: &[0xc2, 0xa0, 0x20, 0xc2, 0xa0, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "ERR" }, // C: ERR malformed record literal: "Â  Â (a,b)"
    InCase { name: "p14_quoted_only_ws", ch: "NBSP", literal: &[0x28, 0x22, 0xc2, 0xa0, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=c2a0 f2=62 out=28c2a02c6229" }, // C: OK f1=c2a0 f2=62 out=28c2a02c6229
    InCase { name: "p15_empty_field", ch: "NBSP", literal: &[0x28, 0x2c, 0x62, 0x29],
        expect: "OK f1=<NULL> f2=62 out=282c6229" }, // C: OK f1=<NULL> f2=62 out=282c6229
    InCase { name: "p16_trailing_then_junk", ch: "NBSP", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0xc2, 0xa0, 0x78],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)Â x"
    InCase { name: "p01_leading", ch: "NEL", literal: &[0xc2, 0x85, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "ERR" }, // C: ERR malformed record literal: "Â(a,b)"
    InCase { name: "p02_after_lparen", ch: "NEL", literal: &[0x28, 0xc2, 0x85, 0x61, 0x2c, 0x62, 0x29],
        expect: "OK f1=c28561 f2=62 out=28c285612c6229" }, // C: OK f1=c28561 f2=62 out=28c285612c6229
    InCase { name: "p03_before_comma", ch: "NEL", literal: &[0x28, 0x61, 0xc2, 0x85, 0x2c, 0x62, 0x29],
        expect: "OK f1=61c285 f2=62 out=2861c2852c6229" }, // C: OK f1=61c285 f2=62 out=2861c2852c6229
    InCase { name: "p04_after_comma", ch: "NEL", literal: &[0x28, 0x61, 0x2c, 0xc2, 0x85, 0x62, 0x29],
        expect: "OK f1=61 f2=c28562 out=28612cc2856229" }, // C: OK f1=61 f2=c28562 out=28612cc2856229
    InCase { name: "p05_before_rparen", ch: "NEL", literal: &[0x28, 0x61, 0x2c, 0x62, 0xc2, 0x85, 0x29],
        expect: "OK f1=61 f2=62c285 out=28612c62c28529" }, // C: OK f1=61 f2=62c285 out=28612c62c28529
    InCase { name: "p06_trailing", ch: "NEL", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0xc2, 0x85],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)Â"
    InCase { name: "p07_in_quotes", ch: "NEL", literal: &[0x28, 0x22, 0x61, 0xc2, 0x85, 0x62, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=61c28562 f2=62 out=2861c285622c6229" }, // C: OK f1=61c28562 f2=62 out=2861c285622c6229
    InCase { name: "p08_after_backslash", ch: "NEL", literal: &[0x28, 0x61, 0x5c, 0xc2, 0x85, 0x62, 0x2c, 0x62, 0x29],
        expect: "OK f1=61c28562 f2=62 out=2861c285622c6229" }, // C: OK f1=61c28562 f2=62 out=2861c285622c6229
    InCase { name: "p09_lone_field", ch: "NEL", literal: &[0x28, 0xc2, 0x85, 0x2c, 0x62, 0x29],
        expect: "OK f1=c285 f2=62 out=28c2852c6229" }, // C: OK f1=c285 f2=62 out=28c2852c6229
    InCase { name: "p10_only_ws", ch: "NEL", literal: &[0xc2, 0x85],
        expect: "ERR" }, // C: ERR malformed record literal: "Â"
    InCase { name: "p11_leading_twice", ch: "NEL", literal: &[0xc2, 0x85, 0xc2, 0x85, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "ERR" }, // C: ERR malformed record literal: "ÂÂ(a,b)"
    InCase { name: "p12_lead_and_trail", ch: "NEL", literal: &[0xc2, 0x85, 0x28, 0x61, 0x2c, 0x62, 0x29, 0xc2, 0x85],
        expect: "ERR" }, // C: ERR malformed record literal: "Â(a,b)Â"
    InCase { name: "p13_ws_before_lparen_after_ws", ch: "NEL", literal: &[0xc2, 0x85, 0x20, 0xc2, 0x85, 0x28, 0x61, 0x2c, 0x62, 0x29],
        expect: "ERR" }, // C: ERR malformed record literal: "Â Â(a,b)"
    InCase { name: "p14_quoted_only_ws", ch: "NEL", literal: &[0x28, 0x22, 0xc2, 0x85, 0x22, 0x2c, 0x62, 0x29],
        expect: "OK f1=c285 f2=62 out=28c2852c6229" }, // C: OK f1=c285 f2=62 out=28c2852c6229
    InCase { name: "p15_empty_field", ch: "NEL", literal: &[0x28, 0x2c, 0x62, 0x29],
        expect: "OK f1=<NULL> f2=62 out=282c6229" }, // C: OK f1=<NULL> f2=62 out=282c6229
    InCase { name: "p16_trailing_then_junk", ch: "NEL", literal: &[0x28, 0x61, 0x2c, 0x62, 0x29, 0xc2, 0x85, 0x78],
        expect: "ERR" }, // C: ERR malformed record literal: "(a,b)Âx"
];

#[rustfmt::skip]
pub(crate) const OUT_CASES: &[OutCase] = &[
    OutCase { name: "o01_ws_only", ch: "SP", value: &[0x20],
        expect: "out=282220222c7a29 rt=EQ" }, // C: out=282220222c7a29 rt=EQ
    OutCase { name: "o02_ws_prefix", ch: "SP", value: &[0x20, 0x61],
        expect: "out=28222061222c7a29 rt=EQ" }, // C: out=28222061222c7a29 rt=EQ
    OutCase { name: "o03_ws_middle", ch: "SP", value: &[0x61, 0x20, 0x62],
        expect: "out=2822612062222c7a29 rt=EQ" }, // C: out=2822612062222c7a29 rt=EQ
    OutCase { name: "o04_ws_suffix", ch: "SP", value: &[0x61, 0x20],
        expect: "out=28226120222c7a29 rt=EQ" }, // C: out=28226120222c7a29 rt=EQ
    OutCase { name: "o01_ws_only", ch: "HT", value: &[0x09],
        expect: "out=282209222c7a29 rt=EQ" }, // C: out=282209222c7a29 rt=EQ
    OutCase { name: "o02_ws_prefix", ch: "HT", value: &[0x09, 0x61],
        expect: "out=28220961222c7a29 rt=EQ" }, // C: out=28220961222c7a29 rt=EQ
    OutCase { name: "o03_ws_middle", ch: "HT", value: &[0x61, 0x09, 0x62],
        expect: "out=2822610962222c7a29 rt=EQ" }, // C: out=2822610962222c7a29 rt=EQ
    OutCase { name: "o04_ws_suffix", ch: "HT", value: &[0x61, 0x09],
        expect: "out=28226109222c7a29 rt=EQ" }, // C: out=28226109222c7a29 rt=EQ
    OutCase { name: "o01_ws_only", ch: "LF", value: &[0x0a],
        expect: "out=28220a222c7a29 rt=EQ" }, // C: out=28220a222c7a29 rt=EQ
    OutCase { name: "o02_ws_prefix", ch: "LF", value: &[0x0a, 0x61],
        expect: "out=28220a61222c7a29 rt=EQ" }, // C: out=28220a61222c7a29 rt=EQ
    OutCase { name: "o03_ws_middle", ch: "LF", value: &[0x61, 0x0a, 0x62],
        expect: "out=2822610a62222c7a29 rt=EQ" }, // C: out=2822610a62222c7a29 rt=EQ
    OutCase { name: "o04_ws_suffix", ch: "LF", value: &[0x61, 0x0a],
        expect: "out=2822610a222c7a29 rt=EQ" }, // C: out=2822610a222c7a29 rt=EQ
    OutCase { name: "o01_ws_only", ch: "VT", value: &[0x0b],
        expect: "out=28220b222c7a29 rt=EQ" }, // C: out=28220b222c7a29 rt=EQ
    OutCase { name: "o02_ws_prefix", ch: "VT", value: &[0x0b, 0x61],
        expect: "out=28220b61222c7a29 rt=EQ" }, // C: out=28220b61222c7a29 rt=EQ
    OutCase { name: "o03_ws_middle", ch: "VT", value: &[0x61, 0x0b, 0x62],
        expect: "out=2822610b62222c7a29 rt=EQ" }, // C: out=2822610b62222c7a29 rt=EQ
    OutCase { name: "o04_ws_suffix", ch: "VT", value: &[0x61, 0x0b],
        expect: "out=2822610b222c7a29 rt=EQ" }, // C: out=2822610b222c7a29 rt=EQ
    OutCase { name: "o01_ws_only", ch: "FF", value: &[0x0c],
        expect: "out=28220c222c7a29 rt=EQ" }, // C: out=28220c222c7a29 rt=EQ
    OutCase { name: "o02_ws_prefix", ch: "FF", value: &[0x0c, 0x61],
        expect: "out=28220c61222c7a29 rt=EQ" }, // C: out=28220c61222c7a29 rt=EQ
    OutCase { name: "o03_ws_middle", ch: "FF", value: &[0x61, 0x0c, 0x62],
        expect: "out=2822610c62222c7a29 rt=EQ" }, // C: out=2822610c62222c7a29 rt=EQ
    OutCase { name: "o04_ws_suffix", ch: "FF", value: &[0x61, 0x0c],
        expect: "out=2822610c222c7a29 rt=EQ" }, // C: out=2822610c222c7a29 rt=EQ
    OutCase { name: "o01_ws_only", ch: "CR", value: &[0x0d],
        expect: "out=28220d222c7a29 rt=EQ" }, // C: out=28220d222c7a29 rt=EQ
    OutCase { name: "o02_ws_prefix", ch: "CR", value: &[0x0d, 0x61],
        expect: "out=28220d61222c7a29 rt=EQ" }, // C: out=28220d61222c7a29 rt=EQ
    OutCase { name: "o03_ws_middle", ch: "CR", value: &[0x61, 0x0d, 0x62],
        expect: "out=2822610d62222c7a29 rt=EQ" }, // C: out=2822610d62222c7a29 rt=EQ
    OutCase { name: "o04_ws_suffix", ch: "CR", value: &[0x61, 0x0d],
        expect: "out=2822610d222c7a29 rt=EQ" }, // C: out=2822610d222c7a29 rt=EQ
    OutCase { name: "o01_ws_only", ch: "NBSP", value: &[0xc2, 0xa0],
        expect: "out=28c2a02c7a29 rt=EQ" }, // C: out=28c2a02c7a29 rt=EQ
    OutCase { name: "o02_ws_prefix", ch: "NBSP", value: &[0xc2, 0xa0, 0x61],
        expect: "out=28c2a0612c7a29 rt=EQ" }, // C: out=28c2a0612c7a29 rt=EQ
    OutCase { name: "o03_ws_middle", ch: "NBSP", value: &[0x61, 0xc2, 0xa0, 0x62],
        expect: "out=2861c2a0622c7a29 rt=EQ" }, // C: out=2861c2a0622c7a29 rt=EQ
    OutCase { name: "o04_ws_suffix", ch: "NBSP", value: &[0x61, 0xc2, 0xa0],
        expect: "out=2861c2a02c7a29 rt=EQ" }, // C: out=2861c2a02c7a29 rt=EQ
    OutCase { name: "o01_ws_only", ch: "NEL", value: &[0xc2, 0x85],
        expect: "out=28c2852c7a29 rt=EQ" }, // C: out=28c2852c7a29 rt=EQ
    OutCase { name: "o02_ws_prefix", ch: "NEL", value: &[0xc2, 0x85, 0x61],
        expect: "out=28c285612c7a29 rt=EQ" }, // C: out=28c285612c7a29 rt=EQ
    OutCase { name: "o03_ws_middle", ch: "NEL", value: &[0x61, 0xc2, 0x85, 0x62],
        expect: "out=2861c285622c7a29 rt=EQ" }, // C: out=2861c285622c7a29 rt=EQ
    OutCase { name: "o04_ws_suffix", ch: "NEL", value: &[0x61, 0xc2, 0x85],
        expect: "out=2861c2852c7a29 rt=EQ" }, // C: out=2861c2852c7a29 rt=EQ
];
