[package]
name = "pg_operator"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "pg_operator"
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../_support/mcx" }
datum = { path = "../../../_support/types/datum" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_rel = { path = "../../../_support/types/rel" }
types_tuple = { path = "../../../_support/types/types_tuple" }
cache_syscache = { path = "../../utils/cache/cache_syscache" }
syscache_seams = { path = "../../utils/cache/syscache_seams" }
lsyscache = { path = "../../utils/cache/lsyscache" }
heaptuple = { path = "../../access/common/heaptuple" }
table = { path = "../../access/table/table" }
catalog = { path = "../catalog" }
catalog_indexing = { path = "../catalog_indexing" }
catalog_namespace = { path = "../catalog_namespace" }
catalog_dependency = { path = "../catalog_dependency" }
pg_shdepend = { path = "../pg_shdepend" }
pg_depend = { path = "../pg_depend" }
parse_oper = { path = "../../parser/parse_oper" }
commands_define = { path = "../../commands/commands_define" }
aclchk = { path = "../aclchk" }
adt_acl = { path = "../../utils/adt/acl" }
miscinit = { path = "../../utils/init/miscinit" }
xact = { path = "../../access/transam/xact" }
