[package]
name = "autovacuum"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "autovacuum"
path = "src/lib.rs"

[dependencies]
aio_seams = { path = "../../storage/aio/aio_seams" }
autovacuum_seams = { path = "../autovacuum_seams" }
bufmgr = { path = "../../storage/buffer/bufmgr" }
dynahash = { path = "../../utils/hash/dynahash" }
elog = { path = "../../utils/error/elog" }
fd = { path = "../../storage/file/fd" }
guc = { path = "../../utils/misc/guc" }
guc_file_seams = { path = "../../utils/misc/guc_file_seams" }
guc_tables = { path = "../../utils/misc/guc_tables" }
init_small = { path = "../../utils/init/init_small" }
interrupt = { path = "../interrupt" }
ipc = { path = "../../storage/ipc/ipc" }
latch = { path = "../../storage/ipc/latch" }
libc = "0.2"
libpq_pqsignal = { path = "../../libpq/libpq_pqsignal" }
lmgr_proc = { path = "../../storage/lmgr/lmgr_proc" }
lwlock = { path = "../../storage/lmgr/lwlock" }
mcx = { path = "../../../_support/mcx" }
mcxt_seams = { path = "../../utils/mmgr/mcxt_seams" }
miscinit = { path = "../../utils/init/miscinit" }
postgres = { path = "../../tcop/postgres" }
postinit = { path = "../../utils/init/postinit" }
procsignal = { path = "../../storage/ipc/procsignal" }
resowner = { path = "../../utils/resowner/resowner" }
sinval = { path = "../../storage/ipc/sinval" }
smgr = { path = "../../storage/smgr/smgr" }
timeout_seams = { path = "../../utils/misc/timeout_seams" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_guc = { path = "../../../_support/types/types_guc" }
types_startup = { path = "../../../_support/types/types_startup" }
types_storage = { path = "../../../_support/types/types_storage" }
varsup = { path = "../../access/transam/varsup" }
waitevent_seams = { path = "../../utils/activity/waitevent_seams" }
xact = { path = "../../access/transam/xact" }
adt_timestamp = { path = "../../utils/adt/adt_timestamp" }
pgstat = { path = "../../utils/activity/pgstat" }
pmsignal = { path = "../../storage/ipc/pmsignal" }
multixact = { path = "../../access/transam/multixact" }
table = { path = "../../access/table/table" }
genam = { path = "../../access/index/genam" }
datum = { path = "../../../_support/types/datum" }
types_tuple = { path = "../../../_support/types/types_tuple" }
types_rel = { path = "../../../_support/types/rel" }
types_scan = { path = "../../../_support/types/types_scan" }
types_nodes = { path = "../../../_support/types/nodes" }
tableam_vocab = { path = "../../access/table/tableam_vocab" }
commands_vacuum = { path = "../../commands/vacuum" }
catalog_namespace = { path = "../../catalog/catalog_namespace" }
pg_database = { path = "../../catalog/pg_database" }
reloptions = { path = "../../access/common/reloptions" }
dependency_seams = { path = "../../catalog/dependency_seams" }
dbcommands_seams = { path = "../../commands/dbcommands_seams" }
syscache_seams = { path = "../../utils/cache/syscache_seams" }
backend_status_seams = { path = "../../utils/activity/backend_status_seams" }
bufmgr_seams = { path = "../../storage/buffer/bufmgr_seams" }
snapmgr = { path = "../../utils/time/snapmgr" }
fmgr_seams = { path = "../../utils/fmgr/fmgr_seams" }
lmgr = { path = "../../storage/lmgr/lmgr" }
postgres_seams = { path = "../../tcop/postgres_seams" }
