[package]
name = "brin_validate"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_brin = { path = "../../../../_support/types/types_brin" }
index_amvalidate = { path = "../../index/index_amvalidate" }
lsyscache = { path = "../../../utils/cache/lsyscache" }
mcx = { path = "../../../../_support/mcx" }
elog = { path = "../../../utils/error/elog" }
syscache_seams = { path = "../../../utils/cache/syscache_seams" }
adt_regproc = { path = "../../../utils/adt/regproc" }
format_type = { path = "../../../utils/adt/format_type" }
