[package]
name = "lanefold"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "lanefold"
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../_support/mcx" }
datum = { path = "../../../_support/types/datum" }
types_core = { path = "../../../_support/types/types_core" }
types_nodes = { path = "../../../_support/types/nodes" }
types_tuple = { path = "../../../_support/types/types_tuple" }
execexpr = { path = "../execexpr" }
exectuples = { path = "../exectuples" }
