use crate::backend::catalog::catalog::column_desc;
use crate::backend::executor::RelationDesc;
use crate::backend::parser::{SqlType, SqlTypeKind};
use crate::include::catalog::{
    BIT_CMP_EQ_PROC_OID, BIT_CMP_GE_PROC_OID, BIT_CMP_GT_PROC_OID, BIT_CMP_LE_PROC_OID,
    BIT_CMP_LT_PROC_OID, BIT_CMP_NE_PROC_OID, BIT_TYPE_OID, BOOL_CMP_EQ_PROC_OID,
    BOOL_CMP_GE_PROC_OID, BOOL_CMP_GT_PROC_OID, BOOL_CMP_LE_PROC_OID, BOOL_CMP_LT_PROC_OID,
    BOOL_CMP_NE_PROC_OID, BOOL_TYPE_OID, BOOTSTRAP_SUPERUSER_OID, BYTEA_CMP_EQ_PROC_OID,
    BYTEA_CMP_GE_PROC_OID, BYTEA_CMP_GT_PROC_OID, BYTEA_CMP_LE_PROC_OID, BYTEA_CMP_LT_PROC_OID,
    BYTEA_CMP_NE_PROC_OID, BYTEA_TYPE_OID, INT4_CMP_EQ_PROC_OID, INT4_CMP_GE_PROC_OID,
    INT4_CMP_GT_PROC_OID, INT4_CMP_LE_PROC_OID, INT4_CMP_LT_PROC_OID, INT4_CMP_NE_PROC_OID,
    INT4_TYPE_OID, JSONB_CMP_EQ_PROC_OID, JSONB_CMP_GE_PROC_OID, JSONB_CMP_GT_PROC_OID,
    JSONB_CMP_LE_PROC_OID, JSONB_CMP_LT_PROC_OID, JSONB_CMP_NE_PROC_OID, JSONB_TYPE_OID,
    PG_CATALOG_NAMESPACE_OID, TEXT_CMP_EQ_PROC_OID, TEXT_CMP_GE_PROC_OID, TEXT_CMP_GT_PROC_OID,
    TEXT_CMP_LE_PROC_OID, TEXT_CMP_LT_PROC_OID, TEXT_CMP_NE_PROC_OID, TEXT_STARTS_WITH_PROC_OID,
    TEXT_TYPE_OID, VARBIT_CMP_EQ_PROC_OID, VARBIT_CMP_GE_PROC_OID, VARBIT_CMP_GT_PROC_OID,
    VARBIT_CMP_LE_PROC_OID, VARBIT_CMP_LT_PROC_OID, VARBIT_CMP_NE_PROC_OID, VARBIT_TYPE_OID,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PgOperatorRow {
    pub oid: u32,
    pub oprname: String,
    pub oprnamespace: u32,
    pub oprowner: u32,
    pub oprkind: char,
    pub oprcanmerge: bool,
    pub oprcanhash: bool,
    pub oprleft: u32,
    pub oprright: u32,
    pub oprresult: u32,
    pub oprcom: u32,
    pub oprnegate: u32,
    pub oprcode: u32,
    pub oprrest: u32,
    pub oprjoin: u32,
}

pub fn pg_operator_desc() -> RelationDesc {
    RelationDesc {
        columns: vec![
            column_desc("oid", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprname", SqlType::new(SqlTypeKind::Text), false),
            column_desc("oprnamespace", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprowner", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprkind", SqlType::new(SqlTypeKind::InternalChar), false),
            column_desc("oprcanmerge", SqlType::new(SqlTypeKind::Bool), false),
            column_desc("oprcanhash", SqlType::new(SqlTypeKind::Bool), false),
            column_desc("oprleft", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprright", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprresult", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprcom", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprnegate", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprcode", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprrest", SqlType::new(SqlTypeKind::Oid), false),
            column_desc("oprjoin", SqlType::new(SqlTypeKind::Oid), false),
        ],
    }
}

pub fn bootstrap_pg_operator_rows() -> [PgOperatorRow; 43] {
    [
        operator_row(
            58,
            "<",
            BOOL_TYPE_OID,
            BOOL_TYPE_OID,
            59,
            1695,
            BOOL_CMP_LT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            59,
            ">",
            BOOL_TYPE_OID,
            BOOL_TYPE_OID,
            58,
            1694,
            BOOL_CMP_GT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            85,
            "<>",
            BOOL_TYPE_OID,
            BOOL_TYPE_OID,
            85,
            91,
            BOOL_CMP_NE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            91,
            "=",
            BOOL_TYPE_OID,
            BOOL_TYPE_OID,
            91,
            85,
            BOOL_CMP_EQ_PROC_OID,
            true,
            true,
        ),
        operator_row(
            96,
            "=",
            INT4_TYPE_OID,
            INT4_TYPE_OID,
            96,
            518,
            INT4_CMP_EQ_PROC_OID,
            true,
            true,
        ),
        operator_row(
            97,
            "<",
            INT4_TYPE_OID,
            INT4_TYPE_OID,
            521,
            525,
            INT4_CMP_LT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            98,
            "=",
            TEXT_TYPE_OID,
            TEXT_TYPE_OID,
            98,
            531,
            TEXT_CMP_EQ_PROC_OID,
            true,
            true,
        ),
        operator_row(
            518,
            "<>",
            INT4_TYPE_OID,
            INT4_TYPE_OID,
            518,
            96,
            INT4_CMP_NE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            521,
            ">",
            INT4_TYPE_OID,
            INT4_TYPE_OID,
            97,
            523,
            INT4_CMP_GT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            523,
            "<=",
            INT4_TYPE_OID,
            INT4_TYPE_OID,
            525,
            521,
            INT4_CMP_LE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            525,
            ">=",
            INT4_TYPE_OID,
            INT4_TYPE_OID,
            523,
            97,
            INT4_CMP_GE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            531,
            "<>",
            TEXT_TYPE_OID,
            TEXT_TYPE_OID,
            531,
            98,
            TEXT_CMP_NE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            664,
            "<",
            TEXT_TYPE_OID,
            TEXT_TYPE_OID,
            666,
            667,
            TEXT_CMP_LT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            665,
            "<=",
            TEXT_TYPE_OID,
            TEXT_TYPE_OID,
            667,
            666,
            TEXT_CMP_LE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            666,
            ">",
            TEXT_TYPE_OID,
            TEXT_TYPE_OID,
            664,
            665,
            TEXT_CMP_GT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            667,
            ">=",
            TEXT_TYPE_OID,
            TEXT_TYPE_OID,
            665,
            664,
            TEXT_CMP_GE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1694,
            "<=",
            BOOL_TYPE_OID,
            BOOL_TYPE_OID,
            1695,
            59,
            BOOL_CMP_LE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1695,
            ">=",
            BOOL_TYPE_OID,
            BOOL_TYPE_OID,
            1694,
            58,
            BOOL_CMP_GE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1784,
            "=",
            BIT_TYPE_OID,
            BIT_TYPE_OID,
            1784,
            1785,
            BIT_CMP_EQ_PROC_OID,
            true,
            false,
        ),
        operator_row(
            1785,
            "<>",
            BIT_TYPE_OID,
            BIT_TYPE_OID,
            1785,
            1784,
            BIT_CMP_NE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1786,
            "<",
            BIT_TYPE_OID,
            BIT_TYPE_OID,
            1787,
            1789,
            BIT_CMP_LT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1787,
            ">",
            BIT_TYPE_OID,
            BIT_TYPE_OID,
            1786,
            1788,
            BIT_CMP_GT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1788,
            "<=",
            BIT_TYPE_OID,
            BIT_TYPE_OID,
            1789,
            1787,
            BIT_CMP_LE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1789,
            ">=",
            BIT_TYPE_OID,
            BIT_TYPE_OID,
            1788,
            1786,
            BIT_CMP_GE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1804,
            "=",
            VARBIT_TYPE_OID,
            VARBIT_TYPE_OID,
            1804,
            1805,
            VARBIT_CMP_EQ_PROC_OID,
            true,
            false,
        ),
        operator_row(
            1805,
            "<>",
            VARBIT_TYPE_OID,
            VARBIT_TYPE_OID,
            1805,
            1804,
            VARBIT_CMP_NE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1806,
            "<",
            VARBIT_TYPE_OID,
            VARBIT_TYPE_OID,
            1807,
            1809,
            VARBIT_CMP_LT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1807,
            ">",
            VARBIT_TYPE_OID,
            VARBIT_TYPE_OID,
            1806,
            1808,
            VARBIT_CMP_GT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1808,
            "<=",
            VARBIT_TYPE_OID,
            VARBIT_TYPE_OID,
            1809,
            1807,
            VARBIT_CMP_LE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1809,
            ">=",
            VARBIT_TYPE_OID,
            VARBIT_TYPE_OID,
            1808,
            1806,
            VARBIT_CMP_GE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1955,
            "=",
            BYTEA_TYPE_OID,
            BYTEA_TYPE_OID,
            1955,
            1956,
            BYTEA_CMP_EQ_PROC_OID,
            true,
            true,
        ),
        operator_row(
            1956,
            "<>",
            BYTEA_TYPE_OID,
            BYTEA_TYPE_OID,
            1956,
            1955,
            BYTEA_CMP_NE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1957,
            "<",
            BYTEA_TYPE_OID,
            BYTEA_TYPE_OID,
            1959,
            1960,
            BYTEA_CMP_LT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1958,
            "<=",
            BYTEA_TYPE_OID,
            BYTEA_TYPE_OID,
            1960,
            1959,
            BYTEA_CMP_LE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1959,
            ">",
            BYTEA_TYPE_OID,
            BYTEA_TYPE_OID,
            1957,
            1958,
            BYTEA_CMP_GT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            1960,
            ">=",
            BYTEA_TYPE_OID,
            BYTEA_TYPE_OID,
            1958,
            1957,
            BYTEA_CMP_GE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            3240,
            "=",
            JSONB_TYPE_OID,
            JSONB_TYPE_OID,
            3240,
            3241,
            JSONB_CMP_EQ_PROC_OID,
            true,
            true,
        ),
        operator_row(
            3241,
            "<>",
            JSONB_TYPE_OID,
            JSONB_TYPE_OID,
            3241,
            3240,
            JSONB_CMP_NE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            3242,
            "<",
            JSONB_TYPE_OID,
            JSONB_TYPE_OID,
            3243,
            3245,
            JSONB_CMP_LT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            3243,
            ">",
            JSONB_TYPE_OID,
            JSONB_TYPE_OID,
            3242,
            3244,
            JSONB_CMP_GT_PROC_OID,
            false,
            false,
        ),
        operator_row(
            3244,
            "<=",
            JSONB_TYPE_OID,
            JSONB_TYPE_OID,
            3245,
            3243,
            JSONB_CMP_LE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            3245,
            ">=",
            JSONB_TYPE_OID,
            JSONB_TYPE_OID,
            3244,
            3242,
            JSONB_CMP_GE_PROC_OID,
            false,
            false,
        ),
        operator_row(
            3877,
            "^@",
            TEXT_TYPE_OID,
            TEXT_TYPE_OID,
            0,
            0,
            TEXT_STARTS_WITH_PROC_OID,
            false,
            false,
        ),
    ]
}

fn operator_row(
    oid: u32,
    oprname: &str,
    oprleft: u32,
    oprright: u32,
    oprcom: u32,
    oprnegate: u32,
    oprcode: u32,
    oprcanmerge: bool,
    oprcanhash: bool,
) -> PgOperatorRow {
    PgOperatorRow {
        oid,
        oprname: oprname.into(),
        oprnamespace: PG_CATALOG_NAMESPACE_OID,
        oprowner: BOOTSTRAP_SUPERUSER_OID,
        oprkind: 'b',
        oprcanmerge,
        oprcanhash,
        oprleft,
        oprright,
        oprresult: BOOL_TYPE_OID,
        oprcom,
        oprnegate,
        oprcode,
        // :HACK: estimator functions are not cataloged yet in pgrust, so keep
        // `oprrest` / `oprjoin` as zero until that metadata exists.
        oprrest: 0,
        oprjoin: 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pg_operator_desc_matches_expected_columns() {
        let desc = pg_operator_desc();
        let names: Vec<_> = desc
            .columns
            .iter()
            .map(|column| column.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "oid",
                "oprname",
                "oprnamespace",
                "oprowner",
                "oprkind",
                "oprcanmerge",
                "oprcanhash",
                "oprleft",
                "oprright",
                "oprresult",
                "oprcom",
                "oprnegate",
                "oprcode",
                "oprrest",
                "oprjoin",
            ]
        );
    }
}
