#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SystemCatalogForeignKey {
    pub fk_table_oid: u32,
    pub fk_table_name: &'static str,
    pub pk_table_oid: u32,
    pub pk_table_name: &'static str,
    pub fk_columns: &'static [&'static str],
    pub pk_columns: &'static [&'static str],
    pub is_array: bool,
    pub is_opt: bool,
}

pub const SYSTEM_CATALOG_FOREIGN_KEYS: &[SystemCatalogForeignKey] = &[
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["pronamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["proowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 2612,
        pk_table_name: "pg_language",
        fk_columns: &["prolang"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["provariadic"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["prosupport"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["prorettype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["proargtypes"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["proallargtypes"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1255,
        fk_table_name: "pg_proc",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["protrftypes"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["typnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["typowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["typrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["typsubscript"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["typelem"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["typarray"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["typinput"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["typoutput"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["typreceive"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["typsend"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["typmodin"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["typmodout"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["typanalyze"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["typbasetype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1247,
        fk_table_name: "pg_type",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["typcollation"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1249,
        fk_table_name: "pg_attribute",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["attrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1249,
        fk_table_name: "pg_attribute",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["atttypid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1249,
        fk_table_name: "pg_attribute",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["attcollation"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1259,
        fk_table_name: "pg_class",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["relnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1259,
        fk_table_name: "pg_class",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["reltype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1259,
        fk_table_name: "pg_class",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["reloftype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1259,
        fk_table_name: "pg_class",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["relowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1259,
        fk_table_name: "pg_class",
        pk_table_oid: 2601,
        pk_table_name: "pg_am",
        fk_columns: &["relam"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1259,
        fk_table_name: "pg_class",
        pk_table_oid: 1213,
        pk_table_name: "pg_tablespace",
        fk_columns: &["reltablespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1259,
        fk_table_name: "pg_class",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["reltoastrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1259,
        fk_table_name: "pg_class",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["relrewrite"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2604,
        fk_table_name: "pg_attrdef",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["adrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2604,
        fk_table_name: "pg_attrdef",
        pk_table_oid: 1249,
        pk_table_name: "pg_attribute",
        fk_columns: &["adrelid", "adnum"],
        pk_columns: &["attrelid", "attnum"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["connamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["conrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["contypid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["conindid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 2606,
        pk_table_name: "pg_constraint",
        fk_columns: &["conparentid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["confrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["conpfeqop"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["conppeqop"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["conffeqop"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["conexclop"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 1249,
        pk_table_name: "pg_attribute",
        fk_columns: &["conrelid", "conkey"],
        pk_columns: &["attrelid", "attnum"],
        is_array: true,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2606,
        fk_table_name: "pg_constraint",
        pk_table_oid: 1249,
        pk_table_name: "pg_attribute",
        fk_columns: &["confrelid", "confkey"],
        pk_columns: &["attrelid", "attnum"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2611,
        fk_table_name: "pg_inherits",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["inhrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2611,
        fk_table_name: "pg_inherits",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["inhparent"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2610,
        fk_table_name: "pg_index",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["indexrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2610,
        fk_table_name: "pg_index",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["indrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2610,
        fk_table_name: "pg_index",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["indcollation"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2610,
        fk_table_name: "pg_index",
        pk_table_oid: 2616,
        pk_table_name: "pg_opclass",
        fk_columns: &["indclass"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2610,
        fk_table_name: "pg_index",
        pk_table_oid: 1249,
        pk_table_name: "pg_attribute",
        fk_columns: &["indrelid", "indkey"],
        pk_columns: &["attrelid", "attnum"],
        is_array: true,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["oprnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["oprowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["oprleft"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["oprright"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["oprresult"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["oprcom"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["oprnegate"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["oprcode"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["oprrest"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2617,
        fk_table_name: "pg_operator",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["oprjoin"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2753,
        fk_table_name: "pg_opfamily",
        pk_table_oid: 2601,
        pk_table_name: "pg_am",
        fk_columns: &["opfmethod"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2753,
        fk_table_name: "pg_opfamily",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["opfnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2753,
        fk_table_name: "pg_opfamily",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["opfowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2616,
        fk_table_name: "pg_opclass",
        pk_table_oid: 2601,
        pk_table_name: "pg_am",
        fk_columns: &["opcmethod"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2616,
        fk_table_name: "pg_opclass",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["opcnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2616,
        fk_table_name: "pg_opclass",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["opcowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2616,
        fk_table_name: "pg_opclass",
        pk_table_oid: 2753,
        pk_table_name: "pg_opfamily",
        fk_columns: &["opcfamily"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2616,
        fk_table_name: "pg_opclass",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["opcintype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2616,
        fk_table_name: "pg_opclass",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["opckeytype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2601,
        fk_table_name: "pg_am",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["amhandler"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2602,
        fk_table_name: "pg_amop",
        pk_table_oid: 2753,
        pk_table_name: "pg_opfamily",
        fk_columns: &["amopfamily"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2602,
        fk_table_name: "pg_amop",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["amoplefttype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2602,
        fk_table_name: "pg_amop",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["amoprighttype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2602,
        fk_table_name: "pg_amop",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["amopopr"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2602,
        fk_table_name: "pg_amop",
        pk_table_oid: 2601,
        pk_table_name: "pg_am",
        fk_columns: &["amopmethod"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2602,
        fk_table_name: "pg_amop",
        pk_table_oid: 2753,
        pk_table_name: "pg_opfamily",
        fk_columns: &["amopsortfamily"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2603,
        fk_table_name: "pg_amproc",
        pk_table_oid: 2753,
        pk_table_name: "pg_opfamily",
        fk_columns: &["amprocfamily"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2603,
        fk_table_name: "pg_amproc",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["amproclefttype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2603,
        fk_table_name: "pg_amproc",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["amprocrighttype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2603,
        fk_table_name: "pg_amproc",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["amproc"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2612,
        fk_table_name: "pg_language",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["lanowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2612,
        fk_table_name: "pg_language",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["lanplcallfoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2612,
        fk_table_name: "pg_language",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["laninline"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2612,
        fk_table_name: "pg_language",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["lanvalidator"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2995,
        fk_table_name: "pg_largeobject_metadata",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["lomowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2613,
        fk_table_name: "pg_largeobject",
        pk_table_oid: 2995,
        pk_table_name: "pg_largeobject_metadata",
        fk_columns: &["loid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggfnoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggtransfn"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggfinalfn"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggcombinefn"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggserialfn"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggdeserialfn"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggmtransfn"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggminvtransfn"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["aggmfinalfn"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["aggsortop"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["aggtranstype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2600,
        fk_table_name: "pg_aggregate",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["aggmtranstype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["starelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["staop1"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["staop2"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["staop3"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["staop4"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 2617,
        pk_table_name: "pg_operator",
        fk_columns: &["staop5"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["stacoll1"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["stacoll2"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["stacoll3"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["stacoll4"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["stacoll5"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2619,
        fk_table_name: "pg_statistic",
        pk_table_oid: 1249,
        pk_table_name: "pg_attribute",
        fk_columns: &["starelid", "staattnum"],
        pk_columns: &["attrelid", "attnum"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3381,
        fk_table_name: "pg_statistic_ext",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["stxrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3381,
        fk_table_name: "pg_statistic_ext",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["stxnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3381,
        fk_table_name: "pg_statistic_ext",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["stxowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3381,
        fk_table_name: "pg_statistic_ext",
        pk_table_oid: 1249,
        pk_table_name: "pg_attribute",
        fk_columns: &["stxrelid", "stxkeys"],
        pk_columns: &["attrelid", "attnum"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3429,
        fk_table_name: "pg_statistic_ext_data",
        pk_table_oid: 3381,
        pk_table_name: "pg_statistic_ext",
        fk_columns: &["stxoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2618,
        fk_table_name: "pg_rewrite",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["ev_class"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2620,
        fk_table_name: "pg_trigger",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["tgrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2620,
        fk_table_name: "pg_trigger",
        pk_table_oid: 2620,
        pk_table_name: "pg_trigger",
        fk_columns: &["tgparentid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2620,
        fk_table_name: "pg_trigger",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["tgfoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2620,
        fk_table_name: "pg_trigger",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["tgconstrrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2620,
        fk_table_name: "pg_trigger",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["tgconstrindid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2620,
        fk_table_name: "pg_trigger",
        pk_table_oid: 2606,
        pk_table_name: "pg_constraint",
        fk_columns: &["tgconstraint"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2620,
        fk_table_name: "pg_trigger",
        pk_table_oid: 1249,
        pk_table_name: "pg_attribute",
        fk_columns: &["tgrelid", "tgattr"],
        pk_columns: &["attrelid", "attnum"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3466,
        fk_table_name: "pg_event_trigger",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["evtowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3466,
        fk_table_name: "pg_event_trigger",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["evtfoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2609,
        fk_table_name: "pg_description",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["classoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2605,
        fk_table_name: "pg_cast",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["castsource"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2605,
        fk_table_name: "pg_cast",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["casttarget"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2605,
        fk_table_name: "pg_cast",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["castfunc"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3501,
        fk_table_name: "pg_enum",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["enumtypid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2615,
        fk_table_name: "pg_namespace",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["nspowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2607,
        fk_table_name: "pg_conversion",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["connamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2607,
        fk_table_name: "pg_conversion",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["conowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2607,
        fk_table_name: "pg_conversion",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["conproc"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2608,
        fk_table_name: "pg_depend",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["classid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2608,
        fk_table_name: "pg_depend",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["refclassid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1262,
        fk_table_name: "pg_database",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["datdba"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1262,
        fk_table_name: "pg_database",
        pk_table_oid: 1213,
        pk_table_name: "pg_tablespace",
        fk_columns: &["dattablespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2964,
        fk_table_name: "pg_db_role_setting",
        pk_table_oid: 1262,
        pk_table_name: "pg_database",
        fk_columns: &["setdatabase"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2964,
        fk_table_name: "pg_db_role_setting",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["setrole"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1213,
        fk_table_name: "pg_tablespace",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["spcowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1261,
        fk_table_name: "pg_auth_members",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["roleid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1261,
        fk_table_name: "pg_auth_members",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["member"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1261,
        fk_table_name: "pg_auth_members",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["grantor"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1214,
        fk_table_name: "pg_shdepend",
        pk_table_oid: 1262,
        pk_table_name: "pg_database",
        fk_columns: &["dbid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1214,
        fk_table_name: "pg_shdepend",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["classid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1214,
        fk_table_name: "pg_shdepend",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["refclassid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2396,
        fk_table_name: "pg_shdescription",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["classoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3602,
        fk_table_name: "pg_ts_config",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["cfgnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3602,
        fk_table_name: "pg_ts_config",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["cfgowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3602,
        fk_table_name: "pg_ts_config",
        pk_table_oid: 3601,
        pk_table_name: "pg_ts_parser",
        fk_columns: &["cfgparser"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3603,
        fk_table_name: "pg_ts_config_map",
        pk_table_oid: 3602,
        pk_table_name: "pg_ts_config",
        fk_columns: &["mapcfg"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3603,
        fk_table_name: "pg_ts_config_map",
        pk_table_oid: 3600,
        pk_table_name: "pg_ts_dict",
        fk_columns: &["mapdict"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3600,
        fk_table_name: "pg_ts_dict",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["dictnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3600,
        fk_table_name: "pg_ts_dict",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["dictowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3600,
        fk_table_name: "pg_ts_dict",
        pk_table_oid: 3764,
        pk_table_name: "pg_ts_template",
        fk_columns: &["dicttemplate"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3601,
        fk_table_name: "pg_ts_parser",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["prsnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3601,
        fk_table_name: "pg_ts_parser",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["prsstart"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3601,
        fk_table_name: "pg_ts_parser",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["prstoken"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3601,
        fk_table_name: "pg_ts_parser",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["prsend"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3601,
        fk_table_name: "pg_ts_parser",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["prsheadline"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3601,
        fk_table_name: "pg_ts_parser",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["prslextype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3764,
        fk_table_name: "pg_ts_template",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["tmplnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3764,
        fk_table_name: "pg_ts_template",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["tmplinit"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3764,
        fk_table_name: "pg_ts_template",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["tmpllexize"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3079,
        fk_table_name: "pg_extension",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["extowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3079,
        fk_table_name: "pg_extension",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["extnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3079,
        fk_table_name: "pg_extension",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["extconfig"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2328,
        fk_table_name: "pg_foreign_data_wrapper",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["fdwowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2328,
        fk_table_name: "pg_foreign_data_wrapper",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["fdwhandler"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2328,
        fk_table_name: "pg_foreign_data_wrapper",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["fdwvalidator"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1417,
        fk_table_name: "pg_foreign_server",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["srvowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1417,
        fk_table_name: "pg_foreign_server",
        pk_table_oid: 2328,
        pk_table_name: "pg_foreign_data_wrapper",
        fk_columns: &["srvfdw"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1418,
        fk_table_name: "pg_user_mapping",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["umuser"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 1418,
        fk_table_name: "pg_user_mapping",
        pk_table_oid: 1417,
        pk_table_name: "pg_foreign_server",
        fk_columns: &["umserver"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3118,
        fk_table_name: "pg_foreign_table",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["ftrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3118,
        fk_table_name: "pg_foreign_table",
        pk_table_oid: 1417,
        pk_table_name: "pg_foreign_server",
        fk_columns: &["ftserver"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3256,
        fk_table_name: "pg_policy",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["polrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3256,
        fk_table_name: "pg_policy",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["polroles"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 826,
        fk_table_name: "pg_default_acl",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["defaclrole"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 826,
        fk_table_name: "pg_default_acl",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["defaclnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3394,
        fk_table_name: "pg_init_privs",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["classoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3596,
        fk_table_name: "pg_seclabel",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["classoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3592,
        fk_table_name: "pg_shseclabel",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["classoid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3456,
        fk_table_name: "pg_collation",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["collnamespace"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3456,
        fk_table_name: "pg_collation",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["collowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3350,
        fk_table_name: "pg_partitioned_table",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["partrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3350,
        fk_table_name: "pg_partitioned_table",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["partdefid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3350,
        fk_table_name: "pg_partitioned_table",
        pk_table_oid: 2616,
        pk_table_name: "pg_opclass",
        fk_columns: &["partclass"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3350,
        fk_table_name: "pg_partitioned_table",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["partcollation"],
        pk_columns: &["oid"],
        is_array: true,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3350,
        fk_table_name: "pg_partitioned_table",
        pk_table_oid: 1249,
        pk_table_name: "pg_attribute",
        fk_columns: &["partrelid", "partattrs"],
        pk_columns: &["attrelid", "attnum"],
        is_array: true,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3541,
        fk_table_name: "pg_range",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["rngtypid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3541,
        fk_table_name: "pg_range",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["rngsubtype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3541,
        fk_table_name: "pg_range",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["rngmultitypid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3541,
        fk_table_name: "pg_range",
        pk_table_oid: 3456,
        pk_table_name: "pg_collation",
        fk_columns: &["rngcollation"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3541,
        fk_table_name: "pg_range",
        pk_table_oid: 2616,
        pk_table_name: "pg_opclass",
        fk_columns: &["rngsubopc"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3541,
        fk_table_name: "pg_range",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["rngcanonical"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3541,
        fk_table_name: "pg_range",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["rngsubdiff"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3576,
        fk_table_name: "pg_transform",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["trftype"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3576,
        fk_table_name: "pg_transform",
        pk_table_oid: 2612,
        pk_table_name: "pg_language",
        fk_columns: &["trflang"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3576,
        fk_table_name: "pg_transform",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["trffromsql"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 3576,
        fk_table_name: "pg_transform",
        pk_table_oid: 1255,
        pk_table_name: "pg_proc",
        fk_columns: &["trftosql"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: true,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2224,
        fk_table_name: "pg_sequence",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["seqrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 2224,
        fk_table_name: "pg_sequence",
        pk_table_oid: 1247,
        pk_table_name: "pg_type",
        fk_columns: &["seqtypid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6104,
        fk_table_name: "pg_publication",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["pubowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6237,
        fk_table_name: "pg_publication_namespace",
        pk_table_oid: 6104,
        pk_table_name: "pg_publication",
        fk_columns: &["pnpubid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6237,
        fk_table_name: "pg_publication_namespace",
        pk_table_oid: 2615,
        pk_table_name: "pg_namespace",
        fk_columns: &["pnnspid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6106,
        fk_table_name: "pg_publication_rel",
        pk_table_oid: 6104,
        pk_table_name: "pg_publication",
        fk_columns: &["prpubid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6106,
        fk_table_name: "pg_publication_rel",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["prrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6100,
        fk_table_name: "pg_subscription",
        pk_table_oid: 1262,
        pk_table_name: "pg_database",
        fk_columns: &["subdbid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6100,
        fk_table_name: "pg_subscription",
        pk_table_oid: 1260,
        pk_table_name: "pg_authid",
        fk_columns: &["subowner"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6102,
        fk_table_name: "pg_subscription_rel",
        pk_table_oid: 6100,
        pk_table_name: "pg_subscription",
        fk_columns: &["srsubid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
    SystemCatalogForeignKey {
        fk_table_oid: 6102,
        fk_table_name: "pg_subscription_rel",
        pk_table_oid: 1259,
        pk_table_name: "pg_class",
        fk_columns: &["srrelid"],
        pk_columns: &["oid"],
        is_array: false,
        is_opt: false,
    },
];

pub fn system_catalog_foreign_key_notice(row: &SystemCatalogForeignKey) -> String {
    format!(
        "checking {} {{{}}} => {} {{{}}}",
        row.fk_table_name,
        row.fk_columns.join(","),
        row.pk_table_name,
        row.pk_columns.join(",")
    )
}
