[package]
name = "parse_relation"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "parse_relation"
path = "src/lib.rs"

[dependencies]
datum = { path = "../../../_support/types/datum" }
catalog_namespace = { path = "../../catalog/catalog_namespace" }
elog = { path = "../../utils/error/elog" }
lsyscache = { path = "../../utils/cache/lsyscache" }
mbutils = { path = "../../utils/mb/mbutils" }
mcx = { path = "../../../_support/mcx" }
namespace_seams = { path = "../../catalog/namespace_seams" }
parser_small1 = { path = "../parser_small1" }
relation_seams = { path = "../../access/common/relation_seams" }
rel_vocab = { path = "../../../_support/types/rel_vocab" }
table = { path = "../../access/table/table" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_rel = { path = "../../../_support/types/rel" }
types_tuple = { path = "../../../_support/types/types_tuple" }

[dev-dependencies]
lmgr_seams = { path = "../../storage/lmgr/lmgr_seams" }
pg_class_seams = { path = "../../catalog/pg_class_seams" }
tupdesc = { path = "../../access/common/tupdesc" }
