[package]
name = "regress_lib"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "regress_lib"
path = "src/lib.rs"

[dependencies]
datum = { path = "../../_support/types/datum" }
types_nodes = { path = "../../_support/types/nodes" }
guc_tables = { path = "../utils/misc/guc_tables" }
mcx = { path = "../../_support/mcx" }
types_core = { path = "../../_support/types/types_core" }
types_error = { path = "../../_support/types/types_error" }
types_storage = { path = "../../_support/types/types_storage" }
types_tuple = { path = "../../_support/types/types_tuple" }
fmgr = { package = "types_fmgr", path = "../../_support/types/fmgr" }
types_trigger_call = { path = "../../_support/types/types_trigger_call" }
dfmgr = { path = "../utils/fmgr/dfmgr" }
coerce = { path = "../parser/coerce" }
adt_geo = { path = "../utils/adt/geo" }
pg_path = { path = "../../port/pg_path" }
mbutils = { path = "../utils/mb/mbutils" }
wchar = { path = "../../common/wchar" }
arrayfuncs = { path = "../utils/adt/arrayfuncs" }
superuser = { path = "../utils/misc/superuser" }
varlena = { path = "../utils/adt/varlena" }
relpath = { path = "../../common/relpath" }
elog_seams = { path = "../utils/error/elog_seams" }
typcache = { path = "../utils/cache/typcache" }
detoast_seams = { path = "../access/common/detoast_seams" }
detoast = { path = "../access/common/detoast" }
heaptuple = { path = "../access/common/heaptuple" }
catalog = { path = "../catalog/catalog" }
init_small = { path = "../utils/init/init_small" }
funcapi = { path = "../utils/fmgr/funcapi" }
namespace_seams = { path = "../catalog/namespace_seams" }
libc = "0.2"
