[package]
name = "timeline"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "timeline"
path = "src/lib.rs"

[dependencies]
init_small = { path = "../../../utils/init/init_small" }
libc = "0.2"
mcx = { path = "../../../../_support/mcx" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
elog = { path = "../../../utils/error/elog" }
fd = { path = "../../../storage/file/fd" }
timeline_seams = { path = "../timeline_seams" }
xlogarchive_seams = { path = "../xlogarchive_seams" }
xlogrecovery_seams = { path = "../xlogrecovery_seams" }
waitevent_seams = { path = "../../../utils/activity/waitevent_seams" }

[dev-dependencies]
guc_tables = { path = "../../../utils/misc/guc_tables" }
xact_seams = { path = "../xact_seams" }
pgstat_seams = { path = "../../../utils/activity/pgstat_seams" }
ipc_seams = { path = "../../../storage/ipc/ipc_seams" }
init_small_seams = { path = "../../../utils/init/init_small_seams" }
