-- deck-ld8-earm2: ERROR-ARM round 2 hand-verify deck (lane LD8).
-- Probe superset for the earm2 module: residual ereport/validation arms
-- the LD6 earm pass left in the four ERROR-ARM chunks (line-drain-queue,
-- line-gap-report-002 grain): tablecmds partition/inherit/FK-clone arms,
-- ALTER COLUMN TYPE, DefineType I/O combos, function/operator DDL +
-- resolution, window/agg validation, extension/tsearch DDL, shared-dep
-- drops, sequence/identity, trigger/rule/constraint definition, encoding/
-- conversion/collation errors, parser residue (U& escapes, literals),
-- async/NOTIFY arms, relation/target-list analysis errors.
-- One statement per line (diffrunner --replay compatible). Every erroring
-- probe is isolated; intentional successes are fixtures and are dropped
-- in-section. Applied per-statement to BOTH engines before module encoding.
-- ============================================================ fixtures ====
CREATE TABLE ea2_base (a int PRIMARY KEY, b text, c numeric(10,2));
INSERT INTO ea2_base VALUES (1, 'one', 1.10), (2, 'two', 2.20);
CREATE TABLE ea2_ref (x int, y int);
INSERT INTO ea2_ref VALUES (1, 1), (2, 2);
-- ==================================================== earm2:parttab =======
CREATE TABLE ea2_part (id int NOT NULL, ts date NOT NULL) PARTITION BY RANGE (ts);
CREATE TABLE ea2_p1 PARTITION OF ea2_part FOR VALUES FROM ('2020-01-01') TO ('2021-01-01');
CREATE TABLE ea2_p2 PARTITION OF ea2_part FOR VALUES FROM ('2021-01-01') TO ('2022-01-01');
CREATE TABLE ea2_cand (id int, ts date);
CREATE TABLE ea2_badcols (id text, ts date);
CREATE TABLE ea2_extra (id int, ts date, zz int);
CREATE TABLE ea2_part2 (id int, ts date) PARTITION BY LIST (id);
ALTER TABLE ea2_part ATTACH PARTITION ea2_p1 FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');
ALTER TABLE ea2_part ATTACH PARTITION ea2_part FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');
ALTER TABLE ea2_part ATTACH PARTITION ea2_badcols FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');
ALTER TABLE ea2_part ATTACH PARTITION ea2_extra FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');
ALTER TABLE ea2_part ATTACH PARTITION ea2_cand FOR VALUES FROM ('2020-06-01') TO ('2020-09-01');
ALTER TABLE ea2_part ATTACH PARTITION ea2_cand FOR VALUES FROM ('2026-01-01') TO ('2025-01-01');
ALTER TABLE ea2_part ATTACH PARTITION ea2_cand DEFAULT;
ALTER TABLE ea2_part DETACH PARTITION ea2_cand;
ALTER TABLE ea2_part DETACH PARTITION ea2_badcols;
BEGIN;
ALTER TABLE ea2_part DETACH PARTITION ea2_p1 CONCURRENTLY;
ROLLBACK;
ALTER TABLE ea2_part DETACH PARTITION ea2_p1 FINALIZE;
CREATE TABLE ea2_pbad PARTITION OF ea2_part FOR VALUES FROM ('2020-06-01') TO ('2020-09-01');
CREATE TABLE ea2_pbad PARTITION OF ea2_part FOR VALUES FROM ('2022-01-01') TO ('2022-01-01');
CREATE TABLE ea2_pbad PARTITION OF ea2_base FOR VALUES FROM (1) TO (10);
CREATE TABLE ea2_pbad PARTITION OF ea2_part (LIKE ea2_base) FOR VALUES FROM ('2023-01-01') TO ('2024-01-01');
INSERT INTO ea2_part VALUES (1, '2019-06-01');
ALTER TABLE ea2_p1 INHERIT ea2_base;
ALTER TABLE ea2_cand INHERIT ea2_cand;
ALTER TABLE ea2_cand INHERIT ea2_base;
ALTER TABLE ea2_cand INHERIT ea2_part;
ALTER TABLE ea2_cand NO INHERIT ea2_base;
ALTER TABLE ea2_p1 NO INHERIT ea2_part;
CREATE TABLE ea2_child (a text) INHERITS (ea2_base);
CREATE TABLE ea2_child (zz int) INHERITS (ea2_base, ea2_base);
CREATE TABLE ea2_child (zz int) INHERITS (ea2_part);
CREATE TABLE ea2_child (a int DEFAULT 5, zz int) INHERITS (ea2_base);
DROP TABLE ea2_child;
TRUNCATE ONLY ea2_part;
ALTER TABLE ONLY ea2_part ADD COLUMN oc int;
CREATE TABLE ea2_fkref (id int PRIMARY KEY);
ALTER TABLE ea2_part ADD CONSTRAINT ea2_pfk FOREIGN KEY (id) REFERENCES ea2_fkref;
TRUNCATE ea2_fkref;
ALTER TABLE ea2_part DROP CONSTRAINT ea2_pfk;
ALTER TABLE ea2_p1 DROP CONSTRAINT ea2_pfk;
DROP TABLE ea2_fkref;
ALTER TABLE ea2_part OWNER TO ea2_norole;
ALTER TABLE pg_class OWNER TO postgres;
ALTER TABLE pg_class SET SCHEMA public;
ALTER TABLE ea2_part2 ATTACH PARTITION ea2_p1 FOR VALUES IN (1);
DROP TABLE ea2_part2;
DROP TABLE ea2_extra;
DROP TABLE ea2_badcols;
DROP TABLE ea2_cand;
DROP TABLE ea2_part;
-- ==================================================== earm2:altype ========
CREATE TABLE ea2_at (i int, t text, g int GENERATED ALWAYS AS (i + 1) STORED, iden int GENERATED ALWAYS AS IDENTITY);
CREATE VIEW ea2_atv AS SELECT i FROM ea2_at;
CREATE INDEX ea2_at_ti ON ea2_at (t);
ALTER TABLE ea2_at ALTER COLUMN i TYPE point;
ALTER TABLE ea2_at ALTER COLUMN i TYPE text;
ALTER TABLE ea2_at ALTER COLUMN t TYPE int;
ALTER TABLE ea2_at ALTER COLUMN t TYPE int USING length(t) || 'x';
ALTER TABLE ea2_at ALTER COLUMN t TYPE int USING nosuchcol + 1;
ALTER TABLE ea2_at ALTER COLUMN i TYPE bigint USING (SELECT 1);
ALTER TABLE ea2_at ALTER COLUMN g TYPE point;
ALTER TABLE ea2_at ALTER COLUMN iden TYPE text;
ALTER TABLE ea2_at ALTER COLUMN nosuch TYPE int;
ALTER TABLE ea2_atv ALTER COLUMN i TYPE bigint;
CREATE TABLE ea2_pk (ts date NOT NULL) PARTITION BY RANGE (ts);
ALTER TABLE ea2_pk ALTER COLUMN ts TYPE text;
DROP TABLE ea2_pk;
CREATE TABLE ea2_par (i int);
CREATE TABLE ea2_chi () INHERITS (ea2_par);
ALTER TABLE ea2_chi ALTER COLUMN i TYPE bigint;
ALTER TABLE ONLY ea2_par ALTER COLUMN i TYPE bigint;
DROP TABLE ea2_chi;
DROP TABLE ea2_par;
DROP VIEW ea2_atv;
DROP TABLE ea2_at;
-- ==================================================== earm2:typio =========
CREATE TYPE ea2_shell;
CREATE TYPE ea2_shell;
CREATE TYPE ea2_tio (input = nosuch_in, output = nosuch_out);
CREATE TYPE ea2_tio (output = int4out);
CREATE TYPE ea2_tio (input = int4in);
CREATE TYPE ea2_tio (input = int4in, output = int4out, internallength = -3);
CREATE TYPE ea2_tio (input = int4in, output = int4out, alignment = char16);
CREATE TYPE ea2_tio (input = int4in, output = int4out, storage = nosuch);
CREATE TYPE ea2_tio (input = int4in, output = int4out, internallength = 2, passedbyvalue, alignment = double);
CREATE TYPE ea2_tio (input = array_in, output = int4out);
CREATE TYPE ea2_tio (input = int4in, output = int4out, element = nosuchtype);
CREATE TYPE ea2_tio (input = int4in, output = int4out, delimiter = 'ab');
CREATE TYPE ea2_tio (input = int4in, output = int4out, category = 'xx');
CREATE TYPE ea2_tio (input = int4in, output = int4out, receive = nosuch_recv);
CREATE TYPE ea2_tio (input = int4in, output = int4out, send = nosuch_send);
CREATE TYPE ea2_tio (input = int4in, output = int4out, typmod_in = nosuch_tmin);
CREATE TYPE ea2_tio (input = int4in, output = int4out, analyze = nosuch_an);
CREATE TYPE ea2_tio (input = int4in, output = int4out, collatable = maybe);
CREATE TYPE ea2_tio (nosuchparam = 1);
CREATE TYPE ea2_comp AS (p int, q text);
CREATE TYPE ea2_comp AS (p int, p int);
CREATE TYPE ea2_enum AS ENUM ('a', 'a');
CREATE TYPE ea2_rng AS RANGE (subtype = ea2_shell);
CREATE TYPE ea2_rng AS RANGE (subtype = int4, subtype_opclass = nosuch_opc);
CREATE TYPE ea2_rng AS RANGE (subtype = int4, collation = "C");
CREATE TYPE ea2_rng AS RANGE (subtype = int4, canonical = nosuch_canon);
CREATE TYPE ea2_rng AS RANGE (subtype = point);
CREATE TYPE ea2_mr AS RANGE (subtype = int4, multirange_type_name = ea2_comp);
DROP TYPE ea2_comp;
DROP TYPE ea2_shell;
-- ==================================================== earm2:funcddl =======
CREATE FUNCTION ea2_bad() RETURNS int LANGUAGE sql AS 'SELECT ''x''::text';
CREATE FUNCTION ea2_bad() RETURNS int LANGUAGE nosuchlang AS 'SELECT 1';
CREATE FUNCTION ea2_bad(VARIADIC v int[], z int) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION ea2_bad(a int DEFAULT 1, b int) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION ea2_bad(a int, a int) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION ea2_bad(OUT o int, VARIADIC v text[]) RETURNS SETOF record LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION ea2_bad() RETURNS trigger LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION ea2_f1(int) RETURNS int LANGUAGE sql AS 'SELECT $1';
CREATE OR REPLACE FUNCTION ea2_f1(int) RETURNS text LANGUAGE sql AS 'SELECT ''x''::text';
CREATE OR REPLACE FUNCTION ea2_f1(x int) RETURNS int LANGUAGE sql AS 'SELECT x';
CREATE OR REPLACE FUNCTION ea2_f1(y int) RETURNS int LANGUAGE sql AS 'SELECT y';
CREATE PROCEDURE ea2_pr1() LANGUAGE sql AS 'SELECT 1';
ALTER FUNCTION ea2_pr1() STRICT;
ALTER FUNCTION ea2_nosuch(int) STRICT;
ALTER FUNCTION ea2_f1(int) COST -5;
ALTER FUNCTION ea2_f1(int) ROWS 10;
ALTER PROCEDURE ea2_f1(int) SET search_path = public;
ALTER PROCEDURE ea2_pr1() COST 5;
ALTER ROUTINE ea2_nosuch(int) IMMUTABLE;
DROP PROCEDURE ea2_pr1();
CREATE AGGREGATE ea2_f1(int) (sfunc = int4pl, stype = int);
CREATE FUNCTION ea2_opf(int, int) RETURNS int LANGUAGE sql AS 'SELECT $1 + $2';
CREATE OPERATOR ##! (function = nosuchfunc, leftarg = int, rightarg = int);
CREATE OPERATOR ##! (leftarg = int, rightarg = int);
CREATE OPERATOR ##! (function = ea2_opf, leftarg = int, rightarg = int, commutator = OPERATOR(###!!));
CREATE OPERATOR ##! (function = ea2_opf, leftarg = int, rightarg = int, negator = ##!);
CREATE OPERATOR =>= (function = ea2_opf, leftarg = int, rightarg = int);
CREATE OPERATOR ##! (function = ea2_opf);
CREATE OPERATOR ##! (function = ea2_opf, leftarg = int, rightarg = int, restrict = nosuchrest);
CREATE OPERATOR ##! (function = ea2_opf, leftarg = int, rightarg = int, join = nosuchjoin);
CREATE OPERATOR ##! (function = ea2_opf, leftarg = int, rightarg = int, hashes, merges);
ALTER OPERATOR ##! (int, int) SET (restrict = nosuchrest);
ALTER OPERATOR ##! (int, int) SET (negator = ##!);
ALTER OPERATOR ##! (int, int) SET (nosuchopt = 1);
DROP OPERATOR ##! (int, int);
DROP OPERATOR =>= (int, int);
DROP OPERATOR IF EXISTS ###!! (int, int);
DROP FUNCTION ea2_opf(int, int);
DROP FUNCTION ea2_f1(int);
-- ==================================================== earm2:funcres =======
CREATE FUNCTION ea2_amb(x int) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION ea2_amb(x real) RETURNS int LANGUAGE sql AS 'SELECT 2';
SELECT ea2_amb(1.5);
SELECT ea2_amb('7');
SELECT ea2_nosuchfunc(1);
SELECT ea2_amb(nosucharg => 1);
SELECT ea2_amb(x => 1, x => 2);
SELECT ea2_amb(x => 1, 2);
SELECT ea2_amb(VARIADIC ARRAY[1]);
SELECT count(DISTINCT a) OVER () FROM ea2_base;
SELECT (a).nosuchfield FROM ea2_base;
SELECT (b).f1 FROM ea2_base;
SELECT ea2_base.nosuchcol FROM ea2_base;
CREATE PROCEDURE ea2_pr2() LANGUAGE sql AS 'SELECT 1';
SELECT ea2_pr2();
CALL ea2_amb(1);
CALL ea2_nosuchproc();
DROP PROCEDURE ea2_pr2();
DROP FUNCTION ea2_amb(int);
DROP FUNCTION ea2_amb(real);
SELECT 1 OPERATOR(nosuchschema.+) 2;
SELECT 1 OPERATOR(pg_catalog.!!!) 2;
SELECT point '(1,1)' + 'abc';
SELECT 'abc'::text % 'def'::text;
SELECT abs('abc'::text);
SELECT lower(42);
-- ==================================================== earm2:winval ========
SELECT a, row_number() OVER (ORDER BY a) FROM ea2_base WHERE row_number() OVER (ORDER BY a) < 2;
SELECT a FROM ea2_base GROUP BY row_number() OVER ();
SELECT rank() OVER (ORDER BY rank() OVER (ORDER BY a)) FROM ea2_base;
SELECT abs(1) OVER () FROM ea2_base;
SELECT sum(a) OVER (ROWS BETWEEN 1 FOLLOWING AND CURRENT ROW) FROM ea2_base;
SELECT sum(a) OVER (ROWS BETWEEN CURRENT ROW AND 1 PRECEDING) FROM ea2_base;
SELECT sum(a) OVER (ORDER BY a, b RANGE BETWEEN 1 PRECEDING AND CURRENT ROW) FROM ea2_base;
SELECT sum(a) OVER (RANGE BETWEEN 1 PRECEDING AND CURRENT ROW) FROM ea2_base;
SELECT sum(a) OVER (GROUPS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM ea2_base;
SELECT sum(a) OVER (ORDER BY a ROWS BETWEEN -1 PRECEDING AND CURRENT ROW) FROM ea2_base;
SELECT sum(a) OVER (ORDER BY a RANGE BETWEEN 'x' PRECEDING AND CURRENT ROW) FROM ea2_base;
SELECT sum(a) OVER (ORDER BY b RANGE BETWEEN 1 PRECEDING AND CURRENT ROW) FROM ea2_base;
SELECT rank(a) OVER (ORDER BY a) FROM ea2_base;
SELECT rank() FILTER (WHERE a > 1) OVER (ORDER BY a) FROM ea2_base;
SELECT sum(a) OVER w2 FROM ea2_base WINDOW w AS (ORDER BY a);
SELECT sum(a) OVER (w ORDER BY b) FROM ea2_base WINDOW w AS (ORDER BY a ROWS UNBOUNDED PRECEDING);
SELECT sum(a) OVER (w) FROM ea2_base WINDOW w AS (PARTITION BY a), w AS (PARTITION BY b);
SELECT sum(a) OVER (PARTITION BY b w) FROM ea2_base WINDOW w AS (ORDER BY a);
SELECT lag(a) OVER () FROM ea2_base GROUP BY b;
SELECT sum(sum(a)) FROM ea2_base;
SELECT sum(a) FROM ea2_base HAVING sum(a) OVER () > 1;
SELECT a FROM ea2_base GROUP BY GROUPING SETS (a, sum(a));
SELECT GROUPING(a) FROM ea2_base;
SELECT GROUPING(b) FROM ea2_base GROUP BY a;
SELECT GROUPING() FROM ea2_base GROUP BY a;
SELECT a, GROUPING(a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a) FROM ea2_base GROUP BY a;
SELECT string_agg(b, ',' ORDER BY a) WITHIN GROUP (ORDER BY b) FROM ea2_base;
SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY a) OVER () FROM ea2_base;
SELECT percentile_cont(a) WITHIN GROUP (ORDER BY a) FROM ea2_base;
SELECT mode() FROM ea2_base;
SELECT nth_value(a, 0) OVER (ORDER BY a) FROM ea2_base;
SELECT ntile(0) OVER (ORDER BY a) FROM ea2_base;
-- ==================================================== earm2:ext ===========
CREATE EXTENSION ea2_nosuchext;
CREATE EXTENSION plpgsql;
CREATE EXTENSION IF NOT EXISTS plpgsql;
CREATE EXTENSION plpgsql VERSION 'nosuch';
CREATE EXTENSION plpgsql SCHEMA ea2_noschema;
ALTER EXTENSION plpgsql UPDATE TO 'nosuch';
ALTER EXTENSION ea2_nosuchext UPDATE;
ALTER EXTENSION plpgsql SET SCHEMA public;
ALTER EXTENSION plpgsql ADD TABLE ea2_base;
ALTER EXTENSION plpgsql DROP TABLE ea2_base;
DROP EXTENSION ea2_nosuchext;
COMMENT ON EXTENSION ea2_nosuchext IS 'x';
-- ==================================================== earm2:tsearch =======
CREATE TEXT SEARCH DICTIONARY ea2_d (nosuchopt = 1);
CREATE TEXT SEARCH DICTIONARY ea2_d (template = nosuchtmpl);
CREATE TEXT SEARCH DICTIONARY ea2_d (template = simple, nosuchopt = 1);
CREATE TEXT SEARCH DICTIONARY ea2_d (template = simple, stopwords = ea2_nosuchfile);
CREATE TEXT SEARCH DICTIONARY ea2_d (template = simple);
ALTER TEXT SEARCH DICTIONARY ea2_d (nosuchopt = 1);
ALTER TEXT SEARCH DICTIONARY ea2_d (stopwords = ea2_nosuchfile);
ALTER TEXT SEARCH DICTIONARY ea2_nosuch (accept = false);
CREATE TEXT SEARCH CONFIGURATION ea2_c (parser = nosuchparser);
CREATE TEXT SEARCH CONFIGURATION ea2_c (parser = default, copy = english);
CREATE TEXT SEARCH CONFIGURATION ea2_c (copy = nosuchcfg);
CREATE TEXT SEARCH CONFIGURATION ea2_c (nosuchopt = 1);
CREATE TEXT SEARCH CONFIGURATION ea2_c (copy = english);
ALTER TEXT SEARCH CONFIGURATION ea2_c ADD MAPPING FOR nosuchtoken WITH simple;
ALTER TEXT SEARCH CONFIGURATION ea2_c ADD MAPPING FOR word WITH nosuchdict;
ALTER TEXT SEARCH CONFIGURATION ea2_c ADD MAPPING FOR word WITH ea2_d;
ALTER TEXT SEARCH CONFIGURATION ea2_c DROP MAPPING FOR nosuchtoken;
ALTER TEXT SEARCH CONFIGURATION ea2_c DROP MAPPING FOR sfloat;
ALTER TEXT SEARCH CONFIGURATION ea2_c DROP MAPPING IF EXISTS FOR sfloat;
ALTER TEXT SEARCH CONFIGURATION ea2_c ALTER MAPPING REPLACE nosuchdict WITH simple;
DROP TEXT SEARCH CONFIGURATION ea2_c;
DROP TEXT SEARCH DICTIONARY ea2_d;
CREATE TEXT SEARCH TEMPLATE ea2_t (lexize = nosuchfunc);
CREATE TEXT SEARCH TEMPLATE ea2_t (init = dsimple_init);
CREATE TEXT SEARCH PARSER ea2_p (start = prsd_start, gettoken = prsd_nexttoken, end = prsd_end, lextypes = nosuchfunc);
CREATE TEXT SEARCH PARSER ea2_p (gettoken = prsd_nexttoken, end = prsd_end, lextypes = prsd_lextype);
SELECT ts_lexize('nosuchdict', 'word');
SELECT to_tsvector('nosuchcfg', 'word');
-- ==================================================== earm2:schema2 =======
CREATE TEMP TABLE public.ea2_tt (x int);
CREATE TABLE pg_temp.ea2_tt2 (x int);
DROP TABLE pg_temp.ea2_tt2;
CREATE TABLE ea2_totoast (x int);
ALTER TABLE ea2_totoast SET SCHEMA pg_toast;
ALTER TABLE ea2_totoast SET SCHEMA pg_temp;
ALTER TABLE ea2_totoast SET SCHEMA ea2_noschema;
ALTER TABLE ea2_totoast SET SCHEMA public;
DROP TABLE ea2_totoast;
CREATE TABLE pg_toast.ea2_bad (x int);
SET search_path = ea2_nosuchschema;
CREATE TABLE ea2_nowhere (x int);
RESET search_path;
CREATE SCHEMA IF NOT EXISTS public;
CREATE SCHEMA pg_reserved2;
CREATE SCHEMA AUTHORIZATION ea2_norole;
ALTER SCHEMA ea2_nosuchschema RENAME TO x;
-- ==================================================== earm2:relref ========
INSERT INTO ea2_base (a, b) VALUES (10, 'x', 1);
INSERT INTO ea2_base (a, b, c, a) VALUES (10, 'x', 1, 2);
INSERT INTO ea2_base (a, nosuch) VALUES (10, 'x');
INSERT INTO ea2_base VALUES (10, 'x', 1, 99);
INSERT INTO ea2_base SELECT * FROM ea2_ref;
UPDATE ea2_base SET a = 1, a = 2 WHERE a = 1;
UPDATE ea2_base SET (a, b) = (SELECT 1, 'x', 2) WHERE a = 1;
UPDATE ea2_base SET (a, b) = (1, 'x') WHERE nosuch = 1;
INSERT INTO ea2_base VALUES (1, 'dup', 0) ON CONFLICT ON CONSTRAINT ea2_nosuchcon DO NOTHING;
INSERT INTO ea2_base VALUES (1, 'dup', 0) ON CONFLICT (b) DO NOTHING;
INSERT INTO ea2_base VALUES (1, 'dup', 0) ON CONFLICT (a) DO UPDATE SET nosuch = 1;
INSERT INTO ea2_base VALUES (1, 'dup', 0) ON CONFLICT (a) DO UPDATE SET a = excluded.nosuch;
SELECT * FROM ea2_base, ea2_base;
SELECT * FROM ea2_base x, ea2_ref x;
SELECT * FROM ea2_base JOIN ea2_ref USING (nosuch);
SELECT * FROM ea2_base JOIN ea2_ref USING (a);
SELECT * FROM ea2_base b1 JOIN ea2_ref r1 ON b2.a = r1.x;
SELECT ea2_ref.x FROM ea2_base;
SELECT * FROM ea2_base AS t (c1, c2, c3, c4);
SELECT * FROM ea2_base TABLESAMPLE nosuchmethod (10);
SELECT * FROM ea2_base TABLESAMPLE bernoulli (101);
SELECT * FROM ea2_base TABLESAMPLE system (10) REPEATABLE (1e400);
SELECT * FROM generate_series(1, 3) WITH ORDINALITY AS t (v);
SELECT * FROM ROWS FROM (generate_series(1, 2), abs(1)) WITH ORDINALITY AS t (a, b);
SELECT a FROM ea2_base GROUP BY 5;
SELECT a FROM ea2_base ORDER BY 5;
SELECT a FROM ea2_base GROUP BY a ORDER BY b;
SELECT DISTINCT ON (b) a FROM ea2_base ORDER BY a;
SELECT DISTINCT a, b FROM ea2_base ORDER BY c;
SELECT a FROM ea2_base FOR UPDATE OF nosuch;
SELECT sum(a) FROM ea2_base FOR UPDATE;
SELECT DISTINCT a FROM ea2_base FOR UPDATE;
SELECT a FROM ea2_base GROUP BY a FOR UPDATE;
SELECT * FROM (SELECT a FROM ea2_base) s FOR UPDATE OF nosuchrel;
SELECT * FROM ea2_base LEFT JOIN ea2_ref ON true FOR UPDATE OF ea2_ref;
VALUES (1, 2), (3);
VALUES (1) ORDER BY 2;
SELECT 1 UNION SELECT 'a', 'b';
SELECT 1 UNION SELECT 'abc';
SELECT 1 INTERSECT SELECT point '(1,1)';
SELECT nosuchcol;
SELECT * INTO ea2_into FROM ea2_base;
SELECT * INTO ea2_into FROM ea2_base;
DROP TABLE ea2_into;
WITH x AS (SELECT 1) SELECT * FROM nosuchtable;
WITH x AS (SELECT 1), x AS (SELECT 2) SELECT 1;
WITH RECURSIVE x (n) AS (SELECT 1 UNION SELECT n + 1 FROM x, x y WHERE n < 3) SELECT 1 FROM x;
WITH RECURSIVE x (n) AS (SELECT n FROM x) SELECT 1 FROM x;
-- ==================================================== earm2:shdep =========
CREATE ROLE ea2_owner;
CREATE TABLE ea2_owned (z int);
ALTER TABLE ea2_owned OWNER TO ea2_owner;
DROP ROLE ea2_owner;
CREATE ROLE ea2_grantee;
GRANT SELECT ON ea2_base TO ea2_grantee;
DROP ROLE ea2_grantee;
REVOKE SELECT ON ea2_base FROM ea2_grantee;
DROP OWNED BY ea2_grantee;
DROP ROLE ea2_grantee;
ALTER TABLE ea2_owned OWNER TO postgres;
DROP ROLE ea2_owner;
DROP TABLE ea2_owned;
REASSIGN OWNED BY ea2_nosuchrole TO postgres;
DROP OWNED BY ea2_nosuchrole;
REASSIGN OWNED BY postgres TO postgres;
GRANT SELECT ON ea2_base TO ea2_nosuchrole;
GRANT nosuchpriv ON ea2_base TO PUBLIC;
GRANT USAGE ON TABLE ea2_base TO PUBLIC;
GRANT SELECT ON FUNCTION abs(int) TO PUBLIC;
GRANT EXECUTE ON TABLE ea2_base TO PUBLIC;
GRANT SELECT (nosuchcol) ON ea2_base TO PUBLIC;
GRANT EXECUTE ON FUNCTION ea2_nosuchfunc(int) TO PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA ea2_noschema TO PUBLIC;
REVOKE nosuchpriv ON ea2_base FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE ea2_nosuchrole GRANT SELECT ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA ea2_noschema GRANT SELECT ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON TABLES TO PUBLIC;
GRANT ea2_nosuchrole TO postgres;
GRANT postgres TO postgres;
CREATE ROLE ea2_cyc1;
CREATE ROLE ea2_cyc2;
GRANT ea2_cyc1 TO ea2_cyc2;
GRANT ea2_cyc2 TO ea2_cyc1;
GRANT ea2_cyc1 TO ea2_cyc1;
DROP ROLE ea2_cyc2;
DROP ROLE ea2_cyc1;
-- ==================================================== earm2:seqid =========
CREATE SEQUENCE ea2_s INCREMENT 0;
CREATE SEQUENCE ea2_s MINVALUE 10 MAXVALUE 5;
CREATE SEQUENCE ea2_s START 100 MAXVALUE 50;
CREATE SEQUENCE ea2_s START -100 MINVALUE -50;
CREATE SEQUENCE ea2_s AS text;
CREATE SEQUENCE ea2_s AS numeric;
CREATE SEQUENCE ea2_s CACHE 0;
CREATE SEQUENCE ea2_s MAXVALUE 100 AS smallint START 99999;
CREATE SEQUENCE ea2_s;
ALTER SEQUENCE ea2_s RESTART 10 MAXVALUE 5;
ALTER SEQUENCE ea2_s AS smallint MAXVALUE 99999999;
ALTER SEQUENCE ea2_s OWNED BY ea2_base.nosuch;
ALTER SEQUENCE ea2_s OWNED BY ea2_base;
ALTER SEQUENCE ea2_s OWNED BY nosuchtab.col;
ALTER SEQUENCE ea2_s OWNED BY ea2_base.a.b.c;
SELECT setval('ea2_s', 9223372036854775807);
SELECT nextval('ea2_base');
SELECT currval('ea2_s');
DROP SEQUENCE ea2_s;
CREATE TABLE ea2_idt (i int GENERATED ALWAYS AS IDENTITY, t text);
ALTER TABLE ea2_idt ALTER COLUMN i ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE ea2_idt ALTER COLUMN t ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE ea2_idt ALTER COLUMN t SET GENERATED BY DEFAULT;
ALTER TABLE ea2_idt ALTER COLUMN t DROP IDENTITY;
ALTER TABLE ea2_idt ALTER COLUMN t DROP IDENTITY IF EXISTS;
ALTER TABLE ea2_idt ALTER COLUMN i SET NOT NULL;
ALTER TABLE ea2_idt ALTER COLUMN i DROP NOT NULL;
INSERT INTO ea2_idt (i, t) VALUES (5, 'x');
INSERT INTO ea2_idt (i, t) OVERRIDING USER VALUE VALUES (5, 'x');
UPDATE ea2_idt SET i = 9;
CREATE TABLE ea2_gen (i int, g int GENERATED ALWAYS AS (i * 2) STORED);
ALTER TABLE ea2_gen ALTER COLUMN g SET DEFAULT 5;
ALTER TABLE ea2_gen ALTER COLUMN g DROP DEFAULT;
INSERT INTO ea2_gen (i, g) VALUES (1, 5);
UPDATE ea2_gen SET g = 9;
CREATE TABLE ea2_genbad (i int, g int GENERATED ALWAYS AS (random()::int) STORED);
CREATE TABLE ea2_genbad (i int, g int GENERATED ALWAYS AS ((SELECT 1)) STORED);
CREATE TABLE ea2_genbad (i int, g int GENERATED ALWAYS AS (h + 1) STORED, h int GENERATED ALWAYS AS (i + 1) STORED);
CREATE TABLE ea2_genbad (i int, g int GENERATED ALWAYS AS (g + 1) STORED);
CREATE TABLE ea2_genbad (i int, g int GENERATED ALWAYS AS (i + 1) STORED DEFAULT 5);
CREATE TABLE ea2_genbad (i int, g serial GENERATED ALWAYS AS (i + 1) STORED);
DROP TABLE ea2_gen;
DROP TABLE ea2_idt;
-- ==================================================== earm2:trigrule ======
CREATE FUNCTION ea2_tgf() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RETURN NEW; END$$;
CREATE FUNCTION ea2_plain() RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE VIEW ea2_v AS SELECT a, b FROM ea2_base;
CREATE TRIGGER ea2_tg BEFORE INSERT ON ea2_base FOR EACH ROW EXECUTE FUNCTION ea2_nosuchtgf();
CREATE TRIGGER ea2_tg BEFORE INSERT ON ea2_base FOR EACH ROW EXECUTE FUNCTION ea2_plain();
CREATE TRIGGER ea2_tg BEFORE INSERT ON ea2_v FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg INSTEAD OF INSERT ON ea2_base FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg INSTEAD OF INSERT ON ea2_v FOR EACH ROW WHEN (true) EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg INSTEAD OF INSERT ON ea2_v FOR EACH STATEMENT EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg AFTER TRUNCATE ON ea2_base FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg BEFORE INSERT ON ea2_base REFERENCING NEW TABLE AS nt FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg AFTER UPDATE ON ea2_base REFERENCING OLD TABLE AS ot NEW TABLE AS ot FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg AFTER INSERT ON ea2_base REFERENCING OLD TABLE AS ot FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg AFTER DELETE ON ea2_base REFERENCING NEW TABLE AS nt FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg BEFORE INSERT ON ea2_base FOR EACH ROW WHEN (OLD.a > 1) EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg BEFORE DELETE ON ea2_base FOR EACH ROW WHEN (NEW.a > 1) EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg AFTER INSERT ON ea2_base FOR EACH ROW WHEN ((SELECT true)) EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg BEFORE INSERT ON ea2_base FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE TRIGGER ea2_tg BEFORE INSERT ON ea2_base FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE CONSTRAINT TRIGGER ea2_ctg BEFORE INSERT ON ea2_base FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
CREATE CONSTRAINT TRIGGER ea2_ctg AFTER INSERT ON ea2_v FOR EACH ROW EXECUTE FUNCTION ea2_tgf();
DROP TRIGGER ea2_nosuchtg ON ea2_base;
DROP TRIGGER ea2_tg ON ea2_v;
DROP TRIGGER ea2_tg ON ea2_base;
ALTER TRIGGER ea2_nosuchtg ON ea2_base RENAME TO x;
ALTER TABLE ea2_base DISABLE TRIGGER ea2_nosuchtg;
CREATE RULE ea2_r AS ON SELECT TO ea2_base DO INSTEAD SELECT 1;
CREATE RULE "_RETURN" AS ON SELECT TO ea2_base DO INSTEAD SELECT a, b FROM ea2_ref;
CREATE RULE ea2_r AS ON INSERT TO ea2_v DO INSTEAD NOTHING;
CREATE RULE ea2_r AS ON UPDATE TO ea2_base WHERE nosuch = 1 DO INSTEAD NOTHING;
CREATE RULE ea2_r AS ON DELETE TO ea2_base DO INSTEAD SELECT NEW.a;
CREATE RULE ea2_r AS ON INSERT TO ea2_base DO ALSO INSERT INTO ea2_nosuchtab VALUES (1);
CREATE RULE ea2_r AS ON UPDATE TO pg_class DO INSTEAD NOTHING;
CREATE OR REPLACE RULE ea2_r AS ON INSERT TO ea2_v DO INSTEAD NOTHING;
CREATE OR REPLACE RULE ea2_r AS ON DELETE TO ea2_v DO INSTEAD NOTHING;
DROP RULE ea2_r ON ea2_v;
DROP RULE ea2_nosuchrule ON ea2_base;
ALTER TABLE ea2_base ADD CONSTRAINT ea2_ck CHECK (a > 0);
ALTER TABLE ea2_base ADD CONSTRAINT ea2_ck CHECK (a < 1000);
ALTER TABLE ea2_base ADD CONSTRAINT ea2_ck2 CHECK (nosuch > 0);
ALTER TABLE ea2_base ADD CONSTRAINT ea2_ck3 CHECK ((SELECT true));
ALTER TABLE ea2_base ADD CONSTRAINT ea2_ck5 CHECK (sum(a) > 0);
ALTER TABLE ea2_base DROP CONSTRAINT ea2_ck;
ALTER TABLE ea2_base ADD CONSTRAINT ea2_ex EXCLUDE USING btree (b WITH %);
ALTER TABLE ea2_base ADD CONSTRAINT ea2_ex EXCLUDE USING hash (a WITH <);
ALTER TABLE ea2_base ADD CONSTRAINT ea2_uq UNIQUE (nosuch);
ALTER TABLE ea2_base ADD CONSTRAINT ea2_uq UNIQUE (b) DEFERRABLE INITIALLY DEFERRED;
INSERT INTO ea2_base VALUES (90, 'one', 0) ON CONFLICT (b) DO NOTHING;
ALTER TABLE ea2_base DROP CONSTRAINT ea2_uq;
ALTER TABLE ea2_base VALIDATE CONSTRAINT ea2_nosuchcon;
ALTER TABLE ea2_base ALTER CONSTRAINT ea2_nosuchcon DEFERRABLE;
DROP VIEW ea2_v;
DROP FUNCTION ea2_plain();
DROP FUNCTION ea2_tgf();
-- ==================================================== earm2:coerce2 =======
CREATE FUNCTION ea2_mr(m anymultirange) RETURNS anymultirange LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea2_mr2(r anyrange, m anymultirange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION ea2_cr(r anycompatiblerange, e anycompatible) RETURNS anycompatible LANGUAGE sql AS 'SELECT $2';
CREATE FUNCTION ea2_badpoly(x int) RETURNS anyelement LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea2_badpoly2(x int) RETURNS anyrange LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea2_badpoly3(x anycompatible) RETURNS anycompatiblerange LANGUAGE sql AS 'SELECT $1';
SELECT ea2_mr(1);
SELECT ea2_mr(NULL);
SELECT ea2_mr('[1,2]'::int4range);
SELECT ea2_mr2('[1,2]'::int4range, '{[1,2]}'::nummultirange);
SELECT ea2_cr('[1,2]'::int4range, 'abc');
SELECT ea2_cr(1, 2);
DROP FUNCTION ea2_mr(anymultirange);
DROP FUNCTION ea2_mr2(anyrange, anymultirange);
DROP FUNCTION ea2_cr(anycompatiblerange, anycompatible);
CREATE AGGREGATE ea2_badagg (anyelement) (sfunc = array_append, stype = int);
CREATE CAST (int AS int) WITH INOUT;
CREATE CAST (text AS varchar) WITH FUNCTION nosuchfunc(text);
CREATE CAST (int AS bigint) WITH FUNCTION abs(int);
CREATE CAST (int4 AS bool) WITH INOUT;
DROP CAST (int4 AS bool);
SELECT CAST(point '(1,1)' AS int);
SELECT CAST(ARRAY[1,2] AS point);
SELECT NULLIF(1, 'abc');
SELECT COALESCE(1, point '(1,1)');
SELECT greatest(1, 'abc', point '(1,1)');
SELECT CASE WHEN true THEN 1 ELSE point '(1,1)' END;
SELECT ARRAY[1, point '(1,1)'];
SELECT a IN (1, point '(1,1)') FROM ea2_base;
-- ==================================================== earm2:parser2 =======
SELECT U&'\D800';
SELECT U&'\DC00\D800';
SELECT U&'\+110000';
SELECT U&'d!0061t!+000061' UESCAPE '!!';
SELECT U&'d\0061t' UESCAPE 'a';
SELECT U&'d\0061t' UESCAPE '+';
SELECT U&'wrong: \db99\0061';
SELECT U&"\D800";
SELECT E'\uD800';
SELECT E'\uDC00\uD800';
SELECT E'\U00110000';
SELECT E'\xyz';
SELECT 123abc;
SELECT 0x;
SELECT 0b012;
SELECT 0o18;
SELECT 1_000_;
SELECT _1000;
SELECT 1__000;
SELECT 1.5e;
SELECT $2;
SELECT $0;
SELECT B'012';
SELECT X'GG';
SELECT 'a' 'b';
SELECT interval '1 day' second(20);
SELECT interval(20) '1 day';
SELECT time(20) '10:00';
SELECT timestamp(-1) '2020-01-01';
SELECT a COLLATE "C" COLLATE "POSIX" FROM ea2_base;
SELECT b COLLATE "ea2_nosuchcoll" FROM ea2_base;
SELECT a COLLATE "C" FROM ea2_base;
SELECT ROW(1, 2) = ROW(1, 2, 3);
SELECT ROW(1, 2) < ROW('a', 'b');
SELECT (1, 2) OVERLAPS (3, 4);
SELECT 1 IS DISTINCT FROM point '(1,1)';
SELECT 1 BETWEEN 'a' AND 2;
SELECT 1 NOTNULL ISNULL;
SELECT ((((((((((((((((((((((((((((((((((((((((1))))))))))))))))))))))))))))))))))))))));
-- ==================================================== earm2:async ========
NOTIFY ea2_chan;
NOTIFY ea2_chan, 'payload';
SELECT pg_notify('ea2_chan', 'payload');
SELECT pg_notify('', 'payload');
SELECT pg_notify(NULL, 'payload');
SELECT pg_notify('ea2_chan', repeat('x', 9000));
NOTIFY nosuch_channel_but_fine;
LISTEN ea2_chan;
UNLISTEN ea2_chan;
UNLISTEN *;
BEGIN;
LISTEN ea2_chan;
PREPARE TRANSACTION 'ea2_ptx';
ROLLBACK;
BEGIN;
NOTIFY ea2_chan;
PREPARE TRANSACTION 'ea2_ptx';
ROLLBACK;
UNLISTEN *;
-- ==================================================== earm2:collenc ======
CREATE COLLATION ea2_coll ();
CREATE COLLATION ea2_coll (locale = 'C', lc_collate = 'C');
CREATE COLLATION ea2_coll (provider = 'nosuch', locale = 'C');
CREATE COLLATION ea2_coll (provider = 'libc', locale = 'C', deterministic = false);
CREATE COLLATION ea2_coll (locale = 'ea2_nosuchlocale.UTF-8@bogus');
CREATE COLLATION ea2_coll FROM nosuchcoll;
CREATE COLLATION ea2_coll (version = '1.0', locale = 'C');
CREATE COLLATION ea2_coll (deterministic = false);
CREATE COLLATION ea2_coll (locale = 'C', nosuchopt = 'x');
SELECT convert('abc', 'UTF8', 'ea2_nosuchenc');
SELECT convert('abc', 'ea2_nosuchenc', 'UTF8');
SELECT convert_from('\xff'::bytea, 'UTF8');
SELECT convert_to('abc', 'ea2_nosuchenc');
SELECT convert('abc'::bytea, 'UTF8', 'EUC_JP');
SELECT convert(E'\\xe4\\xb8\\xad'::bytea, 'UTF8', 'LATIN1');
SELECT convert_from(E'\\xc3'::bytea, 'UTF8');
SELECT length(convert_from(convert_to('abc', 'LATIN1'), 'LATIN1'));
CREATE CONVERSION ea2_conv FOR 'UTF8' TO 'LATIN1' FROM nosuchfunc;
CREATE CONVERSION ea2_conv FOR 'nosuchenc' TO 'LATIN1' FROM utf8_to_iso8859_1;
CREATE CONVERSION ea2_conv FOR 'UTF8' TO 'nosuchenc' FROM utf8_to_iso8859_1;
CREATE CONVERSION ea2_conv FOR 'LATIN1' TO 'UTF8' FROM utf8_to_iso8859_1;
CREATE DEFAULT CONVERSION ea2_conv2 FOR 'UTF8' TO 'LATIN1' FROM utf8_to_iso8859_1;
DROP CONVERSION ea2_conv2;
DROP CONVERSION IF EXISTS ea2_conv;
SET client_encoding = 'ea2_nosuchenc';
SET client_encoding = 'SQL_ASCII';
RESET client_encoding;
SELECT 'a' < ('b' COLLATE "C") COLLATE "POSIX";
SELECT b || (b COLLATE "C") < b || (b COLLATE "POSIX") FROM ea2_base;
CREATE TABLE ea2_collbad (x int COLLATE "C");
CREATE TABLE ea2_collbad (x text COLLATE "ea2_nosuchcoll");
-- ==================================================== earm2:alter2 =======
ALTER TABLE ea2_nosuch RENAME TO x;
ALTER TABLE IF EXISTS ea2_nosuch RENAME TO x;
ALTER TABLE ea2_base RENAME TO ea2_ref;
ALTER TABLE ea2_base RENAME COLUMN a TO b;
ALTER TABLE ea2_base RENAME COLUMN nosuch TO b2;
ALTER TABLE ea2_base RENAME COLUMN xmin TO b2;
ALTER TABLE ea2_base RENAME CONSTRAINT nosuchcon TO x;
ALTER INDEX ea2_nosuchidx RENAME TO x;
ALTER VIEW ea2_base RENAME TO x;
ALTER SEQUENCE ea2_base RESTART;
ALTER TYPE ea2_nosuchtype RENAME TO x;
ALTER TYPE ea2_nosuchtype OWNER TO postgres;
CREATE TYPE ea2_ren AS (p int);
ALTER TYPE ea2_ren RENAME TO ea2_ren;
ALTER TYPE ea2_ren RENAME ATTRIBUTE nosuch TO q;
ALTER TYPE ea2_ren RENAME ATTRIBUTE p TO p;
ALTER TYPE ea2_ren DROP ATTRIBUTE nosuch;
ALTER TYPE ea2_ren DROP ATTRIBUTE IF EXISTS nosuch;
ALTER TYPE ea2_ren ADD ATTRIBUTE p int;
ALTER TYPE ea2_ren ALTER ATTRIBUTE nosuch TYPE int;
DROP TYPE ea2_ren;
ALTER TABLE ea2_base SET (nosuchopt = 1);
ALTER TABLE ea2_base SET (fillfactor = 0);
ALTER TABLE ea2_base SET (fillfactor = 101);
ALTER TABLE ea2_base SET (autovacuum_enabled = maybe);
ALTER TABLE ea2_base RESET (nosuchopt);
ALTER TABLE ea2_base SET (toast.autovacuum_enabled = false);
ALTER TABLE ea2_base SET (parallel_workers = -2);
CREATE INDEX ea2_ffi ON ea2_base (a) WITH (fillfactor = 5);
CREATE INDEX ea2_ffi2 ON ea2_base (a) WITH (nosuchopt = 5);
DROP INDEX ea2_ffi;
ALTER MATERIALIZED VIEW ea2_nosuchmv SET SCHEMA public;
ALTER FUNCTION abs(int) SET SCHEMA ea2_nosuchschema;
ALTER AGGREGATE sum(int) SET SCHEMA ea2_nosuchschema;
-- ============================================================ teardown ====
DROP TABLE ea2_ref;
DROP TABLE ea2_base;
