-- LD6 ERROR-ARM hand-verify deck. One statement per line (diffrunner --replay
-- compatible). Every probe is deliberately invalid unless marked FIXTURE.
-- Families keyed to line-drain-queue.tsv ERROR-ARM chunk functions.
-- FIXTURE section ------------------------------------------------------------
CREATE TABLE ea_base (a int PRIMARY KEY, b text, c numeric(10,2));
INSERT INTO ea_base VALUES (1, 'one', 1.10), (2, 'two', 2.20);
CREATE TABLE ea_ref (x int, y int);
INSERT INTO ea_ref VALUES (1, 1), (NULL, 2), (1, 3);
CREATE TABLE ea_reftext (tx text);
CREATE VIEW ea_v AS SELECT a, b FROM ea_base;
CREATE SEQUENCE ea_seq;
CREATE MATERIALIZED VIEW ea_mv AS SELECT 1 AS m;
CREATE TYPE ea_comp AS (p int, q text);
CREATE TYPE ea_enum AS ENUM ('r','g','b');
CREATE DOMAIN ea_dom AS int CHECK (VALUE > 0);
CREATE ROLE ea_nobody;
CREATE ROLE ea_owner;
CREATE SCHEMA ea_s;
REVOKE ALL ON SCHEMA ea_s FROM PUBLIC;
CREATE FUNCTION ea_f(int) RETURNS int LANGUAGE sql AS 'SELECT $1';
REVOKE ALL ON FUNCTION ea_f(int) FROM PUBLIC;
CREATE FUNCTION ea_any(x anyelement, y anyelement) RETURNS anyelement LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea_anyarr(x anyarray, y anyelement) RETURNS anyelement LANGUAGE sql AS 'SELECT $2';
CREATE FUNCTION ea_rec() RETURNS record LANGUAGE sql AS $$SELECT 1 AS r1, 'x'::text AS r2$$;
CREATE TABLE ea_part (id int, ts date) PARTITION BY RANGE (ts);
CREATE TABLE ea_p1 PARTITION OF ea_part FOR VALUES FROM ('2020-01-01') TO ('2021-01-01');
CREATE TABLE ea_dup (d int);
INSERT INTO ea_dup VALUES (1), (1);
REVOKE ALL ON ea_base, ea_seq FROM PUBLIC;
-- family:typmod — bad type modifiers ----------------------------------------
CREATE TABLE ea_bad (v varchar(0));
CREATE TABLE ea_bad (v char(0));
CREATE TABLE ea_bad (v bit(0));
CREATE TABLE ea_bad (v numeric(0));
CREATE TABLE ea_bad (v numeric(1001));
CREATE TABLE ea_bad (v numeric(5,2000));
CREATE TABLE ea_bad (v text(5));
CREATE TABLE ea_bad (v int(4));
CREATE TABLE ea_bad (v varchar(10485761));
SELECT 'x'::varchar(0);
SELECT 1.5::numeric(2000,5);
SELECT '10:00'::time(-1);
-- family:dropmissing — DROP ... IF EXISTS notices + hard 42704/42P01 --------
DROP TABLE ea_nosuch;
DROP TABLE IF EXISTS ea_nosuch;
DROP TABLE IF EXISTS ea_noschema.t;
DROP VIEW ea_nosuch;
DROP VIEW IF EXISTS ea_nosuch;
DROP MATERIALIZED VIEW ea_nosuch;
DROP MATERIALIZED VIEW IF EXISTS ea_nosuch;
DROP INDEX ea_nosuch;
DROP INDEX IF EXISTS ea_nosuch;
DROP SEQUENCE ea_nosuch;
DROP SEQUENCE IF EXISTS ea_nosuch;
DROP TYPE ea_nosuch;
DROP TYPE IF EXISTS ea_nosuch;
DROP TYPE IF EXISTS ea_noschema.t;
DROP DOMAIN ea_nosuch;
DROP DOMAIN IF EXISTS ea_nosuch;
DROP COLLATION ea_nosuch;
DROP COLLATION IF EXISTS ea_nosuch;
DROP CONVERSION ea_nosuch;
DROP CONVERSION IF EXISTS ea_nosuch;
DROP SCHEMA ea_nosuch;
DROP SCHEMA IF EXISTS ea_nosuch;
DROP EXTENSION ea_nosuch;
DROP EXTENSION IF EXISTS ea_nosuch;
DROP FUNCTION ea_nosuch(int);
DROP FUNCTION IF EXISTS ea_nosuch(int);
DROP FUNCTION IF EXISTS ea_nosuch(ea_nosuchtype);
DROP PROCEDURE ea_nosuch(int);
DROP PROCEDURE IF EXISTS ea_nosuch(int);
DROP ROUTINE ea_nosuch(int);
DROP ROUTINE IF EXISTS ea_nosuch(int);
DROP AGGREGATE ea_nosuch(int);
DROP AGGREGATE IF EXISTS ea_nosuch(int);
DROP OPERATOR ### (int, int);
DROP OPERATOR IF EXISTS ### (int, int);
DROP OPERATOR IF EXISTS ### (ea_nosuchtype, int);
DROP OPERATOR CLASS ea_nosuch USING btree;
DROP OPERATOR CLASS IF EXISTS ea_nosuch USING btree;
DROP OPERATOR CLASS IF EXISTS ea_nosuch USING ea_nosucham;
DROP OPERATOR FAMILY ea_nosuch USING btree;
DROP OPERATOR FAMILY IF EXISTS ea_nosuch USING btree;
DROP LANGUAGE ea_nosuch;
DROP LANGUAGE IF EXISTS ea_nosuch;
DROP CAST (text AS point);
DROP CAST IF EXISTS (text AS point);
DROP CAST IF EXISTS (ea_nosuchtype AS point);
DROP TRIGGER ea_nosuch ON ea_base;
DROP TRIGGER IF EXISTS ea_nosuch ON ea_base;
DROP TRIGGER IF EXISTS ea_nosuch ON ea_nosuchtab;
DROP RULE ea_nosuch ON ea_base;
DROP RULE IF EXISTS ea_nosuch ON ea_base;
DROP RULE IF EXISTS ea_nosuch ON ea_nosuchtab;
DROP POLICY ea_nosuch ON ea_base;
DROP POLICY IF EXISTS ea_nosuch ON ea_base;
DROP POLICY IF EXISTS ea_nosuch ON ea_nosuchtab;
DROP EVENT TRIGGER ea_nosuch;
DROP EVENT TRIGGER IF EXISTS ea_nosuch;
DROP PUBLICATION ea_nosuch;
DROP PUBLICATION IF EXISTS ea_nosuch;
DROP STATISTICS ea_nosuch;
DROP STATISTICS IF EXISTS ea_nosuch;
DROP TEXT SEARCH PARSER ea_nosuch;
DROP TEXT SEARCH PARSER IF EXISTS ea_nosuch;
DROP TEXT SEARCH DICTIONARY ea_nosuch;
DROP TEXT SEARCH DICTIONARY IF EXISTS ea_nosuch;
DROP TEXT SEARCH TEMPLATE ea_nosuch;
DROP TEXT SEARCH TEMPLATE IF EXISTS ea_nosuch;
DROP TEXT SEARCH CONFIGURATION ea_nosuch;
DROP TEXT SEARCH CONFIGURATION IF EXISTS ea_nosuch;
DROP SERVER ea_nosuch;
DROP SERVER IF EXISTS ea_nosuch;
DROP FOREIGN DATA WRAPPER ea_nosuch;
DROP FOREIGN DATA WRAPPER IF EXISTS ea_nosuch;
DROP FOREIGN TABLE ea_nosuch;
DROP FOREIGN TABLE IF EXISTS ea_nosuch;
DROP ACCESS METHOD ea_nosuch;
DROP ACCESS METHOD IF EXISTS ea_nosuch;
DROP TRANSFORM FOR int LANGUAGE ea_nosuch;
DROP TRANSFORM IF EXISTS FOR int LANGUAGE ea_nosuch;
DROP TRANSFORM IF EXISTS FOR ea_nosuchtype LANGUAGE plpgsql;
DROP DATABASE ea_nosuch;
DROP DATABASE IF EXISTS ea_nosuch;
DROP ROLE ea_nosuch;
DROP ROLE IF EXISTS ea_nosuch;
DROP TABLESPACE ea_nosuch;
DROP TABLESPACE IF EXISTS ea_nosuch;
DROP SUBSCRIPTION IF EXISTS ea_nosuch;
-- family:acl — permission denied / must-be-owner per object type ------------
SET ROLE ea_nobody;
SELECT a FROM ea_base;
INSERT INTO ea_base VALUES (99, 'no', 0);
UPDATE ea_base SET b = 'no';
DELETE FROM ea_base;
TRUNCATE ea_base;
LOCK TABLE ea_base IN ACCESS EXCLUSIVE MODE;
SELECT nextval('ea_seq');
SELECT currval('ea_seq');
SELECT setval('ea_seq', 5);
SELECT ea_f(1);
CREATE TABLE ea_s.deny (z int);
CREATE SCHEMA ea_denied;
ALTER TABLE ea_base ADD COLUMN z int;
ALTER SEQUENCE ea_seq RESTART;
ALTER VIEW ea_v RENAME TO ea_v2;
ALTER MATERIALIZED VIEW ea_mv RENAME TO ea_mv2;
ALTER TYPE ea_comp ADD ATTRIBUTE r int;
ALTER DOMAIN ea_dom ADD CHECK (VALUE < 100);
ALTER FUNCTION ea_f(int) RENAME TO ea_f2;
ALTER SCHEMA ea_s RENAME TO ea_s2;
DROP TABLE ea_base;
DROP VIEW ea_v;
DROP SEQUENCE ea_seq;
DROP TYPE ea_comp;
DROP FUNCTION ea_f(int);
DROP SCHEMA ea_s;
COMMENT ON TABLE ea_base IS 'nope';
COMMENT ON FUNCTION ea_f(int) IS 'nope';
COMMENT ON TYPE ea_comp IS 'nope';
COMMENT ON SCHEMA ea_s IS 'nope';
COMMENT ON SEQUENCE ea_seq IS 'nope';
GRANT SELECT ON ea_base TO ea_owner;
CREATE INDEX ea_deny_idx ON ea_base (a);
ALTER ROLE ea_owner NOLOGIN;
CREATE ROLE ea_sneak;
DROP ROLE ea_owner;
RESET ROLE;
-- family:role — CreateRole/AlterRole arms -----------------------------------
CREATE ROLE ea_nobody;
CREATE ROLE pg_ea_reserved;
CREATE ROLE "none";
ALTER ROLE ea_nosuchrole LOGIN;
ALTER ROLE pg_read_all_data LOGIN;
DROP ROLE current_user;
GRANT ea_owner TO ea_owner;
GRANT ea_nosuchrole TO ea_nobody;
GRANT ea_nobody TO ea_nosuchrole;
SET ROLE ea_nosuchrole;
CREATE ROLE ea_badconn CONNECTION LIMIT -2;
CREATE ROLE ea_dupopt LOGIN LOGIN;
CREATE USER MAPPING FOR ea_nosuchrole SERVER ea_nosuch;
REVOKE ea_owner FROM ea_nosuchrole;
-- family:seq — init_params arms ---------------------------------------------
CREATE SEQUENCE ea_s0 INCREMENT 0;
CREATE SEQUENCE ea_s1 MINVALUE 10 MAXVALUE 5;
CREATE SEQUENCE ea_s2 START 100 MAXVALUE 50;
CREATE SEQUENCE ea_s3 START 0 MINVALUE 5;
CREATE SEQUENCE ea_s4 AS text;
CREATE SEQUENCE ea_s5 AS smallint MAXVALUE 100000;
CREATE SEQUENCE ea_s6 AS smallint MINVALUE -100000;
CREATE SEQUENCE ea_s7 CACHE 0;
CREATE SEQUENCE ea_s8 AS numeric;
ALTER SEQUENCE ea_seq RESTART WITH 0 MINVALUE 1;
ALTER SEQUENCE ea_seq MAXVALUE 5 RESTART WITH 10;
SELECT setval('ea_seq', 0);
CREATE TEMP SEQUENCE ea_s9 INCREMENT 0;
-- family:defidx — DefineIndex/ComputeIndexAttrs/transformIndexConstraint ----
CREATE UNIQUE INDEX ea_bad_idx ON ea_base USING hash (a);
CREATE UNIQUE INDEX ea_bad_idx ON ea_base USING gin (b);
CREATE INDEX ea_bad_idx ON ea_base USING gin (b DESC);
CREATE INDEX ea_bad_idx ON ea_base USING gin (b NULLS FIRST);
CREATE INDEX ea_bad_idx ON ea_base USING brin (a) INCLUDE (b);
CREATE INDEX ea_bad_idx ON ea_base (b ea_nosuch_ops);
CREATE INDEX ea_bad_idx ON ea_base (b int4_ops);
CREATE INDEX ea_bad_idx ON ea_base USING gin (a);
CREATE INDEX ea_bad_idx ON ea_v (a);
CREATE INDEX ea_bad_idx ON ea_seq (last_value);
CREATE INDEX ea_bad_idx ON ea_base (ctid);
CREATE INDEX ea_bad_idx ON ea_base ((generate_series(1, a)));
CREATE INDEX ea_bad_idx ON ea_base (a) WHERE (SELECT true);
CREATE INDEX ea_bad_idx ON ea_base ((random() > 0.5));
CREATE INDEX ea_bad_idx ON ea_base (a COLLATE "C");
CREATE UNIQUE INDEX ea_bad_idx ON ea_part (id);
CREATE INDEX CONCURRENTLY ea_bad_idx ON ea_part (id);
CREATE INDEX ea_bad_idx ON ea_base USING ea_nosucham (a);
CREATE INDEX ea_bad_idx ON ea_nosuchtab (a);
CREATE UNIQUE INDEX ea_nonuniq_helper ON ea_ref (x, y);
CREATE INDEX ea_expr_helper ON ea_base (((a + 0)));
ALTER TABLE ea_base ADD PRIMARY KEY USING INDEX ea_expr_helper;
ALTER TABLE ea_ref ADD PRIMARY KEY USING INDEX ea_nonuniq_helper;
ALTER TABLE ea_base ADD CONSTRAINT ea_uniq_dup UNIQUE USING INDEX ea_nosuchidx;
ALTER TABLE ea_part ADD CONSTRAINT ea_excl EXCLUDE USING gist (id WITH =);
ALTER TABLE ea_base ADD UNIQUE (nosuchcol);
ALTER TABLE ea_base ADD PRIMARY KEY (a);
DROP INDEX ea_expr_helper;
DROP INDEX ea_nonuniq_helper;
-- family:defagg — DefineAggregate/AggregateCreate ---------------------------
CREATE AGGREGATE ea_a0 (int) (STYPE = int);
CREATE AGGREGATE ea_a1 (int) (SFUNC = int4pl);
CREATE AGGREGATE ea_a2 (int) (SFUNC = ea_nosuchfn, STYPE = int);
CREATE AGGREGATE ea_a3 (int) (SFUNC = int4pl, STYPE = point);
CREATE AGGREGATE ea_a4 (int) (SFUNC = int4pl, STYPE = int, FINALFUNC = ea_nosuchfn);
CREATE AGGREGATE ea_a5 (int) (SFUNC = int4pl, STYPE = int, SORTOP = ###);
CREATE AGGREGATE ea_a6 (int) (SFUNC = int4pl, STYPE = int, PARALLEL = bogus);
CREATE AGGREGATE ea_a7 (int) (SFUNC = int4pl, STYPE = int, FINALFUNC_MODIFY = bogus);
CREATE AGGREGATE ea_a8 (int) (SFUNC = int4pl, STYPE = int, MSFUNC = int4pl);
CREATE AGGREGATE ea_a9 (int) (SFUNC = int4pl, STYPE = int, MSTYPE = int);
CREATE AGGREGATE ea_a10 (int) (SFUNC = int4pl, STYPE = int, MSTYPE = int, MSFUNC = int4pl);
CREATE AGGREGATE ea_a11 (int) (SFUNC = int4pl, STYPE = int, SERIALFUNC = numeric_avg_serialize);
CREATE AGGREGATE ea_a12 (int) (SFUNC = int4pl, STYPE = int, HYPOTHETICAL);
CREATE AGGREGATE ea_a13 (int) (SFUNC = int4pl, STYPE = int, INITCOND = 'notanint');
CREATE AGGREGATE ea_a14 (*) (SFUNC = int4pl, STYPE = int);
CREATE AGGREGATE ea_a15 (int ORDER BY int) (SFUNC = int4pl, STYPE = int, SORTOP = >);
CREATE AGGREGATE ea_a16 (int) (SFUNC = int4larger, STYPE = int, SORTOP = ea_nosuchop);
CREATE AGGREGATE ea_a17 (text) (SFUNC = textcat, STYPE = text, COMBINEFUNC = int4pl);
CREATE AGGREGATE ea_a18 (int) (SFUNC = int4pl, STYPE = int, MSTYPE = int, MSFUNC = int4pl, MINVFUNC = int4mi, MFINALFUNC = ea_nosuchfn);
-- family:deftype — DefineType/DefineDomain/typecmds -------------------------
CREATE TYPE ea_t1 (INPUT = ea_nosuch_in, OUTPUT = ea_nosuch_out);
CREATE TYPE ea_t2 (INPUT = int4in);
CREATE TYPE ea_t3 (INPUT = int4in, OUTPUT = int4out, INTERNALLENGTH = -3);
CREATE TYPE ea_t4 (INPUT = int4in, OUTPUT = int4out, ALIGNMENT = wonky);
CREATE TYPE ea_t5 (INPUT = int4in, OUTPUT = int4out, STORAGE = bogus);
CREATE TYPE ea_t6 (INPUT = int4in, OUTPUT = int4out, CATEGORY = 'xx');
CREATE TYPE ea_comp;
CREATE TYPE ea_r1 AS RANGE (SUBTYPE = ea_comp);
CREATE TYPE ea_r2 AS RANGE (COLLATION = "C");
CREATE TYPE ea_r3 AS RANGE (SUBTYPE = int, COLLATION = "C");
CREATE TYPE ea_r4 AS RANGE (SUBTYPE = int, SUBTYPE_OPCLASS = text_ops);
CREATE TYPE ea_r5 AS RANGE (SUBTYPE = int, MULTIRANGE_TYPE_NAME = ea_comp);
CREATE TYPE ea_e2 AS ENUM ('a', 'a');
CREATE DOMAIN ea_d1 AS int NOT NULL NULL;
CREATE DOMAIN ea_d2 AS int DEFAULT 1 DEFAULT 2;
CREATE DOMAIN ea_d3 AS int PRIMARY KEY;
CREATE DOMAIN ea_d4 AS int UNIQUE;
CREATE DOMAIN ea_d5 AS int REFERENCES ea_base;
CREATE DOMAIN ea_d6 AS ea_nosuchtype;
ALTER TYPE ea_enum ADD VALUE 'r';
ALTER TYPE ea_enum ADD VALUE 'x' BEFORE 'nosuch';
ALTER TYPE ea_enum RENAME VALUE 'r' TO 'g';
ALTER TYPE ea_enum RENAME VALUE 'nosuch' TO 'z';
ALTER TYPE ea_comp DROP ATTRIBUTE nosuch;
ALTER TYPE ea_comp DROP ATTRIBUTE IF EXISTS nosuch;
ALTER TYPE ea_enum ADD ATTRIBUTE z int;
ALTER TYPE ea_comp ADD ATTRIBUTE p int;
ALTER DOMAIN ea_dom DROP CONSTRAINT ea_nosuch;
ALTER DOMAIN ea_dom DROP CONSTRAINT IF EXISTS ea_nosuch;
ALTER DOMAIN ea_dom ADD PRIMARY KEY;
ALTER TYPE ea_dom ADD ATTRIBUTE z int;
ALTER TYPE ea_comp RENAME ATTRIBUTE nosuch TO other;
-- family:coerce — enforce_generic_type_consistency / polymorphism -----------
SELECT ea_any(1, 'x'::text);
SELECT ea_any('a', 'b');
SELECT ea_anyarr(ARRAY[1], 'x'::text);
SELECT ea_anyarr(1, 2);
SELECT ea_anyarr('{1}', '{2}');
SELECT array_append(ARRAY[1], 'x'::text);
SELECT array_cat(ARRAY[1], ARRAY['x'::text]);
SELECT ea_f('nope');
SELECT ea_f(1, 2);
SELECT ea_nosuchfn(1);
SELECT nosuchagg(a) FROM ea_base;
-- family:colref — transformColumnRef/expandRTE/ParseFuncOrColumn ------------
SELECT nosuchcol FROM ea_base;
SELECT ea_base.nosuchcol FROM ea_base;
SELECT missingalias.a FROM ea_base;
SELECT missingtab.* FROM ea_base;
SELECT a FROM ea_base e1, ea_base e2;
SELECT * FROM ea_base, ea_base;
SELECT ea_base.b FROM ea_base e1;
SELECT e.a.b FROM ea_base e;
SELECT * FROM ea_rec();
SELECT * FROM ea_rec() AS t(r1 int, r2 text, r3 int);
SELECT * FROM ea_f(1) AS t(f1 int, f2 int);
SELECT * FROM generate_series(1, 3) AS g(a int, b int);
SELECT (e).nosuchfield FROM ea_base e;
SELECT (ROW(1,2)).nosuchfield;
-- family:aggplace — check_agglevels_and_constraints / parse_agg -------------
SELECT count(*) FROM ea_base WHERE count(a) > 0;
SELECT a FROM ea_base GROUP BY count(a);
SELECT count(a) FROM ea_base GROUP BY 1;
SELECT sum(count(a)) FROM ea_base;
SELECT a FROM ea_base HAVING a > 0;
CREATE TABLE ea_bad (x int CHECK (sum(x) > 0));
CREATE INDEX ea_bad_idx ON ea_base ((sum(a)));
UPDATE ea_base SET a = count(*);
DELETE FROM ea_base WHERE sum(a) > 0;
INSERT INTO ea_ref VALUES (count(1), 2);
SELECT generate_series(1, count(a)) FROM ea_base;
SELECT count(rank() OVER ()) FROM ea_base;
SELECT rank() OVER (ORDER BY count(a)) FROM ea_base;
SELECT a, rank() OVER () FROM ea_base WHERE rank() OVER () = 1;
SELECT a FROM ea_base GROUP BY rank() OVER ();
SELECT rank() OVER (), sum(rank() OVER ()) FROM ea_base;
SELECT lag(a) FROM ea_base;
SELECT count(*) FILTER (WHERE rank() OVER () = 1) FROM ea_base;
SELECT rank(a) WITHIN GROUP (ORDER BY a) OVER () FROM ea_base;
-- family:srf — check_srf_call_placement -------------------------------------
SELECT 1 FROM ea_base WHERE generate_series(1, 2) = 1;
SELECT CASE WHEN a > 0 THEN generate_series(1, 2) END FROM ea_base;
SELECT COALESCE(generate_series(1, 2), a) FROM ea_base;
UPDATE ea_base SET a = generate_series(1, 2);
SELECT 1 LIMIT generate_series(1, 2);
SELECT 1 OFFSET generate_series(1, 2);
SELECT sum(generate_series(1, 2)) OVER () FROM ea_base;
SELECT count(generate_series(1, 2)) FROM ea_base;
SELECT a FROM ea_base HAVING generate_series(1, 2) > 0;
VALUES (generate_series(1, 2));
SELECT generate_series(1, generate_series(1, 2));
INSERT INTO ea_ref VALUES (1, 2) RETURNING generate_series(1, x);
-- family:cte — checkWellFormedRecursionWalker -------------------------------
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM r WHERE EXISTS (SELECT * FROM r)) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT n FROM r EXCEPT SELECT n FROM r) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT r1.n FROM r r1, r r2) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT b.a FROM ea_base b LEFT JOIN r ON true) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT n FROM r UNION ALL SELECT 1) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n INTERSECT SELECT n FROM r) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION SELECT sum(n) FROM r) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT sum(n)::int FROM r) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT n FROM r ORDER BY n) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT n FROM r LIMIT 5) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT n FROM r FOR UPDATE) SELECT * FROM r;
WITH RECURSIVE r AS (SELECT 1 AS n UNION ALL SELECT lateral_ref.n + 1 FROM LATERAL (SELECT n FROM r) lateral_ref WHERE lateral_ref.n < 3) SELECT count(*) FROM r;
WITH r AS (SELECT 1 AS n), r AS (SELECT 2 AS n) SELECT * FROM r;
WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM r) SEARCH DEPTH FIRST BY nosuch SET pathcol SELECT * FROM r;
WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM r) CYCLE nosuch SET is_cycle USING path SELECT * FROM r;
WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM r) CYCLE n SET is_cycle TO 1 DEFAULT 0 USING n SELECT * FROM r;
-- family:altable — ALTER TABLE ATPrepCmd/ATExecCmd/MergeAttributes ----------
ALTER TABLE ea_v ADD COLUMN z int;
ALTER TABLE ea_seq ADD COLUMN z int;
ALTER TABLE ea_mv ADD COLUMN z int;
ALTER TABLE ea_nosuchtab ADD COLUMN z int;
ALTER TABLE IF EXISTS ea_nosuchtab ADD COLUMN z int;
ALTER TABLE ea_base DROP COLUMN nosuch;
ALTER TABLE ea_base DROP COLUMN IF EXISTS nosuch;
ALTER TABLE ea_base ADD COLUMN a int;
ALTER TABLE ea_base ADD COLUMN IF NOT EXISTS a int;
ALTER TABLE ea_base ALTER COLUMN a TYPE point;
ALTER TABLE ea_base ALTER COLUMN a TYPE varchar(0);
ALTER TABLE ea_base ALTER COLUMN nosuch TYPE int;
ALTER TABLE ea_base ALTER COLUMN a SET DEFAULT random() * nosuchcol;
ALTER TABLE ea_ref ALTER COLUMN x SET NOT NULL;
ALTER TABLE ea_ref ADD CONSTRAINT ea_chk CHECK (x > 100);
ALTER TABLE ea_dup ADD CONSTRAINT ea_uni UNIQUE (d);
ALTER TABLE ea_base DROP CONSTRAINT nosuch;
ALTER TABLE ea_base DROP CONSTRAINT IF EXISTS nosuch;
ALTER TABLE ea_base INHERIT ea_base;
ALTER TABLE ea_base INHERIT ea_v;
ALTER TABLE ea_base INHERIT ea_part;
ALTER TABLE ea_ref INHERIT ea_base;
CREATE TABLE ea_child (a text) INHERITS (ea_base);
CREATE TABLE ea_child () INHERITS (ea_v);
CREATE TABLE ea_child () INHERITS (ea_part);
CREATE TABLE ea_child () INHERITS (ea_base, ea_base);
ALTER TABLE ea_base ALTER COLUMN b ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE ea_base ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE ea_base ALTER COLUMN a DROP IDENTITY;
ALTER TABLE ea_base ALTER COLUMN a DROP IDENTITY IF EXISTS;
ALTER TABLE ea_base ALTER COLUMN a DROP EXPRESSION;
ALTER TABLE ea_base ALTER COLUMN a DROP EXPRESSION IF EXISTS;
ALTER TABLE ea_base SET (fillfactor = 0);
ALTER TABLE ea_base SET (ea_bogus_option = 1);
ALTER TABLE ea_base SET TABLESPACE ea_nosuch;
ALTER TABLE ea_base SET SCHEMA ea_nosuchschema;
ALTER TABLE ea_base ALTER COLUMN a SET STATISTICS 20000;
ALTER TABLE ea_base ALTER COLUMN a SET STATISTICS -5;
ALTER TABLE ea_base ALTER COLUMN b SET STORAGE bogus;
ALTER TABLE ea_base ALTER COLUMN a SET COMPRESSION bogus;
ALTER TABLE ea_base OF ea_comp;
ALTER TABLE ea_base NOT OF;
ALTER TABLE ea_part ALTER COLUMN ts TYPE text;
ALTER TABLE ea_part DROP COLUMN ts;
ALTER TABLE ONLY ea_part ADD COLUMN extra int;
ALTER TABLE ONLY ea_part ADD CONSTRAINT ea_pchk CHECK (id > 0) NO INHERIT;
ALTER TABLE ea_part ATTACH PARTITION ea_ref FOR VALUES FROM ('2022-01-01') TO ('2023-01-01');
ALTER TABLE ea_part ATTACH PARTITION ea_v FOR VALUES FROM ('2022-01-01') TO ('2023-01-01');
ALTER TABLE ea_part ATTACH PARTITION ea_p1 FOR VALUES FROM ('2022-01-01') TO ('2023-01-01');
CREATE TABLE ea_p2 (id int, ts date);
ALTER TABLE ea_part ATTACH PARTITION ea_p2 FOR VALUES FROM ('2020-06-01') TO ('2020-09-01');
ALTER TABLE ea_part DETACH PARTITION ea_p2;
ALTER TABLE ea_part DETACH PARTITION ea_nosuchpart;
ALTER TABLE ea_base DETACH PARTITION ea_ref;
ALTER TABLE ea_part ATTACH PARTITION ea_part FOR VALUES FROM ('2022-01-01') TO ('2023-01-01');
DROP TABLE ea_p2;
ALTER TABLE ea_p1 RENAME TO ea_p1;
ALTER TABLE ea_base RENAME COLUMN a TO b;
ALTER TABLE ea_base RENAME COLUMN nosuch TO z;
ALTER TABLE ea_base RENAME CONSTRAINT nosuch TO z;
ALTER TABLE ea_base REPLICA IDENTITY USING INDEX ea_nosuchidx;
ALTER TABLE ea_base CLUSTER ON ea_nosuchidx;
ALTER TABLE ea_base SET WITHOUT OIDS;
ALTER TABLE ea_base ENABLE TRIGGER ea_nosuchtrig;
ALTER TABLE ea_base DISABLE TRIGGER ea_nosuchtrig;
ALTER TABLE ea_base VALIDATE CONSTRAINT ea_nosuchcon;
ALTER TABLE ea_base FORCE ROW LEVEL SECURITY;
ALTER TABLE ea_v ENABLE ROW LEVEL SECURITY;
-- family:fk — ATAddForeignKeyConstraint / CloneFk* --------------------------
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_nosuchtab;
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_base (b);
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_v;
ALTER TABLE ea_ref ADD FOREIGN KEY (nosuchcol) REFERENCES ea_base;
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_base (nosuchcol);
ALTER TABLE ea_reftext ADD FOREIGN KEY (tx) REFERENCES ea_base (a);
ALTER TABLE ea_ref ADD FOREIGN KEY (x, y) REFERENCES ea_base (a);
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_base (a) MATCH PARTIAL;
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_base (a) ON DELETE SET NULL (y);
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_base (a) ON DELETE SET DEFAULT (nosuchcol);
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_base (a);
ALTER TABLE ea_ref DROP CONSTRAINT ea_ref_x_fkey;
ALTER TABLE ea_ref ADD FOREIGN KEY (x) REFERENCES ea_seq;
-- family:stats — CreateStatistics -------------------------------------------
CREATE STATISTICS ea_st ON a FROM ea_base;
CREATE STATISTICS ea_st ON a, a FROM ea_base;
CREATE STATISTICS ea_st ON a, nosuch FROM ea_base;
CREATE STATISTICS ea_st ON a, b FROM ea_base, ea_ref;
CREATE STATISTICS ea_st ON ctid, a FROM ea_base;
CREATE STATISTICS ea_st (bogus_kind) ON a, b FROM ea_base;
CREATE STATISTICS ea_st ON a, b FROM ea_v;
CREATE STATISTICS ea_st ON a, b FROM ea_nosuchtab;
CREATE STATISTICS ea_st ON x, y FROM ea_ref;
CREATE STATISTICS ea_st ON x, y FROM ea_ref;
CREATE STATISTICS IF NOT EXISTS ea_st ON x, y FROM ea_ref;
DROP STATISTICS ea_st;
-- family:coll — DefineCollation + variable.c GUC check hooks ----------------
CREATE COLLATION ea_c1 (lc_collate = 'C');
CREATE COLLATION ea_c2 ();
CREATE COLLATION ea_c3 (locale = 'C', lc_collate = 'C');
CREATE COLLATION ea_c4 (provider = 'bogus', locale = 'C');
CREATE COLLATION ea_c5 (provider = 'icu', locale = 'en');
CREATE COLLATION ea_c6 FROM ea_nosuchcoll;
CREATE COLLATION ea_c7 (locale = 'C', deterministic = false);
CREATE COLLATION "C" FROM "C";
CREATE COLLATION ea_c8 (locale = 'C', version = '99');
SET datestyle = 'bogus';
SET datestyle = 'ISO, MDY, DMY';
SET datestyle = 'SQL, ISO';
SET timezone = 'Bogus/Zone';
SET TIME ZONE INTERVAL '25:00' HOUR TO MINUTE;
SET client_encoding = 'BOGUS_ENC';
SET transaction_isolation = 'bogus';
SET seq_page_cost = -1;
SET work_mem = '10kB';
SET default_transaction_isolation = 'nope';
SET search_path = ea_nosuchschema;
SELECT set_config('datestyle', 'nonsense', false);
-- family:opclass — opclasscmds ----------------------------------------------
CREATE OPERATOR CLASS ea_oc1 FOR TYPE int USING btree AS OPERATOR 0 = (int, int);
CREATE OPERATOR CLASS ea_oc2 FOR TYPE int USING btree AS OPERATOR 1 = (int, int), FUNCTION 99 btint4cmp(int, int);
CREATE OPERATOR CLASS ea_oc3 FOR TYPE int USING btree AS OPERATOR 1 ea_nosuchop (int, int);
CREATE OPERATOR CLASS ea_oc4 FOR TYPE int USING btree AS FUNCTION 1 ea_nosuchfn(int, int);
CREATE OPERATOR CLASS ea_oc5 FOR TYPE int USING btree AS OPERATOR 1 = (int, int), FUNCTION 1 btint4cmp(int, int), STORAGE text;
CREATE OPERATOR CLASS ea_oc6 FOR TYPE int USING ea_nosucham AS OPERATOR 1 = (int, int);
CREATE OPERATOR CLASS ea_oc7 FOR TYPE ea_nosuchtype USING btree AS OPERATOR 1 = (int, int);
CREATE OPERATOR FAMILY ea_of1 USING ea_nosucham;
CREATE OPERATOR FAMILY pg_catalog.integer_ops USING btree;
ALTER OPERATOR FAMILY ea_nosuchfam USING btree ADD OPERATOR 1 = (int, int);
ALTER OPERATOR CLASS ea_nosuchoc USING btree RENAME TO ea_x;
-- family:tabdef — transformColumnDefinition / CREATE TABLE parse errors -----
CREATE TABLE ea_bad (x int DEFAULT 1 DEFAULT 2);
CREATE TABLE ea_bad (x int NULL NOT NULL);
CREATE TABLE ea_bad (x serial DEFAULT 5);
CREATE TABLE ea_bad (x int GENERATED ALWAYS AS (1) STORED DEFAULT 5);
CREATE TABLE ea_bad (x int GENERATED ALWAYS AS IDENTITY GENERATED ALWAYS AS IDENTITY);
CREATE TABLE ea_bad (x int GENERATED ALWAYS AS (1) STORED GENERATED ALWAYS AS (2) STORED);
CREATE TABLE ea_bad (x text GENERATED ALWAYS AS IDENTITY);
CREATE TABLE ea_bad (x int, PRIMARY KEY (x), PRIMARY KEY (x));
CREATE TABLE ea_bad (x int CHECK (x > 0) DEFERRABLE);
CREATE TABLE ea_bad (x int, y int GENERATED ALWAYS AS (z + 1) STORED);
CREATE TABLE ea_bad (x int, y int GENERATED ALWAYS AS (random()::int) STORED);
CREATE TABLE ea_bad (x int, y int GENERATED ALWAYS AS ((SELECT 1)) STORED);
CREATE TABLE ea_bad (x int, y int GENERATED ALWAYS AS (sum(x)) STORED);
CREATE TABLE ea_bad (x ea_nosuchtype);
CREATE TABLE ea_bad (x int COLLATE "C");
CREATE TABLE ea_bad (x text COLLATE ea_nosuchcoll);
CREATE TEMP TABLE public.ea_bad (x int);
CREATE TABLE ea_typed OF ea_enum;
CREATE TABLE ea_typed OF ea_dom;
CREATE TABLE ea_bad (LIKE ea_seq);
CREATE TABLE ea_bad (LIKE ea_nosuchtab);
CREATE TABLE ea_bad (LIKE ea_v INCLUDING INDEXES);
CREATE TABLE ea_bad (x int, LIKE ea_bad);
CREATE TABLE ea_base (a int);
CREATE TABLE IF NOT EXISTS ea_base (a int);
CREATE UNLOGGED TABLE ea_ulp (id int, ts date) PARTITION BY RANGE (ts) ;
CREATE TABLE ea_badpart (id int) PARTITION BY bogus (id);
CREATE TABLE ea_badpart (id int) PARTITION BY RANGE (nosuchcol);
CREATE TABLE ea_badpart (id int) PARTITION BY RANGE (ctid);
CREATE TABLE ea_badpart (id int) PARTITION BY RANGE ((random()));
CREATE TABLE ea_badpart (id int, t text) PARTITION BY RANGE (t COLLATE ea_nosuchcoll);
CREATE TABLE ea_badp PARTITION OF ea_nosuchtab FOR VALUES FROM (1) TO (2);
CREATE TABLE ea_badp PARTITION OF ea_base FOR VALUES FROM (1) TO (2);
CREATE TABLE ea_badp PARTITION OF ea_part FOR VALUES FROM ('2020-06-01') TO ('2020-03-01');
CREATE TABLE ea_badp PARTITION OF ea_part FOR VALUES FROM ('2020-06-01') TO ('2020-09-01');
CREATE TABLE ea_badp PARTITION OF ea_part FOR VALUES IN (5);
CREATE TABLE ea_badp PARTITION OF ea_part FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE ea_badp PARTITION OF ea_part DEFAULT;
DROP TABLE ea_badp;
-- family:cleanup ------------------------------------------------------------
DROP TABLE ea_dup;
DROP TABLE ea_reftext;
DROP TABLE ea_part;
DROP MATERIALIZED VIEW ea_mv;
DROP VIEW ea_v;
DROP SEQUENCE ea_seq;
DROP FUNCTION ea_f(int);
DROP FUNCTION ea_any(anyelement, anyelement);
DROP FUNCTION ea_anyarr(anyarray, anyelement);
DROP FUNCTION ea_rec();
DROP DOMAIN ea_dom;
DROP TYPE ea_enum;
DROP TYPE ea_comp CASCADE;
DROP TABLE ea_base;
DROP TABLE ea_ref;
DROP SCHEMA ea_s;
DROP ROLE ea_nobody;
DROP ROLE ea_owner;
