-- LD8 ERROR-ARM round-2 wave-2 deck (earm2b): residual arms after the
-- earm2 wave-1 drain, targeted at the biggest remaining ERROR-ARM
-- functions (aclcheck_error, DefineType, CreateRole/AlterRole,
-- DefineAggregate/AggregateCreate, agg/window/SRF placement contexts,
-- str_udeescape, transformColumnRef, transformIndexConstraint/
-- DefineIndex, enforce_generic_type_consistency).
-- One statement per line, diffrunner --replay compatible.
-- section: w2acl — aclcheck_error per-objtype arms (no-priv + not-owner)
CREATE ROLE ea2b_u;
CREATE TABLE ea2b_at (a int, b int);
CREATE AGGREGATE ea2b_cagg(int) (sfunc = int4pl, stype = int);
CREATE COLLATION ea2b_ccoll (locale = 'C');
CREATE CONVERSION ea2b_cconv FOR 'UTF8' TO 'LATIN1' FROM utf8_to_iso_8859_1;
CREATE DOMAIN ea2b_cdom AS int CHECK (VALUE > 0);
CREATE FUNCTION ea2b_evtf() RETURNS event_trigger LANGUAGE plpgsql AS 'BEGIN END';
CREATE EVENT TRIGGER ea2b_evt ON ddl_command_start EXECUTE FUNCTION ea2b_evtf();
CREATE FOREIGN DATA WRAPPER ea2b_fdw;
CREATE SERVER ea2b_srv FOREIGN DATA WRAPPER ea2b_fdw;
CREATE FOREIGN TABLE ea2b_ft (a int) SERVER ea2b_srv;
CREATE FUNCTION ea2b_cf() RETURNS int LANGUAGE sql AS 'SELECT 1';
REVOKE EXECUTE ON FUNCTION ea2b_cf() FROM PUBLIC;
CREATE PROCEDURE ea2b_cp() LANGUAGE sql AS 'SELECT 1';
CREATE INDEX ea2b_cidx ON ea2b_at (a);
SELECT lo_create(424242);
CREATE MATERIALIZED VIEW ea2b_cmv AS SELECT 1 AS x;
CREATE PUBLICATION ea2b_cpub;
CREATE SCHEMA ea2b_ns;
CREATE SEQUENCE ea2b_cs;
CREATE STATISTICS ea2b_cst ON a, b FROM ea2b_at;
CREATE TEXT SEARCH DICTIONARY ea2b_cd (template = simple);
CREATE TEXT SEARCH CONFIGURATION ea2b_cc (copy = english);
CREATE TYPE ea2b_ct AS ENUM ('x', 'y');
REVOKE USAGE ON TYPE ea2b_ct FROM PUBLIC;
REVOKE USAGE ON DOMAIN ea2b_cdom FROM PUBLIC;
CREATE VIEW ea2b_cv AS SELECT 1 AS x;
SET ROLE ea2b_u;
COMMENT ON AGGREGATE ea2b_cagg(int) IS 'x';
COMMENT ON COLLATION ea2b_ccoll IS 'x';
COMMENT ON CONVERSION ea2b_cconv IS 'x';
COMMENT ON DOMAIN ea2b_cdom IS 'x';
COMMENT ON EVENT TRIGGER ea2b_evt IS 'x';
COMMENT ON EXTENSION plpgsql IS 'x';
COMMENT ON FOREIGN DATA WRAPPER ea2b_fdw IS 'x';
COMMENT ON SERVER ea2b_srv IS 'x';
COMMENT ON FOREIGN TABLE ea2b_ft IS 'x';
COMMENT ON FUNCTION ea2b_cf() IS 'x';
COMMENT ON PROCEDURE ea2b_cp() IS 'x';
COMMENT ON ROUTINE ea2b_cf() IS 'x';
COMMENT ON INDEX ea2b_cidx IS 'x';
COMMENT ON LANGUAGE plpgsql IS 'x';
COMMENT ON LARGE OBJECT 424242 IS 'x';
COMMENT ON MATERIALIZED VIEW ea2b_cmv IS 'x';
COMMENT ON OPERATOR CLASS int4_ops USING btree IS 'x';
COMMENT ON OPERATOR FAMILY integer_ops USING btree IS 'x';
COMMENT ON OPERATOR + (int, int) IS 'x';
COMMENT ON PUBLICATION ea2b_cpub IS 'x';
COMMENT ON SCHEMA ea2b_ns IS 'x';
COMMENT ON SEQUENCE ea2b_cs IS 'x';
COMMENT ON STATISTICS ea2b_cst IS 'x';
COMMENT ON TABLE ea2b_at IS 'x';
COMMENT ON TABLESPACE pg_default IS 'x';
COMMENT ON TEXT SEARCH CONFIGURATION ea2b_cc IS 'x';
COMMENT ON TEXT SEARCH DICTIONARY ea2b_cd IS 'x';
COMMENT ON TYPE ea2b_ct IS 'x';
COMMENT ON VIEW ea2b_cv IS 'x';
CREATE SERVER ea2b_srv2 FOREIGN DATA WRAPPER ea2b_fdw;
CREATE FOREIGN TABLE ea2b_ft2 (a int) SERVER ea2b_srv;
CREATE FUNCTION ea2b_badlang() RETURNS int LANGUAGE c AS 'nosuchfile', 'nosuchsym';
SELECT ea2b_cf();
SELECT lo_get(424242);
SELECT * FROM ea2b_cmv;
ALTER PUBLICATION ea2b_cpub RENAME TO ea2b_cpub2;
CREATE TABLE ea2b_ns.t1 (a int);
SELECT nextval('ea2b_cs');
CREATE TABLE ea2b_tst (a int) TABLESPACE pg_default;
ALTER TEXT SEARCH CONFIGURATION ea2b_cc DROP MAPPING FOR word;
CREATE TABLE ea2b_tt (c ea2b_ct);
SELECT 1::ea2b_cdom;
SELECT * FROM ea2b_cv;
SELECT * FROM ea2b_at;
ALTER COLLATION ea2b_ccoll REFRESH VERSION;
RESET ROLE;
DROP VIEW ea2b_cv;
DROP TYPE ea2b_ct;
DROP TEXT SEARCH CONFIGURATION ea2b_cc;
DROP TEXT SEARCH DICTIONARY ea2b_cd;
DROP STATISTICS ea2b_cst;
DROP SEQUENCE ea2b_cs;
DROP SCHEMA ea2b_ns;
DROP PUBLICATION ea2b_cpub;
DROP MATERIALIZED VIEW ea2b_cmv;
SELECT lo_unlink(424242);
DROP INDEX ea2b_cidx;
DROP PROCEDURE ea2b_cp();
DROP FUNCTION ea2b_cf();
DROP FOREIGN TABLE ea2b_ft;
DROP SERVER ea2b_srv;
DROP FOREIGN DATA WRAPPER ea2b_fdw;
DROP EVENT TRIGGER ea2b_evt;
DROP FUNCTION ea2b_evtf();
DROP DOMAIN ea2b_cdom;
DROP CONVERSION ea2b_cconv;
DROP COLLATION ea2b_ccoll;
DROP AGGREGATE ea2b_cagg(int);
DROP TABLE ea2b_at;
DROP ROLE ea2b_u;
-- section: w2typ — DefineType full base type + validation arms
CREATE TYPE ea2b_bt;
CREATE FUNCTION ea2b_bt_in(cstring) RETURNS ea2b_bt AS 'int4in' LANGUAGE internal IMMUTABLE STRICT;
CREATE FUNCTION ea2b_bt_out(ea2b_bt) RETURNS cstring AS 'int4out' LANGUAGE internal IMMUTABLE STRICT;
CREATE FUNCTION ea2b_bt_recv(internal) RETURNS ea2b_bt AS 'int4recv' LANGUAGE internal IMMUTABLE STRICT;
CREATE FUNCTION ea2b_bt_send(ea2b_bt) RETURNS bytea AS 'int4send' LANGUAGE internal IMMUTABLE STRICT;
CREATE TYPE ea2b_bt (input = ea2b_bt_in, output = ea2b_bt_out, receive = ea2b_bt_recv, send = ea2b_bt_send, internallength = 4, passedbyvalue, alignment = int4, storage = plain, category = 'N', preferred = false, delimiter = ',', collatable = false, default = '42');
SELECT ea2b_bt_out('7'::ea2b_bt);
CREATE TABLE ea2b_btt (v ea2b_bt DEFAULT '1');
DROP TABLE ea2b_btt;
CREATE TYPE ea2b_bt2;
CREATE FUNCTION ea2b_bt2_in(cstring) RETURNS ea2b_bt2 AS 'textin' LANGUAGE internal IMMUTABLE STRICT;
CREATE FUNCTION ea2b_bt2_out(ea2b_bt2) RETURNS cstring AS 'textout' LANGUAGE internal IMMUTABLE STRICT;
CREATE TYPE ea2b_bt2 (input = ea2b_bt2_in, output = ea2b_bt2_out, like = text, category = 'S', preferred = true, typmod_in = numerictypmodin, typmod_out = numerictypmodout, analyze = ts_typanalyze, collatable = true, storage = extended);
CREATE TYPE ea2b_bt3 (input = ea2b_bt2_in, output = ea2b_bt2_out);
CREATE TYPE ea2b_shell2;
CREATE TYPE ea2b_shell2;
CREATE TYPE ea2b_nsx (output = ea2b_bt2_out);
CREATE TYPE ea2b_nsy (input = ea2b_bt2_in);
CREATE TYPE ea2b_bt4 (input = ea2b_bt2_in, output = ea2b_bt2_out, typmod_out = numerictypmodout);
CREATE TYPE ea2b_bt5 (input = ea2b_bt2_in, output = ea2b_bt2_out, alignment = int8);
CREATE TYPE ea2b_bt6 (input = ea2b_bt2_in, output = ea2b_bt2_out, storage = compressed);
CREATE TYPE ea2b_bt7 (input = ea2b_bt2_in, output = ea2b_bt2_out, category = '');
CREATE TYPE ea2b_bt8 (input = ea2b_bt2_in, output = ea2b_bt2_out, element = ea2b_shell2);
CREATE TYPE ea2b_bt9 (input = ea2b_bt2_in, output = ea2b_bt2_out, element = internal);
CREATE TYPE ea2b_bt10 (input = ea2b_bt2_in, output = ea2b_bt2_out, element = int4);
CREATE TYPE ea2b_bt11 (input = ea2b_bt2_in, output = ea2b_bt2_out, input = ea2b_bt2_in);
CREATE TYPE ea2b_bt12 (input = ea2b_bt2_in, output = ea2b_bt2_out, nosuchattr = 1);
CREATE TYPE ea2b_bt13 (input = int4in, output = ea2b_bt2_out);
CREATE TYPE ea2b_nosh (input = nosuchfunc_in, output = ea2b_bt2_out);
DROP TYPE ea2b_shell2;
DROP TYPE ea2b_bt2 CASCADE;
DROP FUNCTION ea2b_bt2_in(cstring) CASCADE;
DROP FUNCTION ea2b_bt2_out(ea2b_bt2);
DROP TYPE ea2b_bt CASCADE;
-- section: w2role — CreateRole/AlterRole option matrix + reserved names
CREATE ROLE ea2b_r1 WITH SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS CONNECTION LIMIT 10 PASSWORD 'sekret' VALID UNTIL '2030-01-01';
CREATE ROLE ea2b_r2 WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD NULL;
CREATE ROLE ea2b_r3 IN ROLE ea2b_r2;
CREATE ROLE ea2b_r4 ROLE ea2b_r3 ADMIN ea2b_r2;
CREATE ROLE ea2b_r5 SYSID 100;
DROP ROLE ea2b_r5;
CREATE ROLE public;
CREATE ROLE "none";
CREATE ROLE current_role;
CREATE ROLE pg_ea2b_reserved;
CREATE ROLE ea2b_r1;
CREATE USER ea2b_r6;
CREATE ROLE ea2b_r7 WITH LOGIN LOGIN;
CREATE ROLE ea2b_r8 WITH PASSWORD 'a' PASSWORD 'b';
CREATE ROLE ea2b_r9 VALID UNTIL 'not-a-date';
ALTER ROLE ea2b_r1 WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
ALTER ROLE ea2b_r1 VALID UNTIL 'infinity';
ALTER ROLE ea2b_r1 PASSWORD NULL;
ALTER ROLE ea2b_r1 SET work_mem = '8MB';
ALTER ROLE ea2b_r1 IN DATABASE nosuchdb SET work_mem = '8MB';
ALTER ROLE ALL SET statement_timeout = '30s';
ALTER ROLE ALL RESET statement_timeout;
ALTER ROLE ea2b_r1 RESET ALL;
ALTER ROLE nosuchrole CREATEDB;
ALTER ROLE public CREATEDB;
ALTER ROLE ea2b_r2 SYSID 42;
ALTER USER ea2b_r6 RENAME TO ea2b_r6b;
ALTER ROLE ea2b_r6b RENAME TO public;
ALTER ROLE ea2b_r6b RENAME TO pg_ea2b_x;
SET ROLE ea2b_r2;
CREATE ROLE ea2b_rx;
ALTER ROLE ea2b_r1 CREATEDB;
ALTER ROLE ea2b_r1 PASSWORD 'hacked';
DROP ROLE ea2b_r1;
RESET ROLE;
DROP ROLE ea2b_r6b;
DROP ROLE ea2b_r4;
DROP ROLE ea2b_r3;
DROP ROLE ea2b_r2;
DROP ROLE ea2b_r1;
-- section: w2agg — DefineAggregate/AggregateCreate arms
CREATE AGGREGATE ea2b_ag1(int) (sfunc = int4pl, stype = int, initcond = '0', msfunc = int4pl, minvfunc = int4mi, mstype = int, minitcond = '0', combinefunc = int4pl, parallel = safe);
SELECT ea2b_ag1(g) FROM generate_series(1, 5) g;
CREATE AGGREGATE ea2b_ag2(numeric) (sfunc = numeric_avg_accum, stype = internal, sspace = 128, finalfunc = numeric_avg, serialfunc = numeric_avg_serialize, deserialfunc = numeric_avg_deserialize, combinefunc = numeric_avg_combine, parallel = safe);
SELECT ea2b_ag2(g::numeric) FROM generate_series(1, 5) g;
CREATE AGGREGATE ea2b_os1(float8 ORDER BY float8) (sfunc = ordered_set_transition, stype = internal, finalfunc = percentile_cont_float8_final, finalfunc_extra);
SELECT ea2b_os1(0.5) WITHIN GROUP (ORDER BY g::float8) FROM generate_series(1, 4) g;
CREATE AGGREGATE ea2b_hs1(float8 ORDER BY float8) (sfunc = ordered_set_transition, stype = internal, finalfunc = rank_final, finalfunc_extra, hypothetical);
CREATE AGGREGATE ea2b_agmax(int) (sfunc = int4larger, stype = int, sortop = >);
CREATE AGGREGATE ea2b_bad1(int) (sfunc = int4pl, stype = int, mfinalfunc = int4um);
CREATE AGGREGATE ea2b_bad2(int) (sfunc = int4pl, stype = int, minvfunc = int4mi);
CREATE AGGREGATE ea2b_bad3(int) (sfunc = int4pl, stype = int, msfunc = int4pl);
CREATE AGGREGATE ea2b_bad4(int) (sfunc = int4pl, stype = int, mstype = int);
CREATE AGGREGATE ea2b_bad5(int) (sfunc = int4pl, stype = int, serialfunc = numeric_avg_serialize);
CREATE AGGREGATE ea2b_bad6(int) (sfunc = int4pl, stype = int, deserialfunc = numeric_avg_deserialize);
CREATE AGGREGATE ea2b_bad7(int) (sfunc = int4pl, stype = internal);
CREATE AGGREGATE ea2b_bad8(int) (sfunc = int4pl, stype = int, initcond = 'notanint');
CREATE AGGREGATE ea2b_bad9(int, int) (sfunc = int4pl, stype = int, sortop = >);
CREATE AGGREGATE ea2b_bad10(int) (stype = int);
CREATE AGGREGATE ea2b_bad11(int) (sfunc = int4pl);
CREATE AGGREGATE ea2b_bad12(int) (sfunc = nosuchsfunc, stype = int);
CREATE AGGREGATE ea2b_bad13(int) (sfunc = textcat, stype = text);
CREATE AGGREGATE ea2b_bad14(int) (sfunc = int4pl, stype = int, parallel = bogus);
CREATE AGGREGATE ea2b_bad15(int) (sfunc = int4pl, stype = int, finalfunc_modify = bogus);
CREATE AGGREGATE ea2b_bad16(int) (sfunc = int4pl, stype = int, hypothetical);
CREATE AGGREGATE ea2b_bad17(int) (sfunc = int4pl, stype = int, nosuchopt = 1);
CREATE AGGREGATE ea2b_bad18(*) (sfunc = int4pl, stype = int);
CREATE AGGREGATE ea2b_bad19(int) (sfunc = int4pl, stype = int, finalfunc = nosuchfinal);
CREATE AGGREGATE ea2b_bad20(int) (sfunc = int4pl, stype = int, combinefunc = textcat);
DROP AGGREGATE ea2b_agmax(int);
DROP AGGREGATE ea2b_hs1(float8 ORDER BY float8);
DROP AGGREGATE ea2b_os1(float8 ORDER BY float8);
DROP AGGREGATE ea2b_ag2(numeric);
DROP AGGREGATE ea2b_ag1(int);
-- section: w2aggpl — aggregate/window/SRF placement context arms
CREATE TABLE ea2b_p1 (a int, b int);
CREATE TABLE ea2b_p2 (x int, y int);
INSERT INTO ea2b_p1 VALUES (1, 1), (2, 2);
INSERT INTO ea2b_p2 VALUES (1, 1);
SELECT 1 FROM ea2b_p1 JOIN ea2b_p2 ON count(*) > 0;
SELECT 1 FROM ea2b_p1 WHERE count(*) > 0;
CREATE POLICY ea2b_pol ON ea2b_p1 USING (count(*) > 0);
SELECT a, sum(b) OVER (ORDER BY a ROWS count(*) PRECEDING) FROM ea2b_p1;
SELECT a FROM ea2b_p1 GROUP BY count(*);
SELECT a FROM ea2b_p1 LIMIT count(*);
SELECT a FROM ea2b_p1 OFFSET count(*);
INSERT INTO ea2b_p1 VALUES (3, 3) RETURNING count(*);
SELECT * FROM (VALUES (count(*))) v;
ALTER TABLE ea2b_p1 ADD CONSTRAINT ea2b_ck CHECK (count(*) > 0);
CREATE DOMAIN ea2b_dck AS int CHECK (count(VALUE) > 0);
ALTER TABLE ea2b_p1 ALTER COLUMN a SET DEFAULT count(*);
CREATE FUNCTION ea2b_fd(x int DEFAULT count(*)) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE INDEX ea2b_iag ON ea2b_p1 ((count(*)));
CREATE INDEX ea2b_iag2 ON ea2b_p1 (a) WHERE count(*) > 0;
CREATE STATISTICS ea2b_sag ON (count(*)), a FROM ea2b_p1;
ALTER TABLE ea2b_p1 ALTER COLUMN b TYPE bigint USING count(*);
CREATE TRIGGER ea2b_tag BEFORE UPDATE ON ea2b_p1 FOR EACH ROW WHEN (count(*) > 0) EXECUTE FUNCTION suppress_redundant_updates_trigger();
CREATE TABLE ea2b_pb (a int) PARTITION BY RANGE (a);
CREATE TABLE ea2b_pbc PARTITION OF ea2b_pb FOR VALUES FROM (count(*)) TO (10);
CREATE TABLE ea2b_pe (a int) PARTITION BY RANGE ((count(*)));
CREATE TABLE ea2b_gc (a int, g int GENERATED ALWAYS AS (count(*)) STORED);
CALL ea2b_nosuchproc(count(*));
COPY ea2b_p1 FROM '/nonexistent' WHERE count(*) > 0;
MERGE INTO ea2b_p1 t USING ea2b_p2 s ON t.a = s.x WHEN MATCHED AND count(*) > 0 THEN DO NOTHING;
SELECT 1 FROM ea2b_p1 JOIN ea2b_p2 ON lag(1) OVER () > 0;
SELECT 1 FROM ea2b_p1 WHERE lag(1) OVER () IS NULL;
SELECT a FROM ea2b_p1 GROUP BY lag(1) OVER ();
SELECT count(*) FILTER (WHERE lag(1) OVER () IS NULL) FROM ea2b_p1;
SELECT sum(a) OVER (PARTITION BY lag(1) OVER ()) FROM ea2b_p1;
SELECT a FROM ea2b_p1 LIMIT lag(1) OVER ();
INSERT INTO ea2b_p1 VALUES (4, 4) RETURNING lag(1) OVER ();
SELECT * FROM (VALUES (lag(1) OVER ())) v;
ALTER TABLE ea2b_p1 ADD CONSTRAINT ea2b_ckw CHECK (lag(1) OVER () IS NULL);
ALTER TABLE ea2b_p1 ALTER COLUMN a SET DEFAULT lag(1) OVER ();
CREATE INDEX ea2b_iw ON ea2b_p1 ((lag(1) OVER ()));
CREATE INDEX ea2b_iw2 ON ea2b_p1 (a) WHERE lag(1) OVER () IS NULL;
CREATE STATISTICS ea2b_sw ON (lag(1) OVER ()), a FROM ea2b_p1;
ALTER TABLE ea2b_p1 ALTER COLUMN b TYPE bigint USING lag(1) OVER ();
CREATE TRIGGER ea2b_tw BEFORE UPDATE ON ea2b_p1 FOR EACH ROW WHEN (lag(1) OVER () IS NULL) EXECUTE FUNCTION suppress_redundant_updates_trigger();
CREATE TABLE ea2b_pbw PARTITION OF ea2b_pb FOR VALUES FROM (lag(1) OVER ()) TO (10);
CREATE TABLE ea2b_pew (a int) PARTITION BY RANGE ((lag(1) OVER ()));
CREATE TABLE ea2b_gcw (a int, g int GENERATED ALWAYS AS (lag(1) OVER ()) STORED);
COPY ea2b_p1 FROM '/nonexistent' WHERE lag(1) OVER () IS NULL;
MERGE INTO ea2b_p1 t USING ea2b_p2 s ON t.a = s.x WHEN MATCHED AND lag(1) OVER () IS NULL THEN DO NOTHING;
UPDATE ea2b_p1 SET a = lag(1) OVER ();
SELECT 1 FROM ea2b_p1 JOIN ea2b_p2 ON generate_series(1, 2) > 0;
CREATE POLICY ea2b_pols ON ea2b_p1 USING (generate_series(1, 2) > 0);
SELECT sum(a) OVER (PARTITION BY generate_series(1, 2)) FROM ea2b_p1;
SELECT sum(a) OVER (ORDER BY a ROWS generate_series(1, 2) PRECEDING) FROM ea2b_p1;
UPDATE ea2b_p1 SET a = generate_series(1, 2);
SELECT * FROM (VALUES (generate_series(1, 2)), (2)) v;
ALTER TABLE ea2b_p1 ADD CONSTRAINT ea2b_cks CHECK (generate_series(1, a) > 0);
CREATE DOMAIN ea2b_dcks AS int CHECK (generate_series(1, VALUE) > 0);
ALTER TABLE ea2b_p1 ALTER COLUMN a SET DEFAULT generate_series(1, 2);
CREATE FUNCTION ea2b_fds(x int DEFAULT generate_series(1, 2)) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE INDEX ea2b_is ON ea2b_p1 ((generate_series(1, a)));
CREATE INDEX ea2b_is2 ON ea2b_p1 (a) WHERE generate_series(1, a) > 0;
CREATE STATISTICS ea2b_ss ON (generate_series(1, a)), a FROM ea2b_p1;
ALTER TABLE ea2b_p1 ALTER COLUMN b TYPE bigint USING generate_series(1, b);
CREATE TRIGGER ea2b_ts BEFORE UPDATE ON ea2b_p1 FOR EACH ROW WHEN (generate_series(1, 2) > 0) EXECUTE FUNCTION suppress_redundant_updates_trigger();
CREATE TABLE ea2b_pbs PARTITION OF ea2b_pb FOR VALUES FROM (generate_series(1, 2)) TO (10);
CREATE TABLE ea2b_pes (a int) PARTITION BY RANGE ((generate_series(1, a)));
CREATE TABLE ea2b_gcs (a int, g int GENERATED ALWAYS AS (generate_series(1, a)) STORED);
COPY ea2b_p1 FROM '/nonexistent' WHERE generate_series(1, 2) > 0;
MERGE INTO ea2b_p1 t USING ea2b_p2 s ON t.a = s.x WHEN MATCHED AND generate_series(1, 2) > 0 THEN DO NOTHING;
SELECT a FROM ea2b_p1 HAVING generate_series(1, 2) > 0;
DROP TABLE ea2b_pb;
DROP TABLE ea2b_p2;
DROP TABLE ea2b_p1;
-- section: w2udesc — U& escape arms (str_udeescape)
SELECT U&'\0041\0042';
SELECT U&'\+000041';
SELECT U&'d\0061t\+000061';
SELECT U&'\d83d\de04';
SELECT U&'\+00d83d\+00de04';
SELECT U&'!0041' UESCAPE '!';
SELECT U&'\\';
SELECT U&'!!' UESCAPE '!';
SELECT U&'\dc04';
SELECT U&'\d83d';
SELECT U&'\d83dX';
SELECT U&'\d83d\0041';
SELECT U&'\d83d\d83d';
SELECT U&'\00zz';
SELECT U&'\+110000';
SELECT U&'\0000';
SELECT U&'\0041' UESCAPE 'a';
SELECT U&'\0041' UESCAPE '+';
SELECT U&'\0041' UESCAPE '''';
SELECT U&'\0041' UESCAPE '!!';
SELECT U&"\0041";
SELECT U&"\dc04";
SELECT U&"!0041" UESCAPE '!';
-- section: w2colref — transformColumnRef arms
CREATE TABLE ea2b_cr (aa int, ab int);
INSERT INTO ea2b_cr VALUES (1, 2);
SELECT ea2b_cr.aa FROM ea2b_cr;
SELECT public.ea2b_cr.aa FROM ea2b_cr;
SELECT ea2b_cr.* FROM ea2b_cr;
SELECT public.ea2b_cr.* FROM ea2b_cr;
SELECT nosuchtab.aa FROM ea2b_cr;
SELECT nosuchtab.* FROM ea2b_cr;
SELECT ea2b_cr.nosuchcol FROM ea2b_cr;
SELECT nosuchschema.ea2b_cr.aa FROM ea2b_cr;
SELECT otherdb.public.ea2b_cr.aa FROM ea2b_cr;
SELECT a.b.c.d.e FROM ea2b_cr;
SELECT az FROM ea2b_cr;
SELECT abb FROM ea2b_cr;
SELECT (ea2b_cr).nosuchcol FROM ea2b_cr;
SELECT (ea2b_cr).aa FROM ea2b_cr;
DROP TABLE ea2b_cr;
-- section: w2idx — transformIndexConstraint + DefineIndex arms
CREATE TABLE ea2b_it (a int NOT NULL, b int, c text, r int4range);
CREATE TABLE ea2b_other (z int);
CREATE UNIQUE INDEX ea2b_uix ON ea2b_it (a);
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_uc1 UNIQUE USING INDEX ea2b_uix;
ALTER TABLE ea2b_it DROP CONSTRAINT ea2b_uc1;
CREATE UNIQUE INDEX ea2b_uix2 ON ea2b_it (a);
ALTER TABLE ea2b_other ADD CONSTRAINT ea2b_uc2 UNIQUE USING INDEX ea2b_uix2;
CREATE UNIQUE INDEX ea2b_eix ON ea2b_it ((a + 1));
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_uc3 UNIQUE USING INDEX ea2b_eix;
CREATE UNIQUE INDEX ea2b_pix ON ea2b_it (a) WHERE b > 0;
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_uc4 UNIQUE USING INDEX ea2b_pix;
CREATE INDEX ea2b_nix ON ea2b_it (a);
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_uc5 UNIQUE USING INDEX ea2b_nix;
CREATE INDEX ea2b_hix ON ea2b_it USING hash (a);
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_uc6 PRIMARY KEY USING INDEX ea2b_hix;
CREATE UNIQUE INDEX ea2b_dix ON ea2b_it (a DESC);
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_uc7 PRIMARY KEY USING INDEX ea2b_dix;
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_uc8 UNIQUE USING INDEX nosuchindex;
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_ol1 UNIQUE (b, r WITHOUT OVERLAPS);
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_ol2 UNIQUE (b, c WITHOUT OVERLAPS);
ALTER TABLE ea2b_it ADD CONSTRAINT ea2b_ol3 PRIMARY KEY (a, b WITHOUT OVERLAPS);
ALTER TABLE ea2b_it DROP CONSTRAINT ea2b_ol1;
CREATE UNIQUE INDEX ea2b_gix ON ea2b_it USING gin (c);
CREATE UNIQUE INDEX ea2b_hux ON ea2b_it USING hash (a);
CREATE INDEX ea2b_amx ON ea2b_it USING nosucham (a);
CREATE INDEX ea2b_ocx ON ea2b_it (a text_ops);
CREATE INDEX ea2b_ocy ON ea2b_it (a nosuchops);
CREATE INDEX ea2b_clx ON ea2b_it (a COLLATE "C");
CREATE INDEX ea2b_adx ON ea2b_it USING hash (a DESC);
CREATE INDEX ea2b_nfx ON ea2b_it USING hash (a NULLS FIRST);
CREATE INDEX ea2b_sysx ON pg_class (relname);
CREATE INDEX ea2b_incg ON ea2b_it USING gin (c) INCLUDE (a);
BEGIN;
CREATE INDEX CONCURRENTLY ea2b_cix ON ea2b_it (a);
ROLLBACK;
CREATE TABLE ea2b_pt (a int, b int) PARTITION BY RANGE (a);
CREATE UNIQUE INDEX ea2b_pux ON ea2b_pt (b);
CREATE INDEX CONCURRENTLY ea2b_pcx ON ea2b_pt (a);
ALTER TABLE ea2b_pt ADD CONSTRAINT ea2b_pex EXCLUDE USING btree (a WITH =);
CREATE UNIQUE INDEX ea2b_okx ON ea2b_pt (a);
DROP TABLE ea2b_pt;
DROP TABLE ea2b_other;
DROP TABLE ea2b_it;
-- section: w2poly — enforce_generic_type_consistency residue (anycompatible/range/multirange)
CREATE FUNCTION ea2b_pe(anyelement, anyelement) RETURNS anyelement LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea2b_pa(anyelement, anyarray) RETURNS anyelement LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea2b_pr(anyrange) RETURNS anyelement LANGUAGE sql AS 'SELECT lower($1)';
CREATE FUNCTION ea2b_pm(anymultirange) RETURNS anyelement LANGUAGE sql AS 'SELECT lower($1)';
CREATE FUNCTION ea2b_prm(anyrange, anymultirange) RETURNS anyelement LANGUAGE sql AS 'SELECT lower($1)';
CREATE FUNCTION ea2b_pc(anycompatible, anycompatible) RETURNS anycompatible LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea2b_pca(anycompatible, anycompatiblearray) RETURNS anycompatible LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea2b_pcr(anycompatiblerange, anycompatible) RETURNS anycompatible LANGUAGE sql AS 'SELECT lower($1)';
CREATE FUNCTION ea2b_pcm(anycompatiblemultirange, anycompatible) RETURNS anycompatible LANGUAGE sql AS 'SELECT lower($1)';
CREATE FUNCTION ea2b_pn(anynonarray) RETURNS anynonarray LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea2b_pen(anyenum) RETURNS anyenum LANGUAGE sql AS 'SELECT $1';
SELECT ea2b_pe(1, 2);
SELECT ea2b_pe(1, 'x'::text);
SELECT ea2b_pa(1, ARRAY[1, 2]);
SELECT ea2b_pa(1, ARRAY['x'::text]);
SELECT ea2b_pa(1, 42);
SELECT ea2b_pr(int4range(1, 5));
SELECT ea2b_pr(NULL);
SELECT ea2b_pr(42);
SELECT ea2b_pm(int4multirange(int4range(1, 5)));
SELECT ea2b_pm(NULL);
SELECT ea2b_pm(int4range(1, 5));
SELECT ea2b_prm(int4range(1, 5), int4multirange(int4range(1, 5)));
SELECT ea2b_prm(int4range(1, 5), nummultirange(numrange(1, 5)));
SELECT ea2b_prm(NULL, NULL);
SELECT ea2b_pc(1, 2.5);
SELECT ea2b_pc(1, point '(1,2)');
SELECT ea2b_pca(1, ARRAY[2.5]);
SELECT ea2b_pca(1, point '(1,2)');
SELECT ea2b_pca(NULL, NULL);
SELECT ea2b_pcr(int4range(1, 5), 2.5);
SELECT ea2b_pcr(NULL, 1);
SELECT ea2b_pcr(42, 1);
SELECT ea2b_pcm(int4multirange(int4range(1, 5)), 2.5);
SELECT ea2b_pcm(NULL, 1);
SELECT ea2b_pn(ARRAY[1]);
SELECT ea2b_pn(1);
SELECT ea2b_pen(1);
SELECT ea2b_pen(NULL);
DROP FUNCTION ea2b_pen(anyenum);
DROP FUNCTION ea2b_pn(anynonarray);
DROP FUNCTION ea2b_pcm(anycompatiblemultirange, anycompatible);
DROP FUNCTION ea2b_pcr(anycompatiblerange, anycompatible);
DROP FUNCTION ea2b_pca(anycompatible, anycompatiblearray);
DROP FUNCTION ea2b_pc(anycompatible, anycompatible);
DROP FUNCTION ea2b_prm(anyrange, anymultirange);
DROP FUNCTION ea2b_pm(anymultirange);
DROP FUNCTION ea2b_pr(anyrange);
DROP FUNCTION ea2b_pa(anyelement, anyarray);
DROP FUNCTION ea2b_pe(anyelement, anyelement);
