-- LD6 v2 rider: residual-arm probes after round-1 measure. One stmt/line.
-- FIXTURES
CREATE TABLE ea_base (a int PRIMARY KEY, b text, c numeric(10,2));
CREATE TABLE ea_part (id int, ts date) PARTITION BY RANGE (ts);
CREATE TABLE ea_p1 PARTITION OF ea_part FOR VALUES FROM ('2020-01-01') TO ('2021-01-01');
CREATE ROLE ea_nobody;
CREATE ROLE ea_owner;
CREATE TEXT SEARCH CONFIGURATION ea_tsc (COPY = simple);
CREATE TEXT SEARCH DICTIONARY ea_tsd (TEMPLATE = simple);
CREATE FUNCTION ea_f(int) RETURNS int LANGUAGE sql AS 'SELECT $1';
-- family:schema — namespace.c missing-schema / reserved-schema arms
CREATE TABLE ea_noschema.t (x int);
CREATE VIEW ea_noschema.v AS SELECT 1;
CREATE SEQUENCE ea_noschema.s;
CREATE TYPE ea_noschema.ty AS (p int);
CREATE FUNCTION ea_noschema.f() RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE INDEX ea_noschema_idx ON ea_noschema.t (x);
CREATE TABLE pg_catalog.ea_bad (x int);
CREATE SCHEMA pg_ea_reserved;
ALTER TABLE ea_base SET SCHEMA pg_catalog;
CREATE TEMP TABLE pg_temp.ea_tmpok (x int);
DROP TABLE pg_temp.ea_tmpok;
SELECT nosuchschema.f();
SELECT pg_catalog.nosuchfunc(1);
-- family:acl2 — more objtype denial arms
SET ROLE ea_nobody;
ALTER TEXT SEARCH CONFIGURATION ea_tsc ALTER MAPPING FOR word WITH simple;
ALTER TEXT SEARCH DICTIONARY ea_tsd (StopWords = ea);
COMMENT ON TEXT SEARCH CONFIGURATION ea_tsc IS 'no';
COMMENT ON TEXT SEARCH DICTIONARY ea_tsd IS 'no';
COMMENT ON ROLE ea_owner IS 'no';
COMMENT ON DATABASE fuzz IS 'no';
CREATE PUBLICATION ea_pub;
CREATE EVENT TRIGGER ea_et ON ddl_command_start EXECUTE FUNCTION ea_f();
CREATE EXTENSION ea_nosuchext;
ALTER DATABASE fuzz SET work_mem = '8MB';
ALTER DATABASE fuzz RENAME TO fuzz2;
CREATE TABLESPACE ea_ts LOCATION '/nonexistent';
VACUUM ea_base;
ANALYZE ea_base;
CLUSTER ea_base;
REINDEX TABLE ea_base;
SECURITY LABEL ON TABLE ea_base IS 'no';
ALTER TABLE ea_p1 OWNER TO ea_owner;
ALTER FUNCTION ea_f(int) OWNER TO ea_owner;
ALTER TABLE ea_base OWNER TO ea_owner;
RESET ROLE;
-- family:role2 — user.c breadth
ALTER ROLE ea_owner RENAME TO pg_ea_sneak;
ALTER ROLE current_user RENAME TO ea_self;
ALTER ROLE ea_nobody IN DATABASE ea_nosuchdb SET work_mem = '8MB';
ALTER ROLE ea_nobody SET nosuch_guc = 1;
ALTER ROLE ea_nobody SET work_mem = 'bogus';
ALTER ROLE ea_nobody VALID UNTIL 'notadate';
GRANT ea_owner TO ea_nobody WITH ADMIN OPTION;
GRANT ea_nobody TO ea_owner;
GRANT ea_owner TO ea_nobody;
REVOKE ea_owner FROM ea_nobody;
REVOKE ADMIN OPTION FOR ea_owner FROM ea_nobody;
DROP ROLE ea_nobody, ea_nosuchrole;
DROP OWNED BY ea_nosuchrole;
REASSIGN OWNED BY ea_nosuchrole TO ea_owner;
REASSIGN OWNED BY ea_owner TO ea_nosuchrole;
-- family:poly2 — anycompatible/anyenum/anyrange family
CREATE FUNCTION ea_ac(x anycompatible, y anycompatible) RETURNS anycompatible LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION ea_acarr(x anycompatiblearray, y anycompatible) RETURNS anycompatible LANGUAGE sql AS 'SELECT $2';
CREATE FUNCTION ea_ar(r anyrange, e anyelement) RETURNS anyelement LANGUAGE sql AS 'SELECT $2';
CREATE FUNCTION ea_ae(e anyenum) RETURNS anyenum LANGUAGE sql AS 'SELECT $1';
SELECT ea_ac(1, point '(1,1)');
SELECT ea_ac('a', 'b');
SELECT ea_acarr(ARRAY[1], point '(1,1)');
SELECT ea_acarr('{1}', '{2}');
SELECT ea_acarr(1, 2);
SELECT ea_ar(int4range(1,2), 'x'::text);
SELECT ea_ar('x', 'y');
SELECT ea_ae(1);
SELECT ea_ae('r');
DROP FUNCTION ea_ac(anycompatible, anycompatible);
DROP FUNCTION ea_acarr(anycompatiblearray, anycompatible);
DROP FUNCTION ea_ar(anyrange, anyelement);
DROP FUNCTION ea_ae(anyenum);
-- family:type2 — DefineType/AlterType breadth
CREATE TYPE ea_t7 (INPUT = int4in, OUTPUT = int4out, RECEIVE = ea_nosuchrecv);
CREATE TYPE ea_t8 (INPUT = int4in, OUTPUT = int4out, SEND = ea_nosuchsend);
CREATE TYPE ea_t9 (INPUT = int4in, OUTPUT = int4out, TYPMOD_IN = ea_nosuchtmin);
CREATE TYPE ea_t10 (INPUT = int4in, OUTPUT = int4out, ANALYZE = ea_nosuchan);
CREATE TYPE ea_t11 (INPUT = int4in, OUTPUT = int4out, SUBSCRIPT = ea_nosuchsub);
CREATE TYPE ea_t12 (INPUT = int4in, OUTPUT = int4out, ELEMENT = ea_nosuchtype);
CREATE TYPE ea_t13 (INPUT = int4in, OUTPUT = int4out, DELIMITER = 'toolong');
CREATE TYPE ea_t14 (INPUT = int4in, OUTPUT = int4out, LIKE = ea_nosuchtype);
CREATE TYPE ea_t15 (INPUT = int4in, OUTPUT = int4out, INTERNALLENGTH = 100000000000);
CREATE TYPE ea_t16 (INPUT = int4in, OUTPUT = int4out, PASSEDBYVALUE, INTERNALLENGTH = 100);
CREATE TYPE ea_t17 (BOGUSATTR = 1);
CREATE TYPE ea_t18 AS (p int, p int);
CREATE TYPE ea_t19 AS (p int COLLATE ea_nosuchcoll);
ALTER TYPE ea_base ADD ATTRIBUTE z int;
CREATE DOMAIN ea_d7 AS int COLLATE "C";
CREATE DOMAIN ea_d8 AS int[] DEFAULT 'notanarray';
CREATE DOMAIN ea_d9 AS anyelement;
ALTER DOMAIN ea_nosuchdom ADD CHECK (VALUE > 0);
ALTER DOMAIN int4 ADD CHECK (VALUE > 0);
-- family:idx2 — DefineIndex/transformIndexConstraint breadth
CREATE INDEX ea_bad_idx ON ea_base (a) TABLESPACE ea_nosuch;
CREATE INDEX ea_bad_idx ON ea_base (a) INCLUDE (a);
CREATE INDEX ea_bad_idx ON ea_base USING brin (a int4_minmax_ops, a);
CREATE UNIQUE INDEX ea_bad_idx ON ea_base USING brin (a);
CREATE UNIQUE INDEX ea_bad_idx ON ea_p1 (id) NULLS NOT DISTINCT;
CREATE INDEX ea_bad_idx ON ea_base (a) WITH (bogus_opt = 1);
CREATE INDEX ea_bad_idx ON ea_base (a) WITH (fillfactor = 5);
CREATE INDEX ea_bad_idx ON ea_base ((rank() OVER ()));
CREATE INDEX ea_bad_idx ON ea_base (a) WHERE rank() OVER () = 1;
CREATE UNIQUE INDEX ea_uniq_part ON ea_part (id, ts);
ALTER TABLE ea_part ADD PRIMARY KEY USING INDEX ea_uniq_part;
DROP INDEX ea_uniq_part;
CREATE UNIQUE INDEX ea_partial ON ea_base (a) WHERE a > 0;
ALTER TABLE ea_base ADD UNIQUE USING INDEX ea_partial;
DROP INDEX ea_partial;
CREATE UNIQUE INDEX ea_desc ON ea_base (a DESC);
ALTER TABLE ea_base ADD PRIMARY KEY USING INDEX ea_desc;
DROP INDEX ea_desc;
ALTER TABLE ea_base ADD CONSTRAINT ea_x EXCLUDE USING btree (a WITH <>);
ALTER TABLE ea_part ADD EXCLUDE USING gist (ts WITH &&);
ALTER TABLE ea_base ADD PRIMARY KEY (a) DEFERRABLE NOT DEFERRABLE;
-- family:altable2 — tablecmds breadth
ALTER TABLE ea_base SET ACCESS METHOD ea_nosucham;
ALTER TABLE ea_base OWNER TO ea_nosuchrole;
ALTER TABLE ea_base SET (toast.bogus = 1);
ALTER TABLE ea_base ALTER COLUMN a SET (n_distinct = 'x');
ALTER TABLE ea_base ALTER COLUMN a SET (bogus_attopt = 1);
ALTER TABLE ea_base ALTER COLUMN a SET STORAGE EXTENDED;
ALTER TABLE ea_base ADD COLUMN q ea_nosuchtype;
ALTER TABLE ea_base ADD COLUMN q serial;
ALTER TABLE ea_p1 ADD COLUMN q int;
ALTER TABLE ea_p1 DROP COLUMN id;
ALTER TABLE ea_p1 ALTER COLUMN id TYPE bigint;
ALTER TABLE ea_part DETACH PARTITION ea_p1 CONCURRENTLY;
ALTER TABLE ea_base ALTER CONSTRAINT nosuchcon DEFERRABLE;
ALTER TABLE ea_base ADD CONSTRAINT ea_fk2 FOREIGN KEY (a) REFERENCES ea_base (a) NOT VALID DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ea_base DROP CONSTRAINT ea_fk2;
ALTER INDEX ea_nosuchidx SET (fillfactor = 50);
ALTER INDEX ALL IN TABLESPACE ea_nosuch SET TABLESPACE pg_default;
ALTER MATERIALIZED VIEW ea_nosuchmv SET SCHEMA public;
ALTER VIEW ea_nosuchview RENAME TO x;
ALTER SEQUENCE ea_nosuchseq RESTART;
ALTER SEQUENCE IF EXISTS ea_nosuchseq RESTART;
ALTER VIEW IF EXISTS ea_nosuchview RENAME TO x;
ALTER TABLE ea_base ALTER COLUMN a TYPE int USING nosuchcol + 1;
ALTER TABLE ea_base ALTER COLUMN a TYPE int USING sum(a);
ALTER TABLE ea_base ALTER COLUMN a TYPE int USING (SELECT 1);
TRUNCATE ea_nosuchtab;
TRUNCATE ONLY ea_part;
COMMENT ON COLUMN ea_base.nosuchcol IS 'x';
COMMENT ON CONSTRAINT nosuchcon ON ea_base IS 'x';
-- CLEANUP
DROP TEXT SEARCH DICTIONARY ea_tsd;
DROP TEXT SEARCH CONFIGURATION ea_tsc;
DROP FUNCTION ea_f(int);
DROP TABLE ea_part;
DROP TABLE ea_base;
DROP ROLE ea_nobody;
DROP ROLE ea_owner;
