-- fuzzgen seed=302 modules=expr=off,joins=off,subq=off,agg=off,win=off,dml=off,merge=off,txn=off,ddl=off,types=off,explain=off,util=off,part=off,objddl=off,idx=off,par=off,tsdl=off,cursor=off,views=off,geo=off,dtm=off,adtmisc=on,sqljson=off,plpg=off,coll=off,mbconv=off,xnum=off,nodes=off,obs=off,admin=off,objid=off,einterp=off,exd=off,spill=off,earm=off,pubsub=off weights=adtm:strsafe=40,adtm:regex2=40,adtm:locks=25,adtm:activity=15,adtm:hba=15,adtm:amprop=25,adtm:inet2=40,adtm:fmtty=25,adtm:trim2=40,adtm:lev=25,adtm:ident=25,adtm:bit2=40,adtm:cash2=40,adtm:spgbox=25,adtm:xrec=25,adtm:progress=10 count=200
SELECT inet_same_family('::1'::inet, '0.0.0.0/32'::inet), inet_merge('::1'::inet, '0.0.0.0/32'::inet)::text, ('::1'::inet << '0.0.0.0/32'::inet), ('::1'::inet &&  '0.0.0.0/32'::inet), ('::1'::inet >>= '0.0.0.0/32'::inet);
DROP TYPE IF EXISTS fz_adtm_mood CASCADE;
CREATE TYPE fz_adtm_mood AS ENUM ('sad', 'ok', 'happy');
SELECT ('ok'::fz_adtm_mood)::text, ('ok'::fz_adtm_mood > 'sad'::fz_adtm_mood)::text, enum_range(NULL::fz_adtm_mood)::text;
SELECT enum_first(NULL::fz_adtm_mood)::text, enum_last(NULL::fz_adtm_mood)::text, enum_range('sad'::fz_adtm_mood, 'ok'::fz_adtm_mood)::text;
SELECT min(m)::text, max(m)::text FROM (VALUES ('ok'::fz_adtm_mood), ('sad')) v(m);
DROP TYPE fz_adtm_mood;
SELECT (ROW(0, 'x') *<= ROW(2, 'x'))::text;
SELECT state, xact_start IS NOT NULL, query <> '' FROM pg_stat_activity WHERE pid = pg_backend_pid();
SELECT parse_ident('a."b""q".c', true)::text;
SELECT has_table_privilege(10, 'fz_wide'::regclass, 'SELECT'), has_table_privilege('fz_wide'::regclass, 'SELECT WITH GRANT OPTION');
SELECT btrim('\x001122330000'::bytea, '\x00'::bytea)::text, ltrim('\x0011'::bytea, '\x00'::bytea)::text, rtrim('\x110000'::bytea, '\x00'::bytea)::text, btrim(''::bytea, '\x00'::bytea)::text;
SELECT (pg_input_error_info('10.0.0.1/33', 'bytea')).sql_error_code, (pg_input_error_info('12abc', 'int4')).sql_error_code, pg_input_is_valid('$1,2,3', 'bytea'), pg_input_is_valid('10.0.0.1/33', 'money'), (pg_input_error_info('-32768', 'macaddr')).sql_error_code;
CREATE TABLE fz_amp (i int, t text, b box);
CREATE INDEX fz_amp_bt ON fz_amp USING btree (i DESC NULLS LAST, t);
CREATE INDEX fz_amp_hash ON fz_amp USING hash (i);
CREATE INDEX fz_amp_gist ON fz_amp USING gist (b);
CREATE INDEX fz_amp_spg ON fz_amp USING spgist (b);
CREATE INDEX fz_amp_brin ON fz_amp USING brin (i);
CREATE INDEX fz_amp_gin ON fz_amp USING gin (to_tsvector('simple', t));
SELECT p, pg_index_column_has_property('fz_amp_bt'::regclass, 1, p) FROM unnest(ARRAY['asc','desc','nulls_first','nulls_last','orderable','distance_orderable','returnable','search_array','search_nulls','bogus']) p ORDER BY p;
SELECT p, pg_index_has_property('fz_amp_bt'::regclass, p) FROM unnest(ARRAY['clusterable','index_scan','bitmap_scan','backward_scan','bogus']) p ORDER BY p;
SELECT p, pg_indexam_has_property((SELECT oid FROM pg_am WHERE amname = 'spgist'), p) FROM unnest(ARRAY['can_order','can_unique','can_multi_col','can_exclude','can_include','bogus']) p ORDER BY p;
DROP TABLE fz_amp;
CREATE TABLE fz_spg (b box);
INSERT INTO fz_spg SELECT box(point(x, y), point(x + w, y + w)) FROM generate_series(0, 12, 3) x, generate_series(0, 12, 3) y, generate_series(1, 5, 2) w;
CREATE INDEX fz_spg_idx ON fz_spg USING spgist (b);
SET enable_seqscan = off;
SELECT b::text FROM fz_spg WHERE b && box(point(5,5), point(14,15)) ORDER BY area(b), b::text;
RESET enable_seqscan;
DROP TABLE fz_spg;
SELECT type, database::text, user_name::text, address, netmask, auth_method, options::text, error FROM pg_hba_file_rules ORDER BY rule_number;
SELECT multirange(numrange(3.31, 4.5))::text;
SELECT pg_advisory_lock(452), pg_advisory_lock(452, 453), pg_advisory_lock_shared(454), pg_try_advisory_lock(455), pg_try_advisory_lock_shared(452, 7);
SELECT pg_try_advisory_xact_lock(456), pg_advisory_xact_lock_shared(452, 9);
SELECT locktype, database IS NOT NULL AS hasdb, classid, objid, objsubid, mode, granted, fastpath FROM pg_locks WHERE locktype = 'advisory' ORDER BY classid, objid, objsubid, mode;
SELECT pg_advisory_unlock_all();
SELECT (B'101' || B'0110')::text, (B'101' & B'110')::text, (B'101' | B'110')::text, (B'101' # B'110')::text, (~B'1010')::text, bit_length(B'10101');
SELECT translate('12345abc', '143', 'ax'), translate('', 'a', 'b'), translate('日本語', '本', '書'), repeat('ab', 3), repeat('x', 0), repeat('', 5);
SELECT ('10.1.2.3/25'::inet + 87)::text, ('10.1.2.3/25'::inet - 87)::text, ('10.1.2.3/25'::inet - '255.254.253.252'::inet), (~'10.1.2.3/25'::inet)::text, ('10.1.2.3/25'::inet & '255.254.253.252'::inet)::text, ('10.1.2.3/25'::inet | '255.254.253.252'::inet)::text;
SELECT initcap('hello tHE WORLD 3rd time'), initcap(''), initcap('über älter'), ascii('A'), ascii('日'), chr(66), chr(955);
SELECT (pg_input_error_info('nan', 'cidr')).sql_error_code, pg_input_is_valid('not-a-uuid', 'date'), pg_input_is_valid('0B11', 'int2'), (pg_input_error_info(' 42 ', 'money')).sql_error_code, pg_input_is_valid('-9223372036854775809', 'interval');
SELECT B'101'::bit(8);
SELECT (60343::bit(16))::text, (60343::bit(32))::text, (B'1000'::int4), (B'111111111111111111111111111111111111'::int8);
SELECT chr(0);
SELECT ('10/8'::cidr)::text, abbrev('172.16.5/24'::cidr), broadcast('fe80::1%1/64'::inet)::text;
SELECT pg_input_is_valid('-32768', 'oid'), pg_input_is_valid('-2147483649', 'box'), pg_input_is_valid('   ', 'bit(8)'), (pg_input_error_info('9223372036854775808', 'macaddr8')).sql_error_code, pg_input_is_valid('99999999999999999999999999', 'int4');
SELECT '0x1A'::int2::text, '0o17'::int4::text, '0b101'::int8::text, '1_000_000'::int4::text, '0x7fff_ffff'::int4::text, '-0x8000'::int2::text;
CREATE TABLE fz_lev (column_count int, colname text, col2 int);
SELECT clm FROM fz_lev;
UPDATE fz_lev SET clm = 1 WHERE false;
DROP TABLE fz_lev;
SELECT host('10.1.2.3/8'::inet), masklen('10.1.2.3/8'::inet), family('10.1.2.3/8'::inet), netmask('10.1.2.3/8'::inet)::text, hostmask('10.1.2.3/8'::inet)::text, network('10.1.2.3/8'::inet)::text;
SELECT (B'1011001110001111' >> 10)::text, (B'1011001110001111' << 10)::text, (B'101' >> 64)::text, (B'101' << 65)::text;
SELECT ('2001:db8::8:800:200c:417a/64'::inet + 727)::text, ('2001:db8::8:800:200c:417a/64'::inet - 727)::text, ('2001:db8::8:800:200c:417a/64'::inet - '0.0.0.0/32'::inet), (~'2001:db8::8:800:200c:417a/64'::inet)::text, ('2001:db8::8:800:200c:417a/64'::inet & '0.0.0.0/32'::inet)::text, ('2001:db8::8:800:200c:417a/64'::inet | '0.0.0.0/32'::inet)::text;
SELECT host('10.1.2.3/25'::inet), masklen('10.1.2.3/25'::inet), family('10.1.2.3/25'::inet), netmask('10.1.2.3/25'::inet)::text, hostmask('10.1.2.3/25'::inet)::text, network('10.1.2.3/25'::inet)::text;
SELECT parse_ident('x.y.z junk', false)::text;
CREATE TABLE fz_amp (i int, t text, b box);
CREATE INDEX fz_amp_bt ON fz_amp USING btree (i DESC NULLS LAST, t);
CREATE INDEX fz_amp_hash ON fz_amp USING hash (i);
CREATE INDEX fz_amp_gist ON fz_amp USING gist (b);
CREATE INDEX fz_amp_spg ON fz_amp USING spgist (b);
CREATE INDEX fz_amp_brin ON fz_amp USING brin (i);
CREATE INDEX fz_amp_gin ON fz_amp USING gin (to_tsvector('simple', t));
SELECT p, pg_index_column_has_property('fz_amp_brin'::regclass, 1, p) FROM unnest(ARRAY['asc','desc','nulls_first','nulls_last','orderable','distance_orderable','returnable','search_array','search_nulls','bogus']) p ORDER BY p;
SELECT p, pg_index_has_property('fz_amp_brin'::regclass, p) FROM unnest(ARRAY['clusterable','index_scan','bitmap_scan','backward_scan','bogus']) p ORDER BY p;
SELECT p, pg_indexam_has_property((SELECT oid FROM pg_am WHERE amname = 'gin'), p) FROM unnest(ARRAY['can_order','can_unique','can_multi_col','can_exclude','can_include','bogus']) p ORDER BY p;
DROP TABLE fz_amp;
SELECT ('92233720368547758.07'::money)::text, ('-.05'::money)::text, ('-92233720368547758.08'::money)::text, ('$0.009'::money)::text, ('($55.00)'::money)::text;
SELECT lpad('abc', 7), rpad('abc', 7, 'xy'), lpad('日本', 7, '語'), rpad('', 7, 'z'), lpad('abc', -1), rpad('abc', 0);
SELECT ('0/0'::cidr)::text, abbrev('0/0'::cidr), broadcast('::1'::inet)::text;
SELECT btrim('');
CREATE TABLE fz_lev (column_count int, colname text, col2 int);
SELECT 日本語のカラム FROM fz_lev;
UPDATE fz_lev SET 日本語のカラム = 1 WHERE false;
DROP TABLE fz_lev;
SELECT (pg_input_error_info('--5', 'date')).sql_error_code, pg_input_is_valid('not-a-uuid', 'money'), (pg_input_error_info('0x', 'macaddr8')).sql_error_code, (pg_input_error_info('1__0', 'bytea')).sql_error_code;
DROP TYPE IF EXISTS fz_adtm_mood CASCADE;
CREATE TYPE fz_adtm_mood AS ENUM ('sad', 'ok');
SELECT ('ok'::fz_adtm_mood)::text, ('ok'::fz_adtm_mood <= 'ok'::fz_adtm_mood)::text, enum_range(NULL::fz_adtm_mood)::text;
SELECT enum_first(NULL::fz_adtm_mood)::text, enum_last(NULL::fz_adtm_mood)::text, enum_range('sad'::fz_adtm_mood, 'ok'::fz_adtm_mood)::text;
SELECT min(m)::text, max(m)::text FROM (VALUES ('ok'::fz_adtm_mood), ('ok')) v(m);
SELECT 'grumpy'::fz_adtm_mood;
DROP TYPE fz_adtm_mood;
SELECT B'101'::bit(8);
SELECT (B'1011001110001111' >> 15)::text, (B'1011001110001111' << 15)::text, (B'101' >> 64)::text, (B'101' << 65)::text;
SELECT uuid_extract_version('017f22e2-79b0-7cc3-98c4-dc0c0c07398f')::text, uuid_extract_timestamp('017f22e2-79b0-7cc3-98c4-dc0c0c07398f')::text;
SELECT current_query();
CREATE TABLE fz_spg (b box);
INSERT INTO fz_spg SELECT box(point(x, y), point(x + w, y + w)) FROM generate_series(0, 12, 3) x, generate_series(0, 12, 3) y, generate_series(1, 5, 2) w;
CREATE INDEX fz_spg_idx ON fz_spg USING spgist (b);
SET enable_seqscan = off;
SELECT b::text FROM fz_spg WHERE b |&> box(point(4,3), point(14,11)) ORDER BY area(b), b::text;
RESET enable_seqscan;
DROP TABLE fz_spg;
SELECT state, xact_start IS NOT NULL, query <> '' FROM pg_stat_activity WHERE pid = pg_backend_pid();
SELECT cash_words('12.34'::money), cash_words('-0.05'::money);
SELECT ('92233720368547758.08'::money)::text;
SELECT regexp_split_to_array('50%', '[b ]', 'x')::text;
CREATE TABLE fz_spg (b box);
INSERT INTO fz_spg SELECT box(point(x, y), point(x + w, y + w)) FROM generate_series(0, 12, 3) x, generate_series(0, 12, 3) y, generate_series(1, 5, 2) w;
CREATE INDEX fz_spg_idx ON fz_spg USING spgist (b);
SET enable_seqscan = off;
SELECT b::text FROM fz_spg WHERE b |&> box(point(3,2), point(11,15)) ORDER BY area(b), b::text;
RESET enable_seqscan;
DROP TABLE fz_spg;
CREATE TABLE fz_xrec_out (id int, r text);
CREATE TYPE fz_xrec_t AS (a int, b text, c numeric);
DO $$ DECLARE x fz_xrec_t; y fz_xrec_t; z fz_xrec_out%ROWTYPE; BEGIN x := ROW(29, 'seed', 1.25); x.a := x.a + 1; x.b := x.b || '-x'; y := x; y.c := y.c * 2; y.b := NULL; z.id := 1; z.r := x::text || '|' || y::text; INSERT INTO fz_xrec_out VALUES (z.id, z.r); x := NULL; INSERT INTO fz_xrec_out VALUES (2, coalesce(x::text, '<null>')); END $$;
SELECT id, r FROM fz_xrec_out ORDER BY id;
DROP TABLE fz_xrec_out;
DROP TYPE fz_xrec_t;
SELECT format_type(1266, 65540), format_type(700, 6), format_type(20, 6), format_type(701, 4), format_type(1562, -1), format_type(19, 65540);
CREATE TABLE fz_spg (b box);
INSERT INTO fz_spg SELECT box(point(x, y), point(x + w, y + w)) FROM generate_series(0, 12, 3) x, generate_series(0, 12, 3) y, generate_series(1, 5, 2) w;
CREATE INDEX fz_spg_idx ON fz_spg USING spgist (b);
SET enable_seqscan = off;
SELECT b::text FROM fz_spg WHERE b &> box(point(0,5), point(12,13)) ORDER BY area(b), b::text;
RESET enable_seqscan;
DROP TABLE fz_spg;
CREATE TABLE fz_spg (b box);
INSERT INTO fz_spg SELECT box(point(x, y), point(x + w, y + w)) FROM generate_series(0, 12, 3) x, generate_series(0, 12, 3) y, generate_series(1, 5, 2) w;
CREATE INDEX fz_spg_idx ON fz_spg USING spgist (b);
SET enable_seqscan = off;
SELECT b::text FROM fz_spg WHERE b @> box(point(4,4), point(11,14)) ORDER BY area(b), b::text;
RESET enable_seqscan;
DROP TABLE fz_spg;
SELECT pg_advisory_lock(142), pg_advisory_lock(142, 143), pg_advisory_lock_shared(144), pg_try_advisory_lock(145), pg_try_advisory_lock_shared(142, 7);
SELECT pg_try_advisory_xact_lock(146), pg_advisory_xact_lock_shared(142, 9);
SELECT locktype, database IS NOT NULL AS hasdb, classid, objid, objsubid, mode, granted, fastpath FROM pg_locks WHERE locktype = 'advisory' ORDER BY classid, objid, objsubid, mode;
SELECT pg_advisory_unlock_all();
SELECT parse_ident('""', true)::text;
SELECT count(*) FROM pg_ident_file_mappings;
CREATE TABLE fz_amp (i int, t text, b box);
CREATE INDEX fz_amp_bt ON fz_amp USING btree (i DESC NULLS LAST, t);
CREATE INDEX fz_amp_hash ON fz_amp USING hash (i);
CREATE INDEX fz_amp_gist ON fz_amp USING gist (b);
CREATE INDEX fz_amp_spg ON fz_amp USING spgist (b);
CREATE INDEX fz_amp_brin ON fz_amp USING brin (i);
CREATE INDEX fz_amp_gin ON fz_amp USING gin (to_tsvector('simple', t));
SELECT p, pg_index_column_has_property('fz_amp_brin'::regclass, 1, p) FROM unnest(ARRAY['asc','desc','nulls_first','nulls_last','orderable','distance_orderable','returnable','search_array','search_nulls','bogus']) p ORDER BY p;
SELECT p, pg_index_has_property('fz_amp_brin'::regclass, p) FROM unnest(ARRAY['clusterable','index_scan','bitmap_scan','backward_scan','bogus']) p ORDER BY p;
SELECT p, pg_indexam_has_property((SELECT oid FROM pg_am WHERE amname = 'spgist'), p) FROM unnest(ARRAY['can_order','can_unique','can_multi_col','can_exclude','can_include','bogus']) p ORDER BY p;
DROP TABLE fz_amp;
CREATE TABLE fz_lev (column_count int, colname text, col2 int);
SELECT extremely_long_identifier_no_match_at_all_qq FROM fz_lev;
UPDATE fz_lev SET extremely_long_identifier_no_match_at_all_qq = 1 WHERE false;
DROP TABLE fz_lev;
SELECT parse_ident('a.b.c', true)::text;
SELECT get_bit(B'101101', 3), set_bit(B'101101', 2, 0)::text, overlay(B'10111000' placing B'01' from 3 for 2)::text, position(B'11' in B'00110'), bit_count(B'1101101');
SELECT lpad('abc', 10), rpad('abc', 10, 'xy'), lpad('日本', 10, '語'), rpad('', 10, 'z'), lpad('abc', -1), rpad('abc', 0);
CREATE TABLE fz_amp (i int, t text, b box);
CREATE INDEX fz_amp_bt ON fz_amp USING btree (i DESC NULLS LAST, t);
CREATE INDEX fz_amp_hash ON fz_amp USING hash (i);
CREATE INDEX fz_amp_gist ON fz_amp USING gist (b);
CREATE INDEX fz_amp_spg ON fz_amp USING spgist (b);
CREATE INDEX fz_amp_brin ON fz_amp USING brin (i);
CREATE INDEX fz_amp_gin ON fz_amp USING gin (to_tsvector('simple', t));
SELECT p, pg_index_column_has_property('fz_amp_gist'::regclass, 1, p) FROM unnest(ARRAY['asc','desc','nulls_first','nulls_last','orderable','distance_orderable','returnable','search_array','search_nulls','bogus']) p ORDER BY p;
SELECT p, pg_index_has_property('fz_amp_gist'::regclass, p) FROM unnest(ARRAY['clusterable','index_scan','bitmap_scan','backward_scan','bogus']) p ORDER BY p;
SELECT p, pg_indexam_has_property((SELECT oid FROM pg_am WHERE amname = 'brin'), p) FROM unnest(ARRAY['can_order','can_unique','can_multi_col','can_exclude','can_include','bogus']) p ORDER BY p;
DROP TABLE fz_amp;
SELECT ('12.34'::money::numeric)::text, (12.345::numeric::money)::text, (7::int4::money)::text, (9::int8::money)::text, ('12.34'::money::numeric::money)::text;
SELECT pg_input_is_valid('0o17', 'bit(8)'), pg_input_is_valid('-', 'date'), (pg_input_error_info('--5', 'bit(8)')).sql_error_code, pg_input_is_valid('0B11', 'uuid'), pg_input_is_valid('1.5', 'cidr');
SELECT '0x1A'::int2::text, '0o17'::int4::text, '0b101'::int8::text, '1_000_000'::int4::text, '0x7fff_ffff'::int4::text, '-0x8000'::int2::text;
CREATE TABLE fz_spg (b box);
INSERT INTO fz_spg SELECT box(point(x, y), point(x + w, y + w)) FROM generate_series(0, 12, 3) x, generate_series(0, 12, 3) y, generate_series(1, 5, 2) w;
CREATE INDEX fz_spg_idx ON fz_spg USING spgist (b);
SET enable_seqscan = off;
SELECT b::text FROM fz_spg WHERE b @> box(point(6,1), point(8,11)) ORDER BY area(b), b::text;
RESET enable_seqscan;
DROP TABLE fz_spg;
CREATE TABLE fz_xrec_out (id int, r text);
CREATE TYPE fz_xrec_t AS (a int, b text, c numeric);
DO $$ DECLARE x fz_xrec_t; y fz_xrec_t; z fz_xrec_out%ROWTYPE; BEGIN x := ROW(79, 'seed', 1.25); x.a := x.a + 1; x.b := x.b || '-x'; y := x; y.c := y.c * 2; y.b := NULL; z.id := 1; z.r := x::text || '|' || y::text; INSERT INTO fz_xrec_out VALUES (z.id, z.r); x := NULL; INSERT INTO fz_xrec_out VALUES (2, coalesce(x::text, '<null>')); END $$;
SELECT id, r FROM fz_xrec_out ORDER BY id;
DROP TABLE fz_xrec_out;
DROP TYPE fz_xrec_t;
SELECT pg_input_is_valid('1e5', 'money'), (pg_input_error_info('$1,2,3', 'oid')).sql_error_code, pg_input_is_valid('-2147483649', 'box'), pg_input_is_valid('12abc', 'regtype');
SELECT '0x1A'::int2::text, '0o17'::int4::text, '0b101'::int8::text, '1_000_000'::int4::text, '0x7fff_ffff'::int4::text, '-0x8000'::int2::text;
SELECT (log(2.5::numeric, 100::numeric))::text;
SELECT pg_advisory_lock(509), pg_advisory_lock(509, 510), pg_advisory_lock_shared(511), pg_try_advisory_lock(512), pg_try_advisory_lock_shared(509, 7);
SELECT pg_try_advisory_xact_lock(513), pg_advisory_xact_lock_shared(509, 9);
SELECT locktype, database IS NOT NULL AS hasdb, classid, objid, objsubid, mode, granted, fastpath FROM pg_locks WHERE locktype = 'advisory' ORDER BY classid, objid, objsubid, mode;
SELECT pg_advisory_unlock_all();
SELECT binary_upgrade_create_empty_extension('x', 'pg_catalog', false, '1.0', NULL, NULL, NULL);
SELECT (B'101' || B'0110')::text, (B'101' & B'110')::text, (B'101' | B'110')::text, (B'101' # B'110')::text, (~B'1010')::text, bit_length(B'10101');
SELECT ('1.23'::money * 2)::text, ('1.23'::money * 2.5::float8)::text, ('10'::money / 4)::text, ('10'::money / '2.50'::money), ('1.23'::money + '4.56'::money)::text, ('1.23'::money * -1)::text;
SELECT B'101'::bit(3)::text, B'10'::bit varying(5)::text, X'1F'::bit(8)::text, X'F'::bit(4)::text, B''::varbit::text;
SELECT length(repeat('ab', 8192) || 'tail');
SELECT regexp_replace('AbCdAb', '(a|b)', 'Z', 'x');
SELECT host('2001:db8::8:800:200c:417a/64'::inet), masklen('2001:db8::8:800:200c:417a/64'::inet), family('2001:db8::8:800:200c:417a/64'::inet), netmask('2001:db8::8:800:200c:417a/64'::inet)::text, hostmask('2001:db8::8:800:200c:417a/64'::inet)::text, network('2001:db8::8:800:200c:417a/64'::inet)::text;
SELECT type, database::text, user_name::text, address, netmask, auth_method, options::text, error FROM pg_hba_file_rules ORDER BY rule_number;
SELECT format_type(1700, 0), format_type(1083, 0), format_type(0, 6), format_type(25, 0);
SELECT (43739::bit(16))::text, (43739::bit(32))::text, (B'1000'::int4), (B'111111111111111111111111111111111111'::int8);
SELECT 'abcde' NOT SIMILAR TO '(ab)?cd';
SELECT set_masklen('::1'::inet, 15)::text, set_masklen('0/0'::cidr, 20)::text;
SELECT ('fe80::1%1/64'::inet + 303)::text, ('fe80::1%1/64'::inet - 303)::text, ('fe80::1%1/64'::inet - '255.254.253.252'::inet), (~'fe80::1%1/64'::inet)::text, ('fe80::1%1/64'::inet & '255.254.253.252'::inet)::text, ('fe80::1%1/64'::inet | '255.254.253.252'::inet)::text;
SELECT parse_ident('x.y.z junk', true)::text;
CREATE TABLE fz_amp (i int, t text, b box);
CREATE INDEX fz_amp_bt ON fz_amp USING btree (i DESC NULLS LAST, t);
CREATE INDEX fz_amp_hash ON fz_amp USING hash (i);
CREATE INDEX fz_amp_gist ON fz_amp USING gist (b);
CREATE INDEX fz_amp_spg ON fz_amp USING spgist (b);
CREATE INDEX fz_amp_brin ON fz_amp USING brin (i);
CREATE INDEX fz_amp_gin ON fz_amp USING gin (to_tsvector('simple', t));
SELECT p, pg_index_column_has_property('fz_amp_gist'::regclass, 1, p) FROM unnest(ARRAY['asc','desc','nulls_first','nulls_last','orderable','distance_orderable','returnable','search_array','search_nulls','bogus']) p ORDER BY p;
SELECT p, pg_index_has_property('fz_amp_gist'::regclass, p) FROM unnest(ARRAY['clusterable','index_scan','bitmap_scan','backward_scan','bogus']) p ORDER BY p;
SELECT p, pg_indexam_has_property((SELECT oid FROM pg_am WHERE amname = 'brin'), p) FROM unnest(ARRAY['can_order','can_unique','can_multi_col','can_exclude','can_include','bogus']) p ORDER BY p;
DROP TABLE fz_amp;
