-- fuzzgen seed=301 modules=expr=off,joins=off,subq=off,agg=off,win=off,dml=off,merge=off,txn=off,ddl=off,types=off,explain=off,util=off,part=off,objddl=off,idx=off,par=off,tsdl=off,cursor=off,views=off,geo=off,dtm=off,adtmisc=off,sqljson=off,plpg=off,coll=off,mbconv=off,xnum=off,nodes=off,obs=off,admin=off,objid=off,einterp=off,exd=off,spill=off,earm=off,pubsub=on weights= count=150
CREATE SUBSCRIPTION fz_sub2 CONNECTION 'dbname=fzdb' PUBLICATION fz_nopub WITH (connect = false, slot_name = NONE, enabled = false);
ALTER SUBSCRIPTION fz_sub2 SET PUBLICATION fz_nopub, fz_otherpub WITH (refresh = false);
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub2;
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, create_slot = true);
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, synchronous_commit = 'sometimes');
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, frobnicate = 1);
CREATE TABLE fz_pubt1 (id int PRIMARY KEY, v text, w int);
CREATE PUBLICATION fz_pub1 WITH (publish = 'delete');
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub1;
DROP TABLE IF EXISTS fz_pubt1;
CREATE TABLE fz_pubt2 (id int PRIMARY KEY, v text, w int);
CREATE TABLE fz_pubt3 (id int PRIMARY KEY, s text);
CREATE PUBLICATION fz_pub2 FOR TABLE fz_pubt2;
ALTER PUBLICATION fz_pub2 ADD TABLES IN SCHEMA public;
ALTER PUBLICATION fz_pub2 DROP TABLES IN SCHEMA public;
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub2;
DROP TABLE IF EXISTS fz_pubt2;
DROP TABLE IF EXISTS fz_pubt3;
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (slot_name = NONE);
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, copy_data = true);
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, synchronous_commit = 'sometimes');
DROP SUBSCRIPTION IF EXISTS fz_nosuchsub;
CREATE SUBSCRIPTION fz_sub2 CONNECTION 'dbname=fzdb' PUBLICATION fz_nopub WITH (connect = false, slot_name = NONE, enabled = false);
ALTER SUBSCRIPTION fz_sub2 SET (run_as_owner = true);
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub2;
CREATE TABLE fz_pubt1 (id int PRIMARY KEY, v text, w int);
CREATE PUBLICATION fz_pub1 FOR TABLE fz_pubt1 WHERE (id > 43 AND v IS NOT NULL) WITH (publish = 'update, truncate');
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub1;
DROP TABLE IF EXISTS fz_pubt1;
CREATE TABLE fz_pubt4 (id int PRIMARY KEY, v text, w int);
CREATE PUBLICATION fz_puberr FOR ALL TABLES;
CREATE PUBLICATION fz_pube2 FOR TABLE nosuch_table;
CREATE PUBLICATION fz_pube2 WITH (publish_generated_columns = 'sometimes');
DROP PUBLICATION IF EXISTS fz_puberr;
DROP TABLE IF EXISTS fz_pubt4;
CREATE PUBLICATION fz_pubs1;
CREATE SUBSCRIPTION fz_sub1 CONNECTION '' PUBLICATION fz_pubs1 WITH (connect = false, slot_name = NONE, enabled = false, create_slot = false, binary = false, binary = true);
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub1;
DROP PUBLICATION IF EXISTS fz_pubs1;
CREATE SUBSCRIPTION fz_sub2 CONNECTION 'dbname=fzdb' PUBLICATION fz_nopub WITH (connect = false, slot_name = NONE, enabled = false);
ALTER SUBSCRIPTION fz_sub2 DISABLE;
ALTER SUBSCRIPTION fz_sub2 ENABLE;
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub2;
CREATE SUBSCRIPTION fz_sub2 CONNECTION 'dbname=fzdb' PUBLICATION fz_nopub WITH (connect = false, slot_name = NONE, enabled = false);
ALTER SUBSCRIPTION fz_sub2 REFRESH PUBLICATION;
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub2;
CREATE TABLE fz_pubt2 (id int PRIMARY KEY, v text, w int);
CREATE TABLE fz_pubt3 (id int PRIMARY KEY, s text);
CREATE PUBLICATION fz_pub2 FOR TABLE fz_pubt2;
ALTER PUBLICATION fz_pub2 ADD TABLE fz_pubt3;
ALTER PUBLICATION fz_pub2 DROP TABLE fz_pubt3, fz_pubt2;
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub2;
DROP TABLE IF EXISTS fz_pubt2;
DROP TABLE IF EXISTS fz_pubt3;
CREATE PUBLICATION fz_pubs1;
CREATE SUBSCRIPTION fz_sub1 CONNECTION 'host=example.invalid port=5433 dbname=src user=fzuser' PUBLICATION fz_pubs1 WITH (connect = false, slot_name = NONE, enabled = false, create_slot = false, streaming = on, synchronous_commit = 'remote_apply');
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub1;
DROP PUBLICATION IF EXISTS fz_pubs1;
CREATE TABLE fz_pubt1 (id int PRIMARY KEY, v text, w int);
CREATE PUBLICATION fz_pub1 FOR TABLES IN SCHEMA public WITH (publish = 'insert, update, delete, truncate', publish_via_partition_root = false, publish_generated_columns = none);
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub1;
DROP TABLE IF EXISTS fz_pubt1;
CREATE PUBLICATION fz_pubs1;
CREATE SUBSCRIPTION fz_sub1 CONNECTION 'dbname=fzdb' PUBLICATION fz_pubs1 WITH (connect = false, slot_name = NONE, enabled = false, create_slot = false, two_phase = true, password_required = true, run_as_owner = true);
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub1;
DROP PUBLICATION IF EXISTS fz_pubs1;
CREATE SUBSCRIPTION fz_sub2 CONNECTION 'dbname=fzdb' PUBLICATION fz_nopub WITH (connect = false, slot_name = NONE, enabled = false);
ALTER SUBSCRIPTION fz_sub2 REFRESH PUBLICATION;
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub2;
CREATE TABLE fz_pubt2 (id int PRIMARY KEY, v text, w int);
CREATE TABLE fz_pubt3 (id int PRIMARY KEY, s text);
CREATE PUBLICATION fz_pub2 FOR TABLE fz_pubt2;
ALTER PUBLICATION fz_pub2 SET (publish = 'insert, update, delete, truncate');
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub2;
DROP TABLE IF EXISTS fz_pubt2;
DROP TABLE IF EXISTS fz_pubt3;
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, enabled = true);
DROP SUBSCRIPTION fz_nosuchsub;
DROP SUBSCRIPTION IF EXISTS fz_nosuchsub;
CREATE TABLE fz_pubt2 (id int PRIMARY KEY, v text, w int);
CREATE TABLE fz_pubt3 (id int PRIMARY KEY, s text);
CREATE PUBLICATION fz_pub2 FOR TABLE fz_pubt2;
ALTER PUBLICATION fz_pub2 RENAME TO fz_pub2r;
ALTER PUBLICATION fz_pub2r RENAME TO fz_pub2;
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub2;
DROP TABLE IF EXISTS fz_pubt2;
DROP TABLE IF EXISTS fz_pubt3;
CREATE TABLE fz_pubt1 (id int PRIMARY KEY, v text, w int);
CREATE PUBLICATION fz_pub1 FOR TABLES IN SCHEMA public WITH (publish_via_partition_root = false, publish_generated_columns = stored);
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub1;
DROP TABLE IF EXISTS fz_pubt1;
CREATE SUBSCRIPTION fz_sub2 CONNECTION 'dbname=fzdb' PUBLICATION fz_nopub WITH (connect = false, slot_name = NONE, enabled = false);
ALTER SUBSCRIPTION fz_sub2 SET (two_phase = false);
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub2;
CREATE TABLE fz_pubt1 (id int PRIMARY KEY, v text, w int);
CREATE PUBLICATION fz_pub1 FOR TABLE fz_pubt1 WHERE (id > 71 AND v IS NOT NULL) WITH (publish_generated_columns = none);
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub1;
DROP TABLE IF EXISTS fz_pubt1;
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p, p WITH (connect = false);
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (slot_name = NONE, enabled = false, create_slot = true);
CREATE TABLE fz_pubt1 (id int PRIMARY KEY, v text, w int);
CREATE PUBLICATION fz_pub1 FOR TABLE fz_pubt1 WHERE (id > 32 AND v IS NOT NULL) WITH (publish = 'delete');
SELECT pubname, puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot, pubgencols FROM pg_publication WHERE pubname LIKE 'fz\_%' ORDER BY pubname;
SELECT pubname, schemaname, tablename, attnames::text, rowfilter FROM pg_publication_tables WHERE pubname LIKE 'fz\_%' ORDER BY pubname, schemaname, tablename;
DROP PUBLICATION IF EXISTS fz_pub1;
DROP TABLE IF EXISTS fz_pubt1;
CREATE PUBLICATION fz_pubs1;
CREATE SUBSCRIPTION fz_sub1 CONNECTION 'host=localhost port=5432 dbname=fzdb' PUBLICATION fz_pubs1, fz_remote_pub WITH (connect = false, slot_name = NONE, enabled = false, create_slot = false, disable_on_error = true);
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub1;
DROP PUBLICATION IF EXISTS fz_pubs1;
CREATE SUBSCRIPTION fz_sub2 CONNECTION 'dbname=fzdb' PUBLICATION fz_nopub WITH (connect = false, slot_name = NONE, enabled = false);
ALTER SUBSCRIPTION fz_sub2 SKIP (lsn = '0/12345');
SELECT subname, subenabled, subbinary, substream, subtwophasestate, subdisableonerr, subpasswordrequired, subrunasowner, subfailover, subslotname, subsynccommit, subpublications::text, suborigin FROM pg_subscription WHERE subname LIKE 'fz\_%' ORDER BY subname;
DROP SUBSCRIPTION IF EXISTS fz_sub2;
ALTER SUBSCRIPTION fz_nosuchsub SKIP (lsn = 'notalsn');
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, frobnicate = 1);
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, create_slot = true);
DROP SUBSCRIPTION IF EXISTS fz_nosuchsub;
ALTER SUBSCRIPTION fz_nosuchsub DISABLE;
ALTER SUBSCRIPTION fz_nosuchsub SET (streaming = on);
ALTER SUBSCRIPTION fz_nosuchsub SET (streaming = on);
CREATE SUBSCRIPTION fz_sube CONNECTION 'dbname=x' PUBLICATION p WITH (connect = false, streaming = 'sideways');
DROP SUBSCRIPTION fz_nosuchsub;
