-- deck-w5-typerr: TYPE/FUNCTION/OPERATOR resolution ERROR-ARM deck (lane W5-TYPERR).
-- Probe superset for the typerr module: still-drainable ereport arms on the
-- parser resolution surface — parse_func.c / parse_coerce.c / parse_oper.c /
-- parse_type.c (line-gap-report-003 grain): ambiguous/unknown function and
-- operator resolution, cast lookup failures, polymorphic family-1 and
-- anycompatible (family-2) resolution errors, typmod application, aggregate/
-- window/SRF call-context errors, collation mismatch. Distinct from the
-- LD6/LD8 DDL error-arm decks: this is EXPRESSION error fuel — near-valid
-- expressions that fail late in resolution.
-- One statement per line (diffrunner --replay compatible). Every erroring
-- probe is isolated; intentional successes are fixtures/success-path drains
-- and are dropped in-section. Applied per-statement to BOTH engines before
-- module encoding; differential bar = full error identity (SQLSTATE + message).
-- ============================================================ fixtures ====
CREATE TABLE w5t_base (a int PRIMARY KEY, b text, c numeric(10,2));
INSERT INTO w5t_base VALUES (1, 'one', 1.10), (2, 'two', 2.20);
CREATE TYPE w5t_mood AS ENUM ('sad', 'ok', 'happy');
CREATE TYPE w5t_pair AS (x int, y text);
CREATE DOMAIN w5t_posint AS int CHECK (VALUE > 0);
CREATE DOMAIN w5t_arrdom AS int[];
CREATE TYPE w5t_range AS RANGE (subtype = int8, multirange_type_name = w5t_mrange);
-- ==================================================== typerr:poly1 ========
CREATE FUNCTION w5t_elem2(anyelement, anyelement) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_arr2(anyarray, anyarray) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_ea(anyelement, anyarray) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_rng2(anyrange, anyrange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_mr2(anymultirange, anymultirange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_rmr(anyrange, anymultirange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_emr(anyelement, anymultirange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_na(anynonarray) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_en(anyenum) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_aa1(anyarray) RETURNS anyelement LANGUAGE sql AS 'SELECT $1[1]';
CREATE FUNCTION w5t_reta(anyelement) RETURNS anyarray LANGUAGE sql AS 'SELECT ARRAY[$1]';
SELECT w5t_elem2(1, 'x'::text);
SELECT w5t_elem2(1.5, point '(1,2)');
SELECT w5t_elem2('a', 'b');
SELECT w5t_arr2(ARRAY[1], ARRAY['x'::text]);
SELECT w5t_arr2(1, 2);
SELECT w5t_arr2(ARRAY[1], 'nope'::text);
SELECT w5t_ea(1, ARRAY['x'::text]);
SELECT w5t_ea(1.5, ARRAY[1]);
SELECT w5t_ea(1, 2);
SELECT w5t_rng2(int8range(1,2), numrange(1,2));
SELECT w5t_rng2(1, 2);
SELECT w5t_rng2('[1,2)', '[3,4)');
SELECT w5t_mr2(int8multirange(), nummultirange());
SELECT w5t_mr2(1, 2);
SELECT w5t_mr2('{}', '{}');
SELECT w5t_rmr(int8range(1,2), nummultirange());
SELECT w5t_rmr('[1,2)', '{}');
SELECT w5t_emr(1.5, int8multirange());
SELECT w5t_na(ARRAY[1]);
SELECT w5t_na('{1}'::w5t_arrdom);
SELECT w5t_en(1);
SELECT w5t_en('sad'::w5t_mood);
SELECT w5t_aa1('not an array'::text);
SELECT w5t_aa1(stavalues1) FROM pg_statistic LIMIT 1;
SELECT w5t_arr2(stavalues1, stavalues2) FROM pg_statistic LIMIT 1;
SELECT w5t_reta('x');
SELECT w5t_elem2(NULL, NULL);
SELECT w5t_rng2(w5t_range(1,2), int8range(1,2));
SELECT w5t_rmr(int8range(1,2), '{[1,2)}'::w5t_mrange);
CREATE FUNCTION w5t_badsig1(anyelement) RETURNS anyrange LANGUAGE sql AS 'SELECT NULL';
CREATE FUNCTION w5t_badsig2(anyelement) RETURNS anymultirange LANGUAGE sql AS 'SELECT NULL';
CREATE FUNCTION w5t_badsig3(int) RETURNS anyelement LANGUAGE sql AS 'SELECT NULL';
CREATE FUNCTION w5t_badsig4(int) RETURNS internal LANGUAGE sql AS 'SELECT NULL';
DROP FUNCTION w5t_elem2(anyelement, anyelement);
DROP FUNCTION w5t_arr2(anyarray, anyarray);
DROP FUNCTION w5t_ea(anyelement, anyarray);
DROP FUNCTION w5t_rng2(anyrange, anyrange);
DROP FUNCTION w5t_mr2(anymultirange, anymultirange);
DROP FUNCTION w5t_rmr(anyrange, anymultirange);
DROP FUNCTION w5t_emr(anyelement, anymultirange);
DROP FUNCTION w5t_na(anynonarray);
DROP FUNCTION w5t_en(anyenum);
DROP FUNCTION w5t_aa1(anyarray);
DROP FUNCTION w5t_reta(anyelement);
-- ==================================================== typerr:poly2 ========
CREATE FUNCTION w5t_c2(anycompatible, anycompatible) RETURNS anycompatible LANGUAGE sql AS 'SELECT $1';
CREATE FUNCTION w5t_ca(anycompatiblearray, anycompatible) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_caonly(anycompatiblearray) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_cr(anycompatiblerange, anycompatible) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_cr2(anycompatiblerange, anycompatiblerange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_cm(anycompatiblemultirange, anycompatible) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_cm2(anycompatiblemultirange, anycompatiblemultirange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_crm(anycompatiblerange, anycompatiblemultirange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_cna(anycompatiblenonarray) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_cronly(anycompatiblerange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_cmonly(anycompatiblemultirange) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_retca(anycompatible) RETURNS anycompatiblearray LANGUAGE sql AS 'SELECT ARRAY[$1]';
SELECT w5t_c2(1, point '(1,2)');
SELECT w5t_c2(1, 2.5);
SELECT w5t_ca(1, 2);
SELECT w5t_ca(ARRAY[1], point '(1,2)');
SELECT w5t_ca(ARRAY[1], 2.5);
SELECT w5t_caonly('{1}');
SELECT w5t_cr(int8range(1,2), point '(1,2)');
SELECT w5t_cr(int8range(1,2), 1.5);
SELECT w5t_cr(1, 2);
SELECT w5t_cr2(int8range(1,2), numrange(1,2));
SELECT w5t_cm(int8multirange(), point '(1,2)');
SELECT w5t_cm(int8multirange(), 1.5);
SELECT w5t_cm(1, 2);
SELECT w5t_cm2(int8multirange(), nummultirange());
SELECT w5t_crm(int8range(1,2), nummultirange());
SELECT w5t_crm(numrange(1,2), '{}');
SELECT w5t_cna(ARRAY[1]);
SELECT w5t_cna('{1}'::w5t_arrdom);
SELECT w5t_cronly('[1,2)');
SELECT w5t_cmonly('{}');
SELECT w5t_retca('x');
SELECT w5t_c2('a', 'b');
CREATE FUNCTION w5t_badsig5(int) RETURNS anycompatible LANGUAGE sql AS 'SELECT NULL';
CREATE FUNCTION w5t_badsig6(anycompatible) RETURNS anycompatiblerange LANGUAGE sql AS 'SELECT NULL';
CREATE FUNCTION w5t_badsig7(anycompatible) RETURNS anycompatiblemultirange LANGUAGE sql AS 'SELECT NULL';
DROP FUNCTION w5t_c2(anycompatible, anycompatible);
DROP FUNCTION w5t_ca(anycompatiblearray, anycompatible);
DROP FUNCTION w5t_caonly(anycompatiblearray);
DROP FUNCTION w5t_cr(anycompatiblerange, anycompatible);
DROP FUNCTION w5t_cr2(anycompatiblerange, anycompatiblerange);
DROP FUNCTION w5t_cm(anycompatiblemultirange, anycompatible);
DROP FUNCTION w5t_cm2(anycompatiblemultirange, anycompatiblemultirange);
DROP FUNCTION w5t_crm(anycompatiblerange, anycompatiblemultirange);
DROP FUNCTION w5t_cna(anycompatiblenonarray);
DROP FUNCTION w5t_cronly(anycompatiblerange);
DROP FUNCTION w5t_cmonly(anycompatiblemultirange);
DROP FUNCTION w5t_retca(anycompatible);
-- ==================================================== typerr:funcres ======
SELECT w5t_nosuchfunc(1);
SELECT w5t_nosuchfunc();
SELECT abs('a'::text);
SELECT abs(1, 2);
SELECT nosuchschema.f(1);
SELECT pg_catalog.w5t_nosuchfunc(1);
SELECT length(1, point '(1,2)', 'x');
CREATE FUNCTION w5t_amb(a int, b text) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_amb(a text, b int) RETURNS int LANGUAGE sql AS 'SELECT 2';
SELECT w5t_amb('1', '2');
SELECT w5t_amb(NULL, NULL);
DROP FUNCTION w5t_amb(int, text);
DROP FUNCTION w5t_amb(text, int);
SELECT percentile_cont(0.5);
SELECT percentile_cont(0.5, 0.7) WITHIN GROUP (ORDER BY 1);
SELECT percentile_cont(0.5, 0.6, 0.7) WITHIN GROUP (ORDER BY 1);
SELECT rank(1, 2) WITHIN GROUP (ORDER BY 1);
SELECT rank('x') WITHIN GROUP (ORDER BY 1, 2);
SELECT dense_rank(1, 2, 3) WITHIN GROUP (ORDER BY 1);
SELECT mode(1) WITHIN GROUP (ORDER BY a) FROM w5t_base;
SELECT concat(VARIADIC 1);
SELECT concat(VARIADIC point '(1,2)');
SELECT format(VARIADIC 'x'::text);
SELECT abs(*);
SELECT sum(*);
SELECT count(x => 1);
SELECT sum(b => a) FROM w5t_base;
CREATE TYPE w5t_shell;
SELECT w5t_shell('x');
SELECT NULL::w5t_shell;
CREATE PROCEDURE w5t_proc(int) LANGUAGE sql AS 'SELECT 1';
SELECT w5t_proc(1);
CALL abs(1);
CALL w5t_nosuchproc(1);
CALL w5t_proc('x'::point);
DROP PROCEDURE w5t_proc(int);
SELECT 1 FROM w5t_base WHERE w5t_base.nosuchcol > 0;
SELECT w5t_base.b(a) FROM w5t_base;
-- ==================================================== typerr:aggwin =======
SELECT sum(DISTINCT a) OVER () FROM w5t_base;
SELECT sum(a ORDER BY a) OVER () FROM w5t_base;
SELECT row_number() FILTER (WHERE true) OVER () FROM w5t_base;
SELECT row_number();
SELECT lead(a) FROM w5t_base;
SELECT sum(1) WITHIN GROUP (ORDER BY 1);
SELECT count(*) WITHIN GROUP (ORDER BY 1);
SELECT percentile_cont(DISTINCT 0.5) WITHIN GROUP (ORDER BY 1);
SELECT percentile_cont(VARIADIC ARRAY[0.5]) WITHIN GROUP (ORDER BY 1);
SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY 1) OVER () FROM w5t_base;
SELECT row_number(*) OVER () FROM w5t_base;
SELECT lead(*) OVER () FROM w5t_base;
SELECT count(generate_series(1, 2)) FROM w5t_base;
SELECT sum(a) OVER (ORDER BY generate_series(1, 2)) FROM w5t_base;
SELECT row_number() OVER (), generate_series(1, row_number() OVER ()) FROM w5t_base;
SELECT count(*) OVER (PARTITION BY sum(a)) FROM w5t_base;
SELECT sum(count(*)) FROM w5t_base;
-- ==================================================== typerr:srfplace =====
SELECT 1 FROM w5t_base t1 JOIN w5t_base t2 ON generate_series(1, 2) = 1;
SELECT 1 FROM w5t_base WHERE generate_series(1, 2) = 1;
SELECT 1 FROM w5t_base GROUP BY a HAVING generate_series(1, 2) = 1;
SELECT count(*) FILTER (WHERE generate_series(1, 2) = 1) FROM w5t_base;
SELECT count(*) OVER (PARTITION BY generate_series(1, 2)) FROM w5t_base;
SELECT count(*) OVER (ORDER BY a ROWS BETWEEN generate_series(1, 2) PRECEDING AND CURRENT ROW) FROM w5t_base;
UPDATE w5t_base SET a = generate_series(1, 2) WHERE false;
SELECT 1 LIMIT generate_series(1, 2);
SELECT 1 OFFSET generate_series(1, 2);
INSERT INTO w5t_base VALUES (99, 'z', 0) RETURNING generate_series(1, 2);
INSERT INTO w5t_base VALUES (generate_series(90, 92), 'z', 0), (98, 'z', 0);
CREATE POLICY w5t_pol ON w5t_base USING (generate_series(a, 2) = 1);
ALTER TABLE w5t_base ADD CONSTRAINT w5t_chk CHECK (generate_series(a, 2) = 1);
CREATE DOMAIN w5t_baddom AS int CHECK (generate_series(VALUE, 2) = 1);
ALTER TABLE w5t_base ADD COLUMN zdef int DEFAULT generate_series(1, 2);
CREATE FUNCTION w5t_dfl(x int DEFAULT generate_series(1, 2)) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE INDEX w5t_badidx ON w5t_base ((generate_series(a, 2)));
CREATE INDEX w5t_badidx2 ON w5t_base (a) WHERE generate_series(a, 2) = 1;
CREATE STATISTICS w5t_badstat ON (generate_series(a, 2)), a FROM w5t_base;
ALTER TABLE w5t_base ALTER COLUMN a TYPE bigint USING generate_series(a, 2);
PREPARE w5t_prep(int) AS SELECT $1;
EXECUTE w5t_prep(generate_series(1, 2));
DEALLOCATE w5t_prep;
CREATE TABLE w5t_plist (i int) PARTITION BY LIST (i);
CREATE TABLE w5t_plist1 PARTITION OF w5t_plist FOR VALUES IN (generate_series(1, 2));
DROP TABLE w5t_plist;
CREATE TABLE w5t_pkey (i int) PARTITION BY RANGE ((generate_series(i, 2)));
CREATE PROCEDURE w5t_proc2(int) LANGUAGE sql AS 'SELECT 1';
CALL w5t_proc2(generate_series(1, 2));
DROP PROCEDURE w5t_proc2(int);
COPY w5t_base FROM '/nonexistent/w5t' WHERE generate_series(a, 2) = 1;
ALTER TABLE w5t_base ADD COLUMN zgen int GENERATED ALWAYS AS (generate_series(a, 2)) STORED;
WITH RECURSIVE t(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM t WHERE n < 3) CYCLE n SET c TO generate_series(1, 2) DEFAULT 0 USING p SELECT * FROM t;
SELECT CASE WHEN a > 0 THEN generate_series(1, 2) ELSE 0 END FROM w5t_base;
SELECT COALESCE(generate_series(1, 2), 0) FROM w5t_base;
SELECT 1 FROM w5t_base ORDER BY generate_series(1, a);
SELECT generate_series(1, a) FROM w5t_base GROUP BY 1;
-- ==================================================== typerr:typmod =======
SELECT 1::int(4);
SELECT 'x'::text(10);
SELECT 'x'::point(2);
SELECT 1.5::numeric(1000);
SELECT 1.5::numeric(2, 5);
SELECT 1.5::numeric(0);
SELECT ''::varchar(0);
SELECT ''::varchar(1 + 1);
SELECT now()::timestamp(-1);
SELECT ''::bit(0);
SELECT ''::interval(20);
SELECT ''::interval second(20);
CREATE TYPE w5t_shell2;
SELECT NULL::w5t_shell2(4);
SELECT 'w5t_shell2'::regtype;
SELECT 'nosuchtype_w5t'::regtype;
SELECT 'int('::regtype;
SELECT 'int4 int4'::regtype;
SELECT to_regtype('nosuchtype_w5t');
SELECT to_regtype('w5t_shell2');
SELECT to_regtype('int(');
SELECT NULL::nosuchtype_w5t;
SELECT NULL::nosuchschema.nosuchtype;
SELECT NULL::pg_catalog.nosuchtype_w5t;
CREATE FUNCTION w5t_pt1(x w5t_base%TYPE) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_pt2(x w5t_base.a%TYPE) RETURNS int LANGUAGE sql AS 'SELECT 1';
DROP FUNCTION w5t_pt2(int);
CREATE FUNCTION w5t_pt3(x public.w5t_base.a%TYPE) RETURNS int LANGUAGE sql AS 'SELECT 1';
DROP FUNCTION w5t_pt3(int);
CREATE FUNCTION w5t_pt4(x w5t_base.nosuchcol%TYPE) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_pt5(x nosuchtbl_w5t.a%TYPE) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_pt6(x a.b.c.d.e%TYPE) RETURNS int LANGUAGE sql AS 'SELECT 1';
SELECT NULL::w5t_posint(4);
SELECT '(1,2)'::point[](3);
-- ==================================================== typerr:castres ======
SELECT CAST(point '(1,2)' AS int);
SELECT CAST(now() AS int);
SELECT CAST(true AS point);
SELECT CAST(x'ff' AS point);
SELECT CAST('(1,2)'::point AS circle)::point;
SELECT CAST(ARRAY[point '(1,2)'] AS int[]);
SELECT CAST(ARRAY[1] AS point[]);
SELECT CAST(ROW(1) AS w5t_pair);
SELECT CAST(ROW(1, 'x', 2) AS w5t_pair);
SELECT CAST(ROW(point '(1,2)', 'x') AS w5t_pair);
SELECT CAST(ROW(1, 'x') AS w5t_pair);
SELECT CAST(ROW(NULL, NULL) AS w5t_pair);
SELECT CAST(x AS w5t_pair) FROM (SELECT ROW(1, 'x') AS x) s;
SELECT CAST(t AS w5t_pair) FROM w5t_base t;
SELECT CAST(ROW(1, 'x') AS w5t_mood);
SELECT CAST('sad' AS w5t_mood)::int;
SELECT (-1)::w5t_posint;
SELECT 'x'::w5t_posint;
SELECT NULL::w5t_posint::point;
SELECT 1 FROM w5t_base WHERE a;
SELECT 1 FROM w5t_base WHERE b;
SELECT CASE WHEN 1 THEN 2 ELSE 3 END;
SELECT CASE WHEN point '(1,2)' THEN 2 ELSE 3 END;
SELECT 1 LIMIT point '(1,2)';
SELECT 1 LIMIT 'x';
SELECT 1 OFFSET point '(1,2)';
SELECT 1 FETCH FIRST point '(1,2)' ROWS ONLY;
SELECT CASE WHEN true THEN 1 ELSE point '(1,2)' END;
SELECT CASE WHEN true THEN 'abc' ELSE 5 END;
SELECT 1 UNION SELECT point '(1,2)';
SELECT 1 INTERSECT SELECT point '(1,2)';
SELECT 1 EXCEPT SELECT 'x'::text;
SELECT ARRAY[1, point '(1,2)'];
SELECT ARRAY[1, 'x'::text];
SELECT COALESCE(1, point '(1,2)');
SELECT GREATEST(1, point '(1,2)');
SELECT LEAST('x'::text, 1);
SELECT NULLIF(1, point '(1,2)');
SELECT * FROM (VALUES (1), (point '(1,2)')) v;
SELECT a FROM w5t_base UNION SELECT b FROM w5t_base ORDER BY nosuchcol;
-- ==================================================== typerr:operres ======
SELECT 1 <=> 2;
SELECT 1 ~~~~ 2;
SELECT point '(1,2)' + 'x'::text;
SELECT 'a'::text # 'b'::text;
SELECT '1' # '2';
SELECT @ 'x'::text;
SELECT @ '1';
SELECT |/ 'x'::text;
SELECT 1 = ANY (7);
SELECT 1 = ANY ('x'::text);
SELECT 1 + ANY (ARRAY[1, 2]);
SELECT 1 = ALL (42);
SELECT ROW(1) = ANY ('{}');
SELECT 1 <=> ANY (ARRAY[1]);
CREATE FUNCTION w5t_setof(int, int) RETURNS SETOF bool LANGUAGE sql AS 'SELECT true';
CREATE OPERATOR ==# (leftarg = int, rightarg = int, procedure = w5t_setof);
SELECT 1 ==# ANY (ARRAY[1, 2]);
DROP OPERATOR ==# (int, int);
DROP FUNCTION w5t_setof(int, int);
CREATE OPERATOR ### (leftarg = int, rightarg = int, procedure = int4pl, commutator = ###>);
SELECT 1 ###> 2;
SELECT 1 OPERATOR(public.###>) 2;
DROP OPERATOR ### (int, int);
DROP OPERATOR ###> (int, int);
CREATE OPERATOR <<# (leftarg = int4, rightarg = int4, procedure = int4lt);
CREATE AGGREGATE w5t_ag (basetype = int2, sfunc = int2smaller, stype = int2, sortop = <<#);
DROP AGGREGATE IF EXISTS w5t_ag (int2);
DROP OPERATOR <<# (int4, int4);
SELECT 5 !;
SELECT OPERATOR(pg_catalog.+) 1;
SELECT 1 OPERATOR(pg_catalog.<=>) 2;
SELECT 1 OPERATOR(nosuchschema.+) 2;
DROP OPERATOR nosuchop (int, int);
DROP OPERATOR + (nosuchtype_w5t, int);
DROP OPERATOR + (NONE, NONE);
COMMENT ON OPERATOR <=> (int, int) IS 'x';
-- ==================================================== typerr:collmix ======
SELECT 'a' COLLATE "C" < 'b' COLLATE "POSIX";
SELECT 'a' COLLATE "C" || ('b' COLLATE "POSIX");
SELECT 1 COLLATE "C";
SELECT now() COLLATE "C";
SELECT 'a' COLLATE nosuchcoll_w5t;
SELECT 'a'::text COLLATE "C" IN ('b' COLLATE "POSIX", 'c');
CREATE TABLE w5t_coll (t text COLLATE "C", u text COLLATE "POSIX");
INSERT INTO w5t_coll VALUES ('a', 'b');
SELECT t < u FROM w5t_coll;
SELECT t || u < t FROM w5t_coll;
SELECT greatest(t, u) FROM w5t_coll;
DROP TABLE w5t_coll;
-- ==================================================== typerr:funcddl2 =====
DROP FUNCTION w5t_nosuchf(int);
DROP FUNCTION w5t_nosuchf;
DROP FUNCTION IF EXISTS w5t_nosuchf(int);
DROP AGGREGATE w5t_nosuchagg(int);
DROP AGGREGATE w5t_nosuchagg(*);
DROP AGGREGATE w5t_nosuchagg;
DROP AGGREGATE abs(int);
DROP AGGREGATE IF EXISTS abs(int);
DROP PROCEDURE abs(int);
DROP PROCEDURE w5t_nosuchproc;
DROP ROUTINE w5t_nosuchr(int);
DROP ROUTINE w5t_nosuchr;
CREATE PROCEDURE w5t_donly(int) LANGUAGE sql AS 'SELECT 1';
DROP FUNCTION w5t_donly(int);
DROP AGGREGATE w5t_donly(int);
DROP PROCEDURE w5t_donly(int);
CREATE FUNCTION w5t_over(int) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION w5t_over(text) RETURNS int LANGUAGE sql AS 'SELECT 1';
DROP FUNCTION w5t_over;
DROP ROUTINE w5t_over;
COMMENT ON FUNCTION w5t_over IS 'x';
DROP FUNCTION w5t_over(int);
DROP FUNCTION w5t_over(text);
CREATE PROCEDURE w5t_provl(int) LANGUAGE sql AS 'SELECT 1';
CREATE PROCEDURE w5t_provl(text) LANGUAGE sql AS 'SELECT 1';
DROP PROCEDURE w5t_provl;
DROP PROCEDURE w5t_provl(int);
DROP PROCEDURE w5t_provl(text);
DROP AGGREGATE count;
DROP AGGREGATE sum(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int);
DROP FUNCTION w5t_nosuchf(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int);
DROP PROCEDURE w5t_nosuchproc(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int);
ALTER FUNCTION w5t_nosuchf(int) OWNER TO CURRENT_USER;
ALTER ROUTINE w5t_nosuchr(int) RENAME TO w5t_nosuchr2;
COMMENT ON FUNCTION w5t_nosuchf(int) IS 'x';
COMMENT ON AGGREGATE w5t_nosuchagg(int) IS 'x';
COMMENT ON PROCEDURE w5t_nosuchproc(int) IS 'x';
-- ======================================================== teardown ========
DROP TYPE w5t_shell;
DROP TYPE w5t_shell2;
DROP TYPE w5t_range;
DROP DOMAIN w5t_arrdom;
DROP DOMAIN w5t_posint;
DROP TYPE w5t_pair;
DROP TYPE w5t_mood;
DROP TABLE w5t_base;
