#!/usr/bin/env python3
"""Generate crates/bin/fuzzgen/src/stem_data.rs from the REL_18_3 snowball
C sources (LD3 stemmer-drain lane).

The snowball stemmers are edge-branch hollow: every suffix rule is one
among-table entry plus a per-arm action, and the shipped 8-word pools in
rich::TS_LANGS fire only a handful of arms per language.  Draining them
means feeding every suffix through ts_lexize.  The ground truth for "every
suffix" is the generated C itself: each stem_UTF_8_<lang>.c stores its
among-table strings as `static const symbol s_G_I[N] = { ... };` byte
arrays (forward byte order — find_among_b indexes from the tail).  This
script decodes every such array, dedupes per language, and emits a static
Rust table the fuzzgen `tsdl:stemdrain` production walks exhaustively via
a per-language cursor.

Provenance: run against the pinned REL_18_3 checkout (62d6c7d) under
cpg-cov/src (scripts/gapreport.sh build) or any checkout of the same tag:

    python3 fuzz/gen_stem_data.py cpg-cov/src/src/backend/snowball/libstemmer \
        > crates/bin/fuzzgen/src/stem_data.rs

The union deliberately includes non-suffix strings (prelude/replacement
strings, single letters): appended to a base they are harmless word
material, and bare they exercise the short-word / R1-empty failure arms.
"""

import re
import sys
from pathlib import Path

ARRAY_RE = re.compile(
    r"static const symbol s_(\d+)_(\d+)\[\d+\]\s*=\s*\{([^}]*)\};"
)
ELEM_RE = re.compile(r"0[xX][0-9a-fA-F]+|\d+|'(?:\\.|[^'\\])'")


def decode_elem(tok: str) -> int:
    if tok.startswith("'"):
        body = tok[1:-1]
        if body.startswith("\\"):
            return ord(body[1:].encode().decode("unicode_escape"))
        return ord(body)
    return int(tok, 0)


def extract(path: Path):
    """All among-table strings in the file, deduped, source order kept."""
    text = path.read_text()
    seen = set()
    out = []
    for m in ARRAY_RE.finditer(text):
        raw = bytes(decode_elem(t) for t in ELEM_RE.findall(m.group(3)))
        try:
            s = raw.decode("utf-8")
        except UnicodeDecodeError:
            continue  # not expected in the UTF_8_* sources
        if s and s not in seen:
            seen.add(s)
            out.append(s)
    return out


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    srcdir = Path(sys.argv[1])
    files = sorted(srcdir.glob("stem_UTF_8_*.c"))
    if not files:
        sys.exit(f"no stem_UTF_8_*.c under {srcdir}")
    print("//! GENERATED by fuzz/gen_stem_data.py from the pinned REL_18_3")
    print("//! snowball C sources (see that script for provenance) — do not")
    print("//! hand-edit.  Per-language among-table string unions for the")
    print("//! tsdl:stemdrain production.")
    print()
    print("/// One snowball language's drain material.")
    print("pub struct StemSuffixes {")
    print("    /// Language name as spelled in `TEMPLATE = snowball, Language =`.")
    print("    pub lang: &'static str,")
    print("    /// Every distinct among-table string in the language's stemmer.")
    print("    pub suffixes: &'static [&'static str],")
    print("}")
    print()
    total = 0
    entries = []
    for f in files:
        lang = f.stem.replace("stem_UTF_8_", "")
        sufs = extract(f)
        total += len(sufs)
        entries.append((lang, sufs))
        print(f"static SUF_{lang.upper()}: &[&str] = &[")
        line = "   "
        for s in sufs:
            tok = " " + rust_str(s) + ","
            if len(line) + len(tok) > 96:
                print(line)
                line = "   "
            line += tok
        if line.strip():
            print(line)
        print("];")
        print()
    print(f"/// {total} strings over {len(entries)} languages.")
    print("pub const STEM_SUFFIXES: &[StemSuffixes] = &[")
    for lang, sufs in entries:
        print(
            f"    StemSuffixes {{ lang: {rust_str(lang)}, "
            f"suffixes: SUF_{lang.upper()} }},  // {len(sufs)}"
        )
    print("];")


if __name__ == "__main__":
    main()
