#!/usr/bin/env python3
"""Generate crates/bin/fuzzgen/src/stem_reach.rs from the pinned REL_18_3
snowball C sources (W4-STEM targeted-synthesis lane).

The line-grain snowball residue after the LD3/LD10 suffix sweeps is
context-conditioned: arms whose guard needs a specific STEM to the left
of the suffix.  The biggest mechanizable family is the greek stemmer:
most of its r_step_* rules are "[suffix] delete, then repair iff the
remaining stem is in an exception among-table" — several hundred
exception stems (a_1, a_10, a_13, a_17, a_25 ... a_64), each reachable
only by an input word = exception-stem + step-suffix (bare for the
`atlimit` whole-word classes, prefixed for the ends-with classes).

This script parses the generated C directly: for every greek r_step_*
function it collects the rule's suffix strings (both `eq_s_b` literals
and the first find_among_b table) and the exception stems (every later
find_among_b table), and emits the cross products — bare and with a
neutral "παρα" prefix — plus the r_step_1 irregular whole-word forms
and a vowel-final stem variant for each eq_s_b suffix (the
vowel-preceded repair arms).  Verified against the in-lane cpg-cov
build: this table alone drains ~120 greek lines the curated pools miss.

Provenance: run against the pinned REL_18_3 checkout (62d6c7d), e.g.

    python3 fuzz/gen_stem_reach.py \
        cpg-cov/src/src/backend/snowball/libstemmer \
        > crates/bin/fuzzgen/src/stem_reach.rs

Swept by the fuzzgen `tsdl:stemvocab` cursor after the curated
STEM_VOCAB pools (see tsdl.rs).
"""

import collections
import re
import sys
from pathlib import Path

SYM_RE = re.compile(r"static const symbol (s_\d+(?:_\d+)?)\[\d*\]\s*=\s*\{([^}]*)\};")
ELEM_RE = re.compile(r"0[xX][0-9a-fA-F]+|\d+|'(?:\\.|[^'\\])'")
AMONG_RE = re.compile(r"static const struct among (a_\d+)\[(\d+)\]\s*=\s*\{(.*?)\n\};", re.S)
ENTRY_RE = re.compile(r"\{\s*(-?\d+),\s*(s_\d+_\d+|0),\s*(-?\d+),\s*(-?\d+),\s*(\S+?)\s*\}")
FN_RE = re.compile(r"(?:static int|extern int) (\w+)\(struct SN_env")


def decode_syms(text):
    sym = {}
    for m in SYM_RE.finditer(text):
        bs = []
        for t in ELEM_RE.findall(m.group(2)):
            if t.startswith("'"):
                body = t[1:-1]
                bs.append(ord(body[1:].encode().decode("unicode_escape")) if body.startswith("\\") else ord(body))
            else:
                bs.append(int(t, 0))
        try:
            sym[m.group(1)] = bytes(bs).decode("utf-8")
        except UnicodeDecodeError:
            pass
    return sym


def parse(path):
    text = path.read_text()
    sym = decode_syms(text)
    among = {}
    for m in AMONG_RE.finditer(text):
        entries = []
        for em in ENTRY_RE.finditer(m.group(3)):
            s = sym.get(em.group(2), "") if em.group(2) != "0" else ""
            entries.append(s)
        among[m.group(1)] = entries
    # function bodies with their find_among tables + eq_s_b strings
    funcs = {}
    lines = text.split("\n")
    cur, start = None, 0
    for i, ln in enumerate(lines):
        fm = FN_RE.match(ln)
        if fm and ln.rstrip().endswith("{"):
            if cur:
                funcs[cur] = "\n".join(lines[start:i])
            cur, start = fm.group(1), i
    if cur:
        funcs[cur] = "\n".join(lines[start:])
    return sym, among, funcs


def greek_words(srcdir):
    sym, among, funcs = parse(srcdir / "stem_UTF_8_greek.c")
    words = set(w for w in among.get("a_1", []) if w)  # step-1 irregulars
    for fn, body in funcs.items():
        if not fn.startswith("r_step"):
            continue
        tabs = re.findall(r"find_among(?:_b)?\(z, (a_\d+), \d+\)", body)
        eqs = [sym[m] for m in re.findall(r"eq_s_b\(z, \d+, (s_\d+)\)", body) if m in sym]
        sufs = list(dict.fromkeys(eqs))
        if tabs:
            t0 = sorted((s for s in among[tabs[0]] if s), key=len)
            if t0:
                sufs += [t0[0], t0[-1], t0[len(t0) // 2]]
        sufs = list(dict.fromkeys(sufs))[:6]
        exc = set()
        for t in tabs[1:]:
            exc.update(s for s in among[t] if s)
        for e in exc:
            for s in sufs:
                words.add(e + s)
                words.add("παρα" + e + s)
        for s in eqs:
            words.add("ακου" + s)
            words.add("θεα" + s)
    return sorted(words)


def main():
    srcdir = Path(sys.argv[1])
    words = greek_words(srcdir)
    print("//! GENERATED by fuzz/gen_stem_reach.py from the pinned REL_18_3")
    print("//! snowball C sources (see that script for provenance and the")
    print("//! synthesis rule) — do not hand-edit.  Exception-stem reach")
    print("//! products for the tsdl:stemvocab sweep.")
    print()
    print("/// Per-language reach-product pools, swept after STEM_VOCAB.")
    print("pub const STEM_REACH: &[(&str, &[&str])] = &[")
    print('    ("greek", &[')
    line = "       "
    for w in words:
        piece = ' "' + w + '",'
        if len(line) + len(piece) > 98:
            print(line)
            line = "       "
        line += piece
    if line.strip():
        print(line)
    print("    ]),")
    print("];")


if __name__ == "__main__":
    main()
