/*
 * pg_cryptbe_io.c: vendored PostgreSQL C oracle for the crypt_be_diff
 * differential fuzz target (100%-coverage campaign, lane p1-wavea).
 * Crate under test: crates/backend/libpq/crypt (src/lib.rs, file-grain
 * MINUS get_role_password — syscache rolpassword + valid-until clock reads
 * are session/catalog environment, carved OUT of the unit's denominator per
 * the census note; it is deliberately NOT vendored here).
 *
 * GENERATED by csrc/gen/assemble_cryptbe.sh — verbatim sections are
 * sed-extracted, never hand-typed. Do not edit the VERBATIM sections here;
 * edit the script's shim heredocs and re-run.
 *
 * Provenance (all VERBATIM sections byte-for-byte from
 * ~/dev/pgrust-fabled/vendor/postgres-src, Stamp-18.3, upstream sha
 * 62d6c7d3df6287f1bd83199c1a746e50d31571a0):
 *   - src/backend/libpq/crypt.c lines 86-321: get_password_type,
 *     encrypt_password, md5_crypt_verify, plain_crypt_verify (ALL bodies of
 *     the unit; get_role_password lines 30-84 excluded per the carve, and
 *     the md5_password_warnings GUC storage line 28 is consumed via the
 *     stub channel below instead of a second definition).
 *   - src/backend/libpq/auth-scram.c lines 477-515 pg_be_scram_build_secret,
 *     517-585 scram_verify_plain_password, 588-683 parse_scram_secret (the
 *     three auth-scram entry points crypt.c calls).
 *   - src/include/libpq/crypt.h: MAX_ENCRYPTED_PASSWORD_LEN + the
 *     PasswordType enum (sed-extracted below).
 *   - src/common/wchar.c pg_utf_mblen and src/common/string.c pg_is_ascii
 *     (saslprep.c's two out-of-file libpgcommon calls), pasted at the end.
 *   - Whole verbatim sibling TUs in this directory (cp'd by the script):
 *     src/common/saslprep.c, src/common/unicode_norm.c (FRONTEND arms:
 *     malloc/free allocator + the linear/table lookup arms — the SAME
 *     verbatim file every libpq frontend SCRAM client runs; the ifdef arms
 *     select allocator + lookup mechanism only, and client/server SCRAM
 *     interop requires the results to be identical), plus vendored headers
 *     common/{saslprep,unicode_norm,unicode_norm_table,string}.h and
 *     mb/pg_wchar.h.
 *   - crypto/base64/scram primitives are NOT duplicated: pg_md5_encrypt,
 *     pg_b64_*, scram_build_secret, scram_SaltedPassword, scram_ServerKey
 *     resolve (via the family's -D renames in build.rs, which mirror
 *     CRYPTO_SHARED_SYMS) to the cryptofam_* exports of csrc/cryptofam/ —
 *     the verbatim 18.3 copies the cryptofam_diff target already vendors
 *     (single copy per the duplicate-export rule).
 *
 * Symbol renames (build.rs -D, bodies untouched): get_password_type,
 * encrypt_password, md5_crypt_verify, plain_crypt_verify,
 * parse_scram_secret, pg_be_scram_build_secret, scram_verify_plain_password,
 * pg_saslprep, unicode_normalize, pg_utf_mblen, pg_is_ascii all carry the
 * pg_cryptbe_ family prefix; the CRYPTO_SHARED_SYMS set carries cryptofam_.
 *
 * Shims (PLUMBING ONLY, never logic):
 *   - ereport/elog -> record an errcode class in TLS; >= ERROR longjmps to
 *     the armed wrapper; WARNING/LOG record and continue. Message text is
 *     out of the comparison planes (errmsg/errdetail/errhint swallowed);
 *     the errcode class IS compared. elog(ERROR) carries C's implicit
 *     ERRCODE_INTERNAL_ERROR (XX000).
 *   - logdetail psprintf: real vsnprintf into the exec arena so the
 *     logdetail STRING is a compared plane (same format strings both
 *     sides); _() -> identity.
 *   - palloc/pstrdup -> per-exec pointer arena (reset by pg_cryptbe_reset);
 *     pfree -> free (in the pasted bodies pfree is only ever applied to
 *     pg_saslprep results, which the FRONTEND arm mallocs).
 *   - pg_strong_random -> pg_stub_scram_salt (stub:prng salt channel,
 *     csrc/stubshims/pg_stub_state.c). The Rust driver pins the SAME 16
 *     bytes through the shipped crate's PGRUST_SCRAM_FIXED_SALT_B64
 *     determinism hook per fuzz/STUBS.md: the entropy read is ENVIRONMENT;
 *     everything derived from it is verbatim scram-common.c.
 *   - scram_sha_256_iterations / md5_password_warnings GUC reads ->
 *     pg_stub_scram_iterations / pg_stub_md5_password_warnings (stub:guc).
 *   - Assert compiled out (matches a production NDEBUG PostgreSQL build;
 *     shim postgres_fe.h). STATUS_OK/STATUS_ERROR transcribed from c.h.
 *   - ereport level constants transcribed from utils/elog.h (LOG 15,
 *     WARNING 19, ERROR 21); errcode CLASSES are small ints mapped to
 *     sqlstates on the Rust side (1=54000 program_limit_exceeded,
 *     2=XX000 internal_error, 3=01P01 deprecated_feature warning).
 */

#include "postgres_fe.h"

#include <errno.h>
#include <setjmp.h>
#include <stdarg.h>

#include "common/base64.h"
#include "common/md5.h"
#include "common/saslprep.h"
#include "common/scram-common.h"

/* stub channels (csrc/stubshims/pg_stub_state.c) */
extern int	pg_stub_get_md5_password_warnings(void);
extern int	pg_stub_get_scram_iterations(void);
extern void pg_stub_get_scram_salt(uint8_t *out16);

/* ---------------- shim: elog/ereport capture ------------------------------ */

/* transcribed level values, src/include/utils/elog.h */
#define LOG			15
#define WARNING		19
#define ERROR		21

/* oracle errcode classes (Rust side maps to sqlstates) */
#define PG_CRYPTBE_ECLASS_PROGRAM_LIMIT 1	/* 54000 */
#define PG_CRYPTBE_ECLASS_INTERNAL		2	/* XX000 (elog ERROR default) */
#define PG_CRYPTBE_ECLASS_DEPRECATED	3	/* 01P01 */

#define ERRCODE_PROGRAM_LIMIT_EXCEEDED		PG_CRYPTBE_ECLASS_PROGRAM_LIMIT
#define ERRCODE_INTERNAL_ERROR				PG_CRYPTBE_ECLASS_INTERNAL
#define ERRCODE_WARNING_DEPRECATED_FEATURE	PG_CRYPTBE_ECLASS_DEPRECATED

static _Thread_local jmp_buf pg_cryptbe_jmp;
static _Thread_local int pg_cryptbe_armed = 0;
static _Thread_local int pg_cryptbe_errclass = 0;	/* >= ERROR */
static _Thread_local int pg_cryptbe_warnclass = 0;	/* WARNING */
static _Thread_local int pg_cryptbe_logfired = 0;	/* LOG */
static _Thread_local int pg_cryptbe_pending = 0;

static int
pg_cryptbe_set_pending_code(int eclass)
{
	pg_cryptbe_pending = eclass;
	return 0;
}

static int
pg_cryptbe_pending_take(void)
{
	int			c = pg_cryptbe_pending;

	pg_cryptbe_pending = 0;
	return c;
}

static void
pg_cryptbe_report(int level, int eclass)
{
	if (level >= ERROR)
	{
		pg_cryptbe_errclass = eclass ? eclass : PG_CRYPTBE_ECLASS_INTERNAL;
		if (pg_cryptbe_armed)
			longjmp(pg_cryptbe_jmp, 1);
		abort();				/* wrapper forgot to arm — harness bug */
	}
	else if (level == WARNING)
		pg_cryptbe_warnclass = eclass ? eclass : PG_CRYPTBE_ECLASS_INTERNAL;
	else
		pg_cryptbe_logfired = 1;
}

#define errcode(c)				pg_cryptbe_set_pending_code(c)
#define errmsg(...)				0
#define errmsg_internal(...)	0
#define errdetail(...)			0
#define errhint(...)			0
#define ereport(level, rest) \
	do { (void) (rest); pg_cryptbe_report((level), pg_cryptbe_pending_take()); } while (0)
#define elog(level, ...) \
	pg_cryptbe_report((level), PG_CRYPTBE_ECLASS_INTERNAL)

/* ---------------- shim: per-exec pointer arena ---------------------------- */

#define PG_CRYPTBE_ARENA_MAX 512

static _Thread_local void *pg_cryptbe_arena[PG_CRYPTBE_ARENA_MAX];
static _Thread_local int pg_cryptbe_arena_n = 0;

static void *
pg_cryptbe_palloc(size_t size)
{
	void	   *p = malloc(size ? size : 1);

	if (p == NULL || pg_cryptbe_arena_n >= PG_CRYPTBE_ARENA_MAX)
		abort();				/* harness resource error, never a verdict */
	pg_cryptbe_arena[pg_cryptbe_arena_n++] = p;
	return p;
}

static char *
pg_cryptbe_pstrdup(const char *s)
{
	size_t		n = strlen(s) + 1;
	char	   *p = pg_cryptbe_palloc(n);

	memcpy(p, s, n);
	return p;
}

static char *
pg_cryptbe_psprintf(const char *fmt,...)
{
	va_list		ap;
	char		buf[1024];
	int			n;

	va_start(ap, fmt);
	n = vsnprintf(buf, sizeof(buf), fmt, ap);
	va_end(ap);
	if (n < 0 || n >= (int) sizeof(buf))
		abort();
	return pg_cryptbe_pstrdup(buf);
}

#define palloc(sz)		pg_cryptbe_palloc(sz)
#define pstrdup(s)		pg_cryptbe_pstrdup(s)
#define psprintf		pg_cryptbe_psprintf
#define pfree(p)		free(p)

/* ---------------- shim: stubbed session reads ----------------------------- */

/* stub:prng salt channel — the pg_strong_random entropy read */
static bool
pg_cryptbe_strong_random(void *buf, size_t len)
{
	uint8_t		salt[16];

	if (len != 16)
		abort();				/* SCRAM_DEFAULT_SALT_LEN is 16 in 18.3 */
	pg_stub_get_scram_salt(salt);
	memcpy(buf, salt, 16);
	return true;
}

#define pg_strong_random(buf, len) pg_cryptbe_strong_random((buf), (len))
#define scram_sha_256_iterations (pg_stub_get_scram_iterations())
#define md5_password_warnings (pg_stub_get_md5_password_warnings() != 0)

/* transcribed from src/include/c.h (values verbatim) */
#define STATUS_OK				(0)
#define STATUS_ERROR			(-1)

/* scram_build_secret's result is a RAW malloc (the cryptofam vendored
 * scram-common.c is compiled FRONTEND, so its palloc arm is malloc), but the
 * verbatim crypt.c/auth-scram.c callers below treat it as palloc'd-and-
 * forgotten — 140 bytes leaked per SCRAM encrypt_password exec (LSan, fleet
 * job 1785631457). Route this TU's references through an arena-tracking shim
 * (build.rs -D scram_build_secret=pg_cryptbe_scram_build_secret) so
 * pg_cryptbe_reset frees it; vendored bodies untouched. */
extern char *cryptofam_scram_build_secret(pg_cryptohash_type hash_type,
										  int key_length, const uint8 *salt,
										  int saltlen, int iterations,
										  const char *password,
										  const char **errstr);
char *
pg_cryptbe_scram_build_secret(pg_cryptohash_type hash_type, int key_length,
							  const uint8 *salt, int saltlen, int iterations,
							  const char *password, const char **errstr)
{
	char	   *m = cryptofam_scram_build_secret(hash_type, key_length, salt,
												 saltlen, iterations,
												 password, errstr);

	if (m != NULL)
	{
		if (pg_cryptbe_arena_n >= PG_CRYPTBE_ARENA_MAX)
			abort();			/* harness resource error, never a verdict */
		pg_cryptbe_arena[pg_cryptbe_arena_n++] = m;
	}
	return m;
}

/* forward decls for the pasted bodies (renamed by build.rs -D like all
 * other identifiers below) */
extern bool parse_scram_secret(const char *secret, int *iterations,
							   pg_cryptohash_type *hash_type, int *key_length,
							   char **salt, uint8 *stored_key, uint8 *server_key);
extern char *pg_be_scram_build_secret(const char *password);
extern bool scram_verify_plain_password(const char *username,
										const char *password, const char *secret);

/* VERBATIM src/include/libpq/crypt.h (MAX_ENCRYPTED_PASSWORD_LEN + enum): */
#define MAX_ENCRYPTED_PASSWORD_LEN (512)
typedef enum PasswordType
{
	PASSWORD_TYPE_PLAINTEXT = 0,
	PASSWORD_TYPE_MD5,
	PASSWORD_TYPE_SCRAM_SHA_256,
} PasswordType;

/* ===== VERBATIM src/backend/libpq/crypt.c lines 86-321 ==================== */
/*
 * What kind of a password type is 'shadow_pass'?
 */
PasswordType
get_password_type(const char *shadow_pass)
{
	char	   *encoded_salt;
	int			iterations;
	int			key_length = 0;
	pg_cryptohash_type hash_type;
	uint8		stored_key[SCRAM_MAX_KEY_LEN];
	uint8		server_key[SCRAM_MAX_KEY_LEN];

	if (strncmp(shadow_pass, "md5", 3) == 0 &&
		strlen(shadow_pass) == MD5_PASSWD_LEN &&
		strspn(shadow_pass + 3, MD5_PASSWD_CHARSET) == MD5_PASSWD_LEN - 3)
		return PASSWORD_TYPE_MD5;
	if (parse_scram_secret(shadow_pass, &iterations, &hash_type, &key_length,
						   &encoded_salt, stored_key, server_key))
		return PASSWORD_TYPE_SCRAM_SHA_256;
	return PASSWORD_TYPE_PLAINTEXT;
}

/*
 * Given a user-supplied password, convert it into a secret of
 * 'target_type' kind.
 *
 * If the password is already in encrypted form, we cannot reverse the
 * hash, so it is stored as it is regardless of the requested type.
 */
char *
encrypt_password(PasswordType target_type, const char *role,
				 const char *password)
{
	PasswordType guessed_type = get_password_type(password);
	char	   *encrypted_password = NULL;
	const char *errstr = NULL;

	if (guessed_type != PASSWORD_TYPE_PLAINTEXT)
	{
		/*
		 * Cannot convert an already-encrypted password from one format to
		 * another, so return it as it is.
		 */
		encrypted_password = pstrdup(password);
	}
	else
	{
		switch (target_type)
		{
			case PASSWORD_TYPE_MD5:
				encrypted_password = palloc(MD5_PASSWD_LEN + 1);

				if (!pg_md5_encrypt(password, (uint8 *) role, strlen(role),
									encrypted_password, &errstr))
					elog(ERROR, "password encryption failed: %s", errstr);
				break;

			case PASSWORD_TYPE_SCRAM_SHA_256:
				encrypted_password = pg_be_scram_build_secret(password);
				break;

			case PASSWORD_TYPE_PLAINTEXT:
				elog(ERROR, "cannot encrypt password with 'plaintext'");
				break;
		}
	}

	Assert(encrypted_password);

	/*
	 * Valid password hashes may be very long, but we don't want to store
	 * anything that might need out-of-line storage, since de-TOASTing won't
	 * work during authentication because we haven't selected a database yet
	 * and cannot read pg_class. 512 bytes should be more than enough for all
	 * practical use, so fail for anything longer.
	 */
	if (encrypted_password &&	/* keep compiler quiet */
		strlen(encrypted_password) > MAX_ENCRYPTED_PASSWORD_LEN)
	{
		/*
		 * We don't expect any of our own hashing routines to produce hashes
		 * that are too long.
		 */
		Assert(guessed_type != PASSWORD_TYPE_PLAINTEXT);

		ereport(ERROR,
				(errcode(ERRCODE_PROGRAM_LIMIT_EXCEEDED),
				 errmsg("encrypted password is too long"),
				 errdetail("Encrypted passwords must be no longer than %d bytes.",
						   MAX_ENCRYPTED_PASSWORD_LEN)));
	}

	if (md5_password_warnings &&
		get_password_type(encrypted_password) == PASSWORD_TYPE_MD5)
		ereport(WARNING,
				(errcode(ERRCODE_WARNING_DEPRECATED_FEATURE),
				 errmsg("setting an MD5-encrypted password"),
				 errdetail("MD5 password support is deprecated and will be removed in a future release of PostgreSQL."),
				 errhint("Refer to the PostgreSQL documentation for details about migrating to another password type.")));

	return encrypted_password;
}

/*
 * Check MD5 authentication response, and return STATUS_OK or STATUS_ERROR.
 *
 * 'shadow_pass' is the user's correct password or password hash, as stored
 * in pg_authid.rolpassword.
 * 'client_pass' is the response given by the remote user to the MD5 challenge.
 * 'md5_salt' is the salt used in the MD5 authentication challenge.
 *
 * In the error case, save a string at *logdetail that will be sent to the
 * postmaster log (but not the client).
 */
int
md5_crypt_verify(const char *role, const char *shadow_pass,
				 const char *client_pass,
				 const uint8 *md5_salt, int md5_salt_len,
				 const char **logdetail)
{
	int			retval;
	char		crypt_pwd[MD5_PASSWD_LEN + 1];
	const char *errstr = NULL;

	Assert(md5_salt_len > 0);

	if (get_password_type(shadow_pass) != PASSWORD_TYPE_MD5)
	{
		/* incompatible password hash format. */
		*logdetail = psprintf(_("User \"%s\" has a password that cannot be used with MD5 authentication."),
							  role);
		return STATUS_ERROR;
	}

	/*
	 * Compute the correct answer for the MD5 challenge.
	 */
	/* stored password already encrypted, only do salt */
	if (!pg_md5_encrypt(shadow_pass + strlen("md5"),
						md5_salt, md5_salt_len,
						crypt_pwd, &errstr))
	{
		*logdetail = errstr;
		return STATUS_ERROR;
	}

	if (strcmp(client_pass, crypt_pwd) == 0)
		retval = STATUS_OK;
	else
	{
		*logdetail = psprintf(_("Password does not match for user \"%s\"."),
							  role);
		retval = STATUS_ERROR;
	}

	return retval;
}

/*
 * Check given password for given user, and return STATUS_OK or STATUS_ERROR.
 *
 * 'shadow_pass' is the user's correct password hash, as stored in
 * pg_authid.rolpassword.
 * 'client_pass' is the password given by the remote user.
 *
 * In the error case, store a string at *logdetail that will be sent to the
 * postmaster log (but not the client).
 */
int
plain_crypt_verify(const char *role, const char *shadow_pass,
				   const char *client_pass,
				   const char **logdetail)
{
	char		crypt_client_pass[MD5_PASSWD_LEN + 1];
	const char *errstr = NULL;

	/*
	 * Client sent password in plaintext.  If we have an MD5 hash stored, hash
	 * the password the client sent, and compare the hashes.  Otherwise
	 * compare the plaintext passwords directly.
	 */
	switch (get_password_type(shadow_pass))
	{
		case PASSWORD_TYPE_SCRAM_SHA_256:
			if (scram_verify_plain_password(role,
											client_pass,
											shadow_pass))
			{
				return STATUS_OK;
			}
			else
			{
				*logdetail = psprintf(_("Password does not match for user \"%s\"."),
									  role);
				return STATUS_ERROR;
			}
			break;

		case PASSWORD_TYPE_MD5:
			if (!pg_md5_encrypt(client_pass,
								(uint8 *) role,
								strlen(role),
								crypt_client_pass,
								&errstr))
			{
				*logdetail = errstr;
				return STATUS_ERROR;
			}
			if (strcmp(crypt_client_pass, shadow_pass) == 0)
				return STATUS_OK;
			else
			{
				*logdetail = psprintf(_("Password does not match for user \"%s\"."),
									  role);
				return STATUS_ERROR;
			}
			break;

		case PASSWORD_TYPE_PLAINTEXT:

			/*
			 * We never store passwords in plaintext, so this shouldn't
			 * happen.
			 */
			break;
	}

	/*
	 * This shouldn't happen.  Plain "password" authentication is possible
	 * with any kind of stored password hash.
	 */
	*logdetail = psprintf(_("Password of user \"%s\" is in unrecognized format."),
						  role);
	return STATUS_ERROR;
}

/* ===== VERBATIM src/backend/libpq/auth-scram.c lines 477-515, 517-585,
 *       588-683 ============================================================ */
/*
 * Construct a SCRAM secret, for storing in pg_authid.rolpassword.
 *
 * The result is palloc'd, so caller is responsible for freeing it.
 */
char *
pg_be_scram_build_secret(const char *password)
{
	char	   *prep_password;
	pg_saslprep_rc rc;
	uint8		saltbuf[SCRAM_DEFAULT_SALT_LEN];
	char	   *result;
	const char *errstr = NULL;

	/*
	 * Normalize the password with SASLprep.  If that doesn't work, because
	 * the password isn't valid UTF-8 or contains prohibited characters, just
	 * proceed with the original password.  (See comments at top of file.)
	 */
	rc = pg_saslprep(password, &prep_password);
	if (rc == SASLPREP_SUCCESS)
		password = (const char *) prep_password;

	/* Generate random salt */
	if (!pg_strong_random(saltbuf, SCRAM_DEFAULT_SALT_LEN))
		ereport(ERROR,
				(errcode(ERRCODE_INTERNAL_ERROR),
				 errmsg("could not generate random salt")));

	result = scram_build_secret(PG_SHA256, SCRAM_SHA_256_KEY_LEN,
								saltbuf, SCRAM_DEFAULT_SALT_LEN,
								scram_sha_256_iterations, password,
								&errstr);

	if (prep_password)
		pfree(prep_password);

	return result;
}
/*
 * Verify a plaintext password against a SCRAM secret.  This is used when
 * performing plaintext password authentication for a user that has a SCRAM
 * secret stored in pg_authid.
 */
bool
scram_verify_plain_password(const char *username, const char *password,
							const char *secret)
{
	char	   *encoded_salt;
	uint8	   *salt;
	int			saltlen;
	int			iterations;
	int			key_length = 0;
	pg_cryptohash_type hash_type;
	uint8		salted_password[SCRAM_MAX_KEY_LEN];
	uint8		stored_key[SCRAM_MAX_KEY_LEN];
	uint8		server_key[SCRAM_MAX_KEY_LEN];
	uint8		computed_key[SCRAM_MAX_KEY_LEN];
	char	   *prep_password;
	pg_saslprep_rc rc;
	const char *errstr = NULL;

	if (!parse_scram_secret(secret, &iterations, &hash_type, &key_length,
							&encoded_salt, stored_key, server_key))
	{
		/*
		 * The password looked like a SCRAM secret, but could not be parsed.
		 */
		ereport(LOG,
				(errmsg("invalid SCRAM secret for user \"%s\"", username)));
		return false;
	}

	saltlen = pg_b64_dec_len(strlen(encoded_salt));
	salt = palloc(saltlen);
	saltlen = pg_b64_decode(encoded_salt, strlen(encoded_salt), salt,
							saltlen);
	if (saltlen < 0)
	{
		ereport(LOG,
				(errmsg("invalid SCRAM secret for user \"%s\"", username)));
		return false;
	}

	/* Normalize the password */
	rc = pg_saslprep(password, &prep_password);
	if (rc == SASLPREP_SUCCESS)
		password = prep_password;

	/* Compute Server Key based on the user-supplied plaintext password */
	if (scram_SaltedPassword(password, hash_type, key_length,
							 salt, saltlen, iterations,
							 salted_password, &errstr) < 0 ||
		scram_ServerKey(salted_password, hash_type, key_length,
						computed_key, &errstr) < 0)
	{
		elog(ERROR, "could not compute server key: %s", errstr);
	}

	if (prep_password)
		pfree(prep_password);

	/*
	 * Compare the secret's Server Key with the one computed from the
	 * user-supplied password.
	 */
	return memcmp(computed_key, server_key, key_length) == 0;
}
/*
 * Parse and validate format of given SCRAM secret.
 *
 * On success, the iteration count, salt, stored key, and server key are
 * extracted from the secret, and returned to the caller.  For 'stored_key'
 * and 'server_key', the caller must pass pre-allocated buffers of size
 * SCRAM_MAX_KEY_LEN.  Salt is returned as a base64-encoded, null-terminated
 * string.  The buffer for the salt is palloc'd by this function.
 *
 * Returns true if the SCRAM secret has been parsed, and false otherwise.
 */
bool
parse_scram_secret(const char *secret, int *iterations,
				   pg_cryptohash_type *hash_type, int *key_length,
				   char **salt, uint8 *stored_key, uint8 *server_key)
{
	char	   *v;
	char	   *p;
	char	   *scheme_str;
	char	   *salt_str;
	char	   *iterations_str;
	char	   *storedkey_str;
	char	   *serverkey_str;
	int			decoded_len;
	uint8	   *decoded_salt_buf;
	uint8	   *decoded_stored_buf;
	uint8	   *decoded_server_buf;

	/*
	 * The secret is of form:
	 *
	 * SCRAM-SHA-256$<iterations>:<salt>$<storedkey>:<serverkey>
	 */
	v = pstrdup(secret);
	scheme_str = strsep(&v, "$");
	if (v == NULL)
		goto invalid_secret;
	iterations_str = strsep(&v, ":");
	if (v == NULL)
		goto invalid_secret;
	salt_str = strsep(&v, "$");
	if (v == NULL)
		goto invalid_secret;
	storedkey_str = strsep(&v, ":");
	if (v == NULL)
		goto invalid_secret;
	serverkey_str = v;

	/* Parse the fields */
	if (strcmp(scheme_str, "SCRAM-SHA-256") != 0)
		goto invalid_secret;
	*hash_type = PG_SHA256;
	*key_length = SCRAM_SHA_256_KEY_LEN;

	errno = 0;
	*iterations = strtol(iterations_str, &p, 10);
	if (*p || errno != 0)
		goto invalid_secret;

	/*
	 * Verify that the salt is in Base64-encoded format, by decoding it,
	 * although we return the encoded version to the caller.
	 */
	decoded_len = pg_b64_dec_len(strlen(salt_str));
	decoded_salt_buf = palloc(decoded_len);
	decoded_len = pg_b64_decode(salt_str, strlen(salt_str),
								decoded_salt_buf, decoded_len);
	if (decoded_len < 0)
		goto invalid_secret;
	*salt = pstrdup(salt_str);

	/*
	 * Decode StoredKey and ServerKey.
	 */
	decoded_len = pg_b64_dec_len(strlen(storedkey_str));
	decoded_stored_buf = palloc(decoded_len);
	decoded_len = pg_b64_decode(storedkey_str, strlen(storedkey_str),
								decoded_stored_buf, decoded_len);
	if (decoded_len != *key_length)
		goto invalid_secret;
	memcpy(stored_key, decoded_stored_buf, *key_length);

	decoded_len = pg_b64_dec_len(strlen(serverkey_str));
	decoded_server_buf = palloc(decoded_len);
	decoded_len = pg_b64_decode(serverkey_str, strlen(serverkey_str),
								decoded_server_buf, decoded_len);
	if (decoded_len != *key_length)
		goto invalid_secret;
	memcpy(server_key, decoded_server_buf, *key_length);

	return true;

invalid_secret:
	*salt = NULL;
	return false;
}

/* ===== VERBATIM src/common/wchar.c lines 544-577 (pg_utf_mblen) =========== */
/*
 * Return the byte length of a UTF8 character pointed to by s
 *
 * Note: in the current implementation we do not support UTF8 sequences
 * of more than 4 bytes; hence do NOT return a value larger than 4.
 * We return "1" for any leading byte that is either flat-out illegal or
 * indicates a length larger than we support.
 *
 * pg_utf2wchar_with_len(), utf8_to_unicode(), pg_utf8_islegal(), and perhaps
 * other places would need to be fixed to change this.
 */
int
pg_utf_mblen(const unsigned char *s)
{
	int			len;

	if ((*s & 0x80) == 0)
		len = 1;
	else if ((*s & 0xe0) == 0xc0)
		len = 2;
	else if ((*s & 0xf0) == 0xe0)
		len = 3;
	else if ((*s & 0xf8) == 0xf0)
		len = 4;
#ifdef NOT_USED
	else if ((*s & 0xfc) == 0xf8)
		len = 5;
	else if ((*s & 0xfe) == 0xfc)
		len = 6;
#endif
	else
		len = 1;
	return len;
}

/* ===== VERBATIM src/common/wchar.c lines 1996-2065 (pg_utf8_islegal —
 *       called by saslprep.c's pg_utf8_string_len) ======================== */
/*
 * Check for validity of a single UTF-8 encoded character
 *
 * This directly implements the rules in RFC3629.  The bizarre-looking
 * restrictions on the second byte are meant to ensure that there isn't
 * more than one encoding of a given Unicode character point; that is,
 * you may not use a longer-than-necessary byte sequence with high order
 * zero bits to represent a character that would fit in fewer bytes.
 * To do otherwise is to create security hazards (eg, create an apparent
 * non-ASCII character that decodes to plain ASCII).
 *
 * length is assumed to have been obtained by pg_utf_mblen(), and the
 * caller must have checked that that many bytes are present in the buffer.
 */
bool
pg_utf8_islegal(const unsigned char *source, int length)
{
	unsigned char a;

	switch (length)
	{
		default:
			/* reject lengths 5 and 6 for now */
			return false;
		case 4:
			a = source[3];
			if (a < 0x80 || a > 0xBF)
				return false;
			/* FALL THRU */
		case 3:
			a = source[2];
			if (a < 0x80 || a > 0xBF)
				return false;
			/* FALL THRU */
		case 2:
			a = source[1];
			switch (*source)
			{
				case 0xE0:
					if (a < 0xA0 || a > 0xBF)
						return false;
					break;
				case 0xED:
					if (a < 0x80 || a > 0x9F)
						return false;
					break;
				case 0xF0:
					if (a < 0x90 || a > 0xBF)
						return false;
					break;
				case 0xF4:
					if (a < 0x80 || a > 0x8F)
						return false;
					break;
				default:
					if (a < 0x80 || a > 0xBF)
						return false;
					break;
			}
			/* FALL THRU */
		case 1:
			a = *source;
			if (a >= 0x80 && a < 0xC2)
				return false;
			if (a > 0xF4)
				return false;
			break;
	}
	return true;
}

/* transcribed from src/include/c.h (verbatim macro): */
#define HIGHBIT					(0x80)
#define IS_HIGHBIT_SET(ch)		((unsigned char)(ch) & HIGHBIT)

/* ===== VERBATIM src/common/string.c lines 128-142 (pg_is_ascii) =========== */
/*
 * pg_is_ascii -- Check if string is made only of ASCII characters
 */
bool
pg_is_ascii(const char *str)
{
	while (*str)
	{
		if (IS_HIGHBIT_SET(*str))
			return false;
		str++;
	}
	return true;
}


/* ---------------- driver entry points (shim, exported) -------------------- */

void
pg_cryptbe_reset(void)
{
	for (int i = 0; i < pg_cryptbe_arena_n; i++)
		free(pg_cryptbe_arena[i]);
	pg_cryptbe_arena_n = 0;
	pg_cryptbe_errclass = 0;
	pg_cryptbe_warnclass = 0;
	pg_cryptbe_logfired = 0;
	pg_cryptbe_pending = 0;
	pg_cryptbe_armed = 0;
}

/* TAKE semantics: one warning/log observation per paired call (an arm may
 * chain several paired calls per exec; a warning must not bleed forward). */
int
pg_cryptbe_warnclass_get(void)
{
	int			c = pg_cryptbe_warnclass;

	pg_cryptbe_warnclass = 0;
	return c;
}

int
pg_cryptbe_logfired_get(void)
{
	int			c = pg_cryptbe_logfired;

	pg_cryptbe_logfired = 0;
	return c;
}

int
pg_cryptbe_w_get_password_type(const char *shadow_pass)
{
	return (int) get_password_type(shadow_pass);
}

/*
 * Returns 0 and the NUL-terminated secret in out (cap bytes) on success;
 * -eclass on ereport(ERROR).
 */
int
pg_cryptbe_w_encrypt_password(int target_type, const char *role,
							  const char *password, char *out, size_t cap)
{
	char	   *r;

	pg_cryptbe_armed = 1;
	if (setjmp(pg_cryptbe_jmp))
	{
		pg_cryptbe_armed = 0;
		return -pg_cryptbe_errclass;
	}
	r = encrypt_password((PasswordType) target_type, role, password);
	pg_cryptbe_armed = 0;
	if (r == NULL || strlen(r) + 1 > cap)
		abort();				/* cap is a harness sizing bug, not a verdict */
	memcpy(out, r, strlen(r) + 1);
	return 0;
}

/*
 * Verify wrappers: return STATUS_OK/STATUS_ERROR, or -100-eclass if the
 * body ereport(ERROR)ed (possible only via elog in scram key computation —
 * OOM-shaped, treated as harness-fatal by the driver). *logdetail_out is
 * NULL or an arena string valid until pg_cryptbe_reset.
 */
int
pg_cryptbe_w_md5_crypt_verify(const char *role, const char *shadow_pass,
							  const char *client_pass, const uint8 *md5_salt,
							  int md5_salt_len, const char **logdetail_out)
{
	const char *logdetail = NULL;
	int			st;

	pg_cryptbe_armed = 1;
	if (setjmp(pg_cryptbe_jmp))
	{
		pg_cryptbe_armed = 0;
		*logdetail_out = NULL;
		return -100 - pg_cryptbe_errclass;
	}
	st = md5_crypt_verify(role, shadow_pass, client_pass, md5_salt,
						  md5_salt_len, &logdetail);
	pg_cryptbe_armed = 0;
	*logdetail_out = logdetail;
	return st;
}

int
pg_cryptbe_w_plain_crypt_verify(const char *role, const char *shadow_pass,
								const char *client_pass,
								const char **logdetail_out)
{
	const char *logdetail = NULL;
	int			st;

	pg_cryptbe_armed = 1;
	if (setjmp(pg_cryptbe_jmp))
	{
		pg_cryptbe_armed = 0;
		*logdetail_out = NULL;
		return -100 - pg_cryptbe_errclass;
	}
	st = plain_crypt_verify(role, shadow_pass, client_pass, &logdetail);
	pg_cryptbe_armed = 0;
	*logdetail_out = logdetail;
	return st;
}
