[package]
name = "schemacmds"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../_support/mcx" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_guc = { path = "../../../_support/types/types_guc" }
types_nodes = { path = "../../../_support/types/nodes" }
adt_acl = { path = "../../utils/adt/acl" }
adt_quote = { path = "../../utils/adt/quote" }
guc = { path = "../../utils/misc/guc" }
aclchk = { path = "../../catalog/aclchk" }
aclchk_seams = { path = "../../catalog/aclchk_seams" }
catalog = { path = "../../catalog/catalog" }
catalog_namespace = { path = "../../catalog/catalog_namespace" }
pg_namespace = { path = "../../catalog/pg_namespace" }
dbcommands = { path = "../dbcommands" }
elog_seams = { path = "../../utils/error/elog_seams" }
init_small = { path = "../../utils/init/init_small" }
miscinit = { path = "../../utils/init/miscinit" }
xact = { path = "../../access/transam/xact" }
types_rel = { path = "../../../_support/types/rel" }
types_scan = { path = "../../../_support/types/types_scan" }
types_tuple = { path = "../../../_support/types/types_tuple" }
datum = { path = "../../../_support/types/datum" }
fmgr_seams = { path = "../../utils/fmgr/fmgr_seams" }
table = { path = "../../access/table/table" }
genam = { path = "../../access/index/genam" }
heaptuple = { path = "../../access/common/heaptuple" }
catalog_indexing = { path = "../../catalog/catalog_indexing" }
pg_shdepend = { path = "../../catalog/pg_shdepend" }
