[package]
name = "nodetablefuncscan"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
adt_jsonpath_exec = { path = "../../utils/adt/jsonpath_exec" }
adt_xml = { path = "../../utils/adt/xml" }
datum = { path = "../../../_support/types/datum" }
detoast_seams = { path = "../../access/common/detoast_seams" }
execexpr = { path = "../execexpr" }
execscan = { path = "../execscan" }
executils = { path = "../executils" }
fmgr_core = { path = "../../utils/fmgr/fmgr_core" }
init_small = { path = "../../utils/init/init_small" }
lsyscache = { path = "../../utils/cache/lsyscache" }
mcx = { path = "../../../_support/mcx" }
nodes_core = { path = "../../nodes/nodes_core" }
tupdesc = { path = "../../access/common/tupdesc" }
tuplestore = { path = "../../utils/sort/tuplestore" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_fmgr = { path = "../../../_support/types/fmgr" }
types_nodes = { path = "../../../_support/types/nodes" }
types_scan = { path = "../../../_support/types/types_scan" }
types_slot = { path = "../../../_support/types/types_slot" }
types_tuple = { path = "../../../_support/types/types_tuple" }
