[package]
name = "aio_config"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "aio_config"
path = "src/lib.rs"

[dependencies]
types_guc = { path = "../../../../_support/types/types_guc" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
datum = { path = "../../../../_support/types/datum" }
guc_tables = { path = "../../../utils/misc/guc_tables" }
aio_seams = { path = "../aio_seams" }
ipc_seams = { path = "../../ipc/ipc_seams" }
miscinit = { path = "../../../utils/init/miscinit" }
lmgr_proc = { path = "../../lmgr/lmgr_proc" }
