[package]
name = "discard"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "discard"
path = "src/lib.rs"

[dependencies]
catalog_namespace = { path = "../../catalog/catalog_namespace" }
commands_async = { path = "../commands_async" }
guc = { path = "../../utils/misc/guc" }
guc_funcs = { path = "../../utils/misc/guc_funcs" }
lock = { path = "../../storage/lmgr/lock" }
plancache = { path = "../../utils/cache/plancache" }
portalmem = { path = "../../utils/mmgr/portalmem" }
prepare = { path = "../prepare" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_storage = { path = "../../../_support/types/types_storage" }
xact = { path = "../../access/transam/xact" }
sequence = { path = "../sequence" }
