[package]
name = "parallel"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "parallel"
path = "src/lib.rs"

[dependencies]
parallel_seams = { path = "../parallel_seams" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_storage = { path = "../../../../_support/types/types_storage" }
elog = { path = "../../../utils/error/elog" }
init_small = { path = "../../../utils/init/init_small" }
miscinit = { path = "../../../utils/init/miscinit" }
guc = { path = "../../../utils/misc/guc" }
guc_tables = { path = "../../../utils/misc/guc_tables" }
snapmgr = { path = "../../../utils/time/snapmgr" }
combocid = { path = "../../../utils/time/combocid" }
relmapper = { path = "../../../utils/cache/relmapper" }
inval = { path = "../../../utils/cache/inval" }
mbutils = { path = "../../../utils/mb/mbutils" }
xact = { path = "../xact" }
transam_xlog_seams = { path = "../transam_xlog_seams" }
bgworker = { path = "../../../postmaster/bgworker" }
lmgr_proc = { path = "../../../storage/lmgr/lmgr_proc" }
procsignal = { path = "../../../storage/ipc/procsignal" }
latch = { path = "../../../storage/ipc/latch" }
catalog_namespace = { path = "../../../catalog/catalog_namespace" }
catalog_storage = { path = "../../../catalog/catalog_storage" }
pg_enum = { path = "../../../catalog/pg_enum" }
postgres_seams = { path = "../../../tcop/postgres_seams" }

[dev-dependencies]
test_boot = { path = "../../../../_support/test_boot" }
seams_init = { path = "../../../../_support/seams_init" }
mcx = { path = "../../../../_support/mcx" }
types_snapshot = { path = "../../../../_support/types/snapshot" }
types_startup = { path = "../../../../_support/types/types_startup" }
ipc = { path = "../../../storage/ipc/ipc" }
pmsignal = { path = "../../../storage/ipc/pmsignal" }
waiteventset = { path = "../../../storage/ipc/waiteventset" }
fd = { path = "../../../storage/file/fd" }
shm_mq = { path = "../../../storage/ipc/shm_mq" }
tqueue = { path = "../../../executor/tqueue" }
instrument = { path = "../../../executor/instrument" }
