[package]
name = "nodetidrangescan"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
mcx = { path = "../../../_support/mcx" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_scan = { path = "../../../_support/types/types_scan" }
types_core = { path = "../../../_support/types/types_core" }
types_tuple = { path = "../../../_support/types/types_tuple" }
tableam = { path = "../../access/table/tableam" }
execscan = { path = "../execscan" }
execexpr = { path = "../execexpr" }
exectuples = { path = "../exectuples" }
executils = { path = "../executils" }
