//! The two static metadata tables from objectaddress.c, ported verbatim:
//! `ObjectProperty[]` (per-catalog property rows) and `ObjectTypeMap[]`
//! (string-name → [`ObjectType`] mapping used by `read_objtype_from_string`).

use ::types_core::Oid;

use ::cache_syscache::{
    AMNAME, AMOID, AUTHNAME, AUTHOID, CLAOID, COLLOID, CONNAMENSP, CONSTROID, CONVOID, DATABASEOID,
    EVENTTRIGGERNAME, EVENTTRIGGEROID, FOREIGNDATAWRAPPERNAME, FOREIGNDATAWRAPPEROID,
    FOREIGNSERVERNAME, FOREIGNSERVEROID, LANGNAME, LANGOID, NAMESPACENAME, NAMESPACEOID, OPEROID,
    OPFAMILYOID, PROCOID, PUBLICATIONNAME, PUBLICATIONOID, RELNAMENSP, RELOID, STATEXTNAMENSP,
    STATEXTOID, SUBSCRIPTIONNAME, SUBSCRIPTIONOID, TABLESPACEOID, TRFOID, TSCONFIGNAMENSP,
    TSCONFIGOID, TSDICTNAMENSP, TSDICTOID, TSPARSERNAMENSP, TSPARSEROID, TSTEMPLATENAMENSP,
    TSTEMPLATEOID, TYPENAMENSP, TYPEOID, USERMAPPINGOID,
};

use crate::consts::*;
use ::nodes::parsenodes::ObjectType;
// The two metadata tables refer to object types by their C names
// (`OBJECT_ACCESS_METHOD`, …); these are the re-exported aliases of the
// `ObjectType` enum variants.
use ::nodes::parsenodes::{
    OBJECT_ACCESS_METHOD, OBJECT_AGGREGATE, OBJECT_AMOP, OBJECT_AMPROC, OBJECT_CAST,
    OBJECT_COLLATION, OBJECT_COLUMN, OBJECT_CONVERSION, OBJECT_DATABASE, OBJECT_DEFACL,
    OBJECT_DEFAULT, OBJECT_DOMCONSTRAINT, OBJECT_EVENT_TRIGGER, OBJECT_EXTENSION, OBJECT_FDW,
    OBJECT_FOREIGN_SERVER, OBJECT_FOREIGN_TABLE, OBJECT_FUNCTION, OBJECT_INDEX, OBJECT_LANGUAGE,
    OBJECT_LARGEOBJECT, OBJECT_MATVIEW, OBJECT_OPCLASS, OBJECT_OPERATOR, OBJECT_OPFAMILY,
    OBJECT_PARAMETER_ACL, OBJECT_POLICY, OBJECT_PROCEDURE, OBJECT_PUBLICATION,
    OBJECT_PUBLICATION_NAMESPACE, OBJECT_PUBLICATION_REL, OBJECT_ROLE, OBJECT_RULE, OBJECT_SCHEMA,
    OBJECT_SEQUENCE, OBJECT_STATISTIC_EXT, OBJECT_SUBSCRIPTION, OBJECT_TABCONSTRAINT, OBJECT_TABLE,
    OBJECT_TABLESPACE, OBJECT_TRANSFORM, OBJECT_TRIGGER, OBJECT_TSCONFIGURATION, OBJECT_TSDICTIONARY,
    OBJECT_TSPARSER, OBJECT_TSTEMPLATE, OBJECT_TYPE, OBJECT_USER_MAPPING, OBJECT_VIEW,
};

/// `typedef struct { … } ObjectPropertyType` — a common per-catalog descriptor.
#[derive(Clone, Copy, Debug)]
pub struct ObjectPropertyType {
    /// `class_descr` — string describing the catalog, for internal error msgs.
    pub class_descr: &'static str,
    /// `class_oid` — oid of catalog.
    pub class_oid: Oid,
    /// `oid_index_oid` — oid of index on system oid column.
    pub oid_index_oid: Oid,
    /// `oid_catcache_id` — id of catcache on system oid column.
    pub oid_catcache_id: i32,
    /// `name_catcache_id` — id of catcache on (name,namespace) or (name).
    pub name_catcache_id: i32,
    /// `attnum_oid` — attribute number of oid column.
    pub attnum_oid: i16,
    /// `attnum_name` — attnum of name field.
    pub attnum_name: i16,
    /// `attnum_namespace` — attnum of namespace field.
    pub attnum_namespace: i16,
    /// `attnum_owner` — attnum of owner field.
    pub attnum_owner: i16,
    /// `attnum_acl` — attnum of acl field.
    pub attnum_acl: i16,
    /// `objtype` — `OBJECT_*` of this object type.
    pub objtype: i32,
    /// `is_nsp_name_unique` — can nsp/name (or name alone) uniquely identify it?
    pub is_nsp_name_unique: bool,
}

const IA: i16 = InvalidAttrNumber;

/// `static const ObjectPropertyType ObjectProperty[]` — 37 rows, 1:1 with C.
///
/// `objtype` is stored as the raw `i32` (`-1` for the two rows the C declares
/// with no `OBJECT_*` value: "constraint" and "role membership").
pub static OBJECT_PROPERTY: &[ObjectPropertyType] = &[
    ObjectPropertyType {
        class_descr: "access method",
        class_oid: AccessMethodRelationId,
        oid_index_oid: AmOidIndexId,
        oid_catcache_id: AMOID,
        name_catcache_id: AMNAME,
        attnum_oid: Anum_pg_am_oid,
        attnum_name: Anum_pg_am_amname,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_ACCESS_METHOD as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "access method operator",
        class_oid: AccessMethodOperatorRelationId,
        oid_index_oid: AccessMethodOperatorOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_amop_oid,
        attnum_name: IA,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_AMOP as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "access method procedure",
        class_oid: AccessMethodProcedureRelationId,
        oid_index_oid: AccessMethodProcedureOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_amproc_oid,
        attnum_name: IA,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_AMPROC as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "cast",
        class_oid: CastRelationId,
        oid_index_oid: CastOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_cast_oid,
        attnum_name: IA,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_CAST as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "collation",
        class_oid: CollationRelationId,
        oid_index_oid: CollationOidIndexId,
        oid_catcache_id: COLLOID,
        name_catcache_id: -1, // COLLNAMEENCNSP also takes encoding
        attnum_oid: Anum_pg_collation_oid,
        attnum_name: Anum_pg_collation_collname,
        attnum_namespace: Anum_pg_collation_collnamespace,
        attnum_owner: Anum_pg_collation_collowner,
        attnum_acl: IA,
        objtype: OBJECT_COLLATION as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "constraint",
        class_oid: ConstraintRelationId,
        oid_index_oid: ConstraintOidIndexId,
        oid_catcache_id: CONSTROID,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_constraint_oid,
        attnum_name: Anum_pg_constraint_conname,
        attnum_namespace: Anum_pg_constraint_connamespace,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: -1,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "conversion",
        class_oid: ConversionRelationId,
        oid_index_oid: ConversionOidIndexId,
        oid_catcache_id: CONVOID,
        name_catcache_id: CONNAMENSP,
        attnum_oid: Anum_pg_conversion_oid,
        attnum_name: Anum_pg_conversion_conname,
        attnum_namespace: Anum_pg_conversion_connamespace,
        attnum_owner: Anum_pg_conversion_conowner,
        attnum_acl: IA,
        objtype: OBJECT_CONVERSION as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "database",
        class_oid: DatabaseRelationId,
        oid_index_oid: DatabaseOidIndexId,
        oid_catcache_id: DATABASEOID,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_database_oid,
        attnum_name: Anum_pg_database_datname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_database_datdba,
        attnum_acl: Anum_pg_database_datacl,
        objtype: OBJECT_DATABASE as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "default ACL",
        class_oid: DefaultAclRelationId,
        oid_index_oid: DefaultAclOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_default_acl_oid,
        attnum_name: IA,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_DEFACL as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "extension",
        class_oid: ExtensionRelationId,
        oid_index_oid: ExtensionOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_extension_oid,
        attnum_name: Anum_pg_extension_extname,
        attnum_namespace: IA, // extension doesn't belong to extnamespace
        attnum_owner: Anum_pg_extension_extowner,
        attnum_acl: IA,
        objtype: OBJECT_EXTENSION as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "foreign-data wrapper",
        class_oid: ForeignDataWrapperRelationId,
        oid_index_oid: ForeignDataWrapperOidIndexId,
        oid_catcache_id: FOREIGNDATAWRAPPEROID,
        name_catcache_id: FOREIGNDATAWRAPPERNAME,
        attnum_oid: Anum_pg_foreign_data_wrapper_oid,
        attnum_name: Anum_pg_foreign_data_wrapper_fdwname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_foreign_data_wrapper_fdwowner,
        attnum_acl: Anum_pg_foreign_data_wrapper_fdwacl,
        objtype: OBJECT_FDW as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "foreign server",
        class_oid: ForeignServerRelationId,
        oid_index_oid: ForeignServerOidIndexId,
        oid_catcache_id: FOREIGNSERVEROID,
        name_catcache_id: FOREIGNSERVERNAME,
        attnum_oid: Anum_pg_foreign_server_oid,
        attnum_name: Anum_pg_foreign_server_srvname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_foreign_server_srvowner,
        attnum_acl: Anum_pg_foreign_server_srvacl,
        objtype: OBJECT_FOREIGN_SERVER as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "function",
        class_oid: ProcedureRelationId,
        oid_index_oid: ProcedureOidIndexId,
        oid_catcache_id: PROCOID,
        name_catcache_id: -1, // PROCNAMEARGSNSP also takes argument types
        attnum_oid: Anum_pg_proc_oid,
        attnum_name: Anum_pg_proc_proname,
        attnum_namespace: Anum_pg_proc_pronamespace,
        attnum_owner: Anum_pg_proc_proowner,
        attnum_acl: Anum_pg_proc_proacl,
        objtype: OBJECT_FUNCTION as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "language",
        class_oid: LanguageRelationId,
        oid_index_oid: LanguageOidIndexId,
        oid_catcache_id: LANGOID,
        name_catcache_id: LANGNAME,
        attnum_oid: Anum_pg_language_oid,
        attnum_name: Anum_pg_language_lanname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_language_lanowner,
        attnum_acl: Anum_pg_language_lanacl,
        objtype: OBJECT_LANGUAGE as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "large object metadata",
        class_oid: LargeObjectMetadataRelationId,
        oid_index_oid: LargeObjectMetadataOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_largeobject_metadata_oid,
        attnum_name: IA,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_largeobject_metadata_lomowner,
        attnum_acl: Anum_pg_largeobject_metadata_lomacl,
        objtype: OBJECT_LARGEOBJECT as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "operator class",
        class_oid: OperatorClassRelationId,
        oid_index_oid: OpclassOidIndexId,
        oid_catcache_id: CLAOID,
        name_catcache_id: -1, // CLAAMNAMENSP also takes opcmethod
        attnum_oid: Anum_pg_opclass_oid,
        attnum_name: Anum_pg_opclass_opcname,
        attnum_namespace: Anum_pg_opclass_opcnamespace,
        attnum_owner: Anum_pg_opclass_opcowner,
        attnum_acl: IA,
        objtype: OBJECT_OPCLASS as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "operator",
        class_oid: OperatorRelationId,
        oid_index_oid: OperatorOidIndexId,
        oid_catcache_id: OPEROID,
        name_catcache_id: -1, // OPERNAMENSP also takes left and right type
        attnum_oid: Anum_pg_operator_oid,
        attnum_name: Anum_pg_operator_oprname,
        attnum_namespace: Anum_pg_operator_oprnamespace,
        attnum_owner: Anum_pg_operator_oprowner,
        attnum_acl: IA,
        objtype: OBJECT_OPERATOR as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "operator family",
        class_oid: OperatorFamilyRelationId,
        oid_index_oid: OpfamilyOidIndexId,
        oid_catcache_id: OPFAMILYOID,
        name_catcache_id: -1, // OPFAMILYAMNAMENSP also takes opfmethod
        attnum_oid: Anum_pg_opfamily_oid,
        attnum_name: Anum_pg_opfamily_opfname,
        attnum_namespace: Anum_pg_opfamily_opfnamespace,
        attnum_owner: Anum_pg_opfamily_opfowner,
        attnum_acl: IA,
        objtype: OBJECT_OPFAMILY as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "role",
        class_oid: AuthIdRelationId,
        oid_index_oid: AuthIdOidIndexId,
        oid_catcache_id: AUTHOID,
        name_catcache_id: AUTHNAME,
        attnum_oid: Anum_pg_authid_oid,
        attnum_name: Anum_pg_authid_rolname,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_ROLE as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "role membership",
        class_oid: AuthMemRelationId,
        oid_index_oid: AuthMemOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_auth_members_oid,
        attnum_name: IA,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_auth_members_grantor,
        attnum_acl: IA,
        objtype: -1,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "rule",
        class_oid: RewriteRelationId,
        oid_index_oid: RewriteOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_rewrite_oid,
        attnum_name: Anum_pg_rewrite_rulename,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_RULE as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "schema",
        class_oid: NamespaceRelationId,
        oid_index_oid: NamespaceOidIndexId,
        oid_catcache_id: NAMESPACEOID,
        name_catcache_id: NAMESPACENAME,
        attnum_oid: Anum_pg_namespace_oid,
        attnum_name: Anum_pg_namespace_nspname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_namespace_nspowner,
        attnum_acl: Anum_pg_namespace_nspacl,
        objtype: OBJECT_SCHEMA as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "relation",
        class_oid: RelationRelationId,
        oid_index_oid: ClassOidIndexId,
        oid_catcache_id: RELOID,
        name_catcache_id: RELNAMENSP,
        attnum_oid: Anum_pg_class_oid,
        attnum_name: Anum_pg_class_relname,
        attnum_namespace: Anum_pg_class_relnamespace,
        attnum_owner: Anum_pg_class_relowner,
        attnum_acl: Anum_pg_class_relacl,
        objtype: OBJECT_TABLE as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "tablespace",
        class_oid: TableSpaceRelationId,
        oid_index_oid: TablespaceOidIndexId,
        oid_catcache_id: TABLESPACEOID,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_tablespace_oid,
        attnum_name: Anum_pg_tablespace_spcname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_tablespace_spcowner,
        attnum_acl: Anum_pg_tablespace_spcacl,
        objtype: OBJECT_TABLESPACE as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "transform",
        class_oid: TransformRelationId,
        oid_index_oid: TransformOidIndexId,
        oid_catcache_id: TRFOID,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_transform_oid,
        attnum_name: IA,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_TRANSFORM as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "trigger",
        class_oid: TriggerRelationId,
        oid_index_oid: TriggerOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_trigger_oid,
        attnum_name: Anum_pg_trigger_tgname,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_TRIGGER as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "policy",
        class_oid: PolicyRelationId,
        oid_index_oid: PolicyOidIndexId,
        oid_catcache_id: -1,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_policy_oid,
        attnum_name: Anum_pg_policy_polname,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_POLICY as i32,
        is_nsp_name_unique: false,
    },
    ObjectPropertyType {
        class_descr: "event trigger",
        class_oid: EventTriggerRelationId,
        oid_index_oid: EventTriggerOidIndexId,
        oid_catcache_id: EVENTTRIGGEROID,
        name_catcache_id: EVENTTRIGGERNAME,
        attnum_oid: Anum_pg_event_trigger_oid,
        attnum_name: Anum_pg_event_trigger_evtname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_event_trigger_evtowner,
        attnum_acl: IA,
        objtype: OBJECT_EVENT_TRIGGER as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "text search configuration",
        class_oid: TSConfigRelationId,
        oid_index_oid: TSConfigOidIndexId,
        oid_catcache_id: TSCONFIGOID,
        name_catcache_id: TSCONFIGNAMENSP,
        attnum_oid: Anum_pg_ts_config_oid,
        attnum_name: Anum_pg_ts_config_cfgname,
        attnum_namespace: Anum_pg_ts_config_cfgnamespace,
        attnum_owner: Anum_pg_ts_config_cfgowner,
        attnum_acl: IA,
        objtype: OBJECT_TSCONFIGURATION as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "text search dictionary",
        class_oid: TSDictionaryRelationId,
        oid_index_oid: TSDictionaryOidIndexId,
        oid_catcache_id: TSDICTOID,
        name_catcache_id: TSDICTNAMENSP,
        attnum_oid: Anum_pg_ts_dict_oid,
        attnum_name: Anum_pg_ts_dict_dictname,
        attnum_namespace: Anum_pg_ts_dict_dictnamespace,
        attnum_owner: Anum_pg_ts_dict_dictowner,
        attnum_acl: IA,
        objtype: OBJECT_TSDICTIONARY as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "text search parser",
        class_oid: TSParserRelationId,
        oid_index_oid: TSParserOidIndexId,
        oid_catcache_id: TSPARSEROID,
        name_catcache_id: TSPARSERNAMENSP,
        attnum_oid: Anum_pg_ts_parser_oid,
        attnum_name: Anum_pg_ts_parser_prsname,
        attnum_namespace: Anum_pg_ts_parser_prsnamespace,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_TSPARSER as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "text search template",
        class_oid: TSTemplateRelationId,
        oid_index_oid: TSTemplateOidIndexId,
        oid_catcache_id: TSTEMPLATEOID,
        name_catcache_id: TSTEMPLATENAMENSP,
        attnum_oid: Anum_pg_ts_template_oid,
        attnum_name: Anum_pg_ts_template_tmplname,
        attnum_namespace: Anum_pg_ts_template_tmplnamespace,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_TSTEMPLATE as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "type",
        class_oid: TypeRelationId,
        oid_index_oid: TypeOidIndexId,
        oid_catcache_id: TYPEOID,
        name_catcache_id: TYPENAMENSP,
        attnum_oid: Anum_pg_type_oid,
        attnum_name: Anum_pg_type_typname,
        attnum_namespace: Anum_pg_type_typnamespace,
        attnum_owner: Anum_pg_type_typowner,
        attnum_acl: Anum_pg_type_typacl,
        objtype: OBJECT_TYPE as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "publication",
        class_oid: PublicationRelationId,
        oid_index_oid: PublicationObjectIndexId,
        oid_catcache_id: PUBLICATIONOID,
        name_catcache_id: PUBLICATIONNAME,
        attnum_oid: Anum_pg_publication_oid,
        attnum_name: Anum_pg_publication_pubname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_publication_pubowner,
        attnum_acl: IA,
        objtype: OBJECT_PUBLICATION as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "subscription",
        class_oid: SubscriptionRelationId,
        oid_index_oid: SubscriptionObjectIndexId,
        oid_catcache_id: SUBSCRIPTIONOID,
        name_catcache_id: SUBSCRIPTIONNAME,
        attnum_oid: Anum_pg_subscription_oid,
        attnum_name: Anum_pg_subscription_subname,
        attnum_namespace: IA,
        attnum_owner: Anum_pg_subscription_subowner,
        attnum_acl: IA,
        objtype: OBJECT_SUBSCRIPTION as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "extended statistics",
        class_oid: StatisticExtRelationId,
        oid_index_oid: StatisticExtOidIndexId,
        oid_catcache_id: STATEXTOID,
        name_catcache_id: STATEXTNAMENSP,
        attnum_oid: Anum_pg_statistic_ext_oid,
        attnum_name: Anum_pg_statistic_ext_stxname,
        attnum_namespace: Anum_pg_statistic_ext_stxnamespace,
        attnum_owner: Anum_pg_statistic_ext_stxowner,
        attnum_acl: IA, // no ACL (same as relation)
        objtype: OBJECT_STATISTIC_EXT as i32,
        is_nsp_name_unique: true,
    },
    ObjectPropertyType {
        class_descr: "user mapping",
        class_oid: UserMappingRelationId,
        oid_index_oid: UserMappingOidIndexId,
        oid_catcache_id: USERMAPPINGOID,
        name_catcache_id: -1,
        attnum_oid: Anum_pg_user_mapping_oid,
        attnum_name: IA,
        attnum_namespace: IA,
        attnum_owner: IA,
        attnum_acl: IA,
        objtype: OBJECT_USER_MAPPING as i32,
        is_nsp_name_unique: false,
    },
];

/// `struct object_type_map { const char *tm_name; ObjectType tm_type; }`.
///
/// `tm_type` is the raw `i32` because some rows are `-1` (unmapped).
#[derive(Clone, Copy, Debug)]
pub struct ObjectTypeMapEntry {
    pub tm_name: &'static str,
    pub tm_type: i32,
}

const fn m(name: &'static str, t: ObjectType) -> ObjectTypeMapEntry {
    ObjectTypeMapEntry {
        tm_name: name,
        tm_type: t as i32,
    }
}
const fn mu(name: &'static str) -> ObjectTypeMapEntry {
    ObjectTypeMapEntry {
        tm_name: name,
        tm_type: -1,
    }
}

/// `static const struct object_type_map ObjectTypeMap[]` — follows the order of
/// `getObjectTypeDescription`, 1:1 with C (incl. the `-1` "unmapped" rows).
pub static OBJECT_TYPE_MAP: &[ObjectTypeMapEntry] = &[
    m("table", OBJECT_TABLE),
    m("index", OBJECT_INDEX),
    m("sequence", OBJECT_SEQUENCE),
    mu("toast table"),
    m("view", OBJECT_VIEW),
    m("materialized view", OBJECT_MATVIEW),
    mu("composite type"),
    m("foreign table", OBJECT_FOREIGN_TABLE),
    m("table column", OBJECT_COLUMN),
    mu("index column"),
    mu("sequence column"),
    mu("toast table column"),
    mu("view column"),
    mu("materialized view column"),
    mu("composite type column"),
    m("foreign table column", OBJECT_COLUMN),
    m("aggregate", OBJECT_AGGREGATE),
    m("function", OBJECT_FUNCTION),
    m("procedure", OBJECT_PROCEDURE),
    m("type", OBJECT_TYPE),
    m("cast", OBJECT_CAST),
    m("collation", OBJECT_COLLATION),
    m("table constraint", OBJECT_TABCONSTRAINT),
    m("domain constraint", OBJECT_DOMCONSTRAINT),
    m("conversion", OBJECT_CONVERSION),
    m("default value", OBJECT_DEFAULT),
    m("language", OBJECT_LANGUAGE),
    m("large object", OBJECT_LARGEOBJECT),
    m("operator", OBJECT_OPERATOR),
    m("operator class", OBJECT_OPCLASS),
    m("operator family", OBJECT_OPFAMILY),
    m("access method", OBJECT_ACCESS_METHOD),
    m("operator of access method", OBJECT_AMOP),
    m("function of access method", OBJECT_AMPROC),
    m("rule", OBJECT_RULE),
    m("trigger", OBJECT_TRIGGER),
    m("schema", OBJECT_SCHEMA),
    m("text search parser", OBJECT_TSPARSER),
    m("text search dictionary", OBJECT_TSDICTIONARY),
    m("text search template", OBJECT_TSTEMPLATE),
    m("text search configuration", OBJECT_TSCONFIGURATION),
    m("role", OBJECT_ROLE),
    mu("role membership"),
    m("database", OBJECT_DATABASE),
    m("tablespace", OBJECT_TABLESPACE),
    m("foreign-data wrapper", OBJECT_FDW),
    m("server", OBJECT_FOREIGN_SERVER),
    m("user mapping", OBJECT_USER_MAPPING),
    m("default acl", OBJECT_DEFACL),
    m("extension", OBJECT_EXTENSION),
    m("event trigger", OBJECT_EVENT_TRIGGER),
    m("parameter ACL", OBJECT_PARAMETER_ACL),
    m("policy", OBJECT_POLICY),
    m("publication", OBJECT_PUBLICATION),
    m("publication namespace", OBJECT_PUBLICATION_NAMESPACE),
    m("publication relation", OBJECT_PUBLICATION_REL),
    m("subscription", OBJECT_SUBSCRIPTION),
    m("transform", OBJECT_TRANSFORM),
    m("statistics object", OBJECT_STATISTIC_EXT),
];
