-- Object zoo for the information_schema differential matrix. Run once by C
-- postgres against the shared datadir; both sides then capture the matrix.
CREATE ROLE ischeck_role1;
CREATE ROLE ischeck_role2;

CREATE SCHEMA ischeck;
SET search_path = ischeck, public;

CREATE COLLATION ischeck.testcoll (locale = 'C');

CREATE DOMAIN ischeck.posint AS integer DEFAULT 42 CHECK (VALUE > 0);
CREATE DOMAIN ischeck.shortname AS varchar(16) NOT NULL COLLATE "C";

CREATE TYPE ischeck.rgb AS ENUM ('red', 'green', 'blue');
CREATE TYPE ischeck.pair AS (a integer, b text);
CREATE TYPE ischeck.floatrange AS RANGE (subtype = float8);

CREATE SEQUENCE ischeck.standalone_seq INCREMENT 5 MINVALUE 10 MAXVALUE 9999 START 15 CYCLE;

CREATE TABLE ischeck.parent (
    id integer NOT NULL,
    tag varchar(32) DEFAULT 'none',
    CONSTRAINT parent_pk PRIMARY KEY (id),
    CONSTRAINT parent_tag_uni UNIQUE (tag)
);

CREATE TABLE ischeck.child (
    cid serial,
    pid integer,
    amount numeric(12,3) CHECK (amount >= 0),
    label ischeck.shortname,
    pos ischeck.posint,
    color ischeck.rgb DEFAULT 'red',
    ts timestamp(3) DEFAULT '2020-01-01 00:00:00',
    iv interval hour to minute,
    bits bit(5),
    vbits bit varying(10),
    arr integer[],
    doubled integer GENERATED ALWAYS AS (pid * 2) STORED,
    ident bigint GENERATED BY DEFAULT AS IDENTITY (START 100 INCREMENT 3),
    CONSTRAINT child_pk PRIMARY KEY (cid),
    CONSTRAINT child_fk FOREIGN KEY (pid) REFERENCES ischeck.parent (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT child_amount_label CHECK (amount IS NULL OR label <> 'zero')
);

CREATE TABLE ischeck.part (pk integer, region text, PRIMARY KEY (pk, region))
    PARTITION BY LIST (region);
CREATE TABLE ischeck.part_east PARTITION OF ischeck.part FOR VALUES IN ('east');

CREATE VIEW ischeck.v_child AS
    SELECT cid, pid, amount FROM ischeck.child WHERE amount > 0;
CREATE VIEW ischeck.v_child_co AS
    SELECT cid, pid FROM ischeck.child WHERE pid IS NOT NULL
    WITH CASCADED CHECK OPTION;
CREATE VIEW ischeck.v_join AS
    SELECT c.cid, p.tag FROM ischeck.child c JOIN ischeck.parent p ON c.pid = p.id;

CREATE FUNCTION ischeck.add_pair(x integer, y integer DEFAULT 7, OUT total integer)
    LANGUAGE sql IMMUTABLE STRICT
    AS 'SELECT x + y';
CREATE FUNCTION ischeck.swap(INOUT a integer, INOUT b integer)
    LANGUAGE sql AS 'SELECT b, a';
CREATE FUNCTION ischeck.list_tags() RETURNS SETOF varchar
    LANGUAGE sql STABLE AS 'SELECT tag FROM ischeck.parent ORDER BY tag';
CREATE PROCEDURE ischeck.bump(IN delta integer)
    LANGUAGE sql AS 'UPDATE ischeck.parent SET id = id + delta';

CREATE FUNCTION ischeck.trg_fn() RETURNS trigger LANGUAGE plpgsql AS
$$BEGIN NEW.tag := lower(NEW.tag); RETURN NEW; END$$;
CREATE TRIGGER parent_lower_tag
    BEFORE INSERT OR UPDATE OF tag ON ischeck.parent
    FOR EACH ROW WHEN (NEW.tag IS NOT NULL)
    EXECUTE FUNCTION ischeck.trg_fn();

CREATE FOREIGN DATA WRAPPER ischeck_fdw OPTIONS (debug 'true');
CREATE SERVER ischeck_srv FOREIGN DATA WRAPPER ischeck_fdw OPTIONS (host 'localhost', dbname 'x');
CREATE USER MAPPING FOR postgres SERVER ischeck_srv OPTIONS (user 'remote');
-- Handler-less FDW: a foreign table in the main schema would make the
-- columns/tables views error (pg_relation_is_updatable needs a handler), so
-- it lives in its own schema and is probed separately.
CREATE SCHEMA ischeck_ft;
CREATE FOREIGN TABLE ischeck_ft.ftab (fa integer NOT NULL, fb text)
    SERVER ischeck_srv OPTIONS (schema_name 'remote_s', table_name 'remote_t');

GRANT SELECT, INSERT ON ischeck.parent TO ischeck_role1;
GRANT SELECT (cid, amount), UPDATE (amount) ON ischeck.child TO ischeck_role2;
GRANT USAGE ON DOMAIN ischeck.posint TO ischeck_role1;
GRANT USAGE, SELECT ON SEQUENCE ischeck.standalone_seq TO ischeck_role2;
GRANT EXECUTE ON FUNCTION ischeck.add_pair(integer, integer) TO ischeck_role1;
GRANT ischeck_role1 TO ischeck_role2 WITH ADMIN OPTION;

INSERT INTO ischeck.parent VALUES (1, 'alpha'), (2, 'beta');
INSERT INTO ischeck.child (pid, amount, label, bits, vbits, arr, iv)
    VALUES (1, 10.5, 'one', B'10101', B'1100', ARRAY[1,2], '3:30');
