[package]
name = "execexpr"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
mcx = { path = "../../../_support/mcx" }
datum = { path = "../../../_support/types/datum" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_fmgr = { path = "../../../_support/types/fmgr" }
types_nodes = { path = "../../../_support/types/nodes" }
types_portal = { path = "../../../_support/types/portal" }
types_slot = { path = "../../../_support/types/types_slot" }
types_tuple = { path = "../../../_support/types/types_tuple" }
fmgr_core = { path = "../../utils/fmgr/fmgr_core" }
typcache = { path = "../../utils/cache/typcache" }
format_type = { path = "../../utils/adt/format_type" }
exectuples = { path = "../exectuples" }
lsyscache = { path = "../../utils/cache/lsyscache" }
clauses_seams = { path = "../../optimizer/util/clauses_seams" }
guc_tables = { path = "../../utils/misc/guc_tables" }
aclchk_seams = { path = "../../catalog/aclchk_seams" }
miscinit_seams = { path = "../../utils/init/miscinit_seams" }

[features]
bench-internals = []

[dev-dependencies]
adt_int = { path = "../../utils/adt/int" }
indexcmds_seams = { path = "../../commands/indexcmds_seams" }
heaptuple = { path = "../../access/common/heaptuple" }
syscache_seams = { path = "../../utils/cache/syscache_seams" }
