[package]
name = "rewrite_handler"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../_support/mcx" }
datum = { path = "../../../_support/types/datum" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_rel = { path = "../../../_support/types/rel" }
table = { path = "../../access/table/table" }
rewrite_handler_seams = { path = "../rewrite_handler_seams" }
foreigncmds_seams = { path = "../../commands/foreigncmds_seams" }
nodes_core = { path = "../../nodes/nodes_core" }
readfuncs = { path = "../../nodes/readfuncs" }
rewrite_manip = { path = "../rewrite_manip" }
rewrite_search_cycle = { path = "../rewrite_search_cycle" }
relcache = { path = "../../utils/cache/relcache" }
rowsecurity = { path = "../rowsecurity" }
coerce = { path = "../../parser/coerce" }
parse_expr = { path = "../../parser/parse_expr" }
parse_relation = { path = "../../parser/parse_relation" }
parser_analyze = { path = "../../parser/parser_analyze" }
relation = { path = "../../access/common/relation" }
parser_small1 = { path = "../../parser/parser_small1" }
format_type = { path = "../../utils/adt/format_type" }
pg_depend = { path = "../../catalog/pg_depend" }
lsyscache = { path = "../../utils/cache/lsyscache" }
types_tuple = { path = "../../../_support/types/types_tuple" }
cache_syscache = { path = "../../utils/cache/cache_syscache" }
funcapi = { path = "../../utils/fmgr/funcapi" }
types_fmgr = { path = "../../../_support/types/fmgr" }
guc_tables = { path = "../../utils/misc/guc_tables" }

[dev-dependencies]
execreplication = { path = "../../executor/execreplication" }
transam_seams = { path = "../../access/transam/transam_seams" }
lock = { path = "../../storage/lmgr/lock" }
logical_worker_seams = { path = "../../replication/logical_worker_seams" }
dbcommands_seams = { path = "../../commands/dbcommands_seams" }
resowner = { path = "../../utils/resowner/resowner" }
sinval_seams = { path = "../../storage/ipc/sinval_seams" }
sync_seams = { path = "../../storage/sync/sync_seams" }
adt_float = { path = "../../utils/adt/float" }
adt_bool = { path = "../../utils/adt/bool" }
guc = { path = "../../utils/misc/guc" }
relcache_seams = { path = "../../utils/cache/relcache_seams" }
rls_seams = { path = "../../utils/misc/rls_seams" }
aclchk_seams = { path = "../../catalog/aclchk_seams" }
aio_seams = { path = "../../storage/aio/aio_seams" }
async_seams = { path = "../../commands/async_seams" }
autovacuum_seams = { path = "../../postmaster/autovacuum_seams" }
backend_progress_seams = { path = "../../utils/activity/backend_progress_seams" }
backend_status_seams = { path = "../../utils/activity/backend_status_seams" }
be_fsstubs_seams = { path = "../../libpq/be_fsstubs_seams" }
bufmgr_seams = { path = "../../storage/buffer/bufmgr_seams" }
catalog_index_seams = { path = "../../catalog/catalog_index_seams" }
catalog_seams = { path = "../../catalog/catalog_seams" }
catalog_storage_seams = { path = "../../catalog/storage_seams" }
clog = { path = "../../access/transam/clog" }
combocid_seams = { path = "../../utils/time/combocid_seams" }
commit_ts_seams = { path = "../../access/transam/commit_ts_seams" }
condition_variable_seams = { path = "../../storage/lmgr/condition_variable_seams" }
controldata_utils = { path = "../../../common/controldata_utils" }
deadlock_seams = { path = "../../storage/lmgr/deadlock_seams" }
execmain = { path = "../../executor/execmain" }
execmain_seams = { path = "../../executor/execmain_seams" }
exectuples = { path = "../../executor/exectuples" }
executils = { path = "../../executor/executils" }
explain = { path = "../../commands/explain" }
fd = { path = "../../storage/file/fd" }
freespace_seams = { path = "../../storage/freespace/freespace_seams" }
gram_core = { path = "../../parser/gram_core" }
guc_tables = { path = "../../utils/misc/guc_tables" }
heapam_visibility = { path = "../../access/heap/heapam_visibility" }
init_small = { path = "../../utils/init/init_small" }
inval = { path = "../../utils/cache/inval" }
ipc_seams = { path = "../../storage/ipc/ipc_seams" }
latch_seams = { path = "../../storage/ipc/latch_seams" }
lmgr_proc = { path = "../../storage/lmgr/lmgr_proc" }
lmgr_seams = { path = "../../storage/lmgr/lmgr_seams" }
lock_seams = { path = "../../storage/lmgr/lock_seams" }
logical_seams = { path = "../../replication/logical_seams" }
lwlock = { path = "../../storage/lmgr/lwlock" }
miscinit_seams = { path = "../../utils/init/miscinit_seams" }
multixact_seams = { path = "../../access/transam/multixact_seams" }
namespace_seams = { path = "../../catalog/namespace_seams" }
nodeseqscan = { path = "../../executor/nodeseqscan" }
origin_seams = { path = "../../replication/origin_seams" }
parallel_seams = { path = "../../access/transam/parallel_seams" }
parser_analyze = { path = "../../parser/parser_analyze" }
parser_driver = { path = "../../parser/parser_driver" }
parser_seams = { path = "../../parser/parser_seams" }
pg_enum_seams = { path = "../../catalog/pg_enum_seams" }
pg_sema_seams = { path = "../../port/pg_sema_seams" }
pgstat = { path = "../../utils/activity/pgstat" }
planner = { path = "../../optimizer/plan/planner" }
pmsignal_seams = { path = "../../storage/ipc/pmsignal_seams" }
predicate_seams = { path = "../../storage/lmgr/predicate_seams" }
procarray = { path = "../../storage/ipc/procarray" }
pruneheap_seams = { path = "../../access/heap/pruneheap_seams" }
rel_vocab = { path = "../../../_support/types/rel_vocab" }
relcache_build_seams = { path = "../../utils/cache/relcache_build_seams" }
rmgr = { path = "../../access/transam/rmgr" }
s_lock_seams = { path = "../../storage/lmgr/s_lock_seams" }
scan_fgram = { path = "../../parser/scan_fgram" }
shmem = { path = "../../storage/ipc/shmem" }
snapbuild_seams = { path = "../../replication/snapbuild_seams" }
snapmgr = { path = "../../utils/time/snapmgr" }
spi_seams = { path = "../../executor/spi_seams" }
subtrans = { path = "../../access/transam/subtrans" }
syncrep_seams = { path = "../../replication/syncrep_seams" }
syscache_seams = { path = "../../utils/cache/syscache_seams" }
indexcmds_seams = { path = "../../commands/indexcmds_seams" }
tableam = { path = "../../access/table/tableam" }
tableam_vocab = { path = "../../access/table/tableam_vocab" }
tablecmds_seams = { path = "../../commands/tablecmds_seams" }
tcop_dest = { path = "../../tcop/dest" }
timeout_seams = { path = "../../utils/misc/timeout_seams" }
timestamp_seams = { path = "../../utils/adt/timestamp_seams" }
transam = { path = "../../access/transam/transam" }
transam_xlog = { path = "../../access/transam/transam_xlog" }
transam_xlog_seams = { path = "../../access/transam/transam_xlog_seams" }
trigger_seams = { path = "../../commands/trigger_seams" }
typcache_seams = { path = "../../utils/cache/typcache_seams" }
types_dest = { path = "../../../_support/types/types_dest" }
types_portal = { path = "../../../_support/types/portal" }
types_scan = { path = "../../../_support/types/types_scan" }
types_slot = { path = "../../../_support/types/types_slot" }
types_snapshot = { path = "../../../_support/types/snapshot" }
types_storage = { path = "../../../_support/types/types_storage" }
varsup = { path = "../../access/transam/varsup" }
waitevent_seams = { path = "../../utils/activity/waitevent_seams" }
xact = { path = "../../access/transam/xact" }
xact_seams = { path = "../../access/transam/xact_seams" }
xlogutils = { path = "../../access/transam/xlogutils" }
xloginsert = { path = "../../access/transam/xloginsert" }
xloginsert_seams = { path = "../../access/transam/xloginsert_seams" }
relation_seams = { path = "../../access/common/relation_seams" }
types_tuple = { path = "../../../_support/types/types_tuple" }
datum = { path = "../../../_support/types/datum" }
