#!/usr/bin/env python3
"""gen_enum_domains.py — emit gen/enum_domains.tsv: for every `typedef enum`
in the vendored header closure, the set of integer values C's own writer can
emit for a field of that enum type.

WHY: the nodesfam gate must restrict the compared domain to node text C's
outfuncs could have written. An out-of-domain enum integer is not writer-
producible, and the two sides diverge on it in TWO different ways (the port
either panics on validation or silently maps to the default, e.g.
`{JSONFORMAT :format_type 5 ...}` where C echoes 5 and pgrust echoes 0).

Format: <EnumName>\t<comma-separated values>   — or `*` when the block has an
initializer this parser will not model (bit shifts, arithmetic, references to
other constants); such enums stay fully permissive and their divergences are
handled by the panic-carve classes instead. Called by assemble.sh.
"""
import os
import re
import sys

root = sys.argv[1]            # nodesfam/include
out_path = sys.argv[2]        # nodesfam/gen/enum_domains.tsv

BLOCK = re.compile(r"typedef\s+enum\s+(\w+)?\s*\{(.*?)\}\s*(\w+)\s*;", re.S)

rows = {}
for dirpath, _dirs, files in os.walk(root):
    for f in files:
        if not f.endswith(".h"):
            continue
        text = open(os.path.join(dirpath, f), encoding="utf-8", errors="replace").read()
        # strip comments so initializers parse cleanly
        text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
        text = re.sub(r"//[^\n]*", " ", text)
        for m in BLOCK.finditer(text):
            name = m.group(3) or m.group(1)
            if not name:
                continue
            values, nxt, opaque = [], 0, False
            for part in m.group(2).split(","):
                part = part.strip()
                if not part:
                    continue
                if "=" in part:
                    _, rhs = part.split("=", 1)
                    rhs = rhs.strip()
                    try:
                        nxt = int(rhs, 0)
                    except ValueError:
                        opaque = True
                        break
                values.append(nxt)
                nxt += 1
            rows[name] = "*" if opaque else ",".join(str(v) for v in sorted(set(values)))

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w") as fh:
    fh.write("# enum-domain table for the nodesfam gate — GENERATED by\n")
    fh.write("# gen_enum_domains.py over the vendored header closure. '*' = not modelled.\n")
    for name in sorted(rows):
        fh.write(f"{name}\t{rows[name]}\n")
print(f"enum_domains: {len(rows)} enums", file=sys.stderr)
