[package]
name = "execscan"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
postgres_seams = { path = "../../tcop/postgres_seams" }
mcx = { path = "../../../_support/mcx" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_slot = { path = "../../../_support/types/types_slot" }
types_tuple = { path = "../../../_support/types/types_tuple" }
types_snapshot = { path = "../../../_support/types/snapshot" }
types_rel = { path = "../../../_support/types/rel" }
tupdesc = { path = "../../access/common/tupdesc" }
init_small = { path = "../../utils/init/init_small" }
tableam = { path = "../../access/table/tableam" }
exectuples = { path = "../exectuples" }
detoast_seams = { path = "../../access/common/detoast_seams" }
execexpr = { path = "../execexpr" }
executils = { path = "../executils" }
nodes_core = { path = "../../nodes/nodes_core" }

[dev-dependencies]
datum = { path = "../../../_support/types/datum" }
syscache_seams = { path = "../../utils/cache/syscache_seams" }
