#!/usr/bin/env perl
# Generates src/generated.rs — the built-in catalog tables the typcache mock
# serves — FROM the vendored PostgreSQL catalog .dat files (never hand-typed).
#
# Usage:
#   PGSRC=/path/to/vendor/postgres-src perl generate.pl > src/generated.rs
# Default PGSRC matches the sibling pgrust-fabled clone layout.
#
# Faithfulness notes:
# - Rows are parsed with PostgreSQL's own Catalog.pm (ParseHeader + ParseData),
#   so pg_type array-type synthesis (Catalog.pm GenerateArrayTypes) and the
#   BKI_DEFAULT / BKI_ARRAY_DEFAULT column defaults are PostgreSQL's, not ours.
# - Symbolic references (regproc names, 'btree/integer_ops' opfamily keys,
#   '=(int4,int4)' operator keys, type names) are resolved with the same rules
#   genbki.pl uses (unique-name or full-signature for procs; name(l,r) for
#   operators; am/name for opfamilies and opclasses).
# - NAMEDATALEN = 64; FLOAT8PASSBYVAL = true (64-bit Datum, as pgrust builds).
use strict;
use warnings;

my $pgsrc = $ENV{PGSRC}
  // "$ENV{HOME}/dev/pgrust-fabled/vendor/postgres-src";
my $cat = "$pgsrc/src/include/catalog";
die "no catalog dir at $cat" unless -d $cat;
unshift @INC, "$pgsrc/src/backend/catalog";
require Catalog;

sub load {
    my ($name) = @_;
    my $h = Catalog::ParseHeader("$cat/$name.h");
    my $rows = Catalog::ParseData("$cat/$name.dat", $h->{columns}, 0);
    # Apply per-column BKI_DEFAULT for absent fields (genbki.pl morph step),
    # and replicate genbki.pl assign_next_oid: rows without an explicit oid get
    # sequential oids from FirstGenbkiObjectId (10000), per catalog, in row
    # order — byte-identical to what initdb ships for these pinned catalogs.
    my $has_oid = grep { $_->{name} eq 'oid' } @{ $h->{columns} };
    my $next_oid = 10000;    # FirstGenbkiObjectId (access/transam.h)
    for my $r (@$rows) {
        next unless ref $r eq 'HASH';
        $r->{oid} = $next_oid++ if $has_oid && !defined $r->{oid};
        for my $c (@{ $h->{columns} }) {
            my $n = $c->{name};
            $r->{$n} = $c->{default} if !defined $r->{$n} && defined $c->{default};
        }
    }
    return ($h, [ grep { ref $_ eq 'HASH' } @$rows ]);
}

my ($type_h, $types)   = load('pg_type');
my ($am_h, $ams)       = load('pg_am');
my ($opf_h, $opfs)     = load('pg_opfamily');
my ($opc_h, $opcs)     = load('pg_opclass');
my ($amop_h, $amops)   = load('pg_amop');
my ($amproc_h, $amprocs) = load('pg_amproc');
my ($oper_h, $opers)   = load('pg_operator');
my ($range_h, $ranges) = load('pg_range');
my ($cast_h, $casts)   = load('pg_cast');
my ($coll_h, $colls)   = load('pg_collation');
my ($class_h, $classes) = load('pg_class');
my ($proc_h, $procs)   = load('pg_proc');

# ---- lookup maps (genbki.pl lookup_kind equivalents) ----
my (%typeoid, %amoid, %opfoid, %opcoid, %colloid, %classoid, %operoid, %procbyname);
$typeoid{ $_->{typname} } = $_->{oid} for @$types;
$amoid{ $_->{amname} }    = $_->{oid} for @$ams;
$opfoid{ "$_->{opfmethod}/$_->{opfname}" } = $_->{oid} for @$opfs;
$opcoid{ "$_->{opcmethod}/$_->{opcname}" } = $_->{oid} for @$opcs;
$colloid{ $_->{collname} } = $_->{oid} for @$colls;
$classoid{ $_->{relname} } = $_->{oid} for @$classes;
$operoid{ "$_->{oprname}($_->{oprleft},$_->{oprright})" } = $_->{oid} for @$opers;
push @{ $procbyname{ $_->{proname} } }, $_ for @$procs;

sub res_type {
    my ($v) = @_;
    return 0 if !defined $v || $v eq '0' || $v eq '-';
    defined $typeoid{$v} ? $typeoid{$v} : ($v =~ /^\d+$/ ? $v : die "type? $v");
}
sub res_proc {
    my ($v) = @_;
    return 0 if !defined $v || $v eq '0' || $v eq '-';
    if ($v =~ /^(\w+)\((.*)\)$/) {
        my ($n, $args) = ($1, $2);
        my $sig = join ' ', map { my $t = $_; $t =~ s/^\s+|\s+$//g; $t } split /,/, $args;
        for my $p (@{ $procbyname{$n} // [] }) {
            return $p->{oid} if ($p->{proargtypes} // '') eq $sig;
        }
        die "proc? $v";
    }
    my $c = $procbyname{$v} // die "proc? $v";
    die "ambiguous proc $v" if @$c != 1;
    return $c->[0]{oid};
}
sub res_oper {
    my ($v) = @_;
    return 0 if !defined $v || $v eq '0' || $v eq '-';
    defined $operoid{$v} ? $operoid{$v} : die "oper? $v";
}
sub res_simple {
    my ($map, $v, $what) = @_;
    return 0 if !defined $v || $v eq '0' || $v eq '-';
    defined $map->{$v} ? $map->{$v} : ($v =~ /^\d+$/ ? $v : die "$what? $v");
}
sub b { my ($v) = @_; $v eq 't' ? 'true' : 'false' }
sub ch { my ($v) = @_; die "char? $v" unless length($v) == 1; sprintf "%d", ord($v) }

my $out = '';
$out .= "// GENERATED by generate.pl from the vendored PostgreSQL catalog .dat files\n";
$out .= "// (REL_18 vendor tree). DO NOT HAND-EDIT — rerun:\n";
$out .= "//   PGSRC=.../vendor/postgres-src perl generate.pl > src/generated.rs\n";
$out .= "#![allow(clippy::all)]\n\npub type Oid = u32;\n\n";

# ---- pg_type ----
$out .= <<'EOS';
#[derive(Clone, Copy, Debug)]
pub struct GenPgType {
    pub oid: Oid,
    pub typname: &'static str,
    pub typlen: i16,
    pub typbyval: bool,
    pub typalign: u8,
    pub typstorage: u8,
    pub typtype: u8,
    pub typcategory: u8,
    pub typispreferred: bool,
    pub typisdefined: bool,
    pub typdelim: u8,
    pub typrelid: Oid,
    pub typsubscript: Oid,
    pub typelem: Oid,
    pub typarray: Oid,
    pub typcollation: Oid,
    pub typinput: Oid,
    pub typoutput: Oid,
    pub typreceive: Oid,
    pub typsend: Oid,
    pub typmodin: Oid,
    pub typmodout: Oid,
}
EOS
$out .= "pub const PG_TYPE: &[GenPgType] = &[\n";
for my $t (sort { $a->{oid} <=> $b->{oid} } @$types) {
    my $len = $t->{typlen};
    $len = 64 if $len eq 'NAMEDATALEN';        # pg_config: NAMEDATALEN
    $len = 8 if $len eq 'SIZEOF_POINTER';      # 64-bit build
    my $byval = $t->{typbyval};
    $byval = 't' if $byval eq 'FLOAT8PASSBYVAL';    # 64-bit Datum
    my $align = $t->{typalign};
    $align = 'd' if $align eq 'ALIGNOF_POINTER';    # 64-bit pointers
    local $t->{typalign} = $align;
    $out .= sprintf
      "    GenPgType { oid: %d, typname: \"%s\", typlen: %d, typbyval: %s, typalign: %s, typstorage: %s, typtype: %s, typcategory: %s, typispreferred: %s, typisdefined: %s, typdelim: %s, typrelid: %d, typsubscript: %d, typelem: %d, typarray: %d, typcollation: %d, typinput: %d, typoutput: %d, typreceive: %d, typsend: %d, typmodin: %d, typmodout: %d },\n",
      $t->{oid}, $t->{typname}, $len, b($byval), ch($t->{typalign}),
      ch($t->{typstorage}), ch($t->{typtype}), ch($t->{typcategory}),
      b($t->{typispreferred}), b($t->{typisdefined}), ch($t->{typdelim}),
      res_simple(\%classoid, $t->{typrelid}, 'class'),
      res_proc($t->{typsubscript}), res_type($t->{typelem}),
      res_type($t->{typarray}), res_simple(\%colloid, $t->{typcollation}, 'coll'),
      res_proc($t->{typinput}), res_proc($t->{typoutput}),
      res_proc($t->{typreceive}), res_proc($t->{typsend}),
      res_proc($t->{typmodin}), res_proc($t->{typmodout});
}
$out .= "];\n\n";

# ---- pg_opclass ----
$out .= "// (oid, opcmethod, opcfamily, opcintype, opckeytype, opcdefault)\n";
$out .= "pub const PG_OPCLASS: &[(Oid, Oid, Oid, Oid, Oid, bool)] = &[\n";
for my $o (sort { $a->{oid} <=> $b->{oid} } @$opcs) {
    $out .= sprintf "    (%d, %d, %d, %d, %d, %s),\n",
      $o->{oid}, res_simple(\%amoid, $o->{opcmethod}, 'am'),
      res_simple(\%opfoid, $o->{opcfamily}, 'opf'),
      res_type($o->{opcintype}), res_type($o->{opckeytype}), b($o->{opcdefault});
}
$out .= "];\n\n";

# ---- pg_amop (search entries carry amoppurpose 's'; ordering entries 'o') ----
$out .= "// (amopfamily, amoplefttype, amoprighttype, amopstrategy, amoppurpose, amopopr)\n";
$out .= "pub const PG_AMOP: &[(Oid, Oid, Oid, i16, u8, Oid)] = &[\n";
for my $a (
    sort {
        res_simple(\%opfoid, $a->{amopfamily}, 'opf') <=> res_simple(\%opfoid, $b->{amopfamily}, 'opf')
          || res_type($a->{amoplefttype}) <=> res_type($b->{amoplefttype})
          || res_type($a->{amoprighttype}) <=> res_type($b->{amoprighttype})
          || $a->{amopstrategy} <=> $b->{amopstrategy}
    } @$amops)
{
    $out .= sprintf "    (%d, %d, %d, %d, %s, %d),\n",
      res_simple(\%opfoid, $a->{amopfamily}, 'opf'),
      res_type($a->{amoplefttype}), res_type($a->{amoprighttype}),
      $a->{amopstrategy}, ch($a->{amoppurpose}), res_oper($a->{amopopr});
}
$out .= "];\n\n";

# ---- pg_amproc ----
$out .= "// (amprocfamily, amproclefttype, amprocrighttype, amprocnum, amproc)\n";
$out .= "pub const PG_AMPROC: &[(Oid, Oid, Oid, i16, Oid)] = &[\n";
for my $a (
    sort {
        res_simple(\%opfoid, $a->{amprocfamily}, 'opf') <=> res_simple(\%opfoid, $b->{amprocfamily}, 'opf')
          || res_type($a->{amproclefttype}) <=> res_type($b->{amproclefttype})
          || res_type($a->{amprocrighttype}) <=> res_type($b->{amprocrighttype})
          || $a->{amprocnum} <=> $b->{amprocnum}
    } @$amprocs)
{
    $out .= sprintf "    (%d, %d, %d, %d, %d),\n",
      res_simple(\%opfoid, $a->{amprocfamily}, 'opf'),
      res_type($a->{amproclefttype}), res_type($a->{amprocrighttype}),
      $a->{amprocnum}, res_proc($a->{amproc});
}
$out .= "];\n\n";

# ---- pg_operator ----
$out .= <<'EOS';
#[derive(Clone, Copy, Debug)]
pub struct GenPgOperator {
    pub oid: Oid,
    pub oprname: &'static str,
    pub oprleft: Oid,
    pub oprright: Oid,
    pub oprresult: Oid,
    pub oprcom: Oid,
    pub oprnegate: Oid,
    pub oprcode: Oid,
    pub oprrest: Oid,
    pub oprjoin: Oid,
    pub oprcanmerge: bool,
    pub oprcanhash: bool,
}
EOS
$out .= "pub const PG_OPERATOR: &[GenPgOperator] = &[\n";
for my $o (sort { $a->{oid} <=> $b->{oid} } @$opers) {
    $out .= sprintf
      "    GenPgOperator { oid: %d, oprname: \"%s\", oprleft: %d, oprright: %d, oprresult: %d, oprcom: %d, oprnegate: %d, oprcode: %d, oprrest: %d, oprjoin: %d, oprcanmerge: %s, oprcanhash: %s },\n",
      $o->{oid}, ($o->{oprname} =~ s/\\/\\\\/gr =~ s/"/\\"/gr),
      res_type($o->{oprleft}), res_type($o->{oprright}), res_type($o->{oprresult}),
      res_oper($o->{oprcom}), res_oper($o->{oprnegate}), res_proc($o->{oprcode}),
      res_proc($o->{oprrest}), res_proc($o->{oprjoin}),
      b($o->{oprcanmerge}), b($o->{oprcanhash});
}
$out .= "];\n\n";

# ---- pg_range ----
$out .= "// (rngtypid, rngsubtype, rngmultitypid, rngcollation, rngsubopc, rngcanonical, rngsubdiff)\n";
$out .= "pub const PG_RANGE: &[(Oid, Oid, Oid, Oid, Oid, Oid, Oid)] = &[\n";
for my $r (sort { res_type($a->{rngtypid}) <=> res_type($b->{rngtypid}) } @$ranges) {
    $out .= sprintf "    (%d, %d, %d, %d, %d, %d, %d),\n",
      res_type($r->{rngtypid}), res_type($r->{rngsubtype}), res_type($r->{rngmultitypid}),
      res_simple(\%colloid, $r->{rngcollation}, 'coll'),
      res_simple(\%opcoid, $r->{rngsubopc}, 'opc'),
      res_proc($r->{rngcanonical}), res_proc($r->{rngsubdiff});
}
$out .= "];\n\n";

# ---- pg_cast ----
$out .= "// (castsource, casttarget, castfunc, castcontext, castmethod)\n";
$out .= "pub const PG_CAST: &[(Oid, Oid, Oid, u8, u8)] = &[\n";
for my $c (
    sort {
        res_type($a->{castsource}) <=> res_type($b->{castsource})
          || res_type($a->{casttarget}) <=> res_type($b->{casttarget})
    } @$casts)
{
    $out .= sprintf "    (%d, %d, %d, %s, %s),\n",
      res_type($c->{castsource}), res_type($c->{casttarget}), res_proc($c->{castfunc}),
      ch($c->{castcontext}), ch($c->{castmethod});
}
$out .= "];\n\n";

# ---- pg_am (small; for completeness/debug) ----
$out .= "// (oid, amname)\n";
$out .= "pub const PG_AM: &[(Oid, &str)] = &[\n";
for my $a (sort { $a->{oid} <=> $b->{oid} } @$ams) {
    $out .= sprintf "    (%d, \"%s\"),\n", $a->{oid}, $a->{amname};
}
$out .= "];\n";

print $out;
