[package]
name = "nodeworktablescan"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
execexpr = { path = "../execexpr" }
execscan = { path = "../execscan" }
exectuples = { path = "../exectuples" }
executils = { path = "../executils" }
mcx = { path = "../../../_support/mcx" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_scan = { path = "../../../_support/types/types_scan" }
types_slot = { path = "../../../_support/types/types_slot" }
