#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::result_large_err)]
#![allow(clippy::too_many_arguments)]

//! `backend/commands/indexcmds.c` — the CREATE INDEX command driver
//! (PostgreSQL 18.3).
//!
//! This unit grounds the high-value CREATE INDEX command path against the
//! repo's owned node / relcache model:
//!
//!  * [`DefineIndex`] — the command-level driver: validate the statement, open
//!    the table, resolve the access method, run [`ComputeIndexAttrs`], assemble
//!    the [`IndexInfo`] + [`IndexCreateArgs`], call `index_create`, and (for a
//!    non-concurrent, non-partitioned build) `index_create` already builds it.
//!  * [`ComputeIndexAttrs`] — per-column opclass / collation / expression
//!    resolution, exclusion / WITHOUT-OVERLAPS operator handling, included-column
//!    restrictions, `indoption` derivation, and per-column `attoptions`.
//!  * [`ResolveOpClass`] / [`GetOperatorFromCompareType`] / [`CheckPredicate`].
//!  * the autogenerated-name choosers
//!    ([`makeObjectName`] / [`ChooseRelationName`] / [`ChooseIndexName`] /
//!    `ChooseIndexNameAddition` / [`ChooseIndexColumnNames`]).
//!
//! `GetDefaultOpClass` lives in the repo's `pg_opclass` / lsyscache owner (a
//! home divergence already merged); [`ResolveOpClass`] reaches it through
//! `lsyscache::get_default_opclass`.
//!
//! ## Deferred (precise seam-panics, tracked)
//!
//! The CONCURRENTLY tail of `DefineIndex` (multi-transaction build/validate
//! state machine: `index_concurrently_build`, `validate_index`,
//! `WaitForLockers`, `WaitForOlderSnapshots`, snapshot/session-lock dance) and
//! the partitioned-table recursion (`generateClonedIndexStmt`,
//! `IndexSetParentIndex`, `BuildIndexInfo`/`CompareIndexInfo` matching) are NOT
//! built here — their substrate (cross-transaction control, partition-index
//! cloning) is unported. They are precise loud panics, not silent stubs.
//!
//! `ReindexIndex` / `ReindexTable` (the REINDEX drivers) seam-panic into the
//! `reindex_index` / `reindex_relation` seams, which are declared but
//! owner-uninstalled (substrate unported).

extern crate alloc;

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

use mcx::{Mcx, PgVec};

use types_core::primitive::Oid;
use types_core::{InvalidOid, OidIsValid};
use types_error::PgResult;
use types_nodes::ddlnodes::{IndexElem, IndexStmt};
use types_nodes::nodes::Node;
use types_nodes::primnodes::Expr;
use types_nodes::rawnodes::RangeVar;
use types_rel::Relation;

use backend_utils_error::ereport;
use types_error::ERROR;

// ---- real owner crates ----
use backend_nodes_core::makefuncs::{make_ands_implicit, make_index_info};
use backend_nodes_core::bitmapset::{bms_is_member, bms_next_member, bms_union};
use backend_catalog_index::index_check_primary_key;
use backend_access_index_amapi::GetIndexAmRoutineByAmId;
use backend_optimizer_util_clauses::contain_mutable_functions_after_planning;
use backend_commands_tablespace::{get_tablespace_name, get_tablespace_oid, GetDefaultTablespace};
use backend_commands_comment::CreateComments;
use backend_utils_misc_guc::{at_eoxact_guc, NewGUCNestLevel};
use backend_utils_misc_guc_seams::{restrict_search_path, set_config_option};
use backend_access_table_table::table_close as owner_table_close;
use backend_utils_init_miscinit::{GetUserIdAndSecContext, SetUserIdAndSecContext};
use backend_utils_activity_small::backend_progress::{
    pgstat_progress_end_command, pgstat_progress_incr_param, pgstat_progress_start_command,
    pgstat_progress_update_param,
};

// ---- seams consumed from other units ----
use backend_catalog_index_seams::{self as index_seam, IndexCreateArgs};
use backend_catalog_aclchk_seams as aclchk_seam;
use backend_utils_cache_lsyscache_seams as lsyscache;
use backend_utils_cache_syscache_seams as syscache;
use backend_optimizer_util_var_seams as var_seam;
use backend_commands_tablecmds_seams as tablecmds_seam;
use backend_access_heap_vacuumlazy_seams as namespacename_seam;
use backend_access_table_table_seams as table_seam;

use types_acl::acl::{ACL_CREATE, ACLCHECK_OK};
use types_nodes::parsenodes::{OBJECT_SCHEMA, OBJECT_TABLESPACE};
use types_catalog::catalog::{GLOBALTABLESPACE_OID, TABLESPACE_RELATION_ID};
use types_catalog::catalog_dependency::ObjectAddress;
use types_core::catalog::{NAMESPACE_RELATION_ID, RELATION_RELATION_ID};
use types_tuple::access::{
    ATTRIBUTE_GENERATED_VIRTUAL, RELKIND_MATVIEW, RELKIND_PARTITIONED_TABLE, RELKIND_RELATION,
};
use types_tuple::heaptuple::FirstLowInvalidHeapAttributeNumber;
use types_pgstat::backend_progress::ProgressCommandType;

pub mod choosers;
pub mod compute;
pub mod opclass;

pub use choosers::{
    makeObjectName, ChooseIndexColumnNames, ChooseIndexName, ChooseRelationName,
};
pub use compute::ComputeIndexAttrs;
pub use opclass::{GetOperatorFromCompareType, ResolveOpClass};

/// `NAMEDATALEN` (`pg_config_manual.h`).
pub(crate) const NAMEDATALEN: i32 = 64;

/// `INDEX_MAX_KEYS` (`pg_config_manual.h`).
const INDEX_MAX_KEYS: i32 = 32;

/// `RELPERSISTENCE_TEMP` (`catalog/pg_class.h`).
const RELPERSISTENCE_TEMP: u8 = b't';

// `index.h` `index_create` flag bits / constraint flag bits (defined locally,
// mirroring `catalog/index.h`, matching the established pattern in
// `backend-catalog-toasting`).
const INDEX_CREATE_IS_PRIMARY: u16 = 1 << 0;
const INDEX_CREATE_ADD_CONSTRAINT: u16 = 1 << 1;
const INDEX_CREATE_SKIP_BUILD: u16 = 1 << 2;
const INDEX_CREATE_CONCURRENT: u16 = 1 << 3;
const INDEX_CREATE_IF_NOT_EXISTS: u16 = 1 << 4;
const INDEX_CREATE_PARTITIONED: u16 = 1 << 5;
const INDEX_CREATE_INVALID: u16 = 1 << 6;
const INDEX_CONSTR_CREATE_DEFERRABLE: u16 = 1 << 1;
const INDEX_CONSTR_CREATE_INIT_DEFERRED: u16 = 1 << 2;
const INDEX_CONSTR_CREATE_WITHOUT_OVERLAPS: u16 = 1 << 5;

// `commands/progress.h` — PROGRESS_CREATEIDX_* param indices and command kinds.
const PROGRESS_CREATEIDX_COMMAND: i32 = 0;
const PROGRESS_CREATEIDX_INDEX_OID: i32 = 6;
const PROGRESS_CREATEIDX_ACCESS_METHOD_OID: i32 = 8;
const PROGRESS_CREATEIDX_PARTITIONS_DONE: i32 = 14;
const PROGRESS_CREATEIDX_COMMAND_CREATE: i64 = 1;
const PROGRESS_CREATEIDX_COMMAND_CREATE_CONCURRENTLY: i64 = 2;

/// `SECURITY_RESTRICTED_OPERATION` (`miscadmin.h`).
const SECURITY_RESTRICTED_OPERATION: i32 = 1 << 1;

// ---------------------------------------------------------------------------
// small node-list helpers (NodePtr lists of String value nodes)
// ---------------------------------------------------------------------------

/// `strVal`-style read of a `Node::String`'s `sval`.
pub(crate) fn node_sval<'a>(node: &'a Node<'_>) -> &'a str {
    match node {
        Node::String(s) => s.sval.as_str(),
        _ => panic!("indexcmds: expected a String value node in a name list"),
    }
}

/// A list of `Node::String` (the C `List *` of `String` nodes) rendered as a
/// `NameList` (`&[Option<String>]`) for the namespace helpers.
pub(crate) fn name_list(names: &PgVec<'_, types_nodes::nodes::NodePtr<'_>>) -> Vec<Option<String>> {
    names
        .iter()
        .map(|n| Some(node_sval(n).to_string()))
        .collect()
}

/// The same list rendered as `Vec<String>` for `compatible_oper_opid`.
pub(crate) fn name_list_strings(
    names: &PgVec<'_, types_nodes::nodes::NodePtr<'_>>,
) -> Vec<String> {
    names.iter().map(|n| node_sval(n).to_string()).collect()
}

// ---------------------------------------------------------------------------
// CheckPredicate  (indexcmds.c:1842-1858)
// ---------------------------------------------------------------------------

/// `CheckPredicate(Expr *predicate)`.
///
/// `transformExpr()` already rejected subqueries / aggregates / window
/// functions; the only remaining check is that a predicate using mutable
/// functions is rejected.
pub fn CheckPredicate(mcx: Mcx<'_>, predicate: Expr) -> PgResult<()> {
    if contain_mutable_functions_after_planning(mcx, predicate)? {
        return Err(ereport(ERROR)
            .errcode(types_error::ERRCODE_INVALID_OBJECT_DEFINITION)
            .errmsg("functions in index predicate must be marked IMMUTABLE")
            .into_error());
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// DefineIndex  (indexcmds.c:542-1828) — the CREATE INDEX command driver.
// ---------------------------------------------------------------------------

/// `DefineIndex(tableId, stmt, indexRelationId, parentIndexId,
/// parentConstraintId, total_parts, is_alter_table, check_rights,
/// check_not_in_use, skip_build, quiet)`.
///
/// Ported for the non-concurrent, non-partitioned core (the high-value CREATE
/// INDEX command path). The CONCURRENTLY tail and the partitioned-table
/// recursion are precise seam-panics — see the module docs and
/// [`define_index_concurrent_tail`] / [`define_index_partition_recursion`].
///
/// Returns the [`ObjectAddress`] of the created index.
pub fn DefineIndex<'mcx>(
    mcx: Mcx<'mcx>,
    table_id: Oid,
    stmt: &IndexStmt<'mcx>,
    mut index_relation_id: Oid,
    parent_index_id: Oid,
    parent_constraint_id: Oid,
    _total_parts: i32,
    is_alter_table: bool,
    check_rights: bool,
    check_not_in_use: bool,
    skip_build: bool,
    quiet: bool,
) -> PgResult<ObjectAddress> {
    let mut root_save_nestlevel = NewGUCNestLevel();

    restrict_search_path::call()?;

    // Some callers need us to run with an empty default_tablespace; this is a
    // necessary hack to be able to reproduce catalog state accurately when
    // recreating indexes after table-rewriting ALTER TABLE.
    //
    // C: set_config_option("default_tablespace", "", PGC_USERSET, PGC_S_SESSION,
    //    GUC_ACTION_SAVE, true, 0, false). The repo seam is the `SetConfigOption`
    //    macro shape (no explicit GUC_ACTION_SAVE); the action defaults there.
    if stmt.reset_default_tblspc {
        set_config_option::call(
            "default_tablespace",
            "",
            types_guc::guc::GucContext::PGC_USERSET,
            types_guc::guc::GucSource::PGC_S_SESSION,
        )?;
    }

    // Force non-concurrent build on temporary relations.
    let concurrent =
        stmt.concurrent && lsyscache::get_rel_persistence::call(table_id)? != RELPERSISTENCE_TEMP;

    // Start progress report (skipped when building a partition).
    if !OidIsValid(parent_index_id) {
        pgstat_progress_start_command(ProgressCommandType::CreateIndex, table_id);
        pgstat_progress_update_param(
            PROGRESS_CREATEIDX_COMMAND,
            if concurrent {
                PROGRESS_CREATEIDX_COMMAND_CREATE_CONCURRENTLY
            } else {
                PROGRESS_CREATEIDX_COMMAND_CREATE
            },
        );
    }

    // No index OID to report yet.
    pgstat_progress_update_param(PROGRESS_CREATEIDX_INDEX_OID, InvalidOid as i64);

    // count key attributes in index
    let number_of_key_attributes = stmt.indexParams.len() as i32;

    // Build the combined list of (key + INCLUDE) index parameters, as IndexElems.
    let all_index_params: Vec<&IndexElem<'mcx>> = stmt
        .indexParams
        .iter()
        .chain(stmt.indexIncludingParams.iter())
        .map(|n| node_as_index_elem(n.as_ref()))
        .collect();
    let number_of_attributes = all_index_params.len() as i32;

    if number_of_key_attributes <= 0 {
        return Err(ereport(ERROR)
            .errcode(types_error::ERRCODE_INVALID_OBJECT_DEFINITION)
            .errmsg("must specify at least one column")
            .into_error());
    }
    if number_of_attributes > INDEX_MAX_KEYS {
        return Err(ereport(ERROR)
            .errcode(types_error::ERRCODE_TOO_MANY_COLUMNS)
            .errmsg(format!(
                "cannot use more than {INDEX_MAX_KEYS} columns in an index"
            ))
            .into_error());
    }

    // Take the table lock. ShareUpdateExclusiveLock for concurrent, ShareLock
    // otherwise.
    let lockmode: types_storage::lock::LOCKMODE = if concurrent {
        types_storage::lock::ShareUpdateExclusiveLock
    } else {
        types_storage::lock::ShareLock
    };
    let rel = table_seam::table_open::call(mcx, table_id, lockmode)?;

    // Switch to the table owner's userid + lock down security-restricted ops.
    let (root_save_userid, root_save_sec_context) = GetUserIdAndSecContext();
    SetUserIdAndSecContext(
        rel.rd_rel.relowner,
        root_save_sec_context | SECURITY_RESTRICTED_OPERATION,
    );

    let namespace_id = rel.rd_rel.relnamespace;

    // Exclusion behavior: EXCLUDE constraint or temporal PRIMARY KEY/UNIQUE.
    let exclusion = !stmt.excludeOpNames.is_empty() || stmt.iswithoutoverlaps;

    // Ensure it makes sense to index this kind of relation.
    match rel.rd_rel.relkind {
        x if x == RELKIND_RELATION || x == RELKIND_MATVIEW || x == RELKIND_PARTITIONED_TABLE => {}
        _ => {
            let name = rel.rd_rel.relname.as_str().to_string();
            return Err(ereport(ERROR)
                .errcode(types_error::ERRCODE_WRONG_OBJECT_TYPE)
                .errmsg(format!("cannot create index on relation \"{name}\""))
                .into_error());
        }
    }

    // Partitioned tables: we only create catalog entries; actual indexes are
    // built by recursing per partition.
    let partitioned = rel.rd_rel.relkind == RELKIND_PARTITIONED_TABLE;
    if partitioned && stmt.concurrent {
        let name = rel.rd_rel.relname.as_str().to_string();
        return Err(ereport(ERROR)
            .errcode(types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
            .errmsg(format!(
                "cannot create index on partitioned table \"{name}\" concurrently"
            ))
            .into_error());
    }

    // Unless the caller vouches for it, insist the table not be in use.
    if check_not_in_use {
        tablecmds_seam::check_table_not_in_use::call(&rel, "CREATE INDEX")?;
    }

    // Verify CREATE rights in the rel's namespace.
    if check_rights {
        let aclresult =
            aclchk_seam::object_aclcheck::call(NAMESPACE_RELATION_ID, namespace_id, root_save_userid, ACL_CREATE)?;
        if aclresult != ACLCHECK_OK {
            aclchk_seam::aclcheck_error::call(
                aclresult,
                OBJECT_SCHEMA,
                Some(namespacename_seam::get_namespace_name::call(namespace_id)?),
            )?;
        }
    }

    // Select tablespace.
    let mut tablespace_id: Oid;
    if let Some(ts) = stmt.tableSpace.as_ref() {
        tablespace_id = get_tablespace_oid(mcx, ts.as_str(), false)?;
        if partitioned && tablespace_id == my_database_tablespace()? {
            return Err(ereport(ERROR)
                .errcode(types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                .errmsg("cannot specify default tablespace for partitioned relations")
                .into_error());
        }
    } else {
        tablespace_id = GetDefaultTablespace(mcx, rel.rd_rel.relpersistence as i8, partitioned)?;
    }

    // Check tablespace permissions.
    if check_rights && OidIsValid(tablespace_id) && tablespace_id != my_database_tablespace()? {
        let aclresult = aclchk_seam::object_aclcheck::call(
            TABLESPACE_RELATION_ID,
            tablespace_id,
            root_save_userid,
            ACL_CREATE,
        )?;
        if aclresult != ACLCHECK_OK {
            let tsname = get_tablespace_name(mcx, tablespace_id)?.map(|s| s.as_str().to_string());
            aclchk_seam::aclcheck_error::call(aclresult, OBJECT_TABLESPACE, tsname)?;
        }
    }

    // Force shared indexes into pg_global; reject pg_global for non-shared.
    if rel.rd_rel.relisshared {
        tablespace_id = GLOBALTABLESPACE_OID;
    } else if tablespace_id == GLOBALTABLESPACE_OID {
        return Err(ereport(ERROR)
            .errcode(types_error::ERRCODE_INVALID_PARAMETER_VALUE)
            .errmsg("only shared relations can be placed in pg_global tablespace")
            .into_error());
    }

    // Choose the index column names.
    let index_col_names = ChooseIndexColumnNames(&all_index_params);

    // Select index name if caller didn't specify.
    let index_relation_name: String = match stmt.idxname.as_ref() {
        Some(n) => n.as_str().to_string(),
        None => ChooseIndexName(
            mcx,
            rel.rd_rel.relname.as_str(),
            namespace_id,
            &index_col_names,
            !stmt.excludeOpNames.is_empty(),
            stmt.primary,
            stmt.isconstraint,
        )?,
    };

    // Look up the access method; "rtree" -> "gist" hack.
    let mut access_method_name: String = stmt
        .accessMethod
        .as_ref()
        .map(|a| a.as_str().to_string())
        .expect("DefineIndex: IndexStmt has no accessMethod");
    let mut am_info = syscache::search_am_by_name::call(mcx, &access_method_name)?;
    if am_info.is_none() && access_method_name == "rtree" {
        ereport(types_error::NOTICE)
            .errmsg("substituting access method \"gist\" for obsolete method \"rtree\"")
            .finish(here("DefineIndex"))?;
        access_method_name = "gist".to_string();
        am_info = syscache::search_am_by_name::call(mcx, &access_method_name)?;
    }
    let am_info = match am_info {
        Some(a) => a,
        None => {
            return Err(ereport(ERROR)
                .errcode(types_error::ERRCODE_UNDEFINED_OBJECT)
                .errmsg(format!("access method \"{access_method_name}\" does not exist"))
                .into_error());
        }
    };
    let access_method_id = am_info.oid;
    let am_routine = GetIndexAmRoutineByAmId(access_method_id)?;

    pgstat_progress_update_param(PROGRESS_CREATEIDX_ACCESS_METHOD_OID, access_method_id as i64);

    if stmt.unique && !stmt.iswithoutoverlaps && !am_routine.amcanunique {
        return Err(amerr("does not support unique indexes", &access_method_name));
    }
    if !stmt.indexIncludingParams.is_empty() && !am_routine.amcaninclude {
        return Err(amerr("does not support included columns", &access_method_name));
    }
    if number_of_key_attributes > 1 && !am_routine.amcanmulticol {
        return Err(amerr("does not support multicolumn indexes", &access_method_name));
    }
    if exclusion && am_routine.amgettuple.is_none() {
        return Err(amerr("does not support exclusion constraints", &access_method_name));
    }
    if stmt.iswithoutoverlaps && access_method_name != "gist" {
        return Err(amerr("does not support WITHOUT OVERLAPS constraints", &access_method_name));
    }

    let amcanorder = am_routine.amcanorder;
    let amissummarizing = am_routine.amsummarizing;

    // Validate predicate, if given.
    if let Some(where_clause) = stmt.whereClause.as_ref() {
        let pred_expr = where_clause
            .as_ref()
            .as_expr()
            .expect("DefineIndex: whereClause is not an Expr")
            .clone();
        CheckPredicate(mcx, pred_expr)?;
    }

    // Parse AM-specific options, convert to text-array form, validate.
    //
    // C: reloptions = transformRelOptions((Datum) 0, stmt->options, NULL, NULL,
    //    false, false); (void) index_reloptions(amoptions, reloptions, true);
    //    where amoptions = accessMethodForm->amoptions.
    //
    // `transformRelOptions` yields a bare-word `types_datum::Datum` (a `text[]`
    // varlena pointer) but `index_reloptions` wants the varlena bytes and
    // `IndexCreateArgs.reloptions` is a `types_tuple::Datum` (ByRef-bytes lane).
    // There is no bridge between the two Datum lanes (the documented
    // Datum-redesign keystone), and `index_create` itself panics on a non-null
    // reloptions `types_tuple::Datum` for the same reason. So a CREATE INDEX
    // carrying a WITH (...) clause is deferred as a precise panic, not silently
    // dropped; the (overwhelmingly common) no-WITH path runs end-to-end.
    let reloptions: types_tuple::Datum<'mcx> = if stmt.options.is_empty() {
        types_tuple::Datum::null()
    } else {
        let _ = (access_method_id, mcx);
        panic!(
            "backend-commands-indexcmds: DefineIndex WITH (...) AM-specific index \
             reloptions are deferred — transformRelOptions yields a bare-word \
             types_datum::Datum with no bridge to the types_tuple::Datum \
             ByRef-bytes lane that index_reloptions / index_create consume \
             (Datum-redesign keystone; index_create panics on the same path)"
        );
    };

    // Prepare the IndexInfo. Predicates must be in implicit-AND format. In a
    // concurrent build, mark it not-ready-for-inserts.
    let predicate_list: Vec<Expr> = match stmt.whereClause.as_ref() {
        Some(wc) => make_ands_implicit(
            wc.as_ref().as_expr().map(|e| e.clone()),
        ),
        None => Vec::new(),
    };

    let mut index_info = make_index_info(
        number_of_attributes,
        number_of_key_attributes,
        access_method_id,
        (),
        (),
        stmt.unique,
        stmt.nulls_not_distinct,
        !concurrent,
        concurrent,
        amissummarizing,
        stmt.iswithoutoverlaps,
    );
    index_info.ii_Context = Some(mcx);
    if !predicate_list.is_empty() {
        let mut pv = PgVec::new_in(mcx);
        for e in predicate_list {
            pv.push(e);
        }
        index_info.ii_Predicate = Some(pv);
    }

    let mut type_ids = vec_oid(number_of_attributes);
    let mut collation_ids = vec_oid(number_of_attributes);
    let mut opclass_ids = vec_oid(number_of_attributes);
    let mut opclass_options: Vec<types_tuple::Datum<'mcx>> =
        (0..number_of_attributes).map(|_| types_tuple::Datum::null()).collect();
    let mut col_options = vec![0i16; number_of_attributes as usize];

    ComputeIndexAttrs(
        mcx,
        &mut index_info,
        &rel,
        &mut type_ids,
        &mut collation_ids,
        &mut opclass_ids,
        &mut opclass_options,
        &mut col_options,
        &all_index_params,
        if stmt.excludeOpNames.is_empty() {
            None
        } else {
            Some(&stmt.excludeOpNames)
        },
        table_id,
        &access_method_name,
        access_method_id,
        amcanorder,
        stmt.isconstraint,
        stmt.iswithoutoverlaps,
        root_save_userid,
        root_save_sec_context,
        &mut root_save_nestlevel,
    )?;

    // Extra checks when creating a PRIMARY KEY index.
    if stmt.primary {
        index_check_primary_key(mcx, &rel, &index_info, is_alter_table)?;
    }

    // Partitioned + (unique | exclusion): partition-key subset check.
    if partitioned && (stmt.unique || exclusion) {
        return Err(define_index_partition_keycheck_unsupported());
    }

    // Disallow indexes on system columns + virtual generated columns.
    for i in 0..index_info.ii_NumIndexAttrs as usize {
        let attno = index_info.ii_IndexAttrNumbers[i];
        if attno < 0 {
            return Err(ereport(ERROR)
                .errcode(types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                .errmsg("index creation on system columns is not supported")
                .into_error());
        }
        if attno > 0
            && rel.rd_att.attr((attno - 1) as usize).attgenerated == ATTRIBUTE_GENERATED_VIRTUAL
        {
            return Err(virtual_gencol_error(stmt));
        }
    }

    // Check for system and generated columns used in expressions / predicates.
    if index_info.ii_Expressions.is_some() || index_info.ii_Predicate.is_some() {
        let mut indexattrs: Option<mcx::PgBox<'mcx, types_nodes::Bitmapset<'mcx>>> = None;
        if let Some(exprs) = index_info.ii_Expressions.as_ref() {
            for e in exprs.iter() {
                indexattrs = bms_union_opt(mcx, indexattrs, var_seam::pull_varattnos::call(mcx, e, 1)?)?;
            }
        }
        if let Some(preds) = index_info.ii_Predicate.as_ref() {
            for e in preds.iter() {
                indexattrs = bms_union_opt(mcx, indexattrs, var_seam::pull_varattnos::call(mcx, e, 1)?)?;
            }
        }

        let attrs_ref = indexattrs.as_deref();
        let mut i = FirstLowInvalidHeapAttributeNumber as i32 + 1;
        while i < 0 {
            if bms_is_member(i - FirstLowInvalidHeapAttributeNumber as i32, attrs_ref) {
                return Err(ereport(ERROR)
                    .errcode(types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                    .errmsg("index creation on system columns is not supported")
                    .into_error());
            }
            i += 1;
        }

        let mut j = -1;
        loop {
            j = bms_next_member(attrs_ref, j);
            if j < 0 {
                break;
            }
            let attno = j + FirstLowInvalidHeapAttributeNumber as i32;
            if attno > 0
                && rel.rd_att.attr((attno - 1) as usize).attgenerated == ATTRIBUTE_GENERATED_VIRTUAL
            {
                return Err(virtual_gencol_error_expr(stmt));
            }
        }
    }

    // Is the index safe for others to ignore? (only relevant to concurrent.)
    let safe_index = index_info.ii_Expressions.is_none() && index_info.ii_Predicate.is_none();
    let _ = safe_index;

    // Report index creation (constraint case), as a DEBUG message — omitted
    // (DEBUG1 chatter; not observable behavior).
    let _ = quiet;

    // Make the catalog entries (and, unless skipped/concurrent/partitioned,
    // build the index).
    let mut flags: u16 = 0;
    let mut constr_flags: u16 = 0;
    if stmt.isconstraint {
        flags |= INDEX_CREATE_ADD_CONSTRAINT;
    }
    if skip_build || concurrent || partitioned {
        flags |= INDEX_CREATE_SKIP_BUILD;
    }
    if stmt.if_not_exists {
        flags |= INDEX_CREATE_IF_NOT_EXISTS;
    }
    if concurrent {
        flags |= INDEX_CREATE_CONCURRENT;
    }
    if partitioned {
        flags |= INDEX_CREATE_PARTITIONED;
    }
    if stmt.primary {
        flags |= INDEX_CREATE_IS_PRIMARY;
    }

    // If partitioned, recursion declined but partitions exist -> mark invalid.
    if partitioned && relation_inh_declined(stmt) && relation_has_partitions(&rel) {
        flags |= INDEX_CREATE_INVALID;
    }

    if stmt.deferrable {
        constr_flags |= INDEX_CONSTR_CREATE_DEFERRABLE;
    }
    if stmt.initdeferred {
        constr_flags |= INDEX_CONSTR_CREATE_INIT_DEFERRED;
    }
    if stmt.iswithoutoverlaps {
        constr_flags |= INDEX_CONSTR_CREATE_WITHOUT_OVERLAPS;
    }

    // Assemble IndexCreateArgs and call index_create. The per-column
    // opclassOptions cross as Some(vec) (one Datum per attribute).
    let col_names_owned: Vec<String> = index_col_names.clone();
    let collation_ids_v = collation_ids.clone();
    let opclass_ids_v = opclass_ids.clone();
    let coloptions_v = col_options.clone();

    let args = IndexCreateArgs {
        index_relation_name: index_relation_name.clone(),
        index_relation_id,
        parent_index_relid: parent_index_id,
        parent_constraint_id,
        rel_file_number: stmt.oldNumber,
        index_info,
        index_col_names: col_names_owned,
        access_method_id,
        table_space_id: tablespace_id,
        collation_ids: collation_ids_v,
        opclass_ids: opclass_ids_v,
        coloptions: coloptions_v,
        reloptions,
        opclass_options: Some(opclass_options),
        flags,
        constr_flags,
        allow_system_table_mods: allow_system_table_mods(),
        is_internal: !check_rights,
    };

    let (created_index_relation_id, created_constraint_id) = index_seam::index_create::call(&rel, args)?;
    index_relation_id = created_index_relation_id;
    let _ = created_constraint_id;

    let address = ObjectAddress {
        classId: RELATION_RELATION_ID,
        objectId: index_relation_id,
        objectSubId: 0,
    };

    if !OidIsValid(index_relation_id) {
        // IF NOT EXISTS hit an existing index: roll back GUC + userid, close.
        at_eoxact_guc(false, root_save_nestlevel);
        SetUserIdAndSecContext(root_save_userid, root_save_sec_context);
        owner_table_close(rel, types_storage::lock::NoLock)?;
        if !OidIsValid(parent_index_id) {
            pgstat_progress_end_command();
        }
        return Ok(address);
    }

    // Roll back GUC changes from index functions; keep subsequent changes local.
    at_eoxact_guc(false, root_save_nestlevel);
    root_save_nestlevel = NewGUCNestLevel();
    restrict_search_path::call()?;
    let _ = root_save_nestlevel;

    // Add any requested comment.
    if let Some(comment) = stmt.idxcomment.as_ref() {
        CreateComments(mcx, index_relation_id, RELATION_RELATION_ID, 0, Some(comment.as_str()))?;
    }

    // Partitioned-table recursion: build/attach child indexes. DEFERRED.
    if partitioned {
        if relation_should_recurse(stmt) && relation_has_partitions(&rel) {
            return Err(define_index_partition_recursion());
        }
        // No partitions / ONLY: indexes on partitioned tables aren't built.
        at_eoxact_guc(false, NewGUCNestLevel());
        SetUserIdAndSecContext(root_save_userid, root_save_sec_context);
        owner_table_close(rel, types_storage::lock::NoLock)?;
        if !OidIsValid(parent_index_id) {
            pgstat_progress_end_command();
        } else {
            pgstat_progress_incr_param(PROGRESS_CREATEIDX_PARTITIONS_DONE, 1);
        }
        return Ok(address);
    }

    SetUserIdAndSecContext(root_save_userid, root_save_sec_context);

    if !concurrent {
        // Non-concurrent: index_create already built it; close and we're done.
        owner_table_close(rel, types_storage::lock::NoLock)?;
        if !OidIsValid(parent_index_id) {
            pgstat_progress_end_command();
        } else {
            pgstat_progress_incr_param(PROGRESS_CREATEIDX_PARTITIONS_DONE, 1);
        }
        return Ok(address);
    }

    // CONCURRENTLY build/validate state machine. DEFERRED.
    owner_table_close(rel, types_storage::lock::NoLock)?;
    Err(define_index_concurrent_tail())
}

// ---------------------------------------------------------------------------
// ReindexIndex / ReindexTable  (precise seam-panics; substrate unported)
// ---------------------------------------------------------------------------

/// `ReindexIndex(...)` (indexcmds.c) — rebuild a single index. The
/// non-concurrent slice calls the `reindex_index` seam, which is declared but
/// owner-uninstalled (the reindex substrate is unported), so a call panics
/// loudly there. The concurrent slice is additionally deferred.
pub fn ReindexIndex() -> ! {
    panic!(
        "backend-commands-indexcmds: ReindexIndex (REINDEX INDEX driver) is deferred — its \
         reindex_index / cross-transaction concurrent substrate is unported"
    );
}

/// `ReindexTable(...)` (indexcmds.c) — rebuild every index on a table via
/// `reindex_relation`. The `reindex_relation` seam is declared but
/// owner-uninstalled; deferred.
pub fn ReindexTable() -> ! {
    panic!(
        "backend-commands-indexcmds: ReindexTable (REINDEX TABLE driver) is deferred — its \
         reindex_relation substrate is unported"
    );
}

// ---------------------------------------------------------------------------
// Deferred DefineIndex tails (precise panics)
// ---------------------------------------------------------------------------

fn define_index_concurrent_tail() -> backend_utils_error::PgError {
    panic!(
        "backend-commands-indexcmds: DefineIndex CREATE INDEX CONCURRENTLY tail is deferred — \
         the multi-transaction build/validate state machine (index_concurrently_build, \
         validate_index, WaitForLockers, WaitForOlderSnapshots, session-lock + snapshot dance) \
         is unported"
    );
}

fn define_index_partition_recursion() -> backend_utils_error::PgError {
    panic!(
        "backend-commands-indexcmds: DefineIndex partitioned-table recursion is deferred — \
         generateClonedIndexStmt / IndexSetParentIndex / BuildIndexInfo+CompareIndexInfo \
         child-index matching is unported"
    );
}

fn define_index_partition_keycheck_unsupported() -> backend_utils_error::PgError {
    panic!(
        "backend-commands-indexcmds: DefineIndex partition-key subset check (UNIQUE / PRIMARY \
         KEY / EXCLUDE on a partitioned table) is deferred — it needs RelationGetPartitionKey \
         + partition-opfamily matching, which is unported"
    );
}

// ---------------------------------------------------------------------------
// small helpers
// ---------------------------------------------------------------------------

fn vec_oid(n: i32) -> Vec<Oid> {
    vec![InvalidOid; n.max(0) as usize]
}

fn amerr(what: &str, amname: &str) -> backend_utils_error::PgError {
    ereport(ERROR)
        .errcode(types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
        .errmsg(format!("access method \"{amname}\" {what}"))
        .into_error()
}

fn virtual_gencol_error(stmt: &IndexStmt<'_>) -> backend_utils_error::PgError {
    let msg = if stmt.primary {
        "primary keys on virtual generated columns are not supported"
    } else if stmt.isconstraint {
        "unique constraints on virtual generated columns are not supported"
    } else {
        "indexes on virtual generated columns are not supported"
    };
    ereport(ERROR)
        .errcode(types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
        .errmsg(msg)
        .into_error()
}

fn virtual_gencol_error_expr(stmt: &IndexStmt<'_>) -> backend_utils_error::PgError {
    let msg = if stmt.isconstraint {
        "unique constraints on virtual generated columns are not supported"
    } else {
        "indexes on virtual generated columns are not supported"
    };
    ereport(ERROR)
        .errcode(types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
        .errmsg(msg)
        .into_error()
}

/// `bms_union` accumulation helper for the two `pull_varattnos` results, each an
/// `Option<PgBox<Bitmapset>>` (the C `Bitmapset *`, NULL == empty).
fn bms_union_opt<'mcx>(
    mcx: Mcx<'mcx>,
    a: Option<mcx::PgBox<'mcx, types_nodes::Bitmapset<'mcx>>>,
    b: Option<mcx::PgBox<'mcx, types_nodes::Bitmapset<'mcx>>>,
) -> PgResult<Option<mcx::PgBox<'mcx, types_nodes::Bitmapset<'mcx>>>> {
    match (a, b) {
        (None, x) => Ok(x),
        (x, None) => Ok(x),
        (Some(a), Some(b)) => Ok(bms_union(mcx, Some(&a), Some(&b))?),
    }
}

/// `MyDatabaseTableSpace` (globals.c) — the database's default tablespace OID.
fn my_database_tablespace() -> PgResult<Oid> {
    backend_commands_tablespace_globals_seams::MyDatabaseTableSpace::call()
}

/// `allowSystemTableMods` (globals.c).
fn allow_system_table_mods() -> bool {
    backend_utils_misc_guc_seams::allow_system_table_mods::call()
}

/// `stmt->relation && !stmt->relation->inh` (the recursion-declined-but-
/// partitions-exist invalidation predicate).
fn relation_inh_declined(stmt: &IndexStmt<'_>) -> bool {
    match index_stmt_relation(stmt) {
        Some(rv) => !rv.inh,
        None => false,
    }
}

/// `!stmt->relation || stmt->relation->inh` (recurse-into-partitions predicate).
fn relation_should_recurse(stmt: &IndexStmt<'_>) -> bool {
    match index_stmt_relation(stmt) {
        Some(rv) => rv.inh,
        None => true,
    }
}

fn index_stmt_relation<'a, 'mcx>(stmt: &'a IndexStmt<'mcx>) -> Option<&'a RangeVar<'mcx>> {
    stmt.relation.as_ref().and_then(|n| match n.as_ref() {
        Node::RangeVar(rv) => Some(rv),
        _ => None,
    })
}

/// `(IndexElem *) lfirst(...)` — read an `IndexElem` out of a name-list `Node`.
fn node_as_index_elem<'a, 'mcx>(node: &'a Node<'mcx>) -> &'a IndexElem<'mcx> {
    match node {
        Node::IndexElem(e) => e,
        _ => panic!("DefineIndex: indexParams entry is not an IndexElem"),
    }
}

/// `ErrorLocation` for `ereport(...).finish(...)` in this module.
fn here(funcname: &'static str) -> types_error::pg_error::ErrorLocation {
    types_error::pg_error::ErrorLocation::new("../src/backend/commands/indexcmds.c", 0, funcname)
}

/// `RelationGetPartitionDesc(rel, true)->nparts != 0`. The partition-descriptor
/// machinery is unported; reaching this for a non-partitioned table is a no-op
/// (returns false). For a partitioned table with the recursion paths above it
/// is gated by the partition-recursion deferral panic, so a precise panic here
/// keeps the "partitions exist?" probe honest.
fn relation_has_partitions(rel: &Relation<'_>) -> bool {
    if rel.rd_rel.relkind != RELKIND_PARTITIONED_TABLE {
        return false;
    }
    panic!(
        "backend-commands-indexcmds: RelationGetPartitionDesc (partition-descriptor probe) is \
         unported; CREATE INDEX on a partitioned table is deferred"
    );
}

/// Install this unit's outward seams.
pub fn init_seams() {
    // makeObjectName(name1, name2, label) — name2/label are non-null at the
    // pg_constraint call sites (ChooseConstraintName), matching the &str seam.
    backend_commands_indexcmds_seams::make_object_name::set(|name1, name2, label| {
        choosers::makeObjectName(name1, Some(name2), Some(label))
    });

    // GetOperatorFromCompareType(opclass, rhstype, cmptype) -> (op, strat).
    backend_commands_indexcmds_seams::get_operator_from_compare_type::set(
        |opclass, rhstype, cmptype| {
            let mut op = InvalidOid;
            let mut strat: u16 = 0;
            opclass::GetOperatorFromCompareType(opclass, rhstype, cmptype, &mut op, &mut strat)?;
            Ok((op, strat))
        },
    );
}
