[package]
name = "nodemergejoin"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
datum = { path = "../../../_support/types/datum" }
execexpr = { path = "../execexpr" }
exectuples = { path = "../exectuples" }
executils = { path = "../executils" }
init_small = { path = "../../utils/init/init_small" }
lsyscache = { path = "../../utils/cache/lsyscache" }
mcx = { path = "../../../_support/mcx" }
postgres_seams = { path = "../../tcop/postgres_seams" }
tuplesort = { path = "../../utils/sort/tuplesort" }
types_error = { path = "../../../_support/types/types_error" }
types_nbtree = { path = "../../../_support/types/types_nbtree" }
types_nodes = { path = "../../../_support/types/nodes" }
types_slot = { path = "../../../_support/types/types_slot" }
types_tuple = { path = "../../../_support/types/types_tuple" }

[dev-dependencies]
syscache_seams = { path = "../../utils/cache/syscache_seams" }
