[package]
name = "varlena"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
hashfn = { path = "../../../../common/hashfn" }
hyperloglog = { path = "../../../lib/hyperloglog" }
mcx = { path = "../../../../_support/mcx" }
datum = { path = "../../../../_support/types/datum" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
stringinfo = { path = "../../../../_support/types/stringinfo" }
pqformat = { path = "../../../libpq/pqformat" }
guc_tables = { path = "../../misc/guc_tables" }
mbutils = { path = "../../mb/mbutils" }
regex = { path = "../../../../_support/types/regex" }
regex_core_seams = { path = "../../../regex/regex_core_seams" }
regexp_seams = { path = "../regexp_seams" }
regexp_alt = { path = "../regexp_alt" }
postgres_seams = { path = "../../../tcop/postgres_seams" }
mbutils_seams = { path = "../../mb/mbutils_seams" }
pg_locale_seams = { path = "../pg_locale_seams" }
detoast_seams = { path = "../../../access/common/detoast_seams" }
detoast = { path = "../../../access/common/detoast" }
parser_small1 = { path = "../../../parser/parser_small1" }
wchar = { path = "../../../../common/wchar" }
unicode_norm = { path = "../../../../common/unicode_norm" }
unicode_category = { path = "../../../../common/unicode_category" }
lsyscache = { path = "../../cache/lsyscache" }
arrayfuncs = { path = "../arrayfuncs" }
fmgr_seams = { path = "../../fmgr/fmgr_seams" }
format_type = { path = "../format_type" }
numutils = { path = "../numutils" }
pg_bitutils = { path = "../../../../port/pg_bitutils" }
funcapi_srf = { path = "../../fmgr/funcapi_srf" }

[dev-dependencies]
syscache_seams = { path = "../../cache/syscache_seams" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
