[package]
name = "sql_functions_seams"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[dependencies]
seam_core = { path = "../../../_support/seam_core" }
datum = { path = "../../../_support/types/datum" }
mcx = { path = "../../../_support/mcx" }
types_error = { path = "../../../_support/types/types_error" }
types_portal = { path = "../../../_support/types/portal" }
types_slot = { path = "../../../_support/types/types_slot" }
types_tuple = { path = "../../../_support/types/types_tuple" }
