//! print.c debug printers. Formatting is byte-exact vs C (oracle fixtures in
//! cprint_expected.txt, regenerated by scripts/print-oracle-e2e.sh); the dump
//! source is outfuncs::nodeToStringWithLocations, as in C print.c:41/59/77
//! (real source-text locations, not -1).
use core::fmt::Write;

use mcx::{Mcx, PgString, PgVec};
use types_core::AttrNumber;
use types_error::{
    ErrorLevel, ErrorLocation, PgError, PgResult, ERRCODE_FEATURE_NOT_SUPPORTED,
    ERRCODE_INTERNAL_ERROR, LOG,
};
use types_nodes::parsenodes::{RTEKind, RangeTblEntry};
use types_nodes::primnodes::{INDEX_VAR, INNER_VAR, OUTER_VAR};
use types_nodes::{Node, NodeList, NodeTag};
use types_pathnodes::{NodeId, PathKey, PlannerInfo};
use types_slot::SlotData;

const LINELEN: usize = 78;
const INDENTSTOP: i32 = 3;
const MAXINDENT: i32 = 60;

// C emits the raw bytes; a wrap inside a multibyte character leaves a
// partial sequence on each side, rendered lossily here.
fn emit(out: &mut PgString<'_>, line: &[u8]) {
    push(out, &String::from_utf8_lossy(line));
    push(out, "\n");
}

fn push(out: &mut PgString<'_>, s: &str) {
    out.try_push_str(s).expect("print append");
}

pub fn format_node_dump<'mcx>(mcx: Mcx<'mcx>, dump: &str) -> PgResult<PgString<'mcx>> {
    let d = dump.as_bytes();
    let mut line = [0u8; LINELEN + 1];
    let mut out = PgString::new_in(mcx);
    let mut i = 0usize;
    let mut j;
    loop {
        j = 0;
        while j < LINELEN && i < d.len() {
            line[j] = d[i];
            i += 1;
            j += 1;
        }
        if i >= d.len() {
            break;
        }
        if d[i] == b' ' {
            i += 1;
        } else {
            let mut k = j as i32 - 1;
            while k > 0 && line[k as usize] != b' ' {
                k -= 1;
            }
            if k > 0 {
                i -= j - k as usize - 1;
                j = k as usize;
            }
        }
        emit(&mut out, &line[..j]);
    }
    if j > 0 {
        emit(&mut out, &line[..j]);
    }
    Ok(out)
}

pub fn pretty_format_node_dump<'mcx>(mcx: Mcx<'mcx>, dump: &str) -> PgResult<PgString<'mcx>> {
    let d = dump.as_bytes();
    let mut line = [0u8; LINELEN + 1];
    let mut out = PgString::new_in(mcx);
    let mut indent_lev: i32 = 0;
    let mut indent_dist: i32 = 0;
    let mut i = 0usize;
    let mut j: i32;
    loop {
        j = 0;
        while j < indent_dist {
            line[j as usize] = b' ';
            j += 1;
        }
        while j < LINELEN as i32 && i < d.len() {
            line[j as usize] = d[i];
            match line[j as usize] {
                b'}' => {
                    if j != indent_dist {
                        emit(&mut out, &line[..j as usize]);
                    }
                    line[indent_dist as usize] = b'}';
                    emit(&mut out, &line[..indent_dist as usize + 1]);
                    if indent_lev > 0 {
                        indent_lev -= 1;
                        indent_dist = (indent_lev * INDENTSTOP).min(MAXINDENT);
                    }
                    j = indent_dist - 1;
                    while i + 1 < d.len() && d[i + 1] == b' ' {
                        i += 1;
                    }
                }
                b')' => {
                    if i + 1 >= d.len() || d[i + 1] != b')' {
                        emit(&mut out, &line[..j as usize + 1]);
                        j = indent_dist - 1;
                        while i + 1 < d.len() && d[i + 1] == b' ' {
                            i += 1;
                        }
                    }
                }
                b'{' => {
                    if j != indent_dist {
                        emit(&mut out, &line[..j as usize]);
                    }
                    indent_lev += 1;
                    indent_dist = (indent_lev * INDENTSTOP).min(MAXINDENT);
                    j = 0;
                    while j < indent_dist {
                        line[j as usize] = b' ';
                        j += 1;
                    }
                    line[j as usize] = d[i];
                }
                b':' => {
                    if j != indent_dist {
                        emit(&mut out, &line[..j as usize]);
                    }
                    j = indent_dist;
                    line[j as usize] = d[i];
                }
                _ => {}
            }
            i += 1;
            j += 1;
        }
        if i >= d.len() {
            break;
        }
        emit(&mut out, &line[..j as usize]);
    }
    if j > 0 {
        emit(&mut out, &line[..j as usize]);
    }
    Ok(out)
}

pub fn print(mcx: Mcx<'_>, node: Node<'_>) -> PgResult<()> {
    let s = outfuncs::nodeToStringWithLocations(mcx, node)?;
    let f = format_node_dump(mcx, s.as_str())?;
    stdout_line(f.as_str());
    Ok(())
}

pub fn pprint(mcx: Mcx<'_>, node: Node<'_>) -> PgResult<()> {
    let s = outfuncs::nodeToStringWithLocations(mcx, node)?;
    let f = pretty_format_node_dump(mcx, s.as_str())?;
    stdout_line(f.as_str());
    Ok(())
}

fn stdout_line(s: &str) {
    use std::io::Write as _;
    let mut o = std::io::stdout();
    let _ = o.write_all(s.as_bytes());
    let _ = o.write_all(b"\n");
    let _ = o.flush();
}

pub fn elog_node_display(
    mcx: Mcx<'_>,
    lev: ErrorLevel,
    title: &str,
    node: Node<'_>,
    pretty: bool,
) -> PgResult<()> {
    let s = outfuncs::nodeToStringWithLocations(mcx, node)?;
    elog_node_dump_display(mcx, lev, title, s.as_str(), pretty)
}

// The debug_print_* arms of pg_rewrite_query / pg_plan_query (postgres.c:803,
// 870, 954, and plancache.c's calls into them):
// `elog_node_display(LOG, title, tree, Debug_pretty_print)`. `dump` is the
// nodeToStringWithLocations text (or its failure). C's outNode can dump every
// node; here a tree holding a node whose writer is not yet ported comes back
// as outfuncs' typed ERRCODE_FEATURE_NOT_SUPPORTED refusal, and a debug
// logging switch must not abort the statement over it: the refusal is logged
// in the DETAIL slot instead (still the C-shaped LOG + DETAIL pair, never a
// silently truncated tree). Any other failure (OOM, stack depth) propagates
// as it would from C.
pub fn debug_print_tree(
    mcx: Mcx<'_>,
    title: &str,
    dump: PgResult<PgString<'_>>,
    pretty: bool,
) -> PgResult<()> {
    match dump {
        Ok(s) => elog_node_dump_display(mcx, LOG, title, s.as_str(), pretty),
        Err(e) if e.sqlstate == ERRCODE_FEATURE_NOT_SUPPORTED => elog::ereport(LOG)
            .errmsg_internal(format!("{title}:"))
            .errdetail_internal(format!("{} (node dump not yet ported)", e.message))
            .finish(ErrorLocation::new("print.c", 88, "elog_node_display")),
        Err(e) => Err(e),
    }
}

// elog_node_display (print.c:70-89) over an already-serialized
// nodeToStringWithLocations dump: the debug_print_* sites in tcop and
// plancache hold the Query, the Query list and the PlannedStmt by value
// (no node handle), so they serialize through outfuncs' slice writers and
// format here.
pub fn elog_node_dump_display(
    mcx: Mcx<'_>,
    lev: ErrorLevel,
    title: &str,
    dump: &str,
    pretty: bool,
) -> PgResult<()> {
    let f = if pretty {
        pretty_format_node_dump(mcx, dump)?
    } else {
        format_node_dump(mcx, dump)?
    };
    elog::ereport(lev)
        .errmsg_internal(format!("{title}:"))
        .errdetail_internal(f.as_str().to_owned())
        .finish(ErrorLocation::new("print.c", 88, "elog_node_display"))
}

/// Arena byte buffer for the printf-style printers: C prints raw bytes
/// (output-function results need not be UTF-8 under every server encoding).
struct Buf<'mcx>(PgVec<'mcx, u8>);

impl<'mcx> Buf<'mcx> {
    fn new(mcx: Mcx<'mcx>) -> Self {
        Buf(PgVec::new_in(mcx))
    }
    fn push_bytes(&mut self, b: &[u8]) {
        mcx::vec_append_bytes(&mut self.0, b).expect("print append");
    }
}

impl Write for Buf<'_> {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        self.push_bytes(s.as_bytes());
        Ok(())
    }
}

pub fn print_rt(mcx: Mcx<'_>, rtable: &NodeList<'_>) {
    let mut buf = Buf::new(mcx);
    write_rt(&mut buf, rtable);
    stdout_flush(&buf.0);
}

fn write_rt(buf: &mut Buf<'_>, rtable: &NodeList<'_>) {
    let _ = writeln!(buf, "resno\trefname  \trelid\tinFromCl");
    let _ = writeln!(buf, "-----\t---------\t-----\t--------");
    for (idx, rte_node) in rtable.iter().enumerate() {
        let i = idx + 1;
        let rte = rte_node.as_range_tbl_entry().expect("rtable element");
        let aliasname = rte.eref.and_then(|e| e.aliasname).unwrap_or("");
        let _ = match rte.rtekind {
            RTEKind::RTE_RELATION => {
                write!(buf, "{i}\t{aliasname}\t{}\t{}", rte.relid, rte.relkind as char)
            }
            RTEKind::RTE_SUBQUERY => write!(buf, "{i}\t{aliasname}\t[subquery]"),
            RTEKind::RTE_JOIN => write!(buf, "{i}\t{aliasname}\t[join]"),
            RTEKind::RTE_FUNCTION => write!(buf, "{i}\t{aliasname}\t[rangefunction]"),
            RTEKind::RTE_TABLEFUNC => write!(buf, "{i}\t{aliasname}\t[table function]"),
            RTEKind::RTE_VALUES => write!(buf, "{i}\t{aliasname}\t[values list]"),
            RTEKind::RTE_CTE => write!(buf, "{i}\t{aliasname}\t[cte]"),
            RTEKind::RTE_NAMEDTUPLESTORE => write!(buf, "{i}\t{aliasname}\t[tuplestore]"),
            RTEKind::RTE_RESULT => write!(buf, "{i}\t{aliasname}\t[result]"),
            RTEKind::RTE_GROUP => write!(buf, "{i}\t{aliasname}\t[group]"),
        };
        let _ = writeln!(
            buf,
            "\t{}\t{}",
            if rte.inh { "inh" } else { "" },
            if rte.inFromCl { "inFromCl" } else { "" }
        );
    }
}

fn stdout_flush(s: &[u8]) {
    use std::io::Write as _;
    let mut o = std::io::stdout();
    let _ = o.write_all(s);
    let _ = o.flush();
}

// parse_relation.c get_rte_attribute_name (print_expr's only consumer here);
// its out-of-range attnum is elog(ERROR, "invalid attnum %d for rangetable
// entry %s") — a catchable XX000.
fn rte_attribute_name<'mcx>(
    mcx: Mcx<'mcx>,
    rte: &RangeTblEntry<'mcx>,
    attnum: AttrNumber,
) -> PgResult<PgString<'mcx>> {
    if attnum == 0 {
        return PgString::from_str_in("*", mcx);
    }
    let colname = |alias: &types_nodes::primnodes::Alias<'mcx>| -> Option<&'mcx str> {
        if attnum > 0 && (attnum as usize) <= alias.colnames.len() {
            alias.colnames.nth(attnum as usize - 1).as_string().map(|s| s.sval)
        } else {
            None
        }
    };
    if let Some(name) = rte.alias.and_then(colname) {
        return PgString::from_str_in(name, mcx);
    }
    if rte.rtekind == RTEKind::RTE_RELATION {
        return Ok(lsyscache::get_attname(mcx, rte.relid, attnum, false)?
            .expect("get_attname missing_ok=false"));
    }
    if let Some(name) = rte.eref.and_then(colname) {
        return PgString::from_str_in(name, mcx);
    }
    Err(Box::new(
        PgError::error(format!(
            "invalid attnum {attnum} for rangetable entry {}",
            rte.eref.and_then(|e| e.aliasname).unwrap_or("")
        ))
        .with_sqlstate(ERRCODE_INTERNAL_ERROR),
    ))
}

// C OidOutputFunctionCall + printf("%s"): the raw output bytes, whatever the
// server encoding.
fn output_function_call<'mcx>(
    mcx: Mcx<'mcx>,
    typoutput: types_core::Oid,
    value: datum::Datum,
) -> PgResult<PgVec<'mcx, u8>> {
    let mut finfo = fmgr_seams::fmgr_info::call(typoutput)?;
    let d = types_fmgr::function_call1_coll_in(&mut finfo, types_core::InvalidOid, mcx, value)?;
    // SAFETY: out functions return a NUL-terminated cstring datum; copied out
    // before finfo (and its scratch) dies.
    let s = unsafe { core::ffi::CStr::from_ptr(d.as_usize() as *const core::ffi::c_char) };
    let mut out = PgVec::new_in(mcx);
    mcx::vec_append_bytes(&mut out, s.to_bytes())?;
    Ok(out)
}

pub fn print_expr(mcx: Mcx<'_>, expr: Option<Node<'_>>, rtable: &NodeList<'_>) -> PgResult<()> {
    let mut buf = Buf::new(mcx);
    write_expr(&mut buf, mcx, expr, rtable)?;
    stdout_flush(&buf.0);
    Ok(())
}

fn write_expr(
    buf: &mut Buf<'_>,
    mcx: Mcx<'_>,
    expr: Option<Node<'_>>,
    rtable: &NodeList<'_>,
) -> PgResult<()> {
    let Some(expr) = expr else {
        buf.push_bytes(b"<>");
        return Ok(());
    };
    match expr.node_tag() {
        NodeTag::T_Var => {
            let var = expr.as_var().unwrap();
            match var.varno {
                INNER_VAR => buf.push_bytes(b"INNER.?"),
                OUTER_VAR => buf.push_bytes(b"OUTER.?"),
                INDEX_VAR => buf.push_bytes(b"INDEX.?"),
                _ => {
                    debug_assert!(var.varno > 0 && var.varno as usize <= rtable.len());
                    let rte = rtable
                        .nth(var.varno as usize - 1)
                        .as_range_tbl_entry()
                        .expect("rtable element");
                    let relname = rte.eref.and_then(|e| e.aliasname).unwrap_or("");
                    let attname = rte_attribute_name(mcx, rte, var.varattno)?;
                    let _ = write!(buf, "{relname}.{}", attname.as_str());
                }
            }
        }
        NodeTag::T_Const => {
            let c = expr.as_const().unwrap();
            if c.constisnull {
                buf.push_bytes(b"NULL");
                return Ok(());
            }
            let (typoutput, _) = lsyscache::getTypeOutputInfo(c.consttype)?;
            let s = output_function_call(mcx, typoutput, c.constvalue)?;
            buf.push_bytes(&s);
        }
        NodeTag::T_OpExpr => {
            let e = expr.as_op_expr().unwrap();
            let opname = lsyscache::operator::get_opname(mcx, e.opno)?;
            let opname = opname.as_ref().map(|s| s.as_str()).unwrap_or("(invalid operator)");
            if e.args.len() > 1 {
                write_expr(buf, mcx, Some(e.args.nth(0)), rtable)?;
                let _ = write!(buf, " {opname} ");
                write_expr(buf, mcx, Some(e.args.nth(1)), rtable)?;
            } else {
                let _ = write!(buf, "{opname} ");
                write_expr(buf, mcx, Some(e.args.nth(0)), rtable)?;
            }
        }
        NodeTag::T_FuncExpr => {
            let e = expr.as_func_expr().unwrap();
            let funcname = lsyscache::get_func_name(mcx, e.funcid)?;
            let funcname = funcname.as_ref().map(|s| s.as_str()).unwrap_or("(invalid function)");
            let _ = write!(buf, "{funcname}(");
            for (i, arg) in e.args.iter().enumerate() {
                write_expr(buf, mcx, Some(arg), rtable)?;
                if i + 1 < e.args.len() {
                    buf.push_bytes(b",");
                }
            }
            buf.push_bytes(b")");
        }
        _ => buf.push_bytes(b"unknown expr"),
    }
    Ok(())
}

pub fn print_tl(mcx: Mcx<'_>, tlist: &NodeList<'_>, rtable: &NodeList<'_>) -> PgResult<()> {
    let mut buf = Buf::new(mcx);
    buf.push_bytes(b"(\n");
    for tl in tlist {
        let tle = tl.as_target_entry().expect("tlist element");
        let _ = write!(buf, "\t{} {}\t", tle.resno, tle.resname.unwrap_or("<null>"));
        if tle.ressortgroupref != 0 {
            let _ = write!(buf, "({}):\t", tle.ressortgroupref);
        } else {
            buf.push_bytes(b"    :\t");
        }
        write_expr(&mut buf, mcx, Some(tle.expr), rtable)?;
        buf.push_bytes(b"\n");
    }
    buf.push_bytes(b")\n");
    stdout_flush(&buf.0);
    Ok(())
}

// print_pathkeys (print.c:430-465): "(" then, per PathKey, "(" the
// canonical EquivalenceClass's members through print_expr joined by ", "
// ")" — pathkeys joined by ", " — then ")\n". PathKeys and their
// EquivalenceClasses/Members are PlannerInfo arena records here, so the
// root that owns them is the extra argument (C reaches them by pointer).
pub fn print_pathkeys(
    mcx: Mcx<'_>,
    root: &PlannerInfo<'_>,
    pathkeys: &[PathKey],
    rtable: &NodeList<'_>,
) -> PgResult<()> {
    let text = format_pathkeys(mcx, root, pathkeys, rtable)?;
    stdout_flush(&text);
    Ok(())
}

pub(crate) fn format_pathkeys<'mcx>(
    mcx: Mcx<'mcx>,
    root: &PlannerInfo<'_>,
    pathkeys: &[PathKey],
    rtable: &NodeList<'_>,
) -> PgResult<PgVec<'mcx, u8>> {
    let mut buf = Buf::new(mcx);
    write_pathkeys(&mut buf, mcx, root, pathkeys, rtable)?;
    Ok(buf.0)
}

fn write_pathkeys(
    buf: &mut Buf<'_>,
    mcx: Mcx<'_>,
    root: &PlannerInfo<'_>,
    pathkeys: &[PathKey],
    rtable: &NodeList<'_>,
) -> PgResult<()> {
    buf.push_bytes(b"(");
    for (i, pathkey) in pathkeys.iter().enumerate() {
        // C dereferences pk_eclass unconditionally (a NULL is a backend
        // crash there); every PathKey the planner builds carries one.
        let eclass = pathkey.pk_eclass.expect("PathKey without an EquivalenceClass");
        // chase up, in case pathkey is non-canonical
        let eclass = root.ec_canonical(eclass);
        buf.push_bytes(b"(");
        for (k, em) in root.ec(eclass).ec_members.iter().enumerate() {
            if k > 0 {
                buf.push_bytes(b", ");
            }
            write_expr(buf, mcx, arena_expr(root, root.em(*em).em_expr), rtable)?;
        }
        buf.push_bytes(b")");
        if i + 1 < pathkeys.len() {
            buf.push_bytes(b", ");
        }
    }
    buf.push_bytes(b")\n");
    Ok(())
}

// A planner expression handle: NodeId(0) is the NULL pointer (print_expr
// then writes "<>", as C does for a NULL Expr).
fn arena_expr<'mcx>(root: &PlannerInfo<'mcx>, id: NodeId) -> Option<Node<'mcx>> {
    if id == NodeId::default() {
        None
    } else {
        Some(*root.expr_node(id))
    }
}

// print_slot (print.c:496-511): TupIsNull (a NULL slot or an empty one) and
// a slot without a descriptor print a fixed line; otherwise the tuple goes
// through debugtup (printtup.c:462), the interactive-backend row printer.
pub fn print_slot(slot: Option<&mut SlotData<'_>>) -> PgResult<()> {
    let Some(slot) = slot else {
        stdout_flush(b"tuple is null.\n");
        return Ok(());
    };
    if let Some(line) = slot_preamble(slot) {
        stdout_flush(line.as_bytes());
        return Ok(());
    }
    printtup::debugtup::DrDebugtup::new().receive_slot(slot)?;
    Ok(())
}

// The two early returns of print_slot for a non-NULL slot, in C order.
pub(crate) fn slot_preamble(slot: &SlotData<'_>) -> Option<&'static str> {
    let base = slot.base();
    if base.is_empty() {
        return Some("tuple is null.\n");
    }
    if base.tts_tupleDescriptor.is_none() {
        return Some("no tuple descriptor.\n");
    }
    None
}
