[package]
name = "passwordcheck"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "passwordcheck"
path = "src/lib.rs"

[dependencies]
datum = { path = "../../_support/types/datum" }
mcx = { path = "../../_support/mcx" }
types_error = { path = "../../_support/types/types_error" }
types_fmgr = { path = "../../_support/types/fmgr" }
types_guc = { path = "../../_support/types/types_guc" }
dfmgr = { path = "../../backend/utils/fmgr/dfmgr" }
guc = { path = "../../backend/utils/misc/guc" }
crypt = { path = "../../backend/libpq/crypt" }
user = { path = "../../backend/commands/user" }
