[package]
name = "ri_triggers"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../../_support/mcx" }
datum = { path = "../../../../_support/types/datum" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_rel = { path = "../../../../_support/types/rel" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
types_trigger = { path = "../../../../_support/types/types_trigger" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
types_snapshot = { path = "../../../../_support/types/snapshot" }
ri_triggers_seams = { path = "../ri_triggers_seams" }
fmgr_seams = { path = "../../fmgr/fmgr_seams" }
lsyscache = { path = "../../cache/lsyscache" }
pg_constraint = { path = "../../../catalog/pg_constraint" }
cache_syscache = { path = "../../cache/cache_syscache" }
coerce = { path = "../../../parser/coerce" }
format_type = { path = "../format_type" }
syscache_seams = { path = "../../cache/syscache_seams" }
table = { path = "../../../access/table/table" }
heapam = { path = "../../../access/heap/heapam" }
xact = { path = "../../../access/transam/xact" }
xact_seams = { path = "../../../access/transam/xact_seams" }
spi = { path = "../../../executor/spi" }
miscinit = { path = "../../init/miscinit" }
superuser = { path = "../../misc/superuser" }
guc = { path = "../../misc/guc" }
types_guc = { path = "../../../../_support/types/types_guc" }
snapmgr = { path = "../../time/snapmgr" }
init_small = { path = "../../init/init_small" }
varlena = { path = "../varlena" }
ruleutils = { path = "../ruleutils" }
rls_seams = { path = "../../misc/rls_seams" }
aclchk_seams = { path = "../../../catalog/aclchk_seams" }
types_nodes = { path = "../../../../_support/types/nodes" }
