//! The central, generated leaf-node tree (`nodes/nodes.h` `Node` over the
//! CONVERTED leaf node families), the idiomatic-Rust analogue of the *central*
//! artifacts that `src/backend/nodes/gen_node_support.pl` emits.
//!
//! This module is intentionally THIN: the actual `pub enum Node<'mcx>`, its
//! `node_tag()` accessor, and the `copy_node_in` / `equal_node` dispatch are
//! code-generated by `types-nodes/build.rs` from `nodetags.h` + `nodes.list`
//! (variant order = nodetags.h numeric-tag/ABI order). The generated file is
//! `include!`d below; growing the enum is purely appending lines to
//! `nodes.list`.
//!
//! It is DISTINCT from the plan-node dispatch enum in [`crate::nodes`]
//! (`Plan *`): that hand-written enum carries the executor plan nodes, while
//! this generated one carries the leaf literal/structural nodes
//! (Value/`Bitmapset`/`List`). Both reconcile on the same numeric
//! [`crate::nodes::NodeTag`] tag value (`node_tag()` returns it).
//!
//! Per-struct copy/equal lives on the struct itself (via `#[derive(PgNode)]`
//! for the Value nodes, or hand-written `PgNodeCopy`/`PgNodeEqual` for the
//! special-cased `List`/`Bitmapset`); this module only assembles the central
//! tag-discriminated dispatch over them.
//!
//! # Scalar-leaf opt-ins
//!
//! Node-local value-leaf field types that are not the Rust primitives / `mcx`
//! containers already covered by `backend-nodes-node-support` opt into
//! `PgNodeCopy`/`PgNodeEqual` here via [`backend_nodes_node_support::pg_scalar_eq!`]
//! (a flat `Clone` copy + `==` equality — the analogue of
//! `COPY_SCALAR_FIELD`/`COMPARE_SCALAR_FIELD`). The `NodeTag` newtype is opted in
//! so any future generated node carrying a `NodeTag` data field copies/compares
//! it as a scalar.

// `NodeTag` is `Clone + PartialEq` and lifetime-free: a node-local scalar leaf.
backend_nodes_node_support::pg_scalar_eq!(crate::nodes::NodeTag);

include!(concat!(env!("OUT_DIR"), "/node_tree.rs"));
