//! The central, generated leaf-node tree (`nodes/nodes.h` `Node` over the
//! CONVERTED leaf node families), the idiomatic-Rust analogue of the *central*
//! artifacts that `src/backend/nodes/gen_node_support.pl` emits.
//!
//! This module is intentionally THIN: the actual `pub enum Node<'mcx>`, its
//! `node_tag()` accessor, and the `copy_node_in` / `equal_node` dispatch are
//! code-generated by `types-nodes/build.rs` from `nodetags.h` + `nodes.list`
//! (variant order = nodetags.h numeric-tag/ABI order). The generated file is
//! `include!`d below; growing the enum is purely appending lines to
//! `nodes.list`.
//!
//! It is DISTINCT from the plan-node dispatch enum in [`crate::nodes`]
//! (`Plan *`): that hand-written enum carries the executor plan nodes, while
//! this generated one carries the leaf literal/structural nodes
//! (Value/`Bitmapset`/`List`). Both reconcile on the same numeric
//! [`crate::nodes::NodeTag`] tag value (`node_tag()` returns it).
//!
//! Per-struct copy/equal lives on the struct itself (via `#[derive(PgNode)]`
//! for the Value nodes, or hand-written `PgNodeCopy`/`PgNodeEqual` for the
//! special-cased `List`/`Bitmapset`); this module only assembles the central
//! tag-discriminated dispatch over them.
//!
//! # Scalar-leaf opt-ins
//!
//! Node-local value-leaf field types that are not the Rust primitives / `mcx`
//! containers already covered by `backend-nodes-node-support` opt into
//! `PgNodeCopy`/`PgNodeEqual` here via [`backend_nodes_node_support::pg_scalar_eq!`]
//! (a flat `Clone` copy + `==` equality — the analogue of
//! `COPY_SCALAR_FIELD`/`COMPARE_SCALAR_FIELD`). The `NodeTag` newtype is opted in
//! so any future generated node carrying a `NodeTag` data field copies/compares
//! it as a scalar.

// `NodeTag` is `Clone + PartialEq` and lifetime-free: a node-local scalar leaf.
backend_nodes_node_support::pg_scalar_eq!(crate::nodes::NodeTag);

include!(concat!(env!("OUT_DIR"), "/node_tree.rs"));

#[cfg(test)]
mod out_read_derive_tests {
    //! Proves the `#[derive(PgNode)] #[pg_node(out_read)]` framed OUT/READ emit
    //! (and the `pg_scalar_enum_out_read!` leaf macro) produce valid, round-
    //! tripping code in the charged/fallible model. These exercise the
    //! serialization-stage machinery end-to-end without depending on any node
    //! family opting into the stage on `main` (the converted leaves are all
    //! `special_read_write`/custom for now).
    use alloc::string::String;
    use backend_nodes_macros::PgNode;
    use backend_nodes_node_support::{PgNodeOut, PgNodeRead, ReadCursor};
    use mcx::{MemoryContext, PgString};

    // A node enum field type: serialized as `(int)` via WRITE_ENUM_FIELD.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(i32)]
    enum Color {
        Red = 0,
        Green = 1,
        Blue = 7,
    }
    backend_nodes_node_support::pg_scalar_eq!(Color);
    // A real Rust `enum` rebuilds from the discriminant via the table form (the
    // `as`-cast form `pg_scalar_enum_out_read!` is for integer ALIASES only).
    backend_nodes_node_support::pg_node_enum_out_read!(
        Color { Color::Red => 0, Color::Green => 1, Color::Blue => 7 }
    );

    // A framed node opting into the OUT/READ stage with scalar + string + enum +
    // location fields, mirroring a typical generated `_outFoo`/`_readFoo`.
    #[derive(Debug, PgNode)]
    #[pg_node(out_read)]
    struct Demo<'mcx> {
        n: i32,
        flag: bool,
        name: PgString<'mcx>,
        color: Color,
        #[pg_node(location)]
        location: i32,
    }

    #[test]
    fn framed_out_read_round_trips() {
        let ctx = MemoryContext::new("demo");
        let mcx = ctx.mcx();
        let d = Demo {
            n: -42,
            flag: true,
            name: PgString::from_str_in("hi there", mcx).unwrap(),
            color: Color::Blue,
            location: 99,
        };
        let mut buf = String::new();
        d.out_node(&mut buf);
        // Byte-exact framing: `{DEMO :n -42 :flag true :name hi\ there :color 7
        // :location -1}` — the LABEL is the struct name uppercased; a location
        // field always writes the literal -1 (write_location_fields == false).
        assert_eq!(buf, "{DEMO :n -42 :flag true :name hi\\ there :color 7 :location -1}");

        let mut cur = ReadCursor::new(&buf);
        let back = Demo::read_node(&mut cur, mcx).unwrap();
        assert_eq!(back.n, -42);
        assert!(back.flag);
        assert_eq!(back.name.as_str(), "hi there");
        assert_eq!(back.color, Color::Blue);
        // READ_LOCATION_FIELD reconstructs -1 (the OUT side wrote -1).
        assert_eq!(back.location, -1);
    }
}
