//! Value nodes (`nodes/value.h`) — the leaf literal nodes
//! `Integer`/`Float`/`Boolean`/`String`/`BitString`.
//!
//! These represent literals in the lexer and carry constants through the
//! parser. The one thing that distinguishes them from a plain `int` / `char *`
//! is that they are `Node`s, so they can live in a `List` and flow through the
//! generic `Node *` machinery (`copyObject` / `equal`).
//!
//! ```c
//! typedef struct Integer   { NodeTag type; int   ival;   } Integer;
//! typedef struct Float     { NodeTag type; char *fval;   } Float;   // numeric-as-string
//! typedef struct Boolean   { NodeTag type; bool  boolval;} Boolean;
//! typedef struct String    { NodeTag type; char *sval;   } String;
//! typedef struct BitString { NodeTag type; char *bsval;  } BitString;
//! ```
//!
//! ## Owned model
//!
//! C's `NodeTag type` first field is the enum discriminant in the owned model
//! (the central [`crate::node_tree::Node`] enum), so it is dropped from the
//! struct bodies. The `char *` payloads (`fval`/`sval`/`bsval`) are
//! context-allocated strings, so they become [`PgString`] re-homed onto `mcx`
//! (the `T_Float` value is deliberately kept as a string — see `value.h`: an
//! integer literal too large for an `int` lexes as `T_Float`, and the value may
//! become `NUMERIC`, so it must not be stored as a C `double`).
//!
//! Copy is the fallible owned-tree analogue of `copyObject` (allocates the copy
//! into a TARGET context); equality is the analogue of `equal()`. Both are
//! generated by `#[derive(PgNode)]` (the value nodes have no field-level
//! `pg_node_attr` in C beyond `special_read_write`, which only affects the
//! deferred OUT/READ stage — copy/equal copy/compare every field).

use mcx::PgString;

use backend_nodes_macros::PgNode;

/// `typedef struct Integer` (`nodes/value.h`). A small integer literal. Lifetime-
/// free (its sole payload is a flat `i32`), so `copy_node_in` clones into any
/// context and `equal_node` is field-wise `==`.
#[derive(Debug, Clone, PartialEq, Eq, PgNode)]
pub struct Integer {
    /// `int ival`.
    pub ival: i32,
}

/// `typedef struct Float` (`nodes/value.h`). A numeric literal kept as its
/// source string (`char *fval`): the value can be too large for `int` or end up
/// `NUMERIC`, so it is never stored as a C `double`. The string is
/// context-allocated, so the node carries the allocator lifetime.
#[derive(Debug, PgNode)]
pub struct Float<'mcx> {
    /// `char *fval` — the numeric literal text. `COPY_STRING_FIELD`: deep-copied
    /// into the target context; compared by contents.
    pub fval: PgString<'mcx>,
}

/// `typedef struct Boolean` (`nodes/value.h`). A boolean literal. Lifetime-free
/// (its sole payload is a flat `bool`).
#[derive(Debug, Clone, PartialEq, Eq, PgNode)]
pub struct Boolean {
    /// `bool boolval`.
    pub boolval: bool,
}

/// `typedef struct String` (`nodes/value.h`) — named `StringNode` so it does not
/// collide with Rust's `String`. A string literal / identifier; the payload is a
/// context-allocated string, so the node carries the allocator lifetime.
#[derive(Debug, PgNode)]
pub struct StringNode<'mcx> {
    /// `char *sval` — the string contents. `COPY_STRING_FIELD`.
    pub sval: PgString<'mcx>,
}

/// `typedef struct BitString` (`nodes/value.h`). A bit-string literal kept as its
/// source string (`char *bsval`); context-allocated, carries the allocator
/// lifetime.
#[derive(Debug, PgNode)]
pub struct BitString<'mcx> {
    /// `char *bsval` — the bit-string text. `COPY_STRING_FIELD`.
    pub bsval: PgString<'mcx>,
}
