[package]
name = "hash"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
vacuum_seams = { path = "../../../commands/vacuum_seams" }
types_nbtree = { path = "../../../../_support/types/types_nbtree" }
postgres_seams = { path = "../../../tcop/postgres_seams" }
mcx = { path = "../../../../_support/mcx" }
datum = { path = "../../../../_support/types/datum" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_scan = { path = "../../../../_support/types/types_scan" }
types_hash = { path = "../../../../_support/types/hash" }
types_rel = { path = "../../../../_support/types/rel" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
types_storage = { path = "../../../../_support/types/types_storage" }
types_snapshot = { path = "../../../../_support/types/snapshot" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
types_relscan = { path = "../../index/relscan" }
fmgr_core = { path = "../../../utils/fmgr/fmgr_core" }
lsyscache = { path = "../../../utils/cache/lsyscache" }
hashfn = { path = "../../../../common/hashfn" }
nbtree = { path = "../../nbtree/nbtree" }
bufmgr_seams = { path = "../../../storage/buffer/bufmgr_seams" }
predicate_seams = { path = "../../../storage/lmgr/predicate_seams" }
transam_xlog_seams = { path = "../../transam/transam_xlog_seams" }
xact = { path = "../../transam/xact" }
tidbitmap = { path = "../../../nodes/tidbitmap" }
init_small = { path = "../../../utils/init/init_small" }
xloginsert = { path = "../../transam/xloginsert" }
xloginsert_seams = { path = "../../transam/xloginsert_seams" }
smgr = { path = "../../../storage/smgr/smgr" }
bufmgr = { path = "../../../storage/buffer/bufmgr" }
