[package]
name = "pg_visibility"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "pg_visibility"
path = "src/lib.rs"

[dependencies]
datum = { path = "../../_support/types/datum" }
mcx = { path = "../../_support/mcx" }
types_core = { path = "../../_support/types/types_core" }
types_error = { path = "../../_support/types/types_error" }
types_fmgr = { path = "../../_support/types/fmgr" }
types_rel = { path = "../../_support/types/rel" }
types_snapshot = { path = "../../_support/types/snapshot" }
types_storage = { path = "../../_support/types/types_storage" }
types_tuple = { path = "../../_support/types/types_tuple" }
dfmgr = { path = "../../backend/utils/fmgr/dfmgr" }
funcapi = { path = "../../backend/utils/fmgr/funcapi" }
heaptuple = { path = "../../backend/access/common/heaptuple" }
relation = { path = "../../backend/access/common/relation" }
bufmgr = { path = "../../backend/storage/buffer/bufmgr" }
bufmgr_seams = { path = "../../backend/storage/buffer/bufmgr_seams" }
heapam = { path = "../../backend/access/heap/heapam" }
heapam_visibility = { path = "../../backend/access/heap/heapam_visibility" }
visibilitymap = { path = "../../backend/access/heap/visibilitymap" }
procarray = { path = "../../backend/storage/ipc/procarray" }
lwlock = { path = "../../backend/storage/lmgr/lwlock" }
lmgr_proc = { path = "../../backend/storage/lmgr/lmgr_proc" }
smgr = { path = "../../backend/storage/smgr/smgr" }
storage_xlog = { path = "../../backend/catalog/storage_xlog" }
xloginsert_seams = { path = "../../backend/access/transam/xloginsert_seams" }
transam_xlog = { path = "../../backend/access/transam/transam_xlog" }
varsup = { path = "../../backend/access/transam/varsup" }
init_small = { path = "../../backend/utils/init/init_small" }
pg_class_seams = { path = "../../backend/catalog/pg_class_seams" }
postgres_seams = { path = "../../backend/tcop/postgres_seams" }
