[package]
name = "xloginsert"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "xloginsert"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_storage = { path = "../../../../_support/types/types_storage" }
types_rel = { path = "../../../../_support/types/rel" }
postgres_seams = { path = "../../../tcop/postgres_seams" }
elog = { path = "../../../utils/error/elog" }
crc32c = { path = "../../../../port/crc32c" }
pglz = { path = "../../../../common/pglz" }
init_small = { path = "../../../utils/init/init_small" }
miscinit = { path = "../../../utils/init/miscinit" }
guc_tables = { path = "../../../utils/misc/guc_tables" }
bufmgr = { path = "../../../storage/buffer/bufmgr" }
xact = { path = "../xact" }
origin_seams = { path = "../../../replication/origin_seams" }
transam_xlog = { path = "../transam_xlog" }
xloginsert_seams = { path = "../xloginsert_seams" }
xlogreader_seams = { path = "../xlogreader_seams" }

[dev-dependencies]
fd = { path = "../../../storage/file/fd" }
lwlock = { path = "../../../storage/lmgr/lwlock" }
shmem = { path = "../../../storage/ipc/shmem" }
aio_seams = { path = "../../../storage/aio/aio_seams" }
waitevent_seams = { path = "../../../utils/activity/waitevent_seams" }
xact_seams = { path = "../xact_seams" }
xlogreader = { path = "../xlogreader" }
controldata_utils = { path = "../../../../common/controldata_utils" }
mcx = { path = "../../../../_support/mcx" }
xlogutils = { path = "../xlogutils" }
libc = "0.2"
