//! Seam declarations for the `backend-catalog-pg-type` unit
//! (`catalog/pg_type.c`) — the entry points that `commands/typecmds.c`,
//! `commands/tablecmds.c`, `commands/cluster.c`, and other not-yet-ported
//! callers invoke across the dependency edge to `pg_type.c`.
//!
//! The owning unit (`backend-catalog-pg-type`) installs all of these from its
//! `init_seams()`; until a consumer's owner lands the decl just documents the
//! contract. `TypeShellMake` is consumed by `functioncmds.c`, whose first-
//! consumer seam crate (`backend-commands-functioncmds-seams`) already declares
//! `type_shell_make`; the `pg_type.c` owner installs that decl cross-crate
//! rather than duplicating it here (seam ownership is by C-source coverage, the
//! install is what matters).

#![allow(non_snake_case)]

use types_catalog::catalog_dependency::ObjectAddress;
use types_catalog::pg_type::{TypeCreateParams, TypeFormFields};
use types_core::Oid;
use types_error::PgResult;

seam_core::seam!(
    /// `TypeCreate(...)` (pg_type.c): do all the work to define a new type,
    /// returning the `ObjectAddress` assigned to it. The 32 positional C
    /// arguments cross as the owned [`TypeCreateParams`] bundle. Can
    /// `ereport(ERROR)` (invalid size/alignment, duplicate type, not-owner),
    /// carried on `Err`.
    pub fn type_create(params: TypeCreateParams) -> PgResult<ObjectAddress>
);

seam_core::seam!(
    /// `GenerateTypeDependencies(typeForm, defaultExpr_text, typacl, relationKind,
    /// isImplicitArray, isDependentType, makeExtensionDep, rebuild)` (pg_type.c):
    /// build the pg_depend/pg_shdepend dependency records for a type. The
    /// freshly-formed `pg_type` row crosses as its fixed-part projection
    /// [`TypeFormFields`]; the cooked default expression as its `nodeToString`
    /// text (`None` = the C `Anum_pg_type_typdefaultbin` SQL NULL); the ACL as
    /// its `aclitem[]` array (`None` = the C `Anum_pg_type_typacl` SQL NULL).
    /// The C "extract defaultExpr/typacl from the tuple if the caller passed
    /// NULL" branch is subsumed: the caller always projects them off its tuple.
    /// Can `ereport(ERROR)`, carried on `Err`.
    pub fn generate_type_dependencies(
        type_form: TypeFormFields,
        default_expr_bin: Option<String>,
        typacl: Option<std::vec::Vec<u8>>,
        relation_kind: i8,
        is_implicit_array: bool,
        is_dependent_type: bool,
        make_extension_dep: bool,
        rebuild: bool,
    ) -> PgResult<()>
);

seam_core::seam!(
    /// `RenameTypeInternal(typeOid, newTypeName, typeNamespace)` (pg_type.c):
    /// rename a type and any associated autogenerated array type. Caller has
    /// already checked privileges. Can `ereport(ERROR)` (duplicate name),
    /// carried on `Err`.
    pub fn rename_type_internal(
        type_oid: Oid,
        new_type_name: String,
        type_namespace: Oid,
    ) -> PgResult<()>
);

seam_core::seam!(
    /// `makeArrayTypeName(typeName, typeNamespace)` (pg_type.c): derive an
    /// unused `_`-prefixed array type name for a base type. Can `ereport(ERROR)`
    /// via its syscache probes, carried on `Err`.
    pub fn make_array_type_name(type_name: String, type_namespace: Oid) -> PgResult<String>
);

seam_core::seam!(
    /// `moveArrayTypeName(typeOid, typeName, typeNamespace)` (pg_type.c): if the
    /// conflicting type is an autogenerated array type, rename it out of the
    /// way (returns `true`, also for a shell type); else `false`. Can
    /// `ereport(ERROR)`, carried on `Err`.
    pub fn move_array_type_name(
        type_oid: Oid,
        type_name: String,
        type_namespace: Oid,
    ) -> PgResult<bool>
);

seam_core::seam!(
    /// `makeMultirangeTypeName(rangeTypeName, typeNamespace)` (pg_type.c):
    /// derive a multirange type name from a range type name. `ereport(ERROR)`
    /// on a name clash, carried on `Err`.
    pub fn make_multirange_type_name(
        range_type_name: String,
        type_namespace: Oid,
    ) -> PgResult<String>
);

seam_core::seam!(
    /// Guts of `RemoveTypeById` (typecmds.c:656) that live on the pg_type side:
    /// `table_open(TypeRelationId, RowExclusiveLock)` +
    /// `SearchSysCache1(TYPEOID, typeOid)` +
    /// `CatalogTupleDelete(relation, &tup->t_self)` + `ReleaseSysCache(tup)` +
    /// `table_close(relation, RowExclusiveLock)`. Returns the deleted row's
    /// `typtype` char so the caller (typecmds) can do the by-hand
    /// `EnumValuesDelete`/`RangeDelete` cleanup. `elog(ERROR, "cache lookup
    /// failed for type %u")` on a missing row, carried on `Err`.
    pub fn remove_type_catalog_row(type_oid: Oid) -> PgResult<i8>
);

seam_core::seam!(
    /// `table_open(TypeRelationId, AccessShareLock)` +
    /// `GetNewOidWithIndex(pg_type, TypeOidIndexId, Anum_pg_type_oid)` +
    /// `table_close(...)` — the non-binary-upgrade OID source shared by
    /// `AssignTypeArrayOid` / `AssignTypeMultirangeOid` /
    /// `AssignTypeMultirangeArrayOid` (typecmds.c:2447-2539). Can
    /// `ereport(ERROR)`, carried on `Err`.
    pub fn get_new_type_oid() -> PgResult<Oid>
);

// ---------------------------------------------------------------------------
// F3/F4 single-row mutators (commands/typecmds.c ALTER TYPE / ALTER DOMAIN).
//
// Each owns the pg_type catalog WRITE for one ALTER path: the owner opens
// pg_type (RowExclusiveLock), reads the row form for the values it needs, calls
// the narrow `catalog_tuple_update_*_pg_type` indexing seam (which does the
// heap_modify_tuple over only the targeted columns), then performs the
// `GenerateTypeDependencies` + `InvokeObjectPostAlterHook` calls where C does.
// typecmds does NO datum writes and NO GenerateTypeDependencies of its own.
// ---------------------------------------------------------------------------

use types_catalog::pg_type::TypeAttrUpdate;

seam_core::seam!(
    /// `AlterTypeOwnerInternal`'s SINGLE-ROW write (typecmds.c:3985): set
    /// `typowner = new_owner_id` and (when typacl non-NULL)
    /// `typacl = aclnewowner(old_acl, old_owner, new_owner)`, then
    /// `CatalogTupleUpdate`. No recursion to array/multirange (typecmds does
    /// that). Can `ereport(ERROR)`, carried on `Err`.
    pub fn set_type_owner(type_oid: Oid, new_owner_id: Oid) -> PgResult<()>
);

seam_core::seam!(
    /// `AlterTypeNamespaceInternal`'s single-row `typnamespace` write
    /// (typecmds.c:4233) + `CatalogTupleUpdate`. Can `ereport(ERROR)`.
    pub fn set_type_namespace(type_oid: Oid, nsp_oid: Oid) -> PgResult<()>
);

seam_core::seam!(
    /// AlterDomain* single-row `typnotnull` write + `CatalogTupleUpdate`. Can
    /// `ereport(ERROR)`.
    pub fn set_type_not_null(type_oid: Oid, not_null: bool) -> PgResult<()>
);

seam_core::seam!(
    /// `AlterDomainDefault`'s pg_type write (typecmds.c:2614): replace
    /// `typdefault`/`typdefaultbin` (`None` = SQL NULL), `CatalogTupleUpdate`,
    /// then `GenerateTypeDependencies(newtuple, defaultExpr=string_to_node(
    /// default_bin) when Some, typacl=None, relationKind=0, isImplicitArray=
    /// false, isDependentType=false, makeExtensionDep=false, rebuild=true)` +
    /// `InvokeObjectPostAlterHook(TypeRelationId, type_oid, 0)`. Can
    /// `ereport(ERROR)`.
    pub fn set_domain_default(
        type_oid: Oid,
        default_value: Option<String>,
        default_bin: Option<String>,
    ) -> PgResult<()>
);

seam_core::seam!(
    /// `AlterTypeRecurse`'s per-row update (typecmds.c:4561): build values/nulls/
    /// replaces from the [`TypeAttrUpdate`] gates, `heap_modify_tuple`,
    /// `CatalogTupleUpdate`, `GenerateTypeDependencies(newtup, NULL, NULL, 0,
    /// is_implicit_array, is_implicit_array, false, true)`,
    /// `InvokeObjectPostAlterHook(TypeRelationId, type_oid, 0)`. Returns the
    /// row's `typarray` OID (so typecmds can recurse to the array type). Can
    /// `ereport(ERROR)`.
    pub fn alter_type_recurse_update(
        type_oid: Oid,
        is_implicit_array: bool,
        attr: TypeAttrUpdate,
    ) -> PgResult<Oid>
);

seam_core::seam!(
    /// `AlterTypeRecurse`'s domain scan (typecmds.c:4682): `systable_beginscan(
    /// pg_type, InvalidOid, false, NULL, 1, key[typbasetype = base_type_oid])`
    /// returning the OIDs of rows with `typbasetype = base_type_oid` AND
    /// `typtype == TYPTYPE_DOMAIN` (the C `domainForm->typtype != TYPTYPE_DOMAIN`
    /// continue). typecmds then re-fires `AlterTypeRecurse` over each. Keeps the
    /// table scan in the pg_type owner. Can `ereport(ERROR)`.
    pub fn scan_domains_over_basetype(base_type_oid: Oid) -> PgResult<Vec<Oid>>
);
