//! Seam declarations for the `backend-catalog-pg-type` unit
//! (`catalog/pg_type.c`) — the entry points that `commands/typecmds.c`,
//! `commands/tablecmds.c`, `commands/cluster.c`, and other not-yet-ported
//! callers invoke across the dependency edge to `pg_type.c`.
//!
//! The owning unit (`backend-catalog-pg-type`) installs all of these from its
//! `init_seams()`; until a consumer's owner lands the decl just documents the
//! contract. `TypeShellMake` is consumed by `functioncmds.c`, whose first-
//! consumer seam crate (`backend-commands-functioncmds-seams`) already declares
//! `type_shell_make`; the `pg_type.c` owner installs that decl cross-crate
//! rather than duplicating it here (seam ownership is by C-source coverage, the
//! install is what matters).

#![allow(non_snake_case)]

use types_array::ArrayType;
use types_catalog::catalog_dependency::ObjectAddress;
use types_catalog::pg_type::{TypeCreateParams, TypeFormFields};
use types_core::Oid;
use types_error::PgResult;

seam_core::seam!(
    /// `TypeCreate(...)` (pg_type.c): do all the work to define a new type,
    /// returning the `ObjectAddress` assigned to it. The 32 positional C
    /// arguments cross as the owned [`TypeCreateParams`] bundle. Can
    /// `ereport(ERROR)` (invalid size/alignment, duplicate type, not-owner),
    /// carried on `Err`.
    pub fn type_create(params: TypeCreateParams) -> PgResult<ObjectAddress>
);

seam_core::seam!(
    /// `GenerateTypeDependencies(typeForm, defaultExpr_text, typacl, relationKind,
    /// isImplicitArray, isDependentType, makeExtensionDep, rebuild)` (pg_type.c):
    /// build the pg_depend/pg_shdepend dependency records for a type. The
    /// freshly-formed `pg_type` row crosses as its fixed-part projection
    /// [`TypeFormFields`]; the cooked default expression as its `nodeToString`
    /// text (`None` = the C `Anum_pg_type_typdefaultbin` SQL NULL); the ACL as
    /// its `aclitem[]` array (`None` = the C `Anum_pg_type_typacl` SQL NULL).
    /// The C "extract defaultExpr/typacl from the tuple if the caller passed
    /// NULL" branch is subsumed: the caller always projects them off its tuple.
    /// Can `ereport(ERROR)`, carried on `Err`.
    pub fn generate_type_dependencies(
        type_form: TypeFormFields,
        default_expr_bin: Option<String>,
        typacl: Option<ArrayType>,
        relation_kind: i8,
        is_implicit_array: bool,
        is_dependent_type: bool,
        make_extension_dep: bool,
        rebuild: bool,
    ) -> PgResult<()>
);

seam_core::seam!(
    /// `RenameTypeInternal(typeOid, newTypeName, typeNamespace)` (pg_type.c):
    /// rename a type and any associated autogenerated array type. Caller has
    /// already checked privileges. Can `ereport(ERROR)` (duplicate name),
    /// carried on `Err`.
    pub fn rename_type_internal(
        type_oid: Oid,
        new_type_name: String,
        type_namespace: Oid,
    ) -> PgResult<()>
);

seam_core::seam!(
    /// `makeArrayTypeName(typeName, typeNamespace)` (pg_type.c): derive an
    /// unused `_`-prefixed array type name for a base type. Can `ereport(ERROR)`
    /// via its syscache probes, carried on `Err`.
    pub fn make_array_type_name(type_name: String, type_namespace: Oid) -> PgResult<String>
);

seam_core::seam!(
    /// `moveArrayTypeName(typeOid, typeName, typeNamespace)` (pg_type.c): if the
    /// conflicting type is an autogenerated array type, rename it out of the
    /// way (returns `true`, also for a shell type); else `false`. Can
    /// `ereport(ERROR)`, carried on `Err`.
    pub fn move_array_type_name(
        type_oid: Oid,
        type_name: String,
        type_namespace: Oid,
    ) -> PgResult<bool>
);

seam_core::seam!(
    /// `makeMultirangeTypeName(rangeTypeName, typeNamespace)` (pg_type.c):
    /// derive a multirange type name from a range type name. `ereport(ERROR)`
    /// on a name clash, carried on `Err`.
    pub fn make_multirange_type_name(
        range_type_name: String,
        type_namespace: Oid,
    ) -> PgResult<String>
);

seam_core::seam!(
    /// Guts of `RemoveTypeById` (typecmds.c:656) that live on the pg_type side:
    /// `table_open(TypeRelationId, RowExclusiveLock)` +
    /// `SearchSysCache1(TYPEOID, typeOid)` +
    /// `CatalogTupleDelete(relation, &tup->t_self)` + `ReleaseSysCache(tup)` +
    /// `table_close(relation, RowExclusiveLock)`. Returns the deleted row's
    /// `typtype` char so the caller (typecmds) can do the by-hand
    /// `EnumValuesDelete`/`RangeDelete` cleanup. `elog(ERROR, "cache lookup
    /// failed for type %u")` on a missing row, carried on `Err`.
    pub fn remove_type_catalog_row(type_oid: Oid) -> PgResult<i8>
);

seam_core::seam!(
    /// `table_open(TypeRelationId, AccessShareLock)` +
    /// `GetNewOidWithIndex(pg_type, TypeOidIndexId, Anum_pg_type_oid)` +
    /// `table_close(...)` — the non-binary-upgrade OID source shared by
    /// `AssignTypeArrayOid` / `AssignTypeMultirangeOid` /
    /// `AssignTypeMultirangeArrayOid` (typecmds.c:2447-2539). Can
    /// `ereport(ERROR)`, carried on `Err`.
    pub fn get_new_type_oid() -> PgResult<Oid>
);

seam_core::seam!(
    /// Read-and-clear of the `binary_upgrade_next_array_pg_type_oid` global
    /// (catalog/binary_upgrade.h), set by the pg_upgrade_support functions:
    /// returns the pending value and resets it to `InvalidOid`.
    pub fn take_binary_upgrade_next_array_pg_type_oid() -> PgResult<Oid>
);

seam_core::seam!(
    /// Read-and-clear of the `binary_upgrade_next_mrng_pg_type_oid` global.
    pub fn take_binary_upgrade_next_mrng_pg_type_oid() -> PgResult<Oid>
);

seam_core::seam!(
    /// Read-and-clear of the `binary_upgrade_next_mrng_array_pg_type_oid` global.
    pub fn take_binary_upgrade_next_mrng_array_pg_type_oid() -> PgResult<Oid>
);
