[package]
name = "pg_config"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "pg_config"
path = "src/lib.rs"

[dependencies]
datum = { path = "../../../../_support/types/datum" }
types_error = { path = "../../../../_support/types/types_error" }
types_fmgr = { package = "types_fmgr", path = "../../../../_support/types/fmgr" }
funcapi = { path = "../../fmgr/funcapi" }
varlena = { path = "../../adt/varlena" }
init_small = { path = "../../init/init_small" }
pg_path = { path = "../../../../port/pg_path" }

[dev-dependencies]
types_core = { path = "../../../../_support/types/types_core" }
