[package]
name = "gram_core"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../_support/mcx" }
parser_seams = { path = "../parser_seams" }
parser_small1 = { path = "../parser_small1" }
scan_fgram = { path = "../scan_fgram" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
