// commands/progress.h, wired producers' sections only (vacuum, analyze);
// other commands' constants land with their producer wiring.

pub const PROGRESS_VACUUM_PHASE: usize = 0;
pub const PROGRESS_VACUUM_TOTAL_HEAP_BLKS: usize = 1;
pub const PROGRESS_VACUUM_HEAP_BLKS_SCANNED: usize = 2;
pub const PROGRESS_VACUUM_HEAP_BLKS_VACUUMED: usize = 3;
pub const PROGRESS_VACUUM_NUM_INDEX_VACUUMS: usize = 4;
pub const PROGRESS_VACUUM_MAX_DEAD_TUPLE_BYTES: usize = 5;
pub const PROGRESS_VACUUM_DEAD_TUPLE_BYTES: usize = 6;
pub const PROGRESS_VACUUM_NUM_DEAD_ITEM_IDS: usize = 7;
pub const PROGRESS_VACUUM_INDEXES_TOTAL: usize = 8;
pub const PROGRESS_VACUUM_INDEXES_PROCESSED: usize = 9;
pub const PROGRESS_VACUUM_DELAY_TIME: usize = 10;

pub const PROGRESS_VACUUM_PHASE_SCAN_HEAP: i64 = 1;
pub const PROGRESS_VACUUM_PHASE_VACUUM_INDEX: i64 = 2;
pub const PROGRESS_VACUUM_PHASE_VACUUM_HEAP: i64 = 3;
pub const PROGRESS_VACUUM_PHASE_INDEX_CLEANUP: i64 = 4;
pub const PROGRESS_VACUUM_PHASE_TRUNCATE: i64 = 5;
pub const PROGRESS_VACUUM_PHASE_FINAL_CLEANUP: i64 = 6;

pub const PROGRESS_ANALYZE_PHASE: usize = 0;
pub const PROGRESS_ANALYZE_BLOCKS_TOTAL: usize = 1;
pub const PROGRESS_ANALYZE_BLOCKS_DONE: usize = 2;
pub const PROGRESS_ANALYZE_EXT_STATS_TOTAL: usize = 3;
pub const PROGRESS_ANALYZE_EXT_STATS_COMPUTED: usize = 4;
pub const PROGRESS_ANALYZE_CHILD_TABLES_TOTAL: usize = 5;
pub const PROGRESS_ANALYZE_CHILD_TABLES_DONE: usize = 6;
pub const PROGRESS_ANALYZE_CURRENT_CHILD_TABLE_RELID: usize = 7;
pub const PROGRESS_ANALYZE_DELAY_TIME: usize = 8;

pub const PROGRESS_ANALYZE_PHASE_ACQUIRE_SAMPLE_ROWS: i64 = 1;
pub const PROGRESS_ANALYZE_PHASE_ACQUIRE_SAMPLE_ROWS_INH: i64 = 2;
pub const PROGRESS_ANALYZE_PHASE_COMPUTE_STATS: i64 = 3;
pub const PROGRESS_ANALYZE_PHASE_COMPUTE_EXT_STATS: i64 = 4;
pub const PROGRESS_ANALYZE_PHASE_FINALIZE_ANALYZE: i64 = 5;

pub const PROGRESS_COPY_BYTES_PROCESSED: usize = 0;
pub const PROGRESS_COPY_BYTES_TOTAL: usize = 1;
pub const PROGRESS_COPY_TUPLES_PROCESSED: usize = 2;
pub const PROGRESS_COPY_TUPLES_EXCLUDED: usize = 3;
pub const PROGRESS_COPY_COMMAND: usize = 4;
pub const PROGRESS_COPY_TYPE: usize = 5;
pub const PROGRESS_COPY_TUPLES_SKIPPED: usize = 6;

pub const PROGRESS_COPY_COMMAND_FROM: i64 = 1;
pub const PROGRESS_COPY_COMMAND_TO: i64 = 2;

pub const PROGRESS_COPY_TYPE_FILE: i64 = 1;
pub const PROGRESS_COPY_TYPE_PROGRAM: i64 = 2;
pub const PROGRESS_COPY_TYPE_PIPE: i64 = 3;
pub const PROGRESS_COPY_TYPE_CALLBACK: i64 = 4;
