//! `indexcmds.c` — autogenerated index / constraint name derivation:
//! [`makeObjectName`] / [`ChooseRelationName`] / [`ChooseIndexName`] /
//! [`ChooseIndexNameAddition`] / [`ChooseIndexColumnNames`].
//!
//! The NAMEDATALEN truncation arithmetic, branch order, and label choices match
//! the C source. For the `pg_class` name-collision probe the C scans `pg_class`
//! under an `InitDirtySnapshot` snapshot (so in-progress/uncommitted names also
//! collide); the dirty-snapshot systable-scan substrate is not reachable from
//! this lane, so we probe the committed catalog via the installed
//! `get_relname_relid` (`RELNAMENSP` syscache). This is faithful for the common
//! case and only diverges when a concurrent uncommitted backend is creating the
//! same name — the narrow window the C's dirty snapshot additionally guards.
//! The pg_constraint existence probe is the direct
//! `pg_constraint::ConstraintNameExists` owner call.

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

use mcx::Mcx;

use types_core::primitive::Oid;
use types_core::OidIsValid;
use types_error::PgResult;
use ::nodes::ddlnodes::IndexElem;

use utils_error::ereport;
use types_error::ERROR;

use pg_constraint::ConstraintNameExists;
use lsyscache_seams as lsyscache;
use mbutils_seams as mb_seam;

use crate::NAMEDATALEN;

// ---------------------------------------------------------------------------
// makeObjectName  (indexcmds.c:2517-2577)
// ---------------------------------------------------------------------------

/// `makeObjectName(name1, name2, label)`.
///
/// Create a name for an implicitly created index, sequence, constraint,
/// extended statistics, etc. The basic result is `name1_name2_label`, omitting
/// `_name2` or `_label` when those parameters are `None`. Truncates one or both
/// names if necessary to fit in fewer than `NAMEDATALEN` characters; the label
/// part is never truncated (so it had better be reasonably short).
pub fn makeObjectName(
    name1: &str,
    name2: Option<&str>,
    label: Option<&str>,
) -> PgResult<String> {
    let mut overhead = 0i32; // chars needed for label and underscores
    let name1_bytes = name1.as_bytes();

    let mut name1chars = name1_bytes.len() as i32;
    let mut name2chars: i32;
    let name2_bytes: &[u8];
    if let Some(name2) = name2 {
        name2_bytes = name2.as_bytes();
        name2chars = name2_bytes.len() as i32;
        overhead += 1; // allow for separating underscore
    } else {
        name2_bytes = &[];
        name2chars = 0;
    }
    if let Some(label) = label {
        overhead += label.len() as i32 + 1;
    }

    let availchars = NAMEDATALEN - 1 - overhead;
    debug_assert!(availchars > 0); // else caller chose a bad label

    // If we must truncate, preferentially truncate the longer name. This logic
    // could be expressed without a loop, but it's simple and obvious as a loop.
    while name1chars + name2chars > availchars {
        if name1chars > name2chars {
            name1chars -= 1;
        } else {
            name2chars -= 1;
        }
    }

    name1chars = mb_seam::pg_mbcliplen::call(name1_bytes, name1chars, name1chars);
    if name2.is_some() {
        name2chars = mb_seam::pg_mbcliplen::call(name2_bytes, name2chars, name2chars);
    }

    // Now construct the string using the chosen lengths.
    let mut out: Vec<u8> = Vec::new();
    out.try_reserve((name1chars + name2chars + overhead + 1) as usize)
        .map_err(|_| out_of_memory("makeObjectName"))?;
    out.extend_from_slice(&name1_bytes[..name1chars as usize]);
    if name2.is_some() {
        out.push(b'_');
        out.extend_from_slice(&name2_bytes[..name2chars as usize]);
    }
    if let Some(label) = label {
        out.push(b'_');
        out.extend_from_slice(label.as_bytes());
    }

    Ok(String::from_utf8_lossy(&out).into_owned())
}

// ---------------------------------------------------------------------------
// ChooseRelationName  (indexcmds.c:2605-2666)
// ---------------------------------------------------------------------------

/// `ChooseRelationName(name1, name2, label, namespaceid, isconstraint)`.
///
/// Select a nonconflicting name for a new relation (ordinarily an index name,
/// but also usable for sequences or any autogenerated relation kind). `label`
/// can't be `None`; digits are appended to the label if needed to make the name
/// unique within the namespace. If `isconstraint`, also avoids matching any
/// existing constraint name in the namespace.
pub fn ChooseRelationName(
    mcx: Mcx<'_>,
    name1: &str,
    name2: Option<&str>,
    label: &str,
    namespaceid: Oid,
    isconstraint: bool,
) -> PgResult<String> {
    let mut pass = 0i32;
    let relname: String;
    let mut modlabel: String = label.to_string();

    // The pg_class dirty-snapshot scan + the pg_constraint existence probe cross
    // their owners; the loop's name-tweaking control flow stays here.
    loop {
        let candidate = makeObjectName(name1, name2, Some(&modlabel))?;

        let collides = OidIsValid(lsyscache::get_relname_relid::call(&candidate, namespaceid)?);

        // break out of loop if no conflict
        if !collides
            && (!isconstraint || !ConstraintNameExists(mcx, &candidate, namespaceid)?)
        {
            relname = candidate;
            break;
        }

        // found a conflict, so try a new name component
        pass += 1;
        modlabel = format!("{label}{pass}");
    }

    Ok(relname)
}

// ---------------------------------------------------------------------------
// ChooseIndexName  (indexcmds.c:2673-2715)
// ---------------------------------------------------------------------------

/// `ChooseIndexName(tabname, namespaceId, colnames, exclusionOpNames, primary,
/// isconstraint)`.
///
/// Select the name to be used for an index. `has_exclusion_ops` is whether the
/// caller's `exclusionOpNames` list was non-NIL.
pub fn ChooseIndexName(
    mcx: Mcx<'_>,
    tabname: &str,
    namespace_id: Oid,
    colnames: &[String],
    has_exclusion_ops: bool,
    primary: bool,
    isconstraint: bool,
) -> PgResult<String> {
    if primary {
        // the primary key's name does not depend on the specific column(s)
        ChooseRelationName(mcx, tabname, None, "pkey", namespace_id, true)
    } else if has_exclusion_ops {
        let addition = ChooseIndexNameAddition(colnames);
        ChooseRelationName(mcx, tabname, Some(&addition), "excl", namespace_id, true)
    } else if isconstraint {
        let addition = ChooseIndexNameAddition(colnames);
        ChooseRelationName(mcx, tabname, Some(&addition), "key", namespace_id, true)
    } else {
        let addition = ChooseIndexNameAddition(colnames);
        ChooseRelationName(mcx, tabname, Some(&addition), "idx", namespace_id, false)
    }
}

// ---------------------------------------------------------------------------
// ChooseIndexNameAddition  (indexcmds.c:2728-2753)
// ---------------------------------------------------------------------------

/// `ChooseIndexNameAddition(colnames)`.
///
/// Generate "name2" for a new index given the list of column names for it (as
/// produced by [`ChooseIndexColumnNames`]). Less than NAMEDATALEN characters
/// will actually be used, so we truncate the result once we've generated that
/// many.
fn ChooseIndexNameAddition(colnames: &[String]) -> String {
    // buf[NAMEDATALEN * 2]; build up "name1_name2_...".
    let mut buf: Vec<u8> = Vec::new();
    let mut buflen = 0i32;

    for name in colnames {
        if buflen > 0 {
            buf.push(b'_'); // insert _ between names
            buflen += 1;
        }

        // strlcpy(buf + buflen, name, NAMEDATALEN) — copy at most NAMEDATALEN-1
        // bytes.
        let name_bytes = name.as_bytes();
        let copy_len = name_bytes.len().min((NAMEDATALEN - 1) as usize);
        buf.extend_from_slice(&name_bytes[..copy_len]);
        buflen += copy_len as i32;
        if buflen >= NAMEDATALEN {
            break;
        }
    }
    String::from_utf8_lossy(&buf).into_owned()
}

// ---------------------------------------------------------------------------
// ChooseIndexColumnNames  (indexcmds.c:2762-2814)
// ---------------------------------------------------------------------------

/// `ChooseIndexColumnNames(indexElems)`.
///
/// Select the actual names to be used for the columns of an index, given the
/// list of [`IndexElem`]s for the columns. This is mostly about ensuring the
/// names are unique so we don't get a conflicting-attribute-names error.
/// Returns a list of plain strings.
pub fn ChooseIndexColumnNames(index_elems: &[&IndexElem<'_>]) -> Vec<String> {
    let mut result: Vec<String> = Vec::new();

    for ielem in index_elems.iter() {
        // Get the preliminary name from the IndexElem.
        let origname: &str = if let Some(n) = ielem.indexcolname.as_ref() {
            n.as_str() // caller-specified name
        } else if let Some(n) = ielem.name.as_ref() {
            n.as_str() // simple column reference
        } else {
            "expr" // default name for expression
        };

        // If it conflicts with any previous column, tweak it.
        let mut curname: String = origname.to_string();
        let mut i = 1;
        loop {
            let conflict = result.iter().any(|prev| prev.as_str() == curname.as_str());
            if !conflict {
                break; // found nonconflicting name
            }

            let nbuf = format!("{i}");

            // Ensure generated names are shorter than NAMEDATALEN.
            let nlen = mb_seam::pg_mbcliplen::call(
                origname.as_bytes(),
                origname.len() as i32,
                NAMEDATALEN - 1 - nbuf.len() as i32,
            );
            let mut buf: Vec<u8> = Vec::new();
            buf.extend_from_slice(&origname.as_bytes()[..nlen as usize]);
            buf.extend_from_slice(nbuf.as_bytes());
            curname = String::from_utf8_lossy(&buf).into_owned();
            i += 1;
        }

        // And attach to the result list.
        result.push(curname);
    }
    result
}

/// Out-of-memory error (the `try_reserve` failure path), matching the project's
/// OOM-safe allocation rule.
fn out_of_memory(ctx: &str) -> utils_error::PgError {
    ereport(ERROR)
        .errcode(types_error::ERRCODE_OUT_OF_MEMORY)
        .errmsg(format!("out of memory in {ctx}"))
        .into_error()
}
