#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::result_large_err)]
#![allow(clippy::too_many_arguments)]

//! `backend/commands/indexcmds.c` — the CREATE INDEX command driver
//! (PostgreSQL 18.3).
//!
//! This unit grounds the high-value CREATE INDEX command path against the
//! repo's owned node / relcache model:
//!
//!  * [`DefineIndex`] — the command-level driver: validate the statement, open
//!    the table, resolve the access method, run [`ComputeIndexAttrs`], assemble
//!    the [`IndexInfo`] + [`IndexCreateArgs`], call `index_create`, and (for a
//!    non-concurrent, non-partitioned build) `index_create` already builds it.
//!  * [`ComputeIndexAttrs`] — per-column opclass / collation / expression
//!    resolution, exclusion / WITHOUT-OVERLAPS operator handling, included-column
//!    restrictions, `indoption` derivation, and per-column `attoptions`.
//!  * [`ResolveOpClass`] / [`GetOperatorFromCompareType`] / [`CheckPredicate`].
//!  * the autogenerated-name choosers
//!    ([`makeObjectName`] / [`ChooseRelationName`] / [`ChooseIndexName`] /
//!    `ChooseIndexNameAddition` / [`ChooseIndexColumnNames`]).
//!
//! `GetDefaultOpClass` lives in the repo's `pg_opclass` / lsyscache owner (a
//! home divergence already merged); [`ResolveOpClass`] reaches it through
//! `lsyscache::get_default_opclass`.
//!
//! ## Deferred (precise seam-panics, tracked)
//!
//! The CONCURRENTLY tail of `DefineIndex` (multi-transaction build/validate
//! state machine: `index_concurrently_build`, `validate_index`,
//! `WaitForLockers`, `WaitForOlderSnapshots`, snapshot/session-lock dance) and
//! the partitioned-table recursion (`generateClonedIndexStmt`,
//! `IndexSetParentIndex`, `BuildIndexInfo`/`CompareIndexInfo` matching) are NOT
//! built here — their substrate (cross-transaction control, partition-index
//! cloning) is unported. They are precise loud panics, not silent stubs.
//!
//! [`ExecReindex`] / [`ReindexIndex`] / [`ReindexTable`] (the REINDEX command
//! drivers) are ported for the common non-concurrent btree case: parse the
//! option list, resolve+lock the target (heap-before-index callback for an
//! index, maintains-table callback for a table), then call the installed
//! `reindex_index` / `reindex_relation` catalog seams to rebuild storage.
//! Deferred legs raise a precise feature-not-supported error: REINDEX
//! CONCURRENTLY, partitioned table/index (`ReindexPartitions`), and
//! `ReindexMultipleTables` (REINDEX SCHEMA / SYSTEM / DATABASE).

extern crate alloc;

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

use mcx::{Mcx, PgVec};

use ::types_core::primitive::Oid;
use types_core::{InvalidOid, OidIsValid};
use ::types_error::PgResult;
use ::nodes::ddlnodes::{IndexElem, IndexStmt};
use ::nodes::nodes::{ntag, Node};
use ::nodes::primnodes::Expr;
use ::nodes::rawnodes::RangeVar;
use ::rel::Relation;

use ::utils_error::ereport;
use ::types_error::ERROR;

// ---- real owner crates ----
use ::nodes_core::makefuncs::{make_ands_implicit, make_index_info};
use ::nodes_core::bitmapset::{bms_is_member, bms_next_member, bms_union};
use ::index::index_check_primary_key;
use ::index_amapi::GetIndexAmRoutineByAmId;
use ::clauses::contain_mutable_functions_after_planning;
use tablespace::{get_tablespace_name, get_tablespace_oid, GetDefaultTablespace};
use ::comment::CreateComments;
use misc_guc::{at_eoxact_guc, NewGUCNestLevel};
use guc_seams::{restrict_search_path, set_config_option};
use ::table::table_close as owner_table_close;
use miscinit::{GetUserIdAndSecContext, SetUserIdAndSecContext};
use ::activity_small::backend_progress::{
    pgstat_progress_end_command, pgstat_progress_incr_param, pgstat_progress_start_command,
    pgstat_progress_update_param,
};

// ---- seams consumed from other units ----
use index_seams::{self as index_seam, IndexCreateArgs};
use aclchk_seams as aclchk_seam;
use lsyscache_seams as lsyscache;
use syscache_seams as syscache;
use var_seams as var_seam;
use tablecmds_seams as tablecmds_seam;
use vacuumlazy_seams as namespacename_seam;
use table_seams as table_seam;
use namespace_seams as namespace_seam;
use lmgr_seams as lmgr_seam;
use lock_seams as lock_seam;
use lmgr_proc_seams as proc_seam;
use procarray_seams as procarray_seam;
use snapmgr_seams as snapmgr_seam;
use transam_xact_seams as xact_seam;
use inval_seams as inval_seam;
use relcache_seams as relcache_seam;
use partcache_seams as partcache_seam;
use format_type_seams as formattype_seam;
use pg_inherits_seams as inherits_seam;
use pg_depend_seams as depend_seam;
use indexam_seams as indexam_seam;
use parse_utilcmd_seams as utilcmd_seam;

use crate::opclass::get_am_name_str;
use ::types_amapi::COMPARE_EQ;
use ::hash::hash::HTEqualStrategyNumber;
use ::types_scan::scankey::BTEqualStrategyNumber;

use ::types_acl::acl::{ACL_CREATE, ACLCHECK_OK};
use ::nodes::parsenodes::{OBJECT_SCHEMA, OBJECT_TABLESPACE};
use ::types_catalog::catalog::{GLOBALTABLESPACE_OID, TABLESPACE_RELATION_ID};
use ::types_catalog::catalog_dependency::ObjectAddress;
use ::types_core::catalog::{NAMESPACE_RELATION_ID, RELATION_RELATION_ID};
use ::types_tuple::access::{
    ATTRIBUTE_GENERATED_VIRTUAL, RELKIND_FOREIGN_TABLE, RELKIND_INDEX, RELKIND_MATVIEW,
    RELKIND_PARTITIONED_TABLE, RELKIND_RELATION,
};
use ::types_tuple::heaptuple::FirstLowInvalidHeapAttributeNumber;
use ::types_pgstat::backend_progress::ProgressCommandType;

pub mod check_compat;
pub mod choosers;
pub mod compute;
pub mod opclass;
pub mod reindex_concurrently;
pub mod reindex_multi;

pub use check_compat::{check_index_compatible_stmt, CheckIndexCompatible};
pub use choosers::{
    makeObjectName, ChooseIndexColumnNames, ChooseIndexName, ChooseRelationName,
};
pub use compute::ComputeIndexAttrs;
pub use opclass::{GetOperatorFromCompareType, ResolveOpClass};

/// `NAMEDATALEN` (`pg_config_manual.h`).
pub(crate) const NAMEDATALEN: i32 = 64;

/// `INDEX_MAX_KEYS` (`pg_config_manual.h`).
const INDEX_MAX_KEYS: i32 = 32;

/// `RELPERSISTENCE_TEMP` (`catalog/pg_class.h`).
const RELPERSISTENCE_TEMP: u8 = b't';

// `index.h` `index_create` flag bits / constraint flag bits (defined locally,
// mirroring `catalog/index.h`, matching the established pattern in
// `backend-catalog-toasting`).
const INDEX_CREATE_IS_PRIMARY: u16 = 1 << 0;
const INDEX_CREATE_ADD_CONSTRAINT: u16 = 1 << 1;
const INDEX_CREATE_SKIP_BUILD: u16 = 1 << 2;
const INDEX_CREATE_CONCURRENT: u16 = 1 << 3;
const INDEX_CREATE_IF_NOT_EXISTS: u16 = 1 << 4;
const INDEX_CREATE_PARTITIONED: u16 = 1 << 5;
const INDEX_CREATE_INVALID: u16 = 1 << 6;
const INDEX_CONSTR_CREATE_DEFERRABLE: u16 = 1 << 1;
const INDEX_CONSTR_CREATE_INIT_DEFERRED: u16 = 1 << 2;
const INDEX_CONSTR_CREATE_WITHOUT_OVERLAPS: u16 = 1 << 5;

// `commands/progress.h` — PROGRESS_CREATEIDX_* param indices and command kinds.
const PROGRESS_CREATEIDX_COMMAND: i32 = 0;
const PROGRESS_CREATEIDX_INDEX_OID: i32 = 6;
const PROGRESS_CREATEIDX_ACCESS_METHOD_OID: i32 = 8;
const PROGRESS_CREATEIDX_PARTITIONS_TOTAL: i32 = 13;
const PROGRESS_CREATEIDX_PARTITIONS_DONE: i32 = 14;
const PROGRESS_CREATEIDX_COMMAND_CREATE: i64 = 1;
const PROGRESS_CREATEIDX_COMMAND_CREATE_CONCURRENTLY: i64 = 2;
/// `PROGRESS_CREATEIDX_PHASE` — AM-agnostic phase number param index.
const PROGRESS_CREATEIDX_PHASE: i32 = 9;
/// Phases of CREATE INDEX advertised via `PROGRESS_CREATEIDX_PHASE`.
const PROGRESS_CREATEIDX_PHASE_WAIT_1: i64 = 1;
const PROGRESS_CREATEIDX_PHASE_WAIT_2: i64 = 3;
const PROGRESS_CREATEIDX_PHASE_WAIT_3: i64 = 7;
/// `PROGRESS_WAITFOR_*` — the WaitForLockers/WaitForOlderSnapshots params.
const PROGRESS_WAITFOR_TOTAL: i32 = 3;
const PROGRESS_WAITFOR_DONE: i32 = 4;
const PROGRESS_WAITFOR_CURRENT_PID: i32 = 5;

/// `SECURITY_RESTRICTED_OPERATION` (`miscadmin.h`).
const SECURITY_RESTRICTED_OPERATION: i32 = 1 << 1;

// ---------------------------------------------------------------------------
// small node-list helpers (NodePtr lists of String value nodes)
// ---------------------------------------------------------------------------

/// `strVal`-style read of a `Node::String`'s `sval`.
pub(crate) fn node_sval<'a>(node: &'a Node<'_>) -> &'a str {
    match node.node_tag() {
        ntag::T_String => node.expect_string().sval.as_str(),
        _ => panic!("indexcmds: expected a String value node in a name list"),
    }
}

/// A list of `Node::String` (the C `List *` of `String` nodes) rendered as a
/// `NameList` (`&[Option<String>]`) for the namespace helpers.
pub(crate) fn name_list(names: &PgVec<'_, ::nodes::nodes::NodePtr<'_>>) -> Vec<Option<String>> {
    names
        .iter()
        .map(|n| Some(node_sval(n).to_string()))
        .collect()
}

/// The same list rendered as `Vec<String>` for `compatible_oper_opid`.
pub(crate) fn name_list_strings(
    names: &PgVec<'_, ::nodes::nodes::NodePtr<'_>>,
) -> Vec<String> {
    names.iter().map(|n| node_sval(n).to_string()).collect()
}

// ---------------------------------------------------------------------------
// CheckPredicate  (indexcmds.c:1842-1858)
// ---------------------------------------------------------------------------

/// `CheckPredicate(Expr *predicate)`.
///
/// `transformExpr()` already rejected subqueries / aggregates / window
/// functions; the only remaining check is that a predicate using mutable
/// functions is rejected.
pub fn CheckPredicate<'mcx>(mcx: Mcx<'mcx>, predicate: Expr<'mcx>) -> PgResult<()> {
    if contain_mutable_functions_after_planning(mcx, predicate)? {
        return Err(ereport(ERROR)
            .errcode(::types_error::ERRCODE_INVALID_OBJECT_DEFINITION)
            .errmsg("functions in index predicate must be marked IMMUTABLE")
            .into_error());
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// DefineIndex  (indexcmds.c:542-1828) — the CREATE INDEX command driver.
// ---------------------------------------------------------------------------

/// `DefineIndex(tableId, stmt, indexRelationId, parentIndexId,
/// parentConstraintId, total_parts, is_alter_table, check_rights,
/// check_not_in_use, skip_build, quiet)`.
///
/// Ported for the non-concurrent, non-partitioned core (the high-value CREATE
/// INDEX command path) plus the CREATE INDEX CONCURRENTLY multi-transaction
/// build/validate tail. The partitioned-table recursion is a precise
/// seam-panic — see the module docs and [`define_index_partition_recursion`].
///
/// Returns the [`ObjectAddress`] of the created index.
pub fn DefineIndex<'mcx>(
    mcx: Mcx<'mcx>,
    table_id: Oid,
    stmt: &IndexStmt<'mcx>,
    mut index_relation_id: Oid,
    parent_index_id: Oid,
    parent_constraint_id: Oid,
    mut total_parts: i32,
    is_alter_table: bool,
    check_rights: bool,
    check_not_in_use: bool,
    skip_build: bool,
    quiet: bool,
) -> PgResult<ObjectAddress> {
    let mut root_save_nestlevel = NewGUCNestLevel();

    restrict_search_path::call()?;

    // Some callers need us to run with an empty default_tablespace; this is a
    // necessary hack to be able to reproduce catalog state accurately when
    // recreating indexes after table-rewriting ALTER TABLE.
    //
    // C: set_config_option("default_tablespace", "", PGC_USERSET, PGC_S_SESSION,
    //    GUC_ACTION_SAVE, true, 0, false). The repo seam is the `SetConfigOption`
    //    macro shape (no explicit GUC_ACTION_SAVE); the action defaults there.
    if stmt.reset_default_tblspc {
        set_config_option::call(
            "default_tablespace",
            "",
            types_guc::guc::GucContext::PGC_USERSET,
            types_guc::guc::GucSource::PGC_S_SESSION,
        )?;
    }

    // Force non-concurrent build on temporary relations.
    let concurrent =
        stmt.concurrent && lsyscache::get_rel_persistence::call(table_id)? != RELPERSISTENCE_TEMP;

    // Start progress report (skipped when building a partition).
    if !OidIsValid(parent_index_id) {
        pgstat_progress_start_command(ProgressCommandType::CreateIndex, table_id);
        pgstat_progress_update_param(
            PROGRESS_CREATEIDX_COMMAND,
            if concurrent {
                PROGRESS_CREATEIDX_COMMAND_CREATE_CONCURRENTLY
            } else {
                PROGRESS_CREATEIDX_COMMAND_CREATE
            },
        );
    }

    // No index OID to report yet.
    pgstat_progress_update_param(PROGRESS_CREATEIDX_INDEX_OID, InvalidOid as i64);

    // count key attributes in index
    let number_of_key_attributes = stmt.indexParams.len() as i32;

    // Build the combined list of (key + INCLUDE) index parameters, as IndexElems.
    let all_index_params: Vec<&IndexElem<'mcx>> = stmt
        .indexParams
        .iter()
        .chain(stmt.indexIncludingParams.iter())
        .map(|n| node_as_index_elem(n.as_ref()))
        .collect();
    let number_of_attributes = all_index_params.len() as i32;

    if number_of_key_attributes <= 0 {
        return Err(ereport(ERROR)
            .errcode(::types_error::ERRCODE_INVALID_OBJECT_DEFINITION)
            .errmsg("must specify at least one column")
            .into_error());
    }
    if number_of_attributes > INDEX_MAX_KEYS {
        return Err(ereport(ERROR)
            .errcode(::types_error::ERRCODE_TOO_MANY_COLUMNS)
            .errmsg(format!(
                "cannot use more than {INDEX_MAX_KEYS} columns in an index"
            ))
            .into_error());
    }

    // Take the table lock. ShareUpdateExclusiveLock for concurrent, ShareLock
    // otherwise.
    let lockmode: ::types_storage::lock::LOCKMODE = if concurrent {
        ::types_storage::lock::ShareUpdateExclusiveLock
    } else {
        ::types_storage::lock::ShareLock
    };
    let rel = table_seam::table_open::call(mcx, table_id, lockmode)?;

    // Switch to the table owner's userid + lock down security-restricted ops.
    let (root_save_userid, root_save_sec_context) = GetUserIdAndSecContext();
    SetUserIdAndSecContext(
        rel.rd_rel.relowner,
        root_save_sec_context | SECURITY_RESTRICTED_OPERATION,
    );

    let namespace_id = rel.rd_rel.relnamespace;

    // Exclusion behavior: EXCLUDE constraint or temporal PRIMARY KEY/UNIQUE.
    let exclusion = !stmt.excludeOpNames.is_empty() || stmt.iswithoutoverlaps;

    // Ensure it makes sense to index this kind of relation.
    match rel.rd_rel.relkind {
        x if x == RELKIND_RELATION || x == RELKIND_MATVIEW || x == RELKIND_PARTITIONED_TABLE => {}
        _ => {
            let name = rel.rd_rel.relname.as_str().to_string();
            let detail = pg_class_seams::errdetail_relkind_not_supported::call(
                rel.rd_rel.relkind,
            )?;
            return Err(ereport(ERROR)
                .errcode(::types_error::ERRCODE_WRONG_OBJECT_TYPE)
                .errmsg(format!("cannot create index on relation \"{name}\""))
                .errdetail(detail)
                .into_error());
        }
    }

    // Partitioned tables: we only create catalog entries; actual indexes are
    // built by recursing per partition.
    let partitioned = rel.rd_rel.relkind == RELKIND_PARTITIONED_TABLE;
    if partitioned && stmt.concurrent {
        let name = rel.rd_rel.relname.as_str().to_string();
        return Err(ereport(ERROR)
            .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
            .errmsg(format!(
                "cannot create index on partitioned table \"{name}\" concurrently"
            ))
            .into_error());
    }

    // Unless the caller vouches for it, insist the table not be in use.
    if check_not_in_use {
        tablecmds_seam::check_table_not_in_use::call(&rel, "CREATE INDEX")?;
    }

    // Verify CREATE rights in the rel's namespace.
    if check_rights {
        let aclresult =
            aclchk_seam::object_aclcheck::call(NAMESPACE_RELATION_ID, namespace_id, root_save_userid, ACL_CREATE)?;
        if aclresult != ACLCHECK_OK {
            aclchk_seam::aclcheck_error::call(
                aclresult,
                OBJECT_SCHEMA,
                Some(namespacename_seam::get_namespace_name::call(namespace_id)?),
            )?;
        }
    }

    // Select tablespace.
    let mut tablespace_id: Oid;
    if let Some(ts) = stmt.tableSpace.as_ref() {
        tablespace_id = get_tablespace_oid(mcx, ts.as_str(), false)?;
        if partitioned && tablespace_id == my_database_tablespace()? {
            return Err(ereport(ERROR)
                .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                .errmsg("cannot specify default tablespace for partitioned relations")
                .into_error());
        }
    } else {
        tablespace_id = GetDefaultTablespace(mcx, rel.rd_rel.relpersistence as i8, partitioned)?;
    }

    // Check tablespace permissions.
    if check_rights && OidIsValid(tablespace_id) && tablespace_id != my_database_tablespace()? {
        let aclresult = aclchk_seam::object_aclcheck::call(
            TABLESPACE_RELATION_ID,
            tablespace_id,
            root_save_userid,
            ACL_CREATE,
        )?;
        if aclresult != ACLCHECK_OK {
            let tsname = get_tablespace_name(mcx, tablespace_id)?.map(|s| s.as_str().to_string());
            aclchk_seam::aclcheck_error::call(aclresult, OBJECT_TABLESPACE, tsname)?;
        }
    }

    // Force shared indexes into pg_global; reject pg_global for non-shared.
    if rel.rd_rel.relisshared {
        tablespace_id = GLOBALTABLESPACE_OID;
    } else if tablespace_id == GLOBALTABLESPACE_OID {
        return Err(ereport(ERROR)
            .errcode(::types_error::ERRCODE_INVALID_PARAMETER_VALUE)
            .errmsg("only shared relations can be placed in pg_global tablespace")
            .into_error());
    }

    // Choose the index column names.
    let index_col_names = ChooseIndexColumnNames(&all_index_params);

    // Select index name if caller didn't specify.
    let index_relation_name: String = match stmt.idxname.as_ref() {
        Some(n) => n.as_str().to_string(),
        None => ChooseIndexName(
            mcx,
            rel.rd_rel.relname.as_str(),
            namespace_id,
            &index_col_names,
            !stmt.excludeOpNames.is_empty(),
            stmt.primary,
            stmt.isconstraint,
        )?,
    };

    // Look up the access method; "rtree" -> "gist" hack.
    let mut access_method_name: String = stmt
        .accessMethod
        .as_ref()
        .map(|a| a.as_str().to_string())
        .expect("DefineIndex: IndexStmt has no accessMethod");
    let mut am_info = syscache::search_am_by_name::call(mcx, &access_method_name)?;
    if am_info.is_none() && access_method_name == "rtree" {
        ereport(::types_error::NOTICE)
            .errmsg("substituting access method \"gist\" for obsolete method \"rtree\"")
            .finish(here("DefineIndex"))?;
        access_method_name = "gist".to_string();
        am_info = syscache::search_am_by_name::call(mcx, &access_method_name)?;
    }
    let am_info = match am_info {
        Some(a) => a,
        None => {
            return Err(ereport(ERROR)
                .errcode(::types_error::ERRCODE_UNDEFINED_OBJECT)
                .errmsg(format!("access method \"{access_method_name}\" does not exist"))
                .into_error());
        }
    };
    let access_method_id = am_info.oid;
    let am_routine = GetIndexAmRoutineByAmId(access_method_id)?;

    pgstat_progress_update_param(PROGRESS_CREATEIDX_ACCESS_METHOD_OID, access_method_id as i64);

    if stmt.unique && !stmt.iswithoutoverlaps && !am_routine.amcanunique {
        return Err(amerr("does not support unique indexes", &access_method_name));
    }
    if !stmt.indexIncludingParams.is_empty() && !am_routine.amcaninclude {
        return Err(amerr("does not support included columns", &access_method_name));
    }
    if number_of_key_attributes > 1 && !am_routine.amcanmulticol {
        return Err(amerr("does not support multicolumn indexes", &access_method_name));
    }
    if exclusion && am_routine.amgettuple.is_none() {
        return Err(amerr("does not support exclusion constraints", &access_method_name));
    }
    if stmt.iswithoutoverlaps && access_method_name != "gist" {
        return Err(amerr("does not support WITHOUT OVERLAPS constraints", &access_method_name));
    }

    let amcanorder = am_routine.amcanorder;
    let amissummarizing = am_routine.amsummarizing;

    // Validate predicate, if given.
    if let Some(where_clause) = stmt.whereClause.as_ref() {
        let pred_expr = where_clause
            .as_ref()
            .as_expr()
            .expect("DefineIndex: whereClause is not an Expr")
            .clone();
        CheckPredicate(mcx, pred_expr)?;
    }

    // Parse AM-specific options, convert to text-array form, validate.
    //
    // C: reloptions = transformRelOptions((Datum) 0, stmt->options, NULL, NULL,
    //    false, false); (void) index_reloptions(amoptions, reloptions, true);
    //    where amoptions = accessMethodForm->amoptions.
    //
    // `transformRelOptionsBytes` builds the on-disk `text[]` varlena image (the
    // bytes `pg_class.reloptions` stores); it rides the `::types_tuple::Datum`
    // by-reference lane as `Datum::ByRef` so `index_create`'s catalog write
    // (`reloptions_to_bytes`) reads the real array (the Datum-bridge fix —
    // construct_text_array_bytes, mirroring the array-producer ByRef fixes).
    let reloptions: ::types_tuple::Datum<'mcx> = if stmt.options.is_empty() {
        ::types_tuple::Datum::null()
    } else {
        // amoptions = accessMethodForm->amoptions; the port keys the AM's option
        // parser on the handler OID (rd_amhandler), the same dispatch the
        // relcache uses for index_reloptions.
        let amhandler = match syscache::search_am_handler::call(access_method_id)? {
            Some(h) => h,
            None => InvalidOid,
        };
        let bytes = transform_index_reloptions_byref(mcx, &stmt.options, amhandler)?;
        ::types_tuple::Datum::from_byref_bytes_in(mcx, &bytes)?
    };

    // Prepare the IndexInfo. Predicates must be in implicit-AND format. In a
    // concurrent build, mark it not-ready-for-inserts.
    let predicate_list: Vec<Expr> = match stmt.whereClause.as_ref() {
        Some(wc) => make_ands_implicit(
            wc.as_ref().as_expr().map(|e| e.clone()),
        ),
        None => Vec::new(),
    };

    let mut index_info = make_index_info(
        number_of_attributes,
        number_of_key_attributes,
        access_method_id,
        (),
        (),
        stmt.unique,
        stmt.nulls_not_distinct,
        !concurrent,
        concurrent,
        amissummarizing,
        stmt.iswithoutoverlaps,
    );
    index_info.ii_Context = Some(mcx);
    if !predicate_list.is_empty() {
        let mut pv = PgVec::new_in(mcx);
        for e in predicate_list {
            pv.push(e);
        }
        index_info.ii_Predicate = Some(pv);
    }

    let mut type_ids = vec_oid(number_of_attributes);
    let mut collation_ids = vec_oid(number_of_attributes);
    let mut opclass_ids = vec_oid(number_of_attributes);
    let mut opclass_options: Vec<::types_tuple::Datum<'mcx>> =
        (0..number_of_attributes).map(|_| ::types_tuple::Datum::null()).collect();
    let mut col_options = vec![0i16; number_of_attributes as usize];

    ComputeIndexAttrs(
        mcx,
        &mut index_info,
        &rel,
        &mut type_ids,
        &mut collation_ids,
        &mut opclass_ids,
        &mut opclass_options,
        &mut col_options,
        &all_index_params,
        if stmt.excludeOpNames.is_empty() {
            None
        } else {
            Some(&stmt.excludeOpNames)
        },
        table_id,
        &access_method_name,
        access_method_id,
        amcanorder,
        stmt.isconstraint,
        stmt.iswithoutoverlaps,
        root_save_userid,
        root_save_sec_context,
        &mut root_save_nestlevel,
    )?;

    // Extra checks when creating a PRIMARY KEY index.
    if stmt.primary {
        index_check_primary_key(mcx, &rel, &index_info, is_alter_table)?;
    }

    // Partitioned + (unique | exclusion): partition-key subset check.
    //
    // If this table is partitioned and we're creating a unique index, primary
    // key, or exclusion constraint, make sure that the partition key is a
    // subset of the index's columns.  Otherwise it would be possible to violate
    // uniqueness by putting values that ought to be unique in different
    // partitions.
    if partitioned && (stmt.unique || exclusion) {
        define_index_partition_keycheck(
            mcx,
            &rel,
            stmt,
            exclusion,
            &index_info,
            &collation_ids,
            &opclass_ids,
        )?;
    }

    // Disallow indexes on system columns + virtual generated columns.
    for i in 0..index_info.ii_NumIndexAttrs as usize {
        let attno = index_info.ii_IndexAttrNumbers[i];
        if attno < 0 {
            return Err(ereport(ERROR)
                .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                .errmsg("index creation on system columns is not supported")
                .into_error());
        }
        if attno > 0
            && rel.rd_att.attr((attno - 1) as usize).attgenerated == ATTRIBUTE_GENERATED_VIRTUAL
        {
            return Err(virtual_gencol_error(stmt));
        }
    }

    // Check for system and generated columns used in expressions / predicates.
    if index_info.ii_Expressions.is_some() || index_info.ii_Predicate.is_some() {
        let mut indexattrs: Option<::mcx::PgBox<'mcx, ::nodes::Bitmapset<'mcx>>> = None;
        if let Some(exprs) = index_info.ii_Expressions.as_ref() {
            for e in exprs.iter() {
                indexattrs = bms_union_opt(mcx, indexattrs, var_seam::pull_varattnos::call(mcx, e, 1)?)?;
            }
        }
        if let Some(preds) = index_info.ii_Predicate.as_ref() {
            for e in preds.iter() {
                indexattrs = bms_union_opt(mcx, indexattrs, var_seam::pull_varattnos::call(mcx, e, 1)?)?;
            }
        }

        let attrs_ref = indexattrs.as_deref();
        let mut i = FirstLowInvalidHeapAttributeNumber as i32 + 1;
        while i < 0 {
            if bms_is_member(i - FirstLowInvalidHeapAttributeNumber as i32, attrs_ref) {
                return Err(ereport(ERROR)
                    .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                    .errmsg("index creation on system columns is not supported")
                    .into_error());
            }
            i += 1;
        }

        let mut j = -1;
        loop {
            j = bms_next_member(attrs_ref, j);
            if j < 0 {
                break;
            }
            let attno = j + FirstLowInvalidHeapAttributeNumber as i32;
            if attno > 0
                && rel.rd_att.attr((attno - 1) as usize).attgenerated == ATTRIBUTE_GENERATED_VIRTUAL
            {
                return Err(virtual_gencol_error_expr(stmt));
            }
        }
    }

    // Is the index safe for others to ignore? (only relevant to concurrent.)
    let safe_index = index_info.ii_Expressions.is_none() && index_info.ii_Predicate.is_none();
    let _ = safe_index;

    // Report index creation (constraint case), as a DEBUG message — omitted
    // (DEBUG1 chatter; not observable behavior).
    let _ = quiet;

    // Make the catalog entries (and, unless skipped/concurrent/partitioned,
    // build the index).
    let mut flags: u16 = 0;
    let mut constr_flags: u16 = 0;
    if stmt.isconstraint {
        flags |= INDEX_CREATE_ADD_CONSTRAINT;
    }
    if skip_build || concurrent || partitioned {
        flags |= INDEX_CREATE_SKIP_BUILD;
    }
    if stmt.if_not_exists {
        flags |= INDEX_CREATE_IF_NOT_EXISTS;
    }
    if concurrent {
        flags |= INDEX_CREATE_CONCURRENT;
    }
    if partitioned {
        flags |= INDEX_CREATE_PARTITIONED;
    }
    if stmt.primary {
        flags |= INDEX_CREATE_IS_PRIMARY;
    }

    // If partitioned, recursion declined but partitions exist -> mark invalid.
    if partitioned && relation_inh_declined(stmt) && relation_has_partitions(mcx, &rel)? {
        flags |= INDEX_CREATE_INVALID;
    }

    if stmt.deferrable {
        constr_flags |= INDEX_CONSTR_CREATE_DEFERRABLE;
    }
    if stmt.initdeferred {
        constr_flags |= INDEX_CONSTR_CREATE_INIT_DEFERRED;
    }
    if stmt.iswithoutoverlaps {
        constr_flags |= INDEX_CONSTR_CREATE_WITHOUT_OVERLAPS;
    }

    // Assemble IndexCreateArgs and call index_create. The per-column
    // opclassOptions cross as Some(vec) (one Datum per attribute).
    let col_names_owned: Vec<String> = index_col_names.clone();
    let collation_ids_v = collation_ids.clone();
    let opclass_ids_v = opclass_ids.clone();
    let coloptions_v = col_options.clone();

    let args = IndexCreateArgs {
        index_relation_name: index_relation_name.clone(),
        index_relation_id,
        parent_index_relid: parent_index_id,
        parent_constraint_id,
        rel_file_number: stmt.oldNumber,
        index_info,
        index_col_names: col_names_owned,
        access_method_id,
        table_space_id: tablespace_id,
        collation_ids: collation_ids_v,
        opclass_ids: opclass_ids_v,
        coloptions: coloptions_v,
        reloptions,
        opclass_options: Some(opclass_options),
        stattargets: None, // C: stattargets == NULL
        flags,
        constr_flags,
        allow_system_table_mods: allow_system_table_mods(),
        is_internal: !check_rights,
    };

    let (created_index_relation_id, created_constraint_id) = index_seam::index_create::call(&rel, args)?;
    index_relation_id = created_index_relation_id;

    let address = ObjectAddress {
        classId: RELATION_RELATION_ID,
        objectId: index_relation_id,
        objectSubId: 0,
    };

    if !OidIsValid(index_relation_id) {
        // IF NOT EXISTS hit an existing index: roll back GUC + userid, close.
        at_eoxact_guc(false, root_save_nestlevel);
        SetUserIdAndSecContext(root_save_userid, root_save_sec_context);
        owner_table_close(rel, ::types_storage::lock::NoLock)?;
        if !OidIsValid(parent_index_id) {
            pgstat_progress_end_command();
        }
        return Ok(address);
    }

    // Roll back GUC changes from index functions; keep subsequent changes local.
    at_eoxact_guc(false, root_save_nestlevel);
    root_save_nestlevel = NewGUCNestLevel();
    restrict_search_path::call()?;

    // Add any requested comment.
    if let Some(comment) = stmt.idxcomment.as_ref() {
        CreateComments(mcx, index_relation_id, RELATION_RELATION_ID, 0, Some(comment.as_str()))?;
    }

    // Partitioned-table recursion: build/attach child indexes (indexcmds.c
    // DefineIndex partitioned branch, lines ~1292-1600).
    if partitioned {
        let partdesc = partdesc::RelationGetPartitionDesc(mcx, &rel, true)?;

        // Unless caller specified to skip this step (via ONLY), process each
        // partition to make sure they all contain a corresponding index. If we're
        // called internally (no stmt->relation), recurse always.
        if (stmt.relation.is_none() || relation_should_recurse(stmt)) && partdesc.nparts > 0 {
            // Make a local copy of partdesc->oids[], just for safety.
            let part_oids: Vec<Oid> = partdesc.oids.iter().copied().collect();
            let mut invalidate_parent = false;

            // Report the total number of partitions at the start of the command;
            // don't update it when being called recursively.
            if !OidIsValid(parent_index_id) {
                if total_parts < 0 {
                    let children = inherits_seam::find_all_inheritors::call(
                        mcx,
                        table_id,
                        ::types_storage::lock::NoLock,
                    )?;
                    total_parts = children.len() as i32 - 1;
                }
                pgstat_progress_update_param(
                    PROGRESS_CREATEIDX_PARTITIONS_TOTAL,
                    total_parts as i64,
                );
            }

            // We'll need an IndexInfo describing the parent index, built the same
            // way (BuildIndexInfo) so it will match those for child indexes.
            let parent_index = indexam_seam::index_open::call(mcx, index_relation_id, lockmode)?;
            let parent_index_info = ::index::BuildIndexInfo(mcx, &parent_index)?;
            let parent_index_collations: Vec<Oid> = parent_index.rd_indcollation.to_vec();
            let parent_index_opfamilies: Vec<Oid> = parent_index.rd_opfamily.to_vec();

            // For each partition, scan all existing indexes; if one matches our
            // index definition and is not already attached to some other parent
            // index, attach it. If none matches, build a new index by recursing.
            for &child_relid in part_oids.iter() {
                let childrel = table_seam::table_open::call(mcx, child_relid, lockmode)?;

                let (child_save_userid, child_save_sec_context) = GetUserIdAndSecContext();
                SetUserIdAndSecContext(
                    childrel.rd_rel.relowner,
                    child_save_sec_context | SECURITY_RESTRICTED_OPERATION,
                );
                let child_save_nestlevel = NewGUCNestLevel();
                restrict_search_path::call()?;

                // Don't try to create indexes on foreign tables.
                if childrel.rd_rel.relkind == RELKIND_FOREIGN_TABLE {
                    if stmt.unique || stmt.primary {
                        return Err(ereport(ERROR)
                            .errcode(::types_error::ERRCODE_WRONG_OBJECT_TYPE)
                            .errmsg(format!(
                                "cannot create unique index on partitioned table \"{}\"",
                                rel.rd_rel.relname.as_str()
                            ))
                            .errdetail(format!(
                                "Table \"{}\" contains partitions that are foreign tables.",
                                rel.rd_rel.relname.as_str()
                            ))
                            .into_error());
                    }
                    at_eoxact_guc(false, child_save_nestlevel);
                    SetUserIdAndSecContext(child_save_userid, child_save_sec_context);
                    owner_table_close(childrel, lockmode)?;
                    continue;
                }

                let childidxs =
                    relcache_seam::relation_get_index_list::call(mcx, &childrel)?;
                let attmap = next::attmap::build_attrmap_by_name(
                    mcx,
                    &childrel.rd_att,
                    &rel.rd_att,
                    false,
                )?;

                let mut found = false;
                for &cldidxid in childidxs.iter() {
                    // this index is already partition of another one
                    if inherits_seam::has_superclass::call(cldidxid)? {
                        continue;
                    }

                    let cldidx = indexam_seam::index_open::call(mcx, cldidxid, lockmode)?;
                    let cld_idx_info = ::index::BuildIndexInfo(mcx, &cldidx)?;
                    if ::index::CompareIndexInfo(
                        mcx,
                        &cld_idx_info,
                        &parent_index_info,
                        &cldidx.rd_indcollation,
                        &parent_index_collations,
                        &cldidx.rd_opfamily,
                        &parent_index_opfamilies,
                        &attmap.attnums,
                    )? {
                        let mut cld_constr_oid = InvalidOid;

                        // If this index is being created in the parent because of
                        // a constraint, the child needs a constraint also; if none,
                        // this index is no good, so keep looking.
                        if OidIsValid(created_constraint_id) {
                            cld_constr_oid =
                                pg_constraint::get_relation_idx_constraint_oid(
                                    child_relid,
                                    cldidxid,
                                )?;
                            if !OidIsValid(cld_constr_oid) {
                                cldidx.close(lockmode)?;
                                continue;
                            }
                        }

                        // Attach index to parent and we're done.
                        IndexSetParentIndex(mcx, &cldidx, index_relation_id)?;
                        if OidIsValid(created_constraint_id) {
                            pg_constraint::ConstraintSetParentConstraint(
                                mcx,
                                cld_constr_oid,
                                created_constraint_id,
                                child_relid,
                            )?;
                        }

                        if !cldidx
                            .rd_index
                            .as_ref()
                            .map(|i| i.indisvalid)
                            .unwrap_or(false)
                        {
                            invalidate_parent = true;
                        }

                        found = true;

                        pgstat_progress_incr_param(PROGRESS_CREATEIDX_PARTITIONS_DONE, 1);

                        // keep lock till commit
                        cldidx.close(::types_storage::lock::NoLock)?;
                        break;
                    }

                    cldidx.close(lockmode)?;
                }

                at_eoxact_guc(false, child_save_nestlevel);
                SetUserIdAndSecContext(child_save_userid, child_save_sec_context);
                owner_table_close(childrel, ::types_storage::lock::NoLock)?;

                // If no matching index was found, create our own.
                if !found {
                    // Build an IndexStmt describing the desired child index as in
                    // ATTACH PARTITION (search-path-independent via the cloner).
                    let (child_stmt, _child_constr_oid) =
                        utilcmd_seam::generateClonedIndexStmt::call(
                            mcx,
                            None,
                            &parent_index,
                            &attmap,
                        )?;

                    // Recurse as the starting user ID. Callee will use that for
                    // permission checks, then switch again.
                    SetUserIdAndSecContext(root_save_userid, root_save_sec_context);
                    let child_addr = DefineIndex(
                        mcx,
                        child_relid,
                        &child_stmt,
                        InvalidOid,        // no predefined OID
                        index_relation_id, // this is our child
                        created_constraint_id,
                        -1,
                        is_alter_table,
                        check_rights,
                        check_not_in_use,
                        skip_build,
                        quiet,
                    )?;
                    SetUserIdAndSecContext(child_save_userid, child_save_sec_context);

                    // The index just created could have been switched to invalid
                    // when recursing across multiple partition levels.
                    if !lsyscache::get_index_isvalid::call(child_addr.objectId)? {
                        invalidate_parent = true;
                    }
                }
            }

            parent_index.close(lockmode)?;

            // The pg_index row we inserted was marked indisvalid=true. But if we
            // attached an existing index that is invalid, update our row to
            // invalid too.
            if invalidate_parent {
                index_seam::index_mark_invalid::call(index_relation_id)?;
                // CCI here to make this update visible, in case this recurses
                // across multiple partition levels.
                xact_seam::command_counter_increment::call()?;
            }
        }

        // Indexes on partitioned tables are not themselves built, so we're done.
        at_eoxact_guc(false, root_save_nestlevel);
        SetUserIdAndSecContext(root_save_userid, root_save_sec_context);
        owner_table_close(rel, ::types_storage::lock::NoLock)?;
        if !OidIsValid(parent_index_id) {
            pgstat_progress_end_command();
        } else {
            pgstat_progress_incr_param(PROGRESS_CREATEIDX_PARTITIONS_DONE, 1);
        }
        return Ok(address);
    }

    at_eoxact_guc(false, root_save_nestlevel);
    SetUserIdAndSecContext(root_save_userid, root_save_sec_context);

    if !concurrent {
        // Non-concurrent: index_create already built it; close and we're done.
        owner_table_close(rel, ::types_storage::lock::NoLock)?;
        if !OidIsValid(parent_index_id) {
            pgstat_progress_end_command();
        } else {
            pgstat_progress_incr_param(PROGRESS_CREATEIDX_PARTITIONS_DONE, 1);
        }
        return Ok(address);
    }

    // ---------------------------------------------------------------------
    // CONCURRENTLY build/validate state machine (indexcmds.c:1619-1829).
    // ---------------------------------------------------------------------

    // Save lockrelid and locktag for below, then close rel (keep the lock).
    let heaprelid = relcache_seam::rel_lock_relid::call(rel.rd_id)?;
    let heaplocktag = lmgr_seam::set_locktag_relation::call(heaprelid.dbId, heaprelid.relId);
    owner_table_close(rel, ::types_storage::lock::NoLock)?;

    // For a concurrent build, we must make the catalog entries visible to other
    // transactions before we start to build the index (the new index is marked
    // not indisready / not indisvalid, so no one inserts into it or uses it for
    // queries). Commit our current transaction so the index becomes visible;
    // then start another. Before committing, take a session-level lock on the
    // table so neither it nor the index can be dropped before we finish (cannot
    // block — we already hold the same lock within our transaction).
    lmgr_seam::lock_relation_id_for_session::call(heaprelid, ShareUpdateExclusiveLock_v())?;

    snapmgr_seam::pop_active_snapshot::call()?;
    xact_seam::commit_transaction_command::call()?;
    xact_seam::start_transaction_command::call()?;

    // Tell concurrent index builds to ignore us, if index qualifies.
    if safe_index {
        proc_seam::set_indexsafe_procflags::call()?;
    }

    // The index is now visible, so we can report the OID; include the report for
    // the beginning of phase 2.
    pgstat_progress_update_param(PROGRESS_CREATEIDX_INDEX_OID as i32, index_relation_id as i64);
    pgstat_progress_update_param(PROGRESS_CREATEIDX_PHASE, PROGRESS_CREATEIDX_PHASE_WAIT_1);

    // Phase 2: wait until no running transaction could have the table open with
    // the old list of indexes. ShareLock considers transactions holding locks
    // that permit writing to the table. (Real lock acquisition, not a sleep, so
    // deadlocks are detected.)
    lmgr_seam::wait_for_lockers::call(heaplocktag, ShareLock_v(), true)?;

    // Set ActiveSnapshot since functions in the indexes may need it.
    snapmgr_seam::push_active_snapshot::call(alloc::rc::Rc::new(
        snapmgr_seam::get_transaction_snapshot::call()?,
    ))?;

    // Perform concurrent build of the index (first pass).
    ::index::index_concurrently_build(mcx, table_id, index_relation_id)?;

    // We can do away with our snapshot.
    snapmgr_seam::pop_active_snapshot::call()?;

    // Commit this transaction to make the indisready update visible.
    xact_seam::commit_transaction_command::call()?;
    xact_seam::start_transaction_command::call()?;

    if safe_index {
        proc_seam::set_indexsafe_procflags::call()?;
    }

    // Phase 3: once again wait until no transaction can have the table open with
    // the index marked read-only for updates.
    pgstat_progress_update_param(PROGRESS_CREATEIDX_PHASE, PROGRESS_CREATEIDX_PHASE_WAIT_2);
    lmgr_seam::wait_for_lockers::call(heaplocktag, ShareLock_v(), true)?;

    // Take the "reference snapshot" validate_index() uses to filter candidate
    // tuples; also set ActiveSnapshot to it (functions in indexes may need one).
    let snapshot = snapmgr_seam::register_snapshot::call(
        snapmgr_seam::get_transaction_snapshot::call()?,
    )?;
    snapmgr_seam::push_active_snapshot::call(alloc::rc::Rc::new(snapshot.clone()))?;

    // Scan the index and the heap, insert any missing index entries (2nd pass).
    ::index::validate_index(mcx, table_id, index_relation_id, Some(snapshot.clone()))?;

    // Drop the reference snapshot. We must do this before waiting out other
    // snapshot holders, else we deadlock against other CREATE INDEX CONCURRENTLY
    // processes (which would see our snapshot as one they must wait for). But
    // first, save the snapshot's xmin to use as limitXmin for the wait.
    let limit_xmin = snapshot.xmin;

    snapmgr_seam::pop_active_snapshot::call()?;
    snapmgr_seam::unregister_snapshot::call(snapshot);

    // The snapshot subsystem could still hold registered snapshots that pin our
    // advertised xmin (serializable xact snapshot; the CatalogSnapshot). To
    // avoid deadlocks, commit + start yet another transaction and do our wait
    // before any snapshot has been taken in it.
    xact_seam::commit_transaction_command::call()?;
    xact_seam::start_transaction_command::call()?;

    if safe_index {
        proc_seam::set_indexsafe_procflags::call()?;
    }

    // The index is now valid in the sense that it contains all currently
    // interesting tuples; but it might not contain tuples deleted just before
    // the reference snap was taken, so wait out any transactions that might have
    // older snapshots.
    pgstat_progress_update_param(PROGRESS_CREATEIDX_PHASE, PROGRESS_CREATEIDX_PHASE_WAIT_3);
    WaitForOlderSnapshots(mcx, limit_xmin, true)?;

    // Updating pg_index might involve TOAST access, so ensure a valid snapshot.
    snapmgr_seam::push_active_snapshot::call(alloc::rc::Rc::new(
        snapmgr_seam::get_transaction_snapshot::call()?,
    ))?;

    // Index can now be marked valid -- update its pg_index entry.
    ::index::index_set_state_flags(
        mcx,
        index_relation_id,
        ::index_seams::IndexStateFlagsAction::SetValid,
    )?;

    snapmgr_seam::pop_active_snapshot::call()?;

    // The pg_index update causes backends (including us) to refresh the index's
    // relcache entry; also send a relcache inval on the parent table to force
    // replanning of cached plans, so existing sessions can use the new index.
    inval_seam::cache_invalidate_relcache::call(heaprelid.relId)?;

    // Release the session-level lock on the parent table.
    lmgr_seam::unlock_relation_id_for_session::call(heaprelid, ShareUpdateExclusiveLock_v())?;

    pgstat_progress_end_command();

    Ok(address)
}

/// `ShareUpdateExclusiveLock` (`storage/lockdefs.h`).
fn ShareUpdateExclusiveLock_v() -> ::types_storage::lock::LOCKMODE {
    4
}

/// `ShareLock` (`storage/lockdefs.h`).
fn ShareLock_v() -> ::types_storage::lock::LOCKMODE {
    5
}

/// `WaitForOlderSnapshots(limitXmin, progress)` (commands/indexcmds.c) — wait
/// for transactions that might have an older snapshot than `limitXmin`, used at
/// the end of a concurrent index build. Obtain the VXIDs of such transactions
/// (excluding autovacuum / VACUUM / safe-IC backends, and other DBs) and wait
/// for each individually, rechecking the live set each iteration so a backend
/// that goes idle-in-transaction with xmin 0 stops being waited on.
///
/// In single-backend mode `GetCurrentVirtualXIDs` reports no other backends, so
/// this returns immediately.
pub fn WaitForOlderSnapshots<'mcx>(
    mcx: Mcx<'mcx>,
    limit_xmin: ::types_core::TransactionId,
    progress: bool,
) -> PgResult<()> {
    use ::types_storage::storage::{PROC_IN_SAFE_IC, PROC_IN_VACUUM, PROC_IS_AUTOVACUUM};

    let exclude_vacuum = (PROC_IS_AUTOVACUUM | PROC_IN_VACUUM | PROC_IN_SAFE_IC) as i32;

    // old_snapshots = GetCurrentVirtualXIDs(limitXmin, true, false,
    //                     PROC_IS_AUTOVACUUM | PROC_IN_VACUUM | PROC_IN_SAFE_IC,
    //                     &n_old_snapshots);
    let mut old_snapshots = procarray_seam::get_current_virtual_xids::call(
        mcx,
        limit_xmin,
        true,
        false,
        exclude_vacuum,
    )?;
    let n_old_snapshots = old_snapshots.len();

    if progress {
        pgstat_progress_update_param(PROGRESS_WAITFOR_TOTAL, n_old_snapshots as i64);
    }

    for i in 0..n_old_snapshots {
        if !old_snapshots[i].is_valid() {
            continue; // found uninteresting in a previous cycle
        }

        if i > 0 {
            // See if anything's changed: re-read the live VXID set and forget
            // any old snapshot whose VXID is no longer present.
            let newer_snapshots = procarray_seam::get_current_virtual_xids::call(
                mcx,
                limit_xmin,
                true,
                false,
                exclude_vacuum,
            )?;
            for j in i..n_old_snapshots {
                if !old_snapshots[j].is_valid() {
                    continue;
                }
                let still_present = newer_snapshots.iter().any(|nv| {
                    nv.procNumber == old_snapshots[j].procNumber
                        && nv.localTransactionId == old_snapshots[j].localTransactionId
                });
                if !still_present {
                    old_snapshots[j] = ::types_core::xact::VirtualTransactionId::invalid();
                }
            }
        }

        if old_snapshots[i].is_valid() {
            if progress {
                // Publish who we're going to wait for (best-effort pid lookup).
                let pid = procarray_seam::proc_number_get_proc_pid::call(
                    old_snapshots[i].procNumber,
                );
                if pid != 0 {
                    pgstat_progress_update_param(PROGRESS_WAITFOR_CURRENT_PID, pid as i64);
                }
            }
            // VirtualXactLock(old_snapshots[i], true): wait for the xact to end.
            lock_seam::virtual_xact_lock::call(old_snapshots[i], true)?;
        }

        if progress {
            pgstat_progress_update_param(PROGRESS_WAITFOR_DONE, (i + 1) as i64);
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// ExecReindex / ReindexIndex / ReindexTable  (REINDEX command drivers)
// ---------------------------------------------------------------------------

use types_cluster::{
    ReindexParams, REINDEXOPT_CONCURRENTLY, REINDEXOPT_REPORT_PROGRESS, REINDEXOPT_VERBOSE,
    REINDEX_REL_CHECK_CONSTRAINTS, REINDEX_REL_PROCESS_TOAST,
};
use ::nodes::ddlnodes::{DefElem, ReindexObjectType, ReindexStmt};
use ::types_storage::lock::{AccessExclusiveLock, ShareLock, ShareUpdateExclusiveLock};
use ::types_tuple::access::RELKIND_PARTITIONED_INDEX;

const RELPERSISTENCE_TEMP_U8: u8 = b't';

/// `defGetBoolean(defel)` (define.c) — accepts a Boolean, an Integer (0/1), or
/// the strings "true"/"false"/"on"/"off". Read directly off the `'mcx`
/// parse-node `arg` (local copy, matching the dbcommands pattern).
fn reindex_def_get_boolean(defel: &DefElem<'_>) -> PgResult<bool> {
    let name = defel.defname.as_deref().unwrap_or("");
    match defel.arg.as_deref() {
        None => Ok(true),
        Some(n) if n.is_boolean() => Ok(n.expect_boolean().boolval),
        Some(n) if n.is_integer() => match n.expect_integer().ival {
            0 => Ok(false),
            1 => Ok(true),
            _ => Err(reindex_boolean_err(name)),
        },
        Some(n) if n.is_string() => {
            let v = n.expect_string().sval.as_str();
            if v.eq_ignore_ascii_case("true") || v.eq_ignore_ascii_case("on") {
                Ok(true)
            } else if v.eq_ignore_ascii_case("false") || v.eq_ignore_ascii_case("off") {
                Ok(false)
            } else {
                Err(reindex_boolean_err(name))
            }
        }
        _ => Err(reindex_boolean_err(name)),
    }
}

fn reindex_boolean_err(name: &str) -> ::utils_error::PgError {
    ereport(ERROR)
        .errcode(::types_error::ERRCODE_SYNTAX_ERROR)
        .errmsg(format!("{name} requires a Boolean value"))
        .into_error()
}

/// `defGetString(defel)` (define.c) — `strVal(defel->arg)`.
fn reindex_def_get_string(defel: &DefElem<'_>) -> PgResult<String> {
    let name = defel.defname.as_deref().unwrap_or("");
    match defel.arg.as_deref() {
        Some(n) if n.is_string() => Ok(n.expect_string().sval.as_str().to_string()),
        _ => Err(ereport(ERROR)
            .errcode(::types_error::ERRCODE_SYNTAX_ERROR)
            .errmsg(format!("{name} requires a parameter"))
            .into_error()),
    }
}

/// Marshal a parse-tree `RangeVar` node onto the access-layer `RangeVar`
/// consumed by the namespace target-resolution seams (mirrors the matview /
/// CLUSTER bridge).
fn reindex_access_rangevar(rv: &RangeVar<'_>) -> ::types_tuple::access::RangeVar {
    ::types_tuple::access::RangeVar {
        catalogname: rv.catalogname.as_ref().map(|s| s.as_str().to_string()),
        schemaname: rv.schemaname.as_ref().map(|s| s.as_str().to_string()),
        relname: rv
            .relname
            .as_ref()
            .map(|s| s.as_str().to_string())
            .unwrap_or_default(),
        inh: rv.inh,
        relpersistence: rv.relpersistence as u8,
        location: rv.location,
    }
}

/// `stmt->relation` as a `&RangeVar` node (REINDEX INDEX / TABLE always have one).
fn reindex_stmt_rangevar<'a, 'mcx>(stmt: &'a ReindexStmt<'mcx>) -> &'a RangeVar<'mcx> {
    match stmt.relation.as_deref().map(|n| n.node_tag()) {
        Some(t) if t == ntag::T_RangeVar => stmt.relation.as_deref().unwrap().expect_rangevar(),
        _ => panic!("ExecReindex: REINDEX INDEX/TABLE stmt->relation is not a RangeVar"),
    }
}

/// `ExecReindex(pstate, stmt, isTopLevel)` (indexcmds.c) — primary entry point
/// for manual REINDEX commands. A preparation wrapper: parse the option list,
/// resolve the target tablespace, and dispatch to the per-kind subroutine.
pub fn ExecReindex<'mcx>(
    mcx: Mcx<'mcx>,
    pstate: &mut ::nodes::parsestmt::ParseState<'mcx>,
    stmt: &ReindexStmt<'mcx>,
    is_top_level: bool,
) -> PgResult<()> {
    let _ = &pstate;
    let mut params = ReindexParams::default();
    let mut concurrently = false;
    let mut verbose = false;
    let mut tablespacename: Option<String> = None;

    // Parse option list.
    for opt_node in stmt.params.iter() {
        let opt = match opt_node.node_tag() {
            t if t == ntag::T_DefElem => opt_node.expect_defelem(),
            _ => panic!("ExecReindex: REINDEX option is not a DefElem"),
        };
        let defname = opt.defname.as_deref().unwrap_or("");
        if defname == "verbose" {
            verbose = reindex_def_get_boolean(opt)?;
        } else if defname == "concurrently" {
            concurrently = reindex_def_get_boolean(opt)?;
        } else if defname == "tablespace" {
            tablespacename = Some(reindex_def_get_string(opt)?);
        } else {
            return Err(ereport(ERROR)
                .errcode(::types_error::ERRCODE_SYNTAX_ERROR)
                .errmsg(format!("unrecognized REINDEX option \"{defname}\""))
                .into_error());
        }
    }

    if concurrently {
        xact_seam::prevent_in_transaction_block::call(is_top_level, "REINDEX CONCURRENTLY")?;
    }

    params.options = (if verbose { REINDEXOPT_VERBOSE } else { 0 })
        | (if concurrently { REINDEXOPT_CONCURRENTLY } else { 0 });

    // Assign the tablespace OID to move indexes to, with InvalidOid to do nothing.
    if let Some(tsname) = tablespacename {
        let tablespace_oid = get_tablespace_oid(mcx, &tsname, false)?;
        params.tablespace_oid = tablespace_oid;

        // Check permissions except when moving to database's default.
        if OidIsValid(tablespace_oid)
            && tablespace_oid != tablespace_globals_seams::MyDatabaseTableSpace::call()?
        {
            let aclresult = aclchk_seam::object_aclcheck::call(
                TABLESPACE_RELATION_ID,
                tablespace_oid,
                ::miscinit::GetUserId(),
                ACL_CREATE,
            )?;
            if aclresult != ACLCHECK_OK {
                aclchk_seam::aclcheck_error::call(
                    aclresult,
                    OBJECT_TABLESPACE,
                    Some(
                        get_tablespace_name(mcx, tablespace_oid)?
                            .map(|s| s.as_str().to_string())
                            .unwrap_or_default(),
                    ),
                )?;
            }
        }
    } else {
        params.tablespace_oid = InvalidOid;
    }

    match stmt.kind {
        ReindexObjectType::REINDEX_OBJECT_INDEX => {
            ReindexIndex(mcx, stmt, &params, is_top_level)?;
        }
        ReindexObjectType::REINDEX_OBJECT_TABLE => {
            ReindexTable(mcx, stmt, &params, is_top_level)?;
        }
        ReindexObjectType::REINDEX_OBJECT_SCHEMA
        | ReindexObjectType::REINDEX_OBJECT_SYSTEM
        | ReindexObjectType::REINDEX_OBJECT_DATABASE => {
            // These cannot run inside a user transaction block; ReindexMultipleTables
            // reindexes each table in a separate transaction.
            let label = match stmt.kind {
                ReindexObjectType::REINDEX_OBJECT_SCHEMA => "REINDEX SCHEMA",
                ReindexObjectType::REINDEX_OBJECT_SYSTEM => "REINDEX SYSTEM",
                _ => "REINDEX DATABASE",
            };
            xact_seam::prevent_in_transaction_block::call(is_top_level, label)?;
            reindex_multi::ReindexMultipleTables(mcx, stmt, &params)?;
        }
    }
    Ok(())
}

/// `ReindexIndex(stmt, params, isTopLevel)` (indexcmds.c) — recreate a specific
/// index. Resolves+locks the index (heap-before-index via the reindex-index
/// callback), then dispatches to `reindex_index` for the common
/// non-partitioned, non-concurrent case.
fn ReindexIndex<'mcx>(
    mcx: Mcx<'mcx>,
    stmt: &ReindexStmt<'mcx>,
    params: &ReindexParams,
    is_top_level: bool,
) -> PgResult<()> {
    let rv = reindex_stmt_rangevar(stmt);
    let access_rv = reindex_access_rangevar(rv);

    // Find and lock index, checking permissions on the table. The lock level
    // here must match the index lock obtained in reindex_index().
    let lockmode = if (params.options & REINDEXOPT_CONCURRENTLY) != 0 {
        ShareUpdateExclusiveLock
    } else {
        AccessExclusiveLock
    };
    let ind_oid =
        namespace_seam::range_var_get_relid_for_reindex_index::call(mcx, &access_rv, lockmode)?;

    // Obtain the current persistence and kind of the existing index.
    let persistence = lsyscache::get_rel_persistence::call(ind_oid)?;
    let relkind = lsyscache::get_rel_relkind::call(ind_oid)?;

    if relkind == RELKIND_PARTITIONED_INDEX {
        reindex_multi::ReindexPartitions(mcx, stmt, ind_oid, params, is_top_level)?;
    } else if (params.options & REINDEXOPT_CONCURRENTLY) != 0
        && persistence != RELPERSISTENCE_TEMP_U8
    {
        reindex_concurrently::ReindexRelationConcurrently(mcx, stmt, ind_oid, params)?;
    } else {
        let mut newparams = *params;
        newparams.options |= REINDEXOPT_REPORT_PROGRESS;
        index_seam::reindex_index::call(
            mcx,
            stmt,
            ind_oid,
            false,
            persistence as i8,
            newparams,
        )?;
    }
    Ok(())
}

/// `ReindexTable(stmt, params, isTopLevel)` (indexcmds.c) — recreate all indexes
/// of a table (and of its toast table, if any) via `reindex_relation`.
fn ReindexTable<'mcx>(
    mcx: Mcx<'mcx>,
    stmt: &ReindexStmt<'mcx>,
    params: &ReindexParams,
    is_top_level: bool,
) -> PgResult<()> {
    let rv = reindex_stmt_rangevar(stmt);
    let access_rv = reindex_access_rangevar(rv);
    let relname = access_rv.relname.clone();

    // The lock level used here should match reindex_relation().
    let lockmode = if (params.options & REINDEXOPT_CONCURRENTLY) != 0 {
        ShareUpdateExclusiveLock
    } else {
        ShareLock
    };
    let heap_oid =
        namespace_seam::range_var_get_relid_maintains_table::call(mcx, &access_rv, lockmode)?;

    if lsyscache::get_rel_relkind::call(heap_oid)? == RELKIND_PARTITIONED_TABLE {
        reindex_multi::ReindexPartitions(mcx, stmt, heap_oid, params, is_top_level)?;
    } else if (params.options & REINDEXOPT_CONCURRENTLY) != 0
        && lsyscache::get_rel_persistence::call(heap_oid)? != RELPERSISTENCE_TEMP_U8
    {
        let result =
            reindex_concurrently::ReindexRelationConcurrently(mcx, stmt, heap_oid, params)?;
        if !result {
            ereport(::types_error::NOTICE)
                .errmsg(format!(
                    "table \"{relname}\" has no indexes that can be reindexed concurrently"
                ))
                .finish(here("ReindexTable"))?;
        }
    } else {
        let mut newparams = *params;
        newparams.options |= REINDEXOPT_REPORT_PROGRESS;
        let result = index_seam::reindex_relation::call(
            mcx,
            Some(stmt),
            heap_oid,
            REINDEX_REL_PROCESS_TOAST | REINDEX_REL_CHECK_CONSTRAINTS,
            newparams,
        )?;
        if !result {
            ereport(::types_error::NOTICE)
                .errmsg(format!("table \"{relname}\" has no indexes to reindex"))
                .finish(here("ReindexTable"))?;
        }
    }
    Ok(())
}


// ---------------------------------------------------------------------------
// DefineIndex partitioned-table legs (key-subset check + parent-index linking)
// ---------------------------------------------------------------------------

/// `elog(ERROR, msg)` shorthand returning the error value.
fn elog_error(msg: impl Into<String>) -> ::utils_error::PgError {
    ereport(ERROR).errmsg_internal(msg).into_error()
}

/// indexcmds.c DefineIndex partitioned + (unique | exclusion) branch
/// (lines ~963-1098): verify that all columns in the partition key appear in
/// the unique/PK/exclusion index definition, with the same notion of equality.
#[allow(clippy::too_many_arguments)]
fn define_index_partition_keycheck<'mcx>(
    mcx: Mcx<'mcx>,
    rel: &Relation<'mcx>,
    stmt: &IndexStmt<'mcx>,
    exclusion: bool,
    index_info: &::nodes::execnodes::IndexInfo<'mcx>,
    collation_ids: &[Oid],
    opclass_ids: &[Oid],
) -> PgResult<()> {
    use ::nodes::partition::PartitionStrategy;

    let key = partcache_seam::relation_get_partition_key::call(mcx, rel.alias())?
        .ok_or_else(|| elog_error("DefineIndex: partitioned table has no partition key"))?;

    let constraint_type = if stmt.primary {
        "PRIMARY KEY"
    } else if stmt.unique {
        "UNIQUE"
    } else if !stmt.excludeOpNames.is_empty() {
        "EXCLUDE"
    } else {
        return Err(elog_error("unknown constraint type"));
    };

    // Verify that all the columns in the partition key appear in the unique key
    // definition, with the same notion of equality.
    for i in 0..key.partnatts as usize {
        let mut found = false;

        // Identify the equality operator associated with this partkey column.
        // For list and range partitioning, partkeys use btree operator classes;
        // hash partitioning uses hash operator classes. (Keep this in sync with
        // ComputePartitionAttrs!)
        let eq_strategy: i16 = if key.strategy == PartitionStrategy::Hash {
            HTEqualStrategyNumber as i16
        } else {
            BTEqualStrategyNumber as i16
        };

        let ptkey_eqop = lsyscache::get_opfamily_member::call(
            key.partopfamily[i],
            key.partopcintype[i],
            key.partopcintype[i],
            eq_strategy,
        )?;
        if !OidIsValid(ptkey_eqop) {
            return Err(elog_error(format!(
                "missing operator {}({},{}) in partition opfamily {}",
                eq_strategy, key.partopcintype[i], key.partopcintype[i], key.partopfamily[i]
            )));
        }

        // It may be possible to support UNIQUE constraints when partition keys
        // are expressions, but is it worth it? Give up for now.
        if key.partattrs[i] == 0 {
            return Err(ereport(ERROR)
                .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                .errmsg(format!(
                    "unsupported {constraint_type} constraint with partition key definition"
                ))
                .errdetail(format!(
                    "{constraint_type} constraints cannot be used when partition keys include expressions."
                ))
                .into_error());
        }

        // Search the index column(s) for a match.
        for j in 0..index_info.ii_NumIndexKeyAttrs as usize {
            if key.partattrs[i] == index_info.ii_IndexAttrNumbers[j] {
                // Matched the column, now what about the collation and equality op?
                if key.partcollation[i] != collation_ids[j] {
                    continue;
                }

                if let Some((idx_opfamily, idx_opcintype)) =
                    lsyscache::get_opclass_opfamily_and_input_type::call(opclass_ids[j])?
                {
                    let mut idx_eqop = InvalidOid;

                    if stmt.unique && !stmt.iswithoutoverlaps {
                        idx_eqop = lsyscache::get_opfamily_member_for_cmptype::call(
                            idx_opfamily,
                            idx_opcintype,
                            idx_opcintype,
                            COMPARE_EQ as i32,
                        )?;
                    } else if exclusion {
                        idx_eqop = index_info
                            .ii_ExclusionOps
                            .as_ref()
                            .map(|ops| ops[j])
                            .unwrap_or(InvalidOid);
                    }

                    if !OidIsValid(idx_eqop) {
                        let opfam_name = lsyscache::get_opfamily_name::call(mcx, idx_opfamily, false)?
                            .map(|s| s.as_str().to_string())
                            .unwrap_or_default();
                        let am_name =
                            get_am_name_str(lsyscache::get_opfamily_method::call(idx_opfamily)?)?;
                        return Err(ereport(ERROR)
                            .errcode(::types_error::ERRCODE_UNDEFINED_OBJECT)
                            .errmsg(format!(
                                "could not identify an equality operator for type {}",
                                formattype_seam::format_type_be_owned::call(idx_opcintype)?
                            ))
                            .errdetail(format!(
                                "There is no suitable operator in operator family \"{}\" for access method \"{}\".",
                                opfam_name, am_name
                            ))
                            .into_error());
                    }

                    if ptkey_eqop == idx_eqop {
                        found = true;
                        break;
                    } else if exclusion {
                        // We found a match, but it's not an equality operator.
                        // Fail now and explain that the operator is wrong.
                        let att = rel.rd_att.attr((key.partattrs[i] - 1) as usize);
                        let excl_op = index_info
                            .ii_ExclusionOps
                            .as_ref()
                            .map(|ops| ops[j])
                            .unwrap_or(InvalidOid);
                        let opname = lsyscache::get_opname::call(mcx, excl_op)?
                            .map(|s| s.as_str().to_string())
                            .unwrap_or_default();
                        return Err(ereport(ERROR)
                            .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                            .errmsg(format!(
                                "cannot match partition key to index on column \"{}\" using non-equal operator \"{}\"",
                                String::from_utf8_lossy(att.attname.name_str()),
                                opname
                            ))
                            .into_error());
                    }
                }
            }
        }

        if !found {
            let att = rel.rd_att.attr((key.partattrs[i] - 1) as usize);
            return Err(ereport(ERROR)
                .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
                .errmsg("unique constraint on partitioned table must include all partitioning columns")
                .errdetail(format!(
                    "{constraint_type} constraint on table \"{}\" lacks column \"{}\" which is part of the partition key.",
                    rel.rd_rel.relname.as_str(),
                    String::from_utf8_lossy(att.attname.name_str())
                ))
                .into_error());
        }
    }

    Ok(())
}

/// `IndexSetParentIndex(partitionIdx, parentOid)` (indexcmds.c:4443).
///
/// Set or clear the parent-index link of `partition_idx`: detect an existing
/// `pg_inherits` row, then insert (`StoreSingleInheritance`), delete
/// (`DeleteInheritsTuple`), or leave it as-is; set the parent's
/// `relhassubclass` when a parent is added; update the partition's
/// `relispartition`; and add/remove the `DEPENDENCY_PARTITION_{PRI,SEC}` pg_depend
/// rows. A no-op (already in the right state) skips the dependency churn and the
/// `CommandCounterIncrement`.
pub fn IndexSetParentIndex<'mcx>(
    mcx: Mcx<'mcx>,
    partition_idx: &Relation<'mcx>,
    parent_oid: Oid,
) -> PgResult<()> {
    use ::types_catalog::catalog_dependency::{DEPENDENCY_PARTITION_PRI, DEPENDENCY_PARTITION_SEC};

    let part_relid = partition_idx.rd_id;

    // Make sure this is an index (Assert in C).
    debug_assert!(
        partition_idx.rd_rel.relkind == RELKIND_INDEX
            || partition_idx.rd_rel.relkind == RELKIND_PARTITIONED_INDEX
    );

    // Scan pg_inherits for a row linking our index to some parent (inhseqno = 1).
    // `has_superclass` reports whether such a row exists; the partition-index
    // tree only ever has a single (seqno = 1) parent link, so that suffices to
    // distinguish the insert / delete / already-linked cases.
    let has_parent_row = inherits_seam::has_superclass::call(part_relid)?;

    let fix_dependencies: bool;
    if !has_parent_row {
        if !OidIsValid(parent_oid) {
            // No pg_inherits row, and no parent wanted: nothing to do.
            fix_dependencies = false;
        } else {
            inherits_seam::store_single_inheritance::call(part_relid, parent_oid, 1)?;
            fix_dependencies = true;
        }
    } else if !OidIsValid(parent_oid) {
        // There exists a pg_inherits row, which we want to clear; do so.
        inherits_seam::delete_inherits_tuple::call(part_relid, InvalidOid, false, None)?;
        fix_dependencies = true;
    } else {
        // A pg_inherits row exists and a parent is wanted. If it names the same
        // parent we're good (already in the right state); a different parent
        // would be a corrupt catalog, which our callers never produce.
        fix_dependencies = false;
    }

    // Set relhassubclass if an index partition has been added to the parent.
    if OidIsValid(parent_oid) {
        lmgr_seam::lock_relation_oid::call(parent_oid, ShareUpdateExclusiveLock_v())?.keep();
        tablecmds_seam::set_relation_has_subclass::call(mcx, parent_oid, true)?;
    }

    // Set relispartition correctly on the partition.
    tablecmds_seam::update_relispartition_catalog::call(part_relid, OidIsValid(parent_oid))?;

    if fix_dependencies {
        // Insert/delete pg_depend rows.
        if OidIsValid(parent_oid) {
            let part_idx = ObjectAddress {
                classId: RELATION_RELATION_ID,
                objectId: part_relid,
                objectSubId: 0,
            };
            let parent_idx = ObjectAddress {
                classId: RELATION_RELATION_ID,
                objectId: parent_oid,
                objectSubId: 0,
            };
            let partition_tbl = ObjectAddress {
                classId: RELATION_RELATION_ID,
                objectId: partition_idx
                    .rd_index
                    .as_ref()
                    .map(|i| i.indrelid)
                    .unwrap_or(InvalidOid),
                objectSubId: 0,
            };
            depend_seam::recordDependencyOn::call(mcx, &part_idx, &parent_idx, DEPENDENCY_PARTITION_PRI)?;
            depend_seam::recordDependencyOn::call(
                mcx,
                &part_idx,
                &partition_tbl,
                DEPENDENCY_PARTITION_SEC,
            )?;
        } else {
            depend_seam::deleteDependencyRecordsForClass::call(
                RELATION_RELATION_ID,
                part_relid,
                RELATION_RELATION_ID,
                DEPENDENCY_PARTITION_PRI.0,
            )?;
            depend_seam::deleteDependencyRecordsForClass::call(
                RELATION_RELATION_ID,
                part_relid,
                RELATION_RELATION_ID,
                DEPENDENCY_PARTITION_SEC.0,
            )?;
        }

        // Make our updates visible.
        xact_seam::command_counter_increment::call()?;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// small helpers
// ---------------------------------------------------------------------------

fn vec_oid(n: i32) -> Vec<Oid> {
    vec![InvalidOid; n.max(0) as usize]
}

fn amerr(what: &str, amname: &str) -> ::utils_error::PgError {
    ereport(ERROR)
        .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
        .errmsg(format!("access method \"{amname}\" {what}"))
        .into_error()
}

fn virtual_gencol_error(stmt: &IndexStmt<'_>) -> ::utils_error::PgError {
    let msg = if stmt.primary {
        "primary keys on virtual generated columns are not supported"
    } else if stmt.isconstraint {
        "unique constraints on virtual generated columns are not supported"
    } else {
        "indexes on virtual generated columns are not supported"
    };
    ereport(ERROR)
        .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
        .errmsg(msg)
        .into_error()
}

fn virtual_gencol_error_expr(stmt: &IndexStmt<'_>) -> ::utils_error::PgError {
    let msg = if stmt.isconstraint {
        "unique constraints on virtual generated columns are not supported"
    } else {
        "indexes on virtual generated columns are not supported"
    };
    ereport(ERROR)
        .errcode(::types_error::ERRCODE_FEATURE_NOT_SUPPORTED)
        .errmsg(msg)
        .into_error()
}

/// `bms_union` accumulation helper for the two `pull_varattnos` results, each an
/// `Option<PgBox<Bitmapset>>` (the C `Bitmapset *`, NULL == empty).
fn bms_union_opt<'mcx>(
    mcx: Mcx<'mcx>,
    a: Option<::mcx::PgBox<'mcx, ::nodes::Bitmapset<'mcx>>>,
    b: Option<::mcx::PgBox<'mcx, ::nodes::Bitmapset<'mcx>>>,
) -> PgResult<Option<::mcx::PgBox<'mcx, ::nodes::Bitmapset<'mcx>>>> {
    match (a, b) {
        (None, x) => Ok(x),
        (x, None) => Ok(x),
        (Some(a), Some(b)) => Ok(bms_union(mcx, Some(&a), Some(&b))?),
    }
}

/// `MyDatabaseTableSpace` (globals.c) — the database's default tablespace OID.
fn my_database_tablespace() -> PgResult<Oid> {
    tablespace_globals_seams::MyDatabaseTableSpace::call()
}

/// `allowSystemTableMods` (globals.c).
fn allow_system_table_mods() -> bool {
    ::guc_seams::allow_system_table_mods::call()
}

/// `stmt->relation && !stmt->relation->inh` (the recursion-declined-but-
/// partitions-exist invalidation predicate).
fn relation_inh_declined(stmt: &IndexStmt<'_>) -> bool {
    match index_stmt_relation(stmt) {
        Some(rv) => !rv.inh,
        None => false,
    }
}

/// `!stmt->relation || stmt->relation->inh` (recurse-into-partitions predicate).
fn relation_should_recurse(stmt: &IndexStmt<'_>) -> bool {
    match index_stmt_relation(stmt) {
        Some(rv) => rv.inh,
        None => true,
    }
}

fn index_stmt_relation<'a, 'mcx>(stmt: &'a IndexStmt<'mcx>) -> Option<&'a RangeVar<'mcx>> {
    stmt.relation.as_ref().and_then(|n| match n.node_tag() {
        ntag::T_RangeVar => Some(n.expect_rangevar()),
        _ => None,
    })
}

/// `(IndexElem *) lfirst(...)` — read an `IndexElem` out of a name-list `Node`.
fn node_as_index_elem<'a, 'mcx>(node: &'a Node<'mcx>) -> &'a IndexElem<'mcx> {
    match node.node_tag() {
        ntag::T_IndexElem => node.expect_indexelem(),
        _ => panic!("DefineIndex: indexParams entry is not an IndexElem"),
    }
}

/// `ErrorLocation` for `ereport(...).finish(...)` in this module.
pub(crate) fn here(funcname: &'static str) -> ::types_error::pg_error::ErrorLocation {
    ::types_error::pg_error::ErrorLocation::new("../src/backend/commands/indexcmds.c", 0, funcname)
}

/// `RelationGetPartitionDesc(rel, true)->nparts != 0` (indexcmds.c:1232-1234).
fn relation_has_partitions<'mcx>(mcx: Mcx<'mcx>, rel: &Relation<'mcx>) -> PgResult<bool> {
    if rel.rd_rel.relkind != RELKIND_PARTITIONED_TABLE {
        return Ok(false);
    }
    let pd = partdesc::RelationGetPartitionDesc(mcx, rel, true)?;
    Ok(pd.nparts != 0)
}

/// Install this unit's outward seams.
pub fn init_seams() {
    // makeObjectName(name1, name2, label) — name2/label are non-null at the
    // pg_constraint call sites (ChooseConstraintName), matching the &str seam.
    indexcmds_seams::make_object_name::set(|name1, name2, label| {
        // The seam flattens C's `const char *name2`/`const char *label` (both of
        // which may be NULL) to `&str`; an empty value is the NULL case, so the
        // corresponding separating underscore is omitted. E.g. `makeArrayTypeName`
        // calls `makeObjectName("", typeName, NULL)` for the no-suffix array name,
        // which must yield `_typeName` (not `_typeName_`); callers like
        // `ChooseConstraintName` for a domain constraint pass NULL name2 → empty.
        let name2 = if name2.is_empty() { None } else { Some(name2) };
        let label = if label.is_empty() { None } else { Some(label) };
        choosers::makeObjectName(name1, name2, label)
    });

    // GetDefaultOpClass(type_id, am_id) lives in indexcmds.c; the canonical
    // public surface is lsyscache's get_default_opclass convenience wrapper, so
    // the owner installs that seam here.
    lsyscache_seams::get_default_opclass::set(opclass::GetDefaultOpClass);

    // GetOperatorFromCompareType(opclass, rhstype, cmptype) -> (op, strat).
    indexcmds_seams::get_operator_from_compare_type::set(
        |opclass, rhstype, cmptype| {
            let mut op = InvalidOid;
            let mut strat: u16 = 0;
            opclass::GetOperatorFromCompareType(opclass, rhstype, cmptype, &mut op, &mut strat)?;
            Ok((op, strat))
        },
    );

    // DefineIndex(tableId, stmt, ...) — used by the bootstrap (BKI) grammar's
    // DECLARE [UNIQUE] INDEX actions (with skip_build = true).
    indexcmds_seams::define_index::set(|mcx, args| {
        DefineIndex(
            mcx,
            args.table_id,
            &args.stmt,
            args.index_relation_id,
            args.parent_index_id,
            args.parent_constraint_id,
            args.total_parts,
            args.is_alter_table,
            args.check_rights,
            args.check_not_in_use,
            args.skip_build,
            args.quiet,
        )
    });

    // DefineIndex — lifetime-generic form for ALTER TABLE ATExecAddIndex.
    indexcmds_seams::define_index_full::set(|mcx, args| {
        DefineIndex(
            mcx,
            args.table_id,
            &args.stmt,
            args.index_relation_id,
            args.parent_index_id,
            args.parent_constraint_id,
            args.total_parts,
            args.is_alter_table,
            args.check_rights,
            args.check_not_in_use,
            args.skip_build,
            args.quiet,
        )
    });

    indexcmds_seams::check_index_compatible::set(|mcx, old_id, stmt| {
        check_index_compatible_stmt(mcx, old_id, stmt)
    });

    // --- ProcessUtilitySlow CREATE INDEX arm (utility.c:1455-1560) ---
    // The three CREATE-INDEX dispatch seams the command owner installs.
    utility_out_seams::range_var_get_relid_owns_relation::set(
        utility_range_var_get_relid_owns_relation,
    );
    utility_out_seams::create_index_count_partitions::set(
        create_index_count_partitions,
    );
    utility_out_seams::define_index::set(define_index_dispatch_arm);
    utility_out_seams::exec_reindex::set(exec_reindex_dispatch_arm);
}

/// `ExecReindex(pstate, (ReindexStmt *) parsetree, isTopLevel)` — the
/// `T_ReindexStmt` arm of `ProcessUtilitySlow`. Unwrap the node and dispatch.
fn exec_reindex_dispatch_arm<'mcx>(
    mcx: Mcx<'mcx>,
    pstate: &mut ::nodes::parsestmt::ParseState<'mcx>,
    parsetree: &Node<'mcx>,
    is_top_level: bool,
) -> PgResult<()> {
    let stmt = match parsetree.node_tag() {
        t if t == ntag::T_ReindexStmt => parsetree.expect_reindexstmt(),
        _ => panic!("exec_reindex: parsetree is not a ReindexStmt"),
    };
    ExecReindex(mcx, pstate, stmt, is_top_level)
}

/// `RangeVarGetRelidExtended(stmt->relation, lockmode, 0,
/// RangeVarCallbackOwnsRelation, NULL)` (utility.c) — resolve+lock the CREATE
/// INDEX target. Marshals the parse `RangeVar` node and delegates to the
/// namespace owner.
fn utility_range_var_get_relid_owns_relation<'mcx>(
    mcx: Mcx<'mcx>,
    relation: ::nodes::nodes::NodePtr<'mcx>,
    lockmode: ::types_storage::lock::LOCKMODE,
) -> PgResult<Oid> {
    let rv = match relation.node_tag() {
        ntag::T_RangeVar => relation.expect_rangevar(),
        _ => unreachable!(
            "range_var_get_relid_owns_relation: not a RangeVar node: {}",
            relation.node_tag()
        ),
    };
    catalog_namespace::RangeVarGetRelidOwnsRelation(mcx, rv, lockmode)
}

/// utility.c:1490-1525 — CREATE INDEX on a partitioned table recurses to
/// partitions; lock them early, validate each partition's relkind, and count
/// the partitions so `DefineIndex` need not redo the `find_all_inheritors`
/// search. Returns the partition count, or -1 for a non-partitioned target.
fn create_index_count_partitions<'mcx>(
    mcx: Mcx<'mcx>,
    relid: Oid,
    stmt: ::nodes::nodes::NodePtr<'mcx>,
    lockmode: ::types_storage::lock::LOCKMODE,
) -> PgResult<i32> {
    let index_stmt = match stmt.node_tag() {
        ntag::T_IndexStmt => stmt.expect_indexstmt(),
        _ => unreachable!(
            "create_index_count_partitions: not an IndexStmt node: {}",
            stmt.node_tag()
        ),
    };
    let rv = match index_stmt_relation(index_stmt) {
        Some(rv) => rv,
        None => return Ok(-1),
    };

    if !(rv.inh && lsyscache::get_rel_relkind::call(relid)? == RELKIND_PARTITIONED_TABLE) {
        return Ok(-1);
    }

    let relname = rv
        .relname
        .as_ref()
        .map(|s| s.as_str())
        .unwrap_or_default();
    let unique_or_primary = index_stmt.unique || index_stmt.primary;

    let inheritors =
        pg_inherits_seams::find_all_inheritors::call(mcx, relid, lockmode)?;
    for &partrelid in inheritors.iter() {
        let relkind = lsyscache::get_rel_relkind::call(partrelid)?;
        if relkind != RELKIND_RELATION
            && relkind != RELKIND_MATVIEW
            && relkind != RELKIND_PARTITIONED_TABLE
            && relkind != RELKIND_FOREIGN_TABLE
        {
            ereport(ERROR)
                .errmsg(format!(
                    "unexpected relkind \"{}\" on partition \"{}\"",
                    relkind as char, relname
                ))
                .finish(here("create_index_count_partitions"))?;
        }
        if relkind == RELKIND_FOREIGN_TABLE && unique_or_primary {
            ereport(ERROR)
                .errcode(::types_error::ERRCODE_WRONG_OBJECT_TYPE)
                .errmsg(format!(
                    "cannot create unique index on partitioned table \"{}\"",
                    relname
                ))
                .errdetail(format!(
                    "Table \"{}\" contains partitions that are foreign tables.",
                    relname
                ))
                .finish(here("create_index_count_partitions"))?;
        }
    }
    // count direct and indirect children, but not rel
    Ok(inheritors.len() as i32 - 1)
}

/// `DefineIndex(relid, stmt, InvalidOid, InvalidOid, InvalidOid, nparts,
/// is_alter_table, true, true, false, false)` (utility.c) — the CREATE INDEX
/// command. Marshals the transformed `IndexStmt` node and delegates.
fn define_index_dispatch_arm<'mcx>(
    mcx: Mcx<'mcx>,
    relid: Oid,
    stmt: ::nodes::nodes::NodePtr<'mcx>,
    nparts: i32,
    is_alter_table: bool,
) -> PgResult<ObjectAddress> {
    let stmt_tag = stmt.node_tag();
    let stmt = match ::mcx::PgBox::into_inner(stmt).into_indexstmt() {
        Some(s) => s,
        None => unreachable!("define_index: not an IndexStmt node: {}", stmt_tag),
    };
    DefineIndex(
        mcx,
        relid,
        &stmt,
        InvalidOid,
        InvalidOid,
        InvalidOid,
        nparts,
        is_alter_table,
        true,
        true,
        false,
        false,
    )
}

// ===========================================================================
// reloptions / attoptions text[] producers (the Datum-bridge for CREATE INDEX)
// ===========================================================================

/// Build the reloptions-crate [`DefElem`](common_reloptions::DefElem)
/// working view from a parser `DefElem` node (the `T_DefElem` payload of a
/// `WITH (...)` / `OPCLASS (...)` option). The value node is projected to the
/// `DefElemArg` the reloptions `defGetString` seam reads (`def->arg == NULL` is
/// `None`).
fn reloptions_view_defel(
    def: &DefElem<'_>,
) -> PgResult<common_reloptions::DefElem> {
    use ::define_seams::DefElemArg;
    // Mirror `defGetString`/`defGetBoolean` (define.c): every node form that
    // those accessors render must round-trip through the `DefElemArg`
    // projection, not collapse into `A_Star`. Bare identifiers such as
    // `buffering = off` / `auto` arrive as a `T_TypeName` (the grammar's
    // `def_arg: func_type` production) and a qualified name as a `T_List`;
    // both render to their textual form, exactly as `defGetString` does.
    let arg = match def.arg.as_deref() {
        None => None,
        Some(node) => Some(match node.node_tag() {
            ntag::T_Integer => DefElemArg::Integer(node.expect_integer().ival as i64),
            ntag::T_Float => DefElemArg::Float(node.expect_float().fval.as_str().to_string()),
            ntag::T_Boolean => DefElemArg::Boolean(node.expect_boolean().boolval),
            ntag::T_String => DefElemArg::String(node.expect_string().sval.as_str().to_string()),
            // case T_TypeName: return TypeNameToString((TypeName *) def->arg);
            ntag::T_TypeName => DefElemArg::TypeName(type_name_to_string(node.expect_typename())?),
            // case T_List: return NameListToString((List *) def->arg);
            ntag::T_List => DefElemArg::List(name_list_to_string(node.expect_list())?),
            // case T_A_Star: return pstrdup("*");
            ntag::T_A_Star => DefElemArg::AStar,
            other => {
                return Err(elog_error(format!("unrecognized node type: {}", other)))
            }
        }),
    };
    Ok(common_reloptions::DefElem::new(
        def.defnamespace.as_deref(),
        def.defname.as_deref().unwrap_or(""),
        arg,
    ))
}

/// `TypeNameToString(typeName)` for the `defGetString` `T_TypeName` case
/// (parse_type.c). A reloptions `def->arg` `TypeName` is always a parsed
/// identifier carrying `names` (never an internal `typeOid`-only node), so the
/// `format_type_be` fallback is unreachable here.
fn type_name_to_string(tn: &::nodes::rawnodes::TypeName<'_>) -> PgResult<String> {
    if tn.names.is_empty() {
        return Err(elog_error(
            "reloption TypeName carries no name (internal typeOid-only form unsupported here)",
        ));
    }
    let mut out = String::new();
    for (i, name) in tn.names.iter().enumerate() {
        if i != 0 {
            out.push('.');
        }
        let node: &Node = name;
        match node.node_tag() {
            ntag::T_String => out.push_str(node.expect_string().sval.as_str()),
            other => return Err(elog_error(format!("unrecognized node type: {}", other))),
        }
    }
    if tn.pct_type {
        out.push_str("%TYPE");
    }
    if !tn.arrayBounds.is_empty() {
        out.push_str("[]");
    }
    Ok(out)
}

/// `NameListToString(names)` (namespace.c) for the `defGetString` `T_List` case:
/// `'.'`-joined `String` cells, `A_Star` rendered as `*`.
fn name_list_to_string(names: &[::nodes::nodes::NodePtr<'_>]) -> PgResult<String> {
    let mut out = String::new();
    for (i, name) in names.iter().enumerate() {
        if i != 0 {
            out.push('.');
        }
        let node: &Node = name;
        match node.node_tag() {
            ntag::T_String => out.push_str(node.expect_string().sval.as_str()),
            ntag::T_A_Star => out.push('*'),
            other => return Err(elog_error(format!("unrecognized node type: {}", other))),
        }
    }
    Ok(out)
}

/// Build the reloptions-crate `DefElem` view list from a parser option list (a
/// `List *` of `DefElem` — `IndexStmt.options` or `IndexElem.opclassopts`).
fn reloptions_view_list(
    options: &[::nodes::nodes::NodePtr<'_>],
) -> PgResult<Vec<common_reloptions::DefElem>> {
    options
        .iter()
        .map(|opt| {
            let opt: &Node = opt;
            let def = match opt.node_tag() {
                t if t == ntag::T_DefElem => opt.expect_defelem(),
                _ => panic!("reloptions option list element is not a DefElem"),
            };
            reloptions_view_defel(def)
        })
        .collect()
}

/// `reloptions = transformRelOptions((Datum) 0, stmt->options, NULL, NULL,
/// false, false); (void) index_reloptions(amoptions, reloptions, true);`
/// (indexcmds.c DefineIndex). Build the index `text[]` reloptions varlena image
/// (the bytes `pg_class.reloptions` stores) and validate it through the AM's
/// option parser; the caller lowers the bytes onto the `Datum::ByRef` lane.
fn transform_index_reloptions_byref<'mcx>(
    mcx: Mcx<'mcx>,
    options: &[::nodes::nodes::NodePtr<'mcx>],
    amhandler: Oid,
) -> PgResult<PgVec<'mcx, u8>> {
    let def_list = reloptions_view_list(options)?;
    // namspace = NULL, validnsps = NULL, acceptOidsOff = false, isReset = false.
    let bytes = common_reloptions::transformRelOptionsBytes(
        mcx, None, &def_list, None, None, false, false,
    )?;
    let bytes = bytes.expect("CREATE INDEX WITH (...) has at least one option");
    // (void) index_reloptions(amoptions, reloptions, true): validate; the parsed
    // struct is discarded, only the ereport(ERROR) on a bad option matters.
    let _ = common_reloptions::index_reloptions(mcx, amhandler, Some(&bytes), true)?;
    Ok(bytes)
}

/// `opclassOptions[attn] = transformRelOptions((Datum) 0,
/// attribute->opclassopts, NULL, NULL, false, false);` (indexcmds.c
/// ComputeIndexAttrs). Build the per-column attoptions `text[]` varlena image
/// (the bytes `pg_attribute.attoptions` stores); the caller lowers it onto the
/// `Datum::ByRef` lane that `index_create` / `AppendAttributeTuples` consume.
pub(crate) fn transform_attoptions_byref<'mcx>(
    mcx: Mcx<'mcx>,
    opclassopts: &[::nodes::nodes::NodePtr<'mcx>],
) -> PgResult<PgVec<'mcx, u8>> {
    let def_list = reloptions_view_list(opclassopts)?;
    let bytes = common_reloptions::transformRelOptionsBytes(
        mcx, None, &def_list, None, None, false, false,
    )?;
    Ok(bytes.expect("OPCLASS (...) has at least one option"))
}
