[package]
name = "adt_misc"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
datum = { path = "../../../../_support/types/datum" }
mcx = { path = "../../../../_support/mcx" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
fmgr_seams = { path = "../../fmgr/fmgr_seams" }
funcapi = { path = "../../fmgr/funcapi" }
arrayfuncs = { path = "../arrayfuncs" }
arrayutils = { path = "../arrayutils" }
detoast_seams = { path = "../../../access/common/detoast_seams" }
heaptuple = { path = "../../../access/common/heaptuple" }
lsyscache = { path = "../../cache/lsyscache" }
parse_utilcmd = { path = "../../../parser/parse_utilcmd" }
adt_numeric = { path = "../numeric" }
mbutils = { path = "../../mb/mbutils" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
types_rel = { path = "../../../../_support/types/rel" }
types_scan = { path = "../../../../_support/types/types_scan" }
genam_seams = { path = "../../../access/index/genam_seams" }
table = { path = "../../../access/table/table" }
dbcommands = { path = "../../../commands/dbcommands" }
init_small = { path = "../../init/init_small" }
varlena = { path = "../varlena" }
