[package]
name = "funcapi"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
datum = { path = "../../../../_support/types/datum" }
mcx = { path = "../../../../_support/mcx" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
fmgr = { package = "types_fmgr", path = "../../../../_support/types/fmgr" }
nodes = { package = "types_nodes", path = "../../../../_support/types/nodes" }
tupdesc = { path = "../../../access/common/tupdesc" }
format_type = { path = "../../adt/format_type" }
lsyscache = { path = "../../cache/lsyscache" }
syscache_seams = { path = "../../cache/syscache_seams" }
typcache_seams = { path = "../../cache/typcache_seams" }
arrayfuncs = { path = "../../adt/arrayfuncs" }
detoast_seams = { path = "../../../access/common/detoast_seams" }
varlena = { path = "../../adt/varlena" }

[dev-dependencies]
catalog_seams = { path = "../../../catalog/catalog_seams" }
