[package]
name = "tqueue"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "tqueue"
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../../_support/mcx" }
heaptuple = { path = "../../access/common/heaptuple" }
exectuples = { path = "../exectuples" }
types_slot = { path = "../../../_support/types/types_slot" }
types_tuple = { path = "../../../_support/types/types_tuple" }
elog = { path = "../../utils/error/elog" }
shm_mq = { path = "../../storage/ipc/shm_mq" }
types_error = { path = "../../../_support/types/types_error" }
init_small = { path = "../../utils/init/init_small" }
latch = { path = "../../storage/ipc/latch" }
types_storage = { path = "../../../_support/types/types_storage" }

[dev-dependencies]
ipc_seams = { path = "../../storage/ipc/ipc_seams" }
lmgr_proc = { path = "../../storage/lmgr/lmgr_proc" }
lmgr_proc_seams = { path = "../../storage/lmgr/lmgr_proc_seams" }
pg_sema_seams = { path = "../../port/pg_sema_seams" }
postgres_seams = { path = "../../tcop/postgres_seams" }
s_lock_seams = { path = "../../storage/lmgr/s_lock_seams" }
shmem_seams = { path = "../../storage/ipc/shmem_seams" }
types_core = { path = "../../../_support/types/types_core" }
waitevent_seams = { path = "../../utils/activity/waitevent_seams" }
waiteventset = { path = "../../storage/ipc/waiteventset" }
