[package]
name = "network_spgist"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
adt_network = { path = "../network" }
datum = { path = "../../../../_support/types/datum" }
mcx = { path = "../../../../_support/mcx" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
types_scan = { path = "../../../../_support/types/types_scan" }
types_spgist = { path = "../../../../_support/types/types_spgist" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
