[package]
name = "adt_tsginidx"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
datum = { path = "../../../../_support/types/datum" }
mcx = { path = "../../../../_support/mcx" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
adt_tsvector_core = { path = "../tsvector_core" }
gin_vocab = { path = "../../../access/gin/gin_vocab" }

[dev-dependencies]
adt_tsquery_core = { path = "../tsquery_core" }
