[package]
name = "bloom"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "bloom"
path = "src/lib.rs"

[dependencies]
mcx = { path = "../../_support/mcx" }
datum = { path = "../../_support/types/datum" }
types_core = { path = "../../_support/types/types_core" }
types_error = { path = "../../_support/types/types_error" }
types_fmgr = { path = "../../_support/types/fmgr" }
types_tuple = { path = "../../_support/types/types_tuple" }
types_rel = { path = "../../_support/types/rel" }
types_storage = { path = "../../_support/types/types_storage" }
types_relscan = { path = "../../backend/access/index/relscan" }
types_bloom = { path = "../../_support/types/types_bloom" }
types_nbtree = { path = "../../_support/types/types_nbtree" }
nbtree = { path = "../../backend/access/nbtree/nbtree" }
xact = { path = "../../backend/access/transam/xact" }
postgres_seams = { path = "../../backend/tcop/postgres_seams" }
types_scan = { path = "../../_support/types/types_scan" }
bufmgr = { path = "../../backend/storage/buffer/bufmgr" }
bufmgr_seams = { path = "../../backend/storage/buffer/bufmgr_seams" }
generic_xlog = { path = "../../backend/access/transam/generic_xlog" }
freespace = { path = "../../backend/storage/freespace/freespace" }
fmgr_core = { path = "../../backend/utils/fmgr/fmgr_core" }
fmgr_seams = { path = "../../backend/utils/fmgr/fmgr_seams" }
lsyscache = { path = "../../backend/utils/cache/lsyscache" }
tidbitmap = { path = "../../backend/nodes/tidbitmap" }
vacuum_seams = { path = "../../backend/commands/vacuum_seams" }
init_small = { path = "../../backend/utils/init/init_small" }
dfmgr = { path = "../../backend/utils/fmgr/dfmgr" }
adt_regproc = { path = "../../backend/utils/adt/regproc" }
syscache_seams = { path = "../../backend/utils/cache/syscache_seams" }
index_amvalidate = { path = "../../backend/access/index/index_amvalidate" }
elog = { path = "../../backend/utils/error/elog" }
