[package]
name = "launcher"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "launcher"
path = "src/lib.rs"

[dependencies]
guc_tables = { path = "../../utils/misc/guc_tables" }
init_small = { path = "../../utils/init/init_small" }
launcher_seams = { path = "../launcher_seams" }
