//! Generated catalog foreign-key data: a 1:1 transcription of
//! `sys_fk_relationships[]` from `src/include/catalog/system_fk_info.h` (itself
//! generated by `genbki.pl`), and the builder that renders it into
//! [`CatalogForeignKeyRow`]s for the `catalog_foreign_keys` data seam.
//!
//! Each entry is `(fk_table, fk_columns, pk_table, pk_columns, is_array,
//! is_opt)` exactly as in the header. The `{a, b}` brace literals are the C
//! strings that `pg_get_catalog_foreign_keys()` (misc.c:539/544) feeds to
//! `array_in` to build `text[]` values; [`build_sys_fk_rows`] reproduces that
//! `array_in` for these identifier-only literals (strip the braces, split on
//! commas, trim ASCII whitespace) without an fmgr dispatch.

use adt_misc::CatalogForeignKeyRow;
use types_core::Oid;

/// `sys_fk_relationships[]` (catalog/system_fk_info.h): one row per system
/// catalog foreign-key relationship. Columns: referencing catalog OID,
/// referencing column name(s) literal, referenced catalog OID, referenced
/// column name(s) literal, `is_array` (last fk column is an array), `is_opt`
/// (fk column may be zero).
const SYS_FK_RELATIONSHIPS: &[(Oid, &str, Oid, &str, bool, bool)] = &[
	    (1255, "{pronamespace}", 2615, "{oid}", false, false),
	    (1255, "{proowner}", 1260, "{oid}", false, false),
	    (1255, "{prolang}", 2612, "{oid}", false, false),
	    (1255, "{provariadic}", 1247, "{oid}", false, true),
	    (1255, "{prosupport}", 1255, "{oid}", false, true),
	    (1255, "{prorettype}", 1247, "{oid}", false, false),
	    (1255, "{proargtypes}", 1247, "{oid}", true, false),
	    (1255, "{proallargtypes}", 1247, "{oid}", true, false),
	    (1255, "{protrftypes}", 1247, "{oid}", true, false),
	    (1247, "{typnamespace}", 2615, "{oid}", false, false),
	    (1247, "{typowner}", 1260, "{oid}", false, false),
	    (1247, "{typrelid}", 1259, "{oid}", false, true),
	    (1247, "{typsubscript}", 1255, "{oid}", false, true),
	    (1247, "{typelem}", 1247, "{oid}", false, true),
	    (1247, "{typarray}", 1247, "{oid}", false, true),
	    (1247, "{typinput}", 1255, "{oid}", false, false),
	    (1247, "{typoutput}", 1255, "{oid}", false, false),
	    (1247, "{typreceive}", 1255, "{oid}", false, true),
	    (1247, "{typsend}", 1255, "{oid}", false, true),
	    (1247, "{typmodin}", 1255, "{oid}", false, true),
	    (1247, "{typmodout}", 1255, "{oid}", false, true),
	    (1247, "{typanalyze}", 1255, "{oid}", false, true),
	    (1247, "{typbasetype}", 1247, "{oid}", false, true),
	    (1247, "{typcollation}", 3456, "{oid}", false, true),
	    (1249, "{attrelid}", 1259, "{oid}", false, false),
	    (1249, "{atttypid}", 1247, "{oid}", false, true),
	    (1249, "{attcollation}", 3456, "{oid}", false, true),
	    (1259, "{relnamespace}", 2615, "{oid}", false, false),
	    (1259, "{reltype}", 1247, "{oid}", false, true),
	    (1259, "{reloftype}", 1247, "{oid}", false, true),
	    (1259, "{relowner}", 1260, "{oid}", false, false),
	    (1259, "{relam}", 2601, "{oid}", false, true),
	    (1259, "{reltablespace}", 1213, "{oid}", false, true),
	    (1259, "{reltoastrelid}", 1259, "{oid}", false, true),
	    (1259, "{relrewrite}", 1259, "{oid}", false, true),
	    (2604, "{adrelid}", 1259, "{oid}", false, false),
	    (2604, "{adrelid, adnum}", 1249, "{attrelid, attnum}", false, false),
	    (2606, "{connamespace}", 2615, "{oid}", false, false),
	    (2606, "{conrelid}", 1259, "{oid}", false, true),
	    (2606, "{contypid}", 1247, "{oid}", false, true),
	    (2606, "{conindid}", 1259, "{oid}", false, true),
	    (2606, "{conparentid}", 2606, "{oid}", false, true),
	    (2606, "{confrelid}", 1259, "{oid}", false, true),
	    (2606, "{conpfeqop}", 2617, "{oid}", true, false),
	    (2606, "{conppeqop}", 2617, "{oid}", true, false),
	    (2606, "{conffeqop}", 2617, "{oid}", true, false),
	    (2606, "{conexclop}", 2617, "{oid}", true, false),
	    (2606, "{conrelid, conkey}", 1249, "{attrelid, attnum}", true, true),
	    (2606, "{confrelid, confkey}", 1249, "{attrelid, attnum}", true, false),
	    (2611, "{inhrelid}", 1259, "{oid}", false, false),
	    (2611, "{inhparent}", 1259, "{oid}", false, false),
	    (2610, "{indexrelid}", 1259, "{oid}", false, false),
	    (2610, "{indrelid}", 1259, "{oid}", false, false),
	    (2610, "{indcollation}", 3456, "{oid}", true, true),
	    (2610, "{indclass}", 2616, "{oid}", true, false),
	    (2610, "{indrelid, indkey}", 1249, "{attrelid, attnum}", true, true),
	    (2617, "{oprnamespace}", 2615, "{oid}", false, false),
	    (2617, "{oprowner}", 1260, "{oid}", false, false),
	    (2617, "{oprleft}", 1247, "{oid}", false, true),
	    (2617, "{oprright}", 1247, "{oid}", false, false),
	    (2617, "{oprresult}", 1247, "{oid}", false, true),
	    (2617, "{oprcom}", 2617, "{oid}", false, true),
	    (2617, "{oprnegate}", 2617, "{oid}", false, true),
	    (2617, "{oprcode}", 1255, "{oid}", false, true),
	    (2617, "{oprrest}", 1255, "{oid}", false, true),
	    (2617, "{oprjoin}", 1255, "{oid}", false, true),
	    (2753, "{opfmethod}", 2601, "{oid}", false, false),
	    (2753, "{opfnamespace}", 2615, "{oid}", false, false),
	    (2753, "{opfowner}", 1260, "{oid}", false, false),
	    (2616, "{opcmethod}", 2601, "{oid}", false, false),
	    (2616, "{opcnamespace}", 2615, "{oid}", false, false),
	    (2616, "{opcowner}", 1260, "{oid}", false, false),
	    (2616, "{opcfamily}", 2753, "{oid}", false, false),
	    (2616, "{opcintype}", 1247, "{oid}", false, false),
	    (2616, "{opckeytype}", 1247, "{oid}", false, true),
	    (2601, "{amhandler}", 1255, "{oid}", false, false),
	    (2602, "{amopfamily}", 2753, "{oid}", false, false),
	    (2602, "{amoplefttype}", 1247, "{oid}", false, false),
	    (2602, "{amoprighttype}", 1247, "{oid}", false, false),
	    (2602, "{amopopr}", 2617, "{oid}", false, false),
	    (2602, "{amopmethod}", 2601, "{oid}", false, false),
	    (2602, "{amopsortfamily}", 2753, "{oid}", false, true),
	    (2603, "{amprocfamily}", 2753, "{oid}", false, false),
	    (2603, "{amproclefttype}", 1247, "{oid}", false, false),
	    (2603, "{amprocrighttype}", 1247, "{oid}", false, false),
	    (2603, "{amproc}", 1255, "{oid}", false, false),
	    (2612, "{lanowner}", 1260, "{oid}", false, false),
	    (2612, "{lanplcallfoid}", 1255, "{oid}", false, true),
	    (2612, "{laninline}", 1255, "{oid}", false, true),
	    (2612, "{lanvalidator}", 1255, "{oid}", false, true),
	    (2995, "{lomowner}", 1260, "{oid}", false, false),
	    (2613, "{loid}", 2995, "{oid}", false, false),
	    (2600, "{aggfnoid}", 1255, "{oid}", false, false),
	    (2600, "{aggtransfn}", 1255, "{oid}", false, false),
	    (2600, "{aggfinalfn}", 1255, "{oid}", false, true),
	    (2600, "{aggcombinefn}", 1255, "{oid}", false, true),
	    (2600, "{aggserialfn}", 1255, "{oid}", false, true),
	    (2600, "{aggdeserialfn}", 1255, "{oid}", false, true),
	    (2600, "{aggmtransfn}", 1255, "{oid}", false, true),
	    (2600, "{aggminvtransfn}", 1255, "{oid}", false, true),
	    (2600, "{aggmfinalfn}", 1255, "{oid}", false, true),
	    (2600, "{aggsortop}", 2617, "{oid}", false, true),
	    (2600, "{aggtranstype}", 1247, "{oid}", false, false),
	    (2600, "{aggmtranstype}", 1247, "{oid}", false, true),
	    (2619, "{starelid}", 1259, "{oid}", false, false),
	    (2619, "{staop1}", 2617, "{oid}", false, true),
	    (2619, "{staop2}", 2617, "{oid}", false, true),
	    (2619, "{staop3}", 2617, "{oid}", false, true),
	    (2619, "{staop4}", 2617, "{oid}", false, true),
	    (2619, "{staop5}", 2617, "{oid}", false, true),
	    (2619, "{stacoll1}", 3456, "{oid}", false, true),
	    (2619, "{stacoll2}", 3456, "{oid}", false, true),
	    (2619, "{stacoll3}", 3456, "{oid}", false, true),
	    (2619, "{stacoll4}", 3456, "{oid}", false, true),
	    (2619, "{stacoll5}", 3456, "{oid}", false, true),
	    (2619, "{starelid, staattnum}", 1249, "{attrelid, attnum}", false, false),
	    (3381, "{stxrelid}", 1259, "{oid}", false, false),
	    (3381, "{stxnamespace}", 2615, "{oid}", false, false),
	    (3381, "{stxowner}", 1260, "{oid}", false, false),
	    (3381, "{stxrelid, stxkeys}", 1249, "{attrelid, attnum}", true, false),
	    (3429, "{stxoid}", 3381, "{oid}", false, false),
	    (2618, "{ev_class}", 1259, "{oid}", false, false),
	    (2620, "{tgrelid}", 1259, "{oid}", false, false),
	    (2620, "{tgparentid}", 2620, "{oid}", false, true),
	    (2620, "{tgfoid}", 1255, "{oid}", false, false),
	    (2620, "{tgconstrrelid}", 1259, "{oid}", false, true),
	    (2620, "{tgconstrindid}", 1259, "{oid}", false, true),
	    (2620, "{tgconstraint}", 2606, "{oid}", false, true),
	    (2620, "{tgrelid, tgattr}", 1249, "{attrelid, attnum}", true, false),
	    (3466, "{evtowner}", 1260, "{oid}", false, false),
	    (3466, "{evtfoid}", 1255, "{oid}", false, false),
	    (2609, "{classoid}", 1259, "{oid}", false, false),
	    (2605, "{castsource}", 1247, "{oid}", false, false),
	    (2605, "{casttarget}", 1247, "{oid}", false, false),
	    (2605, "{castfunc}", 1255, "{oid}", false, true),
	    (3501, "{enumtypid}", 1247, "{oid}", false, false),
	    (2615, "{nspowner}", 1260, "{oid}", false, false),
	    (2607, "{connamespace}", 2615, "{oid}", false, false),
	    (2607, "{conowner}", 1260, "{oid}", false, false),
	    (2607, "{conproc}", 1255, "{oid}", false, false),
	    (2608, "{classid}", 1259, "{oid}", false, false),
	    (2608, "{refclassid}", 1259, "{oid}", false, false),
	    (1262, "{datdba}", 1260, "{oid}", false, false),
	    (1262, "{dattablespace}", 1213, "{oid}", false, false),
	    (2964, "{setdatabase}", 1262, "{oid}", false, true),
	    (2964, "{setrole}", 1260, "{oid}", false, true),
	    (1213, "{spcowner}", 1260, "{oid}", false, false),
	    (1261, "{roleid}", 1260, "{oid}", false, false),
	    (1261, "{member}", 1260, "{oid}", false, false),
	    (1261, "{grantor}", 1260, "{oid}", false, false),
	    (1214, "{dbid}", 1262, "{oid}", false, true),
	    (1214, "{classid}", 1259, "{oid}", false, false),
	    (1214, "{refclassid}", 1259, "{oid}", false, false),
	    (2396, "{classoid}", 1259, "{oid}", false, false),
	    (3602, "{cfgnamespace}", 2615, "{oid}", false, false),
	    (3602, "{cfgowner}", 1260, "{oid}", false, false),
	    (3602, "{cfgparser}", 3601, "{oid}", false, false),
	    (3603, "{mapcfg}", 3602, "{oid}", false, false),
	    (3603, "{mapdict}", 3600, "{oid}", false, false),
	    (3600, "{dictnamespace}", 2615, "{oid}", false, false),
	    (3600, "{dictowner}", 1260, "{oid}", false, false),
	    (3600, "{dicttemplate}", 3764, "{oid}", false, false),
	    (3601, "{prsnamespace}", 2615, "{oid}", false, false),
	    (3601, "{prsstart}", 1255, "{oid}", false, false),
	    (3601, "{prstoken}", 1255, "{oid}", false, false),
	    (3601, "{prsend}", 1255, "{oid}", false, false),
	    (3601, "{prsheadline}", 1255, "{oid}", false, true),
	    (3601, "{prslextype}", 1255, "{oid}", false, false),
	    (3764, "{tmplnamespace}", 2615, "{oid}", false, false),
	    (3764, "{tmplinit}", 1255, "{oid}", false, true),
	    (3764, "{tmpllexize}", 1255, "{oid}", false, false),
	    (3079, "{extowner}", 1260, "{oid}", false, false),
	    (3079, "{extnamespace}", 2615, "{oid}", false, false),
	    (3079, "{extconfig}", 1259, "{oid}", true, false),
	    (2328, "{fdwowner}", 1260, "{oid}", false, false),
	    (2328, "{fdwhandler}", 1255, "{oid}", false, true),
	    (2328, "{fdwvalidator}", 1255, "{oid}", false, true),
	    (1417, "{srvowner}", 1260, "{oid}", false, false),
	    (1417, "{srvfdw}", 2328, "{oid}", false, false),
	    (1418, "{umuser}", 1260, "{oid}", false, true),
	    (1418, "{umserver}", 1417, "{oid}", false, false),
	    (3118, "{ftrelid}", 1259, "{oid}", false, false),
	    (3118, "{ftserver}", 1417, "{oid}", false, false),
	    (3256, "{polrelid}", 1259, "{oid}", false, false),
	    (3256, "{polroles}", 1260, "{oid}", true, true),
	    (826, "{defaclrole}", 1260, "{oid}", false, false),
	    (826, "{defaclnamespace}", 2615, "{oid}", false, true),
	    (3394, "{classoid}", 1259, "{oid}", false, false),
	    (3596, "{classoid}", 1259, "{oid}", false, false),
	    (3592, "{classoid}", 1259, "{oid}", false, false),
	    (3456, "{collnamespace}", 2615, "{oid}", false, false),
	    (3456, "{collowner}", 1260, "{oid}", false, false),
	    (3350, "{partrelid}", 1259, "{oid}", false, false),
	    (3350, "{partdefid}", 1259, "{oid}", false, true),
	    (3350, "{partclass}", 2616, "{oid}", true, false),
	    (3350, "{partcollation}", 3456, "{oid}", true, true),
	    (3350, "{partrelid, partattrs}", 1249, "{attrelid, attnum}", true, true),
	    (3541, "{rngtypid}", 1247, "{oid}", false, false),
	    (3541, "{rngsubtype}", 1247, "{oid}", false, false),
	    (3541, "{rngmultitypid}", 1247, "{oid}", false, false),
	    (3541, "{rngcollation}", 3456, "{oid}", false, true),
	    (3541, "{rngsubopc}", 2616, "{oid}", false, false),
	    (3541, "{rngcanonical}", 1255, "{oid}", false, true),
	    (3541, "{rngsubdiff}", 1255, "{oid}", false, true),
	    (3576, "{trftype}", 1247, "{oid}", false, false),
	    (3576, "{trflang}", 2612, "{oid}", false, false),
	    (3576, "{trffromsql}", 1255, "{oid}", false, true),
	    (3576, "{trftosql}", 1255, "{oid}", false, true),
	    (2224, "{seqrelid}", 1259, "{oid}", false, false),
	    (2224, "{seqtypid}", 1247, "{oid}", false, false),
	    (6104, "{pubowner}", 1260, "{oid}", false, false),
	    (6237, "{pnpubid}", 6104, "{oid}", false, false),
	    (6237, "{pnnspid}", 2615, "{oid}", false, false),
	    (6106, "{prpubid}", 6104, "{oid}", false, false),
	    (6106, "{prrelid}", 1259, "{oid}", false, false),
	    (6100, "{subdbid}", 1262, "{oid}", false, false),
	    (6100, "{subowner}", 1260, "{oid}", false, false),
	    (6102, "{srsubid}", 6100, "{oid}", false, false),
	    (6102, "{srrelid}", 1259, "{oid}", false, false),
];

/// Reproduce `array_in` for an identifier-only `text[]` literal like
/// `"{adrelid, adnum}"`: strip the surrounding braces, split on commas, trim
/// ASCII whitespace around each element, and collect the raw bytes. These
/// literals contain only catalog column identifiers (no quoting, NULLs or
/// nested arrays), so this faithfully matches what `array_in` would produce for
/// the seam's purposes.
fn array_in_identifiers(literal: &str) -> Vec<Vec<u8>> {
    let bytes = literal.as_bytes();
    // Strip leading '{' and trailing '}'.
    let inner = bytes
        .strip_prefix(b"{")
        .and_then(|b| b.strip_suffix(b"}"))
        .expect("sys_fk_relationships literal must be brace-wrapped");
    inner
        .split(|&c| c == b',')
        .map(|elem| {
            let start = elem.iter().position(|c| !c.is_ascii_whitespace()).unwrap_or(elem.len());
            let end = elem
                .iter()
                .rposition(|c| !c.is_ascii_whitespace())
                .map(|i| i + 1)
                .unwrap_or(start);
            elem[start..end].to_vec()
        })
        .collect()
}

/// Build the full `pg_get_catalog_foreign_keys()` row set from
/// [`SYS_FK_RELATIONSHIPS`] (misc.c:495). One [`CatalogForeignKeyRow`] per
/// entry, with the `fk_columns`/`pk_columns` literals passed through
/// [`array_in_identifiers`] (the `array_in` of misc.c:539/544).
pub fn build_sys_fk_rows() -> Vec<CatalogForeignKeyRow> {
    SYS_FK_RELATIONSHIPS
        .iter()
        .map(|&(fktable, fkcols, pktable, pkcols, is_array, is_opt)| CatalogForeignKeyRow {
            fktable,
            fkcols: array_in_identifiers(fkcols),
            pktable,
            pkcols: array_in_identifiers(pkcols),
            is_array,
            is_opt,
        })
        .collect()
}
