[package]
name = "adt_pg_lsn"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
adt_numeric = { path = "../numeric" }
datum = { path = "../../../../_support/types/datum" }
hashfn = { path = "../../../../common/hashfn" }
mcx = { path = "../../../../_support/mcx" }
pqformat = { path = "../../../libpq/pqformat" }
stringinfo = { path = "../../../../_support/types/stringinfo" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_fmgr = { path = "../../../../_support/types/fmgr" }

[dev-dependencies]
