[package]
name = "indexam"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
mcx = { path = "../../../../_support/mcx" }
datum = { path = "../../../../_support/types/datum" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_rel = { path = "../../../../_support/types/rel" }
types_scan = { path = "../../../../_support/types/types_scan" }
types_snapshot = { path = "../../../../_support/types/snapshot" }
types_slot = { path = "../../../../_support/types/types_slot" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
types_nbtree = { path = "../../../../_support/types/types_nbtree" }
relation_seams = { path = "../../common/relation_seams" }
tableam = { path = "../../table/tableam" }
indexam_seams = { path = "../indexam_seams" }
types_relscan = { path = "../relscan" }
nbtree = { path = "../../nbtree/nbtree" }
hash = { path = "../../hash/hash" }
tidbitmap = { path = "../../../nodes/tidbitmap" }

[dev-dependencies]
types_relscan = { path = "../relscan", features = ["mock"] }
