[package]
name = "catalog_heap"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "catalog_heap"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../_support/types/types_core" }
types_tuple = { path = "../../../_support/types/types_tuple" }
types_error = { path = "../../../_support/types/types_error" }
types_rel = { path = "../../../_support/types/rel" }
datum = { path = "../../../_support/types/datum" }
mcx = { path = "../../../_support/mcx" }
catalog = { path = "../catalog" }
catalog_indexing = { path = "../catalog_indexing" }
catalog_storage = { path = "../catalog_storage" }
heaptuple = { path = "../../access/common/heaptuple" }
table = { path = "../../access/table/table" }
tableam = { path = "../../access/table/tableam" }
relcache = { path = "../../utils/cache/relcache" }
lsyscache = { path = "../../utils/cache/lsyscache" }
lmgr = { path = "../../storage/lmgr/lmgr" }
elog = { path = "../../utils/error/elog" }
init_small = { path = "../../utils/init/init_small" }
miscinit_seams = { path = "../../utils/init/miscinit_seams" }
