[package]
name = "rmgr"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "rmgr"
path = "src/lib.rs"

[dependencies]
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
mcx = { path = "../../../../_support/mcx" }
stringinfo = { path = "../../../../_support/types/stringinfo" }
elog = { path = "../../../utils/error/elog" }
xlogreader_seams = { path = "../xlogreader_seams" }
relmapper = { path = "../../../utils/cache/relmapper" }
clog = { path = "../clog" }
multixact = { path = "../multixact" }
transam_xlog_seams = { path = "../transam_xlog_seams" }
storage_xlog = { path = "../../../catalog/storage_xlog" }
standby = { path = "../../../storage/ipc/standby" }
heapam_xlog = { path = "../../heap/heapam_xlog" }
nbtree_xlog = { path = "../../nbtree/nbtree_xlog" }
xact = { path = "../xact" }
