#!/usr/bin/env python3
"""stub:syscache-row harvest — regenerate src/stub_syscache_harvest.rs.

Pulls REAL catalog rows from a live server (default: the dev server on
port 5433, whose catalog is initdb'd from the same 18.3 .dat pins the
vendored C uses) so the facility's constructor domain is witnessed
REACHABLE rather than invented (band-2 obligation; docs/design/
phase2-plan.md section 8 Q7).

Slice harvested (bounded, curated for the two migrated lanes + the
lsyscache single-probe family):
  pg_amop/pg_amproc : brin bloom/minmax_multi families 4572/4602/4603/4614
                      + btree integer_ops(1976)/text_ops(1994)
  pg_operator       : every oid referenced by harvested amop.amopopr
  pg_opclass        : opclasses of the harvested families
  pg_type           : the 13 types the lanes + common probes touch
  pg_attribute      : pg_class (1259) attnums 1..8
  pg_proc           : every oid referenced by harvested amproc.amproc +
                      operator.oprcode

Usage: python3 harvest_syscache.py [conninfo] > src/stub_syscache_harvest.rs
Default conninfo: host=/tmp port=5433 user=postgres dbname=postgres
"""
import subprocess, sys

CONN = sys.argv[1] if len(sys.argv) > 1 else "host=/tmp port=5433 user=postgres dbname=postgres"
FAMS = "(4572,4602,4603,4614,1976,1994)"
TYPES = "(16,18,19,20,21,23,25,26,700,701,1700,2950,2277)"


def q(sql):
    out = subprocess.run(
        ["psql", CONN, "-Atc", sql], capture_output=True, text=True, check=True
    ).stdout
    return [line.split("|") for line in out.splitlines() if line]


def b(v):  # bool
    return "true" if v == "t" else "false"


def ch(v):  # single char -> i8 ascii (empty = 0)
    return str(ord(v[0])) if v else "0"


amop = q(f"select amopfamily,amoplefttype,amoprighttype,amopstrategy,amoppurpose,"
         f"amopopr,amopmethod,amopsortfamily from pg_amop where amopfamily in {FAMS} "
         f"order by amopfamily,amoplefttype,amoprighttype,amopstrategy")
amproc = q(f"select amprocfamily,amproclefttype,amprocrighttype,amprocnum,amproc::oid "
           f"from pg_amproc where amprocfamily in {FAMS} "
           f"order by amprocfamily,amproclefttype,amprocrighttype,amprocnum")
oper = q(f"select o.oid,o.oprnamespace,o.oprleft,o.oprright,o.oprresult,o.oprcom,"
         f"o.oprnegate,o.oprcode::oid,o.oprrest::oid,o.oprjoin::oid,o.oprcanmerge,"
         f"o.oprcanhash from pg_operator o where o.oid in "
         f"(select amopopr from pg_amop where amopfamily in {FAMS}) order by o.oid")
opclass = q(f"select c.oid,c.opcmethod,c.opcfamily,c.opcintype,c.opckeytype "
            f"from pg_opclass c where c.opcfamily in {FAMS} order by c.oid")
typ = q(f"select t.oid,t.typlen,t.typbyval,t.typalign,t.typstorage,t.typcollation,"
        f"t.typinput::oid,t.typoutput::oid,t.typreceive::oid,t.typsend::oid,"
        f"t.typmodin::oid,t.typmodout::oid,t.typelem,t.typdelim,t.typisdefined "
        f"from pg_type t where t.oid in {TYPES} order by t.oid")
att = q("select attrelid,attnum,attname,atttypid,atttypmod,attcollation,attgenerated "
        "from pg_attribute where attrelid=1259 and attnum between 1 and 8 order by attnum")
proc = q(f"select p.oid,p.pronamespace,p.prorettype,p.provariadic,p.prosupport::oid,"
         f"p.prolang,p.pronargs,p.prokind,p.provolatile,p.proparallel,p.proretset,"
         f"p.proisstrict,p.proleakproof,p.prosecdef,(p.proconfig is null) "
         f"from pg_proc p where p.oid in (select amproc from pg_amproc where "
         f"amprocfamily in {FAMS} union select oprcode::oid from pg_operator where oid in "
         f"(select amopopr from pg_amop where amopfamily in {FAMS})) order by p.oid")

ver = q("select version()")[0][0]

w = sys.stdout.write
w(f"""//! GENERATED by fuzz/core/harvest_syscache.py — DO NOT EDIT BY HAND.
//!
//! REAL catalog rows harvested from a live server (reachability witness for
//! the stub:syscache-row constructor domain; see stub_syscache.rs and
//! fuzz/STUBS.md). Regenerate with:
//!   python3 fuzz/core/harvest_syscache.py > fuzz/core/src/stub_syscache_harvest.rs
//!
//! Provenance: `{ver}`
//! (dev server, catalog initdb'd from the PostgreSQL 18.3 .dat pins the
//! vendored C oracle uses).

use crate::stub_syscache::*;

""")
w(f"pub const HARVEST_AMOP: [AmopRow; {len(amop)}] = [\n")
for r in amop:
    w(f"    AmopRow {{ amopfamily: {r[0]}, amoplefttype: {r[1]}, amoprighttype: {r[2]}, "
      f"amopstrategy: {r[3]}, amoppurpose: {ch(r[4])}, amopopr: {r[5]}, "
      f"amopmethod: {r[6]}, amopsortfamily: {r[7]} }},\n")
w("];\n\n")
w(f"pub const HARVEST_AMPROC: [AmprocRow; {len(amproc)}] = [\n")
for r in amproc:
    w(f"    AmprocRow {{ amprocfamily: {r[0]}, amproclefttype: {r[1]}, "
      f"amprocrighttype: {r[2]}, amprocnum: {r[3]}, amproc: {r[4]} }},\n")
w("];\n\n")
w(f"pub const HARVEST_OPERATOR: [OperatorRow; {len(oper)}] = [\n")
for r in oper:
    w(f"    OperatorRow {{ oid: {r[0]}, oprnamespace: {r[1]}, oprleft: {r[2]}, "
      f"oprright: {r[3]}, oprresult: {r[4]}, oprcom: {r[5]}, oprnegate: {r[6]}, "
      f"oprcode: {r[7]}, oprrest: {r[8]}, oprjoin: {r[9]}, "
      f"oprcanmerge: {b(r[10])}, oprcanhash: {b(r[11])} }},\n")
w("];\n\n")
w(f"pub const HARVEST_OPCLASS: [OpclassRow; {len(opclass)}] = [\n")
for r in opclass:
    w(f"    OpclassRow {{ oid: {r[0]}, opcmethod: {r[1]}, opcfamily: {r[2]}, "
      f"opcintype: {r[3]}, opckeytype: {r[4]} }},\n")
w("];\n\n")
w(f"pub const HARVEST_TYPE: [TypeRow; {len(typ)}] = [\n")
for r in typ:
    w(f"    TypeRow {{ oid: {r[0]}, typlen: {r[1]}, typbyval: {b(r[2])}, "
      f"typalign: {ch(r[3])}, typstorage: {ch(r[4])}, typcollation: {r[5]}, "
      f"typinput: {r[6]}, typoutput: {r[7]}, typreceive: {r[8]}, typsend: {r[9]}, "
      f"typmodin: {r[10]}, typmodout: {r[11]}, typelem: {r[12]}, "
      f"typdelim: {ch(r[13])}, typisdefined: {b(r[14])} }},\n")
w("];\n\n")
w(f"pub const HARVEST_ATTRIBUTE: [AttributeRow; {len(att)}] = [\n")
for r in att:
    name = r[2].encode()[:63]
    arr = ", ".join(str(c) for c in name)
    pad = 64 - len(name)
    w(f"    AttributeRow {{ attrelid: {r[0]}, attnum: {r[1]}, "
      f"attname: attname_from_bytes(&[{arr}]), atttypid: {r[3]}, "
      f"atttypmod: {r[4]}, attcollation: {r[5]}, attgenerated: {ch(r[6])} }},\n")
w("];\n\n")
w(f"pub const HARVEST_PROC: [ProcRow; {len(proc)}] = [\n")
for r in proc:
    w(f"    ProcRow {{ oid: {r[0]}, pronamespace: {r[1]}, prorettype: {r[2]}, "
      f"provariadic: {r[3]}, prosupport: {r[4]}, prolang: {r[5]}, pronargs: {r[6]}, "
      f"prokind: {ch(r[7])}, provolatile: {ch(r[8])}, proparallel: {ch(r[9])}, "
      f"proretset: {b(r[10])}, proisstrict: {b(r[11])}, proleakproof: {b(r[12])}, "
      f"prosecdef: {b(r[13])}, proconfig_isnull: {b(r[14])} }},\n")
w("];\n")
