[package]
name = "seams_init"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "seams_init"
path = "src/lib.rs"

[dependencies]
sequence = { path = "../../backend/commands/sequence" }
detoast = { path = "../../backend/access/common/detoast" }
heaptoast = { path = "../../backend/access/heap/heaptoast" }
printtup = { path = "../../backend/access/common/printtup" }
relation = { path = "../../backend/access/common/relation" }
heapam_visibility = { path = "../../backend/access/heap/heapam_visibility" }
genam = { path = "../../backend/access/index/genam" }
indexam = { path = "../../backend/access/index/indexam" }
table = { path = "../../backend/access/table/table" }
tableam = { path = "../../backend/access/table/tableam" }
vacuumlazy = { path = "../../backend/access/heap/vacuumlazy" }
commands_vacuum = { path = "../../backend/commands/vacuum" }
commands_tablespace = { path = "../../backend/commands/tablespace" }
clog = { path = "../../backend/access/transam/clog" }
multixact = { path = "../../backend/access/transam/multixact" }
rmgr = { path = "../../backend/access/transam/rmgr" }
subtrans = { path = "../../backend/access/transam/subtrans" }
transam_xlog = { path = "../../backend/access/transam/transam_xlog" }
transam = { path = "../../backend/access/transam/transam" }
varsup = { path = "../../backend/access/transam/varsup" }
xact = { path = "../../backend/access/transam/xact" }
xloginsert = { path = "../../backend/access/transam/xloginsert" }
xlogreader = { path = "../../backend/access/transam/xlogreader" }
xlogrecovery = { path = "../../backend/access/transam/xlogrecovery" }
xlogutils = { path = "../../backend/access/transam/xlogutils" }
aclchk = { path = "../../backend/catalog/aclchk" }
catalog_namespace = { path = "../../backend/catalog/catalog_namespace" }
catalog_dependency = { path = "../../backend/catalog/catalog_dependency" }
tablecmds = { path = "../../backend/commands/tablecmds" }
catalog_storage = { path = "../../backend/catalog/catalog_storage" }
catalog = { path = "../../backend/catalog/catalog" }
pg_database = { path = "../../backend/catalog/pg_database" }
pg_db_role_setting = { path = "../../backend/catalog/pg_db_role_setting" }
catalog_index = { path = "../../backend/catalog/catalog_index" }
indexcmds = { path = "../../backend/commands/indexcmds" }
dbcommands = { path = "../../backend/commands/dbcommands" }
executils = { path = "../../backend/executor/executils" }
execexpr = { path = "../../backend/executor/execexpr" }
execjunk = { path = "../../backend/executor/execjunk" }
execmain = { path = "../../backend/executor/execmain" }
execscan = { path = "../../backend/executor/execscan" }
nodeseqscan = { path = "../../backend/executor/nodeseqscan" }
nodeindexscan = { path = "../../backend/executor/nodeindexscan" }
nodeindexonlyscan = { path = "../../backend/executor/nodeindexonlyscan" }
nodeagg = { path = "../../backend/executor/nodeagg" }
nodewindowagg = { path = "../../backend/executor/nodewindowagg" }
nodesort = { path = "../../backend/executor/nodesort" }
nodeunique = { path = "../../backend/executor/nodeunique" }
nodelimit = { path = "../../backend/executor/nodelimit" }
nodelockrows = { path = "../../backend/executor/nodelockrows" }
nodenestloop = { path = "../../backend/executor/nodenestloop" }
nodemergejoin = { path = "../../backend/executor/nodemergejoin" }
nodematerial = { path = "../../backend/executor/nodematerial" }
tuplesort = { path = "../../backend/utils/sort/tuplesort" }
auth = { path = "../../backend/libpq/auth" }
be_secure = { path = "../../backend/libpq/be_secure" }
hba = { path = "../../backend/libpq/hba" }
libpq_pqsignal = { path = "../../backend/libpq/libpq_pqsignal" }
pqcomm = { path = "../../backend/libpq/pqcomm" }
pqformat = { path = "../../backend/libpq/pqformat" }
vars = { path = "../../backend/optimizer/util/vars" }
parser_driver = { path = "../../backend/parser/parser_driver" }
parse_collate = { path = "../../backend/parser/parse_collate" }
parse_clause = { path = "../../backend/parser/parse_clause" }
parse_expr = { path = "../../backend/parser/parse_expr" }
parser_analyze = { path = "../../backend/parser/parser_analyze" }
scan_fgram = { path = "../../backend/parser/scan_fgram" }
interrupt = { path = "../../backend/postmaster/interrupt" }
launch_backend = { path = "../../backend/postmaster/launch_backend" }
pmchild = { path = "../../backend/postmaster/pmchild" }
postmaster = { path = "../../backend/postmaster/postmaster" }
auxprocess = { path = "../../backend/postmaster/auxprocess" }
checkpointer = { path = "../../backend/postmaster/checkpointer" }
bgwriter = { path = "../../backend/postmaster/bgwriter" }
walwriter = { path = "../../backend/postmaster/walwriter" }
postmaster_startup = { path = "../../backend/postmaster/startup" }
rewrite_handler = { path = "../../backend/rewrite/rewrite_handler" }
bufmgr = { path = "../../backend/storage/buffer/bufmgr" }
fd = { path = "../../backend/storage/file/fd" }
dsm_core = { path = "../../backend/storage/ipc/dsm_core" }
ipc = { path = "../../backend/storage/ipc/ipc" }
ipci = { path = "../../backend/storage/ipc/ipci" }
latch = { path = "../../backend/storage/ipc/latch" }
pmsignal = { path = "../../backend/storage/ipc/pmsignal" }
procarray = { path = "../../backend/storage/ipc/procarray" }
procsignal = { path = "../../backend/storage/ipc/procsignal" }
shmem = { path = "../../backend/storage/ipc/shmem" }
sinval = { path = "../../backend/storage/ipc/sinval" }
waiteventset = { path = "../../backend/storage/ipc/waiteventset" }
lmgr_proc = { path = "../../backend/storage/lmgr/lmgr_proc" }
s_lock = { path = "../../backend/storage/lmgr/s_lock" }
standby = { path = "../../backend/storage/ipc/standby" }
condition_variable = { path = "../../backend/storage/lmgr/condition_variable" }
deadlock = { path = "../../backend/storage/lmgr/deadlock" }
predicate = { path = "../../backend/storage/lmgr/predicate" }
parallel = { path = "../../backend/access/transam/parallel" }
spi = { path = "../../backend/executor/spi" }
trigger = { path = "../../backend/commands/trigger" }
ri_triggers = { path = "../../backend/utils/adt/ri_triggers" }
pruneheap = { path = "../../backend/access/heap/pruneheap" }
pg_string = { path = "../../common/string" }
lmgr = { path = "../../backend/storage/lmgr/lmgr" }
lock = { path = "../../backend/storage/lmgr/lock" }
smgr = { path = "../../backend/storage/smgr/smgr" }
sync = { path = "../../backend/storage/sync/sync" }
freespace = { path = "../../backend/storage/freespace/freespace" }
backend_startup = { path = "../../backend/tcop/backend_startup" }
tcop_dest = { path = "../../backend/tcop/dest" }
postgres = { path = "../../backend/tcop/postgres" }
pquery = { path = "../../backend/tcop/pquery" }
explain = { path = "../../backend/commands/explain" }
prepare = { path = "../../backend/commands/prepare" }
commands_async = { path = "../../backend/commands/commands_async" }
portalcmds = { path = "../../backend/commands/portalcmds" }
utility = { path = "../../backend/tcop/utility" }
backend_status = { path = "../../backend/utils/activity/backend_status" }
waitevent = { path = "../../backend/utils/activity/waitevent" }
pgstat = { path = "../../backend/utils/activity/pgstat" }
adt_acl = { path = "../../backend/utils/adt/acl" }
adt_misc = { path = "../../backend/utils/adt/adt_misc" }
adt_timestamp = { path = "../../backend/utils/adt/adt_timestamp" }
pgtz = { path = "../../backend/timezone/pgtz" }
adt_bool = { path = "../../backend/utils/adt/bool" }
arrayfuncs = { path = "../../backend/utils/adt/arrayfuncs" }
adt_float = { path = "../../backend/utils/adt/float" }
pg_locale = { path = "../../backend/utils/adt/pg_locale" }
varlena = { path = "../../backend/utils/adt/varlena" }
cache_syscache = { path = "../../backend/utils/cache/cache_syscache" }
catcache = { path = "../../backend/utils/cache/catcache" }
inval = { path = "../../backend/utils/cache/inval" }
lsyscache = { path = "../../backend/utils/cache/lsyscache" }
plancache = { path = "../../backend/utils/cache/plancache" }
planner = { path = "../../backend/optimizer/plan/planner" }
relcache = { path = "../../backend/utils/cache/relcache" }
relcache_build = { path = "../../backend/utils/cache/relcache_build" }
relmapper = { path = "../../backend/utils/cache/relmapper" }
typcache = { path = "../../backend/utils/cache/typcache" }
elog = { path = "../../backend/utils/error/elog" }
fmgr_core = { path = "../../backend/utils/fmgr/fmgr_core" }
funcapi = { path = "../../backend/utils/fmgr/funcapi" }
init_small = { path = "../../backend/utils/init/init_small" }
miscinit = { path = "../../backend/utils/init/miscinit" }
mbutils = { path = "../../backend/utils/mb/mbutils" }
conffiles = { path = "../../backend/utils/misc/conffiles" }
guc_file = { path = "../../backend/utils/misc/guc_file" }
guc_tables = { path = "../../backend/utils/misc/guc_tables" }
guc = { path = "../../backend/utils/misc/guc" }
guc_funcs = { path = "../../backend/utils/misc/guc_funcs" }
variable = { path = "../../backend/commands/variable" }
ps_status = { path = "../../backend/utils/misc/ps_status" }
queryenvironment = { path = "../../backend/utils/misc/queryenvironment" }
stack_depth = { path = "../../backend/utils/misc/stack_depth" }
superuser = { path = "../../backend/utils/misc/superuser" }
timeout = { path = "../../backend/utils/misc/timeout" }
tuplestore = { path = "../../backend/utils/sort/tuplestore" }
resowner = { path = "../../backend/utils/resowner/resowner" }
combocid = { path = "../../backend/utils/time/combocid" }
snapmgr = { path = "../../backend/utils/time/snapmgr" }
pg_prng = { path = "../../common/pg_prng" }
regex_core = { path = "../../backend/regex/regex_core" }
adt_regexp = { path = "../../backend/utils/adt/regexp" }
twophase_config = { path = "../../backend/access/transam/twophase_config" }
pg_sema = { path = "../../backend/port/pg_sema" }
autovacuum = { path = "../../backend/postmaster/autovacuum" }
syslogger = { path = "../../backend/postmaster/syslogger" }
launcher = { path = "../../backend/replication/launcher" }
walsender_config = { path = "../../backend/replication/walsender_config" }
slot = { path = "../../backend/replication/slot" }
session = { path = "../../backend/access/session" }
relpath = { path = "../../common/relpath" }
aio_config = { path = "../../backend/storage/aio/aio_config" }
