[package]
name = "dbcommands"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "dbcommands"
path = "src/lib.rs"

[dependencies]
pgstat = { path = "../../utils/activity/pgstat" }
slot_seams = { path = "../../replication/slot_seams" }
types_core = { path = "../../../_support/types/types_core" }
types_error = { path = "../../../_support/types/types_error" }
types_nodes = { path = "../../../_support/types/nodes" }
types_rel = { path = "../../../_support/types/rel" }
types_scan = { path = "../../../_support/types/types_scan" }
types_storage = { path = "../../../_support/types/types_storage" }
types_tuple = { path = "../../../_support/types/types_tuple" }
datum = { path = "../../../_support/types/datum" }
mcx = { path = "../../../_support/mcx" }
libc = "0.2"
elog = { path = "../../utils/error/elog" }
cache_syscache = { path = "../../utils/cache/cache_syscache" }
dbcommands_seams = { path = "../dbcommands_seams" }
pg_database = { path = "../../catalog/pg_database" }
pg_database_seams = { path = "../../catalog/pg_database_seams" }
pg_depend = { path = "../../catalog/pg_depend" }
pg_shdepend = { path = "../../catalog/pg_shdepend" }
catalog = { path = "../../catalog/catalog" }
catalog_indexing = { path = "../../catalog/catalog_indexing" }
heaptuple = { path = "../../access/common/heaptuple" }
table = { path = "../../access/table/table" }
genam = { path = "../../access/index/genam" }
fmgr_seams = { path = "../../utils/fmgr/fmgr_seams" }
types_fmgr = { path = "../../../_support/types/fmgr" }
lmgr = { path = "../../storage/lmgr/lmgr" }
procarray = { path = "../../storage/ipc/procarray" }
procsignal = { path = "../../storage/ipc/procsignal" }
bufmgr = { path = "../../storage/buffer/bufmgr" }
smgr = { path = "../../storage/smgr/smgr" }
fd = { path = "../../storage/file/fd" }
checkpointer = { path = "../../postmaster/checkpointer" }
transam_xlog = { path = "../../access/transam/transam_xlog" }
xloginsert = { path = "../../access/transam/xloginsert" }
xlogutils = { path = "../../access/transam/xlogutils" }
xlogreader_seams = { path = "../../access/transam/xlogreader_seams" }
xact = { path = "../../access/transam/xact" }
relpath = { path = "../../../common/relpath" }
wchar = { path = "../../../common/wchar" }
mbutils = { path = "../../utils/mb/mbutils" }
pg_locale = { path = "../../utils/adt/pg_locale" }
adt_acl = { path = "../../utils/adt/acl" }
superuser = { path = "../../utils/misc/superuser" }
miscinit = { path = "../../utils/init/miscinit" }
init_small = { path = "../../utils/init/init_small" }
varlena = { path = "../../utils/adt/varlena" }
explain = { path = "../explain" }
numutils = { path = "../../utils/adt/numutils" }
guc_tables = { path = "../../utils/misc/guc_tables" }
xlogrecovery_seams = { path = "../../access/transam/xlogrecovery_seams" }
relmapper = { path = "../../utils/cache/relmapper" }
snapmgr = { path = "../../utils/time/snapmgr" }
commands_tablespace = { path = "../tablespace" }
aclchk = { path = "../../catalog/aclchk" }
pg_db_role_setting = { path = "../../catalog/pg_db_role_setting" }
guc_funcs = { path = "../../utils/misc/guc_funcs" }
heapam_visibility_seams = { path = "../../access/heap/heapam_visibility_seams" }
postgres_seams = { path = "../../tcop/postgres_seams" }
postmaster_seams = { path = "../../postmaster/postmaster_seams" }
standby = { path = "../../storage/ipc/standby" }
