[package]
name = "heaptoast_seams"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[dependencies]
seam_core = { path = "../../../../_support/seam_core" }
mcx = { path = "../../../../_support/mcx" }
types_error = { path = "../../../../_support/types/types_error" }
types_rel = { path = "../../../../_support/types/rel" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
heaptuple = { path = "../../common/heaptuple" }
