[package]
name = "proof-adt-misc"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
adt_misc = { path = "../../crates/backend/utils/adt/adt_misc" }
types_core = { path = "../../crates/_support/types/types_core" }
types_error = { path = "../../crates/_support/types/types_error" }
types_fmgr = { path = "../../crates/_support/types/fmgr" }
datum = { path = "../../crates/_support/types/datum" }
proof_support = { path = "../support" }

[package.metadata.kani.flags]
c-lib = ["c/pg_adt_misc.c"]
