/* Emits Rust parity vectors by running the real vendored pg_lzcompress.c.
 * Regenerate: clang -O2 -I tests/data/cref -o gen tests/data/gen_vectors.c \
 *   ../../../../pgrust-fabled/vendor/postgres-src/src/common/pg_lzcompress.c \
 *   && ./gen > tests/data/c_vectors.rs
 * NOTE: compressed streams depend on the platform's char signedness (the
 * pglz_hist_idx reads through `char`); this file records which signedness
 * produced them so the Rust side can gate byte-exact compress checks. */
#include <stdio.h>
#include <stdlib.h>
#include "postgres.h"
#include "common/pg_lzcompress.h"

static uint64_t prng;
static unsigned char next_byte(void)
{
	prng = prng * 6364136223846793005ULL + 1442695040888963407ULL;
	return (unsigned char) (prng >> 56);
}

/* Generators mirrored in tests/c_parity.rs — keep in sync. */
static void gen_input(const char *kind, unsigned char *buf, int n)
{
	prng = 0x243f6a8885a308d3ULL;
	if (strcmp(kind, "rep") == 0)
	{
		static const char phrase[] = "the quick brown fox jumps over a lazy dog #";
		for (int i = 0; i < n; i++)
			buf[i] = (unsigned char) phrase[i % (sizeof(phrase) - 1)];
	}
	else if (strcmp(kind, "zeros") == 0)
		memset(buf, 0, n);
	else if (strcmp(kind, "digits") == 0)
	{
		static const char digits[] = "0123456789.";
		for (int i = 0; i < n; i++)
			buf[i] = (unsigned char) digits[next_byte() % 11];
	}
	else if (strcmp(kind, "high") == 0)
	{
		for (int i = 0; i < n; i++)
			buf[i] = (unsigned char) (0x80 | (next_byte() % 7) * 17);
	}
	else if (strcmp(kind, "mixed") == 0)
	{
		/* random blocks with periodic replay of an earlier 24-byte window */
		for (int i = 0; i < n; i++)
			buf[i] = (i % 61 >= 37 && i >= 64) ? buf[i - 64] : next_byte();
	}
	else
	{
		fprintf(stderr, "unknown kind %s\n", kind);
		exit(1);
	}
}

static void emit_case(const char *kind, int n, const char *strat_name,
					  const PGLZ_Strategy *strat)
{
	unsigned char *buf = malloc(n);
	unsigned char *dst = malloc(PGLZ_MAX_OUTPUT(n));
	unsigned char *back = malloc(n);
	int32 clen, rlen;

	gen_input(kind, buf, n);
	clen = pglz_compress((const char *) buf, n, (char *) dst, strat);
	if (clen < 0)
	{
		fprintf(stderr, "SKIP %s/%d/%s: incompressible\n", kind, n, strat_name);
		free(buf); free(dst); free(back);
		return;
	}
	rlen = pglz_decompress((const char *) dst, clen, (char *) back, n, true);
	if (rlen != n || memcmp(back, buf, n) != 0)
	{
		fprintf(stderr, "C roundtrip failed for %s/%d\n", kind, n);
		exit(1);
	}

	printf("    Case { kind: \"%s\", rawsize: %d, strategy: \"%s\", compressed: &[\n        ",
		   kind, n, strat_name);
	for (int i = 0; i < clen; i++)
		printf("%u,%s", dst[i], (i % 20 == 19) ? "\n        " : " ");
	printf("\n    ] },\n");
	free(buf); free(dst); free(back);
}

int main(void)
{
	printf("// Generated by gen_vectors.c from the vendored pg_lzcompress.c — do not edit.\n");
	printf("pub const CHAR_IS_SIGNED: bool = %s;\n", (char) 0x80 < 0 ? "true" : "false");
	printf("pub struct Case { pub kind: &'static str, pub rawsize: i32, pub strategy: &'static str, pub compressed: &'static [u8] }\n");
	printf("pub const CASES: &[Case] = &[\n");
	emit_case("rep", 1024, "default", PGLZ_strategy_default);
	emit_case("rep", 8192, "default", PGLZ_strategy_default);
	emit_case("zeros", 1024, "default", PGLZ_strategy_default);
	emit_case("digits", 1024, "always", PGLZ_strategy_always);
	emit_case("digits", 8192, "always", PGLZ_strategy_always);
	emit_case("high", 2048, "always", PGLZ_strategy_always);
	emit_case("mixed", 1024, "always", PGLZ_strategy_always);
	emit_case("mixed", 8192, "always", PGLZ_strategy_always);
	printf("];\n");
	printf("pub const MAX_COMPRESSED_SIZE: &[(i32, i32, i32)] = &[\n");
	{
		int32 raws[] = {0, 1, 8, 100, 4096, 1000000000};
		int32 totals[] = {2, 100, 5000, 2000000000};
		for (unsigned i = 0; i < sizeof(raws) / sizeof(raws[0]); i++)
			for (unsigned j = 0; j < sizeof(totals) / sizeof(totals[0]); j++)
				printf("    (%d, %d, %d),\n", raws[i], totals[j],
					   pglz_maximum_compressed_size(raws[i], totals[j]));
	}
	printf("];\n");
	return 0;
}
