[package]
name = "tuplesort"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
adt_datetime = { path = "../../adt/adt_datetime" }
adt_float = { path = "../../adt/float" }
adt_timestamp = { path = "../../adt/adt_timestamp" }
mcx = { path = "../../../../_support/mcx" }
datum = { path = "../../../../_support/types/datum" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_slot = { path = "../../../../_support/types/types_slot" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
types_hash = { path = "../../../../_support/types/hash" }
types_nbtree = { path = "../../../../_support/types/types_nbtree" }
exectuples = { path = "../../../executor/exectuples" }
sort_storage = { path = "../sort_storage" }
heaptuple = { path = "../../../access/common/heaptuple" }
lsyscache = { path = "../../cache/lsyscache" }
types_rel = { path = "../../../../_support/types/rel" }
nbtree = { path = "../../../access/nbtree/nbtree" }
varlena = { path = "../../../utils/adt/varlena" }
adt_uuid = { path = "../../adt/uuid" }
adt_network = { path = "../../adt/network" }
adt_numeric = { path = "../../adt/numeric" }
pg_locale = { path = "../../adt/pg_locale" }
init_small = { path = "../../init/init_small" }
postgres_seams = { path = "../../../tcop/postgres_seams" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
types_gist = { path = "../../../../_support/types/gist" }
fmgr_seams = { path = "../../fmgr/fmgr_seams" }
detoast_seams = { path = "../../../access/common/detoast_seams" }
tuplesort_seams = { path = "../tuplesort_seams" }
genam_seams = { path = "../../../access/index/genam_seams" }

[dev-dependencies]
detoast = { path = "../../../access/common/detoast" }
pglz = { path = "../../../../common/pglz" }
guc_tables = { path = "../../misc/guc_tables" }
elog = { path = "../../error/elog" }
fd = { path = "../../../storage/file/fd" }
xact_seams = { path = "../../../access/transam/xact_seams" }
aio_seams = { path = "../../../storage/aio/aio_seams" }
waitevent_seams = { path = "../../activity/waitevent_seams" }
pgstat_seams = { path = "../../activity/pgstat_seams" }
ipc_seams = { path = "../../../storage/ipc/ipc_seams" }
resowner = { path = "../../resowner/resowner" }
resowner_seams = { path = "../../resowner/resowner_seams" }
types_resowner = { path = "../../../../_support/types/types_resowner" }
