// Generated by scripts/gen_radix_tables.py from postgres-18.3 C sources. Do not edit.
pub mod iso8859;
pub mod win;
pub mod cyrillic;
pub mod euc_cn;
pub mod euc_jp;
pub mod euc_kr;
pub mod euc_tw;
pub mod big5;
pub mod gbk;
pub mod uhc;
pub mod johab;
pub mod sjis;
pub mod gb18030;
pub mod euc2004;
pub mod sjis2004;
pub mod local_tables;
