[package]
name = "planner"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
execmain = { path = "../../../executor/execmain" }
nodes_core = { path = "../../../nodes/nodes_core" }
parse_relation = { path = "../../../parser/parse_relation" }
mcx = { path = "../../../../_support/mcx" }
datum = { path = "../../../../_support/types/datum" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_nodes = { path = "../../../../_support/types/nodes" }
types_pathnodes = { path = "../../../../_support/types/pathnodes" }
types_portal = { path = "../../../../_support/types/portal" }
planner_seams = { path = "../planner_seams" }
backend_status_seams = { path = "../../../utils/activity/backend_status_seams" }
adt_int8 = { path = "../../../utils/adt/int8" }
clauses = { path = "../../util/clauses" }
fmgr_core = { path = "../../../utils/fmgr/fmgr_core" }
types_fmgr = { path = "../../../../_support/types/fmgr" }
lsyscache = { path = "../../../utils/cache/lsyscache" }
guc_tables = { path = "../../../utils/misc/guc_tables" }
init_small = { path = "../../../utils/init/init_small" }
tidbitmap = { path = "../../../nodes/tidbitmap" }
types_rel = { path = "../../../../_support/types/rel" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
types_relscan = { path = "../../../access/index/relscan" }
syscache_seams = { path = "../../../utils/cache/syscache_seams" }
relcache_seams = { path = "../../../utils/cache/relcache_seams" }
bufmgr_seams = { path = "../../../storage/buffer/bufmgr_seams" }
table = { path = "../../../access/table/table" }
tableam = { path = "../../../access/table/tableam" }
indexam = { path = "../../../access/index/indexam" }
nbtree = { path = "../../../access/nbtree/nbtree" }
nodeagg = { path = "../../../executor/nodeagg" }
nodehash = { path = "../../../executor/nodehash" }
vars = { path = "../../util/vars" }

[dev-dependencies]
clauses_seams = { path = "../../util/clauses_seams" }
relcache = { path = "../../../utils/cache/relcache" }
relcache_build_seams = { path = "../../../utils/cache/relcache_build_seams" }
relation_seams = { path = "../../../access/common/relation_seams" }
types_nbtree = { path = "../../../../_support/types/types_nbtree" }
