[package]
name = "predicate"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "predicate"
path = "src/lib.rs"

[dependencies]
predicate_seams = { path = "../predicate_seams" }
types_core = { path = "../../../../_support/types/types_core" }
types_error = { path = "../../../../_support/types/types_error" }
types_rel = { path = "../../../../_support/types/rel" }
types_snapshot = { path = "../../../../_support/types/snapshot" }
types_tuple = { path = "../../../../_support/types/types_tuple" }
